tilt-dev/tilt

internal/cloud/cloud_username_manager.go
This reverts commit 4846be75a75e00f62fb342e4b623ea770324d63f.
=> Revert "tilt cloud: don't log http.Response.String() (#2240)"

integration/analytics_test.go, internal/tiltfile/tiltfile.go
would have been better to have this metric in place so we could better
compare the effect that LocalResource had on it whoops, but I think
it's still good to keep an eye on, and may give us useful info --
we can at least see if the second round of LocalResource reduces tiltfile
load times at all.
=> tiltfile: record tiltfile load time

internal/engine/configs/actions.go, internal/engine/configs/configs_controller.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/webview/convert_test.go, internal/store/actions.go, pkg/model/log.go, pkg/model/log_test.go
Please review the following commits I made in branch nicks/ch3434/secrets:
c20a75171cb0e71009d56c25edc767c821c60a1a (2019-09-24 12:56:23 -0400)
engine: redact secrets from the log
a0f815816a3ffdcc8b8ab9b84bf1ea1b8617a7d0 (2019-09-23 17:51:09 -0400)
engine: load secrets into the engine state
=> engine: redact secrets from the log

internal/cli/build.go, scripts/install.sh
Please review the following commits I made in branch maiamcc/bump-0.10.9:
a2ec4d7c45927b083b5e4d643bc00cdc5ffce24f (2019-09-24 16:07:23 -0400)
bump version to 0.10.9
=> bump version to 0.10.9

internal/engine/build_errors.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/renderer.go, internal/hud/view/view.go, internal/store/engine_state.go, internal/store/store.go, internal/store/store_test.go, internal/store/subscriber_test.go
Looks like this:
If a permanent, now called "fatal", error happens the Upper loop stops but the UI stays up and you can still browse through it.
Nothing is displayed in the web UI, and I'm not sure if that's a feature or a bug.
=> store: "permanent" errors dont close ui

internal/hud/webview/convert.go, internal/hud/webview/testdata/snapshot.json, internal/hud/webview/view.go, web/src/AppController.ts, web/src/FatalErrorModal.scss, web/src/FatalErrorModal.test.tsx, web/src/FatalErrorModal.tsx, web/src/HUD.tsx, web/src/__snapshots__/FatalErrorModal.test.tsx.snap, web/src/types.ts
=> web: show fatal error as a modal in web UI

internal/tiltfile/features.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Once we enable snapshots in the UI, an organization might prefer to not have a "share snapshot" button there encouraging their devs to upload their data to TiltCloud.
Add a `disable_snapshots` directive that allows a Tiltfile to specify that a project shouldn't give users a "share snapshot" button.
Notes:
1. Maybe at some point we'll want a second `disable_feature` that's meant for long-term use, but I'm leaning against taking on that as part of the snapshots release. If people feel strongly that we should solve the more general problem, we can talk about that.
2. This isn't any form of security since obviously a user could simply comment it out. It's basically just allowing people to take away an attractive nuisance.
3. `disable_feature` already provides this affordance, but the feature …
=> tiltfile: add disable_snapshots

web/src/ShareSnapshotModal.scss
Hello @nicks,
Please review the following commits I made in branch nicks/styles:
91247c7a62c80a74820fa4db1a549bcdf5df48ce (2019-09-30 11:11:52 -0400)
add a class for precendence when css gets loaded out of order
=> add a class for precendence when css gets loaded out of order

Makefile
I tried running the partial goimports command output by make. It ran and then
hung for a very long time.
Instead, suggest running `make goimports`.
=> More helpful message from verify_goimports target

internal/synclet/sidecar/sidecar.go
This is the least invasive way I could think of to plumb a custom image name through, since command line parsing happens far from the `sidecar` package.
Given how `SyncletContainer` is built (once per execution), the only simple test would be for `getImageName()` and that would be trivial, hence no new tests.
All of the above to say that this could be a more complex change, but I will wait until the owners state a preference (if any).
=> Let TILT_SYNCLET_IMAGE variable override Docker image

internal/engine/buildcontroller.go, internal/engine/local_target_build_and_deployer.go
Please review the following commits I made in branch maiamcc/race-cond:
d5e5c75e2ecfdad876e5d518702feccfad7da0bb (2019-09-26 17:13:36 -0400)
engine: sleep a bit after initial build of local resource to avoid race condition
=> engine: sleep a bit after initial build of local resource to avoid race condition [ch3559]

Makefile
Let's say you want to build a private synclet image and you want to build it with an arbitrary tag that matches an existing tilt binary, not the current date... this change allows you to do that.
=> New custom-synclet-release target to push to custom registry with custom tag

internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go, internal/k8s/fake_client.go
Please review the following commits I made in branch nicks/issue2263:
d2399277ea96dbf89abfc608abd168c36ee9235c (2019-10-01 14:47:01 -0400)
engine: start streaming pod log at tthe tilt start time. fixes issue #2263
=> engine: start streaming pod log at tthe tilt start time. fixes issue #2263

scripts/upload-assets.py
Dan fixed a couple of omissions, but the actual upload's exit code was still unchecked.
> subprocess.check_call(args, *, stdin=None, stdout=None, stderr=None, shell=False)
> Run command with arguments. Wait for command to complete. If the return code was zero then return, otherwise raise CalledProcessError. The CalledProcessError object will have the return code in the returncode attribute.
=> upload_assets: use subprocess.check_call

internal/tiltfile/docker.go, internal/tiltfile/docker_test.go
Please review the following commits I made in branch nicks/issue2296/dockerignore:
f1ca72c69aaf2d6dc4d6ceaab91400583cd6637b (2019-10-03 16:36:03 -0700)
tiltfile: don't pick up dockerignores from sync() directories.
confirmed that this test passed before https://github.com/windmilleng/tilt/pull/2256 but failed afterwards
attempt at fixing issue #2296
=> tiltfile: don't pick up dockerignores from sync() directories.

internal/tiltfile/include.go, internal/tiltfile/include_test.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/issue2271:
5063b7bd6603a01bdf2f29ef4fa5c42de205ba98 (2019-10-04 12:28:47 -0700)
tiltfile: improve stack traces for include()
=> tiltfile: improve stack traces for include()

internal/build/container_test.go, internal/build/options.go, internal/build/test_utils.go, internal/docker/client.go, internal/docker/options.go, internal/engine/image_build_and_deployer_test.go
Please review the following commits I made in branch maiamcc/label-images:
877d89e565eb86180df12ce810f3e301e71c1ef6 (2019-10-07 17:26:27 -0400)
build: label all docker images with builtby:tilt [ch3659]
=> build: label all docker images with builtby:tilt [ch3659]

pkg/logger/deferred.go, pkg/logger/deferred_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/deferred:
edf3fe06cc49122cd91dcf1f1cb5b9531e6f472d (2019-10-07 20:50:17 -0400)
logger: fix a logger that wasn't copying bytes correctly
=> logger: fix a logger that wasn't copying bytes correctly

internal/engine/live_update_build_and_deployer.go
Hello @landism, @dbentley,
Please review the following commits I made in branch maiamcc/silent-redirect-live-update:
061f1c4515c25c935b660bb7122c6d1d21bbb2e3 (2019-10-10 11:21:53 -0400)
engine: if no targets for LiveUpdate found, redirect SILENTLY (the user doesn't care about this)
=> engine: if no targets for LiveUpdate found, redirect SILENTLY (the user doesn't care about this)

Gopkg.lock, integration/fixture_test.go, internal/cli/cli.go, internal/cli/kubectl.go, vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go, vendor/k8s.io/component-base/cli/flag/colon_separated_multimap_string_string.go, vendor/k8s.io/component-base/cli/flag/configuration_map.go, vendor/k8s.io/component-base/cli/flag/flags.go, vendor/k8s.io/component-base/cli/flag/langle_separated_map_string_string.go, vendor/k8s.io/component-base/cli/flag/map_string_bool.go, vendor/k8s.io/component-base/cli/flag/map_string_string.go, vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go, vendor/k8s.io/component-base/cli/flag/noop.go, vendor/k8s.io/component-base/cli/flag/omitempty.go, vendor/k8s.io/component-base/cli/flag/sectioned.go, vendor/k8s.io/component-base/cli/flag/string_flag.go, vendor/k8s.io/component-base/cli/flag/tristate.go, vendor/k8s.io/kubectl/pkg/util/logs/logs.go
Please review the following commits I made in branch nicks/klog2:
6f328d32d4b4e5fa5201bea08c1f5c12eda27ed9 (2019-10-10 17:29:25 -0400)
kubectl: fix initialization of 'tilt kubectl' so that verbose logging works
=> kubectl: fix initialization of 'tilt kubectl' so that verbose logging works

Gopkg.toml, internal/docker/client.go
Please review the following commits I made in branch maiamcc/docker-api-negotiation:
6f5397cf624d2d0a15e7c0e0d3eaee3261fcccfe (2019-10-10 18:19:19 -0400)
docker: use new WithAPIVersionNegotiation Opt to actually negotiate API version w/ server instead of erroring
in the old code, we applied `NegotiateAPIVersion` as an opt, i.e. a
function that we ran the `Client` through when we were creating it.
This resulted in us trying to negotiate with the server--which involved
pinging the server--before we had set a scheme on the `Client` (which
happens later in the client creation process). This, the API negotiation
always failed silently, and we would set the lowest possible version on
the client.
c02e957fd47ffe53e23481e8a96110f7fd902855 (2019-10-10 18:17:42 -0400)
rm …
=> docker: use new WithAPIVersionNegotiation Opt to actually negotiate API version w/ server instead of erroring

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/pod.go, internal/engine/portforwardcontroller.go, internal/engine/runtimelog/actions.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/runtimelog/podlogmanager_test.go, internal/engine/runtimelog/reader.go, internal/engine/subscribers.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/version_checker_test.go
Please review the following commits I made in branch nicks/runtimelog:
b75d24ab1e41342646b2dcc91259fbc39a41c5d2 (2019-10-11 16:05:08 -0400)
engine: put the log managers into their own subpackage
=> engine: put the log managers into their own subpackage

web/src/LogPane.scss, web/src/ResourceInfo.scss, web/src/ResourceInfo.tsx
A previous [refactor PR](https://github.com/windmilleng/tilt/pull/2329) messed up some of the CSS for LogPane. This fixes it so the padding and margins are correct again.
=> Fix LogPane layout

internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/engine/upper_test.go, internal/store/engine_state.go, pkg/model/docker_prune.go
Please review the following commits I made in branch maiamcc/dp-use-settings:
7daad87da01bfbc7bf5ad4eb8e5c80266ae76391 (2019-10-14 20:50:18 -0400)
log something if version insufficient to prune
8f1cf91a58da6c1223cd8c4e524dd3f3c488b770 (2019-10-14 20:12:11 -0400)
dockerprune: use state.dockerPruneSettings to dictate when/how we prune
=> dockerprune: use state.dockerPruneSettings to dictate when/how we prune

internal/docker/client.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/tiltfile/tiltfile_test.go
If someone is using Tilt against a cloud cluster, it's not enough to run `docker image prune` -- Image X may be running a container in the cloud, but the local docker daemon doesn't know about it and thinks it's prune-able, but we DON'T want that, as the user is probably actively developing on it.
alternative: list all tilt-built images, and check "last tagged" metadata for a more accurate picture of when the image was last updated; only delete those images where it was last tagged sufficiently long ago.
=> dockerprune: instead of docker.ImagesPrune, only remove tilt-built images with lastTag younger than MaxAge [ch3707]

internal/tiltfile/dockerprune/docker_prune.go, internal/tiltfile/dockerprune/docker_prune_test.go, internal/tiltfile/k8scontext/k8scontext.go, internal/tiltfile/k8scontext/k8scontext_test.go
Please review the following commits I made in branch nicks/k8scontext:
17b2e34f0c0a894d7f86b8404cefd689322a3083 (2019-10-15 13:52:26 -0400)
tiltfile: extensions should reset state in OnStart
=> tiltfile: extensions should reset state in OnStart

internal/cli/docker_prune.go, internal/container/container.go, internal/container/selector.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go
it was a pain to run tilt.build b/c the docker pruner on a servantes run had pruned away
all my tilt.build images/caches
with this PR, the docker pruner only prunes images matching refs currently being run.
I BELIEVE this will mean that we only prune docker caches corresponding to those images -- b/c we're not pruning dangling caches, so we shouldn't delete any that relate to extant images? lmk if this is wrong.
for future PR: apply this behavior to `tilt docker-prune` so it gives an accurate preview
=> dockerprune: only prune images if they match a running manifest

internal/cli/docker_prune.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, pkg/model/manifest.go
`tilt docker-prune` does a docker prune as tilt would (respecting manifests defined in
this dir's tiltfile, etc.)
=> cli: make docker-prune cli behavior consistent, make logs useful

internal/cloud/update_uploader.go, internal/cloud/update_uploader_test.go
jsonpb expects durations and timestamps to be strings.
We could use the jsonpb json marshaler instead of special-casing the duration and timestamp, but that only converts from proto messages to json, so then we'd have to pull the usage proto into tilt.
=> cloud: put_updates: log non-200, match server api

internal/cloud/update_uploader.go, internal/cloud/update_uploader_test.go
bug: when we look for builds to upload, we iterate in reverse chron until we hit a timestamp prior to the last build we uploaded. This means that we include the last build we uploaded, even though we already uploaded it!
=> cloud: fix watermark check in update upload

internal/feature/flags.go, web/src/HUD.tsx, web/src/LogPane.test.tsx, web/src/LogPane.tsx
We haven't cut a release with this flag, so I'm removing it entirely. (Instead of setting it to `Noop` → `Obsolete`, which seems too scrupulous for this case.)
=> Make snapshot highlights default behavior

internal/k8s/registry_test.go
I'm not sure if there's a good way to run more of these on macos. At least this gets us compilation, and they'll still run in CI.
=> k8s: make registry tests linux-only

internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/entity.go, internal/k8s/entity_test.go, internal/k8s/target.go, internal/k8s/target_test.go, internal/k8s/testyaml/testyaml.go
follow-up to #2364 -- as of that PR we apply the k8s entities in the correct order,
but only sort them just before `apply`ing, so log output still reflects the
unsorted order. e.g. even though we applied `PersistentVolumes` before
`PersistentVolumeClaims`, logs would show:
```
──┤ Building: uncategorized ├──────────────────────────────────────────────
STEP 1/1 — Deploying
│ Injecting images into Kubernetes YAML
│ Applying via kubectl:
│    task-pv-claim:persistentvolumeclaim
│    task-pv-volume:persistentvolume
```
with this PR, we now sort sort YAML entities into safe application order
(i.e. make our best guess as to resources that other resources will depend
on, and put those first) _at the time of manifest creation_. Thus we no
longer need to sort just before calling `apply`, and …
=> k8s: sort k8s entities on manifest creation

internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
For kustomize and helm, we were reading stderr off of ExitError.Stderr, which is empty since we're redirecting stderr on the `Cmd`.
```
type ExitError struct {
*os.ProcessState
// Stderr holds a subset of the standard error output from the
// Cmd.Output method if standard error was not otherwise being
// collected.
```
=> tiltfile: fix failure stderr logging for kustomize/helm

internal/containerupdate/synclet_manager.go, internal/engine/portforwardcontroller.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/portforward.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go, pkg/model/manifest.go
Fixes #2013.
If this gets merged, I can create a PR to update the docs as well.
=> tiltfile: custom host in port forwards

internal/tiltfile/tiltfile_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/helm:
130a5e1448cf2c689203e3fb8a10076e8e72e875 (2019-10-21 19:17:00 -0400)
tiltfile: add a temporary work-around for helm regression
=> tiltfile: add a temporary work-around for helm regression

internal/cloud/update_uploader.go, internal/cloud/update_uploader_test.go, internal/engine/upper_test.go, internal/hud/hud.go, internal/hud/renderer_test.go, internal/hud/webview/convert.go, internal/store/engine_state.go, internal/tiltfile/include_test.go, internal/tiltfile/tiltfile.go
Please review the following commits I made in branch nicks/tiltfile-load-times:
7152396886f4b0476573c9d4c7d16f0280ab6108 (2019-10-22 12:56:19 -0400)
cloud: report tiltfile loads like other manifests
=> cloud: report tiltfile loads like other manifests

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/extractors.go, internal/store/build_result.go
Please review the following commits I made in branch nicks/containerrunning:
663ed1dc14fe74d72be56d3544c2174f112882eb (2019-10-22 17:15:23 -0400)
engine: when we fail to get the running container info, print the error on Redirect so it shows up in the right resource view
=> engine: when we fail to get the running container info, print the error on Redirect so it shows up in the right resource view

internal/containerupdate/exec_updater.go, internal/containerupdate/exec_updater_test.go
Please review the following commits I made in branch nicks/tar:
e8829bf0e7665cd6a01b8416def38389fa427f7d (2019-10-22 19:01:18 -0400)
containerupdate: tar shouldn't echo the files processed. no other container updater does this and it looks weird
=> containerupdate: tar shouldn't echo the files processed. no other container updater does this and it looks weird

internal/dockerfile/ast.go, internal/dockerfile/ast_test.go
```
go test github.com/windmilleng/tilt/internal/dockerfile -run Directive -count 1000
ok  	github.com/windmilleng/tilt/internal/dockerfile	0.144s
```
=> dockerfile: when reinserting directives from a parsed dockerfile, do so in determinisitic order (fix flaky test)

internal/engine/configs/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
I'm guessing this was a map for historical reasons prior to multiple refactorings, and it's a bit weird for it to still be one now.
=> tiltfile: pass manifest names from cmdline args around as slice instead of map

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_test.go
this previously generated an "invalid reference format" error, since we were happily passing `nil` to `ParseNamed`
=> dc: make image actually optional

toast.yml
a3f4a179655f56647020454fa3c8251c932a3b70 (2019-10-24 17:58:17 -0400)
toast: fix broken wire rule
=> toast: fix broken wire rule

toast.yml
Hello @nicks,
Please review the following commits I made in branch nicks/bug:
d498e26f10de6e10c84bfb3b82e653a2291abc93 (2019-10-24 19:04:36 -0400)
toast: remove prettier, this is no longer necessary
=> toast: remove prettier, this is no longer necessary

Gopkg.toml, internal/tiltfile/docker_compose.go, internal/tiltfile/k8s.go, internal/tiltfile/local_resource.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/value.go, pkg/model/manifest.go, vendor/github.com/looplab/tarjan/.gitignore, vendor/github.com/looplab/tarjan/LICENSE, vendor/github.com/looplab/tarjan/README.md, vendor/github.com/looplab/tarjan/tarjan.go, vendor/github.com/looplab/tarjan/wercker.yml
This adds a new `resource_deps` arg to `k8s_resource`, `dc_resource`, and `local_resource`.
It does not yet affect build order.
It does:
1. populate the engine state with those deps so that the build controller will be able to use it in a future PR
2. validate the deps
3. change `tilt up foo` to also get `foo`'s transitive dependencies.
=> tiltfile: add resource_deps arg

internal/tiltfile/build_index.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/warning:
664a4936ef3f3d0a77e790090f74bf0ec02ef844 (2019-10-25 11:35:12 -0400)
tiltfile: adjust an error message to make it clear that we're not building the image
=> tiltfile: adjust an error message to make it clear that we're not building the image

internal/dockercompose/state.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontroller_test.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/runtime_state.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/testutils/podbuilder/podbuilder.go
1. Add `HasEverBeenReady()` state to each `RuntimeState` implementation
2. Don't select a manifest for building unless `HasEverBeenReady()` is true for all of its resource deps
note: `HasEverBeenReady()`'s behavior in practice is still a bit confusing due to the flashing green dot bug
=> build_control: enforce resource_deps in buildorder

internal/tiltfile/files.go
Call "kubectl kustomize" if the kustomize binary is not installed.
Open to suggestions for improvement!
resolves #2436
=> Add fallback option for kustomize cmd

internal/cli/build.go, scripts/install.sh
Hello @nicks,
Please review the following commits I made in branch nicks/upgrade:
c6593b970807356b47828ffbe96f477aaec62d1c (2019-10-28 16:50:39 -0400)
tilt: update current version to v0.10.15
=> tilt: update current version to v0.10.15

pkg/assets/context.go, pkg/assets/fake.go, pkg/assets/middleware.go, pkg/assets/prod.go, pkg/assets/prod_test.go, pkg/assets/server.go
Please review the following commits I made in branch nicks/middleware:
b7e4f7aea6e4292ae0c34ba367978a11776c9aa5 (2019-10-29 14:23:44 -0400)
assets: rewrite the prod asset server to use middleware
953986f1f1f5aac4c8a430bd101eebe917ddfcf9 (2019-10-29 13:03:33 -0400)
assets: rewrite the test to use a test server, rather than reaching into the internals of prodServer
=> assets: rewrite the prod asset server to use middleware

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/runtime_state.go
The [unit test that checks resource dep scheduling](https://github.com/windmilleng/tilt/blob/8d3235173cd24aee1f2e88268455491fb305a367/internal/engine/buildcontroller_test.go#L842) was failing ~10% of the time.
After investigation, it turns out that the build that should have been blocked was getting returned from [here](https://github.com/windmilleng/tilt/blob/51140205344a27ee79ce27b27d11df30bd2b9387/internal/engine/buildcontrol/build_control.go#L48), which was not affected by the resource deps filter.
Apply the resource deps filter to state.Targets directly, instead of just unbuilt targets, which is much cleaner anyway.
=> engine: fix resource dep scheduling

toast.yml
Hello @nicks,
Please review the following commits I made in branch nicks/toast:
61ee1b2fc92b15fb1fbc154774d6be15d3c6f9b1 (2019-10-30 18:24:39 -0400)
toast: speed up toast wire from ~70s to ~32s
=> toast: speed up toast wire from ~70s to ~32s

web/src/HUD.scss, web/src/HUD.tsx
Hello @hyu,
0e00a5deb73179623d3543e621d85e6566ad2b6e (2019-11-01 17:52:03 -0400)
hud: remove SnapshotMessage. AFAICT, this is dead code, bc we no longer load this exact route
=> hud: remove SnapshotMessage. AFAICT, this is dead code, bc we no longer load this exact route

internal/engine/upper.go, internal/store/engine_state.go, internal/store/store.go
EngineState.InitialBuildsQueued was only used to compare to CompletedBuildCount as a way of determining if we'd built all the resources. Doing so relies on incorrect assumptions about build order and trigger modes. The new "ALL BUILDS ARE MANUAL" feature stretches these incorrect assumptions further.
Remove the field and check what we care about more directly.
=> store: remove EngineState.InitialBuildsQueued

integration/fixture_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/dump2:
5baf8d3ab16f1924dfdd8dba36d65644dcae211f (2019-11-05 17:49:14 -0500)
integration: dump the engine state when integration tests fail
=> integration: dump the engine state when integration tests fail

Makefile, integration/crash_test.go, internal/cli/up.go, internal/engine/actions.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/store.go
Please review the following commits I made in branch nicks/fatal2:
d1d4c1fc319a1f9f07b8369b4b1af51bea15e27f (2019-11-05 21:52:35 -0500)
store: fix a bug where tilt hangs indefinitely if it hits a FatalError while hud=false
=> store: fix a bug where tilt hangs indefinitely if it hits a FatalError while hud=false

internal/cli/wire_gen.go, internal/cloud/update_uploader.go, internal/cloud/update_uploader_test.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/update:
2986adcc4e10361ba05344976acec1e8dbb2cf80 (2019-11-05 19:28:36 -0500)
cloud: remove snapshots from update-history
=> cloud: remove snapshots from update-history

internal/k8s/extract.go, internal/k8s/label.go, internal/k8s/label_test.go
Fixes #2498 
When Tilt applies a k8s object, it injects a `app.kubernetes.io/managed-by` label.
When Tilt applies a k8s object that already *has* a `app.kubernetes.io/managed-by` label, it overwrites it.
When a Deployment already has a `app.kubernetes.io/managed-by` label and a selector matching that label, Tilt updates the label in the meta, but not in the selector, leaving a deployment whose selector does not match its pod, generating a "selector does not match template labels" error on apply.
When injecting labels to an object, also inject those labels to any LabelSelectors we find.
=> tilt: inject labels to LabelSelectors, too

internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/hud/webview/view.go, web/src/Sidebar.tsx, web/src/SidebarIcon.test.tsx, web/src/SidebarIcon.tsx, web/src/Statusbar.tsx, web/src/status.test.tsx, web/src/status.tsx, web/src/types.ts
The primary motivation is that with the new local resource stuff, we have local resources that are not pending and have never been built, so the dots should probably be gray.
When trying to figure out how to add a status for gray, it seemed `RuntimeStatus` is for the "deployment" status, `ResourceStatus` is for the "tilt resource" status, `combinedStatus` returns a `RuntimeStatus` (but incorporates the build status!), and the logic that checks the various pending / build / error states is split across `combinedStatus` and `SideBarIcon`.
Luckily (?), the existing "ResourceStatus" class was never actually used, so...make that map to the dot color, change `combinedStatus` to return a `ResourceStatus`, and get rid of the seemingly redundant logic in `SidebarIcon`.
Also, add a new "not …
=> web: refactor dot color calculation

internal/engine/buildcontroller_test.go
happy to hear from ppl with stronger opinions on testing than i have that
the premise of this commit (i.e. that soon the fake builder will require
that manifests have valid k8s YAML) is a bad one -- otherwise, this PR
sets us up for that universe.
=> engine: change some engine tests to use valid yaml -- in another commit, adding preprocessing that depends on valid yaml

web/src/Sidebar.test.tsx, web/src/Sidebar.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Repro:
1. change a resource so that it fails to build
2. `tilt up`
Observed: the resource fails to build, and when you mouse over where the rebuild button would be, you get a "Cannot trigger an update while resource is building or build is pending."
Expected: there's a rebuild button
This basically comes down to a great game of telephone:
* In `ManifestState`, we have `LastSuccessfulDeployTime`, which in the webview, we [rename](https://github.com/windmilleng/tilt/blob/0ca6cba0164994765b0ddd6d64a462a93ad0c348/internal/hud/webview/convert.go#L84) to `lastDeployTime`.
* In Sidebar.tsx, we [translate `lastDeployTime` into `hasBuilt`](https://github.com/windmilleng/tilt/blob/e6ddeec04f1f611152cf15a226e6988912a0ca84/web/src/Sidebar.tsx#L114)
* In SidebarTriggerButton.tsx, we [use …
=> web: show force rebuild button for resource with a single failed build

integration/analytics_test.go, integration/crash_test.go, integration/fixture_test.go, integration/idempotent_test.go, integration/k8s_fixture_test.go, integration/onewatch_exec_test.go, integration/tilt.go
Please review the following commits I made in branch nicks/driver:
168d32106daf55dddcc714a75f1916c9c7750b66 (2019-11-06 18:25:32 -0500)
integration: factor out a TiltDriver class
named in honor of WebDriver. Drives the Tilt command-line and
actively detects when Tilt crashes during the test
=> integration: factor out a TiltDriver class

internal/engine/upper_test.go
1. test starts the engine with two manifests
2. engine completes initial builds of both manifests
3. test calls `nextCallComplete()` twice
After (2), `EngineState.CompletedBuildCount` is 2
In the first call in (3), `nextCall` returns a `call` with `count == 1`, so `nextCallComplete` blocks until `CompletedBuildCount` is 1, which it will never be.
Since CompletedBuildCount is monotonic, `>=` seems good enough.
=> upper_test: fix nextCallComplete race condition

integration/k8s_fixture_test.go, integration/live_update_after_crash_rebuild/Dockerfile, integration/live_update_after_crash_rebuild/Tiltfile, integration/live_update_after_crash_rebuild_test.go
Three problems:
1. We're using restart.sh but not start.sh
2. The dockerfile is using /src, but the live update config is using /app
3. `WaitForAllPodsReady` can give us old pods that are in the process of terminating
=> integration: fix TestLiveUpdateAfterCrashRebuild issues

internal/build/cache_builder.go, internal/build/custom_builder.go, internal/container/helpers.go, internal/container/helpers_test.go, internal/dockerfile/ast.go, internal/engine/extractors.go, internal/engine/image_and_cache_builder.go, internal/engine/image_build_and_deployer.go, internal/k8s/image.go, internal/tiltfile/build_index.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go, pkg/model/target_test.go
Please review the following commits I made in branch nicks/dockerio:
279a0349a50fe7d6cfd8816842684bb4fcf27d99 (2019-11-11 11:03:04 -0500)
container: add a wrapper function around FamiliarString() that handles RefSelectors correctly
=> container: add a wrapper function around FamiliarString() that handles RefSelectors correctly

web/src/AnsiLine.tsx, web/src/LogPane.scss, web/src/LogPane.test.tsx, web/src/LogPane.tsx, web/src/__snapshots__/AlertPane.test.tsx.snap, web/src/__snapshots__/LogPane.test.tsx.snap
Resolves #2524 
In some cases, copy/pasting from Tilt into a rich text editor causes linebreaks to be lost.
We render log lines as individual `<div>s` and rely on their `display: block` behavior to get us newline behavior. Apparently some versions of some text editors do not know how to handle this, and so text gets pasted without newlines.
Drop the `display: block` and `<div>`s on our log lines, and render then with `<span>` and `<br>`s instead.
I was unfortunately unable to repro this bug in the first place, so I haven't been able to verify the fix but the users who reported the bug also reported that making the analogous change in the chrome developer console resolved the issue.
=> webui: use linebreaks instead of display: block to separate lines

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go
1. `tilt up` and successfully deploy a service that has live_update configured
2. make a change to the service's code such that live_update runs and fails
3. click force update in the web UI
the force update is a live update
the force update is an image build
This is because we determine whether a triggered build is a forced update by checking if `PendingFileChanges` is non-empty. Since we only clear `PendingFileChanges` on successful builds, this means that if we've made a change and then failed the build, then subsequent build triggers will not set ForceUpdate.
Instead of setting ForceUpdate iff there are any files in `PendingFileChanges`, set ForceUpdate iff there are any files in `PendingFileChanges` with a timestamp since the last build's start time.
=> engine: fix force rebuild after failed build

.circleci/config.yml
if a master build fails, we don't publish tilt assets, so tilt builds from that sha will create snapshots that don't have assets (e.g. https://cloud.tilt.dev/snapshot/Ae6W2NwL3uAQ_ZHe-so=)
Publish assets no matter what. It might be that the js tests fail, but they're still probably better than nothing.
=> ci: always publish assets

integration/live_update_after_crash_rebuild_test.go
Please review the following commits I made in branch maiamcc/disable-lu-after-crash-test:
0f498585d28ef770c1286e35b1f536162841a1d6 (2019-11-12 14:31:34 -0500)
integration: skip TestLiveUpdateAfterCrashRebuild until we can figure out what's breaking
=> integration: skip TestLiveUpdateAfterCrashRebuild until we can figure out what's breaking

internal/engine/build_and_deployer_test.go, internal/engine/build_errors.go, internal/engine/image_build_and_deployer.go
#2484 observes that we log docker build failures three times.
The middle of these three is because `ImageBuildAndDeployer` was not wrapping its errors in `DontFallBackOn`.
In `CompositeBuildAndDeployer`, we log "unexpected" errors [if they are not on the last builder](https://github.com/windmilleng/tilt/blob/354fbada1d5ced7fac563c67b3e00cda037d9bbf/internal/engine/build_and_deployer.go#L76). Since the introduction of `LocalTargetBuildAndDeployer, `ImageBuildAndDeployer` is no longer the last builder, so it's no longer getting suppressed by that check.
There's probably some rearchitecting we could do to make this all cleaner, but this at least is a small change that makes `ImageBuildAndDeployer` consistent with the other `BuildAndDeployers` and addresses part of the problem.
=> engine: don't fall back on docker build failures

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go
When we do a crash rebuild, we get:
```
live-update…┊ falling back to next update method because: Force update (triggered manually, not automatically, with no dirty files)
```
even though there's no force update involved
This is because we're inferring force update from whether there are any file changes, which is error-prone!
It turns out there are also no file changes for crash rebuild!
This doesn't really have any impact other than wrong verbose logging since either way the effect is to make sure we do an image build instead of a live update, but it's still confusing when debugging.
The refactor suggested in buildcontroller.go (proactively specify force build in the BuildEntry instead of grossly mutating the BuildResult) would have avoided this.
=> build controller: don't set ForceUpdate on crash rebuild

internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch.go, internal/testutils/podbuilder/podbuilder.go
Potentially addresses #2374 (or, at least, addresses a cause of it, which may or may not be the only cause)
As an optimization, when one of Tilt's watchers gets an update for an object from a K8s informer, it checks to see if its resourceVersion is older than the last resourceVersion it saw, and if so, ignores it.
Unfortunately:
1. resourceVersion is a string, and Tilt is using string comparison (so, e.g., if we see resourceVersion "9", we'll then ignore "10" through "89" and "100" through "899")
2. the comment on resourceVersion says clients must treat it as opaque
Simply remove the resourceVersion check. Theoretically the K8s informer provides us updates in order, so it does us no good.
=> watch: ignore resourceVersion

internal/build/pipeline_state.go, internal/build/testdata/TestPipelineErrored_master, internal/engine/build_and_deployer_test.go, internal/engine/upper.go, internal/engine/upper_test.go
addresses the last bit of #2484
When a build fails, both the builder and the upper log the build error, in consecutive lines in the log.
Make the upper solely responsible for logging build failures.
Before:
[snapshot](https://cloud.tilt.dev/snapshot/AcSY7NwLj9igAz5fj8s=)
```
vigoda      ┊     ╎ ERROR IN: [3/3] RUN go install github.com/windmilleng/servantes/vigoda
vigoda      ┊ 
vigoda      ┊ ERROR: ImageBuild: executor failed running [/bin/sh -c go install github.com/windmilleng/servantes/vigoda]
Build Failed: ImageBuild: executor failed running [/bin/sh -c go install github.com/windmilleng/servantes/vigoda]
```
After:
[snapshot](https://cloud.tilt.dev/snapshot/AdaX7NwLrr8GA0oLeQs=)
```
vigoda      ┊     ╎ ERROR IN: [3/3] RUN go install github.com/windmilleng/servantes/vigoda
vigoda …
```
=> build: remove redundant build error log

integration/onewatch_test.go, internal/docker/fake_client.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/pod_template.go, internal/k8s/pod_template_test.go, internal/store/build_result.go, internal/store/engine_state.go, internal/store/json_test.go, internal/store/runtime_state.go, internal/testutils/podbuilder/podbuilder.go
This is the third attempt at #2439. See that PR for the problem description and solution.
The second attempt, #2519, was reverted because it was making an integration test fail pretty consistently. We're now reasonably sure those failures were due to a pre-existing bug resolved by #2555, and not an issue with #2519 itself. In a branch with #2519 and #2555, the test passed 100x in a row.
=> revert the revert of the revert of the revert of podtemplatespec hashes

internal/cli/wire_gen.go, internal/engine/live_update_build_and_deployer.go, internal/engine/live_update_build_and_deployer_test.go, internal/engine/wire_gen.go
Every `BuildAndDeployer` except `LiveUpdateBuildAndDeployer` logs its progress via `build.PipelineState`.
Using `build.PipelineState` in `LiveUpdateBuildAndDeployer` means:
1. output now looks more consistent across build types
2. we log the build time for live updates, advertising their speed
before: [snapshot](https://cloud.tilt.dev/snapshot/Aay57twLL7bK14p8zx8=)
after: [snapshot](https://cloud.tilt.dev/snapshot/AZDB7twL0utgvs64UDA=)
=> live update: use pipeline logger

internal/k8s/extract.go, internal/k8s/label.go, internal/k8s/label_test.go
Resolves #2576
#2500 made label injection also inject to `MatchSelector`s, not just `ObjectMeta.Labels`, to address #2498. This unfortunately added another bug: now we might be adding labels when there were none, and incorrectly changing behavior. e.g., a NetworkPolicy's namespaceSelector might be used to let an ingress talk to a namespace. If the NetworkPolicy is deployed by Tilt and the namespace is not, then Tilt will inject managed-by: tilt into the NetworkPolicy's namespaceSelector, and it will no longer match the intended namespace.
Tangentially: we were never injecting labels into Service's selectors, because they're not of type `MatchSelector`.
1. When injecting labels into a selector, only update the value of an existing key. Don't add new keys.
2. Inject labels into Service's …
=> k8s: when injecting labels to match selectors, only update existing values

internal/cli/cli.go, internal/cli/klog.go, internal/cli/klog_test.go
Resolves #2406
We previously fixed a different instance of this.
#1955 used the same approach to hide a very similar, but different warning.
At some point, K8s changed that warning to not be a warning, so #1955 was reverted: #2029
Basically, [in this code](https://github.com/windmilleng/tilt/blob/90aa4750036b819c9f8da2fa4bf90901b8a43019/vendor/k8s.io/client-go/tools/cache/reflector.go#L297). The old warning was on line 297 and the warning addressed by this PR is hitting line 299.
This is apparently because this warning is not setting its `ReasonForError` to `metav1.StatusReasonExpired`, so [`IsResourceExpired`](https://github.com/windmilleng/tilt/blob/90aa4750036b819c9f8da2fa4bf90901b8a43019/vendor/k8s.io/apimachinery/pkg/api/errors/errors.go#L490) returns false.
I spent 15 minutes trying …
=> klog: ignore too old resource version warnings

internal/tiltfile/flags/flags.go, internal/tiltfile/flags/flags_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
(part of https://github.com/windmilleng/tilt.build/pull/325)
This adds a `flags.set_resources` builtin that overrides the resource list specified as positional arguments to `tilt up`
=> tiltfile: add flags.set_resources

internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/engine/image_and_cache_builder.go
Please review the following commits I made in branch nicks/issue2589:
0ff01c034b3a92ed03b3531dd433b4e147369d71 (2019-11-25 13:00:45 -0500)
build: fix up custom_build to work with non-docker builders like buildah
Currently, custom_build checks to make sure that your local docker registry
has the built image. This doesn't work if you don't have docker installed at all.
Long-term, I think we probably need to rethink the custom_build API to be richer
than a single shell command (and also provide 'tag' and 'push' commands).
=> build: fix up custom_build to work with non-docker builders like buildah

internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/engine/image_and_cache_builder.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/ch3983/push:
3edcfc75d7a71cf1653623a336ac5927946cf611 (2019-11-25 17:54:51 -0500)
build: add skips_local_docker=True to custom_build, for custom_builds that don't use docker at all
=> build: add skips_local_docker=True to custom_build, for custom_builds that don't use docker at all

internal/engine/analytics/analytics_reporter.go, internal/engine/analytics/analytics_reporter_test.go, internal/engine/configs/configs_controller.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/fastbuild2:
0b8263b1c117013ef0ac7e1958ef57c605a597a8 (2019-12-02 17:19:45 -0500)
rm fastbuild from configs package
dd00d9f8de39586d7f34afd8ec6cbde4fa83e37d (2019-12-02 17:18:53 -0500)
rm fastbuild from analytics package
7a8c6c9f3f7ea2e8628c5d24817a14e7adc48b2d (2019-12-02 17:15:39 -0500)
rm fastbuild references from tiltfile package
=> tiltfile / analytics / configs: removing more fastbuild code

.circleci/Dockerfile.integration, .circleci/config.yml, Makefile
Hello @nicks,
Please review the following commits I made in branch nicks/kind6:
bc3f9aacb6646f93575c8592ed5ac2bfd4bbdac1 (2019-12-02 15:33:05 -0500)
integration: update tests to use kind 0.6.0
=> integration: update tests to use kind 0.6.0

pkg/model/logstore/doc.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go
Please review the following commits I made in branch nicks/logs2:
071eb7d657c0d41296e61445326ad4ab02d77b47 (2019-12-03 13:52:08 -0500)
logstore: fork model.Log into logstore.LogStore
The main difference between them is that model.Log stores the logs
with prefixes, and logstore.LogStore stores the logs without prefixes,
then formats them with prefixes on String()
=> logstore: fork model.Log into logstore.LogStore

pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go
Please review the following commits I made in branch nicks/logsegment:
92040f1d12d0865f74034923ea5e42e24b9baa2a (2019-12-03 19:46:09 -0500)
model: store logs by segment instead of by line
A key API we want to be able to support is "give me all the logs since checkpoint X".
Storing the logs in an append-only data structure makes this much easier to support,
even if it makes it a little bit harder to print the logs line-by-line.
Storing the logs line-by-line meant we had to do backtracking and make things mutable.
=> model: store logs by segment instead of by line

internal/engine/upper.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go, pkg/model/logstore/prefix.go, pkg/model/logstore/testing.go
Please review the following commits I made in branch nicks/continuation:
349557cfa6f969b7719d24c8c7baddf75dd2f2cf (2019-12-04 11:27:30 -0500)
logstore: Add a concept of checkpoints and ContinuingStrings, for incremental log printing
ce0e01aa60f2356874962702c8fc4f66d1c8d201 (2019-12-04 11:20:10 -0500)
model: store logs by segment instead of by line
A key API we want to be able to support is "give me all the logs since checkpoint X".
Storing the logs in an append-only data structure makes this much easier to support,
even if it makes it a little bit harder to print the logs line-by-line.
Storing the logs line-by-line meant we had to do backtracking and make things mutable.
=> logstore: Add a concept of checkpoints and ContinuingStrings, for incremental log printing

internal/dockercompose/client.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/docker_compose_log_manager_test.go, internal/engine/upper.go
Please review the following commits I made in branch nicks/dclogs:
47aca0da54791dbfa8a14436b4ca8cce5ca7dcbb (2019-12-03 18:26:04 -0500)
engine: docker-compose log actions should not contain timestamps or service prefixes
Per https://github.com/windmilleng/tilt.specs/pull/19, we're moving towards a system
where the engine stores structured logs, and adds the prefixes later.
=> engine: docker-compose log actions should not contain timestamps or service prefixes

pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go, pkg/model/logstore/reader.go, pkg/model/logstore/reader_test.go
Please review the following commits I made in branch nicks/logstoremutex:
7842dd295c5430cbf9200d51c9e60241de3b4628 (2019-12-04 13:02:54 -0500)
logstore: add a thread-safe log reader
=> logstore: add a thread-safe log reader

internal/engine/buildcontroller_test.go, internal/engine/configs/actions.go, internal/engine/configs/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/disabled_hud.go, internal/hud/fake_hud.go, internal/hud/hud.go, internal/hud/renderer_test.go, internal/hud/tabview.go, internal/hud/text.go, internal/hud/view/view.go, internal/hud/webview/convert.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/store/store.go, internal/store/testing_store.go, pkg/model/logstore/reader.go
Please review the following commits I made in branch nicks/logstore2:
835eec16ff871cbbc12bf74f95d93ab886233e85 (2019-12-04 15:09:13 -0500)
store: Replace the old global log store with a new global log store
=> store: Replace the old global log store with a new global log store

internal/hud/server/websocket.go, internal/hud/server/websocket_test.go
I can spend an hourish on a more elegant/less kludgey solution but this
might be the fastest and simplest way to fix the CPU issues here.
We diagnosed the CPU issues in #2597 as coming from a high volume of
websocket sends (due to the high volume of log messages in the chart
in question). in particular, the problem was the `json.Marshal` to send
proto messages over the websocket; both that `json.Marshal` isn't cheap
in terms of CPU, but that it allocates a lot of memory (that we then
immediately throw away--so garbage collection was taking up a non-trivial
amount of CPU as well).
Alternatives considered:
1. replace `json.Marshal` (or `jsonpb.Encode`) with [`jsoniter`](https://github.com/json-iterator/go),
which is much more performant in terms of CPU and memory …
=> websocket: simple throttle to fix cpu issues [ch3997]

web/src/LogStore.test.ts, web/src/LogStore.ts
Please review the following commits I made in branch nicks/clientlogs:
c8bf2935da179bfa38f0f7dae2564f4ffcf2e7ec (2019-12-06 14:31:52 -0500)
web: add a client-side logstore
currently, this is a straight port of the server-side logstore
over time, we expect this logstore to have much richer methods
for filtering logs by manifest, log level, etc
=> web: add a client-side logstore

internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, pkg/model/logstore/logstore.go, web/src/AppController.ts, web/src/HUD.tsx, web/src/HudState.tsx, web/src/types.ts
Please review the following commits I made in branch nicks/clientlogs2:
769b39842e66aca083a0da852b2e9ab7160d6a8d (2019-12-06 18:02:29 -0500)
web: Use the structured logstore in the web client
e43b4eacebeb87d29ba0ac56eb4c83b3506e16be (2019-12-06 16:32:59 -0500)
web: add a client-side logstore
currently, this is a straight port of the server-side logstore
over time, we expect this logstore to have much richer methods
for filtering logs by manifest, log level, etc
=> web: Use the structured logstore in the web client

internal/engine/build_and_deployer.go, internal/synclet/client_adapter.go, pkg/logger/deferred.go, pkg/logger/func_logger.go, pkg/logger/logger.go, pkg/logger/logger_test.go
Please review the following commits I made in branch nicks/logger2:
2594ea06331a1d477fa29018c9a92a577c4ce051 (2019-12-09 20:06:20 -0500)
logger: fix a bug when printing placeholders to certain types of loggers
Noticed that if you wrote l.Write(logger.InfoLvl, "%s"), it would
print "%s(MISSING)" to the output stream.
While I was here, I ended up deleting a bunch of redundant code.
=> logger: fix a bug when printing placeholders to certain types of loggers

internal/engine/buildcontroller.go, internal/engine/configs/configs_controller.go, internal/engine/configs/tiltfile_log_writer.go, internal/engine/pod.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/webview/convert_test.go, internal/store/actions.go, internal/testutils/podbuilder/podbuilder.go, pkg/model/logstore/logstore.go
Please review the following commits I made in branch nicks/newspanid:
91349bf51c2bbb595879144236a553fff016c9fb (2019-12-10 17:25:34 -0500)
logstore: assign span ids to all span types
=> logstore: assign span ids to all span types

internal/hud/server/websocket.go
DB on slack re: "if multiple OnChange's come in within 100 ms, only call one (right now, if 10 OnChanges come in in quick succession, we'll make 10 OnChange calls, each 100ms apart, and most will be no-ops)":
> Are you sure about this? I think the dirtybit in the subscriber means it will only call it a second time...
a quick glance through the code supports DB's point (though it's a little gnarly, i'm not 100% sure). updating comment to reflect.
=> websocket: update comment about 'throttle'

internal/cli/docker_prune.go, internal/cli/down.go, internal/cli/down_test.go, internal/engine/configs/actions.go, internal/engine/configs/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/tiltfile/config/config.go, internal/tiltfile/config/config_def.go, internal/tiltfile/config/config_test.go, internal/tiltfile/config/resources.go, internal/tiltfile/config/string_list.go, internal/tiltfile/git/git_test.go, internal/tiltfile/starkit/fixture.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/user_config_state.go
This is a scoped-down #2596. 
The behavior implemented by this PR is, when `config.parse` is called:
1. If tilt_config.json specifies any settings, load those.
2. If there are any args on the command line, parse those and have them take precedence over anything in tilt_config.json.
3. in starlark, return whatever config we're left with
Tilt does not write to tilt_config.json.
=> user config: also read from tilt_config.json

web/src/AlertPane.test.tsx, web/src/AlertPane.tsx, web/src/AppController.ts, web/src/FacetsPane.tsx, web/src/HUD.tsx, web/src/HudState.tsx, web/src/Sidebar.stories.tsx, web/src/Sidebar.test.tsx, web/src/Sidebar.tsx, web/src/SidebarTriggerButton.test.tsx, web/src/Statusbar.test.tsx, web/src/Statusbar.tsx, web/src/alerts.test.ts, web/src/alerts.ts, web/src/constants.ts, web/src/feature.ts, web/src/mostRecentBuild.test.ts, web/src/mostRecentBuild.ts, web/src/status.tsx, web/src/testdata.tsx, web/src/time.tsx, web/src/types.ts
Please review the following commits I made in branch nicks/types:
dfd5fda3fc6fb732c09e556af8d5b32015e7608b (2019-12-11 17:45:05 -0500)
web: delete the artisanal, hand-curated typescript types in favor of shiny new protobuf-generated types
=> web: delete the artisanal, hand-curated typescript types in favor of shiny new protobuf-generated types

web/src/LogStore.test.ts, web/src/LogStore.ts
Please review the following commits I made in branch nicks/spanlog:
246d800b26cf402d71f40f4c79472ed246bc736d (2019-12-12 10:57:59 -0500)
web: Add a method for getting a single pod's logs
=> web: Add a method for getting a single pod's logs

web/src/LogStore.test.ts, web/src/logs.ts
Hello @nicks,
Please review the following commits I made in branch nicks/newlines:
8e78fadd1068a4691b4d8f394d43ce2e9b962e94 (2019-12-12 16:28:33 -0500)
web: remove trailing newline from logline serialization
this only affects tests (and is for making some test diffs in a future pr easier to follow)
=> web: remove trailing newline from logline serialization

web/src/alerts.test.ts, web/src/alerts.ts, web/src/combinedStatusMessage.ts, web/src/mostRecentBuild.test.ts, web/src/mostRecentBuild.ts
I thought we should standardize on one way of notating arrays, and this way uses fewer characters
and more closely aligns with how slices are annotated in Go.
I ran:
```
jscodeshift -t ~/development/typescript-generic-array-to-square-brackets/transform.js --extensions=ts --parser=ts src/
```
The code for the jscodeshift transformer lives [here](https://github.com/jazzdan/typescript-generic-array-to-square-brackets).
=> web: standardize on T[] instead of Array<T>

web/src/LogPane.scss
Hello @hyu,
Please review the following commits I made in branch nicks/ch4102/webui:
4aebdf9f2c5ac94e1362ced1e349357a90c9a7ec (2019-12-10 15:42:21 -0500)
web: fix selection behavior by using margin instead of padding
Fixes https://github.com/windmilleng/tilt/issues/2645
=> web: fix selection behavior by using margin instead of padding

web/src/HUDLayout.stories.tsx, web/src/HUDLayout.tsx, web/src/constants.ts
I'm proposing a change to the visual hierarchy of our main page, in preparation for creating more space in our layout for helpful Log navigation tools. 
First step: Create a new HUDLayout which will eventually replace HUDGrid:
=> web: Add new HUDLayout to Storybook in prep for new page hierarchy

internal/cli/args.go, internal/cli/args_test.go, internal/cli/cli.go, internal/cli/up.go, internal/engine/configs/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/actions.go, internal/hud/server/server.go, internal/hud/server/server_test.go, pkg/model/user_config_state.go
This also works on tilt instances that are not using `config` at all.
I've found the help kind of awkward to write and am super interested in advice on making it less awkward. I wrote up some of my thinking on naming issues [here](https://docs.google.com/document/d/1JXoIR2UN4zKMBdcSZiPd7AzdQM7CVOiEL453BQtI8a0/edit?usp=sharing).
=> tilt: add args subcommand

internal/cloud/snapshot_uploader.go, internal/hud/server/server.go, internal/hud/server/websocket.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go, web/src/AppController.ts, web/src/HUD.tsx, web/src/LogStore.test.ts, web/src/LogStore.ts
Please review the following commits I made in branch nicks/ch4095/logs:
cdb8b67a150ed3850a4c3a08b3ed776a274174e7 (2019-12-13 16:19:01 -0500)
logstore: incremental log loading
Now, we only push down the logs that have changed, rather than pushing
down all the logs on every websocket message
89bf4760d2a532c89df5e7033a88838732f49492 (2019-12-13 15:30:10 -0500)
webview proto: define incremental log-loading protocol
=> logstore: incremental log loading

web/src/LogPane.tsx, web/src/TabNav.scss, web/src/constants.scss, web/src/constants.ts
- Right align the text so the ragged left edge makes it easier to distinguish manifests from each other.
- Align the manifest width with the tab width, because it was previously juuuuuust a little off.
- Show full Manifest name on hover
=> web: tweak Manifest Name layout

internal/hud/renderer.go, internal/hud/tabview.go
Please review the following commits I made in branch nicks/ch4131/perf:
ea2de2ddd940dd71d5f26cc84b6b8d98bf25e2cf (2019-12-18 13:11:36 -0500)
hud: shorten default log truncation a lot. makes hud rendering much faster
=> huud: shorted default log truncation a lot. makes hud rendering much faster

web/src/HUD.test.tsx, web/src/LogStore.ts
Please review the following commits I made in branch nicks/ch4132/firestore:
2162402d2520fa86f0fad7de897a405170655bab (2019-12-18 14:33:44 -0500)
web: default span ids to _. Fixes firestore issues with empty map keys
=> web: default span ids to _. Fixes firestore issues with empty map keys

web/src/LogPane.scss, web/src/LogPane.tsx, web/src/LogStore.ts, web/src/__snapshots__/LogPane.test.tsx.snap, web/src/logs.ts
Hello @hyu,
Please review the following commits I made in branch nicks/wrap:
c2a234a79043d7579ad9d763c0527423dd19c48d (2019-12-18 13:39:24 -0500)
web: go back to wrapping-by-default and add section dividers
=> web: go back to wrapping-by-default and add section dividers

internal/engine/upper_test.go
this PR doesn't change any behavior right now, but sets me up
to better test parallel builds--can now start builds A, B, and C,
and complete just build C
=> engine test: fakeBuildAndDeployer can now resolve builds manually

internal/k8s/client.go, vendor/k8s.io/client-go/discovery/cached/memory/memcache.go, vendor/modules.txt
Please review the following commits I made in branch nicks/issue2709/deferred:
99034a273322e0201ecd9d6f001ae4c1f51b747e (2020-01-02 18:41:40 -0500)
k8s: use deferred discovery restmapper. Fixes https://github.com/windmilleng/tilt/issues/2709
=> k8s: use deferred discovery restmapper. Fixes https://github.com/windmilleng/tilt/issues/2709

internal/cloud/snapshot_uploader.go
Please review the following commits I made in branch nicks/ch4136/facets:
92ae7159ced87335ef8078c3ad83c1b78f891ebe (2020-01-02 18:12:27 -0500)
cloud: no longer any reason to clear feature flags on upload
=> cloud: no longer any reason to clear feature flags on upload

internal/cli/up.go, internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/issue2707/host:
2e0ffaafa988795fd15f6581d81a53fab54a3ed8 (2020-01-02 19:42:37 -0500)
tiltfile: default port-forward hosts to the host set on the command-line
Fixes https://github.com/windmilleng/tilt/issues/2707
=> tiltfile: default port-forward hosts to the host set on the command-line

CONTRIBUTING.md, internal/hud/server/server.go
Please review the following commits I made in branch nicks/httppprof:
28f8722b83c95ab2c897a47f99eae882a6288fe6 (2020-01-03 15:13:52 -0500)
server: use the standard golang pprof hooks
=> server: use the standard golang pprof hooks

internal/hud/hud.go
Please review the following commits I made in branch nicks/perf:
436891c58a8befc147b34c8bd56a017f13dad11f (2020-01-03 15:19:18 -0500)
hud: only redraw on clock tick, not OnChange
=> hud: only redraw on clock tick, not OnChange

internal/dockercompose/state.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/runtimelog:
4cca650332357d0bced0b1f08b9aff5c560f5f07 (2019-12-20 17:21:13 -0500)
engine: remove logs from the runtime data model and load them from the logstore
Note that this changes functionality slightly. Before this PR,
we would clear the pod logs every time the pod crashed. In the LogStore,
there's a single span ID for a pod's logs, no matter how many times it crashed.
I don't *think* that changing this behavior will have any bad side-effects
but @maiamcc might be able to think of problems that I don't remember right now.
Long-term, I think we should move towards a system where every container ID
has its own log span ID, and that span ID has a parent span ID for the whole
pod's logs (similar to how …
=> engine: remove logs from the runtime data model and load them from the logstore

internal/engine/buildcontrol/actions.go, internal/engine/buildcontroller.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Hello @,
Please review the following commits I made in branch maiamcc/prework-parallel-build:
9cc74255466f9a1d7d8a38884717b1e6e9251ea6 (2020-01-06 11:48:49 -0500)
engine: more info in BuildCompleteAction, store CurrentlyBuilding as set (pre-work for parallel builds) [ch4065]
=> engine: more info in BuildCompleteAction, store CurrentlyBuilding as set (prework for parallel build) [ch4065]

internal/cli/build.go, scripts/install.sh
Hello @nicks,
6575dbcb91b9d082826edb8afae4ffac7039bdff (2020-01-06 17:18:45 -0500)
bump version to v0.10.26
=> bump version to v0.10.26

.goreleaser.yml
Hello @nicks,
Please review the following commits I made in branch nicks/goreleaser:
e2fce573d5723f14fdd1f8bd29527da7d1860be6 (2020-01-06 17:24:40 -0500)
goreleaser: fix some deprecation notices
=> goreleaser: fix some deprecation notices

internal/tiltfile/local_resource.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Note: this is backwards incompatible because I made a formerly required field optional. It would be possible to do this in other ways. For example, we could leave updateCmd as required and just let people who only want to do serve cmds leave it empty:
```python
local_resource("foo", "", serveCmd="rails s")
```
Or we could make it a boolean parameter, like so:
```python
local_resource("build_foo", "go install .")
local_resource("serve_foo", "./main", serve=True)
```
Or make it an entirely different function.
=> tiltfile: ability to specify serve commands in tiltfile

internal/engine/buildcontroller_test.go, internal/engine/upper_test.go
this should make the parallel build tests less janky
=> engine/tests: fakeBuildAndDeployer stores/completes builds by targetIDs instead of buildIndex

internal/engine/buildcontrol/actions.go, internal/engine/buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/buildid:
a42c508f46989bc9bf6e2e867fb45bb3a7198814 (2020-01-08 12:36:20 -0500)
engine: attach span ids instead of counts to build events, now that they can happen in parallel
=> engine: attach span ids instead of counts to build events, now that they can happen in parallel

integration/fixture_test.go
Please review the following commits I made in branch nicks/integration3:
7e73f85785e5fba3867587a58f7dc1d3b05775b0 (2020-01-08 14:01:57 -0500)
integration: when compiling Tilt, use vendor deps
=> integration: when compiling Tilt, use vendor deps

internal/store/logger.go, pkg/logger/func_logger.go, pkg/logger/func_logger_test.go, pkg/logger/logger.go
Messages logged on the debug level show up even if you aren't running with `--debug` (and same for verbose).
Some uses of `FuncLogger` do level filtering themselves, and some rely on `FuncLogger` to do the filtering for them. It turns out `FuncLogger` does not do any level filtering itself.
Move all `FuncLogger`-related level filtering into `FuncLogger` itself.
(really only the `FuncLogger` change is needed to fix the problem, and the other changes are cleaning up what is not redundant level filtering)
=> logger: fix level filtering

internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/store/engine_state.go
i don't love the build/update naming inconsistency, but i'd rather it
be further down into the engine (e.g. when we compare currentlyBuilding vs.
maxParallelBuilds) than closer to the user (e.g. `update_settings(max_parallel_builds=x)`)
=> engine/store: rename maxBuildSlots to maxParallelUpdates

internal/engine/configs/actions.go, internal/engine/configs/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/updatesettings/update_settings.go, pkg/model/build_settings.go
by all rights, `state.MaxBuildSlots` should be `engine.MaxUpdateSlots` or something,
b/c I think we've been trying to move away from "build" and towards "update"--
I tried to keep the user-facing language consistent with "update", and am happy
to change backend language in a separate PR
=> tiltfile: set max build slots from tiltfile [ch4065]

internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/update-settings-required-arg:
62dbd3888332109d4fd3746c4c21749dca6e7183 (2020-01-09 17:28:25 -0500)
tiltfile: required arg test for max_parallel_updates (for now)
=> tiltfile: required arg test for max_parallel_updates (for now)

pkg/model/update_settings.go
here's the PR that will turn on parallel updates by default; merge it
whenever you like!
=> max number of parallel updates is 3 by default [ch4065]

internal/engine/local/actions.go, internal/engine/local/controller.go, internal/engine/local/controller_test.go
When we have multiple local resources, a resource's logs often end up in the wrong resource.
This is because the span IDs are keyed off of the sequenceCount, but we have duplicate sequenceCounts across resources because it's just 0, 1, 2, ... Since we're logging with identical spanIDs, the LogStore combines these. (even though they have different manifest names! that's probably a bug we should fix, but it seems good to have unique span IDs whether we fix that or not)
Instead of having each process go through sequenceNums of 0, 1, 2..., use a global monotonically increasing number as the tilt process ID, so that each process still has an increasing sequenceNum, but it's also globally unique.
=> local serve: correctly separate resource logs

internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/local/execer.go, internal/engine/upper_test.go
When we kill an old process because we're replacing it with a new one, we log the error generated by killing it. This is unlikely to be useful to the user.
Filter out any events generated by a process that is no longer current, per procNum.
This also obsolesces stoppedCh, which reduces opportunity for dumb channel bugs.
=> local: remove stoppedCh and use procNum to filter out old events

internal/engine/local/execer.go, internal/engine/local/execer_test.go, pkg/assets/dev.go, pkg/procutil/procutil_unix.go, pkg/procutil/procutil_windows.go
We run local resource's serve_cmd as a child process. When that child process spawns a grandchild process, then our mechanism of canceling the Context does not work to kill the grandchild process or cause cmd.Wait to return, so tilt effectively hangs when trying to stop the process.
Don't rely on canceling the context to kill the child process, and instead spawn the child process in a process group and kill the whole process group. Code lifted wholesale from Mish (https://github.com/windmilleng/mish/blob/master/mish/shmill/shmill.go#L170)
While I was here, I also made it so that we consider it an error even when a process exits with exit code 0.
=> local execer: start serve commands in process groups and clean them up

internal/engine/local/controller.go, internal/engine/local/controller_test.go
When using `local_resource` with a `serve_cmd`, the processes are left running when you stop Tilt. When you restart Tilt, all the `serve_cmd`s will fail because the old processes still have the port.
For now, kill `serve_cmd`s when Tilt exits.
Cons:
* inconsistent with other types of resources (k8s and DC resources are left running on exit)
* prevents us from reusing old processes if nothing's changed
Pros:
* restarting tilt when using serve_cmd isn't insanely annoying
We'll probably want to do something different in the longer run (and maybe even before we publicize this feature) but this will ease iterating on this.
=> local: kill processes on shutdown

internal/cli/build.go, scripts/install.sh
Hello @nicks,
dbda089f2b27762d1217a6ec0637f31f28fa60c3 (2020-01-13 18:59:20 -0500)
scripts: bump current version
=> scripts: bump current version

web/src/HUD.tsx, web/src/LogPane.test.tsx, web/src/LogPane.tsx
Please review the following commits I made in branch nicks/windowing:
8877b17b3ba48f851ead49610e48b93fc6118e0b (2020-01-14 19:12:26 -0500)
web: reset autoscroll when switching views. Fixes https://github.com/windmilleng/tilt/issues/2571
=> web: reset autoscroll when switching views. Fixes https://github.com/windmilleng/tilt/issues/2571

internal/hud/view/view.go
with this last line, now local resource runtime logs work in the TUI
=> local resource: fix spanid in view

integration/fixture_test.go, integration/tilt.go, integration/tilt_args/Tiltfile, integration/tilt_args_test.go, internal/cli/args.go, internal/testutils/bufsync/bufsync.go
`path.Join` ends up de-duping existing /'s, and `http://` isn't part of a path, so it's not appropriate to use there.
Don't `path.Join` the scheme.
=> args: fix tilt args url construction

web/src/LogPane.tsx, web/src/index.scss
Please review the following commits I made in branch nicks/windowing2:
94a56d14f2d3da197dc0431903fa14f37280de4e (2020-01-15 09:32:16 -0500)
web: disable smoothing and calculate autoscroll without forcing layouts
These two optimizations speed up scrolling and responsiveness dramatically
4e3e57bf8c8788754188f6a9bbce44d6cc0085aa (2020-01-14 19:27:30 -0500)
web: reset autoscroll when switching views. Fixes https://github.com/windmilleng/tilt/issues/2571
=> web: disable smoothing and calculate autoscroll without forcing layouts

internal/engine/local/execer.go
e.g., `docker run` will kill the underlying container if it gets a SIGINT, but doesn't get a chance if it gets a SIGKILL
=> local serve: make first cleanup attempt w/ SIGINT instead of SIGKILL

scripts/patch/cache/reflector.go.patch, vendor/k8s.io/client-go/tools/cache/reflector.go
Please review the following commits I made in branch nicks/duration:
41937f0b338e70a1941df845d22d191bcbb343d8 (2020-01-16 21:54:00 -0500)
k8s: oops! I accidentally turned the watch timeout too low
This is the length of time that a watch waits before
it notices that it's lost access credentials. It was originally
at 5 minutes. I turned it down to 10sec for testing.
Let's turn it down to 1 minute.
=> k8s: oops! I accidentally turned the watch timeout too low

internal/engine/live_update_build_and_deployer.go
Fixed a typo. The word `with` is repeated twice in one of the log statements. 
```failed with with exit code: 1``` -> ```failed with exit code: 1 ```
=> engine: fixed typo where the word `with` was repeated twice

internal/engine/buildcontroller.go, internal/engine/configs/tiltfile_log_writer.go, internal/engine/local/controller.go, internal/engine/pod.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/telemetry/controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/webview/convert_test.go, internal/store/actions.go, internal/store/logger.go, internal/synclet/log_style.go, internal/tiltfile/tiltfile_test.go, pkg/logger/deferred.go, pkg/logger/func_logger.go, pkg/logger/func_logger_test.go, pkg/logger/logger.go
Please review the following commits I made in branch nicks/fields:
317b614692458b0be3ece62f9a6d5874a3208b38 (2020-01-17 16:59:20 -0500)
logger: add arbitrary fields to log events
e886ec3446bc34583c3362efb588752c069d135e (2020-01-17 16:42:20 -0500)
engine: remove some dead wrapper objects
=> logger: add arbitrary fields to log events

web/src/HUD.test.tsx, web/src/LogStore.test.ts, web/src/LogStore.ts
Please review the following commits I made in branch nicks/logstore:
899bed4e6ed60c777097dd7e6c7d4b266c3845d9 (2020-01-22 13:55:09 -0500)
web: rewrite internal implementation of LogStore
The web UI doesn't need the complex log-streaming stuff that the server
needs. This should be a lot simpler and easier to reason about.
=> web: rewrite internal implementation of LogStore

internal/build/options.go, internal/docker/client.go, internal/docker/options.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, pkg/model/image_target.go
- Adds a network argument to the docker_build command
- Plumbs the network argument in docker_build through to the underlying docker build
Fixes: #2483
=> tiltfile: add network argument to docker_buld

internal/cloud/cloud_username_manager.go
Please review the following commits I made in branch nicks/ch4339/spam:
88634c7dff7f38ef8cb615b3fc5033b05b68feab (2020-01-24 13:19:26 -0500)
cloud: lookup errors should be debug logs
=> cloud: lookup errors should be debug logs

go.mod, go.sum, internal/cli/analytics.go, internal/cli/cli.go, vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go, vendor/github.com/windmilleng/wmclient/pkg/analytics/cli.go, vendor/modules.txt
Please review the following commits I made in branch nicks/ch4338/spam:
52f4bd47b05a549b4c120a7aec9bb0a4efffeddf (2020-01-24 13:16:08 -0500)
cli: analytics failures should be debug logs
=> cli: analytics failures should be debug logs

internal/engine/local/execer.go, internal/engine/local/execer_test.go, pkg/procutil/procutil_unix.go
Before: 
If you `tilt up` this branch Tilt would segfault
https://github.com/windmilleng/enhance/compare/dmiller/crash-tilt?expand=1
After:
It starts up fine and doesn't segfault
=> procutil: don't send signals to nil process

internal/engine/buildcontrol/target_queue.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go
Hello @nicks,
Please review the following commits I made in branch nicks/targetqueue:
2dd42cec5aca64ca67d3ad5fba03a6a745b1f857 (2020-01-24 14:14:37 -0500)
engine: move targetqueue into buildcontrol
=> engine: move targetqueue into buildcontrol

integration/local_resource_test.go
This was failing in CI, I repro'd flakiness locally in the CI image, fixed it so that it passed 100/100 times, reenabled, and now it's still failing in CI.
=> integration: disable local_resource test

internal/cli/build.go, scripts/install.sh
Hello @nicks,
323b2b2da5143dc8520a4baf003f58a8585c1b0b (2020-01-24 17:54:40 -0500)
bump version to v0.11.3
=> bump version to v0.11.3

internal/docker/client.go
Hello @nicks,
Please review the following commits I made in branch nicks/buildkitsession:
a4ee99f4fefa2f707b291129e060b3fecc58ccf5 (2020-01-24 18:28:07 -0500)
docker: fix a bug where we were leaving buildkit sessions open
=> docker: fix a bug where we were leaving buildkit sessions open

CONTRIBUTING.md
Probably because original roadmap.md was removed
=> Link to GitHub project board for Roadmap

integration/local_resource_test.go
this passed 600x in circleci, so hopefully we're good now...
=> integration: bump timeout and reenable local_resource test

web/src/LogStore.test.ts, web/src/LogStore.ts
Please review the following commits I made in branch nicks/progress2:
7956c7eb14137b93e16ceca4dd625105687b2736 (2020-01-27 15:42:29 -0500)
web: fix an off-by-one error in how we show progress logs
=> web: fix an off-by-one error in how we show progress logs

internal/build/buildkit_printer.go, internal/build/testdata/TestBuildkitPrinter/echo-hi-success-verbose.master.txt, internal/build/testdata/TestBuildkitPrinter/echo-hi-success.master.txt, internal/build/testdata/TestBuildkitPrinter/multistage-fail-copy.master.txt, internal/build/testdata/TestBuildkitPrinter/multistage-fail-run.master.txt, internal/build/testdata/TestBuildkitPrinter/multistage-success.master.txt, internal/build/testdata/TestBuildkitPrinter/rust-success.master.txt, internal/build/testdata/TestBuildkitPrinter/sleep-cache.master.txt, internal/build/testdata/TestBuildkitPrinter/sleep-success.master.txt
Please review the following commits I made in branch nicks/progress3:
243ae8a3ad70d1d06f926dda6c96c3119c992e31 (2020-01-27 16:38:51 -0500)
build: use progress ids to print buildkit output more effectively
=> build: use progress ids to print buildkit output more effectively

Makefile
Hello @nicks,
85a1c6713f3fd551fa2ef00a771c90e061e193fe (2020-01-27 18:49:11 -0500)
makefile: increase the timeout on golangci-lint, and make sure it's using vendoring
=> makefile: increase the timeout on golangci-lint, and make sure it's using vendoring

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller_test.go
Please review the following commits I made in branch nicks/ch4318/locals:
958d40ba14fce685182488a2a3e4e309c40131af (2020-01-27 21:12:32 -0500)
buildcontrol: don't parallelize local_resource with other commands
=> buildcontrol: don't parallelize local_resource with other commands

pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go, pkg/model/logstore/reader.go
Please review the following commits I made in branch nicks/continuingstring:
902a694256e1f2cfc52d3e6731360bdf7e767390 (2020-01-28 13:15:50 -0500)
logstore: Return structured log lines for printing to stdout
=> logstore: Return structured log lines for printing to stdout

internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/target_queue.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_state_tree.go, internal/engine/upper_test.go, internal/store/build_result.go
Please review the following commits I made in branch maiamcc/better-image-build-results:
2d2576938775177aa72a6d36b09a356b9a2ac26a (2020-01-28 12:58:48 -0500)
separate localref and clusterref in ImageBuildResult
=> store: separate localref and clusterref in ImageBuildResult [ch4292]

integration/tilt_args_test.go
Hello @nicks,
ad3a0355b0c5a99138838619a6e47d91afc827dd (2020-01-28 15:14:15 -0500)
integration: use the write log writer, so we get an error report if this command fails
=> integration: use the write log writer, so we get an error report if this command fails

integration/tilt_args_test.go
Please review the following commits I made in branch nicks/argsfailure:
e6102eb5983a0a4e15381940278dce5b75dd9765 (2020-01-28 18:26:52 -0500)
integration: fix a race condition in the tilt args integration test
=> integration: fix a race condition in the tilt args integration test

.circleci/config.yml
This strategy is based off of [this CircleCI doc](https://circleci.com/docs/2.0/caching/#restoring-cache).
Basically:
1. After each run cache the golangci-lint cache by git revision. Should look something like `golangci_lint_be4d2b3`.
2. Before each run look for a cached version of this revision. I expect this will rarely hit, except in rebase cases. If it can't be found fallback to _the most recently created_ cached version.
=> circleci: cache golangci-lint cache on git rev, fallback to most recent otherwise

internal/build/image_builder.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/hud/disabled_hud.go, internal/hud/hud.go, internal/hud/hud_test.go, internal/hud/printer.go, internal/hud/printer_test.go, internal/hud/wire.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go
Please review the following commits I made in branch nicks/continuingstring2:
0523866877fa30469becf8855f10e40139993f05 (2020-01-28 14:56:32 -0500)
build: do progress backoff at render-time instead of at logging-time
611beb68a74d97fae1799bea0eda8b5b36e39c49 (2020-01-28 14:50:35 -0500)
logstore: Return structured log lines for printing to stdout
=> build: do progress backoff at render-time instead of at logging-time

internal/container/default_registry.go, internal/tiltfile/docker.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_test.go
This causes a stack trace to be printed during Tiltfile execution
which makes it more obvious where this error is coming from.
Previously the error would only surface when the default registry
was being transformed in to the engine state model, at which point
we don't know what line it occurred on.
Fixes #2768
=> tiltfile: error in default_registry if registry is not canonical

internal/build/container_test.go, internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/build/image_builder.go, internal/build/test_utils.go, internal/container/reference.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_and_cache_builder.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go
in next commit, will wire up tiltfile to allow someone to set distinct
localRef/clusterRef, and will make a unit test
=> build/engine: inject clusterRef (rather than imageRef) into YAML

internal/build/image_builder.go, internal/hud/printer.go, internal/hud/printer_test.go, pkg/logger/fields.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go
Please review the following commits I made in branch nicks/mustprint:
19cb7fbec692022e29906047ae2eba0b9a2f68a9 (2020-01-29 13:21:55 -0500)
hud: when printing push output, make sure we always print the last "finished" line
=> hud: when printing push output, make sure we always print the last "finished" line

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/k8srollout/podmonitor.go, internal/engine/k8srollout/podmonitor_test.go, internal/engine/pod.go, internal/engine/subscribers.go, internal/engine/upper_test.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/pods:
7bc6c2d2613712b52d09ea1e9973a7b436871eed (2020-01-28 20:31:13 -0500)
k8srollout: first pass at a pod rollout monitor
=> k8srollout: first pass at a pod rollout monitor

integration/analytics_test.go, internal/analytics/env.go, internal/analytics/tilt_analytics.go, internal/analytics/tilt_analytics_test.go, internal/cli/up.go, internal/engine/upper_test.go, internal/hud/webview/analytics_nudge_test.go, internal/hud/webview/convert_test.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/ch3992/dnt:
3f73115e3b96961d018ebf66b6bcf0dbaf30ecc7 (2020-01-30 12:23:37 -0500)
analytics: disable tilt analytics when DO_NOT_TRACK=1, CI=1
=> analytics: disable tilt analytics when DO_NOT_TRACK=1, CI=1

internal/build/custom_builder_test.go, internal/container/default_registry.go, internal/container/default_registry_test.go, internal/container/reference.go, internal/engine/extractors.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/upper_test.go, internal/k8s/exploding_client.go, internal/k8s/registry.go, internal/k8s/registry_test.go, internal/store/build_result.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go, pkg/model/manifest.go, pkg/model/manifest_test.go
not strictly necessary but i think this fits better with our mental models
of localRef vs. clusterRef -- i.e. clusterRef is only specified in very specific
situations, and otherwise, we assume that localRef is usaable everywhere
=> container: make clusterref optional, return localref if no clusterref provided

internal/engine/analytics/analytics_reporter_test.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/configs/configs_controller_test.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, pkg/model/custom_build_test.go, pkg/model/image_target.go, pkg/model/target_test.go
as of #2883 this func needs to either return or igore/panic on an error.
since it seems to only be used in tests right now, i'm having it
panic on the error instead of returning in, so changed the name
to reflect.
=> rename NewImageTarget to MustNewImageTarget to make a future PR smaller

Makefile, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
`go test -count 1 -tags skipcontainertests ./internal/tiltfile`: 23s
`go test -count 1 -tags skipcontainertests,skipdockercomposetests ./internal/tiltfile`: 5s
`go test -count 1 -tags skipcontainertests ./...`: 68s
`go test -count 1 -tags skipcontainertests,skipdockercomposetests ./...`: 49s
=> shorttest: no more tiltfile DC tests

.circleci/Dockerfile.integration, .circleci/config.yml
Hello @nicks,
89b556d52e37dc3bfc3475505e2c0a42ba9925ad (2020-01-31 15:34:20 -0500)
circleci: upgrade docker in the integration test container. They changed the URL format, so our download script was downloading an old version
=> circleci: upgrade docker in the integration test container. They changed the URL format, so our download script was downloading an old version

internal/engine/k8swatch/actions.go, internal/engine/k8swatch/pod_watch.go, internal/engine/pod.go, internal/engine/pod_test.go, internal/engine/upper.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/deletepod:
5294b2349e7d2b3f4546cbd79ac85b8558fa5113 (2020-01-31 14:47:02 -0500)
engine: handle pod deletion properly
This is part of a larger change to make our watch code more
generalizable, so that we can watch ReplicaSets and Deployments
=> engine: handle pod deletion properly

internal/tiltfile/live_update.go
hopefully addresses #2870
in so doing, might break windows containers -- which we never purported
to support anyway, so I don't think this is a regression? maybe?
=> tiltfile: always use unix abs-path check when verifying live update remote path

internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/registry.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/autodetect:
704416f3730df5657d19b02cbbb8c22d91d8d436 (2020-02-04 14:42:15 -0500)
k8s: rename private registry to local registry, to reduce confusion
=> k8s: rename private registry to local registry, to reduce confusion

internal/engine/image_build_and_deployer.go, internal/k8s/registry.go, internal/k8s/registry_test.go
Please review the following commits I made in branch nicks/autodetect2:
cc5b8d24210338b7b80fbd99a63affffb8eb1612 (2020-02-04 15:56:06 -0500)
k8s: auto-detect local registry from node labels
d785b12a7bf1b6e50f8157c3397d118bf4b92e9b (2020-02-04 14:44:49 -0500)
k8s: rename private registry to local registry, to reduce confusion
=> k8s: auto-detect local registry from node annotations

Makefile
This will cause CI to fail if `yarn install`
causes an update to `yarn.lock`.
This should prevent drifting lockfiles.
=> ci: use frozen yarn lockfile

pkg/model/logstore/logline.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go
Hello @hyu,
Please review the following commits I made in branch nicks/linebuilder:
5475707bfee549e87bb1481fa4525faa5cf05ccc (2020-02-04 19:06:52 -0500)
logstore: factor out a lineBuilder to separate accumulation of segments from printing lines
=> logstore: factor out a lineBuilder to separate accumulation of segments from printing lines

README.md, integration/analytics_test.go, internal/analytics/tilt_analytics.go, internal/analytics/tilt_analytics_test.go, internal/cli/up.go, internal/engine/analytics/analytics_updater.go, internal/engine/analytics/analytics_updater_test.go, internal/engine/upper.go, internal/hud/server/server.go, internal/hud/server/server_test.go, web/src/AnalyticsNudge.tsx, web/src/__snapshots__/AnalyticsNudge.test.tsx.snap
Hello @dbentley, @jazzdan, @maiamcc,
Please review the following commits I made in branch nicks/ch4422/analytics:
37c2f58a6f1013f1f59aec7df6a4e376b087d039 (2020-02-05 13:55:08 -0500)
analytics: send anonymized analytics by default. update the README and nudge to reflect this
We're having trouble understanding the early part of the Tilt experience.
Are people making it to the web UI?
Are they able to run a project successfully?
Are they able to set up a local kubernetes cluster?
We're going to try enabling it by default on tilt v0.12 and see
what happens. Previous PRs have cleaned up some of the existing
analytics behavior so that it doesn't pick up CI and respects DO_NOT_TRACK=1,
so we feel more comfortable with this.
* Commits are …
=> analytics: send anonymized analytics by default. update the README and nudge to reflect this

internal/engine/configs/configs_controller_test.go, internal/engine/watchmanager_test.go, internal/ospath/ospath_test.go
a6c9d4d87d25177f8c6e30466fc996fd2f1fe0cb (2020-02-06 15:38:51 -0500)
Revert "engine/ospath: use tempdir.Chdir in more places (#2907)"
This reverts commit 284ed0748138e3b33d96cd32810c7e6af0ea1bab.
=> Revert "engine/ospath: use tempdir.Chdir in more places (#2907)"

internal/engine/configs/configs_controller_test.go, internal/engine/watchmanager_test.go, internal/ospath/ospath_test.go
Please review the following commits I made in branch nicks/revert2:
b9c22b53abb9a6c5a26d154ff0e5325df7f0f673 (2020-02-06 15:47:53 -0500)
Revert "Revert "engine/ospath: use tempdir.Chdir in more places (#2907)""
This reverts commit a6c9d4d87d25177f8c6e30466fc996fd2f1fe0cb.
=> Revert "Revert "engine/ospath: use tempdir.Chdir in more places (#2907)""

internal/engine/image_build_and_deployer_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/fix-local-registry-log-spam:
9e7ecd665ae90c5f25162fdd588189680c0f0fd7 (2020-02-06 15:31:51 -0500)
tiltfile: move logging about local registry out of for-loop to reduce spam [ch4451]
=> tiltfile: move logging about local registry out of for-loop to reduce spam [ch4451]

internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/local_resource.go, internal/tiltfile/telemetry/telemetry.go, internal/tiltfile/telemetry/telemetry_test.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/value.go
At the moment, any place a command is specified in the Tiltfile, it's specified as a string, which then gets wrapped in an sh -c '', which forces the user to deal with shell evaluation.
This means that any time a user constructs a command from starlark variables, they potentially have to worry about those starlark variables containing characters with special meaning to the shell, and we provide no way to escape them, so there's not really anything to be done.
Allow commands to be specified as either shell-interpreted strings or raw argv, [Dockerfile-style](https://docs.docker.com/engine/reference/builder/#run).
This PR pretty much consists of:
1. add a new `value.ValueToCmd` function that takes a `starlark.Value` and converts the `string|[]string` to a `model.Cmd`, as appropriate
2. …
=> tiltfile: allow commands to be specified as arrays

internal/tiltfile/extension/store.go, internal/tiltfile/extension/store_test.go
This explicitly only stores the contents of the module's Tiltfile and doesn't deal with any of the other metadata yet, just to unblock work on other parts of functionality.
=> extension: define extension storage API w/ filesystem implementation

internal/engine/k8swatch/pod_watch_test.go
TestPodWatchExtraSelectors [checks f.manifests](https://github.com/windmilleng/tilt/blob/4f58f76bd3a1b7fc1ab666059220912c7f5ed3e8/internal/engine/k8swatch/pod_watch_test.go#L121) immediately after `assertObservedPods` returns, but it is possible for `assertObservedPods` to return before `f.manifests` has been updated.
=> k8swatch: fix flaky pod watch test

internal/tiltfile/encoding/extension.go, internal/tiltfile/encoding/json.go, internal/tiltfile/encoding/json_test.go, internal/tiltfile/encoding/starlark.go, internal/tiltfile/encoding/yaml.go, internal/tiltfile/encoding/yaml_test.go, internal/tiltfile/tiltfile_state.go
the complement of `decode_yaml` and `decode_json`, i.e., from a starlark object to a yaml/json-encoded string (or, really, a `Blob`, to make it easier to pass to `k8s_yaml`)
also: changed `decode_yaml` and `decode_json` to take a `Union[str|Blob]` instead of a `str`, since it's likely most of the inputs to those functions will be `Blob`s already (e.g., from the output of `read_file` or `local`)
I really wanted to name all these `yaml.load` / `yaml.loads` / `yaml.dumps`, but `load` is a keyword in starlark, making that impossible :(
=> tiltfile: add encode_yaml and encode_json

internal/build/container_test.go, internal/build/options.go, internal/docker/client.go, internal/docker/options.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/issue2839:
d6549ee75813d968656a4739f744418f4fcd78f4 (2020-02-11 14:52:08 -0500)
tiltfile: add docker_build(extra_tag=...). Fixes issue 2839
=> tiltfile: add docker_build(extra_tag=...). Fixes issue 2839

internal/dockercompose/client.go
Please review the following commits I made in branch nicks/issue2871/parallel:
0951cfb27fc9b577376f0d0fc4ea6de8b90d9b07 (2020-02-11 15:13:41 -0500)
dockercompose: don't run docker-compose up in parallel. Fixes issue #2817
=> dockercompose: don't run docker-compose up in parallel. Fixes issue #2817

internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
what's the worst that could happen?
sample use case:
I want to write a function that traverses k8s yaml and sets namespaces
=> tiltfile: enable recursion

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/k8s/image.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/issue2918/args:
46ee4002f0414fb20054c24c0682194d05ee5473 (2020-02-11 15:53:05 -0500)
k8s: entrypoint override shouldn't affect container args. Fixes issue #2918
=> k8s: entrypoint override shouldn't affect container args. Fixes issue #2918

internal/cli/build.go, scripts/install.sh
Hello @nicks,
ac991e143e5a1741373e38c5ce97413d6e2fc1b3 (2020-02-12 12:14:52 -0500)
cli: bump to v0.12.1
=> cli: bump to v0.12.1

internal/dockerfile/ast.go, internal/dockerfile/dockerfile_test.go, internal/dockerfile/inject_test.go
Please review the following commits I made in branch nicks/issue2943:
03bdc9e205a085e36ef39c20567a4e96e04bb3b0 (2020-02-13 00:35:23 -0500)
dockerfile: handle ARG variables when injecting images. Fixes issue #2943
=> dockerfile: handle ARG variables when injecting images. Fixes issue #2943

internal/engine/k8srollout/podmonitor.go, internal/engine/k8srollout/podmonitor_test.go, internal/engine/k8srollout/testdata/TestMonitorReady_master
- Use a dotted box-drawing vertical to visually group Pod Rollout events
- The aligned durations makes it clearer when something is Pending, without using an emoji (which doesn't currently render well on RTY)
- No longer using the ❌ emoji, which was alarming
Please note this PR does not include additional visual changes to the Web UI, which may come as a separate PR.
```
Tracking new pod rollout (blog-site-55bf44cbf9-lfx2n):
┊ Scheduled       - <1s
┊ Initialized     - (…) Pending
┊ Ready           - (…) Pending
```
The "Not.." progress events have a slightly different prefix:
```
┊ Scheduled       - <1s
┃ Not Ready       - (ContainersNotReady): containers with unready status: [docs-site tilt-synclet]
```
=> k8srollout: tweak pod rollout logs

web/src/LogStore.test.ts, web/src/LogStore.ts
Sometimes logs show up in the global log pane, but not the resource log pane, even though the UI clearly shows it's aware those logs came from that resource.
It turns out this happens when there is a span with no segments. I was able to repro this a few times by running DC resources prior to the networking fix, which resulted in the creation of both build and runtime spans, but the runtime span would have no segments. I haven't looked into why we create a runtime span with no segments, which feels like it's also a bug, but I think the fix in this PR is desirable either way.
In the logHelper filteredLog path, when a span has no segments, it ends up keeping its default firstLineIndex of -1, and we exit out with an empty list of lines, even if a prior span for that manifest *did* have …
=> web: fix potential empty resource log

internal/tiltfile/config/bool.go, internal/tiltfile/config/config.go, internal/tiltfile/config/config_def.go, internal/tiltfile/config/config_test.go, internal/tiltfile/config/string.go, internal/tiltfile/config/string_list.go
Lots of use cases for config settings don't actually want a list of strings, and it's annoying that we make users deal with that type when it's so cheap to just provide other types (and when pretty much all other arg-parsing APIs provide other types). Especially since for a bool you really want a flag, but the existing syntax makes you say `--foo true`
add setting types for bool and string
=> tiltfile: add config.define_{bool,string}

internal/tiltfile/encoding/extension.go, internal/tiltfile/encoding/fixture.go, internal/tiltfile/encoding/yaml.go, internal/tiltfile/encoding/yaml_test.go, internal/tiltfile/tiltfile_state.go
addresses #2960 
Various k8s tools involve YAML streams rather than YAML docs (i.e., multiple YAML docs in the same string, separated by "\n---\n"). `decode_yaml` / `read_yaml` / `encode_yaml` don't handle these (and worse, `decode_yaml` and `read_yaml` just return the first doc in the stream and throw the rest away)
1. Add `decode_yaml_stream`, `read_yaml_stream`, `encode_yaml_stream` functions, which operate work on streams of YAML docs
2. Make `decode_yaml` and `read_yaml` fail with an error pointing at the `_stream` variants if they're passed a stream, to protect people from unintentionally silently dropping yaml docs past the first
Another option would have been to just have `decode_yaml` / `read_yaml` return an array of objects when there's a stream, but it seems like it'd be …
=> tiltfile: add read/decode/encode_yaml_stream functions

internal/build/tar.go
- Actualy ADD and COPY failed in Docker file if we use windows path.
The bug is that the path are stored as absolute with full volume name and not as relative as it should be when using unix path
=> Fix tar creation to accept windows path

web/src/Sidebar.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Thanks to feedback from @smombartz, I realized that it makes more sense for the last update time to go above the duration. The duration is a secondary bit of information about the last updated build.
=> web: adjust layout of timestamps

web/src/Sidebar.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
fixes #2998 
Resources are not clickable in the webui while they're building.
This appears to be because their ::after element is stealing their clicks.
Change the ::after element to not steal clicks. I don't know much about what is going on here or if there's a more elegant solution and just went with the first SO answer I found after diagnosing the problem.
=> web: fix clicking on building resources

web/src/ResourceInfo.tsx
Clubhouse story: https://app.clubhouse.io/windmill/story/4269/no-spacing-between-multiple-k8s-port-forwards
| Before / After | Screenshot |
| --- | --- |
| Before | <img width="804" alt="multiple-before" src="https://user-images.githubusercontent.com/10860550/75098955-21415900-558a-11ea-828a-315d0178de8c.png"> | 
| After | <img width="776" alt="multiple-after" src="https://user-images.githubusercontent.com/10860550/75098957-26060d00-558a-11ea-89fe-25e231b4b6a8.png"> |
| Before / After | Screenshot |
| --- | --- |
| Before | <img width="395" alt="single-before" src="https://user-images.githubusercontent.com/10860550/75098942-ffe06d00-5589-11ea-9428-d8737d17072a.png"> | 
| After |  <img width="401" alt="single-after" src="https://user-images.githubusercontent.com/10860550/75098946-0373f400-5 …
=> Add space between multiple PortForwardLinks

internal/hud/hud.go, internal/hud/renderer.go
Hi,
Running with go --race, go complain there is a data race :
WARNING: DATA RACE
Write at 0x00c000694330 by goroutine 51:
github.com/windmilleng/tilt/internal/hud.(*Renderer).SetUp()
tilt/internal/hud/renderer.go:315 +0x3a7
github.com/windmilleng/tilt/internal/hud.(*Hud).Run()
tilt/internal/hud/hud.go:95 +0x1fb
github.com/windmilleng/tilt/internal/cli.(*upCmd).run.func1()
tilt/internal/cli/up.go:144 +0x10d
golang.org/x/sync/errgroup.(*Group).Go.func1()
go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x78
Previous read at 0x00c000694330 by goroutine 56:
github.com/windmilleng/tilt/internal/hud.(*Hud).refreshSelectedIndex()
tilt/internal/hud/hud.go:338 +0x5d
github.com/windmilleng/tilt/internal/hud.(*Hud).OnChange()
tilt/internal/hud/hud.go:294 …
=> fix data race between hud and renderer

internal/build/image_builder.go, internal/hud/hud.go, internal/hud/renderer.go
Hi another data race complain, the last catch by go --race. 
After correcting this and the previous one no warning are left.
WARNING: DATA RACE
Read at 0x00c0001fc630 by goroutine 63:
github.com/windmilleng/tilt/internal/build.(*dockerImageBuilder).buildFromDf.func1()
tilt/internal/build/image_builder.go:229 +0x57
Previous write at 0x00c0001fc630 by goroutine 119:
github.com/windmilleng/tilt/internal/build.(*dockerImageBuilder).buildFromDf()
tilt/internal/build/image_builder.go:238 +0xab7
github.com/windmilleng/tilt/internal/build.(*dockerImageBuilder).BuildImage()
tilt/internal/build/image_builder.go:70 +0x39e
github.com/windmilleng/tilt/internal/engine.(*imageAndCacheBuilder).Build()
tilt/internal/engine/image_and_cache_builder.go:40 +0x654 …
=> Fix data race image builder

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/ch4317/busy:
04dc19fa7924f31488532c306f9ed2a3fe917419 (2020-02-25 12:47:20 -0500)
buildcontrol: don't parallelize updates that share images
=> buildcontrol: don't parallelize updates that share images

internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go
Please review the following commits I made in branch nicks/cwd:
b67292e74cf2fa1d205e27cf7dfef5164d07eaa9 (2020-02-26 12:58:16 -0500)
tiltfile: add os.getcwd()
=> tiltfile: add os.getcwd()

internal/engine/buildcontroller_test.go, internal/engine/pod.go, internal/store/build_result.go, internal/store/runtime_state.go, internal/testutils/podbuilder/podbuilder.go
To more explicitly spell out the bad case here:
1. User performs a live update, which recompiles and restarts the process
2. While the process is starting up, the readiness probe is failing for 5 seconds
3. User performs another live update while the readiness probe is still failing
4. Since the container is not ready, tilt says there's no container to live update, and does a full image build + redeploy
It seems like in practice this doesn't cause an issue with pods getting updated before their ready, in my manual testing.
Fixes #3000
=> store: we should still live update unready containers

pkg/logger/func_logger.go, pkg/logger/func_logger_test.go
Please review the following commits I made in branch nicks/filter:
fd0af381ecbb395594f5888d7d5e01601a044a90 (2020-02-26 15:00:18 -0500)
logger: fix a bug in log filtering
Because of this bug, low-level debug messages from the port-forwarder
were getting printed to the log stream.
=> logger: fix a bug in log filtering

web/src/HUD.tsx, web/src/LogPane.stories.tsx, web/src/LogStore.ts, web/src/logs.ts, web/src/trace.test.ts, web/src/trace.ts, web/src/types.ts
Please review the following commits I made in branch nicks/logstore:
defa2b193c6ce594800ed0277b0bf2fadb0f95d9 (2020-02-26 17:41:36 -0500)
web: add data model for trace navigation, broken off from https://github.com/windmilleng/tilt/pull/3008
=> web: add data model for trace navigation, broken off from https://github.com/windmilleng/tilt/pull/3008

internal/cli/tiltfile_result.go
Hello @,
Please review the following commits I made in branch maiamcc/tiltfile-result-docstring:
ad8511e8b42132d1c8213336bbde9f825abe5354 (2020-02-27 17:46:48 -0500)
cli: docstring for tiltfile-result
=> cli: docstring for tiltfile-result

internal/tiltfile/io/io.go, internal/tiltfile/io/io_test.go
The (`read_file docs`)[https://docs.tilt.dev/api.html#api.read_file] state:
> If the file_path does not exist and default is not None , default will be returned. In any other case, an error reading file_path will be a Tiltfile load error.
However, the actual implementation is that `default` has a default value of `""` rather than `None`, and unpacks the arg into a string, so it's not actually possible to get read_file to error on a missing file.
change `read_file` to error if the file doesn't exist and default is unspecified
We can now get errors when `read_file` targets are missing!
This might break users that were relying on the existing behavior.
1. It's easy for them to get the existing behavior back by adding a `default=""` to their `read_file` call.
2. My gut is that the documented …
=> tiltfile: make read_file error on missing file if default unspecified

internal/k8s/env.go, internal/k8s/env_test.go
This improves the environment autodetection logic by matching on the prefix of the cluster name rather than exactly on the cluster name. This allows users to encode more cluster information in the cluster name when, eg, using minikube. This is for https://github.com/windmilleng/tilt/issues/3024
=> Detect k8s environment using the prefix of the cluster name, instead of an exact match

internal/build/test_utils.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/docker/client.go, internal/docker/client_test.go, internal/docker/env.go, internal/engine/k8swatch/service_watch.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/ip.go, internal/synclet/wire_gen.go
Please review the following commits I made in branch nicks/ch4928/minikube:
745a08f35ee6178b049675a0d012e772bcc07751 (2020-02-28 17:00:27 -0500)
k8s: move all minikube calls out of wire injection. Fixes https://github.com/windmilleng/tilt/issues/3021
=> k8s: move all minikube calls out of wire injection. Fixes https://github.com/windmilleng/tilt/issues/3021

internal/hud/hud.go, internal/hud/hud_test.go, internal/hud/renderer.go, internal/hud/renderer_test.go, internal/rty/canvas.go, internal/rty/components.go, internal/rty/error.go, internal/rty/interactive_tester.go, internal/rty/layouts_benchmark_test.go, internal/rty/layouts_test.go, internal/rty/render.go, internal/rty/scroll_test.go
Please review the following commits I made in branch nicks/ch4973/crash:
f746c53c911814e2ab2f5a6da35d4dcf123079f7 (2020-03-02 16:49:56 -0500)
rty: rendering errors shouldn't totally break Tilt. Fixes https://github.com/windmilleng/tilt/issues/3039
Given that Tilt has a browser UI now, TUI rendering errors shouldn't be world-stopping.
For now, let's just throw them out silently and see what happens.
The test frameworks still check for errors.
=> rty: rendering errors shouldn't totally break Tilt. Fixes https://github.com/windmilleng/tilt/issues/3039

internal/container/runtime.go, internal/k8s/runtime.go, internal/k8s/runtime_test.go
Please review the following commits I made in branch nicks/crio:
0d5cf9e5245bb4f8af1340ff47ee90d5f4daa419 (2020-03-03 17:55:16 -0500)
k8s: report runtime differently on read failure
=> k8s: report runtime differently on read failure

internal/cli/build.go, scripts/install.sh
Hello @nicks,
05ea29353b8b157c2e5a7aafdcdd40bfaa7732aa (2020-03-06 17:47:04 -0500)
cli: bump release to v0.12.6
=> cli: bump release to v0.12.6

internal/cli/up.go, internal/cli/up_test.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/cloud/io.go, internal/cloud/io_test.go, internal/cloud/snapshot_uploader.go
Please review the following commits I made in branch nicks/ch5077/dump:
09a457459fac84275ca5efe59c3580a2b51f0f5a (2020-03-06 15:03:53 -0500)
cli: dump the snapshot to a file when exiting. Fixes https://github.com/windmilleng/tilt/issues/3049
=> cli: dump the snapshot to a file when exiting. Fixes https://github.com/windmilleng/tilt/issues/3049

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/upper_test.go, internal/k8s/entity.go, internal/k8s/entity_test.go, internal/k8s/testyaml/testyaml.go, internal/store/build_result.go, internal/store/json_test.go
a user in #tilt reported consistent "ExecUpdater does not support `restart_container()` step" errors
even tho they expected tilt to use the Synclet.
the reverted commit is the cause: as a prerequiste to using the synclet, we check
the last result for the k8s target to see if it has the `HasEligibleSynclet` flag.
However, this didn't work in practice because, when we construct a buildEntry,
we [don't add k8s results to the buildStateSet](https://github.com/windmilleng/tilt/blob/136f1624c77c8eb585c6660c89a2fedba992c0a1/internal/engine/buildcontroller.go#L191);
no k8s result ever made it to the new code that checks the synclet eligibility flag.
will revisit this PR soon to make it do the right thing; for now, just revert to
fix the break.
=> Revert "engine: if we fail to inject the synclet into a resource, try to recover gracefully (#3050)"

.circleci/Dockerfile, .circleci/Dockerfile.integration, .circleci/config.yml, CONTRIBUTING.md, go.mod, vendor/modules.txt
Hello @nicks,
Please review the following commits I made in branch nicks/go14:
27f0f56bc4e03a7ee88ffc616420d48448af744e (2020-03-09 19:05:15 -0400)
go.mod: upgrade to go 1.14
=> go.mod: upgrade to go 1.14

internal/cli/build.go, scripts/install.sh
Please review the following commits I made in branch maiamcc/bump-0.12.7:
0fdbf6d10e03987f774a0f9f8febd0b21c159c03 (2020-03-09 18:13:05 -0400)
bump version to 0.12.7
=> bump version to 0.12.7

web/src/HUDLayout.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/boxshadow:
6d4915f6b0645fccae792ccaf52ba26da961670b (2020-03-06 17:07:49 -0500)
web: fix the header box-shadow, which looks like it broke in the transition from scss -> styled-components
=> web: fix the header box-shadow, which looks like it broke in the transition from scss -> styled-components

web/src/ShareSnapshotModal.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
Related story: https://app.clubhouse.io/windmill/story/5317/check-that-all-user-facing-references-to-tilt-cloud-are-not-tiltcloud
=> Change `TiltCloud` to be `Tilt Cloud`

internal/k8s/registry.go, internal/k8s/registry_test.go
Please review the following commits I made in branch nicks/ch5539/registry:
6838a1549c3e5dd9ac51916a04a39f9e4857f61e (2020-03-20 18:28:36 -0400)
k8s: add warnings if you're not using a local registry but should be
=> k8s: add warnings if you're not using a local registry but should be

internal/k8s/label.go, internal/k8s/label_test.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/ch5648:
7b47d1fe4b852a275202d0f26c3c19667c3858db (2020-03-24 19:07:05 -0400)
k8s: make the label injector handle more types. Fixes https://github.com/windmilleng/tilt/issues/3111
=> k8s: make the label injector handle more types. Fixes https://github.com/windmilleng/tilt/issues/3111

internal/cloud/cloud_username_manager.go, internal/cloud/cloud_username_manager_test.go
/api/whoami is making a GET request with a body, which blows up on some proxies / caches
besides, we don't really want it to get cached anyway
make it a POST
=> cloud: change whoami to POST

Makefile
Hello @nicks,
Please review the following commits I made in branch nicks/makefile:
d3e5750a2685690224464b23618352614f86727e (2020-03-26 14:41:29 -0400)
makefile: move comments out of makefile rules
This implicitly turns the rule into a bash script.
This breaks the rule on Windows.
It's not even good on Linux, because it means that
running the rule prints the comment every time.
=> makefile: move comments out of makefile rules

internal/engine/upper_test.go, internal/testutils/httptest/http_client.go
Please review the following commits I made in branch nicks/httptest:
a722fe8b30ea6ca5bb9f89122372fdf6b5731daa (2020-03-26 16:44:33 -0400)
httptest: fix a bug in the fake http client
A reader can only be consumed once, so returning the same response
reader multiple times doesn't do what you'd expect.
Reduces a lot of the error spam in engine tests
=> httptest: fix a bug in the fake http client

internal/cli/build.go, scripts/install.sh
Hello @nicks,
c7ff56c73daec67b54ef081ab001d6bcdcdb3c96 (2020-03-26 20:18:53 -0400)
bump version to v0.12.10
=> bump version to v0.12.10

internal/testutils/tempdir/temp_dir_fixture.go, internal/tiltfile/tiltextension/extension_test.go, internal/tiltfile/tiltextension/store_test.go
Please review the following commits I made in branch nicks/wintest:
bdea44e6911428898a40731daad0fa175ff47227 (2020-03-26 18:27:34 -0400)
tempdir: fix a bug where we were calling Chdir on an empty dir
=> tempdir: fix a bug where we were calling Chdir on an empty dir

internal/build/tar.go, internal/build/tar_test.go
Please review the following commits I made in branch nicks/ch5780/socket:
585dc76e9eec476e3952e3f0d55141524bf00299 (2020-03-27 10:11:43 -0400)
build: skip sockets in docker build contexts. Fixes #3107
=> build: skip sockets in docker build contexts. Fixes #3107

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/exit/actions.go, internal/engine/exit/controller.go, internal/engine/exit/controller_test.go, internal/engine/subscribers.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/store.go, internal/store/testing_store.go
Please review the following commits I made in branch nicks/exitcontrol:
7e6200481f6d56511a083f62c6e03de21b7c186d (2020-03-27 17:53:56 -0400)
enging: move process exiting logic into exit.Controller
8f244fca99878b79388b4df04aea134ca5652651 (2020-03-27 17:11:32 -0400)
store: Simplify subscription notification
In the old world, every Notify() would create a new goroutine.
The goroutine would block until the subscriber was done processing the last event,
then double-check if it still needed to process.
This made debugging difficult, because you could have 1000s of
goroutines blocked on a single slow subscriber.
In the new world, there are at most two goroutines in flight.
* Code …
=> enging: move process exiting logic into exit.Controller

internal/watch/notify_test.go, internal/watch/watcher_naive.go, internal/watch/watcher_naive_test.go
Hello @nicks,
00477417478e61a0a30261f688100cce3b8247b9 (2020-03-30 13:02:20 -0400)
Revert "watch: fix inotify tests on windows"
This reverts commit 74ac7997b1c8f497babbbd499ff1f047563d699a.
=> Revert "watch: fix inotify tests on windows"

web/src/LogPane.test.tsx, web/src/LogPane.tsx
When we take a snapshot with a highlighted snippet, Tilt sets the snippet text to "[object Object]", when it should be setting it to the selected text. This results in cloud.tilt.dev/snapshots showing this:
[This line](https://github.com/windmilleng/tilt/blob/e6198fa9a41c5443dabcb700b04ad6ace538c878/web/src/LogPane.tsx#L208) was probably intended to be `sel.toString()`, and making that change gets us most of the way there. Unfortunately, now that the resource name prefixes are pulled out into separate HTML elements, simply using `sel.toString()` returns something like:
```
fortune
line1
fortune
line2
```
which looks really weird as a preview!
So I did something slightly more complicated, explained in the comments.
=> web: fix snapshot log highlight snippet

internal/tiltfile/os/os_test.go, internal/tiltfile/starkit/environment.go, internal/tiltfile/starkit/environment_test.go, internal/tiltfile/starkit/path.go
When we execute code from a Tiltfile, we set the CWD equal to the path to the Tiltfile at the bottom of the call stack. This prevents us from defining extensions that, e.g., expose a function that declares a `docker_build`, or runs a `local`, with the caller's working directory.
Set the CWD from the currently executing Tiltfile instead of from the callstack.
(laid out more explicitly in unit tests below)
=> starkit: CurrentExecPath is based on what's being loaded rather than the call stack

internal/cli/up.go, internal/containerupdate/synclet_manager.go, internal/containerupdate/synclet_manager_test.go, internal/engine/actions.go, internal/engine/docker_compose_event_watcher.go, internal/engine/exit/controller.go, internal/engine/exit/controller_test.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/runtimelog/podlogmanager_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/watchmanager_test.go, internal/store/engine_state.go, internal/store/mode.go
Please review the following commits I made in branch nicks/enginemode:
0f575734a07faa0d1bca4293b616a742a7191a0f (2020-03-31 12:30:42 -0400)
store: add named execution modes
Make the default mode ("up") on the CLI the same as the default mode in the engine
=> store: add named execution modes

internal/cli/down_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/k8s/target.go, internal/testutils/manifestbuilder/manifestbuilder.go, pkg/model/k8s_target.go
Please review the following commits I made in branch nicks/yaml:
33c9ffb9969fd93ac9c26d4925bf7266f9b64cfe (2020-04-01 12:30:17 -0400)
k8s: make it easier to create a new K8sTarget with the right internal data structures set
=> k8s: make it easier to create a new K8sTarget with the right internal data structures set

web/src/LogPane.test.tsx, web/src/LogPane.tsx, web/src/LogPaneLine.tsx
Scroll up in the tilt log, highlight some lines, share a snapshot, open the snapshot.
When opening the snapshot, the view scrolls to the highlighted lines
The view scrolls to the bottom of the log
It turns out that we're only scrolling to highlight on componentDidMount, except the highlight state is null at that point, so there's nothing to scroll to. So, let's scroll there on componentDidUpdate.
Also, when we call scrollIntoView, it was putting the top of the highlight at the top of the browser window, so the first few lines were hidden underneath the header (which also means if the highlight was only a couple lines, it'd be entirely hidden under the header!) - I moved it to the center of the screen, instead.
=> snapshots: scroll to highlighted section on load

Makefile, web/src/HUD.tsx, web/src/LogPane.tsx, web/src/LogPaneLine.tsx, web/src/LogStore.ts, web/src/SecondaryNav.tsx, web/src/SidebarIcon.tsx, web/src/analytics.ts, web/src/logs.ts, web/src/selection.ts, web/src/trace.ts, web/src/types.ts
1. ensure js warnings cause `make check-js` to fail
2. fix any such warnings. these fell into a few camps:
- `==` / `!=` instead of `===` / `!==`
- unused variables / imports
- using `.map` on a side-effecting func w/ no return, instead of `.forEach`
=> web: warnings as errors

internal/cli/ci.go, internal/cli/docker_prune.go, internal/cli/down.go, internal/cli/flags.go, internal/cli/tiltfile_result.go, internal/cli/up.go
Please review the following commits I made in branch nicks/file:
124942e3abd23273fa8d92029df0374222a5fe50 (2020-04-02 19:25:57 -0400)
cli: add -f short flag for --file
=> cli: add -f short flag for --file

internal/engine/exit/controller_test.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/pod.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/ch5970/status:
7a152be27e17620fbcc81b74eff45d5848af3ce3 (2020-04-03 14:39:42 -0400)
engine: revamp how we compute RuntimeStatus
In the old way, we would convert a Pod Status struct into a human-readable
reason string. Then we would try to convert the reason string into a
model.RuntimeStatus (one of OK, Pending, Error).
This was fragile and confusing, because the reason string had conflicting
needs. When we made the human-readable bit more descriptive (e.g., including
init container info), we'd break the RuntimeStatus conversion.
In the new way, we compute both RuntimeStatus and the reason string directly
from the PodStatus struct.
Fixes https://github.com/windmilleng/tilt/issues/3177
Code review …
=> engine: revamp how we compute RuntimeStatus

internal/cli/build.go, scripts/install.sh
Please review the following commits I made in branch maiamcc/v0.13.1:
11a0f2e8586f6fd3429f0f388159774c35b1033b (2020-04-09 15:45:27 -0400)
bump version to v0.13.1
=> bump version to v0.13.1

internal/build/test_utils.go, internal/docker/client.go, internal/docker/client_test.go, internal/docker/env.go, internal/k8s/minikube.go, internal/k8s/minikube_fake.go, internal/k8s/minikube_test.go
Please review the following commits I made in branch nicks/ch6163:
ee9f8629c328611ea1b06ddfcdc862ff3fe2c958 (2020-04-10 10:17:26 -0400)
re-enable buildkit on minikube v1.8.0+. Fixes https://github.com/windmilleng/tilt/issues/3192
=> re-enable buildkit on minikube v1.8.0+. Fixes https://github.com/windmilleng/tilt/issues/3192

internal/engine/actions.go, internal/engine/buildcontrol/actions.go, internal/engine/docker_compose_event_watcher.go, internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/time:
baa91cc3f3954be8301fcee3866c29e2800d9118 (2020-04-14 17:20:58 -0400)
engine: pull time.Now out of the state loop, to make it easier to test subtle timing issues
=> engine: pull time.Now out of the state loop, to make it easier to test

internal/build/boil_runs_test.go, internal/build/test_utils.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_build_and_deployer_test.go, internal/engine/local/controller_test.go, internal/engine/local/execer_test.go, internal/engine/local_target_build_and_deployer_test.go, internal/engine/telemetry/controller_test.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/testutils/assert.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/config/config_test.go, internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/local_resource.go, internal/tiltfile/telemetry/telemetry.go, internal/tiltfile/telemetry/telemetry_test.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/value.go, pkg/model/manifest.go, pkg/model/manifest_test.go, pkg/model/service_test.go, pkg/model/squash_test.go
Please review the following commits I made in branch nicks/ch6271/cmd:
f7e7c0a13a73dbab6bc4329589c227236bbd3054 (2020-04-15 11:41:41 -0400)
tiltfile: distinguish host commands from container commands
=> tiltfile: distinguish host commands from container commands

internal/cli/up.go, internal/cli/up_test.go
In Tilt 1.0, we'll hide the HUD by default and make it opt-in via `--hud`. We want to develop the new, hidden-HUD UI prior to actually launching it.
Add a new `--default-tui` argument which is hidden and defaults to true. This is basically a feature flag to enable the 1.0 behavior prior to release. (not using a Tiltfile feature flag since this decision needs to be made before we load the Tiltfile)
=> up: add --default-tui arg

internal/cli/docker_prune.go, internal/container/selector.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/tiltfile/dockerprune/docker_prune.go, internal/tiltfile/dockerprune/docker_prune_test.go, pkg/model/docker_prune.go
Please review the following commits I made in branch nicks/ch6284/prune:
ff8774c73af994c3f591f346ab75e203a94b4db1 (2020-04-16 19:19:35 -0400)
dockerprune: add a setting to keep the most recent N builds of a tag. Fixes https://github.com/windmilleng/tilt/issues/3211
=> dockerprune: add a setting to keep the most recent N builds of a tag. Fixes https://github.com/windmilleng/tilt/issues/3211

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/ch6438/pullpolicy:
7d10e9273a5eb5f5489a8f2f4bc372f6f8d05cf2 (2020-04-20 19:41:29 -0400)
engine: only edit k8s yaml image pull policies if we're editing images. Fixes https://github.com/windmilleng/tilt/issues/3209
=> engine: only edit k8s yaml image pull policies if we're editing images. Fixes https://github.com/windmilleng/tilt/issues/3209

internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go
Please review the following commits I made in branch nicks/osname:
c19a9a35c9744f697136c20e0f6bed1586ae5ec0 (2020-04-20 18:56:53 -0400)
tiltfile: add os.name built-in
=> tiltfile: add os.name built-in

web/package.json
Please review the following commits I made in branch nicks/node:
b63ac14feb752ce770eea5d1bf8a044bf92b0d40 (2020-04-21 11:58:54 -0400)
tilt is currently broken on node13
=> tilt is currently broken on node13

internal/build/buildkit_printer_test.go, internal/build/image_builder_test.go, internal/build/path_mapping.go, internal/build/path_mapping_test.go, internal/build/pipeline_state_test.go, internal/build/tar.go, internal/build/tar_test.go
Please review the following commits I made in branch nicks/windows5:
37f98b610fde67fb7780445347b81c3ba530943c (2020-04-24 21:28:58 -0400)
build: fix tar code on windows
now that we fixed the path mapping code to handle paths
correctly, we don't need a lot of these workarounds
ebcbd16941bfb1b565e960e7460b0aed13d562e8 (2020-04-24 20:50:03 -0400)
build: fix path mapping on windows
=> build: fix tar code on windows

internal/kustomize/ordering.go
Please review the following commits I made in branch nicks/ch6585:
ff5ceea6cb45243f440c2bdb03a8cbc4a4366436 (2020-04-27 11:17:43 -0400)
kustomize: refresh resource ordering. Fixes https://github.com/windmilleng/tilt/issues/3240
=> kustomize: refresh resource ordering. Fixes https://github.com/windmilleng/tilt/issues/3240

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/dcwatch/actions.go, internal/engine/dcwatch/event_watcher.go, internal/engine/subscribers.go, internal/engine/upper.go, internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/dcew:
81ae76a50139812ff00f0991f7c48d3f78632403 (2020-04-27 18:55:40 -0400)
move the dockercompose event watcher into its own package
=> move the dockercompose event watcher into its own package

internal/k8s/env.go, internal/k8s/env_test.go
Hi there,
I tried to use tilt in combination with a CodeReady Containers (CRC) cluster. CRC is a slimmed down OpenShift cluster meant to be used for local development, see also [Red Hat CodeReady Containers](https://developers.redhat.com/products/codeready-containers)
Based on my testing, tilt works very weill with CRC. I encountered only one trivial glitch: tilt didn't recognize CRC as a local cluster. This pull request fixes it.
Thanks,
Ales
=> Recognize Red Hat CodeReady Containers as a local cluster

internal/ospath/ospath_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/windows7:
a2e90a3419a712b02d89066c3925954eda46e554 (2020-04-28 22:26:52 -0400)
ospath: fix ospath tests on windows
=> ospath: fix ospath tests on windows

internal/tiltfile/docker_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/windows8:
033fad4130fd2ff9d8ba7c707c1b36664e771435 (2020-04-28 22:31:23 -0400)
tiltfile: fix the last tiltfile tests on windows
=> tiltfile: fix the last tiltfile tests on windows

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/buildcontroller_test.go, internal/engine/fswatch/action.go, internal/engine/fswatch/factories.go, internal/engine/fswatch/fake.go, internal/engine/fswatch/fake_watcher.go, internal/engine/fswatch/watchmanager.go, internal/engine/fswatch/watchmanager_test.go, internal/engine/subscribers.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/version_checker.go
Hello @nicks,
Please review the following commits I made in branch nicks/watchmanager:
b75cd3cf2d6867a2a3aa746e0e208d90a0af17da (2020-04-28 19:04:57 -0400)
engine: move WatchManager into its own package
=> engine: move WatchManager into its own package

internal/cloud/update_uploader_test.go, internal/containerupdate/synclet_manager_test.go, internal/engine/analytics/analytics_reporter.go, internal/engine/analytics/analytics_reporter_test.go, internal/engine/analytics/analytics_updater_test.go, internal/engine/build_and_deployer_test.go, internal/engine/configs/configs_controller_test.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/dockerprune/docker_pruner_test.go, internal/engine/fswatch/watchmanager_test.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/live_update_build_and_deployer_test.go, internal/engine/local_target_build_and_deployer_test.go, internal/engine/portforwardcontroller_test.go, internal/hud/server/server_test.go, internal/hud/server/websocket_test.go, internal/store/store.go, internal/store/subscriber_test.go, internal/store/testing_store.go
Please review the following commits I made in branch nicks/testingstore:
f30184734ca55270500edada49ae463be3c94a7d (2020-04-29 11:16:52 -0400)
engine: use the simpler test store instead of the real store for testing
=> engine: use the simpler test store instead of the real store for testing

internal/engine/configs/configs_controller_test.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch_test.go, internal/store/testing_store.go
Please review the following commits I made in branch nicks/testingstore2:
5ad218630039b9e79774a292c32405d6bfaed752 (2020-04-29 11:40:06 -0400)
engine: switch more tests to use the simpler store
f30184734ca55270500edada49ae463be3c94a7d (2020-04-29 11:16:52 -0400)
engine: use the simpler test store instead of the real store for testing
=> engine: switch more tests to use the simpler store

internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go, internal/tiltfile/starkit/fixture.go
Please review the following commits I made in branch nicks/ch6674/path:
308614ed38fc990021d2aa73a42b1f2d4a16399c (2020-04-29 18:17:27 -0400)
tiltfile: add a bunch of os.path functions, and fix bugs in os.path.realpath
Fixes https://github.com/windmilleng/tilt/issues/3173
Fixes https://github.com/windmilleng/tilt/issues/3086
=> tiltfile: add a bunch of os.path functions, and fix bugs in os.path.realpath

internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go
Please review the following commits I made in branch nicks/exists:
01d200aa210029399cf06f8845f74f1f5e4dc238 (2020-04-30 15:47:32 -0400)
tiltfile: tweak os.path.exists to return false on permission denied
=> tiltfile: tweak os.path.exists to return false on permission denied

.circleci/Dockerfile.integration, .circleci/config.yml, .circleci/integration_tests.sh, integration/event_test.go, scripts/goreleaser.Dockerfile
Hello @nicks,
Please review the following commits I made in branch nicks/kind8:
532550e3107470bd29b1f02ee6473e7004fee91f (2020-05-01 16:35:04 -0400)
circleci: upgrade integration tests to kind 0.8
=> circleci: upgrade integration tests to kind 0.8

internal/engine/buildcontrol/build_control.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/time.go
Please review the following commits I made in branch nicks/ch4893/windows:
264039ba50f6cbe66765efcdd5d0e25b605df70a (2020-05-04 23:28:46 -0400)
engine: more gracefully handle equal time values
Fixes issues on Windows, where the clocks are not strictly monotonic,
and two consecutive time.Now() calls might return the same value
=> engine: more gracefully handle equal time values

internal/k8s/runtime.go, internal/k8s/runtime_test.go
This error message is not as important as it was with the sunsetting of
the synclet. Better to move it to a debug log since there are plenty
of users for whom Tilt works fine without node read permissions.
Fixes #3280
=> k8s: move forbidden runtime check to debug log

.gitattributes
Hello @nicks,
Please review the following commits I made in branch nicks/lineendings:
f3f4c282b9af6d58b85f68202a8ffd3eda8527fc (2020-05-05 19:05:23 -0400)
windows: shell scripts should always use unix line endings
=> windows: shell scripts should always use unix line endings

.gitattributes
Hello @nicks,
Please review the following commits I made in branch nicks/lineendings:
ce9c10d6b3d62684c2d0c104cb899c1ead37312e (2020-05-06 12:14:16 -0400)
fix an embarrassing typo in gitattributes
=> fix an embarrassing typo in gitattributes

internal/cli/flags.go, internal/cli/up.go
Please review the following commits I made in branch nicks/cimode:
8fb1cf062923121e831b0673f20c8d8c45edec6f (2020-05-05 19:15:17 -0400)
cli: allow 'tilt ci' to use the --web-mode flag for serving local vs prod js
=> cli: allow 'tilt ci' to use the --web-mode flag for serving local vs prod js

internal/engine/buildcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/pendingfiles:
63326b11462767611e4740c40d9ff31dfd53d2b5 (2020-05-06 12:39:24 -0400)
store: clear pending files even on error builds
This is a small code change, but should make the possible build control states
much easier to reason about and display.
This logic is vetigial from the days when we had fast_build and incremental
image builds. If your image build failed, and you wanted to retry it, then Tilt
would need to sync both the recently changed files and the files from the
*failed* build.
This can't really happen anymore where you have partial failed syncs.
If the sync step fails, we'll fall back to an image build.
If the run step fails, we don't need to re-sync the same files.
Code review reminders, …
=> store: clear pending files even on error builds

internal/cli/build.go, scripts/install.sh
Please review the following commits I made in branch bump-v0.13.5:
66e83c16c014d1e9392e1d57acc9f5faf880d39d (2020-05-07 17:28:34 -0400)
bump version to 0.13.5
=> bump version to 0.13.5

pkg/procutil/procutil_windows.go
Please review the following commits I made in branch nicks/procutil:
16101f82b327550a22a2ac95c9eb9f520d2657b9 (2020-05-08 22:05:37 -0400)
procutil: don't worry about process groups, taskkill is way more robust
=> procutil: don't worry about process groups, taskkill is way more robust

internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_test.go, pkg/model/custom_build_test.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/custombuild:
08fcd0edb100924ca3bf7db3a4e3c35a7cffba57 (2020-05-08 19:29:41 -0400)
model: custom_build should be stored as a Cmd instead of a string, and support :bat:s
39f947801c713307434f03e1ff349535b57bfd66 (2020-05-08 18:44:28 -0400)
tiltfile: support batch commands in the same way as Bazel and Buck
=> model: custom_build should be stored as a Cmd instead of a string, and support :bat:s

internal/k8s/client.go, internal/k8s/client_test.go
When we time out a k8s upsert, we log this:
```
Build Failed: kubectl apply:
stderr: : signal: killed
```
which doesn't indicate what killed it or why
log this: `Killed kubectl. Hit timeout of 15s.`
=> k8s: log client timeout

internal/engine/upper_test.go
1. This test is flaky. `f.Start` dispatches an `InitAction` from a goroutine with one value for TiltfilePath, and the test itself dispatches its own `InitAction` with a different value for TiltfilePath, so when we check TiltfilePath at the end, we get the winner of a race.
2. This behavior is covered by [`TestUpperStart`](https://github.com/windmilleng/tilt/blob/947966d6638eeb07f04e4121751dc50036a14803/internal/engine/upper_test.go#L2768) anyway, so it's not worth fixing.
=> upper: remove redundant+flaky init test

internal/tiltfile/os/environ.go, internal/tiltfile/os/environ_methods.go, internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go
Please review the following commits I made in branch nicks/ch6958/putenv:
fcf4b19a168d47b8953667637b877ea1ac1e9fff (2020-05-12 17:01:51 -0400)
tiltfile: add os.getenv, os.putenv, os.unsetenv. Fixes https://github.com/windmilleng/tilt/issues/2564
=> tiltfile: add os.getenv, os.putenv, os.unsetenv. Fixes https://github.com/windmilleng/tilt/issues/2564

.goreleaser.yml
Hello @jazzdan, @victorwuky,
Please review the following commits I made in branch nicks/alpha:
f5345ef9cf32d291843fb399a6d2822a8f1b28ac (2020-05-13 18:05:28 -0400)
windows is no longer alpha. Fixes https://github.com/windmilleng/tilt/issues/1961
=> windows is no longer alpha. Fixes https://github.com/windmilleng/tilt/issues/1961

internal/testutils/tempdir/temp_dir_fixture.go
Hello @nicks,
bcab97f47a54a584483a446b479e6526f26b3794 (2020-05-14 16:08:03 -0400)
testutils: ignore a spurious error
=> testutils: ignore a spurious error

internal/k8s/client.go
Please review the following commits I made in branch nicks/ch6999:
1d6f85d8a8440f7dbe3d4e0a4f20b67aac4887d7 (2020-05-14 10:52:37 -0400)
k8s: Reset() the rest mapper if it fails to map an existing type. Fixes https://github.com/windmilleng/tilt/issues/3325
=> k8s: Reset() the rest mapper if it fails to map an existing type. Fixes https://github.com/windmilleng/tilt/issues/3325

internal/dockerfile/ast.go, internal/dockerfile/dockerfile_test.go
Please review the following commits I made in branch nicks/ch6997/mount:
5f4d2bafd7744ef13cb2d9c14df2dae32214189e (2020-05-13 21:24:52 -0400)
dockerfile: more gracefully handle partial parsing. Fixes https://github.com/windmilleng/tilt/issues/3331
=> dockerfile: more gracefully handle partial parsing. Fixes https://github.com/windmilleng/tilt/issues/3331

internal/cli/args.go, internal/cli/ci.go, internal/cli/dump.go, internal/cli/flags.go, internal/cli/trigger.go, internal/cli/up.go, internal/cli/utils.go
Please review the following commits I made in branch nicks/ch7016:
f75c6a297f559ed016411376da721a6ea109511a (2020-05-14 18:49:56 -0400)
cli: consolidate how we set port and host. Fixes https://github.com/windmilleng/tilt/issues/3332
=> cli: consolidate how we set port and host. Fixes https://github.com/windmilleng/tilt/issues/3332

internal/cli/doctor.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/k8s/registry.go, internal/k8s/registry_test.go
Please review the following commits I made in branch nicks/kind:
f1159e9ccd44f5eb0d91600eec063a4113bd214b (2020-05-15 17:11:58 -0400)
k8s: print local registry as part of 'tilt doctor', and add support for new kind registry annotation
=> k8s: print local registry as part of 'tilt doctor', and add support for new kind registry annotation

internal/tiltfile/files.go, internal/tiltfile/helm_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch7045/namespace:
cfa92e2cbb8e9c266c255dabc394e38076bcd74b (2020-05-18 18:43:00 -0400)
remove auto-namespace creation. Fixes  https://github.com/tilt-dev/tilt/issues/3349
helm3 has moved away from this behavior, and in retrospect, it seems
to create more problems than it solves
As a work-around, people should create a new namespace
themselves if that's what they want.
This is basically a revert of https://github.com/tilt-dev/tilt/pull/2418
I also considered adding some sort of EnsureNamespace
primitive in K8sTarget, which might be more generally useful,
but was worried it added a lot of complexity and made this
harder to implement as a tilt extension.
Code review reminders, by giving a LGTM you attest …
=> remove auto-namespace creation. Fixes  https://github.com/tilt-dev/tilt/issues/3349

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/updatesettings/update_settings.go, pkg/model/update_settings.go
Please review the following commits I made in branch maiamcc/configure-timeout:
e6860bad300cbca51f5660c827d8ba9350dddd63 (2020-05-14 16:18:00 -0400)
tiltfile/engine: expose update_settings.k8s_upsert_timeout_secs
0b9a9f192146471807ca21b024560ac520f33d2c (2020-05-13 18:15:53 -0400)
store: keep the whole UpdateSettings on EngineState, not just MaxParallelBuilds
=> tiltfile/engine: k8s upsert timeout settable from tiltfile [ch6947]

internal/k8s/portforward.go, internal/k8s/portforward/doc.go, internal/k8s/portforward/portforward.go, internal/k8s/portforward/portforward_test.go, vendor/modules.txt
Hello @nicks,
Please review the following commits I made in branch nicks/portforward2:
a5ed76cffefaf306a5b851f44a6248ebd92a1fa8 (2020-05-21 15:31:09 -0400)
k8s: fork the client-go portforwarder
=> k8s: fork the client-go portforwarder

.circleci/config.yml, Makefile, internal/tiltfile/tiltfile_test.go
sample result w/ failures https://circleci.com/gh/tilt-dev/tilt/40825
Installing gotestsum added 35 seconds to the windows build, for a total of 7m54s.
=> windows: use gotestsum in ci

internal/tiltfile/config/bool.go, internal/tiltfile/config/config_def.go, internal/tiltfile/config/config_test.go, internal/tiltfile/config/string.go, internal/tiltfile/config/string_list.go
Fixes #3360
In a Tiltfile's `config.parse()`, as soon as it encounters any non-positional arguments, all remaining arguments are treated as non-positional
in Tiltfile:
```
config.define_string('foo')
config.define_string_list('bar', args=True)
cfg = config.parse()
```
on cmd line:
`tilt up -- a --foo b`
`cfg['foo'] == 'b'` and `cfg['bar'] == ['a']`
`cfg['foo'] is undefined and `cfg['bar'] == ['a', '--foo', 'b']`
Use [`pflag`](https://github.com/spf13/pflag) instead of golang's `flag`. Further discussion [here](https://github.com/tilt-dev/tilt/issues/3360#issuecomment-632236155).
1. tiltfile config parsing is consistent with the "main" tilt parsing (i.e., the cobra stuff that happens in `cmd` - cobra uses pflag), and most (AFAIK) unix tools.
2. this is a breaking change in that go's …
=> tiltfile config: use pflag

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/pod.go, internal/engine/portforward/controller.go, internal/engine/portforward/controller_test.go, internal/engine/subscribers.go, internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/pf:
6f2cb831f23297b1ac1190b01a83b667c391cfa1 (2020-05-21 16:45:03 -0400)
engine: move the portforwardcontroller into its own package
=> engine: move the portforwardcontroller into its own package

pkg/model/logstore/logstore.go
Please review the following commits I made in branch nicks/ch7111/logs:
2665954fef31dc92edb7dc9259f545d624bfb8ef (2020-05-21 18:33:14 -0400)
logstore: ratchet down the logstore max a bit for now
=> logstore: ratchet down the logstore max a bit for now

internal/k8s/portforward.go, internal/k8s/portforward/portforward.go, internal/k8s/portforward/portforward_test.go
Please review the following commits I made in branch nicks/ch7097/portforward:
08faa087c464ed530c1766f6d6ba05ef5bd580ea (2020-05-21 17:59:26 -0400)
k8s: properly route portforward output to debug logs. Fixes https://github.com/tilt-dev/tilt/issues/3355
=> k8s: properly route portforward output to debug logs. Fixes https://github.com/tilt-dev/tilt/issues/3355

internal/hud/webview/analytics_nudge.go, internal/hud/webview/convert.go, internal/k8s/target.go, internal/k8s/target_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/k8s_target.go, pkg/model/manifest.go
=> tiltfile: explicitly mark non-workload manifests as such so we can handle them differently in the UI

internal/engine/buildcontrol/target_queue.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/image_builder.go
Please review the following commits I made in branch nicks/targetqueue:
fda20bb722c9c41ad2efa61498f35120ed24c247 (2020-05-22 16:39:54 -0400)
engine: remove last build state from the target queue build handlers
3e08017f81e2e60c842169d580acbfa8f3660562 (2020-05-22 16:14:48 -0400)
build: rename a bunch of types to make more sense (the new names should be uncontroversial and were already in a todo)
=> engine: remove last build state from the target queue build handlers

internal/tiltfile/files.go, internal/tiltfile/helm_test.go, internal/tiltfile/testdata/grafana.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch7120:
9019d5b21aff073142276147d14c51922bea91f6 (2020-05-22 18:54:50 -0400)
tiltfile: default helm release name to 'tilt'. Fixes https://github.com/tilt-dev/tilt/issues/3370
=> tiltfile: default helm release name to 'tilt'. Fixes https://github.com/tilt-dev/tilt/issues/3370

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go
Please review the following commits I made in branch nicks/ch7144:
db0ea97f0b8d2d043073254ec64e5251435b19a2 (2020-05-26 17:42:18 -0400)
tiltfile: add support for two docker_compose calls in the same tiltfile
=> tiltfile: add support for two docker_compose calls in the same tiltfile

internal/k8s/watch_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/pods:
c152ca266d311422eb55a8d848b9c55f5e661e7a (2020-05-26 19:27:11 -0400)
bump the timeout on watchTestFixture, 10ms isn't enough time if there's a gc pause
=> bump the timeout on watchTestFixture, 10ms isn't enough time if there's a gc pause

internal/ignore/ephemeral.go
KDE's text editor, kate, uses a file similar to Vim's .swp files. Ignore
these files so we don't rebuild on every keypress.
Fixes #3378
=> Add .kate-swp files to ignore pattern

internal/engine/build_and_deployer.go, internal/engine/buildcontrol/target_queue.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/noop:
a935df30053134965d80e454c480059308eb50b1 (2020-05-22 18:03:01 -0400)
engine: build and deployers should return results for targets they built, and not return results for targets they didn't build.
This should make https://github.com/tilt-dev/tilt/pull/3362
much simpler and easy to reason about.
Also adds test harnesses for different build graph configurations.
4fb88080da67e01cb8b18675d12965c1bf92ae8e (2020-05-22 16:40:23 -0400)
engine: remove last build state from the target queue build handlers
* Code is suitably …
=> engine: build and deployers should return results for targets they built, and

.circleci/config.yml, web/package.json, web/src/AlertPane.test.tsx, web/src/SidebarTriggerButton.test.tsx, web/src/__snapshots__/LogPane.test.tsx.snap, web/src/__snapshots__/ResourceInfo.test.tsx.snap, web/src/__snapshots__/SecondaryNav.test.tsx.snap, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/setupTests.ts, web/src/style-helpers.ts, web/yarn.lock
Hello @nicks,
Please review the following commits I made in branch nicks/babel:
139dbf8f299be4803004ec272826028620587842 (2020-05-27 11:46:02 -0400)
upgrade babel-preset env to 7.9.0
c135b715473ef581f88086b006634585b44c709b (2020-05-27 11:43:29 -0400)
Revert "nodejs: pin to node 12.16 (#3382)"
This reverts commit 299c634d9e72c8316bff662669de1a93e82ed85d.
=> upgrade babel-preset env to 7.9.0

internal/engine/buildcontrol/target_queue.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go
Please review the following commits I made in branch nicks/reused:
69a316d8f664ef5d7040ba396d4521b4cb511118 (2020-05-27 15:21:27 -0400)
engine: print out results from previous builds
=> engine: print out results from previous builds

internal/store/engine_state.go, internal/tiltfile/config/config.go, internal/tiltfile/config/config_test.go, internal/tiltfile/encoding/json_test.go, internal/tiltfile/encoding/yaml_test.go, internal/tiltfile/files.go, internal/tiltfile/io/io.go, internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go, internal/tiltfile/starkit/fixture.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch7235:
fb35e62ffbade35cb7bbb2d103e0b50bc9f38b3f (2020-05-29 14:33:03 -0400)
tiltfile: os.path.exists should not watch directories recursively. Fixes https://github.com/tilt-dev/tilt/issues/3387
=> tiltfile: os.path.exists should not watch directories recursively. Fixes https://github.com/tilt-dev/tilt/issues/3387

internal/hud/server/websocket.go
May help with situations where Tilt is being run on a remote server and
the web UI is running on a local laptop resulting in the websocket
messages being sent over the Internet like in #3359.
Currently seeing if there is a measurable performance impact here, but I figure if it's a wash, then we might as well enable this. WDYT?
=> hud/server: enable websocket compression

web/src/LogPaneLine.scss
Please review the following commits I made in branch nicks/ch7387:
3e4e85ade3633981eaeda1b13811880bc8caf6ca (2020-06-04 18:06:42 -0400)
web: fix alignment/truncation of the manifest name
This works more consistently across Chrome/Firefox
=> web: fix alignment/truncation of the manifest name

internal/engine/pod.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/runtimelog/podlogmanager_test.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/ch4113/init:
6588ff15391bec8b7216e9ab126f377e9c7b72af (2020-06-05 13:24:34 -0400)
runtimelog: add support for init containers
=> runtimelog: add support for init containers

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/extractors.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_build_and_deployer_test.go, internal/k8s/client.go, internal/store/build_result.go, web/src/SidebarTriggerButton.tsx
Please review the following commits I made in branch nicks/ch4742:
7cf255f5f557623434cba8c07803638c83ceeb7d (2020-06-05 17:35:16 -0400)
engine: forcing an update should also force a pod update. Fixes https://github.com/tilt-dev/tilt/issues/1928
=> engine: forcing an update should also force a pod update. Fixes https://github.com/tilt-dev/tilt/issues/1928

internal/cli/up.go
Fixes  #3256
I've added the deprecate property to the watch flag. The result of doing so is as follows: 
When "--watch" is used:
When there's no "--watch" included:
=> Added Deprecate Property to Watch Flag (Issue  #3256) 

web/src/LogPaneLine.scss
Please review the following commits I made in branch nicks/ch7547:
0dd5abbb56d7c63d899ad448c5523367b78000e8 (2020-06-12 14:42:30 -0400)
web: fix fallback log styling when there are debug logs
=> web: fix fallback log styling when there are debug logs

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/ch7688:
5c458ebb7bdffefbb02ce841e24816202953431c (2020-06-12 15:30:10 -0400)
engine: k8sTargets should have buildState too. Fixes https://github.com/tilt-dev/tilt/issues/3454
It's bothered me so much that k8s targets don't have build state and
now I finally have an excuse to fix it!!!
=> engine: k8sTargets should have buildState too. Fixes https://github.com/tilt-dev/tilt/issues/3454

internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/extractors.go, internal/engine/image_build_and_deployer_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/build_result.go, internal/store/engine_state.go, pkg/model/build_reason.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/ch6738:
c9950540c7fc011d2d348b89b250e99d1ba8215b (2020-05-21 11:07:44 -0400)
engine: better handling for image builds in multiple manifests. Fixes https://github.com/windmilleng/tilt/issues/2992
=> engine: better handling for image builds in multiple manifests. Fixes https://github.com/windmilleng/tilt/issues/2992

internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/subscribers.go, internal/engine/upper_test.go, internal/hud/prompt/prompt.go, internal/hud/prompt/prompt_test.go, internal/hud/prompt/wire.go, internal/hud/terminal_stream.go
Please review the following commits I made in branch nicks/browser:
e503e1875abdb320492d5665b7541a807395db62 (2020-06-15 16:00:46 -0400)
hud: add a prompt package for the new terminal mode
=> hud: add a prompt package for the new terminal mode

internal/cli/ci.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/hud/prompt/prompt.go, internal/hud/prompt/prompt_test.go, pkg/logger/deferred.go
Please review the following commits I made in branch nicks/ch7729/output:
5cd0783840165bdfdd03ad1a3de583701b8f92e9 (2020-06-16 12:16:36 -0400)
prompt: handle logs during the init sequence properly
=> prompt: handle logs during the init sequence properly

internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/local/execer.go, internal/engine/local/execer_test.go
Please review the following commits I made in branch nicks/ch7815/local:
257f34aa62103c9bbb9263262e91f26efaabeb14 (2020-06-19 10:08:33 -0400)
local: fix shutdown sequence to handle delayed exit and log correctly Fixes https://github.com/tilt-dev/tilt/issues/3479 Fixes https://github.com/tilt-dev/tilt/issues/3443
=> local: fix shutdown sequence to handle delayed exit and log correctly

internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_state.go
revert restart_container deprecation warning until we can fix #3452 :-/
=> Revert "tiltfile: deprecation warning for restart_container + k8s resource [ch5943] (#3249)"

internal/feature/flags.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/obsolesce-multiple-containers-flag:
1d6489f1e54221b7aad27167ea76e035bb2a35ae (2020-06-16 17:56:01 -0400)
tiltfile: obsolesce multipleContainersPerPod flag, validate live updates better
=> tiltfile: obsolesce multipleContainersPerPod flag, validate live updates better

internal/tiltfile/tiltextension/extension.go, internal/tiltfile/tiltextension/extension_test.go
Please review the following commits I made in branch maiamcc/non-root-extensions:
90e43b7c97c4a985ae8c7f9735dd540547d07f54 (2020-06-19 17:07:55 -0400)
tiltfie: now legal for loaded/included files to call load/include [ch7329 ch7828]
=> tiltfie: now legal for loaded/included files to call load/include [ch7329 ch7828]

internal/engine/telemetry/controller.go, internal/tiltfile/telemetry/telemetry.go, internal/tiltfile/telemetry/telemetry_test.go, internal/tiltfile/value/duration.go, pkg/model/telemetry_settings.go
Please review the following commits I made in branch nicks/opentelemetry:
453fbb4d4142da11e341584ae78d17f7246bb559 (2020-06-22 12:02:03 -0400)
tiltfile: add a period= parameter to experimental_telemetry_cmd
=> tiltfile: add a period= parameter to experimental_telemetry_cmd

internal/engine/buildcontroller_test.go, internal/k8s/names.go, internal/tiltfile/local_resource.go, internal/tiltfile/tiltfile_test.go
Hello @nicks @landism 
Please review the following commit in this pull request which attempts to solve the issue posed in Issue #2919 
f971dc4e933fbeb181d79ad6c8c9956e72369025 fixed local resouce duplication? 
=> tiltfile: Throw Error When local_resource() defined multiple times

internal/hud/prompt/prompt.go, internal/hud/prompt/prompt_test.go
Hello @landism, @victorwuky,
Please review the following commits I made in branch nicks/ch6282/hide:
860cd5464891516001f43c6b75ef1c328e9bbd92 (2020-06-22 13:19:02 -0400)
prompt: emit a warning that the hud key shortcut is going away
=> prompt: emit a warning that the hud key shortcut is going away

internal/engine/buildcontrol/target_queue.go, internal/engine/image_build_and_deployer_test.go
Please review the following commits I made in branch nicks/graph:
0366bb9c17b0df8edcf6f99d12b9bfe9333b7622 (2020-06-23 09:46:45 -0400)
engine: fix up some display and calculations in the build graph
This improves the logs around when cached images are being
reused, and why we're doing a rebuild.
It also fixes a bug where we were reusing a cached image
when we shouldn't have been.
=> engine: fix up some display and calculations in the build graph

internal/k8s/entity.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/k8s/locator.go, internal/k8s/object_selector.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/extract:
738d64af209d34a823fe1c6bd095ab0bbc8c565b (2020-06-24 19:47:38 -0400)
k8s: factor out an interface for extracting/injecting images
This is moving towards solutions for:
- https://github.com/tilt-dev/tilt/issues/3427
- https://github.com/tilt-dev/tilt/issues/3460
It ended up being kind of a yak shave, since we need to be able to attach
the object selectors to K8sTarget so that we know which entities to
inject into.
=> k8s: factor out an interface for extracting/injecting images

internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontroller.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/extractors.go, internal/engine/image_build_and_deployer_test.go, internal/engine/upper.go, internal/store/build_result.go, internal/store/engine_state.go, internal/store/engine_state_test.go, pkg/model/build_reason.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/depchange:
201e1e055898672da2b4a5fad64bbc5307f24be0 (2020-06-24 16:06:55 -0400)
engine: partial roll forward of ee10a5081bb258073aca30950ca7c5abd89c22bb
Adds the fields to the data model for recording dependency changes,
but doesn't yet propagate those changes.
=> engine: partial roll forward of https://github.com/tilt-dev/tilt/pull/3505

internal/engine/buildcontrol/target_queue.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/live_update_build_and_deployer_test.go, internal/engine/live_update_state_tree.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/build_result.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/lastresult:
2af94cc3d4a3b705c6fda5360a1afb2e0ecc4b3f (2020-06-16 18:49:40 -0400)
engine: remove LastSuccessfulResult
The fundamental problem is that, by definition, all concrete BuildResult objects
represent success. If an image build fails, we return a nil BuildResult.
The notion of "BuildResult" gets slippery when we talk about live update.
If the in-container RUN step failed, the live-updater returns a valid BuildResult
(containing the container id) AND an error. In some contexts, we want to
treat that as a success (because the container is still live and can get future
live udpates), but in other cases (like error reporting), we want to report
this as an error.
Better to just get rid of the concept of …
=> engine: remove LastSuccessfulResult

internal/build/docker_builder.go, internal/docker/fake_client.go, internal/engine/build_and_deployer_test.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer_test.go
Please review the following commits I made in branch nicks/close:
e55aebeb4e5834d42ea6037c7b7ebbce48b93c94 (2020-06-26 16:14:18 -0400)
build: close the tar pipe, to avoid zombie goroutines
I was finding it hard to debug some tests because there were zombie
goroutines blocked forever on writing to the pipe. This changes
the semantics so that ImageBuild must consume the pipe.
=> build: close the tar pipe, to avoid zombie goroutines

internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/ch8109:
d6fdf40ce4773816c64237e58f8a8ec567c73360 (2020-06-26 20:43:19 -0400)
engine: handle tiltignore and team loading correctly if execution failed
=> engine: handle tiltignore and team loading correctly if execution failed

internal/k8s/image_test.go, internal/k8s/json_path.go, internal/k8s/locator.go, internal/k8s/locator_test.go, internal/k8s/object_selector.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/locators:
d6af15ae8a3b8cd809598650b1953d645b102827 (2020-06-29 12:46:56 -0400)
k8s: add a locator for image objects
This is moving towards https://github.com/tilt-dev/tilt/issues/3427,
but also is a good model of how to write new kinds of image locators
=> k8s: add a locator for image objects

web/src/ShareSnapshotModal.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
=> tilt: indicate snapshot is private when running w/ a team id

internal/engine/exit/controller_test.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/pod.go, internal/engine/pod_test.go, internal/engine/portforward/controller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/store/manifest_target.go, internal/store/runtime_state.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/testutils/manifestutils/manifest.go
Please review the following commits I made in branch nicks/ch8127:
869806be986d5d9ac938b399c766c1d0d1bbbe64 (2020-06-29 16:40:46 -0400)
store: Use the NonWorkload field to determine runtime status
This is a better indicator if a manifest has pods
Fixes https://github.com/tilt-dev/tilt/issues/3497
=> store: Use the NonWorkload field to determine runtime status

internal/tiltfile/k8s.go, internal/tiltfile/k8s/locators.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch8121:
fa7f254ee849816641a0a0e072822e94498e89da (2020-06-29 15:40:29 -0400)
tiltfile: add an API for adding image object locators. Fixes https://github.com/tilt-dev/tilt/issues/3427
=> tiltfile: add an API for adding image object locators. Fixes https://github.com/tilt-dev/tilt/issues/3427

internal/cli/cli.go, internal/cli/tiltfile_result.go
fix #3541
midstream through #3544 I changed approaches, and failed to revert all of the first approach when implementing the new approach
you can scroll through the top of [this comparison](https://github.com/tilt-dev/tilt/compare/e14064a17a14da12938811bb40ecf73a6aeed6b7...matt/more_revert) to see the net internal/cli changes
=> cli: fix duplicate fatal error logging

internal/build/docker_builder.go, internal/cli/wire_gen.go, internal/docker/fake_client.go, internal/engine/buildcontrol/target_queue.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/image_builder.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/synclet/wire_gen.go
Please review the following commits I made in branch nicks/image-reuse:
f888022a89d06e71acda9de2c89713677136516a (2020-07-02 13:30:48 -0400)
engine: fix bugs in image build caching
this is the source of a lot of the infinite rebuild problems in
https://github.com/tilt-dev/tilt/pull/3362
There are a lot of weird cases where the original image existence check would
fail, and so we would deliberately rebuild the image. This makes the check more
robust, and adds logging when it does fail so that we have some hope of figuring
out the problem.
* Code is suitably instrumented with …
=> engine: fix bugs in image build caching

internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch maiamcc/rm-update-container:
052b720c9e8ee8f4d1dada7a2d17c8a5ed370b25 (2020-07-02 17:47:04 -0400)
tiltfile: turn restart_container deprecation warning into an error [ch7714]
=> tiltfile: turn restart_container deprecation warning into an error [ch7714]

internal/engine/buildcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, pkg/model/build_reason.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/ch6738:
24351f95b0d93a5cd8323e227a2a7c15a45ede25 (2020-07-06 11:43:41 -0400)
engine: roll forward of https://github.com/tilt-dev/tilt/pull/3362, re-using image builds from other resources
=> engine: roll forward of https://github.com/tilt-dev/tilt/pull/3362, re-using image builds from other resources

internal/k8s/entity.go, internal/k8s/entity_test.go, internal/store/build_result.go
Please review the following commits I made in branch nicks/managedfields:
72ced8a167d557611ce5a53702573a3868f7feb9 (2020-07-06 18:56:03 -0400)
k8s: clean up bookkeeping fields
=> k8s: clean up bookkeeping fields

internal/cli/down.go, internal/cli/down_test.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/analytics/analytics_reporter.go, internal/engine/analytics/analytics_reporter_test.go, internal/engine/upper_test.go, internal/tiltfile/config/config.go, internal/tiltfile/config/config_test.go, pkg/model/tilt_subcommand.go.go
The `tilt.up.running` event also gets emitted by `tilt ci`, and includes no information to distinguish `tilt ci` from `tilt up`.
Add a tag for the subcommand (e.g., "up", "ci") on `tilt.up.running` events.
* We should rename `tilt.up.running` as well, but that makes this change riskier (since it gives us an inconsistency to account for in our analytics queries) and can be decoupled from this change.
* Ideally we have a separate mechanism to filter out runs in CI from human runs and this isn't the only thing we rely on, but:
* that's always going to be a heuristic situation and more signal is better
* this might be nice to have for other reasons
* Perhaps it'd be better add this as a global tag rather than just on this one count, but that's probably a couple hours of work instead of a few …
=> analytics: tag tilt.up.running w/ subcommand

internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/nonworkload:
993df2b62ed73023b453e2d30d3980b359a8a301 (2020-07-07 12:30:59 -0400)
tiltfile: resources with extra pod selectors or images should be considered workloads
=> tiltfile: resources with extra pod selectors or images should be considered workloads

internal/analytics/tilt_analytics_test.go, internal/cli/doctor.go
Hello @landism, @abdullahzameek,
Was verifying the interaction between a user's opt in/out and the tiltfile `analytics_settings(enable=True|False)`
call, and saw we didn't have a test for it, so added one.
Please review the following commits I made in branch maiamcc/opt-precedence-test:
158b1953daecdf0ae74e4f511b0e1f34a9c549c0 (2020-07-06 12:49:15 -0400)
analytics: test for opt precedence
=> analytics: test for opt precedence

internal/containerupdate/exec_updater.go, internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/update_mode.go, internal/engine/live_update_build_and_deployer.go
Please review the following commits I made in branch maiamcc/rm-default-synclet:
dee0445636115c5ccea6139a21ed2afd3c5cd8b5 (2020-07-07 18:16:45 -0400)
fix other tests, rm redundant ones
da404d3ff71a9969b57d47c7da4faec34aed94b7 (2020-07-07 17:14:54 -0400)
fix liveupdate tests that expected synclet
12a71c2d55e9e4ec4a3646c4d158008890129d4f (2020-07-07 12:19:47 -0400)
only use synclet with explicit flag (needs tests)
=> engine: updateMode=synclet only if explicitly set with flag [8240]

internal/cli/up.go
Hello @abdullahzameek, @nicks,
Please review the following commits I made in branch maiamcc/update_mode-metric:
890db9b7c837944e99687fc115a30e1345c95bc3 (2020-07-08 14:22:29 -0400)
cli: rename mode metric to update_mode for readability
=> cli: rename mode metric to update_mode for readability

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go
Please review the following commits I made in branch nicks/ch8297:
0fd8038a752db9c8030ff100da2d580cb52aac1c (2020-07-08 15:58:22 -0400)
engine: don't parallelize uncategorized yaml with other yaml. Fixes https://github.com/tilt-dev/tilt/issues/3421
=> engine: don't parallelize uncategorized yaml with other yaml. Fixes https://github.com/tilt-dev/tilt/issues/3421

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go
Please review the following commits I made in branch nicks/ch7744:
75a55f0ae520130718dc631413ab292bd0025475 (2020-07-08 14:47:03 -0400)
engine: parallize builds with common re-usable images. Fixes https://github.com/tilt-dev/tilt/issues/3468
=> engine: parallize builds with common re-usable images. Fixes https://github.com/tilt-dev/tilt/issues/3468

internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller_test.go, internal/engine/exit/controller_test.go, internal/engine/portforward/controller_test.go, internal/engine/upper.go, internal/store/engine_state_test.go, internal/store/runtime_state.go, internal/testutils/manifestutils/manifest.go
Please review the following commits I made in branch nicks/resource-deps:
872a060679f012121fc30770539ca2dc3a4acc12 (2020-07-09 19:21:48 -0400)
engine: fix a bug where resource_deps on non-workloads didn't work correctly
=> engine: fix a bug where resource_deps on non-workloads didn't work correctly

internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/helm_test.go, internal/tiltfile/value/string.go, internal/tiltfile/value/string_test.go
fixes #3570
also improves the error message when one of the list elements is the wrong type
My main outstanding concern is if there are non-List Iterables other than map that we still want to accept. I did test that generators still get represented as lists.
=> tiltfile: StringOrStringList: require Union[string,Union[List,Tuple]] instead of Union[string,Iterable]

internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
Hello @nicks,
Please review the following commits I made in branch abdullahzameek/3528-remove-local-log
50e4e5b5a16f1342269d350f570319710c8a6f88  (Wed Jul 15 17:35:30 2020 +0400)
tiltfile: removed logging of executed command in local()
=> tiltfile: removed logging of executed command in local()

internal/build/tar.go, internal/build/tar_test.go, internal/testutils/tar.go
a user had an issue copying `.` (in their container) into a volume: they got permission errors b/c we tar in the dockerfile with no permission bits. this PR sets permissions arbitrarily to 0644.
we tar in the dockerfile b/c docker requires that the dockerfile exist _somewhere_ in the archive. the idea solution here would be to [replicate Docker's behavior](https://github.com/docker/cli/blob/bece8cc41c248050e1c70ea73ce0097bc5a8e11e/cli/command/image/build/context.go#L374) of putting the Dockerfile _somewhere random_ in the context such that it's in the archive (as is needed for building the image) but doesn't get copied into the container if the user runs `COPY . ...`.
=> build: set permission bits when we tar dockerfile into docker context

internal/k8s/names.go, internal/k8s/names_test.go, internal/k8s/target.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Hi @maiamcc @jazzdan, 
Please review the following commits I made in branch abdullahzameek/3588-duplicate-yaml:
0b8e13f234d1c34c1eeeb3129f2512978c523b77 (Tue Jul 21 17:27:42 2020 +0400)
tiltfile: added error when duplicate yaml is detected
=> tiltfile: added error when duplicate yaml is detected

internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/local/execer.go, internal/engine/local/execer_test.go
Fixes #3602
local_resource does not use the command's workdir when running serve_cmd, e.g.:
in test/Tiltfile:
```
local_resource(
'example-cmd',
cmd='echo "cmd pwd $PWD"',
serve_cmd='echo "serve pwd $PWD"',
)
```
in Tiltfile:
```
include('test/Tiltfile')
```
tilt outputs (modulo tiltfile dir)
```
cmd pwd /Users/matt/w/tilt-serve-cmd-repo/test
serve pwd /Users/matt/w/tilt-serve-cmd-repo/test
```
tilt outputs
```
cmd pwd /Users/matt/w/tilt-serve-cmd-repo/test
serve pwd /Users/matt/w/tilt-serve-cmd-repo
```
note the lack of "test" at the end of "serve"
Use workdir when running serve_cmd.
This is a breaking change along the lines of #3150, but presumably far less contentious, since no one is likely to argue that update_cmd and serve_cmd should behave differently in this respect.
As with …
=> local_resource: run serve_cmd from workdir

internal/k8s/registry.go
Please review the following commits I made in branch nicks/local-registry:
aa431a55bfc38c746ad4a2cc585f6c640e823120 (2020-07-22 19:56:14 -0400)
k8s: make the local registry discovery errors debug logs for now. they're not really actionable yet
=> k8s: make the local registry discovery errors debug logs for now. they're not really actionable yet

scripts/install.sh
Today I saw Brandon Philips report the same issue on twitter that I had when trying the install script.
He reported it in Ubuntu, I had the same issue on Fedora:
```
+ mv tilt /home/user/.local/bin/tilt
mv: cannot move 'tilt' to '/home/user/.local/bin/tilt': No such file or directory
```
The installer would assume that `$HOME/.local/bin` always exists Here is the fix.
=> Check home path in linux before installing

internal/build/docker_builder.go, internal/build/docker_builder_test.go, internal/cli/dump.go, internal/cli/wire.go, internal/cli/wire_gen.go
Please review the following commits I made in branch nicks/ch8524:
d77706bcae5c133327ff1e21e067f9b59b9105b3 (2020-07-22 16:58:12 -0400)
cli: add 'tilt dump image-deploy-ref', for determining the deploy tag of an image
helps with more complex custom_build commands as described in https://github.com/tilt-dev/tilt/issues/3584
=> cli: add 'tilt dump image-deploy-ref', for determining the deploy tag of an image

internal/k8s/env.go, internal/k8s/env_test.go, internal/tiltfile/k8scontext/k8scontext.go
Hi,
I was trying to use Tilt with Krucible, a platform for creating Kubernetes clusters specifically for development, and having to explicitly whitelist the clusters is a bit of a nuisance. This PR adds support for recognising Krucible Kubernetes clusters as development clusters. I also took the liberty of renaming the function to better reflect the intent.
Krucible: https://usekrucible.com/
Let me know what you think!
Cheers,
Ben
=> Recognise Krucible clusters as development clusters

go.mod, go.sum, internal/engine/fswatch/watchmanager.go, internal/engine/fswatch/watchmanager_test.go, internal/watch/notify.go, internal/watch/watcher_naive.go, internal/watch/watcher_nonwin.go, internal/watch/watcher_windows.go, vendor/github.com/tilt-dev/fsnotify/windows.go, vendor/modules.txt
Please review the following commits I made in branch nicks/ch8606/shortread:
7af78517cee06d89b5e7febfb4ea8059d2eb9548 (2020-07-27 16:28:14 -0400)
watch: increase the windows watch i/o buffer
fixes https://github.com/tilt-dev/tilt/issues/3556
=> watch: increase the windows watch i/o buffer

internal/cli/wire_gen.go, internal/containerupdate/docker_container_updater.go, internal/containerupdate/docker_container_updater_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/wire.go, internal/engine/wire_gen.go
was looking thru how we instrumented updates and saw that the DockerUpdater
was missing a span where the other updaters had one, so added it
(and renamed the type to be consistent with the other container updaters)
=> containerupdate: add a span where we were missing one

internal/cli/cli.go, internal/cli/verify_install.go
Hi @nicks ,
Please review the following commit in the branch abdullahzameek/create-verify-install
95ba68639092fba840b44b8cb498e0d8a7a7d52e ( Tue Jul 28 19:00:00 2020 +0400) - cli: created tilt verify install
=> cli: added verify-install option to tilt 

internal/tiltfile/files.go, internal/tiltfile/helm.go, internal/tiltfile/helm_test.go
Please review the following commits I made in branch nicks/ch8617:
21f07304f033d19d41f1dc2617d27d8155a4dd55 (2020-07-28 18:34:10 -0400)
tiltfile: helm() should return CRDs in the new helm3 format. Fixes https://github.com/tilt-dev/tilt/issues/3605
=> tiltfile: helm() should return CRDs in the new helm3 format. Fixes https://github.com/tilt-dev/tilt/issues/3605

internal/tiltfile/tiltfile_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/kustomization:
b446a582d934f9f3cb999d2cc898fd26dfdfbda7 (2020-07-29 13:02:28 -0400)
disable kustomize tests on windows
=> disable kustomize tests on windows

internal/build/options.go, internal/docker/client.go, internal/docker/options.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/ch8626:
a12186c87eb304d9d0690ecd0e05138ec4f29a86 (2020-07-28 20:12:05 -0400)
tiltfile: add support for docker build --pull, docker build --cache-from. Fixes https://github.com/tilt-dev/tilt/issues/3569
=> tiltfile: add support for docker build --pull, docker build --cache-from. Fixes https://github.com/tilt-dev/tilt/issues/3569

internal/tiltfile/tiltfile_test.go
Clarify where `make install` puts the new `tilt` binary. 
I was working through the contribution guidelines and was a bit lost as to where the binary ended up after `make install`; this helps others who may also be a bit lost.
=> Clarify location of `tilt` binary after `make install` 

internal/tiltfile/docker.go, internal/tiltfile/docker_compose.go, internal/tiltfile/docker_test.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
Fixes #3231 
I'm not super confident in how this impacts docker-compose, but all tests pass.
=> Add support for .dockerignore specified by non-default Dockerfile name

internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/kustomize:
df553001268feccc0df9bd32da99a15d29e9912e (2020-07-30 11:34:10 -0400)
tiltfile: workaround a bug in kustomize
for more details, see https://github.com/kubernetes-sigs/kustomize/issues/2789
=> tiltfile: workaround a bug in kustomize

internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller_test.go, internal/hud/webview/analytics_nudge.go, internal/hud/webview/analytics_nudge_test.go, internal/hud/webview/convert.go, internal/k8s/target.go, internal/k8s/target_test.go, internal/store/engine_state.go, internal/store/runtime_state.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/k8s.go, internal/tiltfile/k8s/readiness.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/k8s_target.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/ch8647:
95ef863dd3726c566748fc7340dbfb6d6030270c (2020-07-30 10:01:37 -0400)
tiltfile: add an api for changing the readiness mode of a resource
Helps resolve https://github.com/tilt-dev/tilt/issues/3619
=> tiltfile: add an api for changing the readiness mode of a resource

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/update_mode.go
Please review the following commits I made in branch maiamcc/rm-synclet-flag:
54489fccd9d0ad7cdfe41f7ab37b5cc6810958a9 (2020-07-30 12:44:42 -0400)
deprecate update_mode=syncet flag
=> deprecate update_mode=syncet flag

internal/cli/logs.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/wire_gen.go, internal/hud/server/logs_reader.go
Please review the following commits I made in branch maiamcc/logs-wire-deps:
ac4c504d0f5e7f488c182fecfd50776f0190eaae (2020-07-29 15:10:08 -0400)
logs: wire deps [ch8434]
=> logs: wire deps [ch8434]

integration/restart_process_different_user/Tiltfile, integration/restart_process_different_user/rpdu.yaml, integration/restart_process_different_user_test.go
Please review the following commits I made in branch nicks/sameimg:
ef69af995969d6c8cefc051c1a6287d354bf0256 (2020-07-30 18:48:40 -0400)
integration: rename resources so they don't interfere with each other
=> integration: rename resources so they don't interfere with each other

.circleci/config.yml, internal/k8s/names.go, internal/k8s/names_test.go, internal/k8s/target.go, internal/tiltfile/k8s.go, internal/tiltfile/k8s/state.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Hello @jazzdan, @abdullahzameek,
Please review the following commits I made in branch nicks/ch8756:
5599a2c77d12190132eea71569c935797571fc75 (2020-08-05 20:14:14 -0400)
tiltfile: add k8s_yaml(allow_duplicates=True) to allow duplicate yaml
Also, report the stack traces where the yaml was registered so that
the user has some hope of debugging this.
=> tiltfile: add k8s_yaml(allow_duplicates=True) to allow duplicate yaml

.circleci/config.yml, scripts/install.ps1
Hello @abdullahzameek,
Please review the following commits I made in branch nicks/win-verify-install:
9d9eb91a71290f0c04cd8856a530d12c588f21cf (2020-08-06 16:17:01 -0400)
Add tilt version and tilt verify-install to windows installer
fixes https://github.com/tilt-dev/tilt/issues/3674
=> Add tilt version and tilt verify-install to windows installer

internal/cli/logs.go, internal/hud/server/logs_reader.go, internal/hud/server/logs_reader_test.go, pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go, pkg/model/manifest.go
Please review the following commits I made in branch maiamcc/filter-resources:
857bdf022b6d19dc5f413bccb760be26297bb410 (2020-08-03 13:03:31 -0400)
tilt logs: add port/resource flags, filter by resource [ch8432 ch8433]
=> tilt logs: add port/resource flags, filter by resource [ch8432 ch8433]

internal/cli/logs.go
Please review the following commits I made in branch maiamcc/logsdocs:
c2066a54dd0752c6b607c0947121ab8204512e38 (2020-08-10 12:27:21 -0400)
tilt logs: docstring and unhide cmd
=> tilt logs: docstring and unhide cmd

internal/engine/build_and_deployer.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/live_update_build_and_deployer.go, internal/engine/local_target_build_and_deployer.go
(If we really don't want to make changes to internal analytics right now
I can rescind this)
was talking to @victorwuky about how to get events for user updates,
realized what we have in place right now is a. kludgy and b. incompletely
instrumented--wdyt of this instead?
=> engine: record update stats (with more tags) for ALL BaDs

internal/tiltfile/docker.go, internal/tiltfile/encoding/json.go, internal/tiltfile/encoding/yaml.go, internal/tiltfile/os/os.go, internal/tiltfile/value/string.go
Please review the following commits I made in branch nicks/stringable:
0422a04e761f78a4880c43997f1b2db003517a69 (2020-08-12 19:35:49 -0400)
tiltfile: add a stringable type to make it easier to unpack strings
=> tiltfile: add a stringable type to make it easier to unpack strings

internal/cli/logs.go, internal/hud/server/logs_reader.go, internal/hud/server/websocket_reader_test.go
Resolves issue #3692.
I'm really on the fence about
a. the `--follow` flag naming (trying to imitate `tail`, but also `-f` exists on `tilt up` and does a different thing
b. whether the default should be following or not following
Will gladly accept roll with any (even weak) opinions here.
=> tilt logs: add --follow flag, by default don't follow [ch8923]

internal/build/custom_builder.go, internal/build/docker_builder.go, internal/container/default_registry.go, internal/container/reference.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch8726:
c8e1b3ec17a962a72946491176a0e28bfa1aaa13 (2020-08-12 19:50:01 -0400)
tiltfile: add default_registry(single_name) to push all images to the same image name
Fixes https://github.com/tilt-dev/tilt/issues/2419
0422a04e761f78a4880c43997f1b2db003517a69 (2020-08-12 19:35:49 -0400)
tiltfile: add a stringable type to make it easier to unpack strings
=> tiltfile: add default_registry(single_name) to push all images to the same image name

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/local_resource.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/local_target.go
Please review the following commits I made in branch nicks/ch8725:
12499b4450137ed63d0cb2e925174f74633140b7 (2020-08-12 17:45:22 -0400)
tiltfile: add a force_parallel option for local_resource
=> tiltfile: add a force_parallel option for local_resource

internal/tiltfile/starkit/environment.go, internal/tiltfile/starkit/environment_test.go
Trying to add `__file__` as a predefined variable for all Tiltfiles. 
This is my first foray into tilt development, and I understand this attempt may be *super* off base. Guidance is welcome.
I'm writing a common Tiltfile for a bunch of our argo repositories to leverage. Part of that is to provide a function like...
```python
def install_argo():
k8s_yaml('install-argocd.yaml')
```
I load the function like...
```python
load('ext://git_resource', 'git_checkout')
git_checkout('ssh://....', checkout_dir="tilt_git/common-tilt")
load('tilt_git/common-tilt/Tiltfile', 'install_argocd')
install_argocd()
```
Right now this breaks because install_argocd() tries to load the the YAML file from the root of the original Tiltfile
Example:
```python
_mydir = os.getcwd()
def install_argocd(): …
```
=> add __file__ variable to environment

CONTRIBUTING.md, scripts/goreleaser.sh, scripts/release.sh
Hello @nicks,
Please review the following commits I made in branch nicks/token:
93688dbf1ce1d93263407a318a322f0f8352053b (2020-08-14 18:06:21 -0400)
change GITHUB_API_TOKEN back to GITHUB_TOKEN...i misunderstood something in https://github.com/tilt-dev/tilt/pull/3703
=> change GITHUB_API_TOKEN back to GITHUB_TOKEN...i misunderstood something in https://github.com/tilt-dev/tilt/pull/3703

web/src/HUD.test.tsx, web/src/HUD.tsx, web/src/analytics.ts, web/src/index.tsx
Hello @landism, @victorwuky,
Please review the following commits I made in branch nicks/selection:
d40e89ccc21a6bc3d1a35bf2f70a33f884d1044b (2020-08-17 11:46:20 -0400)
Revert "web: report log highlights to analytics (#3564)"
It sounds like we have what we need from this, and don't need
to log this anymore, right?
This reverts commit 022b45ca268da13c50d5dbc2c25755b6649e4331.
=> Revert "web: report log highlights to analytics (#3564)"

internal/cli/flags.go
as per a complaint from a user that just "default: default" wasn't helpful
=> cli: clarify docstring for web-mode flag

internal/engine/fswatch/gitmanager_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/test:
e984a1a851721a995308ffe875e771cd1363413d (2020-08-20 16:10:10 -0400)
fswatch: fix a race condition in the nnew test
=> fswatch: fix a race condition in the nnew test

Makefile, scripts/build-tilt-releaser.sh, scripts/goreleaser.sh
Please review the following commits I made in branch nicks/ch9069:
a8e4b1f59b0eb723dc80e395a1ec2a646d3f154f (2020-08-24 17:29:50 -0400)
scripts: update release container to contain a Go compile cache
=> scripts: update release container to contain a Go compile cache

internal/tiltfile/encoding/yaml.go, internal/tiltfile/encoding/yaml_test.go
Please review the following commits I made in branch nicks/decodeyaml:
d20281da983a31e9a0cddbbba8778fef25282c1a (2020-08-25 12:49:28 -0400)
tiltfile: fix a bug in decode_yaml_stream when there are empty entries
=> tiltfile: fix a bug in decode_yaml_stream when there are empty entries

internal/cli/tiltfile_result.go, internal/tiltfile/starkit/environment.go, internal/tiltfile/starkit/model.go, internal/tiltfile/tiltfile.go
this is an hour's worth of work to let someone look at the time it takes
to call various Tiltfile builtins. e.g. for the Tiltfile in the Tilt repo
(which runs linters etc.), here are all builtin calls taking longer that 500ms:
```
$ tilt alpha tiltfile-result --builtin-timings --dur-threshold 500ms
- local("cd . && find . -type f -name \"*.go\"") took 783.932424ms
- local("go list ./...") took 3.562675092s
- local("cd web && find . -type f -name \"*.ts*\" | grep -v node_modules | grep -v __snapshots__") took 609.758001ms
```
and longer than 1s:
```
$ tilt alpha tiltfile-result --builtin-timings --dur-threshold 1s
- local("go list ./...") took 3.377749034s
```
at minimum I think it's safe for Tom to install and run this off a branch;
happy to hear it shouldn't be committed (or that the …
=> tiltfile/cli: builtin timings mode for tiltfile-results

internal/tiltfile/files.go, internal/tiltfile/helm_test.go
Please review the following commits I made in branch nicks/helmwatch:
2abde4f65f56f0b1ceed530f1d5d33121bfc7548 (2020-08-26 17:53:58 -0400)
tiltfile: record the helm dependency before running helm, to help iterate on helm charts
=> tiltfile: record the helm dependency before running helm, to help iterate on helm charts

internal/cli/ci.go, internal/cli/doctor.go, internal/cli/down.go, internal/cli/flags.go, internal/cli/tiltfile_result.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/client.go, internal/k8s/env.go
Please review the following commits I made in branch nicks/ch7777:
0627a113e7374cf36106ed50eb34f7a1e2ae1fb5 (2020-08-28 19:03:41 -0400)
cli: add a --context flag for setting kube context
=> cli: add a --context flag for setting kube context

internal/dockerignore/ignore.go, internal/dockerignore/ignore_test.go, internal/watch/notify_test.go, internal/watch/watcher_naive.go
Please review the following commits I made in branch nicks/ignore:
e19c0452dddf3a20acd7d3d296c46d944d781964 (2020-09-01 18:07:57 -0400)
dockerignore: convert ignore patterns to absolute paths
In most places in Tilt, we try to use absolute paths everywhere.
So this makes things more consistent with the rest of Tilt, and lets us be
a bit more flexible in how we handle subdirs and parent dirs in ignores.
Fixes https://github.com/tilt-dev/tilt/issues/3740
=> dockerignore: convert ignore patterns to absolute paths

internal/tiltfile/metrics/metrics.go, internal/tiltfile/metrics/metrics_test.go, pkg/model/metrics.go
Please review the following commits I made in branch nicks/reportingperiod:
17f89a0050f1a277b4662415d86c8a536f462647 (2020-09-02 17:11:46 -0400)
tiltfile: add an api for adjusting the metrics reporting period
=> tiltfile: add an api for adjusting the metrics reporting period

internal/sliceutils/sliceutils.go, pkg/model/local_target.go, pkg/model/manifest.go, pkg/model/manifest_test.go
this addresses the problem i was seeing with my [POC for async deps loading](https://github.com/tilt-dev/kubernetes/blob/maiamcc/async-poc/Tiltfile)
where a change to a resource's Deps would cause the resource to rebuild.
With this PR, a change in CustomBuild.Deps or LocalResource.Deps alone
does not invalidate a build and cause the resource to rebuild.
=> model: changes to deps don't invalidate build

internal/tiltfile/docker.go, internal/tiltfile/k8s.go, internal/tiltfile/value/map.go, internal/tiltfile/value/map_test.go, internal/tiltfile/value/value.go
Having to access the value via `.Map` is a little clumsy, but I'm not sure there's a way to avoid that.
=> tiltfile: add map[string]string unpacker

internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/no-push:
881e7b7c79314b3284eda2102c8169fe1ad418cc (2020-09-02 17:50:04 -0400)
model: better support for no-build no-push custom_builds
=> model: better support for no-build no-push custom_builds

internal/cli/cli.go, internal/cli/metrics.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/metrics/controller.go, internal/engine/metrics/controller_test.go, internal/engine/metrics/meter.go, internal/engine/subscribers.go, internal/engine/upper_test.go, internal/tiltfile/metrics/metrics.go, pkg/model/metrics.go
Please review the following commits I made in branch nicks/ch9214:
dd45c783105f570298785534290df91675ffdb44 (2020-09-03 12:21:54 -0400)
engine: report metrics to opentelemetry.tilt.dev, and give an example of how to report tilt cli commands
=> engine: report metrics to opentelemetry.tilt.dev, and give an example of how to report tilt cli commands

internal/tiltfile/analytics/analytics.go, internal/tiltfile/analytics/analytics_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Adds a new command that allows Tiltfile owners to report data to analytics to allow Tilt members to work with those Tiltfile owners to give them more insight into their team's Tilt use.
Sample Tiltfile usage:
```
username = local('whoami').rstrip('\n')
experimental_analytics_report({'user': username})
```
I'm not in love with the name, but it's less bad than a lot of the ones I came up with.
=> tiltfile: add experimental_analytics_report

internal/cli/analytics.go, internal/cli/cli.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/metrics/controller.go, internal/engine/metrics/controller_test.go, internal/engine/upper_test.go, internal/git/remote.go, internal/git/remote_test.go
Please review the following commits I made in branch nicks/metrics:
d907da2425af9d72fcdaf375cbb2b94ef2bc06d6 (2020-09-04 16:30:16 -0400)
metrics: only send metrics when logged in. Attach token and other env info
=> metrics: only send metrics when logged in. Attach token and other env info

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontrol/hold_set.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/upper_test.go, internal/store/hold.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/ch9350:
254dd92902e054717447878768ffb78e4cb435f4 (2020-09-11 10:03:46 -0400)
If we're still waiting on pods to come up, hold off on any live-update builds
Fixes https://github.com/tilt-dev/tilt/issues/3759
There's two big changes in this PR -
- Making the build controller live-update aware
- Adding a new "holds" system to record why we're not building a target
I found the second one helpful for writing tests for the first,
though they could easily be broken into separate PRs if that's easier to review.
* Code is suitably …
=> If we're still waiting on pods to come up, hold off on any live-update builds

internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/container/container.go, internal/container/reference.go, pkg/model/image_target.go
Please review the following commits I made in branch nicks/custombuilder:
82d91d839043c16f298908009fc5df0333bd820b (2020-09-11 15:28:27 -0400)
builder implementation of outputs_image_ref_to for custom build scripts that want to compute their own tag
=> builder implementation of outputs_image_ref_to for custom build scripts that want to compute their own tag

internal/k8s/names.go, internal/k8s/object_selector.go, internal/sliceutils/sliceutils.go, internal/sliceutils/sliceutils_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
fixes #3761
I wanted to use some existing library for splitting w/ escapes, but I failed to find one.
=> tiltfile: allow escaping of selector strings

scripts/tilt.Dockerfile
Please review the following commits I made in branch nicks/tiltgit:
5f055f887d645761c81aa7e1839399e585f6b5ba (2020-09-18 12:38:15 -0400)
scripts: tilt 0.17.5 requires you to have git installed to use extensions
=> scripts: tilt 0.17.5 requires you to have git installed to use extensions

internal/tiltfile/helm.go, internal/tiltfile/helm_test.go
Hello @nicks,
Please review the following commits I made in branch maiamcc/helm-version-check:
aa38f01a8ec2a855eaf9e0d334288fae12705e5c (2020-09-25 14:01:01 -0400)
tiltfile/helm: throw error when we can't parse helm version, more robust version check if version output is dirty [ch9459]
Fixes #3788 (tho the helm behavior in question is fixed as of v3.3.4 -- see https://github.com/helm/helm/issues/8776)
=> tiltfile/helm: throw error when we can't parse helm version, more robust version check if version output is dirty [ch9459]

internal/cli/metrics.go, internal/engine/image_builder.go
Please review the following commits I made in branch nicks/latency:
4853ebc8d2ec38528f5e6e54949abccb27f65457 (2020-09-25 16:41:31 -0400)
engine: add image build duration metrics
This is loosely adapted from the opencensus guide on how to group and organize
metrics for consumption by metrics systems.
=> engine: add image build duration metrics

internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/service_watch.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/fake_test.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/namespace:
9b1ecc0d0327a7c0d497b0fbd12e7697d8533df3 (2020-09-30 10:28:43 -0400)
k8s: add the ability to watch a specific namespace
=> k8s: add the ability to watch a specific namespace

internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/hud/webview/view.go, internal/store/engine_state.go, pkg/model/manifest.go
Please review the following commits I made in branch maiamcc/port-forward-name:
f24ca527b74dd40e7fe2da45f3d5c0af0f741a1d (2020-10-01 18:17:28 -0400)
send all info
1b3c5558d7779de793e28cc2ea0005a0d71ce7e8 (2020-10-01 17:54:08 -0400)
current behavior
=> model/webview: endpoints sent to web UI contain name [ch9649]

internal/tiltfile/tiltfile_docker_compose_test.go
Please review the following commits I made in branch maiamcc/dc-tests:
3d070d81c4449407a57f4ac49524e9d0337799a7 (2020-10-02 11:30:40 -0400)
tiltfile: add more info to docker compose test output
=> tiltfile: add more info to docker compose test output

internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch.go, internal/k8s/fake_client.go, internal/testutils/podbuilder/podbuilder.go
Please review the following commits I made in branch nicks/ch9648:
553494746ff7b15e9a686fb9e4c5db9b7b687155 (2020-10-01 17:20:07 -0400)
k8swatch: only watch pods in namespaces we've deployed to. fixes https://github.com/tilt-dev/tilt/issues/2846
This is a big change!
Before this change, Tilt watched all pods with the "managed-by: tilt" label and
extra pod selector labels. Then it traces owner references (or uses
extra_pod_selectors) to determine which resource they belong to.
After this change, Tilt watches all pods in namespaces you deploy to, and traces
owner references (or uses extra_pod_selectors) to determine which resource they
belong to.
I think that for most users (where they're using a local cluster, or a remote
cluster where each user gets their own namespace), …
=> k8swatch: only watch pods in namespaces we've deployed to. fixes https://github.com/tilt-dev/tilt/issues/2846

internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Ha, we already had a `port_forwards` constructor method, who knew??
BTW I verified in [Grafana](https://cloud.tilt.dev/grafana/d/V29UlQIMz/tilt-global-built-ins-usage?orgId=1) that ~no one is currently using that func/it's not documented anywhere, so I feel okay about changing the signature.
=> tiltfile: port_forward constructor accepts 'name' param [ch9608]

.gitignore
My global .gitignore ignores .swp, but now that the release build happens in a container, my global .gitignore doesn't apply.
=> tilt: add .swp to .gitignore

internal/hud/webview/convert_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, pkg/model/local_target.go
Please review the following commits I made in branch maiamcc/local-resource-links:
a44f1e247f2ab96d3c01d307d8ed6a0f599f8dff (2020-10-02 17:34:02 -0400)
convert tests
42ea3e67ceb7525cc104f9bb6bec8ce954916543 (2020-10-02 17:31:09 -0400)
store links on local resource, return as endpoints
6adda95b040223292123961d30b772f05c2dc95c (2020-10-02 17:21:28 -0400)
test framework
=> local_resource/store: can attach links to a local_resource, they are returned as endpoints/sent tto frontend views [ch9660]

internal/cli/down.go, internal/cli/down_test.go, internal/k8s/entity.go
Inspired by the issue linked at the bottom of this PR I added support for keeping k8s entities based on an annotation. This mirrors the behavior also found in other k8s-adjacent tools like Helm.
For example, you could define a persistent volume to be kept, so that users can `down` everything when done but keep the database contents saved. To achieve the same behavior right now you can use an if based on `tilt_subcommand`, but that doesn't play well with e.g. the `helm_remote` extension.
The annotation is called `tilt.dev/down-policy` and supports the value `keep` (everything else is ignored). YAML usage example:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: mysql-pvc
annotations:
tilt.dev/down-policy: keep
spec:
accessModes:
- ReadWriteOnce
resources:
requests: …
```
=> k8s: add down policy annotation

web/src/ResourceInfo.test.tsx, web/src/ResourceInfo.tsx
Please review the following commits I made in branch maiamcc/endpoints-in-web:
7989df67f0659bc001518118a1008eec6fbfc8c1 (2020-10-06 17:04:31 -0400)
web/resourceInfo: trim the URL we display for endpoints (and some renaming for consistency) [ch9652]
=> web/resourceInfo: trim the URL we display for endpoints (and some renaming for consistency) [ch9652]

.circleci/config.yml, configs/storybook/.helmignore, configs/storybook/Chart.yaml, configs/storybook/Dockerfile, configs/storybook/Tiltfile, configs/storybook/deploy.sh, configs/storybook/templates/NOTES.txt, configs/storybook/templates/_helpers.tpl, configs/storybook/templates/deployment.yaml, configs/storybook/templates/hpa.yaml, configs/storybook/templates/ingress.yaml, configs/storybook/templates/service.yaml, configs/storybook/templates/serviceaccount.yaml, configs/storybook/templates/tests/test-connection.yaml, configs/storybook/values.yaml
Please review the following commits I made in branch nicks/storybook:
6083aeb30c8c9635a5e1c427ddc4dc73cc312d20 (2020-10-07 19:22:55 -0400)
throw our storybook ui components on https://storybook.tilt.dev/
e48da3754292b25a59f673fabfe88d4294f0dbfe (2020-10-07 13:01:06 -0400)
web: fix storybook server, add tests
=> throw our storybook ui components on https://storybook.tilt.dev/

internal/tiltfile/links/links.go, internal/tiltfile/links/links_test.go
Please review the following commits I made in branch nicks/struct:
eee98cf3b6efe0603035287c5fdbfb9716958cf6 (2020-10-08 16:37:01 -0400)
tiltfile: make a link object a struct
=> tiltfile: make a link object a struct

internal/k8s/watch.go
Please review the following commits I made in branch nicks/resync-period:
9fa8fdc56a492a8f2ef460a73f0a71d3acae5e34 (2020-10-12 15:43:42 -0400)
k8s: set the informer resync period to something more reasonable
=> k8s: set the informer resync period to something more reasonable

internal/k8s/client.go, internal/k8s/entity.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/owner_fetcher.go, vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/doc.go, vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme/register.go, vendor/k8s.io/client-go/metadata/interface.go, vendor/k8s.io/client-go/metadata/metadata.go, vendor/modules.txt
Please review the following commits I made in branch nicks/metadata:
f773fe2f12ad9ccbcb8eddf3ba9c1dbf3e3dbb50 (2020-10-12 16:47:16 -0400)
k8s: use the metadata client to fetch metadata, instead of full objects
I was pulling in the metadata client to help with https://github.com/tilt-dev/tilt/issues/3845,
and this seemed like a good optimization to do while I was here
=> k8s: use the metadata client to fetch metadata, instead of full objects

.circleci/config.yml
Hello @nicks,
094e9189256cd5fbc2438f262edaa35928b8885a (2020-10-12 16:54:00 -0400)
circleci: only broadcast storybook deploys on failure
=> circleci: only broadcast storybook deploys on failure

internal/cli/doctor.go
Verified that whether I've opted in or out (i.e. with `tilt analytics opt in` or `tilt analytics opt out`),`tilt doctor` now shows both fields not redacted.
=> cli: Remove [redacted] in tilt doctor

scripts/build-tilt-releaser.sh, scripts/goreleaser.sh
Hello @nicks,
Please review the following commits I made in branch nicks/cache:
87805fbe93f6a86d4f16d89b9eae6a949a407196 (2020-10-13 09:44:49 -0400)
use an empty directory for the go cache. this should make things much faster
=> use an empty directory for the go cache. this should make things much faster

internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/owner_fetcher.go, internal/k8s/watch.go, internal/k8s/watch_test.go, vendor/k8s.io/client-go/metadata/fake/simple.go, vendor/k8s.io/client-go/metadata/metadatainformer/informer.go, vendor/k8s.io/client-go/metadata/metadatainformer/interface.go, vendor/k8s.io/client-go/metadata/metadatalister/interface.go, vendor/k8s.io/client-go/metadata/metadatalister/lister.go, vendor/k8s.io/client-go/metadata/metadatalister/shim.go, vendor/modules.txt
Please review the following commits I made in branch nicks/informer:
7dc049924c0df491940e76d247e4ee4378ade18a (2020-10-14 13:39:54 -0400)
use informers to pre-populate the object metadata for lookup
=> use informers to pre-populate the object metadata for lookup

internal/k8s/target.go, internal/k8s/target_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/k8s_target.go
This was originally out of scope for the Endpoints epic, but turns out
one of our customers wants this specifically and it was fast, so!
=> tiltfile/model: can attach arbitrary links to k8s resource [ch8238]

internal/k8s/container.go, internal/k8s/container_test.go, internal/k8s/watch.go
This change updates the `WatchPods` code to not mutate objects from an informer cache.  These objects are meant to be shared across go routines and are read-only.
Before this change, running tilt as follows would crash:
```shell
export KUBE_CACHE_MUTATION_DETECTOR=true
tilt up
```
```
Tilt started on http://localhost:10350/
v0.17.8, built 2020-10-13
(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
CACHE *v1.Pod[3] ALTERED!
(*v1.Pod)(0xc0005d8bb8)({                                  (*v1.Pod)(0xc0004f5000)({
...
Image: (string) (len=22) "kindest/kindnetd:0.5.4",         Image: (string) (len=32) "docker.io/kindest/kindnetd:0.5.4",
...
})                                                         })
panic: cache …
```
=> Do not mutate objects from informer cache

internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/owner_fetcher.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/ch9946:
555d24e4bc4164c95e49348bbf733768e09dd083 (2020-10-23 13:51:38 -0400)
k8s: add missing polyfill over metadata watch on k8s 1.14-. Fixes https://github.com/tilt-dev/tilt/issues/3870
=> k8s: add missing polyfill over metadata watch on k8s 1.14-. Fixes https://github.com/tilt-dev/tilt/issues/3870

pkg/model/manifest.go, pkg/model/manifest_test.go
in response to [user issue raised in slack](https://kubernetes.slack.com/archives/CESBL84MV/p1603387895199600?thread_ts=1603295786.187500&cid=CESBL84MV)
at least theoretically, changes to `cache_from` shouldn't cause the image to change (if we assume that a cache of statement X always gives output Y -- which is the point of a cache, right?). seems possible that in practice it won't work quite like that e.g. you don't actually want to rely on a cached result of `git clone xyz`--but ideally for that you wouldn't be using the cache at all.
anyway, that seems like a rare enough situation AND `docker_build.cache_from` is very infrequently used--according to our graphs, one repo used that arg in the last 30 days--so this seems safe to try and we can roll it back if we get complaints. wdyt?
=> model: docker_build.cache_from changes don't invalidate manifest

scripts/install.sh
On Alpine Linux, the bash variable `$OSTYPE` is `linux-musl`
instead of `linux-gnu`. But since the `tilt` binary is
statically linked, it will work anyway, so we can let the
script do its thing on Alpine.
“I'd just like to interject for a moment. What you're referring
to as Linux, is in fact, GNU/Linux, or–
— Well, actually, I'm running Alpine Linux on this system, so–
— I think you mean musl/Linux. It's only called Alpine Linux when
it comes from the Alps region of France.”
See #3883.
=> Allow install script to work on Alpine

scripts/install.sh
- Correctly display $OSTYPE instead of $OS
- Add link to the documentation page
See #3883.
=> Improve install script error message for unsupported platforms

internal/tiltfile/include/include.go, internal/tiltfile/include_test.go, internal/tiltfile/loaddynamic/load.go, internal/tiltfile/loaddynamic/load_test.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/include:
ecb9e44b3c954247483ad57252abd7dadee0479c (2020-10-27 14:54:06 -0400)
tiltfile: implement load_dynamic.
Intended as a replacement for include(), but with a more self-descriptive name
and better semantics for loading symbols.
Fixes https://github.com/tilt-dev/tilt/issues/3433
=> tiltfile: implement load_dynamic.

internal/engine/local_target_build_and_deployer.go
Please review the following commits I made in branch nicks/ch10068:
245e7798ba3e7d28f1c9196f2959c520ce5ce7bb (2020-11-02 17:20:19 -0500)
engine: add more artificial delays after local_resource :cry:. Fixes https://github.com/tilt-dev/tilt/issues/3900
=> engine: add more artificial delays after local_resource :cry:. Fixes https://github.com/tilt-dev/tilt/issues/3900

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go
Please review the following commits I made in branch nicks/ch10137:
76719186f158c8934c70b88e6b2b85570d9ee176 (2020-11-10 16:00:04 -0500)
engine: only mutate PodManagementPolicy for images we build. Fixes https://github.com/tilt-dev/tilt/issues/3906
=> engine: only mutate PodManagementPolicy for images we build. Fixes https://github.com/tilt-dev/tilt/issues/3906

.circleci/config.yml, CONTRIBUTING.md, scripts/release-ci.sh
Hello @nicks,
cb0773e739972bf73c3c3ba8bec52786b755de2e (2020-11-12 15:50:50 -0500)
ci-based release process
=> ci-based release process

scripts/release-ci.sh
Hello @nicks,
Please review the following commits I made in branch nicks/tokendir:
020a9ff8a5280106be8d8a0538c28f42c21af50b (2020-11-12 23:41:43 -0500)
release: put the token in the legacy token dir
=> release: put the token in the legacy token dir

web/.eslintrc, web/src/SidebarPin.tsx, web/src/SidebarResources.test.tsx
Prior to this PR, we only record analytics when a user takes the action of pinning or unpinning a resource. It's possible that most common pinning workflow will be to pin the resources one most cares about and then never touch the pins again. This would mean that in order to evaluate current pin usage, we have to go back through all analytics events looking for when the user pinned items.
Also record the number of pinned items when the UI is loaded.
=> web: analytics track number of pinned resources on startup

web/src/SidebarItem.tsx, web/src/SidebarPin.tsx, web/src/SidebarResources.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Fixes #3903
That issue has one repro for the issue, but I've seen similar unpredictable behavior when iterating on the sidebar, and it feels kind of house-of-cardsy. @hyu suggested making it work without the `float`s so that we have one fewer layout system competing for control, which seems to have done the trick.
=> web: fix sidebar wrapping

.goreleaser.yml
Goreleaser uses https by default [for Homebrew](https://goreleaser.com/customization/homebrew/). 
This is just a change to conform to that standard, and provide a tiny bit of extra security (and anonymity) in the process.
=> Change Homebrew URLs to https

internal/store/manifest_target_test.go, internal/tiltfile/tiltfile_test.go, pkg/model/manifest.go
Fixes an issue reported in [#3815](https://github.com/tilt-dev/tilt/issues/3815#issuecomment-731091427).
in `tilt alpha tiltfile-result`, local resources look like this:
```
{
"Name": "frontend-yarn",
"ImageTargets": null,
"TriggerMode": 0,
"ResourceDependencies": null
},
```
Or, more generally, we aren't outputting the manifests' deploy targets at all, which also means yaml contents can't be verified.
Make DeployTarget public, and therefore serialized.
This could also be done by providing a `MarshalJSON` instead of making the field public. I went this way because the other way creates an opportunity for devs to add fields to `Manifest` without realizing they also need to be in `MarshalJSON`, and leaving them out of `tiltfile-result`.
I'm unaware of a reason that this field is private and …
=> tilt: include deploy targets in tiltfile-result

internal/cli/metrics.go, internal/engine/image_build_and_deployer.go, internal/engine/metrics.go
Please review the following commits I made in branch nicks/deploy:
6fe3dded6d4a627955586df57e05e9bdce5c42ae (2020-11-18 17:40:35 -0500)
engine: add metric aggregations for k8s deploys
=> engine: add metric aggregations for k8s deploys

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/metrics/actions.go, internal/engine/metrics/controller.go, internal/engine/metrics/mode_controller.go, internal/engine/metrics/mode_controller_test.go, internal/engine/metrics/yaml.go, internal/engine/subscribers.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/metrics.go, pkg/model/metrics.go
Please review the following commits I made in branch nicks/localmetrics:
80df10eee3bac18e78412619a142ac21b5c2e6bc (2020-11-20 12:02:38 -0500)
engine: add a controller that deploys a local metrics stack
=> engine: add a controller that deploys a local metrics stack

internal/engine/image_builder.go, internal/engine/metrics/mode_controller.go, internal/engine/metrics/yaml.go, internal/engine/upper.go, internal/engine/upper_test.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/localmetrics2:
19a52f3909508db9a66165e99f0ba46ae1cb5bff (2020-11-24 11:49:30 -0500)
engine: merge local metrics services into the engine state
=> engine: merge local metrics services into the engine state

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/serialize.go, internal/k8s/serialize_test.go, internal/k8s/watch_test.go, vendor/modules.txt
Please review the following commits I made in branch nicks/ch10270:
52dba84ebf72495ae31fde5a848f79aae6b9ecb4 (2020-11-23 16:13:28 -0500)
k8s: use the Helm kube client instead of shelling out to a separate process to apply changes
fixes https://github.com/tilt-dev/tilt/issues/3943
=> k8s: use the Helm kube client instead of shelling out to a separate process to apply changes

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/serialize.go, internal/k8s/serialize_test.go, internal/k8s/watch_test.go, vendor/modules.txt
Hello @nicks,
Please review the following commits I made in branch nicks/update-error:
9a9a0d2ddaf701be010c09d99f60c462145530b4 (2020-11-25 17:46:55 -0500)
Revert "k8s: use the Helm kube client instead of shelling out to a separate process to apply changes (#3945)"
This reverts commit f711652e8ad897eef857399f9ae89ebcdb8bec73.
=> Revert "k8s: use the Helm kube client instead of shelling out to a separate process to apply changes (#3945)"

internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/watcher.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/watchbug:
828404bab78263eb3b97349db61cc642083a64b7 (2020-12-01 10:27:13 -0500)
k8swatch: fix a bug where a manifest is removed then re-added, but we never find the pod
=> k8swatch: fix a bug where a manifest is removed then re-added, but we never find the pod

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/analytics/doc.go, internal/engine/metrics/doc.go, internal/engine/metrics/mode_controller.go, internal/engine/metrics/mode_controller_test.go, internal/engine/metrics/wire.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/store/metrics.go, internal/user/api.go, internal/user/api_test.go, internal/user/fake.go, internal/user/file.go, internal/user/helpers.go, internal/user/wire.go, pkg/model/metrics.go
Please review the following commits I made in branch nicks/localmetrics5:
1e84937932f5633abc503ac17d0ab128e059634c (2020-11-30 13:30:29 -0500)
server: add an api for turning on metrics from local
=> server: add an api for turning on metrics from local

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/helm.go, internal/k8s/serialize.go, internal/k8s/serialize_test.go, internal/k8s/watch_test.go, vendor/modules.txt
Hello @nicks,
Please review the following commits I made in branch nicks/ch10270:
4ea5e09504d71b0a9e13b4954a0d5695ed8dbd6a (2020-11-25 18:56:08 -0500)
k8s: use the Helm kube client instead of shelling out to a separate process to apply changes, try #2
9a9a0d2ddaf701be010c09d99f60c462145530b4 (2020-11-25 17:46:55 -0500)
Revert "k8s: use the Helm kube client instead of shelling out to a separate process to apply changes (#3945)"
This reverts commit f711652e8ad897eef857399f9ae89ebcdb8bec73.
=> k8s: use the Helm kube client instead of shelling out to a separate process to apply changes, try #2

internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Hello @nicks,
Please review the following commits I made in branch maiamcc/port-forward-host:
dd4ae1c6bac6ad7c08ea2cb19b58ec08439ced0f (2020-12-07 14:16:05 -0500)
tiltfile: port_forward constructor supports host param
=> tiltfile: port_forward constructor supports host param

internal/tiltfile/starkit/set_state.go
lol I think this was copypasta, `inTyp` is already a type, this
string formatting just prints `*reflectType` always, which is not very helpful
cc @ellenkorbes in case you're curious :P
=> tiltfile: fix some error reporting in setStateFn

integration/crash_test.go, internal/cli/ci.go, internal/cli/cli.go, internal/cli/flags.go, internal/cli/up.go, internal/cli/utils.go, internal/hud/server/controller.go
Please review the following commits I made in branch nicks/ch10491:
d86aa5bb40ccd7b155e616144c6da966ae3acf8c (2020-12-10 18:03:18 -0500)
cli: add TILT_HOST and TILT_PORT env variables
Clarify that --port and TILT_PORT are both Officially Endorsed
ways to run two Tilts simultaneously.
Fixes https://github.com/tilt-dev/tilt/issues/3948
=> cli: add TILT_HOST and TILT_PORT env variables

internal/cloud/io_test.go, internal/hud/webview/convert.go
Hello @hyu,
Please review the following commits I made in branch nicks/ch10422:
b934afd0aa0d60c7e2ecdd9110be0802ef0dc251 (2020-12-08 13:16:11 -0500)
webview: Tiltfile has no runtime status
=> webview: Tiltfile has no runtime status

web/src/HUD.tsx
Please review the following commits I made in branch nicks/ch10548:
4b1b16067b686b073a96c244a19393284ba2f3be (2020-12-17 14:47:54 -0500)
web: don't show the metrics tab in snapshot mode
=> web: don't show the metrics tab in snapshot mode

.circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/publish:
9622b57005497bc4047791139a2a113922dff0b0 (2020-12-17 16:10:55 -0500)
circleci: add tilt deploy context to publish-assets
=> circleci: add tilt deploy context to publish-assets

CONTRIBUTING.md
Hello @nicks,
Please review the following commits I made in branch maiamcc/rm-synclet-release:
79413a9862e8c5ca35175fce3c80a279bd42fb38 (2020-12-18 11:44:25 -0500)
docs: rm synclet release notes from contributing doc
=> docs: rm synclet release notes from contributing doc

web/src/AccountMenu.stories.tsx, web/src/AccountMenu.test.tsx, web/src/AccountMenu.tsx, web/src/SidebarAccount.test.tsx, web/src/SidebarAccount.tsx
Hello @nicks,
Please review the following commits I made in branch nicks/accountmenu:
ed383588f803c8ca4374f97b3a6fae53f4061b4b (2020-12-18 19:24:52 -0500)
web: split AccountMenu into a standalone component
=> web: split AccountMenu into a standalone component

internal/build/custom_builder.go, internal/engine/local/execer.go, internal/engine/local_target_build_and_deployer.go, internal/tiltfile/files.go, pkg/logger/env.go, web/storybook.tiltfile
Please review the following commits I made in branch nicks/lines:
acd5a0ceb0e63d01dc8d102b3adf81008c365827 (2020-12-21 12:33:54 -0500)
logger: default env variables for logging
This makes Tilt more robust when subprocesses try to adjust their output
for the current terminal.
Fixes https://github.com/tilt-dev/tilt/issues/4007
=> logger: default env variables for logging

web/src/FloatDialog.tsx, web/src/ShortcutsDialog.stories.tsx, web/src/ShortcutsDialog.tsx, web/src/SidebarAccount.stories.tsx, web/src/SidebarAccount.test.tsx, web/src/SidebarAccount.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/menus:
7a463482c31273220575c54038d5ccdf6865e421 (2020-12-18 17:01:06 -0500)
web: replace react-modal with Popover in dialogs
With react-modal, we had to manually position the dialogs
to anchor them to the trigger buttons.
With the new system, the Popover library handles the anchor.
This will make it much easier to use the dialogs in different UIs
=> web: replace react-modal with Popover in dialogs

internal/tiltfile/local_resource.go, internal/tiltfile/tests_test.go, internal/tiltfile/tiltfile_state.go, pkg/model/local_target.go
I don't know if we want to merge this into master or just leave it in a mega branch but: here's a tiltfile function `test` that just wraps local resource to create a test resource -- again, just a local resource with an `isTest` flag on it. cc @ellenkorbes
=> Tests MVP: a much less hacky way of specifying tests

internal/k8s/registry.go, internal/k8s/registry_test.go
Please review the following commits I made in branch nicks/k3dregistry:
596a34cc99699a9ec470b9d2eefacbd0b602d435 (2020-12-22 12:31:26 -0500)
k8s: remove registry instructions until we have a registry for k3d 3.0
=> k8s: remove registry instructions until we have a registry for k3d 3.0

web/src/HUD.tsx, web/src/OverviewGrid.stories.tsx, web/src/OverviewGrid.tsx, web/src/OverviewItemView.stories.tsx, web/src/OverviewItemView.tsx, web/src/OverviewPane.stories.tsx, web/src/OverviewPane.tsx, web/src/OverviewResourceBar.stories.tsx, web/src/OverviewResourceBar.tsx, web/src/OverviewResourceDetails.stories.tsx, web/src/OverviewResourceDetails.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewResourceSidebar.tsx, web/src/OverviewTabBar.stories.tsx, web/src/OverviewTabBar.test.tsx, web/src/OverviewTabBar.tsx, web/src/PathBuilder.tsx, web/storybook.tiltfile
Please review the following commits I made in branch nicks/pathbuilder:
9d0bd0e329a5cb22a77a6e961bed79bea7b2bf3f (2020-12-22 12:01:18 -0500)
web: Use contexts to provide PathBuilder
=> web: Use contexts to provide PathBuilder

web/src/AnsiLine.scss, web/src/HUD.tsx, web/src/LogStore.ts, web/src/OverviewLogPane.stories.tsx, web/src/OverviewLogPane.test.tsx, web/src/OverviewLogPane.tsx, web/src/OverviewResourceDetails.stories.tsx, web/src/OverviewResourceDetails.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/ch10498:
06851e637895dcc66d2d9639a4df5b92b6b35dae (2020-12-23 12:25:13 -0500)
web: Add OverviewLogPane, a fork of LogPane
LogPane is pretty closely coupled with window-based scrolling and the particular
DOM layout of the old view, so probably we were going to need to fork it either way.
Meanwhile, I'm pretty unhappy with both the performance and flexibility of the old log pane.
It doesn't really fit in well with React's view of the world. React is optimized
so that any component can be live updated. But most logs need to be rendered once and
never touched again.
OverviewLogPane uses a lot of the existing CSS from LogPane, but substantially
changes rendering to vanilla JS, and gets rid of the concept of a render window. …
=> web: Add OverviewLogPane, a fork of LogPane

web/src/LogStore.ts, web/src/OverviewLogPane.stories.tsx, web/src/OverviewLogPane.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/logpane3:
c8dbb2163f068089e4cdaad9a1714469bb1c6cda (2021-01-04 13:13:15 -0500)
web: redraw the OverviewLogPane when new logs come in
fa99ea3bb4f02fec9eac06ab131f168eaaf19415 (2021-01-04 11:25:34 -0500)
web: Add OverviewLogPane, a fork of LogPane
LogPane is pretty closely coupled with window-based scrolling and the particular
DOM layout of the old view, so probably we were going to need to fork it either way.
Meanwhile, I'm pretty unhappy with both the performance and flexibility of the old log pane.
It doesn't really fit in well with React's view of the world. React is optimized
so that any component can be live updated. But most logs need to be rendered once and
never touched again.
OverviewLogPane uses a lot of the …
=> web: redraw the OverviewLogPane when new logs come in

web/src/LogPane.stories.tsx, web/src/LogStore.test.ts, web/src/LogStore.ts, web/src/logs.ts, web/src/types.ts
Hello @hyu,
Please review the following commits I made in branch nicks/logpane2:
d03bed440557440ff6c830b04bfb8c7c2936a7fd (2021-01-04 16:21:02 -0500)
web: add an api for incremental logs to the LogStore
bfcaac24fb4fc051e454dbc106447cccf77a86e9 (2021-01-04 13:13:54 -0500)
web: redraw the OverviewLogPane when new logs come in
=> web: add an api for incremental logs to the LogStore

internal/engine/runtimelog/podlogmanager.go, internal/engine/runtimelog/podlogmanager_test.go
Please review the following commits I made in branch nicks/logdupe:
c8c3f71f4fa40e02df115a56272d55e5430d8fce (2021-01-05 16:21:33 -0500)
engine: fix a bug in the log rotation handler where sometimes it would erroneously duplicate a log
=> engine: fix a bug in the log rotation handler where sometimes it would erroneously duplicate a log

internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go
Please review the following commits I made in branch nicks/ch10676:
69f390375c330c2cfb9f32c329d4fc0bf272158a (2021-01-08 15:13:42 -0500)
tiltfile: change os.path.exists to not watch files. Fixes https://github.com/tilt-dev/tilt/issues/4062
=> tiltfile: change os.path.exists to not watch files. Fixes https://github.com/tilt-dev/tilt/issues/4062

internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/actions.go, internal/hud/server/server.go, internal/hud/server/server_test.go, pkg/model/manifest.go, pkg/model/override.go, pkg/model/trigger_mode.go
Please review the following commits I made in branch maiamcc/override-trigger-mode:
ea43d65b088d8635febe50c88f8ecd958d835c2f (2021-01-07 17:50:02 -0500)
validate trigger mode, double check request in engine
17518058ff8ebd4f0b82c8bf54d3dfa585e9b9d1 (2021-01-07 17:49:58 -0500)
missing return and rename tests
3851de8b81e4e3c8946516c7b96a0fae59b78d03 (2021-01-07 17:49:56 -0500)
more specific implementation
2c7cbfb2507d39c7a870925170301e0a95fbdfa1 (2021-01-07 17:49:52 -0500)
server: first pass at override endpoint
=> server: api endpoint for setting trigger mode [ch10576]

web/src/FloatDialog.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewTabBar.test.tsx, web/src/OverviewTabBar.tsx, web/src/assets/svg/close.svg
Interaction:
Note: This PR didn't introduce it, but there's a weird effect where trying to close the only remaining tab doesn't actually remove the tab. (It does take you to Overview, though.)
=> web: clean up design for tabs UI

.circleci/config.yml
Hello @nicks,
cd3009b5f74dcccaac1af7235d02b32bbade6ce5 (2021-01-13 16:35:42 -0500)
circleci: add a status notification when the release starts
=> circleci: add a status notification when the release starts

internal/engine/local/execer.go, internal/engine/local/execer_test.go, internal/engine/local_target_build_and_deployer.go, internal/localexec/localexec.go, internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/live_update.go, internal/tiltfile/local_resource.go, internal/tiltfile/telemetry/telemetry.go, internal/tiltfile/tests_test.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/value.go, pkg/logger/env.go, pkg/model/cmd.go
New, optional argument(s) for `local` and `local_resource` to pass
environment variables to the invoked command. In all cases, the
argument is a `dict` and must have both string keys and values:
no type conversion will take place.
For `local`, there is a single `env` argument.
For `local_resource`, there is `env`, which is used for the update
command (`cmd`) and `serve_env`, which is used for the serve command
(`serve_cmd`).
Any environment variables that are passed will take precedence over
the parent process' (i.e. `tilt`) environment. However, it's possible
to read from the environment in `Tiltfile`, so in the event that a
default is desired, a practical approach is to combine with `os.getenv`:
```python
local_resource('mycmd', './mycmd', env={'KEY': os.getenv('KEY', 'default')})
``` …
=> tiltfile: add env support for local + local_resource

web/package.json
I ended up with latest node LTS in my env - webpack config & everything seems happy with v14 as well. This doesn't change what CI will actually use to build the app, but just makes it so yarn won't give up installing deps in a local dev env that's not on node v12.
=> web: add support for latest node LTS (v14)

web/src/OverviewItemView.stories.tsx, web/src/OverviewItemView.tsx, web/src/OverviewResourceDetails.stories.tsx, web/src/OverviewResourceDetails.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/podid:
46d628b7d9ea787b81a94d399a06c909b325b481 (2021-01-14 11:43:22 -0500)
web: display the pod ID, and truncate the text
=> web: display the pod ID, and truncate the text

internal/engine/local/actions.go, internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/upper.go, internal/hud/webview/convert_test.go, internal/store/runtime_state.go, pkg/model/process_state.go
In preparation for `local_resource` readiness checks, represent
the process state via a specific type (modeled after the K8s
`ContainerState`).
This disambiguates it from the higher-level `RuntimeStatus` which
will be the synthesis of the process state + readiness probe.
=> engine: refactor process state representation

web/src/OverviewPane.test.tsx, web/src/OverviewPane.tsx, web/src/OverviewResourceBar.tsx, web/src/testdata.tsx
Please review the following commits I made in branch maiamcc/test-section-tests:
5c6b5eda71a15ca774cf2445b201cdaa0b03b3b0 (2021-01-15 12:29:33 -0500)
ui: tests for test section of overview pane
=> ui: tests for test section of overview pane

internal/hud/webview/convert_test.go, internal/store/engine_state.go, internal/store/runtime_state.go
Currently a noop in that the readiness probe status is simply
initialized to successful and then never touched. In the future,
this will continue to be the behavior for local resources without
a readiness probe defined, while local resources with a readiness
probe will start off in a failing state until the process is up &
probe passes. (This aligns with the behavior of readiness probes
in K8s.)
=> engine: add initial touch points for local readiness probe

internal/cli/down.go
Please review the following commits I made in branch nicks/down:
2cc5a340cfdcb1706f1a045d1f0e9a987c5f9084 (2021-01-20 11:25:09 -0500)
cli: improve documentation in 'tilt down'
- Add notes on down-policy
- Fix the link to the tiltfile config docs
=> cli: improve documentation in 'tilt down'

internal/kustomize/dependencies.go, internal/kustomize/dependencies_test.go
fixes #4086
Kustomize [deprecated](https://github.com/tilt-dev/tilt/blob/15d0c94ccc08230d3a528b14cb0a3455b947d13c/vendor/sigs.k8s.io/kustomize/api/types/kustomization.go#L102) the "bases" name and now everything should be specified as "resources". Tilt does not recurse into "resources" to find deps of bases specified this way.
Also recurse into "resources"
=> tilt: kustomize: check for recursive deps of bases specified under "resources"

web/src/HUD.test.tsx, web/src/HUD.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewTabBar.stories.tsx, web/src/OverviewTabBar.test.tsx, web/src/OverviewTabBar.tsx, web/src/SidebarItemView.stories.tsx, web/src/SidebarItemView.tsx, web/src/SidebarResources.tsx, web/src/TabNav.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/types.ts
Please review the following commits I made in branch nicks/tabnav:
7082148107d1ba54a6f191f594c052429fda98a6 (2021-01-19 19:59:13 -0500)
web: pull up all the Tab logic into a separate React context
We're moving towards a model where clicking on the Sidebar
can have complex interactions with the Tab bar, so we need
a better way to centralize state between them.
This PR doesn't change any of the semantics. It just moves state around.
=> web: pull up all the Tab logic into a separate React context

web/src/OverviewItemView.tsx, web/src/OverviewPane.stories.tsx, web/src/SidebarItemView.stories.tsx, web/src/SidebarItemView.tsx, web/src/SidebarPin.tsx, web/src/SidebarPinButton.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/style-helpers.ts
Hello @hyu,
Please review the following commits I made in branch nicks/ch10512:
517ab132fb94371f03501fdbe224812db4edfa1c (2021-01-21 17:42:08 -0500)
web: move pin button inside SidebarItemVeiw and OverviewItemView cards
2171601e02cddb6c87a6dbfdf9ac568fbff66767 (2021-01-21 14:40:07 -0500)
web: split SidebarPinButton into a standalone component
=> web: move pin button inside SidebarItemVeiw and OverviewItemView cards

web/src/OverviewActionBar.tsx, web/src/OverviewActionBarKeyboardShortcuts.test.tsx, web/src/OverviewActionBarKeyboardShortcuts.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/ch10892:
83e0392bdda1c0db8b1643b490f8d9f0a502217a (2021-01-22 13:16:49 -0500)
web: Add endpoint keyboard shortcuts.
This is a straight-up copy-and-paste from
https://github.com/tilt-dev/tilt/blob/master/web/src/ResourceInfoKeyboardShortcuts.tsx
=> web: Add endpoint keyboard shortcuts.

web/src/OverviewLogPane.stories.tsx, web/src/OverviewLogPane.test.tsx, web/src/OverviewLogPane.tsx, web/src/OverviewResourceDetails.tsx, web/src/logfilters.ts, web/src/types.ts
Hello @hyu,
Please review the following commits I made in branch nicks/filters:
99c25d98c45d019d29f0361f272e888f4281eb05 (2021-01-22 15:47:34 -0500)
web: infer log filters from the url
=> web: infer log filters from the url

web/src/TabNav.test.tsx, web/src/TabNav.tsx
Please review the following commits I made in branch nicks/ch10949:
0415af82f97e65b92e8933b47337f9b472c3fdd4 (2021-01-25 11:50:45 -0500)
web: change Sidebar tab semantics
now, we never change the number of tabs open if the selected resource is already open
=> web: change Sidebar tab semantics

web/src/OverviewItemView.tsx, web/src/SidebarIcon.tsx, web/src/SidebarItemView.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Hello @hyu,
Please review the following commits I made in branch nicks/ch10982:
f5d18e56b8f4dcc37b08b231e20807ba011a34e8 (2021-01-25 20:03:00 -0500)
web: fix card layouts on firefox
I suspect there's some deeper bug here where setting height: 100%
on a flex child isn't working correctly in Firefox...but I think
setting height: 100% on a flex child isn't a great practice anyway.
=> web: fix card layouts on firefox

web/src/HUD.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewTabBar.stories.tsx, web/src/OverviewTabBar.test.tsx, web/src/OverviewTabBar.tsx, web/src/SidebarKeyboardShortcuts.test.tsx, web/src/TabNav.test.tsx, web/src/TabNav.tsx
Please review the following commits I made in branch nicks/ch10999:
950758da3b62996bec2cdd816985a6146a7b3863 (2021-01-26 15:47:02 -0500)
web: centralize all tabs dataflow into OverviewTabNavProvider
This is what I should have done in the first place. It makes everything
much simpler and ensures we're not affected as much by React scheduler
conditions.
=> web: centralize all tabs dataflow into OverviewTabNavProvider

web/src/OverviewItemView.stories.tsx, web/src/OverviewItemView.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/ch10958:
57847ef15fbdb74bad4d1e6f27f326209cfc3eb7 (2021-01-26 16:48:44 -0500)
web: Revamp how the OverviewItemView details are rendered, to improve the animation and interaction
d0d5321dc0e042394ca6b370aa940074c57ef068 (2021-01-26 16:05:56 -0500)
engine: handle readiness probes for local resources (#4102)
Local controller creates a probe worker when starting a serve command
if a probe spec is defined.
The worker will emit readiness probe status update actions that will
result in updates to the local runtime state, which internally tracks
the current passing state of the readiness probe. (Local resources
without a readiness probe will consider themselves to always have a
passing probe, but this is never exposed.)
Some …
=> web: Revamp how the OverviewItemView details are rendered, to improve the animation and interaction

integration/fixture_test.go, integration/local_resource/Tiltfile, integration/local_resource/probe.sh, integration/local_resource_test.go, internal/engine/local/controller.go
~There's some general integration tests improvements here (cc @nicks @maiamcc) to copy the test resource directory (i.e. the dir with `Tiltfile` for the test) to a temporary directory that gets cleaned up at the end of the test. The local resource test was already creating files and manually cleaning up - the readiness probe additions added more to that; I figured rather than continuing to manually clean up (and potentially risk messing with local working repo), this made sense.~
**EDIT:** Just kidding - some of the integration tests are structured in such a way that this isn't quite as straightforward (i.e. it'll need to touch a bunch of the fixtures) so reverted it and added explicit cleanup for new files in this test. 
Main focus is expanding the `local_resource` integration test to …
=> integration: add coverage for local readiness probes

integration/crash_test.go, integration/tilt.go, integration/tilt_args_test.go
This just makes things easier if you've got Tilt running in the
background on your machine already so that you can still run an
integration test.
=> integration: use a random port for each tilt up invocation

web/src/LogPaneLine.scss, web/src/OverviewLogPane.stories.tsx, web/src/OverviewLogPane.test.tsx, web/src/OverviewLogPane.tsx
Hello @hyu,
Please review the following commits I made in branch nicks/errorcontext:
eab5bf25dbed1ecff30dc1765eb3df638e416110 (2021-01-27 22:41:12 -0500)
web: add (more) links to errors that scrolls to the error in-context
7302ea2845620004029acb58b303fa6aa621d4ed (2021-01-27 14:44:18 -0500)
web: add counts to error and warning pickers
=> web: add (more) links to errors that scrolls to the error in-context

internal/engine/configs/configs_controller.go, internal/engine/configs/configs_controller_test.go, internal/tiltfile/tiltfile.go
Please review the following commits I made in branch nicks/ch11044:
b3587be01ec274bddaffef5ef96e87f45a70045f (2021-01-28 15:24:34 -0500)
web: log tiltfile errors with the right error level
also, simplify configs controller tests while i'm here
=> web: log tiltfile errors with the right error level

internal/tiltfile/probe/probe.go, internal/tiltfile/probe/probe_test.go
Oversight when adding a default of `localhost` - the `host` arg needed to be made optional, which means `port` is the only positional (required) argument.
=> tiltfile: make host truly optional for http/tcp probes

web/src/HUD.tsx, web/src/LogStore.test.ts, web/src/LogStore.ts
Truncate logs included in the snapshot upload to avoid being rejected
by the server for > 4MB size.
The logs are truncated to 2MB as there is a substantial amount of
overhead from JSON as well as the rest of the actual UI state that
needs to fit in there as well.
Closes #3687.
=> web: ensure snapshots are under 4MB upload limit

web/package.json, web/src/HUD.tsx, web/src/LocalStorage.test.tsx, web/src/LocalStorage.tsx, web/src/OverviewPane.test.tsx, web/src/OverviewSidebarOptions.test.tsx, web/src/SidebarPin.tsx, web/src/SidebarResources.test.tsx, web/src/TabNav.test.tsx, web/src/TabNav.tsx, web/yarn.lock
The existing local storage code works ok for things that want to store stuff in a context and pass it down through a call stack, but is really onerous if you basically just want a `useState` backed by local storage and keyed by the tiltfile key.
This PR:
1. Separates those concerns, so now a component can just `usePersistentState` to get state backed by localstorage and keyed by the tiltfile without having to define a context and context producer and so on.
2. outsources the actual localstorage stuff to a library
=> web: simplify localstorage + use library

internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/tiltfile/probe/probe.go, internal/tiltfile/probe/probe_test.go
Original behavior tried to fail gracefully, i.e. let the resource
start and just mark it as ready with a warning logged that the probe
spec was bad. There was a bug, however, which meant that dependent
resources would still see it as not ready and not start.
In the end, it seems that this behavior was more confusing than
helpful, so it's better to just prevent the resource from startup
if the probe spec is invalid.
Some validation has also been pushed down to the `Tiltfile` level,
which will provide better errors with line numbers. It's worth
noting, however, that there will likely always be some validation/
cases that we cannot catch during `Tiltfile` parsing, so the logic
in the controller is still important.
Closes #4156.
=> engine: do not start local resources with invalid probe specs

internal/store/manifest_target.go, internal/store/manifest_target_test.go
Please review the following commits I made in branch nicks/pending:
19f305eee54c6d16c8ff254ab818a42c00d1f25a (2021-02-04 13:23:42 -0500)
store: even if a local_resource has no build command, it can still be pending
=> store: even if a local_resource has no build command, it can still be pending

web/src/LogPaneLine.scss
https://app.clubhouse.io/windmill/epic/11101/make-log-font-size-smaller
=> web: Use smallest font for log lines

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_test.go, pkg/model/docker_compose_target.go
Adds `links()` support to `dc_resource` for parity with k8s and local. I tried following the original local pr to add links, but I'm sure I've missed a thing or two.
=> tiltfile: Adds links to dc_resources

integration/local_resource/Tiltfile, internal/tiltfile/probe/probe.go, internal/tiltfile/probe/probe_test.go
There's often a lot of boilerplate involved for optional object arguments
that can be `None` or an actual value; it's necessary to use a
`starlark.Value`, check to see if it's `nil` (kwarg not specified)
or `starlark.None` (kwarg specified) or present and then make sure
the expected type constraint is met.
~~This is exacerbated by `starlarkstruct.Struct`, which does not play
nice with Go nil by design, and when you've got a struct with embedded
structs that can be `None`, this results in a bunch of extra nil/None/type
checking on top of the above.~~
~~Adding an `Optional` type helps abstract some of this and provides
type-checking and a couple convenience methods depending on whether
you're interoping with Go code (`ValueOrNil()`) or Starlark types
(`ValueOrNone()`). There's still some …
=> tiltfile: make probe types play nicer with None

web/src/OverviewResourceBar.tsx
https://app.clubhouse.io/windmill/story/11154/edit-font-size
**Before**
**After**
**Before**
**After**
Surbhi says that the font size should be at least 12px. With this change, it will be 13px.
=> web: Change OverviewResourceBar font size from smallester to smallest

internal/hud/server/server.go
Serialize with the JSON protobuf marshaler rather than stdlib so
that we get `camelCase` rather than `snake_case`.
(This is using the "deprecated" `jsonpb` rather than `protojson`
as we haven't moved to `google.golang.org/protobuf` yet.)
=> server: fix local snapshot testing mode

internal/store/engine_state.go, internal/store/engine_state_test.go
Follow up to https://github.com/tilt-dev/tilt/pull/4164
This should wrap up link support for `dc_resource`s.
=> engine: Adds dc_resource link support

web/src/LocalStorage.tsx, web/src/OverviewPane.test.tsx, web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/SidebarItemView.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx
fwiw all the indenting in the tests is just for:
```
afterEach(() => {
localStorage.clear()
})
```
=> web: persist sidebar options in localStorage

web/src/OverviewLogPane.tsx
Please review the following commits I made in branch nicks/autoscroll:
83e26bbf5bae9c35321a89ed9173e0ae49ff7466 (2021-02-04 13:05:49 -0500)
web: enable autoscroll in snapshots
we lazily render log lines, so autoscroll needs to kick in to scroll to the
bottom of the first render. We still leave in the logic around
re-engaging autoscroll on scrolldown.
=> web: enable autoscroll in snapshots

web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/SidebarResources.test.tsx
streamline handling of the alertsOnTop toggle with show/hide resource/test checkboxes
also add some test helpers
=> ui: test and resource sidebar toggles use onlick instead of onchange

web/src/OverviewGrid.tsx
https://app.clubhouse.io/windmill/story/11181/section-divider-line
=> web: Add divider lines between sections in Overview

web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/SidebarResources.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
I'm not sure if it's poor form to simply set `visibility: hidden` rather than omit the checkboxes entirely - it's certainly vastly easier than changing a bunch of css to keep the 'alerts on top' toggle in place when the filter checkboxes are absent.
=> web: show 'alerts on top' toggle even when there are no tests

go.mod, go.sum, integration/local_resource_test.go, internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/local/probe.go, internal/engine/local/probe_fake.go, vendor/github.com/tilt-dev/probe/pkg/probe/worker.go, vendor/modules.txt
When setting up readiness probes, it can be tricky to get them
tuned + passing correctly. Since probe results were only logged
on a status change, and (to mirror K8s) probes start off in the
failing state, there was no way to get any feedback on a
misconfigured probe.
To balance, now _every_ non-success result is logged (assuming it
has output). Successful results are _only_ logged if they're the
result of a status change; otherwise, you would reasonably expect
a chunk of output in the log every ~10 secs that would make verbose
mode pretty much unusable.
This also exposes probe errors, which were previously invisible
within Tilt.
=> engine: log more readiness probe results

internal/engine/configs/tiltfile_log_writer.go, web/src/AlertPane.test.tsx, web/src/ClearLogs.test.tsx, web/src/ClearLogs.tsx, web/src/LogStore.test.ts, web/src/LogStore.ts, web/src/OverviewActionBar.tsx, web/src/OverviewLogPane.test.tsx, web/src/OverviewLogPane.tsx, web/src/OverviewResourcePane.test.tsx, web/src/OverviewResourcePane.tsx, web/src/alerts.test.ts, web/src/alerts.ts, web/src/logs.ts, web/src/testlogs.tsx
New button in the resource bar to clear logs. On the all view,
this will clear logs for all resources. On an individual resource,
it will just clear that resource's logs.
If a resource currently has error/warnings, the latest build or
runtime span respectively will be retained. This is to avoid having
a bunch of alerts that just show empty text on click.
Closes #1885.
=> web: clear logs functionality

web/src/ClearLogs.test.tsx, web/src/ClearLogs.tsx, web/src/OverviewActionBar.tsx, web/src/OverviewActionBarKeyboardShortcuts.test.tsx, web/src/OverviewActionBarKeyboardShortcuts.tsx, web/src/ShortcutsDialog.tsx
This is `Ctrl + Backspace` on Windows/Linux and `Cmd + Backspace`
on macOS.
This also adds a metric for clear logs with tags for how it's invoked
(button click vs shortcut) and whether all logs or a single resource.
I refactored a bit to cut down on passing the FULL resource everywhere,
which I'd been doing before instead of just the resource name.
(On non-macOS, it'll show `Ctrl + Backspace`)
N.B. It actually allows both `Ctrl` and `Meta` (Cmd/Win) on all OSes;
this matches pre-existing conventions and is probably the most
sane thing to do anyway as it's not hugely harmful and avoids
browser OS detection issues.
=> web: add keyboard shortcut for clear logs

web/src/OverviewItemView.tsx, web/src/SidebarIcon.tsx, web/src/SidebarItemView.tsx, web/src/SidebarPinButton.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Long resource names no longer break the layout!
| Before | After |
|---|---|
| <img width="323" alt="Screen Shot 2021-02-04 at 5 52 12 PM" src="https://user-images.githubusercontent.com/20349/107713522-6974f200-6c99-11eb-8d4b-8a5090ff4173.png"> | <img width="319" alt="Screen Shot 2021-02-11 at 6 43 50 PM" src="https://user-images.githubusercontent.com/20349/107713575-8c070b00-6c99-11eb-9805-293a52dab69a.png"> |
&nbsp;
Also, the pin position looks more intentional:
| Before | After |
|---|---|
|<img width="357" alt="Screen Shot 2021-02-11 at 6 47 48 PM" src="https://user-images.githubusercontent.com/20349/107713656-bce74000-6c99-11eb-98b5-502cd46a3870.png"> | <img width="332" alt="Screen Shot 2021-02-11 at 6 48 06 PM" src="https://user-images.githubusercontent.com/20349/107713663-c07ac700-6 …
=> web: Fix Sidebar item layout bugs

web/.storybook/preview.js, web/src/AccountMenu.stories.tsx, web/src/AnalyticsNudge.stories.tsx, web/src/Button.stories.tsx, web/src/FatalErrorModal.stories.tsx, web/src/HUDLayout.stories.tsx, web/src/HeroScreen.stories.tsx, web/src/LogPane.stories.tsx, web/src/LogPaneLine.stories.tsx, web/src/MetricsDialog.stories.tsx, web/src/MetricsPane.stories.tsx, web/src/OverviewActionBar.stories.tsx, web/src/OverviewGrid.stories.tsx, web/src/OverviewItemView.stories.tsx, web/src/OverviewLogPane.stories.tsx, web/src/OverviewPane.stories.tsx, web/src/OverviewResourceBar.stories.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewTabBar.stories.tsx, web/src/SecondaryNav.stories.tsx, web/src/ShareSnapshotModal.stories.tsx, web/src/ShortcutsDialog.stories.tsx, web/src/Sidebar.stories.tsx, web/src/SidebarAccount.stories.tsx, web/src/SidebarItemView.stories.tsx, web/src/SocketBar.stories.tsx, web/src/Tooltip.stories.tsx, web/src/UpdateDialog.stories.tsx
I wanted to make it easier to browse Storybook!
| Before | After |
|---|---|
|<img width="229" alt="Screen Shot 2021-02-11 at 7 28 50 PM" src="https://user-images.githubusercontent.com/20349/107716553-a80dab00-6c9f-11eb-8f6d-74583912a352.png">|<img width="210" alt="Screen Shot 2021-02-11 at 7 41 36 PM" src="https://user-images.githubusercontent.com/20349/107717267-32a2da00-6ca1-11eb-95a3-1d2a5fa04203.png">|
=> web: organize storybook sidebar

pkg/assets/prod.go
Please review the following commits I made in branch nicks/ch11295:
55af715154455766468951ea14bcd31fd171a621 (2021-02-12 12:34:27 -0500)
assets: add the correct caching headers to the prod asset server. Fixes https://github.com/tilt-dev/tilt/issues/4151
=> assets: add the correct caching headers to the prod asset server. Fixes https://github.com/tilt-dev/tilt/issues/4151

pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go
Please review the following commits I made in branch nicks/ch11384:
0bdb3cee474bbe2b9b3dd9f2ccb977fe6bd12684 (2021-02-15 19:14:30 -0500)
logstore: truncate chatty resources before non-chatty resources
This is a simple algorithm to give priority to truncating resources
with lots of logs.
Fixes https://github.com/tilt-dev/tilt/issues/3909
=> logstore: truncate chatty resources before non-chatty resources

web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/types.ts
fyi han, the very last commit of this bunch is a shot at renaming
because lines were getting long and names were feeling clunky,
but if you object (do you have a more specific understanding of
"toggle" than I do?) lmk and i can put it back
=> ui/sidebar: change filter naming and behavior to make it clear that tests are a type of resource [ch11349]

internal/containerupdate/exec_updater.go, internal/containerupdate/exec_updater_test.go, internal/engine/build_and_deployer.go, internal/k8s/fake_client.go, web/src/LogPaneLine.scss, web/src/OverviewLogPane.stories.tsx
Please review the following commits I made in branch nicks/ch11396:
63fa3751e92f147ee790ed4b289951ff45823a66 (2021-02-16 18:20:57 -0500)
containerupdate: improved error messaging when the file system isn't writable
Fixes https://github.com/tilt-dev/tilt/issues/4206
=> containerupdate: improved error messaging when the file system isn't writable

internal/tiltfile/os/os.go, internal/tiltfile/os/os_test.go
this would have been useful for the [Tests In Tilt code snippets](https://docs.tilt.dev/tests_in_tilt.html#go-tests-by-package) i was writing for docs, so I implemented it
=> tiltfile: add os.path.relpath

internal/cli/alpha.go, internal/cli/kubeconfig_path.go, internal/cli/tiltfile_result.go
Hello @maiamcc, @milas,
Please review the following commits I made in branch nicks/ch11415:
51fba76dff22887331fe382ddf2e3beddcfb08c8 (2021-02-18 11:57:17 -0500)
cli: add a helper for querying the tilt server
=> cli: add a helper for querying the tilt server

scripts/release.Dockerfile
Hello @nicks,
Please review the following commits I made in branch nicks/go14:
c68c0df2a404e37c42b77bb43a35971270e69508 (2021-02-19 18:37:01 -0500)
scripts: update release image to go 1.14
=> scripts: update release image to go 1.14

internal/containerupdate/exec_updater_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/test-error:
fa5ef94be3666552b899eed1c5a4ad9fa7a08da4 (2021-02-22 12:14:18 -0500)
test: add extra newline to error message
This is a workaround for https://github.com/golang/go/issues/38063,
where Go incorrectly reports test results if the test output doesn't
end in newlines
=> test: add extra newline to error message

pkg/apis/core/v1alpha1/filewatch_types.go, scripts/api-new-type.sh
Hello @ellenkorbes, @milas,
Please review the following commits I made in branch nicks/kinds:
26441f88f85c68d654233097244f4a9986557a55 (2021-02-24 14:00:11 -0500)
scripts: fix api-new-type to compute resource names properly
=> scripts: fix api-new-type to compute resource names properly

internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/allow-context:
00b9fc22a1a9e45dc02bff412ce0c9523f7e58e2 (2021-02-24 12:47:10 -0500)
tiltfile: check if the k8s context is allowed even when there are no k8s workloads, only uncategorized (fixes #4234) [ch11467]
=> tiltfile: check if the k8s context is allowed even when there are no k8s workloads, only uncategorized (fixes #4234) [ch11467]

internal/watch/paths.go, internal/watch/watcher_naive.go
Unused code linter isn't particularly smart about platform build
tags, so since this func is only used by the "naive" (non-macOS)
file watcher, it needs to live with that or it gets flagged as
dead code when linting on macOS.
=> test: fix lint errors on Darwin (macOS)

web/src/OverviewLogPane.tsx
Please review the following commits I made in branch nicks/ch11471:
79e53db48dc2523d66acc566460c236a79279d77 (2021-02-24 20:22:54 -0500)
web: import css for line colors
unfortunately, it's not really possible to test this because
jest doesn't emulate CSS :\
fixes https://github.com/tilt-dev/tilt/issues/4240
=> web: import css for line colors

internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/local/probe.go, internal/engine/local/probe_test.go, internal/tiltfile/local_resource.go, internal/tiltfile/probe/probe.go, internal/tiltfile/tiltfile_test.go, pkg/model/local_target.go
Hello @milas,
Please review the following commits I made in branch nicks/probe2:
d4eaba75fea3e9b985f0ef533369803b17265870 (2021-02-26 13:25:31 -0500)
engine: switch from Kubernetes Probe API to our fork
e34d60fcd444c8e817daeb02366f574dfb782c11 (2021-02-26 13:19:19 -0500)
apis: fork probe data model
=> engine: switch from Kubernetes Probe API to our fork

internal/cli/wire_gen.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/types.go, internal/controllers/core/cmd/wire.go, internal/controllers/wire.go
Hello @milas,
Please review the following commits I made in branch nicks/cmdscaffold:
e8ef063338ccd1d0e4fa9d6857c6a14d6e1e8cb4 (2021-03-01 11:22:57 -0500)
controllers: add a cmd controller
=> controllers: add a cmd controller

internal/controllers/core/cmd/actions.go, internal/controllers/core/cmd/controller_old.go, internal/controllers/core/cmd/controller_test.go, internal/controllers/core/cmd/execer.go, internal/controllers/core/cmd/execer_test.go, internal/controllers/core/cmd/probe.go, internal/controllers/core/cmd/probe_fake.go, internal/controllers/core/cmd/probe_test.go
Please review the following commits I made in branch nicks/fork:
7204195c212556688904b76bd732687bbc939e0a (2021-03-01 13:44:58 -0500)
controllers: fork engine/local into controllers/cmd
d6f80138a1721d9584140e37a1b936eb508b825c (2021-03-01 11:27:38 -0500)
controllers: add a cmd controller
=> controllers: fork engine/local into controllers/cmd

go.mod, go.sum, internal/engine/upper_test.go, internal/hud/server/apiserver.go, internal/hud/server/apiserver_test.go, vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/apiserver/apiserver.go, vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/apiserver/conn.go, vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/start/start.go, vendor/modules.txt
Hello @milas,
Please review the following commits I made in branch nicks/memconn:
f384e12d1a2de7f0646c93842141bdbc018dba1d (2021-03-03 11:23:19 -0500)
server: use unbuffered memory connections for testing, which seem to be more robust
=> server: use unbuffered memory connections for testing, which seem to be more robust

internal/engine/local/actions.go, internal/engine/local/controller.go, internal/engine/local/controller_test.go, internal/engine/local/execer.go, internal/engine/local/reducers.go, internal/engine/local/types.go, internal/engine/upper.go, internal/store/engine_state.go, internal/store/logger.go, internal/store/runtime_state.go, internal/store/types.go, pkg/apis/core/v1alpha1/register.go, web/storybook.tiltfile
Hello @milas, @ellenkorbes,
Please review the following commits I made in branch nicks/action-time:
8f6df154b2785d368e945a1b97aedcc22c3bcab1 (2021-03-03 18:34:08 -0500)
engine: Write Cmd objects to the EngineState
This is alternative proposal for how to move to the new API,
where we write the objects to the engine state first,
then convert to a controller second.
This also contains some standardization w/r/t how we do logging
in this new system.
7c142e686ed75cbddfe345c422e15b703bdbee18 (2021-03-03 17:02:23 -0500)
apis: add reason to CmdStatus, remove manifest
* Code is suitably instrumented with logging …
=> engine: Write Cmd objects to the EngineState

internal/engine/fswatch/fake_watcher.go, internal/engine/fswatch/watchmanager.go, internal/engine/fswatch/watchmanager_test.go
This will make the tests easier to migrate to an apiserver world,
but the real motivation is for splitting the actions between the
create and reconcile, which results in more complex store interactions
across multiple subscribers that isn't practical to test using the
testing store.
This uses the "real" store with a minimal reducer that just handles
FileWatch actions.
New assertions have also been added that verify the FileWatch spec
is created as expected and also serve to force synchronization on
the naturally async store, so that the tests are still as deterministic
as possible.
=> filewatch: refactor tests to rely on state vs actions

internal/engine/fswatch/action.go, internal/engine/fswatch/manifest_subscriber.go, internal/engine/fswatch/watchmanager.go, internal/engine/upper_test.go, internal/store/summary.go
This is largely just a cleanup that moves some stuff around and
further simplifies to make it look more like the Cmd controller(s).
=> filewatch: use change summary to simplify logic + be consistent

integration/crd/crd.yaml, integration/crd/um.yaml, integration/crd_test.go, internal/k8s/image.go, internal/k8s/jsonpath/value.go, internal/k8s/locator.go, internal/k8s/locator_test.go, internal/k8s/testyaml/testyaml.go
Fixes #4291
For standard k8s objects, Tilt will inject an image pull policy. For CRDs, it will not.
It's relatively common for CRDs to use the normal k8s container spec, with "image" and "imagePullPolicy" fields. Tilt provides a way for users to configure how to inject the image ref, but leave users to their own devices when it comes to imagePullPolicy.
If a CRD "image" field has an "imagePullPolicy" neighbor, inject the pull policy.
Note: the image object locator (where you specify, e.g., a repo and ref field) just ignores the pull policy. An obvious answer here is to add an option to specify the pull policy field. My weak gut instinct is it's not worth the effort to worry about that until someone complains. I'm happy to do that as well if someone has a different gut instinct.
=> k8s: inject pull policies into crds

integration/local_resource/Tiltfile, integration/local_resource/hello.sh, integration/local_resource_test.go
Add a single file dep and change it, ensuring that the service is
restarted appropriately.
[ch11614]
=> tests: verify file watches/restart for local_resource integration test

internal/controllers/core/cmd/controller.go, internal/engine/fswatch/watchmanager.go, internal/engine/upper_test.go, pkg/apis/core/v1alpha1/cmd_types.go, pkg/apis/core/v1alpha1/filewatch_types.go, pkg/openapi/zz_generated.openapi.go
Hello @milas,
Please review the following commits I made in branch nicks/microtime:
96be94cbef484cdac528fcccdd9bb8bc77fcd663 (2021-03-12 15:19:22 -0500)
apis: use MicroTime instead of Time
Currently, metav1.Time is only stored with second-level granularity,
which is probably not sufficient for this API.
=> apis: use MicroTime instead of Time

internal/store/engine_state.go
~~Add a custom encoder for `types.NamespacedName`.~~
Hide new apiserver types from the engine dump output. These types
should only be used by querying the apiserver rather than relying
on this debugging command.
(The actual error is due to JSON serialization of
`types.NamespacedName`; an earlier version of this change made
that serialize correctly but has been reverted since we don't
want to serialize it at all.)
Closes #4316.
=> cli: fix json errors on engine dump

Makefile, internal/tiltfile/helm_test.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/helm:
0a7a46bde6e0d569ef292e2ce274e3d1bce39e0b (2021-03-15 20:15:40 -0400)
test: move helm tests into their own file, and skip them on short tests
On windows, running Helm can take ~0.5 seconds,
which starts to blow up test times. Hoping this
will make the tests less flakey
=> test: move helm tests into their own file, and skip them on short tests

integration/analytics_test.go, integration/configmap_test.go, integration/crash_test.go, integration/crd_test.go, integration/dcbuild_test.go, integration/event_test.go, integration/fixture_test.go, integration/idempotent_test.go, integration/imagetags_test.go, integration/job_test.go, integration/live_update_after_crash_rebuild_test.go, integration/live_update_base_image_test.go, integration/live_update_two_images_one_manifest_test.go, integration/local_resource_test.go, integration/onedc_test.go, integration/oneup_custom_test.go, integration/onewatch_exec_test.go, integration/onewatch_test.go, integration/restart_process_different_user_test.go, integration/same_img_multi_container_test.go, integration/shortlived_pods_test.go, integration/tilt.go, integration/tilt_args_test.go, internal/cli/up.go
a8331c3108c76e8f24eb6c0e0635aebadcb42965 (2021-03-15 18:59:13 -0400)
cli: Remove --watch=false flag, and update integration tests to not depend on it
=> cli: Remove --watch=false flag, and update integration tests to not depend on it

internal/engine/fswatch/action.go, internal/engine/fswatch/manifest_subscriber.go, internal/engine/fswatch/watchmanager_test.go, internal/engine/local/reducers.go, internal/engine/local/servercontroller.go, internal/engine/upper_test.go, internal/store/logger.go, pkg/apis/core/v1alpha1/register.go, pkg/apis/identifiers.go, pkg/apis/identifiers_test.go
1) Use an annotation instead of label for manifest (labels have
strict requirements, e.g. 63 char max + only alphanumeric and
`-_.` allowed.
2) Sanitize resource names that are for entities which cannot be
made compliant, e.g. image refs
=> server: use apiserver safe values where appropriate

integration/access.yaml
Add `kube-public` read-only access for the `tilt-integration` user
so that it can find the `ConfigMap` for registry information.
I was debugging some integration tests today and realized the images
weren't ending up in my local registry, and I wanted to examine them.
This gives full read-only access to `kube-public` which I think is fine,
but we could probably scope this down to `ConfigMap` and even more
specifically the `local-registry-hosting` resource name.
Hopefully this also makes some of the integration tests slightly faster?
=> tests: use local registry for integration tests
