internal/k8s/client.go

Please review the following commits I made in branch nicks/kubeconfig:
d31893079a3608127fad198d2ab33a23076ee796 (2019-12-02 11:32:16 -0500)
k8s: improve error message a little

k8s: improve error message a little

---

internal/build/custom_builder.go

Please review the following commits I made in branch nicks/custombuild:
209d772162c0c62415210684e7b56e8056f843e1 (2019-11-26 15:58:24 -0500)
build: add better error message about custom_build

build: add better error message about custom_build

---

internal/k8s/env.go
internal/k8s/env_test.go

Please review the following commits I made in branch nicks/kind6-detection:
b3f80231b9cb9a5238376e45a21b072ae92d2e37 (2019-12-02 16:28:29 -0500)
k8s: add kind detection for kind 0.6.0

k8s: add kind detection for kind 0.6.0

---

internal/cli/wire_gen.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/k8s/env.go
internal/k8s/env_test.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/kind6-push:
c5aa42caac97b150b0599b4e7b0cbba1a24fba75 (2019-12-02 17:45:14 -0500)
engine: fix kind load on kind 0.6

engine: fix kind load on kind 0.6

---

internal/engine/build_and_deployer_test.go
internal/engine/buildcontroller_test.go
internal/engine/image_build_and_deployer_test.go
internal/engine/testdata_test.go

remove fast build manifest creation helpers, and remove or update
all engine tests that use them

engine: rm fastbuild from engine tests

---

internal/cli/up.go
internal/cli/up_test.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/upper_test.go
internal/hud/disabled_hud.go
internal/hud/fake_hud.go
internal/hud/hud.go

this fixes a small amt of the perf problems in #2597, tho not the bulk of them.
unsure if it's worth the complexity, figured I'd toss up a PR. thoughts?

hud: if hud not running, don't generate the whole view

---

internal/tiltfile/config/args_def.go
internal/tiltfile/config/flags.go
internal/tiltfile/config/flags_test.go
internal/tiltfile/config/resources.go
internal/tiltfile/config/string_list.go
internal/tiltfile/tiltfile_state.go

addressing (hopefully) Maia's post-merge comments on #2578

tiltfile: address comments from #2578

---

internal/hud/renderer_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/newview:
55a8022db4bb1ce0ebe01004bd4861f23fb51db7 (2019-12-03 17:33:08 -0500)
testing: add a helper function for creating views

testing: add a helper function for creating views

---

internal/build/custom_builder.go
internal/build/custom_builder_test.go
internal/engine/image_and_cache_builder.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go

build: execute custom build cmd in Tiltfile directory

---

pkg/model/logstore/logstore.go
pkg/model/logstore/logstore_test.go

Please review the following commits I made in branch nicks/checkpoint2:
f81f73128fd38265485f869ebe7a888aba4972ac (2019-12-04 12:42:46 -0500)
logstore: make sure checkpoints work correctly after logs are truncated

logstore: make sure checkpoints work correctly after logs are truncated

---

internal/engine/configs/actions.go
internal/engine/configs/tiltfile_log_writer.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/tabview.go
internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/store/engine_state.go
pkg/model/logstore/logstore.go
pkg/model/logstore/logstore_test.go
pkg/model/logstore/prefix.go
pkg/model/logstore/reader.go
pkg/model/manifest.go

Please review the following commits I made in branch nicks/deletecombinedlog:
ae21a2557602913a3a50a892e0efa5c8454f1f18 (2019-12-05 18:09:31 -0500)
store: delete the per-manifest log stores

store: delete the per-manifest log stores

---

internal/tiltfile/helm.go

`command` doesn't work on Windows.
Fixes #2633

tiltfile: use  `where` to search for Helm exe on windows

---

internal/cloud/snapshot_uploader.go
internal/hud/webview/convert.go
internal/hud/webview/view.go
internal/hud/webview/view_test.go

816d2d5b4c795209e4d895d44235e9e07300a094 (2019-12-06 14:46:23 -0500)
webview: remove dead code

webview: remove dead code

---

internal/engine/pod.go
internal/engine/upper.go
internal/store/actions.go
pkg/model/logstore/logstore.go
pkg/model/logstore/testing.go
web/src/LogStore.ts

Please review the following commits I made in branch nicks/spans:
1c944efa1878319e7546e40794990b9cda804ed4 (2019-12-09 18:32:20 -0500)
logstore: prep for multiple spans per manifest

logstore: prep for multiple spans per manifest

---

web/src/HUD.tsx
web/src/LogPane.test.tsx
web/src/LogPane.tsx
web/src/LogStore.test.ts
web/src/LogStore.ts
web/src/logs.ts
web/src/types.ts

Please review the following commits I made in branch nicks/ch4097/datamodel:
1b060025abb0e5439fdabd6352b04788ba27d182 (2019-12-10 13:40:57 -0500)
web: use structured logs to build a data model

web: use structured logs to build a data model

---

internal/hud/webview/convert.go
internal/hud/webview/view.go

Please review the following commits I made in branch nicks/resourceinfo:
1a7833ff73892db7504b8319e9a58f240e8bee96 (2019-12-10 21:20:12 -0500)
webview: remove more dead code

webview: remove more dead code

---

web/src/AlertPane.test.tsx
web/src/AlertPane.tsx
web/src/AppController.ts
web/src/alerts.test.ts
web/src/testdata.tsx
web/src/types.ts

Please review the following commits I made in branch nicks/alerts2:
4da1acf074f9b71173c0e954d2d7197eab9e56d2 (2019-12-11 17:20:19 -0500)
web: don't store alerts on the view

web: don't store alerts on the view

---

Gopkg.lock
Gopkg.toml
internal/tiltfile/starlarkstruct/struct.go
internal/tiltfile/starlarkstruct/struct_test.go
internal/tiltfile/tiltfile_state.go
vendor/go.starlark.net/starlarkstruct/module.go
vendor/go.starlark.net/starlarkstruct/struct.go

see behavior [here](https://github.com/google/starlark-go/blob/master/starlarkstruct/testdata/struct.star)

tiltfile: add struct

---

web/src/LogPane.test.tsx
web/src/LogPane.tsx
web/src/__snapshots__/LogPane.test.tsx.snap

Please review the following commits I made in branch nicks/highlightref:
4ee464f4ef4346c95b7486dc1ac2289f5e20dea4 (2019-12-12 17:25:28 -0500)
web: fix bugs in log highlight scrolling

web: fix bugs in log highlight scrolling

---

web/src/LogPane.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/pure:
c8dd35d0fa317b088c84ce652d63a207b8b2d9e8 (2019-12-12 17:36:29 -0500)
web: make LogLineComponent pure for better caching/performance

web: make LogLineComponent pure for better caching/performance

---

web/src/LogPane.scss
web/src/LogPane.tsx
web/src/__snapshots__/LogPane.test.tsx.snap

Hello @hyu,
Please review the following commits I made in branch nicks/ch4004/html:
2ecb385e565bfa4da917451c6fc519b30b876648 (2019-12-12 20:37:04 -0500)
web: html-based manifest names

web: html-based manifest names

---

internal/cli/args.go
internal/cli/up.go

had changes that I failed to commit before merging

args: address comments to #2671

---

Makefile
internal/cli/up.go
internal/cli/wire_gen.go
internal/engine/actions.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/buildcontrol/actions.go
internal/engine/buildcontrol/build_errors.go
internal/engine/buildcontrol/update_mode.go
internal/engine/buildcontroller.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/extractors.go
internal/engine/image_and_cache_builder.go
internal/engine/image_build_and_deployer.go
internal/engine/live_update_build_and_deployer.go
internal/engine/live_update_build_and_deployer_test.go
internal/engine/local_target_build_and_deployer.go
internal/engine/local_target_build_and_deployer_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/wire.go
internal/engine/wire_gen.go

Hello @nicks,
Please review the following commits I made in branch nicks/buildcontrol2:
a3f8e199183cea3b7e15fa2dc0829c72e8b343ba (2019-12-13 17:43:04 -0500)
engine: move some code into the buildcontrol package

engine: move some code into the buildcontrol package

---

web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/LogStore.ts

Please review the following commits I made in branch nicks/loglines:
64d68f282b28a728897181a13ee56341ce625dd3 (2019-12-18 10:10:49 -0500)
web: serialize snapshot correctly in the presence of incremental log loading

web: serialize snapshot correctly in the presence of incremental log loading

---

internal/hud/hud_test.go
pkg/model/logstore/reader.go

Hello @nicks,
Please review the following commits I made in branch nicks/segfault:
f69eea0e715ce0f4b4242bfb2bd540d7d40491e2 (2019-12-19 12:21:12 -0500)
logstore: add some protection against segfaults

logstore: add some protection against segfaults

---

Gopkg.lock
Gopkg.toml
internal/cli/klog.go
vendor/k8s.io/klog/.travis.yml
vendor/k8s.io/klog/CONTRIBUTING.md
vendor/k8s.io/klog/OWNERS
vendor/k8s.io/klog/README.md
vendor/k8s.io/klog/SECURITY_CONTACTS
vendor/k8s.io/klog/code-of-conduct.md
vendor/k8s.io/klog/go.mod
vendor/k8s.io/klog/go.sum
vendor/k8s.io/klog/klog.go
vendor/k8s.io/klog/klog_file.go

c9d082291bb59a669f95e31dcc1323c323d150ef (2019-12-19 15:59:04 -0500)
vendor: update klog to v1.0.0

vendor: update klog to v1.0.0

---

web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/security:
39a22ca6b40569dadc94d92e4884c23b849d6ab2 (2020-01-02 19:56:33 -0500)
web: upgrade javascript deps

web: upgrade javascript deps

---

internal/engine/upper_test.go

this solution swiped from https://go101.org/article/channel-closing.html

engine/tests: fix race condition in fakeBuildAndDeployer concurrency

---

internal/engine/upper_test.go

just got hit with a "concurrent map writes" complaint in my other branch
for b.ResultsByID so here's this.

engine/tests: a few more fixes to fakeBuildAndDeployer for concurrency safety

---

internal/dockercompose/state.go
internal/engine/buildcontrol/build_control.go
internal/engine/pod.go
internal/engine/upper_test.go
internal/store/runtime_state.go

Please review the following commits I made in branch nicks/completed:
5f1c8518198f005448de13040bc8a5d94a3d5c77 (2020-01-03 14:00:08 -0500)
engine: correctly handle Job deps. Fixes https://github.com/windmilleng/tilt/issues/2708

engine: correctly handle Job deps. Fixes https://github.com/windmilleng/tilt/issues/2708

---

web/src/LogPane.scss
web/src/LogPane.tsx
web/src/LogStore.ts
web/src/__snapshots__/LogPane.test.tsx.snap
web/src/logs.ts
web/src/types.ts

Hello @hyu,
Please review the following commits I made in branch nicks/warningglow:
65d705ad8efd415e475ffee79424f0728db27856 (2019-12-20 18:45:52 -0500)
web: visual treatment for warnings

web: visual treatment for warnings

---

internal/engine/local/controller_test.go
internal/store/testing_store.go

This was a conflict between #2740 and #2735

engine: fix local controller test

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/local/actions.go
internal/engine/local/controller.go
internal/engine/local/controller_test.go
internal/engine/local/execer.go
internal/engine/local/execer_test.go
internal/engine/local_target_build_and_deployer.go
internal/engine/subscribers.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/hud/webview/view.go
internal/store/actions.go
internal/store/engine_state.go
internal/store/runtime_state.go
internal/testutils/manifestbuilder/manifestbuilder.go
pkg/model/local_target.go
pkg/model/runtime_status.go

This is working well enough that we can run stuff. I've added some TODOs for bugs I noticed. It seems worth getting this in and then we can work on those in parallel.

engine: hook local resource serve controller up to upper

---

internal/build/container_test.go
internal/build/image_builder.go
internal/build/options.go
internal/engine/image_and_cache_builder.go

Please review the following commits I made in branch nicks/imagebuild:
c2365088240bd3f8808452c1cd5b6ca4fa3c71af (2020-01-08 23:41:31 -0500)
build: simplify ImageBuild API

build: simplify ImageBuild API

---

internal/build/options.go
internal/docker/client.go
internal/docker/options.go
internal/docker/readcloser.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go

Please review the following commits I made in branch nicks/issue2437/ssh:
18711179a6d3679900d5c13ead6ecb76e32d8b3c (2020-01-09 13:30:58 -0500)
docker: support docker build --ssh. Fixes issue #2437

docker: support docker build --ssh. Fixes issue #2437

---

web/src/FatalErrorModal.scss
web/src/FatalErrorModal.stories.tsx
web/src/FatalErrorModal.tsx
web/yarn.lock

Fixes #2760
Screenshot:
Video:
https://drive.google.com/file/d/1PzCvWW6KIQ5zZQB8kV42R4A4SnsLxxjs/view?usp=sharing

web: modal should fit on screen when it's overflowing

---

.circleci/Dockerfile.integration
.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/kind7:
de6b41813f19d6034c55dbacb7636f55f40bf0e1 (2020-01-14 14:01:22 -0500)
circleci: upgrade to kind 0.7.0

circleci: upgrade to kind 0.7.0

---

web/src/LogStore.test.ts
web/src/LogStore.ts

Please review the following commits I made in branch nicks/logcache:
2ee0653bdbbd1011c83e1c82c17c1172f2c468c4 (2020-01-14 14:56:22 -0500)
web: cache the LogLines to reduce GC thrashing

web: cache the LogLines to reduce GC thrashing

---

web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/yarn:
7cd5ffb792bca933ecfa255fd9370755e082aec3 (2020-01-14 19:14:22 -0500)
web: update yarn.lock

web: update yarn.lock

---

internal/engine/local/execer.go

local serve: log process exits as errors

---

internal/cli/wire_gen.go
internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go
internal/engine/upper_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/env:
6ce236909120de6a65019d33084c7cf0530d7cd5 (2020-01-15 12:27:56 -0500)
analytics: add env tags

analytics: add env tags

---

pkg/model/logstore/logstore.go
pkg/model/logstore/logstore_test.go

Please review the following commits I made in branch nicks/maxlogs:
18a6bb93176a367ef80ccd2bfe67596a84d01f84 (2020-01-15 14:50:43 -0500)
model: raise the cap on logs, now that the CPU issues are resolved

model: raise the cap on logs, now that the CPU issues are resolved

---

internal/build/image_builder.go

Please review the following commits I made in branch nicks/push2:
183432229041f42e85e6d7039d33a2fe2aeb2350 (2020-01-16 18:25:05 -0500)
build: Add a minimum viable docker-push-progress. Fixes https://github.com/windmilleng/tilt/issues/1983

build: Add a minimum viable docker-push-progress. Fixes https://github.com/windmilleng/tilt/issues/1983

---

.goreleaser.yml

just gonna merge this since it blocks a release and should be uncontroversial

goreleaser: use -mod=vendor

---

internal/tiltfile/files.go
internal/tiltfile/tiltfile_test.go

tiltfile: add quiet parameter to local

---

internal/build/image_builder.go
internal/hud/renderer_test.go
pkg/logger/fields.go
pkg/logger/logger.go
pkg/model/logstore/logstore.go
pkg/model/logstore/testing.go
web/src/LogStore.test.ts
web/src/LogStore.ts

Please review the following commits I made in branch nicks/ch4296/progress:
53f012e4b9b917242b971cf34ef2c045f43e9426 (2020-01-22 16:03:31 -0500)
web: Implement progress logs

web: Implement progress logs

---

internal/cloud/update_uploader.go
internal/cloud/update_uploader_test.go

Please review the following commits I made in branch nicks/ch4321/updates:
91d3e1ef6af5907737e2fb66d3b6869fba4c97b9 (2020-01-23 18:33:27 -0500)
cloud: Just because we have a token doesn't mean it's valid :embarrassed:

cloud: Just because we have a token doesn't mean it's valid :embarrassed:

---

integration/local_resource_test.go

working on fixing this but don't want to leave master broken in the meantime

integration: skip local resource test

---

integration/local_resource_test.go

integration: fix, reenable local resource test

---

web/src/LogPane.test.tsx
web/src/LogPane.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/scroll:
747c3966fe958ed993ef3eb0a09bcec3a642ca3d (2020-01-24 16:30:11 -0500)
web: fix scrolling in snapshots :grimace:

web: fix scrolling in snapshots :grimace:

---

.circleci/config.yml
Makefile
web/package.json
web/yarn.lock

Also update some dev dependencies while I'm here

ci: report Jest results in JUnit XML format

---

go.sum
internal/tiltfile/files.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

1. Adds decode_yaml file function
2. Rearranges JSON and YAML concerned function definitions to be contiguous/next to each other.
3. Replaces Doesnt with DoesNot in tiltfile_testfile.go

tilt: add decode_yaml file function.

---

internal/engine/image_build_and_deployer_test.go
internal/engine/live_update_state_tree.go
internal/engine/upper_test.go
internal/store/build_result.go
internal/store/build_result_test.go

nick, I know we talked about punting on this, but i already had it 3/4 done,
turned out to be really easy and will make the rest of my code cleaner.
doesn't feel super risky to me--but if it does to you, happy to wait. wdyt?

engine: remove image from LiveUpdateResult (cleanup)

---

internal/engine/image_build_and_deployer.go

Please review the following commits I made in branch maiamcc/rm-incremental-build-reference:
8b690d7176bc1b504f822a73bac56090078955b2 (2020-01-28 11:22:44 -0500)
engine: remove an incremental build reference

engine: remove an incremental build reference

---

internal/engine/image_build_and_deployer_test.go

came across [this funky test](https://windmill-eng.slack.com/archives/C9SA451CJ/p1580234525038900) during refactoring

engine-test: clarify engine test and make it more robust

---

internal/hud/server/server.go
internal/hud/server/websocket.go
internal/hud/server/websocket_test.go

Please review the following commits I made in branch nicks/websocket:
6ea236ca795302500af02c2362eb7d17387e37bf (2020-01-30 13:53:32 -0500)
hud: fix a panic in the websocket handler. context.TODO() doesn't have a logger on it :O

hud: fix a panic in the websocket handler. context.TODO() doesn't have a logger on it :O

---

web/src/HUD.tsx
web/src/LogPane.test.tsx
web/src/LogPane.tsx
web/src/index.tsx
web/src/selection.ts

Please review the following commits I made in branch nicks/ch4394/highlight:
f69f2c8b582a67dc77417103a943aca22f55003c (2020-01-30 15:16:14 -0500)
web: more robust highlighting on firefox. grumble grumble selection apis grumble grumble

web: more robust highlighting on firefox. grumble grumble selection apis grumble grumble

---

internal/engine/k8swatch/actions.go
internal/engine/pod.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/pod:
e6535c08ea75f0965d5bcf29c81a852f03eeef36 (2020-01-30 17:13:21 -0500)
engine: simplify pod registration a bit

engine: simplify pod registration a bit

---

web/src/LogPaneLine.stories.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/storybook:
407d9145d39559825e94f2ca530c7ffa0876a296 (2020-01-31 16:31:04 -0500)
web: add a storybook for the log UI

web: add a storybook for the log UI

---

go.mod
go.sum
internal/analytics/tilt_analytics.go
internal/analytics/tilt_analytics_test.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/modules.txt

Please review the following commits I made in branch nicks/wmclinet:
3cc80c034036ce0ad6fe41c845c8c0eb4b6106e5 (2020-02-05 13:32:48 -0500)
analytics: update wmclient and use WithoutGlobalTags() instead of IncrAnonymous()

analytics: update wmclient and use WithoutGlobalTags() instead of IncrAnonymous()

---

internal/tiltfile/starkit/environment.go
internal/tiltfile/starkit/environment_test.go

silly me copypastad and added two functions with the same name, and couldn't figure out why my function was returning the wrong type

starkit: error if same identifier added multiple times

---

internal/cli/action.go
internal/cli/api_utils.go
internal/cli/cli.go
internal/cli/dump.go
internal/cli/trigger.go

cli: can trigger update from cli

---

internal/cli/build.go
scripts/install.sh

Please review the following commits I made in branch maiamcc/bump-v0.12.0:
899346093892aa7b2736f7ed8aa5d8c2d323934e (2020-02-07 12:13:08 -0500)
bump to v0.12.0

bump to v0.12.0

---

go.mod
go.sum
internal/build/buildkit_printer.go
vendor/github.com/tonistiigi/units/.travis.yml
vendor/github.com/tonistiigi/units/LICENSE
vendor/github.com/tonistiigi/units/bytes.go
vendor/github.com/tonistiigi/units/readme.md
vendor/modules.txt

Hello @nicks,
81b9592bc8e28e098d4dd817bb509ce208cec0c8 (2020-02-10 11:10:17 -0500)
vendor: units library for printing buildkit progress

vendor: units library for printing buildkit progress

---

internal/build/buildkit_printer.go
internal/build/image_builder.go
internal/build/testdata/TestBuildkitPrinter/echo-hi-success-verbose.master.txt
internal/build/testdata/TestBuildkitPrinter/echo-hi-success.master.txt
internal/build/testdata/TestBuildkitPrinter/rust-success.master.txt
internal/build/testdata/TestBuildkitPrinter/sleep-cache.master.txt

Please review the following commits I made in branch nicks/ch4225/progress:
917a49960ceb92a051de276e9cc05e946c4ef49d (2020-02-10 10:57:43 -0500)
build: print docker pull status incrementally

build: print docker pull status incrementally

---

internal/build/custom_builder.go
internal/build/custom_builder_test.go
internal/container/reference.go
internal/container/reference_test.go

Please review the following commits I made in branch nicks/issue2928:
d2913fec33dd6af3e87b0ccd3305fd683132605a (2020-02-11 11:42:22 -0500)
build: make custom_build play more nicely with local registries. Fixes #2928

build: make custom_build play more nicely with local registries. Fixes #2928

---

internal/build/options.go
internal/docker/client.go
internal/docker/options.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go

Please review the following commits I made in branch nicks/issue2563/secret:
e822a1fdbe0920cb28edc8c298417261744f4d97 (2020-02-11 17:22:47 -0500)
tiltfile: docker_build(secret=). Fixes issue #2563
0f0ddba17e08ee184852cd275454ee1937127ee5 (2020-02-11 17:21:45 -0500)
vendor: buildkit secret provider

tiltfile: docker_build(secret=). Fixes issue #2563

---

web/src/HUDLayout.stories.tsx
web/src/HUDLayout.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch4440/grid2:
08a637668cc87be9eaa78b2fb4c078459be3a56a (2020-02-11 16:27:11 -0500)
web: fix a width bug in the new HUD layout grid

web: fix a width bug in the new HUD layout grid

---

internal/cli/wire_gen.go
internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go
internal/engine/upper_test.go
internal/engine/wire_gen.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/metrics:
fe347ef09a5ef44dea0d761aa9b1a0d8b834837b (2020-02-12 15:14:02 -0500)
analytics: add runtime and local registry to report

analytics: add runtime and local registry to report

---

web/src/LogPane.stories.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/logpane:
e44fb5b6615db8a460f5466046836006789cab94 (2020-02-18 15:31:21 -0500)
add a storybook for logpane

add a storybook for logpane

---

internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/analytics:
3c3ac11d4f331cc9f13937b6abbafbd57a6e180a (2020-02-17 01:18:40 -0500)
engine: fix a bug in analytics_settings() propagation

engine: fix a bug in analytics_settings() propagation

---

web/src/ResourceInfo.tsx
web/src/index.scss
web/src/style-helpers.ts

Hello @hyu,
Please review the following commits I made in branch nicks/ux:
0503bacca802170e144538d791f8fa468887832c (2020-02-18 18:44:18 -0500)
web: small ux tweaks. fix the cursor on chrome. make the top bar work better on small screens

web: small ux tweaks. fix the cursor on chrome. make the top bar work better on small screens

---

web/src/HUD.test.tsx
web/src/LogStore.ts

Please review the following commits I made in branch nicks/logpane2:
920648eeed556b932b5adcbda5ec314438ad6522 (2020-02-18 18:23:50 -0500)
web: serialize log fields to snapshot. Fixes https://github.com/windmilleng/tilt/issues/2967

web: serialize log fields to snapshot. Fixes https://github.com/windmilleng/tilt/issues/2967

---

internal/k8s/image.go
internal/k8s/image_test.go

fixes #2979 
TL;DR - FWICT, when we changed InjectImageDigest to have separate selectorRef and injectRef, we simply never applied that to the CRD path.

engine: fix image injection when using CRDs with default_registry

---

web/src/HUD.tsx
web/src/LogStore.test.ts
web/src/LogStore.ts
web/src/SecondaryNav.stories.tsx
web/src/SecondaryNav.test.tsx
web/src/SecondaryNav.tsx
web/src/analytics.test.ts
web/src/analytics.ts
web/src/types.ts

Please review the following commits I made in branch nicks/buildview:
9c11fa394b63cf6c658cc41102c3642952d206d6 (2020-02-20 16:32:53 -0500)
web: add trace view

web: add trace view

---

scripts/install.sh

scripts: don't sudo if $HOME/bin is in $PATH

---

web/src/Sidebar.tsx
web/src/SidebarTriggerButton.scss
web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/__snapshots__/Statusbar.test.tsx.snap
web/src/constants.scss
web/src/style-helpers.ts
web/src/testdata.tsx

|  | Screenshot |
| --- | --- |
| Before | ![Screenshot from 2020-02-24 12-12-14](https://user-images.githubusercontent.com/20349/75291352-05d78780-57f0-11ea-9d68-8e6e1443a74c.png) | 
| After | ![Screen Shot 2020-02-25 at 4 57 46 PM](https://user-images.githubusercontent.com/20349/75291373-10921c80-57f0-11ea-83ac-2ca45d8d15ab.png)
|

web: properly truncate long names in Sidebar

---

internal/engine/k8swatch/pod_watch.go
internal/engine/k8swatch/pod_watch_test.go

Please review the following commits I made in branch nicks/ch4899/update:
75cbac9610e01c610b205d1b2c03faa296ef99dd (2020-02-27 17:41:14 -0500)
k8swatch: fix a race condition in pod change events
Sometimes pod events would show up in the wrong order due to goroutine scheduling

k8swatch: fix a race condition in pod change events

---

internal/cli/trigger.go
internal/engine/upper.go
internal/hud/server/actions.go
internal/hud/server/server.go
internal/hud/server/server_test.go
internal/store/build_result.go
internal/store/engine_state.go
pkg/model/build_reason.go
pkg/model/build_reason_test.go
web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx

Please review the following commits I made in branch nicks/ch4965/reasons:
7deafb7d3913b1af33e4cb1db55bdf8982257ee6 (2020-03-02 18:14:00 -0500)
engine: print trigger reasons

engine: print trigger reasons

---

internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/extractors.go
internal/engine/live_update_build_and_deployer_test.go
internal/store/build_result.go
pkg/model/build_reason.go

Please review the following commits I made in branch nicks/forceupdate:
1bda6e4628227671d6289b5a87ed34e1fc494f60 (2020-03-03 16:47:11 -0500)
engine: replace ForcedUpdate with IsOverrideTrigger

engine: replace ForcedUpdate with IsOverrideTrigger

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/live_update_build_and_deployer.go
internal/engine/upper_test.go
internal/k8s/entity.go
internal/k8s/entity_test.go
internal/k8s/testyaml/testyaml.go
internal/store/build_result.go
internal/store/json_test.go

Please review the following commits I made in branch nicks/ch5085/inject:
3d58c41342ad79c9dff95b7103e68b2e6c62c283 (2020-03-05 21:22:30 -0500)
engine: if we fail to inject the synclet into a resource, try to recover gracefully
Fixes https://github.com/windmilleng/tilt/issues/2948

engine: if we fail to inject the synclet into a resource, try to recover gracefully

---

web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/exports:
34e0226bccdfd720fe0ed3a660d59825b6c573e9 (2020-03-12 11:36:31 -0400)
web: upgrade storybook to fix some babel issues

web: upgrade storybook to fix some babel issues

---

internal/cli/build.go
scripts/install.sh

Please review the following commits I made in branch maiamcc/v0.12.8:
bd0ed7eca8273ee4dce51a81b0a4c89a5ee402e2 (2020-03-12 16:11:41 -0400)
bump v0.12.8

bump v0.12.8

---

web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/acorn:
68780faf5804ef7f18a2b687cee3600d5d583358 (2020-03-13 17:54:03 -0400)
web: run yarn upgrade to silence security warnings

web: run yarn upgrade to silence security warnings

---

web/src/HUD.tsx
web/src/HUDLayout.stories.tsx
web/src/HUDLayout.tsx
web/src/ResourceInfo.tsx
web/src/SecondaryNav.stories.tsx
web/src/SecondaryNav.test.tsx
web/src/SecondaryNav.tsx
web/src/__snapshots__/SecondaryNav.test.tsx.snap
web/src/style-helpers.ts
web/src/trace.test.ts
web/src/trace.ts
web/src/types.ts

Hello @hyu,
Please review the following commits I made in branch nicks/traceviewtabs:
4832a19b843009bfed41a6c9343ec487f5b2f15f (2020-02-28 19:39:31 -0500)
web: add two-level secondary nav

web: add two-level secondary nav

---

CONTRIBUTING.md

Please review the following commits I made in branch nicks/wireguide:
5a4ba99b7730ac56ee039a6e99f61060fc628b48 (2020-03-13 18:53:03 -0400)
contributing: add a guide to debugging wire

contributing: add a guide to debugging wire

---

internal/tiltfile/files.go

Thanks to @khos2ow for spotting

tiltfile: fix typo in kustomize fallback message

---

internal/tiltfile/docker.go
internal/tiltfile/docker_test.go

tiltfile: custom build deps are repos for images

---

internal/tiltfile/os/os.go
internal/tiltfile/os/os_test.go

tiltfile: add os.realpath

---

internal/tiltfile/starkit/environment.go
internal/tiltfile/starkit/environment_test.go
internal/tiltfile/starkit/module.go

Please review the following commits I made in branch nicks/modules:
e80bc4035066f0d40fbe96e49e43d5b80112f92b (2020-03-18 16:50:57 -0400)
starkit: add support for nested modules

starkit: add support for nested modules

---

internal/k8s/client.go

k8s: Add 5 second timeout to kubectl apply

---

go.mod
go.sum
vendor/github.com/evanphx/json-patch/README.md
vendor/github.com/evanphx/json-patch/go.mod
vendor/github.com/evanphx/json-patch/go.sum
vendor/github.com/evanphx/json-patch/merge.go
vendor/github.com/evanphx/json-patch/patch.go
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/Makefile
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/go113.go
vendor/github.com/pkg/errors/stack.go
vendor/modules.txt

Please review the following commits I made in branch nicks/ch5621/resources:
fcaee53305c7b9227208364b23fc5d0d7cd27bee (2020-03-24 12:49:07 -0400)
vendor: upgrade json-patch to deal with perf degradation. Fixes issue #3096

vendor: upgrade json-patch to deal with perf degradation. Fixes issue #3096

---

internal/engine/upper_test.go

This test is occasionally failing in master, and when it fails, it just says it timed out waiting for "done". It's waiting for `LastBuild().Edits` to contain exactly the right string, and when you see the failure, the output makes it hard to distinguish:
1. the manifest state was never updated to reflect the build finishing
2. the build finished, but the expected file wasn't in `Edits`
3. the build finished, and the expected file was in `Edits`, but other files were also in `Edits`
Change the assertions so that the log is a bit clearer about what is happening.

engine tests: reorganize a flaky test

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/winders:
bdddb95aa67ce3499bea631d351d3232916474db (2020-03-26 12:22:05 -0400)
circleci: run builds on a windows VM

circleci: run builds on a windows VM

---

internal/dockerfile/dockerfile.go
internal/dockerfile/dockerfile_test.go

Hello @nicks,
f9f631c2de651ff70d3100938cb26cd16e36598b (2020-03-26 14:38:04 -0400)
dockerfile: remove some dead code

dockerfile: remove some dead code

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/dead:
ed1ad0a172f4915e6e56bf4466ee425694ded071 (2020-03-27 13:34:06 -0400)
engine: remove a dead parameter

engine: remove a dead parameter

---

internal/dockercompose/state.go
internal/hud/webview/convert.go
internal/store/runtime_state.go

Please review the following commits I made in branch nicks/runtimestatus:
f9e8f3e3f1232ceb6345cd29008899443c2654e3 (2020-03-31 17:11:36 -0400)
store: calculate RuntimeStatus in the RuntimeState data model

store: calculate RuntimeStatus in the RuntimeState data model

---

internal/testutils/assert.go
internal/testutils/tempdir/temp_dir_fixture.go
internal/tiltfile/encoding/json_test.go
internal/tiltfile/encoding/yaml_test.go
internal/tiltfile/git/git_test.go
internal/tiltfile/include/include_test.go
internal/tiltfile/io/io_test.go
internal/tiltfile/os/os_test.go
internal/tiltfile/starkit/fixture.go
internal/tiltfile/telemetry/telemetry_test.go

Please review the following commits I made in branch nicks/wintest4:
947fed04bd52328488d3113b15494e1b0f4713da (2020-03-30 23:07:06 -0400)
tiltfile: fix some tests on windows

tiltfile: fix some tests on windows

---

internal/dockercompose/state.go
internal/engine/exit/controller.go
internal/engine/exit/controller_test.go
internal/store/mode.go
internal/store/runtime_state.go

Please review the following commits I made in branch nicks/cimode:
2d289e550bb75176e7c83b519333a72b7df9977e (2020-03-31 19:09:07 -0400)
engine: introduce a CI mode to the engine

engine: introduce a CI mode to the engine

---

internal/cli/ci.go
internal/cli/cli.go
internal/cli/flags.go
internal/cli/up.go
internal/cli/up_test.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/analytics/analytics_updater.go
internal/engine/analytics/analytics_updater_test.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch5914/ci:
4b9e391747100f15ed52308ebe0627d19f2d018f (2020-04-01 11:38:30 -0400)
cli: Introduct `tilt ci` for waiting until pods are healthy

cli: Introduct `tilt ci` for waiting until pods are healthy

---

internal/engine/exit/controller.go
internal/engine/exit/controller_test.go
internal/k8s/target.go
pkg/model/k8s_target.go

Please review the following commits I made in branch nicks/job:
cafa1b9384f8bccabe2f472a8721afa4f326fbb7 (2020-04-01 15:23:10 -0400)
exit: tweak exit conditions for jobs in CI mode

exit: tweak exit conditions for jobs in CI mode

---

internal/cli/down.go
internal/cli/down_test.go

down: don't delete namespaces

---

web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/updates:
43c57c6fddcdd6b6547f08aa2923c94e161c9d30 (2020-04-06 12:14:53 -0400)
web: upgrade some deps

web: upgrade some deps

---

web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/reveret:
919fcaca12a46cbd72d5aaad4fc4d591ce025db3 (2020-04-06 15:28:26 -0400)
Revert "web: upgrade some deps (#3182)"
This reverts commit 5c107aa466a4bf65af1c6dc9beefb58a84f710ff.

Revert "web: upgrade some deps (#3182)"

---

CONTRIBUTING.md

As requested by @maiamcc  in https://github.com/windmilleng/company/pull/25#pullrequestreview-388643049.

Add summary section to release notes task

---

CONTRIBUTING.md

Remove token to sign out of Tilt

---

.circleci/config.yml
internal/tiltfile/helm_test.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/windows:
a843d8867c594b60ec292fece407dc98235904f6 (2020-04-24 17:36:08 -0400)
tiltfile: fix more windows tests

tiltfile: fix more windows tests

---

internal/build/boil_runs_test.go
internal/build/container_test.go
internal/build/custom_builder.go
internal/build/custom_builder_test.go

Please review the following commits I made in branch nicks/windows3:
0517ace7faeca7e404db021dbd3663ab1c2f99da (2020-04-24 20:08:59 -0400)
build: fix custom_builder unit tests on windows, which led to some bug fixes :raised-hands:

build: fix custom_builder unit tests on windows, which led to some bug fixes :raised-hands:

---

internal/engine/configs/configs_controller_test.go
internal/engine/local/controller_test.go
internal/engine/local/execer_test.go
internal/engine/telemetry/controller_test.go

Please review the following commits I made in branch nicks/windows6:
0446b11910c958df99fa349161b5283df17d46d2 (2020-04-24 22:23:58 -0400)
engine: fix a couple subscriber tests on windows

engine: fix a couple subscriber tests on windows

---

internal/build/buildkit_printer_test.go
internal/build/image_builder_test.go
internal/build/path_mapping.go
internal/build/path_mapping_test.go
internal/build/pipeline_state_test.go

Please review the following commits I made in branch nicks/windows4:
ebcbd16941bfb1b565e960e7460b0aed13d562e8 (2020-04-24 20:50:03 -0400)
build: fix path mapping on windows

build: fix path mapping on windows

---

README.md

Hello @dbentley, @ellenkorbes,
Please review the following commits I made in branch nicks/readme:
397727004e0d2926b09ee63680a64896748d703c (2020-04-27 12:35:46 -0400)
tweak the readme language a bit

tweak the readme language a bit

---

internal/engine/fswatch/watchmanager_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/windows10:
83a60e7eb410df514ca4c8ecfaa70b8bb660fd16 (2020-04-29 13:50:01 -0400)
fswatch: fix tests on windows

fswatch: fix tests on windows

---

internal/engine/fswatch/watchmanager.go
internal/engine/fswatch/watchmanager_test.go

Please review the following commits I made in branch nicks/cimode2:
b9e5ae4aca2dba0a7e03c28b973f45d11a5cdc9b (2020-04-29 14:13:39 -0400)
don't watch files in ci mode

don't watch files in ci mode

---

internal/engine/exit/controller_test.go
internal/engine/portforwardcontroller_test.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/store/runtime_state.go
internal/testutils/manifestutils/manifest.go

Please review the following commits I made in branch nicks/ch6706:
6ddf22d82037fc16f8379760fb6c5e8f44e74f68 (2020-04-30 12:14:02 -0400)
store: fix bugs in runtime state of uncategorized yaml. Fixes https://github.com/windmilleng/tilt/issues/3262

store: fix bugs in runtime state of uncategorized yaml. Fixes https://github.com/windmilleng/tilt/issues/3262

---

internal/engine/k8srollout/podmonitor_test.go
internal/engine/k8swatch/pod_watch_test.go
internal/engine/k8swatch/service_watch_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/windows11:
e616a320aa8f0a148c93de446232bd669a4cbbe8 (2020-05-01 20:21:01 -0400)
engine: fix some more tests on windows
1a9348bf1fd56a77cd8db10543373906fdb5b2cd (2020-05-01 20:17:40 -0400)
fix

engine: fix some more tests on windows

---

Makefile
internal/store/engine_state_test.go
internal/store/subscriber_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/windows12:
82546960e0980df9eb060dcf115e6d992808713d (2020-05-01 20:32:55 -0400)
store: fix more tests on windows

store: fix more tests on windows

---

internal/hud/webview/convert_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/windows13:
212ff630feb8593f442b5694e4c9ac729d521e54 (2020-05-04 22:24:15 -0400)
hud: turn on more tests on windows

hud: turn on more tests on windows

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/build_and_deployer_test.go
internal/engine/buildcontroller_test.go
internal/engine/docker_compose_build_and_deployer_test.go
internal/engine/image_build_and_deployer_test.go
internal/engine/live_update_build_and_deployer_test.go
internal/engine/local_target_build_and_deployer_test.go
internal/engine/pod_test.go
internal/engine/testdata_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/windows2:
b429f78352c86d67551d7177d0dc9cc6cabcc7db (2020-05-05 11:52:25 -0400)
engine: fix more tests on windows

engine: fix more tests on windows

---

web/src/SidebarAccount.tsx

Please review the following commits I made in branch maiamcc/tilt-cloud-sign-in-link:
81b153e3796cce1838e9cb5b6f9e3975ec082df3 (2020-04-30 17:44:57 -0400)
web: tilt cloud signin link should open in a new window, not take you away from the web ui

web: tilt cloud signin link should open in a new window, not take you away from the web ui

---

internal/engine/build_and_deployer_test.go
internal/engine/buildcontroller_test.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/disable:
f6ab20685d6cbe84adfa42dee68b6a169fa9eb0d (2020-05-05 20:17:33 -0400)
skip some flaky tests

skip some flaky tests

---

internal/engine/configs/configs_controller_test.go
internal/hud/server/server_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/flaky:
f2be3daaacdcf0fa05e353e4239a1fbe67f3b314 (2020-05-05 20:58:25 -0400)
windows: skip another flaky test

windows: skip another flaky test

---

internal/build/image_builder.go

Hello @nicks,
aff68cb44d1e029a2a741924f681f9d11e0bcc5f (2020-05-06 13:02:29 -0400)
build: delete some dead code

build: delete some dead code

---

internal/engine/buildcontroller_test.go
internal/engine/portforwardcontroller_test.go
internal/engine/upper_test.go
internal/k8s/watch_test.go

Hello @nicks,
b826a79ef48b56db1692e08b00aec4628c5b83eb (2020-05-06 13:00:26 -0400)
windows: silence another flake

windows: silence another flake

---

go.mod
go.sum
vendor/github.com/windmilleng/fsnotify/fen.go
vendor/github.com/windmilleng/fsnotify/inotify.go
vendor/github.com/windmilleng/fsnotify/kqueue.go
vendor/github.com/windmilleng/fsnotify/windows.go
vendor/modules.txt

Hello @nicks,
9640fb733692fce004c52159e3e8851bf245e465 (2020-05-07 18:01:34 -0400)
vendor: pull in fsnotify changes

vendor: pull in fsnotify changes

---

internal/store/testing_store.go
internal/testutils/tempdir/temp_dir_fixture.go
internal/watch/notify_test.go
internal/watch/paths.go
internal/watch/paths_test.go
internal/watch/watcher_darwin.go
internal/watch/watcher_naive.go
internal/watch/watcher_naive_test.go

Please review the following commits I made in branch nicks/recursive:
ea405a6b7f163720ea632c0a8dfdd6f8643d72ac (2020-05-07 20:40:40 -0400)
watch: use the recursive watcher on windows

watch: use the recursive watcher on windows

---

CONTRIBUTING.md
README.md

readme: use pkg.go.dev instead of godoc.org

---

internal/dockercompose/client.go
internal/engine/configs/configs_controller.go
internal/engine/dockerprune/docker_pruner.go
internal/engine/pod.go
internal/engine/upper_test.go
internal/k8s/ip.go

Hello @nicks,
Please review the following commits I made in branch nicks/errorf:
be169197f079379417e973a9177a06dc78da2876 (2020-05-08 20:46:59 -0400)
engine: fix some improper format strings

engine: fix some improper format strings

---

internal/tiltfile/k8s.go
internal/tiltfile/secretsettings/secret_settings.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/secret_settings.go

in re: [this request on #2417](https://github.com/windmilleng/tilt/issues/2417#issuecomment-625896289)

tiltfile: secret_settings builtin lets you turn off secret scrubbing

---

web/src/SidebarAccount.tsx

Hello @hyu, @vw, @nicks,
Please review the following commits I made in branch maiamcc/link-to-tc:
259316890e04682948c1c0dff41f62504ff04d54 (2020-05-08 16:21:30 -0400)
web: clearer copy on tilt cloud signin/link modal [ch6917]
addresses #3307

web: clearer copy on tilt cloud signin/link modal [ch6917]

---

internal/hud/resourceview.go
internal/hud/wire.go
internal/rty/interactive_tester.go

Please review the following commits I made in branch nicks/chars:
22b673d6265a2fa28f3b926bc6ed535629fbbedb (2020-05-08 22:25:45 -0400)
hud: better support for windows terminals

hud: better support for windows terminals

---

internal/cli/ci.go
internal/cli/wire_gen.go
internal/engine/upper_test.go
internal/hud/disabled_hud.go
internal/hud/hud.go
internal/hud/hud_test.go
internal/hud/printer.go
pkg/model/logstore/logstore.go

Please review the following commits I made in branch nicks/color:
2e618e0ebec595bcc71ce574595ba5b6740b7e8c (2020-05-13 00:17:36 -0400)
hud: fix bugs where tilt would drop logs on exit

hud: fix bugs where tilt would drop logs on exit

---

internal/build/image_builder.go
internal/build/image_builder_test.go

Please review the following commits I made in branch nicks/buildkit:
a967e6b461304637907be5ec1562576ad3a91cfc (2020-05-14 10:19:58 -0400)
clean up buildkit error messages a bit

clean up buildkit error messages a bit

---

CONTRIBUTING.md
README.md
scripts/install.ps1

Please review the following commits I made in branch nicks/installer:
16bc2942be3c9b4b1dc1f0c53e0cad97fcd4e67b (2020-05-15 19:31:13 -0400)
scripts: add a windows installer

scripts: add a windows installer

---

scripts/install.ps1

Please review the following commits I made in branch nicks/ch7042:
951e5778c6e82575585ae0b7b5b7cbd4a80fbaeb (2020-05-18 22:02:12 -0400)
Prefer the Scoop installer over our hand-rolled installer

Prefer the Scoop installer over our hand-rolled installer

---

.goreleaser.yml

Please review the following commits I made in branch nicks/ch6842:
96aa62ca43f101a216c50e78b05d5baa9d7babdb (2020-05-18 17:10:54 -0400)
Release Tilt to a scoop bucket

Release Tilt to a scoop bucket

---

.circleci/config.yml
web/package.json

Hello @nicks,
Please review the following commits I made in branch nicks/node12:
7dddf507004cafc17f620340e2a8b7a6410365ad (2020-05-27 11:26:58 -0400)
nodejs: pin to node 12.16

nodejs: pin to node 12.16

---

pkg/assets/dev.go

Hello @nicks,
Please review the following commits I made in branch nicks/stdin:
f9afac26bccb1e7a69632cf98262a697f50b0c09 (2020-05-28 19:20:26 -0400)
assets: fix the webpack dev server

assets: fix the webpack dev server

---

internal/cli/build.go
scripts/install.ps1
scripts/install.sh

Hello @nicks,
4c4cd55e8a9575fe1c8c2c9907cd89581cd53c54 (2020-05-29 16:16:23 -0400)
bump v0.14.1

bump v0.14.1

---

internal/engine/live_update_build_and_deployer.go

Hello @nicks,
Please review the following commits I made in branch nicks/familiar:
c05402765e7c61f3cd184c8f074819d285b13fc6 (2020-05-29 18:32:30 -0400)
fix printing of an image name

fix printing of an image name

---

internal/hud/renderer.go
internal/hud/resourceview.go
internal/hud/text.go
internal/rty/interactive_tester.go

Hello @hyu,
Please review the following commits I made in branch nicks/spinner:
3976994219fc58bbb53d5480ffd69b37e8b5599f (2020-05-19 17:36:11 -0400)
hud: fix the spinner in powershell

hud: fix the spinner in powershell

---

web/src/AppController.ts
web/src/ErrorModal.tsx
web/src/HUD.tsx
web/src/HudState.tsx
web/src/types.ts

(Video is cropped a little strangely, sorry about that)

web: error modal when snapshot fails

---

internal/engine/buildcontrol/log.go
internal/engine/buildcontroller.go
internal/engine/configs/actions.go
internal/engine/configs/configs_controller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/engine_state.go
pkg/model/build_reason.go

Please review the following commits I made in branch nicks/ch7263:
210d336342e8f95b5f84af23a7ed9ee463cfb9d0 (2020-05-29 19:53:14 -0400)
configs: unify manifest build reasons and tiltfile build reasons

configs: unify manifest build reasons and tiltfile build reasons

---

README.md

Hello @ellenkorbes, @victorwuky,
Please review the following commits I made in branch nicks/ch7415:
17fd628d8c3627a2bd3d29f11519e4392194fc55 (2020-06-05 14:47:44 -0400)
readme: add a link to the API reference. Fixes https://github.com/tilt-dev/tilt/issues/3407

readme: add a link to the API reference. Fixes https://github.com/tilt-dev/tilt/issues/3407

---

CONTRIBUTING.md
internal/README.md

Hello @nicks,
Please review the following commits I made in branch nicks/arch:
0168588398bd16868e3e5feb14ec7e7435fdf6b1 (2020-06-05 18:56:16 -0400)
add a README on internal architecture

add a README on internal architecture

---

internal/engine/upper_test.go

Hello @nicks,
e6cf7e28c9d7e246c3813c6ec616e7688bf86f6d (2020-06-08 13:00:13 -0400)
engine: fix some unit tests. Tests should generally not assert things in a goroutine

engine: fix some unit tests. Tests should generally not assert things in a goroutine

---

internal/k8s/testyaml/testyaml.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Discovered while diagnosing #3423
There's a lot of test YAML in here that isn't used, but it will be used in a subsequent diff.

tiltfile: don't assume default namespace if not specified in object selector

---

web/src/LogPaneLine.scss

Please review the following commits I made in branch nicks/ch4197:
4695f40ea2c5514d93da4aecd6dd0c5d8412eeb8 (2020-06-08 18:01:28 -0400)
web: set overflow-wrap: anywhere on log lines

web: set overflow-wrap: anywhere on log lines

---

internal/k8s/registry.go
internal/k8s/registry_test.go

Please review the following commits I made in branch nicks/ch7520:
eba20588a4aeef2049280b0ce3f881966772bac2 (2020-06-12 12:59:22 -0400)
k8s: implement the local registry discovery protocol. Fixes https://github.com/tilt-dev/tilt/issues/3435
514ae79cfab1e697873d0c657bfa4b57b159133c (2020-06-12 12:51:29 -0400)
k8s: implement local registry discovery protocol

k8s: implement the local registry discovery protocol. Fixes https://github.com/tilt-dev/tilt/issues/3435

---

internal/cli/ci.go
internal/cli/up.go
internal/cli/up_test.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/actions.go
internal/engine/subscribers.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/hud.go
internal/hud/hud_test.go
internal/hud/terminal_stream.go
internal/hud/wire.go
internal/store/engine_state.go
internal/store/store.go
internal/store/terminal.go

Please review the following commits I made in branch nicks/termmode:
64a178788237e8d22daa8fc7ee2fc80dbd266e44 (2020-06-12 17:31:10 -0400)
hud: allow the terminal mode to change at run-time

hud: allow the terminal mode to change at run-time

---

go.mod
go.sum
vendor/github.com/tilt-dev/localregistry-go/discover.go
vendor/modules.txt

Hello @nicks,
da0b9b2b0a068998668c8d2543e53549109a08a7 (2020-06-15 19:19:30 -0400)
vendor: localregistry

vendor: localregistry

---

internal/cli/build.go
internal/engine/upper.go
internal/hud/prompt/action.go
internal/hud/prompt/prompt.go
internal/hud/prompt/prompt_test.go
internal/store/testing_store.go
pkg/model/tilt_build.go

Please review the following commits I made in branch nicks/ch6285:
9d071dc036faee9f9bb281235b048e567201e83c (2020-06-16 10:06:07 -0400)
prompt: add hot keys for switching terminal modes

prompt: add hot keys for switching terminal modes

---

internal/cli/up.go
internal/cli/wire_gen.go
internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go
internal/engine/upper_test.go
internal/hud/prompt/prompt.go
internal/hud/prompt/prompt_test.go
internal/store/terminal.go

Hello @landism, @victorwuky,
Please review the following commits I made in branch nicks/ch7730:
d960bb36612f08619b9451e603e68c335257680a (2020-06-16 14:07:56 -0400)
prompt: add some metrics to the new tui prompt

prompt: add some metrics to the new tui prompt

---

internal/cli/up.go
internal/cli/up_test.go
internal/hud/prompt/prompt.go

Please review the following commits I made in branch nicks/ch6286/default:
30ce9da03028e064a6371a74f00fe6bdab321ac3 (2020-06-16 15:04:46 -0400)
cli: make prompt mode the default, and fix some minor bugs

cli: make prompt mode the default, and fix some minor bugs

---

internal/k8s/jsonpath/doc.go
internal/k8s/jsonpath/jsonpath.go
internal/k8s/jsonpath/node.go
internal/k8s/jsonpath/parser.go

Hello @nicks,
Please review the following commits I made in branch nicks/forkjsonpath:
0f53a903595f76f3b5f0bfcbad98b2e1f6452ec3 (2020-06-18 15:07:27 -0400)
fork jsonpath

fork jsonpath

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

I tried to write a k8s Job today and wished I had this

tiltfile: support auto_init on k8s_resource

---

internal/k8s/jsonpath/jsonpath_test.go
internal/k8s/jsonpath/parser_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/jsonpathtest:
eb4dc4bfcc19f4caff3158bdc1e9440dff4eb396 (2020-06-19 10:45:59 -0400)
k8s: also fork jsonpath tests

k8s: also fork jsonpath tests

---

internal/k8s/image.go
internal/k8s/json_path.go
internal/k8s/json_path_test.go
internal/k8s/jsonpath/jsonpath.go
internal/k8s/jsonpath/value.go
internal/k8s/testyaml/testyaml.go
internal/tiltfile/k8s.go

Please review the following commits I made in branch nicks/jsonpath:
3426e7f199012fdab1267f1f9c7c7579a55ae86d (2020-06-18 15:31:42 -0400)
k8s: improve jsonpath api to allow both extraction and injection

k8s: improve jsonpath api to allow both extraction and injection

---

internal/tiltfile/live_update.go
internal/tiltfile/live_update_test.go
internal/tiltfile/tiltfile_state.go

Revert "Revert "tiltfile: deprecation warning for restart_container + k8s resource [ch5943] (#3249)" (#3484)"

---

internal/engine/upper_test.go

Hello @nicks,
32521a95c385ff7c193d91357ebde176fb7f48a0 (2020-06-19 18:28:53 -0400)
engine: fix a racey test

engine: fix a racey test

---

internal/cli/ci.go

Hello @nicks,
Please review the following commits I made in branch nicks/ci:
d4521f55dff9d1b55a83ed3d218e57b4b115a8c4 (2020-06-25 10:32:58 -0400)
fix a minor display issue in tilt ci

fix a minor display issue in tilt ci

---

internal/engine/image_build_and_deployer_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/merge:
592c624cffe1e45527e9f10d86ec60de3323014a (2020-06-26 13:33:53 -0400)
fix a small merge problem

fix a small merge problem

---

integration/crd/Dockerfile
integration/crd/Tiltfile
integration/crd/crd.yaml
integration/crd/um.yaml
integration/crd_test.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/k8s/image.go
internal/k8s/image_test.go
internal/k8s/locator.go
internal/k8s/object_selector.go
internal/k8s/target.go
internal/k8s/target_test.go
internal/store/engine_state_test.go
internal/testutils/manifestbuilder/manifestbuilder.go
internal/tiltfile/tiltfile_state.go
pkg/model/k8s_target.go
pkg/model/manifest.go

Please review the following commits I made in branch nicks/ch4395:
d2035819ee527ee69b93cd13857105ae45023579 (2020-06-26 20:17:59 -0400)
k8s: validate crd injection

k8s: validate crd injection

---

internal/hud/format.go
web/src/SidebarResources.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/format.test.ts
web/src/format.ts

Please review the following commits I made in branch nicks/ch8204:
da9b3bc78278830e76a32930036b41817c6e00f4 (2020-07-01 19:42:11 -0400)
web: fix a bug in duration display. Fixes https://github.com/tilt-dev/tilt/issues/3533

web: fix a bug in duration display. Fixes https://github.com/tilt-dev/tilt/issues/3533

---

internal/rty/scroll.go

Please review the following commits I made in branch nicks/ch8223:
8d7d13fd186aac816e855f92b7901a453ad7a2e9 (2020-07-02 14:14:07 -0400)
rty: fix panic. Fixes https://github.com/tilt-dev/tilt/issues/3543

rty: fix panic. Fixes https://github.com/tilt-dev/tilt/issues/3543

---

web/package.json
web/src/SidebarAccount.tsx
web/yarn.lock

Fixes #3420
TIL: https://developer.paciellogroup.com/blog/2012/04/how-to-remove-css-outlines-in-an-accessible-manner/
https://www.npmjs.com/package/react-outline-manager?activeTab=readme

web: get rid of blue box around tilt cloud status

---

internal/engine/k8swatch/event_watch_manager.go
internal/engine/k8swatch/event_watch_manager_test.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch8352:
91c7e1bfe2b6e594334b97c5212a0198aade9980 (2020-07-10 16:13:28 -0400)
print image pull/pulling events
here's an example of how this looks in practice:
https://cloud.tilt.dev/snapshot/AYakxvAL8dRwcxxqjC4=
Fixes https://github.com/tilt-dev/tilt/issues/3562

print image pull/pulling events

---

internal/cli/build.go
scripts/install.ps1
scripts/install.sh
scripts/record-release.sh

Please review the following commits I made in branch maiamcc/v0.16.1:
5de50de2f0b6104f3ac6cbce6275d080894f9635 (2020-07-17 16:21:24 -0400)
bump to v0.16.1

bump to v0.16.1

---

internal/watch/notify.go
internal/watch/notify_test.go

Please review the following commits I made in branch nicks/bufsize:
a60b49cbd4a9ae9f5d52c8c3502664620685d021 (2020-07-27 19:03:44 -0400)
watch: fix a dumb errcheck

watch: fix a dumb errcheck

---

.goreleaser.yml

goreleaser: add armv6 and arm64

---

.circleci/config.yml
integration/tilt_args_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/dockerupgrade:
64dcf6d981ff9fc3086151b680cfcc31c89d2348 (2020-07-29 18:56:48 -0400)
circleci: update docker

circleci: update docker

---

internal/tiltfile/k8s.go
internal/tiltfile/k8s/resource.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/kindready:
9e2a77eac225974de48ff8094875419550253142 (2020-07-30 18:25:37 -0400)
tiltfile: add support for pod_readiness set on k8s_kind

tiltfile: add support for pod_readiness set on k8s_kind

---

.goreleaser.yml

Hello @nicks,
Please review the following commits I made in branch nicks/goreleaser:
878c21c73276f91d065350f64cccd976ca2da84d (2020-07-31 11:44:38 -0400)
add verify-install to goreleaser

add verify-install to goreleaser

---

internal/cli/build.go
scripts/install.ps1
scripts/install.sh

Hello @nicks,
Please review the following commits I made in branch nicks/versions:
614a639b632f07ce3f37bbe9d02f4e5c04798558 (2020-07-31 12:00:13 -0400)
bump versions

bump versions

---

scripts/goreleaser.Dockerfile

Please review the following commits I made in branch nicks/goreleaser2:
36efd7c3f7d88d3d546ee9b1b3feb05c73f1e6b9 (2020-07-31 11:53:14 -0400)
also update the goreleaser tilt image to use circleci-kind v1.2.0
878c21c73276f91d065350f64cccd976ca2da84d (2020-07-31 11:44:38 -0400)
add verify-install to goreleaser

also update the goreleaser tilt image to use circleci-kind v1.2.0

---

internal/hud/server/logs_reader_test.go
internal/hud/webview/convert.go

Please review the following commits I made in branch maiamcc/logs-reader-tests:
888c660a0bb55bdaaf670f2dfda587222ab99c93 (2020-07-31 16:57:47 -0400)
more tests
34ba00ed0c141c925f9ec1742886492f41f38611 (2020-07-31 16:57:21 -0400)
test framework

logs_reader: test for log streamer [ch8435]

---

pkg/model/logstore/logstore.go
pkg/model/logstore/logstore_test.go

this unblocks #3655 as per [nick's comment](https://github.com/tilt-dev/tilt/pull/3655#discussion_r464553690)

logstore: can pass options to logStore.ContinuingLines

---

internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_state.go

Please review the following commits I made in branch nicks/ch8758:
09be75d309534776bacfd13892ac5af63faf2b62 (2020-08-05 20:34:22 -0400)
docker-compose: handle load failures correctly
fixes https://github.com/tilt-dev/tilt/issues/3661

docker-compose: handle load failures correctly

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/readme:
a60060dc4c918eac97db5033cdafcf3a90dff2d0 (2020-08-06 11:26:02 -0400)
update the readme to match docs.tilt.dev

update the readme to match docs.tilt.dev

---

internal/cli/up.go
internal/cli/up_test.go
internal/hud/prompt/prompt.go
internal/hud/prompt/prompt_test.go

Hi @nicks 
Would this approach count as an "intermediary" solution to the Epic 7733?

cli: added legacy and stream flags, changed prompt to reflect usage

---

internal/cli/logs.go
internal/hud/server/logs_reader.go
internal/hud/server/logs_reader_test.go
internal/hud/server/websocket_reader_test.go
internal/hud/server/websocket_test.go

esp. want to know if
1. I've done anything dumb with channels,
2. I've broken or defiled the existing `fakeConn` struct wtih my changes, or
3. These tests are overkill in your opinion. (I'm on the fence, and don't feel
too bad about it cuz they took me < an hour to write, curious to hear thoughts.)

hud/server: websocket reader tests [ch8683]

---

internal/dockercompose/client.go

Please review the following commits I made in branch nicks/ch8819:
b7e50dc5ebc8cb7d5b5475c2c5c999d3e3d7b1c0 (2020-08-07 11:29:40 -0400)
dockercompose: allow docker-compose build to run in parallel, even though docker-compose up cannot
Fixes https://github.com/tilt-dev/tilt/issues/3665

dockercompose: allow docker-compose build to run in parallel, even though docker-compose up cannot

---

internal/cli/build.go
scripts/install.ps1
scripts/install.sh

Hello @nicks,
57955231a6634c290f6f87fbf2a99e69f7d979cb (2020-08-10 16:11:17 -0400)
bump version to v0.17.1

bump version to v0.17.1

---

internal/hud/server/websocket_reader_test.go
internal/hud/server/websocket_test.go

Hello @nicks,
Please review the following commits I made in branch maiamcc/flakey-test:
69e09fce7763da5b1749f6c59595d90de63fe261 (2020-08-11 11:28:11 -0400)
hud/server: fix flakey test by adding re-check [ch8843]

hud/server: fix flakey test by adding re-check [ch8843]

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/asdf:
65c9e287289f7a0ce008856a66f68b972cd58cc9 (2020-08-11 18:46:41 -0400)
add a reference to asdf in the readme
57955231a6634c290f6f87fbf2a99e69f7d979cb (2020-08-10 16:11:17 -0400)
bump version to v0.17.1

add a reference to asdf in the readme

---

internal/engine/telemetry/controller.go
internal/tracer/tracer.go

Hello @nicks,
Please review the following commits I made in branch nicks/go15:
a1e47475e6bb3b6016fde668ebe62b42f3937aa9 (2020-08-12 18:19:12 -0400)
fix compilation on go 1.15

fix compilation on go 1.15

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/choco:
58b66c10e87c7791651d7b6fab957294ab65b46a (2020-08-12 18:31:53 -0400)
pin the go version in chocolatey

pin the go version in chocolatey

---

internal/k8s/client.go
internal/k8s/entity.go
internal/tiltfile/files.go
internal/tiltfile/helm_test.go

Please review the following commits I made in branch nicks/ch8952:
b0c1a8bdebc577696cc4db75df2d04f9392a5d6f (2020-08-14 09:41:27 -0400)
tiltfile: fix a bug in helm(namespace=) semantics. Fixes https://github.com/tilt-dev/tilt/issues/3701

tiltfile: fix a bug in helm(namespace=) semantics. Fixes https://github.com/tilt-dev/tilt/issues/3701

---

web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/serializejs:
522afdc4193e0b00b40cb00e229ff29b2ecada78 (2020-08-14 14:58:21 -0400)
update web dependencies to address security alerts

update web dependencies to address security alerts

---

Tiltfile
integration/tilt.go
internal/cli/ci.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/upper_test.go
internal/hud/server/controller.go
pkg/model/web.go

Since already have `hud`, `legacy`, and `stream` modes.

Remove no-browser mode

---

internal/cli/build.go
scripts/goreleaser.sh
scripts/install.ps1
scripts/install.sh
scripts/release.sh

Hello @nicks,
d98a91cb38152fb418ef91fe0dd012c82d210729 (2020-08-14 18:50:38 -0400)
bump version numbers and fix some install script bugs

bump version numbers and fix some install script bugs

---

.circleci/Dockerfile
.circleci/config.yml

Please review the following commits I made in branch nicks/lint:
3fd7bfb323119dd89f4d1300632c2c87994a2d02 (2020-08-25 12:59:34 -0400)
give more RAM to the build-linux job

give more RAM to the build-linux job

---

internal/cli/build.go
scripts/install.ps1
scripts/install.sh

Hello @,
Please review the following commits I made in branch maiamcc/v0.17.3:
85befd3c8d5c622dfbd82cea69c3d6d38b6ebadc (2020-08-27 16:27:14 -0400)
bump v0.17.3

bump v0.17.3

---

go.mod
go.sum
vendor/github.com/tilt-dev/wmclient/pkg/analytics/cli.go
vendor/modules.txt

to pick up https://github.com/tilt-dev/wmclient/pull/33

tilt: bump wmclient

---

scripts/install.sh

Hello @nicks,
Please review the following commits I made in branch nicks/check:
955b4a88f93f8c5600e0471f5736413c35cccd90 (2020-09-03 18:14:34 -0400)
fix the version check

fix the version check

---

go.mod
go.sum
internal/cli/metrics.go
internal/engine/metrics/controller.go
internal/engine/metrics/meter.go
vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
vendor/go.opencensus.io/stats/view/aggregation.go
vendor/go.opencensus.io/stats/view/aggregation_data.go
vendor/go.opencensus.io/stats/view/collector.go
vendor/go.opencensus.io/stats/view/view_to_metric.go
vendor/go.opencensus.io/stats/view/worker.go
vendor/go.opencensus.io/stats/view/worker_commands.go
vendor/modules.txt

Please review the following commits I made in branch nicks/flush:
18a4c2b383dd17b15f7b967cbe2597449baa72bb (2020-09-04 14:06:58 -0400)
metrics: add a flush mechanism

metrics: add a flush mechanism

---

CONTRIBUTING.md
scripts/release-update-tilt-docs-repo.sh
scripts/release-update-tilt-repo.sh
scripts/release.sh

7146777f360a7ece145264558e578aa878b947d5 (2020-09-03 18:00:56 -0400)
tweak scripts a bit
02b5358376944cb43738d659adbee2f3e45a4c89 (2020-09-03 17:49:33 -0400)
add scripts to help with the release process

Add scripts for automating release process

---

web/src/__snapshots__/LogPane.test.tsx.snap
web/src/__snapshots__/ResourceInfo.test.tsx.snap
web/src/__snapshots__/SecondaryNav.test.tsx.snap
web/src/__snapshots__/Sidebar.test.tsx.snap
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/security:
b8cb1177b8cba7baa32fdf61dcd7320bea75de08 (2020-09-11 18:47:11 -0400)
update js dependencies

update js dependencies

---

internal/engine/fswatch/watchmanager.go
internal/engine/fswatch/watchmanager_test.go

Please review the following commits I made in branch nicks/custombuildfswatch:
44508a3349be19d14f90217472ad5bdfef8c434d (2020-09-11 18:09:25 -0400)
Make sure custom_build(outputs_image_ref_to=...) writes are always ignored

Make sure custom_build(outputs_image_ref_to=...) writes are always ignored

---

internal/tiltfile/docker.go
internal/tiltfile/docker_test.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/value/path.go
internal/tiltfile/value/value.go

Please review the following commits I made in branch nicks/ch9358:
2ee9c954879e5206cf6716e5500e9cfe4df890e1 (2020-09-11 18:40:23 -0400)
Add custom_build(outputs_image_ref_to=...) Tiltfile API

Add custom_build(outputs_image_ref_to=...) Tiltfile API

---

internal/engine/fswatch/watchmanager_test.go
internal/engine/upper_test.go
internal/ignore/path_matcher.go
internal/ignore/path_matcher_test.go
internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/docker_test.go
internal/tiltfile/tiltfile_state.go
pkg/model/manifest.go
pkg/model/manifest_test.go

Please review the following commits I made in branch nicks/ignores:
02269dd20a7db33b8429a9e8addf3decab760ad2 (2020-09-15 14:48:13 -0400)
model: Change data model for ignores

model: Change data model for ignores

---

scripts/install.sh

Please review the following commits I made in branch nicks/ch9374:
ab42cfb2bad8a40700c7fd45e2b9a7a216e71ee7 (2020-09-15 18:43:59 -0400)
install tilt with homebrew on linux when available. Fixes https://github.com/tilt-dev/tilt/issues/3078

install tilt with homebrew on linux when available. Fixes https://github.com/tilt-dev/tilt/issues/3078

---

internal/tiltfile/config/config.go
internal/tiltfile/config/config_test.go
internal/tiltfile/starkit/environment.go

Please review the following commits I made in branch nicks/ch9402:
4f0bef1c6d13effb52db129dc422b92c07220796 (2020-09-17 09:58:21 -0400)
tiltfile: add config.tiltfile_path, config.tiltfile_dir. Fixes https://github.com/tilt-dev/tilt/issues/3507

tiltfile: add config.tiltfile_path, config.tiltfile_dir. Fixes https://github.com/tilt-dev/tilt/issues/3507

---

internal/engine/configs/actions.go
internal/engine/configs/configs_controller.go
internal/engine/fswatch/watchmanager.go
internal/engine/fswatch/watchmanager_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/engine_state.go
internal/tiltfile/include_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/watch/tiltignore.go
internal/tiltfile/watch/watch.go
internal/tiltfile/watch/watch_test.go
pkg/model/manifest.go
pkg/model/watch_settings.go

Please review the following commits I made in branch nicks/watchsettings:
2dfdd18f7e5cb71b25e1cfef54cf15dac066f2b6 (2020-09-21 22:20:05 -0400)
Add watch_settings(ignore=) for global ignores. Fixes https://github.com/tilt-dev/tilt/issues/3404

Add watch_settings(ignore=) for global ignores. Fixes https://github.com/tilt-dev/tilt/issues/3404

---

internal/engine/k8swatch/event_watch_manager.go
internal/engine/k8swatch/pod_watch.go
internal/engine/k8swatch/service_watch.go
internal/engine/k8swatch/watcher.go

Please review the following commits I made in branch nicks/watcher:
9b3a5bc7da724e051c22a0debcb6029188a62b00 (2020-09-28 18:45:09 -0400)
k8swatch: refactor into a common state struct
i want to add some more state to track here, and having a common struct seems
like the simplest way to help these watchers converge

k8swatch: refactor into a common state struct

---

web/src/testdata.tsx

@hyu @nicks idk if I'm messing with any tsx stuff here: any objections to me typing these test data functions / updating the test data functions to conform exactly with the types as we define them?
(If I get a 👍   I'll go ahead and do the rest)

type some old test data

---

internal/ospath/ospath.go
internal/ospath/ospath_test.go

Please review the following commits I made in branch nicks/ch9650:
24be044572b610c04d75c30e515506468a5cff82 (2020-10-01 19:14:17 -0400)
ospath: handle case-insensitive file systems. fixes https://github.com/tilt-dev/tilt/issues/3730

ospath: handle case-insensitive file systems. fixes https://github.com/tilt-dev/tilt/issues/3730

---

web/src/__snapshots__/AlertPane.test.tsx.snap
web/src/testdata.tsx

whoops this is what #3817 was supposed to be, my bad

web tests: clean up unused test data, add typing

---

web/src/HUD.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/SidebarKeyboardShortcuts.tsx

Please review the following commits I made in branch nicks/ch9619:
50328ffffe3e5c2e20fb13f8e5655b80c4404108 (2020-10-02 19:12:44 -0400)
Add j/k keyboard shortcuts
0ecb7ec011c38ec8163c8e12507caa1f2b84b843 (2020-10-02 18:33:55 -0400)
web: split SidebarItem into its own file

Add j/k keyboard shortcuts

---

internal/k8s/kubectl_runner.go

If the path entry that points you to the tilt binary uses a tilde as short for the home dir (e.g. `~/go/bin`),
commands run from within Tilt apparently don't parse the path correctly, and calls to `exec.Cmd('tilt'...)`
fall through to the next `tilt` available on your path (for me and many others, the ruby gem).
With the old code, setting path with `export PATH='~/code/go/bin':$PATH` and calling `tilt up` threw the following when trying to kubectl apply my resources:
```
Build Failed: kubectl apply:
stderr: tilt: invalid option: --context
template engine not found for: kind-kind
: exit status 1
```
setting path with `export PATH='/Users/maia/code/go/bin':$PATH` and running `tilt up` did not throw an error.
With new code, both configurations work.

k8s: get tilt executable path (for 'tilt kubectl' calls) in a way that respects ~ in $PATH

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/fix:
d60eb88e2db65dfbceea8263e80da61d0f247e28 (2020-10-08 11:55:54 -0400)
fix path

circleci: fix paths in circleci config

---

internal/hud/webview/convert_test.go
internal/hud/webview/view.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/tiltfile/links/links.go
internal/tiltfile/links/links_test.go
internal/tiltfile/tiltfile_test.go
pkg/model/manifest.go

Nick made a good call in #3834

model: Link contains a url instead of a string

---

web/package.json
web/src/HUD.tsx
web/src/SecondaryNav.tsx
web/src/SecondaryNavKeyboardShortcuts.test.tsx
web/src/SecondaryNavKeyboardShortcuts.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/SidebarKeyboardShortcuts.tsx
web/src/__snapshots__/SecondaryNav.test.tsx.snap
web/yarn.lock

Please review the following commits I made in branch nicks/morenav:
eb19230b3b3b2b45b1243ea8290a3de1b4792777 (2020-10-06 18:57:45 -0400)
web: add navigate with 1, 2, 3 keys

web: add navigate with 1, 2, 3 keys

---

.circleci/config.yml
configs/storybook/deploy.sh

Hello @nicks,
Please review the following commits I made in branch nicks/storybook2:
de96e213f3b08ec5c97a438aab97fb1a694c53c0 (2020-10-09 12:57:57 -0400)
upgrade docker version in deploy-storybook, use buildkit

upgrade docker version in deploy-storybook, use buildkit

---

web/src/ResourceInfo.tsx
web/src/ResourceInfoKeyboardShortcuts.test.tsx
web/src/ResourceInfoKeyboardShortcuts.tsx
web/src/SecondaryNavKeyboardShortcuts.test.tsx
web/src/SecondaryNavKeyboardShortcuts.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/__snapshots__/ResourceInfo.test.tsx.snap

Please review the following commits I made in branch nicks/morenav2:
28d0405a9b002d826c833dce7c00692cb80ceb29 (2020-10-07 12:03:39 -0400)
web: add keyboard shortcuts for snapshot, endpoints
ed79dfa44bb185a638e5e72fbf086e850ffd9a00 (2020-10-07 09:57:55 -0400)
web: add navigate with 1, 2, 3 keys

web: add keyboard shortcuts for snapshot, endpoints

---

web/src/SidebarAccount.stories.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/stories:
f9dedad9226fb5a128d12a716adc3158a0dcf63c (2020-10-13 19:25:03 -0400)
add storybooks for sidebar account

add storybooks for sidebar account

---

web/src/FloatDialog.tsx
web/src/ShortcutsDialog.stories.tsx
web/src/ShortcutsDialog.tsx
web/src/assets/svg/close.svg

Please review the following commits I made in branch nicks/dialog:
ffec2c5cce5602435216e3f15f711eae4f922d6a (2020-10-13 19:11:11 -0400)
add a shortcut dialog

add a shortcut dialog

---

web/src/AlertPane.test.tsx
web/src/AppController.test.ts
web/src/AppController.ts
web/src/HUD.tsx
web/src/PathBuilder.test.tsx
web/src/PathBuilder.tsx
web/src/Sidebar.stories.tsx
web/src/Sidebar.test.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/SidebarTriggerButton.test.tsx
web/src/trace.test.ts

Please review the following commits I made in branch nicks/ch9817:
d82a2a7f1f8fd76273bb3312ce4b6bf046276f3d (2020-10-14 19:07:50 -0400)
switch websocket to wss when running over https. fixes https://github.com/tilt-dev/tilt/issues/3863

switch websocket to wss when running over https. fixes https://github.com/tilt-dev/tilt/issues/3863

---

web/src/HUD.tsx
web/src/ResourceInfo.tsx
web/src/ResourceInfoKeyboardShortcuts.tsx
web/src/SecondaryNavKeyboardShortcuts.tsx
web/src/SidebarAccount.tsx
web/src/SidebarKeyboardShortcuts.tsx

Please review the following commits I made in branch nicks/ch9591/analytics:
86bc2abe29276a83c19165eb9a508f6085ff7ad4 (2020-10-16 14:03:38 -0400)
web: analytics for keyboard shortcuts

web: analytics for keyboard shortcuts

---

internal/hud/webview/convert_test.go
internal/store/engine_state.go
internal/store/engine_state_test.go

Previous behavior was to alphabetically sort all endpoints to make sure order was deterministic; this is vestigial. Sort endpoints only where have to to ensure determinism.

store: preserve user's ordering of endpoints wherever possible [ch9653]

---

web/src/HUD.tsx
web/src/ShortcutsDialog.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/SidebarKeyboardShortcuts.tsx
web/src/SidebarResources.tsx
web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Please review the following commits I made in branch nicks/ch9618/r:
7adfe60e0e1bf117aff9e8ad32cf62839d4ddfe3 (2020-10-19 12:26:08 -0400)
web: reload resource on 'r'

web: reload resource on 'r'

---

web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/object-path:
797d1f86d375f8d1e09b9587c27eb521490c0378 (2020-10-21 18:34:39 -0400)
yarn upgrades, based on security warnings

yarn upgrades, based on security warnings

---

internal/k8s/env.go
internal/k8s/env_test.go

Please review the following commits I made in branch nicks/minikube:
a9aba0ead460aa23aafeb7604a1bd276e72f8edb (2020-10-22 17:50:17 -0400)
k8s: improve minikube detection

k8s: improve minikube detection

---

internal/engine/upper.go
internal/store/engine_state.go

redoing #3878 as per comments, and i'll want these methods accessible from
the `configs` package for tests

store: move some trigger queue methods onto engine state

---

internal/engine/runtimelog/podlogmanager.go
internal/engine/runtimelog/podlogmanager_test.go

Please review the following commits I made in branch nicks/istio:
fe24ce34e9c2b2471ba3aa731c886fddd5cbdd1b (2020-10-27 12:09:01 -0400)
engine: ignore istio-init and istio-proxy by default. A short-term fix to address https://github.com/tilt-dev/tilt/issues/3814

engine: ignore istio-init and istio-proxy by default. A short-term fix to address https://github.com/tilt-dev/tilt/issues/3814

---

internal/engine/buildcontrol/build_control.go
internal/engine/buildcontrol/build_control_test.go

Please review the following commits I made in branch nicks/restarts:
08e4f97ac73ff87dbe0a2595c5b9a3c0e1cf3c35 (2020-10-28 23:10:14 -0400)
buildcontrol: don't hold back live updates if the container is crashlooping

buildcontrol: don't hold back live updates if the container is crashlooping

---

web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx

here's the frontend change for triggering tiltfile;
won't land until backend code is in, but had it done
so figured I'd send for review

web: show triggr button for tiltfile [ch9864]

---

internal/tiltfile/config/config.go
internal/tiltfile/config/config_test.go
internal/tiltfile/config/object.go
internal/tiltfile/encoding/json.go
internal/tiltfile/encoding/starlark.go
internal/tiltfile/encoding/yaml.go

Please review the following commits I made in branch nicks/ch10114:
3b87a5e48b90dab286758a9f4bad2629f8cd5ad9 (2020-11-10 14:58:12 -0500)
tiltfile: add config.define_object. Fixes https://github.com/tilt-dev/tilt/issues/3334

tiltfile: add config.define_object. Fixes https://github.com/tilt-dev/tilt/issues/3334

---

internal/engine/runtimelog/podlogmanager.go
internal/engine/runtimelog/podlogmanager_test.go
internal/engine/runtimelog/reader.go
internal/k8s/fake_client.go

Please review the following commits I made in branch nicks/ch10128:
d1db65d60f432f9c0ae39cc5c3a27fb70206e9f1 (2020-11-10 13:59:17 -0500)
engine: restart log watcher if nothing's happening. Fixes https://github.com/tilt-dev/tilt/issues/3908

engine: restart log watcher if nothing's happening. Fixes https://github.com/tilt-dev/tilt/issues/3908

---

internal/k8s/watch.go
internal/k8s/watch_test.go

d06b36ef9b0a8cdf12e1ff4a9f784f6d4554cc6d (2020-11-11 21:58:06 -0500)
k8s: fix a bug in k8s version parsing. Fixes https://github.com/tilt-dev/tilt/issues/3870

k8s: fix a bug in k8s version parsing. Fixes https://github.com/tilt-dev/tilt/issues/3870

---

internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/docker_test.go
internal/tiltfile/live_update.go
internal/tiltfile/live_update_test.go
internal/tiltfile/local_resource.go
internal/tiltfile/value/path.go

Please review the following commits I made in branch nicks/ch10018:
04f72bc58ba682b3bf7c118425d0ccf50997693a (2020-11-10 17:09:28 -0500)
custom_build should allow 0 deps. Also, clean up path unpacking

custom_build should allow 0 deps. Also, clean up path unpacking

---

scripts/release-ci.sh
scripts/release.Dockerfile

Hello @nicks,
Please review the following commits I made in branch nicks/releaser:
48d52b7156f145aece78e88ca2c68b2eba009905 (2020-11-12 18:45:17 -0500)
fix the releaser

fix the releaser

---

internal/engine/buildcontrol/actions.go
internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/upper.go

Please review the following commits I made in branch nicks/ch10185:
1a1eae7e0cbef21ec60e20a0e6982e6f117127bc (2020-11-12 14:29:30 -0500)
engine: correctly handle crash detection on full rebuilds

engine: correctly handle crash detection on full rebuilds

---

internal/engine/k8swatch/event_watch_manager_test.go
internal/engine/k8swatch/watcher.go

Please review the following commits I made in branch nicks/ch10237:
c9eaa66d6b9c13bf23ac06ac21d1cc43bb49284d (2020-11-16 15:50:17 -0500)
engine: more robust handling of duplicate resources

engine: more robust handling of duplicate resources

---

internal/cli/metrics.go
internal/tiltfile/metrics.go
internal/tiltfile/tiltfile.go

Please review the following commits I made in branch nicks/ch10252:
b32577a4eb56af68997f4822faa1b121637226c0 (2020-11-18 14:01:33 -0500)
tiltfile: add tiltfile exec metrics reporting

tiltfile: add tiltfile exec metrics reporting

---

internal/engine/buildcontroller_test.go

Hello @nicks,
1d69b9d9fa154e284ee0ae78b867f440d7ac4570 (2020-11-18 15:10:52 -0500)
engine: fix a flakey test

engine: fix a flakey test

---

scripts/release-ci.sh
scripts/release.Dockerfile

Hello @nicks,
Please review the following commits I made in branch nicks/dir:
b27032058979f51cd556ac00673b3c5a9208f8b4 (2020-11-19 11:29:28 -0500)
scripts: make sure the .windmill directory exists during the release process

scripts: make sure the .windmill directory exists during the release process

---

.github/ISSUE_TEMPLATE/feature_request.md

Hello @nicks,
Please review the following commits I made in branch nicks/enhancement:
cde96add037639224c2c9f31508e12819ad85343 (2020-11-24 15:22:18 -0500)
add enhancement label to feature request issue template
19a52f3909508db9a66165e99f0ba46ae1cb5bff (2020-11-24 11:49:30 -0500)
engine: merge local metrics services into the engine state

add enhancement label to feature request issue template

---

internal/engine/metrics/yaml.go

Hello @nicks,
Please review the following commits I made in branch nicks/newgraphs:
3fb4cb861ec5d5725232b6e123291aa5b1d38ceb (2020-11-25 00:00:54 -0500)
add new grafana graphs

add new grafana graphs

---

internal/cli/cli.go

Please review the following commits I made in branch nicks/issue3962:
c7d4d1ae2f8efb243f3ff9ef2b2f2a791ff794ad (2020-12-03 11:47:00 -0500)
cli: handle SIGHUP. Fixes https://github.com/tilt-dev/tilt/issues/3962

cli: handle SIGHUP. Fixes https://github.com/tilt-dev/tilt/issues/3962

---

internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/watcherror:
c1c51dfe76db94d8eb85af599c4a9d2f6fb1e5b4 (2020-12-02 18:10:15 -0500)
watch: improve error messages when you run out of inotify instances

watch: improve error messages when you run out of inotify instances

---

web/src/SidebarItemView.stories.tsx
web/src/SidebarResources.tsx

Please review the following commits I made in branch nicks/newsidebar:
c73ccb23395766b0341d3c2a27e8a842122d641d (2020-12-04 14:11:16 -0500)
web: pull out a storybook for iterating on the sidebar card

web: pull out a storybook for iterating on the sidebar card

---

web/src/SidebarItemView.stories.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/stories2:
fe9a8f3a2f5244770aec24471d24ef79601bf042 (2020-12-07 11:14:58 -0500)
web: refactor the sidebar item view storybook a bit

web: refactor the sidebar item view storybook a bit

---

web/package.json
web/src/__snapshots__/FatalErrorModal.test.tsx.snap
web/src/__snapshots__/LogPane.test.tsx.snap
web/src/__snapshots__/ResourceInfo.test.tsx.snap
web/src/__snapshots__/SecondaryNav.test.tsx.snap
web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
web/src/__snapshots__/Sidebar.test.tsx.snap
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/storybook:
3281ea44c45ac10c829eac26bb753f5068622748 (2020-12-07 11:44:30 -0500)
web: update package.json

web: update package.json

---

web/src/AnalyticsNudge.stories.tsx
web/src/FatalErrorModal.stories.tsx
web/src/HUDLayout.stories.tsx
web/src/HeroScreen.stories.tsx
web/src/LogPane.stories.tsx
web/src/LogPaneLine.stories.tsx
web/src/MetricsPane.stories.tsx
web/src/SecondaryNav.stories.tsx
web/src/ShareSnapshotModal.stories.tsx
web/src/ShortcutsDialog.stories.tsx
web/src/Sidebar.stories.tsx
web/src/SidebarAccount.stories.tsx
web/src/SidebarItemView.stories.tsx
web/src/SocketBar.stories.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/storybook-migrate:
a0837f4d6e063783ae84edeb4bb9aac82870a21e (2020-12-07 12:40:46 -0500)
web: update storybooks to CSF format
https://storybook.js.org/docs/react/api/csf
this makes it easier to use storybook components in tests
a4dd370e73e3f220f684b04cb455aba655114c82 (2020-12-07 12:10:55 -0500)
web: update package.json

web: update storybooks to CSF format

---

integration/imagetags/Tiltfile
internal/engine/upper_test.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch5510:
ce98cdbef6035c79f7285f6f6af5d31a2bb20916 (2020-12-07 15:16:15 -0500)
tiltfile: remove k8s_resource_assembly

tiltfile: remove k8s_resource_assembly

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/empty:
593e6e385ed5d2ca9243a9058251e5b956a65f5e (2020-12-07 17:02:34 -0500)
tiltfile: improve empty yaml error message

tiltfile: improve empty yaml error message

---

web/src/AlertPane.tsx
web/src/HUD.tsx
web/src/Sidebar.stories.tsx
web/src/SidebarIcon.tsx
web/src/SidebarItem.tsx
web/src/SidebarItemView.stories.tsx
web/src/SidebarPin.tsx
web/src/SidebarResources.test.tsx
web/src/SidebarResources.tsx
web/src/SidebarTriggerButton.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/alerts.test.ts
web/src/alerts.ts
web/src/status.tsx
web/src/style-helpers.ts

Please review the following commits I made in branch nicks/newsidebar2:
c42bc56d1ed05a2a195c778bd88383bd73164466 (2020-12-07 11:34:23 -0500)
web: split sidebar item into a build status and a runtime status

web: split sidebar item into a build status and a runtime status

---

web/src/SidebarIcon.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/__snapshots__/SidebarIcon.test.tsx.snap

Hello @hyu,
Please review the following commits I made in branch nicks/ch10436:
4f8d1648a609690a8f524c2f9f7acc3f1d3a0cf9 (2020-12-08 18:47:33 -0500)
web: add sidebar item textures

web: add sidebar item textures

---

web/src/testdata.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/testdata:
7e3535c09bae527a664c52ebbd034e45f1bf36cf (2020-12-10 18:09:07 -0500)
test: add well-formed version data to testdata

test: add well-formed version data to testdata

---

web/src/SidebarItemView.stories.tsx
web/src/SidebarResources.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Hello @hyu,
Please review the following commits I made in branch nicks/ch10423:
be44abd80b18e1cf7de4ff342bbf6d2b2d66ffbd (2020-12-08 16:00:00 -0500)
web: adjust the size of the all sidebar item

web: adjust the size of the all sidebar item

---

web/.storybook/preview-head.html
web/package.json
web/public/index.html
web/src/SidebarIcon.test.tsx
web/src/SidebarIcon.tsx
web/src/SidebarItemView.stories.tsx
web/src/SidebarResources.test.tsx
web/src/SidebarResources.tsx
web/src/Tooltip.stories.tsx
web/src/Tooltip.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/__snapshots__/SidebarIcon.test.tsx.snap
web/yarn.lock

Hello @hyu,
Please review the following commits I made in branch nicks/ch10425:
98aa19f98d0eea5f9fc6e548ed9ffee0cf5c7176 (2020-12-11 16:27:46 -0500)
web: add tooltips for sidebar items

web: add tooltips for sidebar items

---

web/.storybook/preview-head.html
web/src/HUD.tsx
web/src/OverviewGrid.stories.tsx
web/src/OverviewGrid.tsx
web/src/OverviewPane.stories.tsx
web/src/OverviewPane.tsx
web/src/OverviewResourceBar.stories.tsx
web/src/OverviewResourceBar.tsx
web/src/OverviewStatusBar.stories.tsx
web/src/OverviewStatusBar.tsx
web/src/OverviewTabBar.stories.tsx
web/src/OverviewTabBar.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10468:
b24c8c2aa19f9ae3aff91139bc6d4fad40675c05 (2020-12-10 16:45:47 -0500)
web: add scaffolding for the OverviewPane

web: add scaffolding for the OverviewPane

---

web/src/HUD.tsx
web/src/OverviewPane.tsx
web/src/OverviewResourceDetails.stories.tsx
web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.stories.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewResourceSidebar.stories.tsx
web/src/OverviewResourceSidebar.tsx
web/src/OverviewTabBar.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10469:
a1885b8f387ca91fd9f7963ba0a3369e426bd793 (2020-12-11 09:59:16 -0500)
web: scaffolding for OverviewResourcePane
3f06807899330ad4600b62f8e4d9a433036045bb (2020-12-11 09:59:16 -0500)
web: add scaffolding for the OverviewPane

web: scaffolding for OverviewResourcePane

---

scripts/install.sh

(as always, my bash is slapdash, so lmk what i missed)

scripts: install script calls brew upgrade if tilt is already installed via brew

---

web/src/SidebarItemView.stories.tsx
web/src/SidebarItemView.tsx
web/src/SidebarResources.test.tsx
web/src/SidebarResources.tsx
web/src/SidebarTriggerButton.test.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Hello @nicks,
Please review the following commits I made in branch nicks/sidebaritemview:
db9c1949bc5ba6a1f8a31181647957b201858361 (2020-12-14 19:45:54 -0500)
web: refactor SidebarItemView into a separate file

web: refactor SidebarItemView into a separate file

---

web/src/OverviewGrid.stories.tsx
web/src/OverviewGrid.test.tsx
web/src/OverviewGrid.tsx
web/src/OverviewItemView.stories.tsx
web/src/OverviewItemView.tsx
web/src/OverviewPane.stories.tsx
web/src/testdata.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10493:
8490b27a2db3c2a5b293ee32b5ca47bec76135f0 (2020-12-15 12:37:16 -0500)
web: fork SidebarItemView into OverviewItemView

web: fork SidebarItemView into OverviewItemView

---

web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx

Please review the following commits I made in branch nicks/issue4002:
de80bfc25f638999a90adff6189689fd5c42aa06 (2020-12-15 19:06:44 -0500)
web: clicking SidebarTriggerButton shouldn't navigate. Fixes https://github.com/tilt-dev/tilt/issues/4002

web: clicking SidebarTriggerButton shouldn't navigate. Fixes https://github.com/tilt-dev/tilt/issues/4002

---

scripts/install.sh

Please review the following commits I made in branch nicks/issue4000:
6ef0aeca21229a4b2cc1b40f3a5acd9f5c931df9 (2020-12-15 18:01:22 -0500)
scripts: update the install script to warn if brew tilt conflicts with another tilt

scripts: update the install script to warn if brew tilt conflicts with another tilt

---

web/src/OverviewResourcePane.stories.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewResourceSidebar.stories.tsx
web/src/OverviewResourceSidebar.test.tsx
web/src/OverviewResourceSidebar.tsx
web/src/OverviewStatusBar.tsx
web/src/OverviewTabBar.tsx
web/src/SidebarItemView.tsx
web/src/SidebarResources.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/types.ts

Hello @hyu,
Please review the following commits I made in branch nicks/ch10495:
27501e2f29abc5759d2624dfaf15f4a7e6672263 (2020-12-17 12:05:32 -0500)
web: Add the resource sidebar to the resource overview page

web: Add the resource sidebar to the resource overview page

---

README.md
SECURITY.md

Hello @victorwuky,
Please review the following commits I made in branch nicks/security:
b1d54f2b81be23e91d60db165594c64e1e6741f6 (2020-12-18 10:08:43 -0500)
docs: Add a security policy

docs: Add a security policy

---

web/src/OverviewItemView.tsx
web/src/SidebarTriggerButton.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/overviewitempopoverattach:
41cc649000064b2874442abd262c9a84ded4a58a (2020-12-16 18:42:21 -0500)
web: attach the overview item popover
a6b96c6c92d363cda96586fb8e20a00933bd9af9 (2020-12-16 18:10:55 -0500)
web: add the overview item popover

web: attach the overview item popover

---

web/src/OverviewItemView.tsx
web/src/Tooltip.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/styles:
d58395bf7dd42cdc20d064821e4a9e3a8592166a (2020-12-18 17:10:01 -0500)
web: use the makeStyles API correctly

web: use the makeStyles API correctly

---

internal/k8s/env.go
internal/k8s/env_test.go

Please review the following commits I made in branch nicks/k3d:
c2dcac1c65732f409c37a91cc42b0d7c5f9c6883 (2020-12-18 17:20:01 -0500)
k8s: improve k3d detection. Fixes https://github.com/tilt-dev/tilt/issues/4020

k8s: improve k3d detection. Fixes https://github.com/tilt-dev/tilt/issues/4020

---

web/src/LocalStorage.tsx
web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewResourceSidebar.tsx
web/src/OverviewTabBar.stories.tsx
web/src/OverviewTabBar.test.tsx
web/src/OverviewTabBar.tsx

Please review the following commits I made in branch nicks/tabs:
4628c310f37a7d9a3d0f5c55a652e77830f89991 (2020-12-21 18:45:20 -0500)
web: Add semantics for the overview tab bar

web: Add semantics for the overview tab bar

---

web/.storybook/main.js
web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/storybook-controls:
330d5ee2f33401ce3ea180bfe460eb91d96a8c1e (2020-12-23 15:50:21 -0500)
test: add storybook controls

test: add storybook controls

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/macos:
c9a77deec4aff89526c28c3fe6ee7ed47007fed7 (2021-01-04 11:07:06 -0500)
circleci: update macos

circleci: update macos

---

web/src/HUD.tsx
web/src/OverviewPane.tsx
web/src/OverviewResourceBar.test.tsx
web/src/OverviewResourceBar.tsx
web/src/snapshot.ts

Hello @hyu,
Please review the following commits I made in branch nicks/snapshot:
a8d95e2bb6e9b98386611aac2e9f2b0cceeb5203 (2021-01-04 19:28:40 -0500)
web: add snapshot button to new overview

web: add snapshot button to new overview

---

web/src/OverviewLogPane.stories.tsx
web/src/OverviewLogPane.tsx
web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.stories.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/logpane4:
7fb32428927e53deac16f34b2d29122851271005 (2021-01-04 17:38:26 -0500)
web: incrementally render logs
352c95d91149df871ab5ea199ae1773e34ab0828 (2021-01-04 17:00:22 -0500)
web: add an api for incremental logs to the LogStore
bfcaac24fb4fc051e454dbc106447cccf77a86e9 (2021-01-04 13:13:54 -0500)
web: redraw the OverviewLogPane when new logs come in

web: incrementally render logs

---

web/src/LogStore.test.ts
web/src/LogStore.ts
web/src/OverviewLogPane.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/incremental:
8e2894a44fda46d5e13ea66c1f4e729d5420f91b (2021-01-05 15:53:46 -0500)
web: fix some minor log rendering bugs

web: fix some minor log rendering bugs

---

internal/docker/client.go

Please review the following commits I made in branch nicks/creds:
2e7c6fa0c592f5b4895de06bf52a28b179cc4333 (2021-01-04 18:25:21 -0500)
docker: always use one-time sessions with buildkit. Fixes https://github.com/tilt-dev/tilt/issues/4043

docker: always use one-time sessions with buildkit. Fixes https://github.com/tilt-dev/tilt/issues/4043

---

internal/hud/server/server_test.go

it'll be helpful with my upcoming PR, and also refactoring/prettifying tests is soothing

server: streamline hud server tests

---

web/src/FloatDialog.tsx
web/src/OverviewItemView.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10601:
2f5c0cb72aaa0c7c642d9ac1fde8e368044f748b (2021-01-05 11:53:11 -0500)
web: polish the popover interaction

web: polish the popover interaction

---

web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewResourceSidebar.tsx
web/src/SidebarItemView.stories.tsx
web/src/SidebarItemView.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/SidebarKeyboardShortcuts.tsx
web/src/SidebarResources.tsx
web/src/SidebarTriggerButton.test.tsx
web/src/logs.ts
web/src/types.ts

Hello @hyu,
Please review the following commits I made in branch nicks/sidebar:
5ee5529efcd453e02ed2a7370541f1760c33d4be (2021-01-05 15:13:41 -0500)
web: fix some bugs in sidebar navigation. /r/(all)/overview now points to the 'all' details

web: fix some bugs in sidebar navigation. /r/(all)/overview now points to the 'all' details

---

web/src/OverviewLogPane.stories.tsx
web/src/OverviewLogPane.test.tsx
web/src/OverviewLogPane.tsx
web/src/OverviewResourcePane.stories.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/pairing2:
7a194d2026a4ccf344f4b27c876bca6e5a4221ab (2021-01-06 16:56:04 -0500)
web: add an api for filtering build logs and run logs

web: add an api for filtering build logs and run logs

---

internal/tiltfile/docker.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch10675:
b1bc3419368c5180a293e8ce9c68f1befc649a93 (2021-01-08 14:28:30 -0500)
tiltfile: fix name of custom_build(command_bat). Fixes https://github.com/tilt-dev/tilt/issues/4061

tiltfile: fix name of custom_build(command_bat). Fixes https://github.com/tilt-dev/tilt/issues/4061

---

web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/InterfaceVersion.tsx
web/src/OverviewResourceBar.tsx
web/src/SidebarAccount.tsx
web/src/UpdateDialog.stories.tsx
web/src/UpdateDialog.tsx
web/src/analytics.ts
web/src/index.scss
web/src/index.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10712:
a7b362d4d6dfcded2a468f57e7791efa7e874bb8 (2021-01-11 20:11:49 -0500)
web: Add a button to opt into the new UX
55105dab830a7913de1fe505daf1ba2c775f1f8b (2021-01-11 20:07:26 -0500)
web: add an update dialog. Also fixes https://github.com/tilt-dev/tilt/issues/3844 while I'm here

web: Add a button to opt into the new UX

---

web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.stories.tsx
web/src/OverviewResourceSidebar.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/sidebar2:
f8330acb99a1f0fe25cae03cb0f5a808475431c8 (2021-01-12 11:43:23 -0500)
web: make the sidebar fixed width

web: make the sidebar fixed width

---

web/src/OverviewResourceBar.stories.tsx
web/src/OverviewResourceBar.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/alignment:
dde15cdd17d734527408ceed45f0f802c7627534 (2021-01-13 11:57:08 -0500)
web: update the overview resource bar to display errors and warnings

web: update the overview resource bar to display errors and warnings

---

web/src/OverviewResourceBar.tsx
web/src/style-helpers.ts

Hello @hyu,
Please review the following commits I made in branch nicks/hover:
bca1c39be546727ce940c8a1c301f21091802e09 (2021-01-13 15:40:24 -0500)
web: add hover behavior to overview buttons

web: add hover behavior to overview buttons

---

web/src/OverviewPane.tsx
web/src/OverviewResourceBar.tsx
web/src/OverviewResourceDetails.stories.tsx
web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.test.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewTabBar.stories.tsx
web/src/OverviewTabBar.test.tsx
web/src/OverviewTabBar.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/notfound:
ede2b63a7116ab778fae2cafd848d00afda50304 (2021-01-14 12:30:32 -0500)
web: render correctly when the resource is not found

web: render correctly when the resource is not found

---

web/src/OverviewLogPane.stories.tsx
web/src/OverviewLogPane.test.tsx
web/src/OverviewLogPane.tsx
web/src/raf.tsx

Please review the following commits I made in branch nicks/raf:
3a99f7145eaf09a756a7ec3ccb2d2f7cf704303a (2021-01-15 15:40:44 -0500)
web: fixtures and async behavior for the log pane
Add the ability to inject our own asynchonous logic into the log pane,
so we can test it manually.

web: fixtures and async behavior for the log pane

---

web/src/OverviewResourceDetails.stories.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/errors:
e90040ccd63eb8886c0b1ec8ac91bac861bf606c (2021-01-15 17:19:17 -0500)
web: fix up a typescript error in the storybook

web: fix up a typescript error in the storybook

---

README.md

Last week, different people in #tilt didn't seem aware of Tilt Extensions related to their issues. Let's talk up Extensions in our docs more!

docs: add info about Tilt Extensions

---

web/src/OverviewPane.tsx

Please review the following commits I made in branch maiamcc/tests-section-label:
ddcbfb7ec0420fe722693a544e601af284dd09d8 (2021-01-20 17:11:56 -0500)
ui: fix label on tests section

ui: fix label on tests section

---

web/src/OverviewLogPane.stories.tsx
web/src/OverviewLogPane.test.tsx
web/src/OverviewLogPane.tsx
web/src/testlogs.tsx

Please review the following commits I made in branch nicks/ch10779:
6d58e787fb576756bbe31262eec89f74ec6bec9a (2021-01-15 17:14:27 -0500)
web: incremental line rendering
navigating to a pane with a lot of logs was still feeling a bit sluggish
This performs well even when you get up to 1,000,000+ lines,
so should hold up for a while.

web: incremental line rendering

---

web/src/HUDLayout.tsx
web/src/OverviewPane.tsx
web/src/OverviewResourcePane.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/overflow:
448e11ac671d9014a7eefd74557ac69d5ddcba93 (2021-01-19 20:07:03 -0500)
web: fix scrollbars in new interface

web: fix scrollbars in new interface

---

web/src/SidebarItemView.tsx
web/src/TabNav.test.tsx
web/src/TabNav.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Please review the following commits I made in branch nicks/ch10895:
4511410a1718234d6243f5f65bd2f263d2d87ec1 (2021-01-21 12:05:38 -0500)
web: change open-new-tab to ctrl-click

web: change open-new-tab to ctrl-click

---

web/src/OverviewActionBar.stories.tsx
web/src/OverviewActionBar.tsx
web/src/OverviewResourceDetails.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/actionbar:
38562fffda6172e096dd391451637dbee5c31372 (2021-01-22 12:58:48 -0500)
web: split the OverviewActionBar into its own component

web: split the OverviewActionBar into its own component

---

scripts/release-update-tilt-docs-repo.sh

good catch by @jazzdan in https://github.com/tilt-dev/tilt.build/pull/801/ !

release: update asdf version numbers in upgrade.md too

---

web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/icons:
1eb07182a93b0e62a76c5319f415a57367c534a5 (2021-01-22 19:33:49 -0500)
web: add material-ui icons

web: add material-ui icons

---

web/src/OverviewActionBar.stories.tsx
web/src/OverviewActionBar.tsx
web/src/OverviewResourceDetails.tsx
web/src/logfilters.ts

Hello @hyu,
Please review the following commits I made in branch nicks/ch10829:
a684ac249148e4db422745ff40fb6db3f741f767 (2021-01-22 17:35:34 -0500)
web: add buttons for warnings and errors
4055d566875b21ee1e150b098cdd9b0b11a83f82 (2021-01-22 16:09:07 -0500)
web: infer log filters from the url

web: add buttons for warnings and errors

---

web/src/HUD.tsx
web/src/OverviewResourcePane.stories.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewTabBar.tsx
web/src/SidebarItemView.tsx
web/src/SidebarKeyboardShortcuts.test.tsx
web/src/SidebarKeyboardShortcuts.tsx
web/src/SidebarResources.tsx
web/src/TabNav.tsx

Please review the following commits I made in branch nicks/ch10950:
b846d99e687d82143cac3ef42846370d69812d98 (2021-01-25 12:23:51 -0500)
web: update j/k keyboard shortcuts to match tab navigation

web: update j/k keyboard shortcuts to match tab navigation

---

web/src/OverviewActionBar.test.tsx
web/src/OverviewActionBar.tsx
web/src/OverviewLogPane.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10577:
ebd9a538f086fe94a8bb61e9eb8cd5356aae8bbe (2021-01-22 20:38:09 -0500)
web: add buttons for build and runtime logs. Fixes https://github.com/tilt-dev/tilt/issues/2947
09578ec09b9b55c093bc42eddfdab4cc49f0ec7c (2021-01-22 20:33:42 -0500)
web: add buttons for warnings and errors

web: add buttons for build and runtime logs. Fixes https://github.com/tilt-dev/tilt/issues/2947

---

web/src/OverviewTabBar.tsx
web/src/TabNav.test.tsx
web/src/TabNav.tsx

Please review the following commits I made in branch nicks/ch10951:
70b907b1d8c1092207bea2023f105c4777e20166 (2021-01-25 19:31:08 -0500)
web: add an All Resources tab by default

web: add an All Resources tab by default

---

web/src/OverviewItemView.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch10953:
c6e5cfd1a48f792efb08fce50a378c22d3957726 (2021-01-26 11:16:42 -0500)
web: make the 'View Details' button bold

web: make the 'View Details' button bold

---

web/src/InterfaceVersion.tsx
web/src/UpdateDialog.tsx

Hello @hyu, @victorwuky,
Please review the following commits I made in branch nicks/ch10827/new-ui:
971e7a5872f8f8511fe31e82fe2440aac14f3366 (2021-01-26 18:31:30 -0500)
web: make the default ui the new ui

web: make the default ui the new ui

---

web/src/HUD.tsx
web/src/analytics.test.ts
web/src/analytics.ts

Please review the following commits I made in branch nicks/ch11008:
bf20db4a7adc5206047bb4d64e9727aa3f3a077b (2021-01-26 17:45:02 -0500)
web: add analytics for level/source filters

web: add analytics for level/source filters

---

web/src/OverviewActionBar.tsx
web/src/OverviewResourceBar.tsx
web/src/OverviewResourceDetails.tsx
web/src/OverviewResourcePane.tsx
web/src/alerts.test.ts
web/src/alerts.ts

Hello @hyu,
Please review the following commits I made in branch nicks/ch11011:
7302ea2845620004029acb58b303fa6aa621d4ed (2021-01-27 14:44:18 -0500)
web: add counts to error and warning pickers

web: add counts to error and warning pickers

---

web/src/ButtonMixin.ts

Hello @hyu,
Please review the following commits I made in branch nicks/ch10954:
a39608c9e7e4603c456e948051c9c2e27572bf2b (2021-01-28 14:23:01 -0500)
web: update button colors

web: update button colors

---

web/src/OverviewResourceSidebar.stories.tsx
web/src/OverviewSidebarOptions.test.tsx

Please review the following commits I made in branch maiamcc/more-sidebar-tests:
a970564bd34d2c0ebee77397ecb0291c9bda02b7 (2021-01-28 16:30:42 -0500)
web ui/sidebar: another test, storybook entry

web ui/sidebar: another test, storybook entry

---

.circleci/Dockerfile.integration
.circleci/config.yml
scripts/tilt.Dockerfile

Hello @nicks,
Please review the following commits I made in branch nicks/kind10:
bda956043fabf0dbc75eaa9d1fc1a2a5c2231561 (2021-01-29 19:16:56 -0500)
test: update integration tests to use kind v0.10

test: update integration tests to use kind v0.10

---

web/src/OverviewResourceSidebar.stories.tsx
web/src/OverviewSidebarOptions.tsx
web/src/SidebarResources.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/style-helpers.ts
web/src/types.ts

Please review the following commits I made in branch maiamcc/alerts-on-top:
04941bd1ea3121cfbbe44178264227242043b1d6 (2021-01-29 14:52:59 -0500)
storybook entry for tests with errors
f92bff4822d87502ec87c536fc494bcc65dc6013 (2021-01-29 13:58:16 -0500)
behavior implemented (needs tests)

ui / sidebar: "alerts on top" toggle (tests, styling tk) [ch10933]

---

web/src/SidebarItemView.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

web: fix sidebar items widths

---

.circleci/Dockerfile
.circleci/config.yml

Hello @nicks,
ecaaee7907c87ccd255c90f58797a4c85acc4da0 (2021-02-04 15:08:22 -0500)
circleci: upgrade some deps

circleci: upgrade some deps

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/size:
6c17c82cb2ba7bbbab44814b9bd865cfe4b5bb8d (2021-02-05 13:10:20 -0500)
test: bump up machine size a bit to see if that fixes linter problems

test: bump up machine size a bit to see if that fixes linter problems

---

web/src/SidebarResources.test.tsx

this was supposed to be in #4157

web: sidebar tests: default alertsOnTop to false

---

web/src/OverviewSidebarOptions.test.tsx

Please review the following commits I made in branch maiamcc/alerts-on-top-tests:
a989a2b4402e39932e121dfc54d597da563ef900 (2021-02-08 18:02:27 -0500)
ui: tests for AlertsOnTop toggle [ch11068]

ui: tests for AlertsOnTop toggle [ch11068]

---

.circleci/config.yml

Hello @nicks,
6f45548f0869c66ed725873ddf2a2af19c1da21b (2021-02-15 13:26:15 -0500)
test: change CI messages

test: change CI messages

---

.golangci.yml
cmd/tilt/main.go
integration/dc_fixture_test.go
integration/k8s_fixture_test.go
internal/build/docker_builder_test.go
internal/build/test_utils.go
internal/docker/client.go
internal/engine/image_build_and_deployer_test.go
internal/engine/runtimelog/podlogmanager.go
internal/engine/telemetry/controller_test.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/hud/fake_hud.go
internal/hud/server/controller.go
internal/hud/server/logs_reader_test.go
internal/hud/server/server.go
internal/k8s/client_test.go
internal/k8s/fake_client.go
internal/k8s/label.go
internal/testutils/podbuilder/podbuilder.go
internal/tiltfile/k8s.go
internal/tiltfile/k8s/locators.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/unused:
a103036104c317345ffd565e6aec2485f9bb18dd (2021-02-16 14:36:59 -0500)
test: enable unused check, remove dead code

test: enable unused check, remove dead code

---

web/src/LogPaneLine.scss
web/src/LogPaneLine.tsx
web/src/OverviewLogPane.stories.tsx
web/src/OverviewLogPane.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/overflow:
ac94f3abb6cb3784130303d1e09e9b5680bb3a1e (2021-02-16 17:19:35 -0500)
web: fix overflow on build fallback lines

web: fix overflow on build fallback lines

---

web/src/OverviewItemView.tsx

Hello @hyu,
Please review the following commits I made in branch maiamcc/test-local-copy:
caa6638d036a6d87e3be09fe84ab0a55ba14e2d5 (2021-02-16 12:10:57 -0500)
ui/overview: don't bother specifying tests as 'local' for now

ui/overview: don't bother specifying tests as 'local' for now

---

web/src/TabNav.test.tsx
web/src/TabNav.tsx

Please review the following commits I made in branch nicks/tabs:
9dc650e9a6bb27bf3886caed539abbfd1bef68f7 (2021-02-17 11:37:55 -0500)
web: filter out tabs that aren't in the resource list anymore

web: filter out tabs that aren't in the resource list anymore

---

web/src/LogStore.test.ts
web/src/LogStore.ts
web/src/OverviewLogPane.tsx

Please review the following commits I made in branch nicks/ch11368:
d6ccd62f5ed7fe8cd531fe1f683105200953d1c7 (2021-02-17 16:20:33 -0500)
web: client-side log truncation
Fixes https://github.com/tilt-dev/tilt/issues/4196

web: client-side log truncation

---

web/src/UpdateDialog.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/old-ui:
84d83cc05f10f246d84cb180bd7308a87b5eb9e4 (2021-02-18 15:59:36 -0500)
web: remove old UI/new UI switch

web: remove old UI/new UI switch

---

internal/tiltfile/tiltextension/extension.go
internal/tiltfile/tiltfile.go

here's a much cleaner version of #4226, tests tk but wanted to put something up before the weekend and get eyes on it.

tiltfile: send analytics on extensions loaded (take 2)

---

.golangci.yml
Makefile
internal/container/reference_test.go
internal/tiltfile/starkit/environment.go
internal/tiltfile/tiltfile_state.go
pkg/assets/prod_test.go
pkg/clientset/tiltapi/typed/core/v1alpha1/fake/fake_filewatch.go
pkg/clientset/tiltapi/typed/core/v1alpha1/filewatch.go
pkg/informers/externalversions/core/v1alpha1/filewatch.go
pkg/listers/core/v1alpha1/filewatch.go
pkg/model/manifest_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/goimports:
fabc1da5ac127b9e5e99b4e56d78858d463997ba (2021-02-23 12:01:13 -0500)
lint: run goimports, remove dead code

lint: run goimports, remove dead code

---

internal/cli/wire_gen.go
internal/engine/dockerprune/docker_pruner.go
internal/engine/subscribers.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/server/controller.go
internal/hud/server/websocket.go
internal/hud/server/websocket_test.go
internal/store/helpers_test.go
internal/store/store.go
internal/store/store_test.go
internal/store/subscriber.go
internal/store/subscriber_test.go

Hello @milas,
Please review the following commits I made in branch nicks/setup:
6b39af73253c133d7008e599d197d1dd8a8b7620 (2021-02-23 12:28:19 -0500)
server: make sure the API server boots first
f996027564f93d1694546cfc2dcd3aece498de49 (2021-02-23 12:19:02 -0500)
lint: run goimports, remove dead code

server: make sure the API server boots first

---

internal/cli/wire_gen.go
internal/hud/server/apiserver.go
internal/hud/server/apiserver_test.go
internal/hud/server/controller.go
internal/hud/server/wire.go

Hello @milas, @ellenkorbes,
b7013ec86cbf34fc0e1df85936804c2137f803f5 (2021-02-24 20:00:48 -0500)
server: demonstrate tilt API clients and add tests

server: demonstrate tilt API clients and add tests

---

go.mod
go.sum
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/apiserver/ext.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/builder/builder_resource.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile_rest.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/strategy.go
vendor/modules.txt

Hello @nicks,
b96b94712951630321dd936a2b7850c0f909fe6a (2021-02-26 12:42:50 -0500)
vendor: update tilt-apiserver

vendor: update tilt-apiserver

---

internal/tiltfile/tiltextension/extension.go
internal/tiltfile/tiltextension/extension_test.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch maiamcc/extensions-metric-test:
0dc44c453a2c7e1bc9489d501887659389c6bb1a (2021-02-26 12:18:43 -0500)
tiltfile: tests for extensions analytics [ch11447]

tiltfile: tests for extensions analytics [ch11447]

---

web/src/OverviewItemView.tsx
web/src/OverviewLogPane.tsx
web/src/OverviewTabBar.tsx
web/src/PathBuilder.tsx
web/src/TabNav.tsx
web/src/trace.test.ts
web/src/trace.ts
web/storybook.tiltfile

Please review the following commits I made in branch nicks/ch11484:
e15dfd38040bdb7c52c3e7b50af38f9fe108be45 (2021-03-01 15:29:49 -0500)
web: use template strings to encode URIs

web: use template strings to encode URIs

---

internal/hud/server/controller.go
internal/hud/server/serving.go

Hello @milas,
Please review the following commits I made in branch nicks/ch11472:
ba0016ebda5cc5435557770308bfb99a2641883f (2021-03-02 11:19:17 -0500)
server: speed up shutdown, and get rid of unnecessarily logging

server: speed up shutdown, and get rid of unnecessarily logging

---

internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

@nicks is this all that's needed? (I would verify but idk how to force a data migration job--would be happy to learn if you have time to show me.)

tiltfile: change tag key for extensions metric so our analytics system imports it correctly [ch11508]

---

internal/engine/pod.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch11536:
1495a42b9030d26836717997631940ba399a804b (2021-03-08 12:47:30 -0500)
engine: print container restart

engine: print container restart

---

internal/cli/wire_gen.go
internal/controllers/client_builder.go
internal/controllers/client_deferred.go
internal/controllers/fake/fake.go
internal/controllers/manager.go
internal/controllers/wire.go
internal/engine/local/controller.go
internal/engine/local/controller_test.go
internal/engine/upper_test.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go

Hello @milas,
Please review the following commits I made in branch nicks/clientinit:
8c09e5fbec567737e3a427a4432bac94af6297ff (2021-03-09 16:23:27 -0500)
server: alternate DI hack using deferred client

server: alternate DI hack using deferred client

---

.circleci/config.yml
Makefile
internal/cli/up.go
scripts/test-extensions.sh

Please review the following commits I made in branch nicks/extensiong:
8b52b9164442dcdb8b0f4883a13b34870419f759 (2021-03-08 16:08:54 -0500)
test: add extension tests to our integration test suite

test: add extension tests to our integration test suite

---

web/src/TabNav.test.tsx
web/src/TabNav.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/ch11483:
2d4a202ba84e9ec3958635053b76149f585475da (2021-03-01 15:10:54 -0500)
web: fix a bug in the 'All Resources' tab appearing

web: fix a bug in the 'All Resources' tab appearing

---

internal/store/subscriber.go
internal/store/subscriber_test.go
internal/store/summary.go

Hello @milas,
Please review the following commits I made in branch nicks/summary:
23e7bda02afe625b5751f3cc3ded1c2d40b58331 (2021-03-11 15:52:31 -0500)
store: merge ChangeSummaries when notify() calls are merged

store: merge ChangeSummaries when notify() calls are merged

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/controllers/core/cmd/controller.go
internal/controllers/core/cmd/controller_test.go
internal/controllers/core/cmd/execer.go
internal/controllers/core/cmd/execer_test.go
internal/controllers/core/cmd/probe.go
internal/controllers/core/cmd/probe_fake.go
internal/controllers/core/cmd/probe_test.go
internal/controllers/core/cmd/types.go
internal/controllers/core/cmd/wire.go
internal/controllers/wire.go
internal/engine/local/servercontroller.go
internal/engine/subscribers.go
internal/engine/upper_test.go

Hello @milas,
Please review the following commits I made in branch nicks/move:
42f3112f3254f53baaf429ee533032aebc58dd1a (2021-03-12 13:15:21 -0500)
cmd: move Cmd controller into the controllers package

cmd: move Cmd controller into the controllers package

---

web/storybook.tiltfile

Align with new validation in #4319.

web: use valid names in Tiltfile

---

.circleci/Dockerfile.integration
.circleci/config.yml
scripts/tilt.Dockerfile

Please review the following commits I made in branch nicks/ci:
ad23daf14d602c1ea2eae551d6fc0f84af67145a (2021-03-16 16:53:38 -0400)
test: use ctlptl for integration testing

test: use ctlptl for integration testing

---

internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/overridetrigger:
6beb3db342b11846e4e7ac8d8e3fe9211c8b403a (2021-03-17 15:36:18 -0400)
test: increase timeout on some tests

test: increase timeout on some tests

---

go.mod
go.sum
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/builder/builder_resource.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile_rest.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/watchset.go
vendor/modules.txt

Hello @nicks,
55db62ea527227c4f3316b7e37dc6e6448e4195f (2021-03-19 11:19:11 -0400)
vendor: pull in apiserver fixes

vendor: pull in apiserver fixes

---

internal/cli/updog-examples/hello-world.yaml
internal/controllers/core/cmd/restartmanager.go
pkg/apis/core/v1alpha1/cmd_types.go
pkg/openapi/zz_generated.openapi.go

Hello @milas,
Please review the following commits I made in branch nicks/ch11574:
3aae74eb0fa1f5a35bcc1e2cfe1f22f6325dbdd5 (2021-03-19 12:21:39 -0400)
examples: hello-world with the new apiserver

examples: hello-world with the new apiserver

---

internal/cli/visitor/decode.go
internal/cli/visitor/decode_test.go

Please review the following commits I made in branch nicks/yaml:
9628fd659212032baed3145386119646e0621942 (2021-03-19 13:16:08 -0400)
visitor: more strict object parsing

visitor: more strict object parsing

---

README.md

Hello @hyu,
Please review the following commits I made in branch nicks/ux-research:
6bc0098670a3bdc156500870e6d174b2823c5aed (2021-03-19 14:57:39 -0400)
readme: add a link to schedule a UX research session

readme: add a link to schedule a UX research session

---

scripts/update-codegen-helper.sh
scripts/update-codegen.sh

Hello @nicks,
Please review the following commits I made in branch nicks/chown:
d14451aff0bb61833a56001eb45223ef81aebaed (2021-03-19 16:16:36 -0400)
scripts: set permissions on codegen files

scripts: set permissions on codegen files

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/ci2:
5489ea8591c79804d5bd4983daaea95b8f4a426d (2021-03-22 13:25:56 -0400)
test: use ctlptl in extensions ci

test: use ctlptl in extensions ci

---

internal/controllers/core/cmd/controller_test.go
internal/engine/local/servercontroller.go

Please review the following commits I made in branch nicks/orphans:
2f49289dd575d4ea77bcd78f1e27df0920c5be6d (2021-03-22 16:22:21 -0400)
local: kill servers when their manifest is removed

local: kill servers when their manifest is removed

---

internal/controllers/core/cmd/controller_test.go
internal/engine/fswatch/action.go
internal/engine/local/actions.go
internal/store/subscriber_test.go
internal/store/summary.go

Please review the following commits I made in branch nicks/summary:
a5863f724d2cdbbf74728e5d2c718d4d243d0aae (2021-03-23 16:02:21 -0400)
store: simplify the summary api a bit

store: simplify the summary api a bit

---

internal/tiltfile/starkit/environment.go
internal/tiltfile/starkit/environment_test.go
internal/tiltfile/tiltfile.go

Please review the following commits I made in branch nicks/ch11721:
185decce92cd9e54bfdd7ac240e2561d70ece96e (2021-03-25 17:15:24 -0400)
tiltfile: add the set() built-in. Fixes https://github.com/tilt-dev/tilt/issues/3773

tiltfile: add the set() built-in. Fixes https://github.com/tilt-dev/tilt/issues/3773

---

internal/engine/upper_test.go

Hello @nicks,
38a5ba31a593c9d2e50fe834c852d32f9a844ad3 (2021-03-26 13:44:32 -0400)
test: turn off a flakey test on windows

test: turn off a flakey test on windows

---

internal/controllers/core/filewatch/controller.go
internal/engine/fswatch/manifest_subscriber.go
internal/engine/fswatch/manifest_subscriber_test.go

Please review the following commits I made in branch nicks/ch11722:
0eac967e3fdd7e969ce6f5e8bf6dd674d848839d (2021-03-26 12:11:49 -0400)
filewatch: fix a missing ignore. Fixes https://github.com/tilt-dev/tilt/issues/4370

filewatch: fix a missing ignore. Fixes https://github.com/tilt-dev/tilt/issues/4370

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/cache:
a04b530daa61a689c0ab0f9a78d9ade2151ef772 (2021-03-26 17:12:15 -0400)
test: bump homebrew cache and xcode version

test: bump homebrew cache and xcode version

---

web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/deps:
7f46737b3352a625666b9b3d9bcce5c7434f0467 (2021-03-29 18:23:30 -0400)
web: upgrade dependencies

web: upgrade dependencies

---

internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go

Please review the following commits I made in branch nicks/ch11744:
ffdfac4d61077c24858bad08063a89b4dd86edf4 (2021-03-29 17:39:28 -0400)
engine: don't delete namespaces on force reload. Fixes https://github.com/tilt-dev/tilt/issues/4377

engine: don't delete namespaces on force reload. Fixes https://github.com/tilt-dev/tilt/issues/4377

---

go.mod
go.sum
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile_rest.go
vendor/modules.txt

Hello @nicks,
41e399d222fca34b68f1ad0cd4e7f3f00487f1dd (2021-04-05 11:43:55 -0400)
vendor: update apiserver

vendor: update apiserver

---

internal/engine/runtimelog/podlogmanager_test.go
internal/engine/runtimelog/podlogstreamcontroller.go

08abb7fa9960a0a72b3ae2303650bdd70407d878 (2021-04-05 18:11:06 -0400)
test: fix a flaky podlogstream test
I think this is a good example of how having a public status
field will make this a bit easier to test in general

test: fix a flaky podlogstream test

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go
internal/hud/server/controller.go

Hello @nicks,
Please review the following commits I made in branch nicks/teardown:
0cdf20bee5b72e30fd8a8308b45b880044f6d6f6 (2021-04-09 15:20:01 -0400)
test: optimize engine tests a bit

test: optimize engine tests a bit

---

internal/cli/client/config.go
internal/cli/client/getter.go
internal/cli/client/wire.go
internal/cli/flags.go
internal/cli/updog_get.go
internal/cli/updog_get_test.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/upper_test.go
internal/hud/server/apiserver.go
internal/hud/server/apiserver_test.go
internal/hud/server/controller.go
internal/hud/server/token.go
internal/hud/server/wire.go
pkg/model/api.go
pkg/model/web.go

Hello @milas,
Please review the following commits I made in branch nicks/ch11849:
9cd33d880a4eaca9c437e35ac33e6f5f652d5abb (2021-04-13 09:42:33 -0400)
cli: use the k8s cli infrastucture to setup 'tilt alpha get'

cli: use the k8s cli infrastucture to setup 'tilt alpha get'

---

internal/controllers/fake/client.go
internal/controllers/fake/fake.go
internal/engine/session/controller.go
internal/engine/session/controller_test.go

Hello @milas,
Please review the following commits I made in branch nicks/ch11871:
86d5057602802d5518b18919419851defaaa60e8 (2021-04-13 18:09:16 -0400)
session: fix a bug that led to infinite loops on linux

session: fix a bug that led to infinite loops on linux

---

.golangci.yml
internal/cli/alpha.go
internal/cli/edit.go
internal/cli/edit_test.go
vendor/k8s.io/kubectl/pkg/cmd/edit/edit.go
vendor/modules.txt

Please review the following commits I made in branch nicks/ch11869:
82db89809e23d2df8f3c4167fe96e111d962f29b (2021-04-14 13:00:18 -0400)
cli: add tilt alpha edit

cli: add tilt alpha edit

---

internal/cli/alpha.go
internal/cli/apply.go
internal/cli/apply_test.go

Please review the following commits I made in branch nicks/ch11865:
b26cb13b9e34a2b518ab7ac0b71cf61dd5fbff14 (2021-04-14 14:41:26 -0400)
cli: add tilt alpha apply

cli: add tilt alpha apply

---

internal/cli/dump.go
internal/cli/openapi.go

Hello @nicks,
Please review the following commits I made in branch nicks/swagger:
18c3dd42e50c3c03e60a3c06b8e7405c2579f654 (2021-04-15 11:00:18 -0400)
cli: add tilt dump openapi

cli: add tilt dump openapi

---

internal/cli/alpha.go
internal/cli/cli.go
internal/cli/create.go
internal/cli/create_cmd.go
internal/cli/create_filewatch.go
internal/cli/get.go
internal/cli/get_test.go

Hello @milas,
Please review the following commits I made in branch nicks/ch11868:
e5f7f240056cc07aea939d80b8bf888f8ffc41f1 (2021-04-16 17:02:24 -0400)
cli: GA of the tilt apiserver CLI

cli: GA of the tilt apiserver CLI

---

go.mod
go.sum
vendor/github.com/tilt-dev/fsnotify/.editorconfig
vendor/github.com/tilt-dev/fsnotify/.gitattributes
vendor/github.com/tilt-dev/fsnotify/.travis.yml
vendor/github.com/tilt-dev/fsnotify/LICENSE
vendor/github.com/tilt-dev/fsnotify/README.md
vendor/github.com/tilt-dev/fsnotify/fsnotify.go
vendor/github.com/tilt-dev/fsnotify/go.mod
vendor/github.com/tilt-dev/fsnotify/go.sum
vendor/github.com/tilt-dev/fsnotify/inotify.go
vendor/github.com/tilt-dev/fsnotify/inotify_poller.go
vendor/github.com/tilt-dev/fsnotify/open_mode_bsd.go
vendor/github.com/tilt-dev/fsnotify/open_mode_darwin.go
vendor/modules.txt

Hello @nicks,
bfbdf51ff186f1405d9a41a668c190f2e83c8394 (2021-04-20 13:56:24 -0400)
vendor: update fsnotify

vendor: update fsnotify

---

internal/controllers/core/cmd/controller_test.go
internal/engine/local/servercontroller.go

Please review the following commits I made in branch nicks/cmd-terminated:
454ea77342ffb2cc673cbefe2ed23269a9fba797 (2021-04-21 15:18:12 -0400)
cmd: fix a bug where terminated commands wouldn't get cleaned up
I'm not confident that this is what's causing https://github.com/tilt-dev/tilt/issues/4455
But this definitely does create weird behavior in the data model,
and should be fixed regardless.

cmd: fix a bug where terminated commands wouldn't get cleaned up

---

internal/hud/server/logs_reader.go
internal/hud/server/logs_reader_test.go

The client was using server checkpoint values to determine which
logs to print. These values aren't portable across `LogStore`s due
to truncation: internally an offset is used to find the right index
as the checkpoint value is monotonically increasing.
Instead, we can use the server value purely as a watermark for
filtering out duplicates, but use local checkpoints to determine
what logs to print / have been printed.
The CLI logs command uses the same `LogStore` implementation but
populates it with the values it receives over the WS connection.
The API does _not_ expose this offset (nor should it), but as a
result, if the server has truncated before a client attaches, the
client will be trying to use offsetted checkpoint values without
knowing the correct offset.
The result is that, since …

cli: fix logs follow after server truncation

---

go.sum
internal/cli/describe.go
internal/cli/describe_test.go
vendor/github.com/fatih/camelcase/.travis.yml
vendor/github.com/fatih/camelcase/LICENSE.md
vendor/github.com/fatih/camelcase/README.md
vendor/github.com/fatih/camelcase/camelcase.go
vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go
vendor/k8s.io/kubectl/pkg/describe/describe.go
vendor/k8s.io/kubectl/pkg/describe/interface.go
vendor/k8s.io/kubectl/pkg/util/certificate/certificate.go
vendor/k8s.io/kubectl/pkg/util/deployment/deployment.go
vendor/k8s.io/kubectl/pkg/util/event/sorted_event_list.go
vendor/k8s.io/kubectl/pkg/util/fieldpath/fieldpath.go
vendor/k8s.io/kubectl/pkg/util/qos/qos.go
vendor/k8s.io/kubectl/pkg/util/rbac/rbac.go
vendor/k8s.io/kubectl/pkg/util/resource/resource.go
vendor/k8s.io/kubectl/pkg/util/slice/slice.go
vendor/k8s.io/kubectl/pkg/util/storage/storage.go
vendor/modules.txt

Please review the following commits I made in branch nicks/describe:
81e414db4c795aef890e164948bd2248f197af94 (2021-04-27 14:44:10 -0400)
cli: add 'tilt describe'

cli: add 'tilt describe'

---

internal/timecmp/cmp_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/timecmp:
5980b767a50271ab1dc091e65d25f0db74a73902 (2021-04-28 14:53:38 -0400)
test: fix a flakey test

test: fix a flakey test

---

internal/controllers/core/podlogstream/podlogstreamcontroller.go

Hello @milas,
Please review the following commits I made in branch nicks/update:
904588f5393c41a44b419dc1d86c260b80eae5b1 (2021-04-27 15:52:09 -0400)
podlogstream: fix an update loop

podlogstream: fix an update loop

---

web/src/HUD.tsx

Please review the following commits I made in branch nicks/ch11951:
e8b6bbd10ef94a3ef51a14a3a1350c4942ee583a (2021-04-28 15:42:49 -0400)
web: if tilt restarts, reload the page. fixes https://github.com/tilt-dev/tilt/issues/4421

web: if tilt restarts, reload the page. fixes https://github.com/tilt-dev/tilt/issues/4421

---

internal/engine/k8swatch/pod_watch_test.go
internal/store/k8sconv/pod_test.go

Missed the test when moving the logic, so just moving it to where
the actual code is.

test: move PodStatus test to k8sconv

---

scripts/update-codegen-helper.sh

Please review the following commits I made in branch nicks/ch11944:
60c3d23e7bdcf5b42b5acdaf581932dc764d00b0 (2021-04-29 19:39:19 -0400)
scripts: codegen should error on api rule violations
f1fc9ebe0445cbf788d7cd3b782c0002b0feba87 (2021-04-29 19:08:53 -0400)
apis: fix some api rule violations
- Go ints aren't allowed, they must be int32
- 2D arrays aren't allowed

scripts: codegen should error on api rule violations

---

internal/engine/k8swatch/pod_watch_test.go

Ensure that the changes from removing a manifest fully propagate
before moving on with the test. The selector check that was here
was insufficient because if the manifest had no extra selectors
(before deletion), it would immediately pass causing a race.

test: fix race condition in k8swatch

---

integration/local_resource/Tiltfile

Hello @nicks,
Please review the following commits I made in branch nicks/localresource:
1551e989c17838a451bfe7f765853a77df7ff16d (2021-05-03 18:53:22 -0400)
test: fix a bug in signal handling in the local_resource test

test: fix a bug in signal handling in the local_resource test

---

internal/engine/session/controller.go
internal/engine/upper_test.go
internal/hud/server/controller.go

Hello @milas,
0c46c6a668b5ae12396eaad412ad0ca24e9b2c74 (2021-05-03 18:15:27 -0400)
test: blackhole useless logs and fix a race condition

test: blackhole useless logs and fix a race condition

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go

See #4513 for the first big chunk of this. These were remaining
tests that used some different helper methods or dispatched stuff
directly themselves so made sense to split independently.
The only material change to a test here is for `TestPodEventOrdering`
which uses some newly exposed options on `PodBuilder` (from #4514)
to more accurately represent the data -- specifically, it ensures
that an old Pod looks like it would in reality: it has the same
name but a different UID. The latter part was missing before and is
critical to ensure the `PodWatcher` handles it correctly in terms
of linking to ancestor.

test: use PodWatcher in rest of upper_test tests

---

internal/k8s/fake_client.go

Probably went a bit overboard as I doubt many of these are
accessed concurrently, but just wanted to avoid race detector
errors.

test: avoid race conditions in FakeK8sClient

---

integration/crd_test.go
internal/k8s/client.go
internal/k8s/errors.go

Please review the following commits I made in branch nicks/ch11964:
f9b39faee7cbd2d1fb646917eecb18b923c4f579 (2021-05-05 19:25:21 -0400)
k8s: improved error handling for missing CRDs. fixes https://github.com/tilt-dev/tilt/issues/4519

k8s: improved error handling for missing CRDs. fixes https://github.com/tilt-dev/tilt/issues/4519

---

internal/testutils/podbuilder/podbuilder.go

Previously, all resources produced by PodBuilder had `default` as
the K8s namespace.
Now, it will examine the manifest YAML and try to find an explicitly
referenced namespace. If it finds more than one, it'll error out
(this is a safeguard - nothing trips it today; if ever hit, we can
add an _explicit_ namespace override to use since there is no sensible
default in those scenarios).
If it doesn't find a single explicit namespace, it'll fallback to a
"context" namespace value if set. This allows simulating the case
where you've got a non-default namespace set in `kubeconfig`. If
that is also not set, it'll fallback to `k8s.DefaultNamespace` (aka
`default`).
The "cluster namespace" has to always be passed to PodBuilder if
you want to use it because there's no practical way for PodBuilder
to …

test: namespace options in PodBuilder

---

integration/crd_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/testcrd:
80d7f5fe619cb49f4c3e26b64aba8ca1a962824d (2021-05-07 19:17:04 -0400)
test: add some extra verification to the crd test

test: add some extra verification to the crd test

---

internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/watch.go

Please review the following commits I made in branch nicks/ch11988:
6a3321f1716d4f742abe433837f77461e1592796 (2021-05-11 13:11:22 -0400)
k8s: more robust delete handling
fixes https://github.com/tilt-dev/tilt/issues/4542

k8s: more robust delete handling

---

go.mod
go.sum
internal/cli/apiresources_test.go
pkg/apis/core/v1alpha1/filewatch_types.go
pkg/apis/core/v1alpha1/podlogstream_types.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/builder/resource/resourcerest/doc.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/builder/resource/resourcerest/interface.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/builder/rest/strategy.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile_rest.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/strategy.go
vendor/modules.txt

Hello @milas,
Please review the following commits I made in branch nicks/shortnames:
bee777d665d3cfe81880c8e37f16f2d6776b7a49 (2021-05-18 10:07:07 -0400)
apis: add aliases. 'fw' for FileWatch. 'pls' for PodLogStream

apis: add aliases. 'fw' for FileWatch. 'pls' for PodLogStream

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/controllers/core/uiresource/reconciler.go
internal/controllers/core/uiresource/wire.go
internal/controllers/core/uisession/reconciler.go
internal/controllers/core/uisession/wire.go
internal/controllers/wire.go
internal/engine/buildcontrol/wire_gen.go
internal/engine/upper_test.go
internal/engine/wire_gen.go

Hello @milas,
Please review the following commits I made in branch nicks/uisession13:
5be2925bb4357e34840ff15a675de639c13d8001 (2021-05-20 16:22:11 -0400)
controllers: add uisession and uiresource reconcilers

controllers: add uisession and uiresource reconcilers

---

go.mod
go.sum
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile_rest.go
vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/watchset.go
vendor/modules.txt

Hello @nicks,
Please review the following commits I made in branch nicks/apiserver:
46fdc8af8f882a82ae7b6ea1105c47aa1dfe2a41 (2021-05-21 11:56:20 -0400)
vendor: update apiserver for Watch() fixes

vendor: update apiserver for Watch() fixes

---

internal/controllers/core/podlogstream/podlogstreamcontroller_test.go
internal/controllers/core/portforward/reconciler_test.go
internal/controllers/fake/fixture.go
internal/engine/buildcontrol/image_build_and_deployer_test.go
internal/engine/k8srollout/podmonitor_test.go
internal/engine/metrics/controller_test.go
internal/k8s/portforward/portforward_test.go
internal/k8s/runtime_test.go
internal/testutils/context.go
internal/watch/notify_test.go
pkg/logger/env_test.go
pkg/logger/logger.go

Hello @nicks,
Please review the following commits I made in branch nicks/test:
47efc0d0bd7a2739b1612f303d6857254fe1f0a0 (2021-05-21 16:54:13 -0400)
test: clean up test loggers a bit

test: clean up test loggers a bit

---

internal/build/container_test.go
internal/build/docker_builder.go
internal/cli/wire_gen.go
internal/docker/client.go
internal/docker/options.go
internal/engine/buildcontrol/wire_gen.go
internal/engine/wire_gen.go

Hello @maiamcc, @milas,
Please review the following commits I made in branch nicks/corruption:
905ff8041dd54032de4da80441033a358bc9b747 (2021-05-24 16:48:38 -0400)
build: retry build on mysterious buildkit corruption errors
This is a crappy solution, but I don't have a better idea right now.
Fixes https://github.com/tilt-dev/tilt/issues/4582

build: retry build on mysterious buildkit corruption errors

---

internal/cli/wire_gen.go
internal/controllers/apicmp/delta.go
internal/controllers/apicmp/delta_test.go
internal/engine/buildcontrol/wire_gen.go
internal/engine/uiresource/subscriber.go
internal/engine/uiresource/subscriber_test.go
internal/engine/uisession/subscriber.go
internal/engine/uisession/subscriber_test.go
internal/engine/upper_test.go
internal/engine/wire_gen.go

Please review the following commits I made in branch nicks/uisession14:
1c4bb747e6651e6801045b331880c018c495f20c (2021-05-25 12:40:45 -0400)
engine: double-write uisession and uiresource

engine: double-write uisession and uiresource

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/winsize:
4dd2385a99f87e6ed9ab72586900632db01764c2 (2021-05-26 20:25:38 -0400)
test: throw bigger computers at the problem

test: throw bigger computers at the problem

---

.gitignore
configs/storybook/Dockerfile
web/.storybook/main.js

Hello @nicks,
Please review the following commits I made in branch nicks/storybook:
1e35f1a331924bb72ad3118a1a6954a464d35d0a (2021-06-07 12:46:03 -0400)
configs: optimize storybook build a bit

configs: optimize storybook build a bit

---

pkg/webview/view.pb.go
pkg/webview/view.swagger.json
web/src/view.d.ts

This is just a run of `make proto` so that the next PR that touches view.proto doesn't have unrelated changes. (it looks like the last edits to `view.proto` were not followed by a `make proto`)

proto: regen code

---

internal/engine/upper_test.go

Hello @nicks,
9cc21f352cd0e0cce46040d56b7dfccaa018a0a7 (2021-06-10 10:53:21 -0400)
test: increases stdTimeout to see if this helps with windows failures

test: increases stdTimeout to see if this helps with windows failures

---

internal/engine/portforward/actions.go

Please review the following commits I made in branch nicks/pf:
4c26ff0afca5a8ceb040687b10d65499f9ac3399 (2021-06-10 16:09:24 -0400)
portforward: fix a copy-paste error

portforward: fix a copy-paste error

---

internal/engine/upper_test.go

Please review the following commits I made in branch nicks/speed2:
32fcd97d652fec90ad50c37542645663c704886a (2021-06-11 10:47:57 -0400)
test: remove the file-coalescing tests in engine
they don't really belong here now that this is in the reconciler

test: remove the file-coalescing tests in engine

---

internal/engine/upper_test.go
internal/hud/server/apiserver.go
internal/hud/server/controller.go

Hello @nicks,
Please review the following commits I made in branch nicks/speed1:
d8100833092f7dcd63fedc988a99213750306d70 (2021-06-11 10:27:02 -0400)
test: speed up server startup a bit

test: speed up server startup a bit

---

internal/cli/wire_gen.go
internal/controllers/core/uibutton/reconciler.go
internal/controllers/core/uibutton/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go
internal/hud/server/websocket.go
internal/hud/webview/convert.go

this is pretty much a copy/paste of the uiresource code (minus the comment about uiresource not being an actual api object)
I spent 15 minutes going down a unit test rabbit hole but it seems like the kind of thing where there'd be a bunch of annoying support code to write and testing it at the unit level wouldn't really give much extra confidence things are working. At some point maybe we can figure out an integration test that involves the web ui.

controllers: send uibutton updates via websocket

---

web/src/AppController.test.ts
web/src/AppController.ts
web/src/HUD.tsx

Please review the following commits I made in branch nicks/snapshothighlight:
cd9a696a64163abcf4d2910cdcfdcec602e68875 (2021-06-14 11:57:12 -0400)
web: remove old snapshot highlight code

web: remove old snapshot highlight code

---

internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go
pkg/model/manifest_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/cachepaths:
fd6292ae8d63d9eec3dfe0f3208de6283f639b54 (2021-06-14 16:32:29 -0400)
model: remove a dead field

model: remove a dead field

---

internal/container/selector.go
internal/engine/buildcontrol/image_build_and_deployer.go
internal/engine/buildcontrol/image_build_and_deployer_test.go
internal/k8s/image.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go

Hello @milas,
Please review the following commits I made in branch nicks/imagemap:
0782c40e93cae77860b00eab2c5dc91df0f714e2 (2021-06-14 17:48:58 -0400)
engine: use ImageMapSpec api
5303bc1fc28e97fa600ca0c937b9e5752ea0a198 (2021-06-14 17:46:03 -0400)
apis: ImageMap fields

engine: use ImageMapSpec api

---

internal/container/selector.go
internal/engine/buildcontrol/image_build_and_deployer.go
internal/engine/buildcontrol/testdata_test.go
internal/engine/testdata_test.go
pkg/model/image_target.go

Hello @milas,
Please review the following commits I made in branch nicks/imagemap3:
7c713c0954967996e504c052f690c7b45da47894 (2021-06-15 11:28:45 -0400)
engine: use ImageMap api models

engine: use ImageMap api models

---

web/src/OverviewActionBar.tsx
web/src/OverviewLogPane.test.tsx
web/src/OverviewLogPane.tsx
web/src/ResourceNav.test.tsx
web/src/ResourceNav.tsx
web/src/logfilters.ts

Please review the following commits I made in branch nicks/resourcenav:
1a7bdd489f80577ebe766d888554728f9b1415da (2021-06-15 16:40:53 -0400)
web: fix a bug where react wasn't properly re-rendering
the useLocation() hook updates the component when the page changes.
the useHistory() hook does not.

web: fix a bug where react wasn't properly re-rendering

---

web/src/HUD.test.tsx
web/src/HUD.tsx

Please review the following commits I made in branch nicks/react-optimize2:
c6960421c234c77d200da5ab53df259653560d26 (2021-06-17 15:31:31 -0400)
web: optimize log rendering

web: optimize log rendering

---

web/src/ResourceNav.test.tsx
web/src/ResourceNav.tsx

Please review the following commits I made in branch nicks/resourcenav3:
ebf80a36f938fba44b0aa7b65d4c1b1388d7a316 (2021-06-18 15:33:42 -0400)
web: update ResourceNav context to avoid re-renders

web: update ResourceNav context to avoid re-renders

---

internal/cli/wire_gen.go
internal/controllers/core/kubernetesapply/reconciler.go
internal/controllers/wire.go
internal/engine/upper_test.go
internal/hud/server/apiserver_test.go
pkg/apis/core/v1alpha1/register.go

Hello @milas,
Please review the following commits I made in branch nicks/controller:
e7e94a966502999089ff2d371f8ee23984eecd63 (2021-06-18 14:44:09 -0400)
controllers: scaffolding for a kubernetesapply reconciler

controllers: scaffolding for a kubernetesapply reconciler

---

internal/controllers/core/kubernetesapply/hash.go
internal/controllers/core/kubernetesapply/hash_test.go
internal/engine/buildcontrol/image_build_and_deployer.go
internal/engine/upper_test.go
internal/k8s/ref.go
internal/store/build_result.go
internal/store/json_test.go
pkg/webview/view.pb.go

Please review the following commits I made in branch nicks/k8sapplystatus:
6d5a818cef03911ca4e34925e4bd263336557107 (2021-06-23 15:44:17 -0400)
engine: create KubernetesApplyStatus
12d70a02d65a63e2aff442dad7faf13d4c367108 (2021-06-23 15:44:04 -0400)
apis: add KubernetesApplyStatus

engine: create KubernetesApplyStatus

---

internal/build/docker_builder.go
internal/cli/wire_gen.go
internal/controllers/core/kubernetesapply/reconciler.go
internal/controllers/core/kubernetesapply/reconciler_test.go
internal/controllers/wire.go
internal/engine/build_and_deployer_test.go
internal/engine/buildcontrol/image_build_and_deployer.go
internal/engine/buildcontrol/image_build_and_deployer_test.go
internal/engine/buildcontrol/wire.go
internal/engine/buildcontrol/wire_gen.go
internal/engine/configs/api.go
internal/engine/upper_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
pkg/apis/core/v1alpha1/register.go

Please review the following commits I made in branch nicks/ka2:
136e0b61433a6ce3395b799acd912d8d28dde458 (2021-06-24 16:30:29 -0400)
controllers: move apply code into the reconciler

controllers: move apply code into the reconciler

---

internal/controllers/core/kubernetesapply/reconciler.go
internal/controllers/core/kubernetesapply/reconciler_test.go

Please review the following commits I made in branch nicks/ch12246:
5106ed9ad5c0919f08173080e4f1e2989cc1b028 (2021-06-28 18:06:32 -0400)
kubernetesapply: garbage collect k8s resources on reconcile
Fixes https://github.com/tilt-dev/tilt/issues/3137

kubernetesapply: garbage collect k8s resources on reconcile

---

web/src/HUD.tsx
web/src/feature.ts

Add a context for feature flagging to make shared state easier to manage, plus add labels feature flag

web: add a context for feature flags and add labels flag

---

web/src/OverviewTable.tsx
web/src/OverviewTableStarResourceButton.tsx
web/src/OverviewTableStatus.tsx
web/src/OverviewTableTriggerButton.tsx
web/src/OverviewTableTriggerModeToggle.tsx
web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx

Thanks to @lizzthabet for finding some issues, which will improve accessibility:
- Show star icon on keyboard focus
- Make Header font easier to read
- Clicking on status takes you to logs
Other fixes in this PR: 
- Refine tooltip text for Trigger and Trigger Mode
- Visual tweak for Endpoints
- Tiltfile should not have Trigger Mode

Accessibility fixes for Table Overview

---

README.md

Hello @ellenkorbes, @hyu,
Please review the following commits I made in branch nicks/cloud:
18c864f23c821f7d10e4d1cc332783071660134c (2021-07-01 11:56:46 -0400)
readme: remove tilt cloud

readme: remove tilt cloud

---

internal/controllers/core/kubernetesdiscovery/portforwards.go
internal/controllers/core/kubernetesdiscovery/portforwards_test.go
internal/controllers/core/kubernetesdiscovery/reconciler.go

Please review the following commits I made in branch nicks/pf2:
27780ba24c08472638756280492ff64df3b6f46e (2021-07-02 18:34:35 -0400)
kubernetesdiscovery: propagate PortForward template

kubernetesdiscovery: propagate PortForward template

---

internal/controllers/core/kubernetesdiscovery/portforwards.go
internal/controllers/core/kubernetesdiscovery/portforwards_test.go
internal/controllers/core/kubernetesdiscovery/reconciler.go

Hello @milas,
Please review the following commits I made in branch nicks/pf3:
367ac4fcb5c675db0196473d6421e4d41c13a3b8 (2021-07-06 13:45:43 -0400)
kubernetesdiscovery: garbagecollect portforwards and podlogstreams

kubernetesdiscovery: garbagecollect portforwards and podlogstreams

---

configs/storybook/templates/ingress.yaml
configs/storybook/values.yaml

Hello @nicks,
Please review the following commits I made in branch nicks/certs:
c6d47612cb96d063876d01ebff87982c64e18e08 (2021-07-06 15:38:55 -0400)
configs: update certificate versions

configs: update certificate versions

---

configs/storybook/templates/ingress.yaml

Hello @nicks,
Please review the following commits I made in branch nicks/ingress:
29cdf458838c6071143e6cc4b1db4cec7ab6f305 (2021-07-06 17:22:30 -0400)
configs: update ingress version

configs: update ingress version

---

configs/storybook/templates/ingress.yaml

Hello @nicks,
Please review the following commits I made in branch nicks/configs:
4221f82e1d58aa952b76fc6f2f881ef635a8646b (2021-07-06 20:02:01 -0400)
configs: update ingress

configs: update ingress

---

pkg/apis/core/v1alpha1/imagemap_types.go
pkg/apis/core/v1alpha1/kubernetesapply_types.go
pkg/apis/core/v1alpha1/kubernetesdiscovery_types.go
pkg/apis/core/v1alpha1/portforward_types.go

Please review the following commits I made in branch nicks/shortnames:
9bbbf3cdbdef01508b251ad5b70334e0572356ab (2021-07-07 16:18:38 -0400)
apis: short names for common resources

apis: short names for common resources

---

internal/container/ignore.go
internal/controllers/core/kubernetesdiscovery/reconciler_test.go
internal/controllers/core/podlogstream/podlogstreamcontroller_test.go
internal/engine/k8swatch/manifest_subscriber.go
internal/engine/runtimelog/ignore.go
internal/k8s/target.go
internal/testutils/manifestbuilder/manifestbuilder.go
internal/tiltfile/tiltfile_test.go
pkg/model/k8s_target.go
pkg/model/manifest_test.go

Please review the following commits I made in branch nicks/kapp3:
23dcca6434ce7798f502240e53b3fcaf603a6cc2 (2021-07-08 18:25:01 -0400)
model: refactor API templates as a property of K8sTarget

model: refactor API templates as a property of K8sTarget

---

integration/k8s_fixture_test.go

Hello @nicks,
4a717eddb68fa56e81dbaf0e4b6e0d0bc11b0ed5 (2021-07-09 16:54:50 -0400)
integration: grab current context/cluster before setting up new kubeconfig
In some environments, kubectl will fail to even load the context
if the kubeconfig is malformed.

integration: grab current context/cluster before setting up new kubeconfig

---

internal/controllers/manager.go

Please review the following commits I made in branch nicks/reconcilererror:
334b676b0d49f627234a335270e146e21df91bfe (2021-07-09 19:38:30 -0400)
controller: improve apiserver logging

controller: improve apiserver logging

---

internal/engine/configs/api.go
internal/engine/configs/api_test.go

Please review the following commits I made in branch nicks/ch12342:
64539277f9756cbc3a3664a547533660cab979ea (2021-07-09 16:25:01 -0400)
configs: on tiltfile error, don't gc orphaned objects
The tiltfile might have only been partially evalutated, and
we don't want the reconcilers to tear those objects down.
Fixes https://github.com/tilt-dev/tilt/issues/4745

configs: on tiltfile error, don't gc orphaned objects

---

web/src/OverviewTable.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/spacing:
6c3d9e649ed656b1141645e3658d21d956015ee0 (2021-07-09 17:49:55 -0400)
web: minor spacing changes

web: minor spacing changes

---

internal/controllers/core/podlogstream/podlogstreamcontroller.go
internal/controllers/core/podlogstream/podlogstreamcontroller_test.go
internal/k8s/fake_client.go

Hello @nicks,
Please review the following commits I made in branch nicks/fakelogs:
cb211e69e611ce7f56b8f48a0bfa5645a0130784 (2021-07-13 20:10:51 -0400)
test: fix an test interaction that caused infinite reconcilation

test: fix an test interaction that caused infinite reconcilation

---

internal/engine/upper_test.go
internal/testutils/podbuilder/podbuilder.go

Hello @nicks,
Please review the following commits I made in branch nicks/kdstatustest:
bc53c3e62b3dd60e11f5bd4385dba8758cb37498 (2021-07-14 10:58:34 -0400)
test: the fake build and deployer should update the Kubernetes status too

test: the fake build and deployer should update the Kubernetes status too

---

internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go
internal/engine/buildcontrol/build_control.go
internal/engine/configs/actions.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/engine/configs/tiltfile_log_writer.go
internal/engine/session/controller.go
internal/engine/session/controller_test.go
internal/engine/session/conv.go
internal/engine/telemetry/controller.go
internal/engine/uiresource/subscriber_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/hud.go
internal/hud/renderer_test.go
internal/hud/server/server_test.go
internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/store/engine_state.go
pkg/model/logstore/prefix.go
pkg/model/manifest.go

fdbf28c3123ed818d1435d407233dd1bddf1bf5d (2021-07-21 19:59:24 -0400)
engine: prepare for multiple tiltfiles

engine: prepare for multiple tiltfiles

---

web/src/OverviewResourcePane.stories.tsx
web/src/OverviewResourceSidebar.tsx

Please review the following commits I made in branch nicks/divider:
cbacbc8ac8925b1da93e696d1fd144938f43fec1 (2021-07-22 13:28:30 -0400)
web: allow sidebar items to shrink properly

web: allow sidebar items to shrink properly

---

internal/cli/wire_gen.go
internal/controllers/core/tiltfile/reconciler.go
internal/controllers/core/tiltfile/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/tiltfile3:
61e2692dcd16f1ec9fa5c87b5a744076e0319576 (2021-07-22 15:41:28 -0400)
controllers: set up a tiltfile reconciler
8b573fdf82386f40ddb393cb2c565f4fa70b0e39 (2021-07-22 10:52:33 -0400)
apis: add Tiltfile API

controllers: set up a tiltfile reconciler

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Fixes #4808
```
k8s_resource(workload='foo', new_name='bar')
k8s_resource('bar', objects=['baz:namespace'])
```
Occasionally fails saying that "bar" is an unknown resource.
`k8s_resource`'s `new_name`s get applied at resource assembly time, but these options get applied in non-deterministic order by [looping over a map](https://github.com/tilt-dev/tilt/blob/51c68522dcde175866e89ea9fef596c27da5ed7e/internal/tiltfile/tiltfile_state.go#L709). If that loop processes 'bar' before 'foo', then it won't know what 'bar' is, and fail.
Store k8s options as a slice and combine them at assembly time, rather than as part of the k8s_resource call.
I tried to fix this inside the k8s_resource call but it turned out to be a bit ugly - there's already renaming happening at assembly time, and the …

tiltfile: move k8s_resource option aggregation to assembly stage

---

internal/cli/wire_gen.go
internal/controllers/core/tiltfile/buildsource.go
internal/controllers/core/tiltfile/reconciler.go
internal/controllers/core/tiltfile/wire.go
internal/engine/buildcontrol/log.go
internal/engine/buildcontroller.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/engine/upper_test.go

ea18baf2f2288d2dd41cfbffe4fe48dbaa22a32c (2021-07-29 14:59:53 -0400)
controllers: trigger tiltfile reconcilation from the configs controller

controllers: trigger tiltfile reconcilation from the configs controller

---

web/storybook.tiltfile

tfw you start using a new feature you built for your own workflows 😇

web: add labels to the storybook Tiltfile

---

internal/cli/wire_gen.go
internal/controllers/core/tiltfile/buildsource.go
internal/controllers/core/tiltfile/log.go
internal/controllers/core/tiltfile/reconciler.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/engine/upper_test.go
internal/hud/webview/convert_test.go

Please review the following commits I made in branch nicks/tiltfile2:
4fe7f7bf31b98012b518000ee7a8751edb1ed19e (2021-07-30 17:58:50 -0400)
controllers: tiltfile reconciler

controllers: tiltfile reconciler

---

internal/cli/wire_gen.go
internal/controllers/core/extensionrepo/reconciler.go
internal/controllers/core/extensionrepo/wire.go
internal/controllers/core/globalextension/reconciler.go
internal/controllers/core/globalextension/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/reconcilers:
5a14fd27cf71ffabc60e32dd7e2ed8ce91204d6b (2021-08-03 11:07:10 -0400)
controllers: reconciler scaffolding for GlobalExtension, ExtensionRepo

controllers: reconciler scaffolding for GlobalExtension, ExtensionRepo

---

internal/tiltfile/files.go
internal/tiltfile/tiltfile_test.go

Currently, `[no output]` is ALWAYS logged if a command from
`local()` / `helm()` / `kustomize()` returns no output.
This can be annoying with `local()` if you have a silent command
using `echo_off=True` + `quiet=True` because it'll result in
`[no output]` in the logs with no context.
At the least, this should be tied to `quiet` - if you've already
requested to NOT receive output, it's weird to get output when
there is no output.
This change also goes one step further - if `echo_off=True` and
`quiet=False`, it _also_ omits the `[no output]` because there's
no way to know what ran and didn't output anything since the
command itself wasn't echoed.

tiltfile: limit scenarios where `[no output]` is shown

---

internal/engine/configs/configs_controller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/store/engine_state.go
pkg/model/manifest.go

Please review the following commits I made in branch nicks/trigger:
d4d2b085518b9311aae7386d6d63951120c3c7b7 (2021-08-03 18:28:46 -0400)
engine: more multi-tiltfile support

engine: more multi-tiltfile support

---

go.mod
go.sum
internal/cli/wire_gen.go
internal/controllers/core/extensionrepo/reconciler.go
internal/controllers/core/extensionrepo/reconciler_test.go
internal/engine/upper_test.go
internal/hud/server/apiserver_test.go
pkg/apis/core/v1alpha1/extensionrepo_types.go
vendor/github.com/tilt-dev/go-get/get.go
vendor/modules.txt

Please review the following commits I made in branch nicks/repo2:
d54d27c14fdd6cd8fe0217fcc3dbd05152510771 (2021-08-03 17:18:11 -0400)
extensionrepo: add a basic reconciler

extensionrepo: add a basic reconciler

---

web/src/OverviewTable.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/prettier:
01714e04bd06e2192deee42752c07973303cfd2b (2021-08-05 15:14:09 -0400)
web: run prettier

web: run prettier

---

go.mod
go.sum
internal/controllers/core/extensionrepo/reconciler.go
internal/controllers/core/extensionrepo/reconciler_test.go
internal/controllers/fake/fixture.go
pkg/apis/core/v1alpha1/extensionrepo_types.go
vendor/github.com/tilt-dev/go-get/get.go
vendor/github.com/tilt-dev/go-get/vcs.go
vendor/modules.txt

Please review the following commits I made in branch nicks/filerepo:
799026ac6a86e999ab8197025b872562fcec3caf (2021-08-05 16:28:26 -0400)
extensionrepo: support on-disk repos

extensionrepo: support on-disk repos

---

internal/cloud/io_test.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/engine/session/controller.go
internal/engine/session/controller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/store/tiltfiles/actions.go
internal/store/tiltfiles/reducers.go

2e2fabc4b5a6d5ee963422474c433513cd5c0fc1 (2021-08-05 20:48:58 -0400)
tiltfile: apiserver <> engine store interop

tiltfile: apiserver <> engine store interop

---

internal/controllers/core/globalextension/reconciler.go
internal/controllers/core/globalextension/reconciler_test.go
internal/controllers/core/globalextension/tiltfiles.go
internal/controllers/core/tiltfile/reconciler.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/store/logger.go
internal/store/tiltfiles/actions.go

Please review the following commits I made in branch nicks/tiltfilechild:
8b019a72ec32175a28a0ef20d12fc72cd23db551 (2021-08-06 15:53:38 -0400)
globalextension: create tiltfiles

globalextension: create tiltfiles

---

internal/cli/ci.go
internal/cli/up.go
internal/cli/updog.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/controllers/core/tiltfile/buildsource.go
internal/controllers/core/tiltfile/reconciler.go
internal/engine/actions.go
internal/engine/analytics/analytics_updater.go
internal/engine/analytics/analytics_updater_test.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/engine/session/controller.go
internal/engine/session/controller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/enginemode:
50aa214830523ec34b98efd9f44c9decc7c6353b (2021-08-10 12:24:45 -0400)
engine: dependency-inject EngineMode

engine: dependency-inject EngineMode

---

go.mod
go.sum
internal/cli/wire.go
internal/cli/wire_gen.go
internal/controllers/core/extensionrepo/reconciler.go
internal/controllers/core/extensionrepo/reconciler_test.go
internal/engine/upper_test.go
internal/xdg/base.go
internal/xdg/fake.go
vendor/github.com/adrg/xdg/CODE_OF_CONDUCT.md
vendor/github.com/adrg/xdg/CONTRIBUTING.md
vendor/github.com/adrg/xdg/LICENSE
vendor/github.com/adrg/xdg/README.md
vendor/github.com/adrg/xdg/base_dirs.go
vendor/github.com/adrg/xdg/codecov.yml
vendor/github.com/adrg/xdg/go.mod
vendor/github.com/adrg/xdg/go.sum
vendor/github.com/adrg/xdg/paths_darwin.go
vendor/github.com/adrg/xdg/paths_plan9.go
vendor/github.com/adrg/xdg/paths_unix.go
vendor/github.com/adrg/xdg/paths_windows.go
vendor/github.com/adrg/xdg/stat.go
vendor/github.com/adrg/xdg/stat_windows.go
vendor/github.com/adrg/xdg/user_dirs.go
vendor/github.com/adrg/xdg/utils.go
vendor/github.com/adrg/xdg/xdg.go
vendor/modules.txt

Please review the following commits I made in branch nicks/xdg:
95efc06f2d4fd807c9b3e8173117e165174fbbe7 (2021-08-11 17:11:31 -0400)
extensionrepo: store repos under ~/.local/share/tilt-dev

extensionrepo: store repos under ~/.local/share/tilt-dev

---

internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/actions.go
internal/hud/hud.go
internal/hud/view/view.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/watchsettings:
f3d69a7c40e92e32c173e007ffcf222a20ea8a6e (2021-08-12 14:50:28 -0400)
store: remove some dead fields from EngineState

store: remove some dead fields from EngineState

---

internal/engine/upper.go

Please review the following commits I made in branch nicks/reload:
a8c2004d996b5b6586674a8b8e4f48e42c17122b (2021-08-12 20:06:35 -0400)
engine: adjust tiltfile reload logic

engine: adjust tiltfile reload logic

---

go.mod
go.sum
vendor/github.com/tilt-dev/tilt-apiserver/pkg/server/builder/resource/types.go
vendor/modules.txt

Hello @nicks,
Please review the following commits I made in branch nicks/apiserver2:
efe4d345979c2f0d5a70147c04f74195ac90b3c7 (2021-08-19 16:33:12 -0400)
vendor: update to tilt-apiserver v0.4.3

vendor: update to tilt-apiserver v0.4.3

---

web/src/ApiButton.tsx
web/src/CustomNav.tsx
web/src/OverviewResourcePane.tsx
web/src/OverviewTable.tsx

web: sort uibuttons

---

internal/cli/patch.go
internal/cli/patch_test.go
vendor/k8s.io/kubectl/pkg/cmd/patch/patch.go
vendor/modules.txt

Please review the following commits I made in branch nicks/patch:
abe093e7b8928943d9d87dae023c600560d69af9 (2021-08-19 17:53:55 -0400)
cli: add tilt patch
this will hopefully make it a bit easier to write
bash scripts in tilt extensions

cli: add tilt patch

---

.circleci/Dockerfile
.circleci/config.yml
configs/storybook/Dockerfile
internal/engine/telemetry/controller_test.go
scripts/release.Dockerfile
web/Dockerfile
web/package.json
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/node16:
e5df091b57a51ba981b7aba550af73cabb0848af (2021-08-27 16:49:26 -0400)
web: upgrade to node16

web: upgrade to node16

---

scripts/upload-assets.py

Hello @nicks,
Please review the following commits I made in branch nicks/python3:
c39839eb3a2f9ed79de5a49cfd6ef6f7a7ce3752 (2021-08-30 10:43:54 -0400)
scripts: python -> python3

scripts: python -> python3

---

internal/controllers/core/tiltfile/reducers.go
internal/controllers/core/tiltfile/reducers_test.go

Please review the following commits I made in branch nicks/mndeforder:
44e99b608d71d68aa6c3e0ffe2c5643d62547999 (2021-09-01 21:12:36 -0400)
tiltfile: fix service shuffling bug
fixes https://github.com/tilt-dev/tilt/issues/4885

tiltfile: fix service shuffling bug

---

internal/controllers/apis/restarton/restarton.go
internal/controllers/core/cmd/controller.go

Please review the following commits I made in branch nicks/restarton:
81bb74ae84eb000ba55ef8aeeba4b8c1aa5d7fa7 (2021-09-02 13:57:26 -0400)
controllers: factor out restarton/starton interpreters

controllers: factor out restarton/starton interpreters

---

internal/controllers/core/tiltfile/reconciler.go
internal/controllers/core/tiltfile/reconciler_test.go

Please review the following commits I made in branch nicks/reconciler2:
1e00f28d041a9b6f7936320b88f9a1338b6946b1 (2021-09-02 21:42:05 -0400)
tiltfile: verify the tiltfile reconciler reaches a steady state

tiltfile: verify the tiltfile reconciler reaches a steady state

---

web/src/OverviewTable.tsx
web/src/constants.ts

(will be dismissable with #4907)
Copy advice welcome!

web: add info tooltip to widgets column header

---

internal/tiltfile/v1alpha1/plugin_test.go
internal/tiltfile/v1alpha1/types.go
internal/tiltfile/value/string.go

Please review the following commits I made in branch nicks/extargs:
51a77545aa083123f4ef67964b57a5279389858a (2021-09-03 13:14:50 -0400)
tiltfile: add extension(args=...)

tiltfile: add extension(args=...)

---

scripts/upload-assets.py

Please review the following commits I made in branch nicks/pythonnnnnnn:
cbad4e25d41df073811475a24a92ee6679e3b6a6 (2021-09-03 17:21:25 -0400)
scripts: decode bytes to string properly

scripts: decode bytes to string properly

---

internal/engine/dockerprune/docker_pruner.go

Recently received a pprof from a user who was experiencing high CPU
while Tilt wasn't really doing anything.
One of the offenders is the Docker Pruner: due to being an older
subscriber, it didn't have the newer optimization to skip running on
log-only store events, so would fire at a high-rate even when it
had no work to do.
Beyond that, collecting image references is surprisingly expensive
due to using a bunch of regex stuff under the hood. While it should
get called orders of magnitude less due to skipping log-only updates,
further changes are included to try and optimize this to exit early
without doing this work if possible.

docker: exit early under more conditions in pruner

---

web/src/OverviewTable.stories.tsx
web/src/OverviewTable.tsx
web/src/OverviewTableStatus.tsx
web/src/SidebarItemView.tsx
web/src/testdata.tsx

Please review the following commits I made in branch nicks/warnings2:
b5374ce8b54fdb305a01f648ce335ef4464ace47 (2021-09-07 17:07:19 -0400)
web: improve warning display in overview

web: improve warning display in overview

---

internal/analytics/utils.go
internal/cli/wire_gen.go
internal/controllers/core/extension/reconciler.go
internal/controllers/core/extension/reconciler_test.go
internal/controllers/core/tiltfile/reconciler.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/metrics2:
5efa2f2a0e7ad14253b02e703c525e5c80cd2fbe (2021-09-08 17:37:28 -0400)
extension: api-level event for extension load
f305a99fb91eafa71ae0a6622df89b8567a67e57 (2021-09-08 17:37:28 -0400)
extension: propagate extension arg changes correctly

extension: api-level event for extension load

---

pkg/model/manifest.go
pkg/model/manifest_test.go

In some cases, `url.URL` can't be compared: case reported was a
URL with a `user@` portion, which populates the `User` field of
type `url.Userinfo` that contains unexported fields. (This came
up when trying to add a link for a local DB connection string.)
While one possible fix would be to add a custom comparer for
`Link` which uses `Link::URLString()` to side-step this, since
the comparers are used for build invalidation, we can actually
just ignore the `Link` type entirely for comparison purposes,
as it does not cause a build to be invalidated.
So, as a bonus, you can now freely change `links` in `Tiltfile`
without triggering new builds unnecessarily!
Fixes #4945.

engine: handle all link types + don't invalidate build on change

---

web/src/ApiButton.tsx
web/src/tiltApi.ts

soon, enable/disable service buttons will be writing to the tilt api, so let's get this code out of apibutton!

web: extract tilt api functions

---

internal/cli/cli.go

Please review the following commits I made in branch nicks/toggle:
0f2f0e2d83879c7233e8de0c04a42cea4b51bd6a (2021-09-10 17:20:44 -0400)
cli: add the patch command

cli: add the patch command

---

configs/storybook/Dockerfile

Please review the following commits I made in branch nicks/storybook2:
b7f4cd51d2ab2c2ed5949a6d039bd7235e8c16db (2021-09-20 13:03:28 -0400)
configs: include yarn.lock in storybook Dockerfile

configs: include yarn.lock in storybook Dockerfile

---

internal/tiltfile/v1alpha1/plugin_test.go
internal/tiltfile/v1alpha1/types.go

Hello @milas,
Please review the following commits I made in branch nicks/codegen3:
fab3286f0dd153e80bdeef798f714185eed8b870 (2021-09-21 16:37:43 -0400)
tiltfile: more filewatch codegen

tiltfile: more filewatch codegen

---

internal/controllers/core/cmd/controller.go
internal/controllers/core/tiltfile/api.go
internal/tiltfile/v1alpha1/plugin_test.go
internal/tiltfile/v1alpha1/types.go
pkg/apis/core/v1alpha1/cmd_types.go
pkg/apis/core/v1alpha1/register.go

Hello @milas,
Please review the following commits I made in branch nicks/codegen4:
19a2185ac63185d2e882b42b71d841fb5c0602cc (2021-09-22 11:36:32 -0400)
tiltfile: codegen cmd built-ins

tiltfile: codegen cmd built-ins

---

internal/cli/dump.go
internal/cli/tiltfile_result.go
internal/cli/tiltfile_result_test.go
internal/controllers/apiset/apiset.go
internal/controllers/core/tiltfile/api.go
internal/tiltfile/v1alpha1/plugin_test.go

Please review the following commits I made in branch nicks/ch12773:
6efcb6f5afcae51ca3bf0d72fc5dbfa85011b5fe (2021-09-23 19:54:12 -0400)
cli: fix serialization of TiltfileResult ObjectSet
fixes https://github.com/tilt-dev/tilt/issues/4981

cli: fix serialization of TiltfileResult ObjectSet

---

Makefile
internal/controllers/core/tiltfile/api.go
internal/tiltfile/v1alpha1/plugin_test.go
internal/tiltfile/v1alpha1/types.go
pkg/apis/core/v1alpha1/uibutton_types.go

Please review the following commits I made in branch nicks/uibutton:
892dcca551556ffac7b4eff2a65bcbef61d27235 (2021-09-24 12:15:19 -0400)
tiltfile: generate built-in for uibutton

tiltfile: generate built-in for uibutton

---

internal/cli/wire_gen.go
internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/wire.go
internal/controllers/wire.go
internal/engine/buildcontrol/wire_gen.go
internal/engine/upper_test.go
internal/engine/wire_gen.go
internal/hud/server/apiserver_test.go
pkg/apis/core/v1alpha1/register.go

Hello @nicks,
Please review the following commits I made in branch nicks/lu6:
efb200f6f1cc93a327b130d90d9a347f6826f004 (2021-09-29 12:34:06 -0400)
controllers: liveupdate scaffolding

controllers: liveupdate scaffolding

---

internal/cli/wire_gen.go
internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/reconciler_test.go
internal/engine/upper_test.go

No reconciler logic yet, just setting up the watches.

controllers: add Kubernetes{Discovery,Apply} watch to Live Update

---

internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/reconciler_test.go
internal/engine/buildcontrol/build_control.go
internal/engine/buildcontrol/extractors.go
internal/store/hold.go

Hello @milas,
Please review the following commits I made in branch nicks/buildcontrol:
5efdc14f45fde4290b3166c6b45ef44c59b242bd (2021-10-29 22:39:14 -0400)
liveupdate: dispatch events for engine state

liveupdate: dispatch events for engine state

---

internal/controllers/apis/configmap/triggerqueue.go
internal/controllers/apis/liveupdate/mode.go
internal/controllers/core/liveupdate/monitor.go
internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/reconciler_test.go
internal/controllers/core/tiltfile/api.go
internal/controllers/core/tiltfile/reconciler.go
internal/controllers/fake/fixture.go
internal/engine/configs/trigger_queue_subscriber.go
internal/store/tiltfiles/actions.go
pkg/model/trigger_mode.go

Hello @milas,
Please review the following commits I made in branch nicks/liveupdate2:
f8dcf9569cb13395f41fdecaeb7d2c50b7d308c9 (2021-11-01 16:44:04 -0400)
liveupdate: handle trigger_mode=manual in the reconciler

liveupdate: handle trigger_mode=manual in the reconciler

---

web/src/SidebarResources.tsx

While working on the display of disabled resources in the resource detail view, I reorganized the sidebar components to simplify the logic between group/non-group sidebar views, as well as move display logic from the parent sidebar component into children components. This should make it easier to display disabled components for group/non-group views. 
This PR just includes the refactoring work, so the disable resources display PR doesn't get too huge. 🙂

web: reorganize sidebar components

---

web/src/logfilters.test.ts
web/src/logfilters.ts

Please review the following commits I made in branch nicks/logfilter:
91a0c8c407e427532b9ba0d033bea1ddde2f299e (2021-11-03 09:53:36 -0400)
web: fix a bug in log filtering

web: fix a bug in log filtering

---

internal/controllers/core/kubernetesapply/reconciler.go
internal/controllers/core/kubernetesapply/reconciler_test.go
internal/localexec/execer.go

When a custom `DeployCmd` is provided, a corresponding `DeleteCmd`
is needed to handle cleanup.
Although Tilt is able to track + diff the managed entities to determine
what to delete (which is still the case when using YAML), the
`DeployCmd` might create additional state, e.g. a Helm release in
Tiller/`Secret`, so this provides the tool with the means to clean
up the external state _as well as all relevant entities in the
cluster_.

api: run DeleteCmd when KubernetesApply object deleted

---

scripts/install.sh

brew bundle handles both install and upgrade
uses new tilt formula in homebrew-core https://github.com/Homebrew/homebrew-core/pull/88977

use brew bundle and new tilt formula

---

internal/build/docker_builder.go
internal/build/progress_writer.go

Please review the following commits I made in branch nicks/progress:
007d822b79e64a8a7b2ca6eeb15441c5093d7a8d (2021-11-01 17:15:55 -0400)
build: print docker upload progress

build: print docker upload progress

---

internal/build/container_test.go
internal/build/docker_builder.go
internal/build/options.go
internal/controllers/core/tiltfile/reconciler_test.go
internal/controllers/core/tiltfile/testdata_test.go
internal/dockerfile/ast.go
internal/dockerfile/dockerfile.go
internal/dockerfile/dockerfile_test.go
internal/dockerfile/inject.go
internal/dockerfile/inject_test.go
internal/engine/build_and_deployer_live_update_test.go
internal/engine/buildcontrol/build_control_test.go
internal/engine/buildcontrol/image_build_and_deployer.go
internal/engine/buildcontrol/image_build_and_deployer_test.go
internal/engine/buildcontrol/testdata_test.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/hud/webview/convert_test.go
internal/store/engine_state_test.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go
pkg/model/manifest.go
pkg/model/manifest_test.go

Please review the following commits I made in branch nicks/imagetarget3:
a3d157b55a20b6c41a8c5819c0f361f969caad7d (2021-11-10 17:57:19 -0500)
model: swap out DockerBuild with v1alpha1.DockerImageSpec

model: swap out DockerBuild with v1alpha1.DockerImageSpec

---

web/src/OverviewTable.tsx
web/src/OverviewTableStarResourceButton.tsx
web/src/OverviewTableTriggerButton.tsx
web/src/ResourceStatus.ts
web/src/SidebarItem.tsx
web/src/SidebarItemView.tsx
web/src/SidebarKeyboardShortcuts.tsx
web/src/SidebarResources.test.tsx
web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx
web/src/StarResourceButton.tsx
web/src/testdata.tsx

Please review the following commits I made in branch nicks/metrics2:
03df5a772fd20696f8763d605b7a6a9ac6a64c9f (2021-11-17 14:39:52 -0500)
web: add tags for the type of resource being triggered

web: add tags for the type of resource being triggered

---

internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go

Please review the following commits I made in branch nicks/metrics3:
b1907876936f3440633dc097da9c2fdc18b45769 (2021-11-17 15:02:25 -0500)
analytics: add a label count

analytics: add a label count

---

web/src/ApiButton.test.tsx
web/src/ApiButton.testhelpers.tsx
web/src/ApiButton.tsx

Please review the following commits I made in branch nicks/metrics:
551c4192c20c8c72779cf9878a979f41953470a7 (2021-11-17 13:25:49 -0500)
web: add the location to button click analytics
also, clean up some test warnings

web: add the location to button click analytics

---

internal/engine/upper_test.go

One of the test cases creates + deletes a pod before sending the
final real pod that it wants in the steady state, but was determining
it'd reached steady state by looking at the pod count, so might have
caught it when the count matched due to the about-to-be-deleted pod,
but the pod it really wanted hadn't been seen yet.

test: fix flaky TestPodEventOrdering test

---

internal/cli/down.go
internal/controllers/core/kubernetesapply/reconciler.go

Hello @milas,
Please review the following commits I made in branch nicks/custom:
5df30f510dbaea65a37fa3c82fe9a69d7604f222 (2021-11-17 18:45:23 -0500)
controllers: minor usability fixes while using k8s_custom_deploy:
- tilt down should run all commands, and aggregate any errors
- truncate stdout when it's too long

controllers: minor usability fixes while using k8s_custom_deploy

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/extensions2:
48cb345e3d0f7cd5144fad47bbcf766397ba85b6 (2021-11-18 14:14:44 -0500)
circleci: update extensions workflow

circleci: update extensions workflow

---

internal/controllers/core/kubernetesdiscovery/reconciler.go
internal/controllers/core/kubernetesdiscovery/reconciler_test.go
internal/k8s/owner_fetcher.go
internal/store/k8sconv/pod.go

Hello @milas,
Please review the following commits I made in branch nicks/owner2:
686b0b199a5180045b4a414b599b674c09c85cb9 (2021-11-18 17:14:41 -0500)
kubernetesdiscovery: fill in pod owner

kubernetesdiscovery: fill in pod owner

---

web/src/ApiButton.test.tsx
web/src/ApiButton.tsx

Please review the following commits I made in branch nicks/metrics4:
bac8d06c96c55dd82e16392a8d655e20844f374b (2021-11-22 16:07:21 -0500)
web: propagate analytics tags a bit better

web: propagate analytics tags a bit better

---

internal/store/k8sconv/resource.go
internal/store/k8sconv/resource_test.go

Hello @milas,
Please review the following commits I made in branch nicks/filter:
be88da27e5c977c9b967c5574d26684774eef238 (2021-11-23 17:21:22 -0500)
store: filter out pods from old replicasets

store: filter out pods from old replicasets

---

web/src/OverviewTable.test.tsx
web/src/OverviewTable.tsx

Hide the widgets column content if a resource is disable, plus add top margin to buttons to alleviate a style pet peeve of mine. 🤓

web: hide ApiButtons on Table View when a resource is disabled

---

internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_docker_compose_test.go

docker_compose: Add auto_init param to dc_resource

---

internal/engine/upper_test.go
internal/tiltfile/local_resource.go

If a local resource has no `serve_cmd`, it cannot logically have a
readiness probe, as there's no server to check for readiness.
The actual impact of this was that if another resource had a
dependency on a local resource in this state, the dependent resource
would get stuck waiting on the local resource indefinitely.
Now, the readiness probe will be ignored and a warning logged.
(I chose not to make this an error, as this came from a user report,
so there are `Tiltfile`s out there configured this way, and didn't want
to break them.)

tiltfile: ignore readiness probe for local resource w/ no serve_cmd

---

internal/engine/buildcontrol/build_control.go
internal/engine/buildcontrol/build_control_test.go

Hello @milas,
Please review the following commits I made in branch nicks/waiting:
107413b3bc6babb4c7bbab6e87f638878e881100 (2021-11-30 13:58:57 -0500)
buildcontrol: 'waiting' status fix
if a manually triggered resource isn't waiting on any change or trigger,
then its waiting field should be nil

buildcontrol: 'waiting' status fix

---

internal/cloud/io_test.go
internal/engine/uiresource/subscriber_test.go
internal/hud/webview/convert.go
pkg/apis/core/v1alpha1/uiresource_types.go

Hello @milas,
Please review the following commits I made in branch nicks/updated:
a0899bcffa825893a86ede8903f49eb55f1f00d0 (2021-11-30 15:35:37 -0500)
engine: add an up-to-date condition to all uiresources

engine: add an up-to-date condition to all uiresources

---

internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/reconciler_test.go

Allow selecting containers by their name instead of the image.
Nice and easy 😉

liveupdate: add container name selector support to reconciler

---

Makefile

Signed-off-by: Lam Tran <tranngoclam288@gmail.com>

script: remove unused command 'check-go'

---

internal/cli/wire_gen.go
internal/controllers/core/cluster/reconciler.go
internal/controllers/core/cluster/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go
pkg/apis/core/v1alpha1/register.go

Hello @nicks,
Please review the following commits I made in branch nicks/cluster2:
a677a6d9d9c45ed735d2a84c20cc92c5e35fc44f (2021-12-06 21:53:32 -0500)
cluster: add reconciler scaffolding

cluster: add reconciler scaffolding

---

internal/controllers/core/cluster/reconciler.go
internal/controllers/core/cluster/reconciler_test.go
internal/docker/fake_client.go
internal/k8s/fake_client.go

Hello @milas,
Please review the following commits I made in branch nicks/cluster:
1e68bb82b88a1176c5bea34322b954060431a310 (2021-12-09 17:00:00 -0500)
cluster: read arch

cluster: read arch

---

scripts/release.Dockerfile

Hello @nicks,
20555c64da7bc35e4a352a1a47e45eef5ede830c (2021-12-10 16:41:00 -0500)
scripts: add homebrew to path in the release container

scripts: add homebrew to path in the release container

---

internal/controllers/core/cluster/reconciler.go
internal/engine/upper.go
internal/store/clusters/actions.go
internal/store/clusters/reducers.go
internal/store/engine_state.go

Hello @milas,
Please review the following commits I made in branch nicks/actions:
a637e275c9e87618838893c0fe36291303b54c71 (2021-12-13 13:15:11 -0500)
clusters: action scaffolding

clusters: action scaffolding

---

.circleci/Dockerfile
.circleci/Dockerfile.integration
.circleci/config.yml
Makefile
integration/dc_fixture_test.go
integration/dcbuild/Dockerfile
integration/dcbuild/cmd/dcbuild/go.mod
integration/onedc/Dockerfile
integration/onedc/go.mod
integration/onedc_test.go
internal/dockercompose/client.go
scripts/install-dc2.ps1

- integration: upgrade go to work with arm64/aarch64
- ci: Install DC v2 on Windows
- ci: Install DC v2 on CI images

ci: test against docker-compose v1+v2

---

internal/controllers/core/cluster/reconciler.go
internal/engine/buildcontrol/build_control.go
internal/engine/buildcontrol/build_control_test.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/store/hold.go
web/src/Hold.tsx
web/src/SidebarItemView.tsx
web/src/status.test.tsx
web/src/status.tsx

Please review the following commits I made in branch nicks/clusterwait:
909cce1c920a408abfd47740c2d325fbc3b23a90 (2021-12-13 19:08:46 -0500)
buildcontrol: wait on cluster connection

buildcontrol: wait on cluster connection

---

scripts/release-update-tilt-docs-repo.sh

Hello @nicks,
Please review the following commits I made in branch nicks/cli-toc:
bfbb9f4073ff189e0232a687e198ef4b65978a0e (2021-12-16 09:50:15 -0500)
release: regenerate the CLI toc

release: regenerate the CLI toc

---

internal/tiltfile/k8s.go
internal/tiltfile/k8s_custom_deploy.go
internal/tiltfile/k8s_custom_deploy_test.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/value/image.go
internal/tiltfile/value/image_test.go
internal/tiltfile/value/label.go
internal/tiltfile/value/path.go
internal/tiltfile/value/string.go

Hello @milas,
Please review the following commits I made in branch nicks/kapp-imagemap2:
e7778b5c430cf2cb4c76e1407cdf683e44898fec (2021-12-16 16:52:19 -0500)
tiltfile: add image deps to k8s_custom_deploy
bd66090651852012ec96ff42f5df9871446ba176 (2021-12-16 16:52:00 -0500)
kubernetesapply: add images to custom commands

tiltfile: add image deps to k8s_custom_deploy

---

internal/k8s/client.go
internal/k8s/client_test.go

Please review the following commits I made in branch nicks/ch13123:
a253cd2eef6db8545aae8a0b023decdbb6f43b4c (2021-12-17 12:55:31 -0500)
k8s: add better error handling for status 413 (entity too large)
Fixes https://github.com/tilt-dev/tilt/issues/5279

k8s: add better error handling for status 413 (entity too large)

---

scripts/release-ci.sh
scripts/release-update-homebrew-core.sh

Hello @nicks,
Please review the following commits I made in branch nicks/homebrew:
2cc733c873241c236825c9b08fa24aa3faebe606 (2021-12-17 17:47:50 -0500)
scripts: add some homebrew checks in the release process

scripts: add some homebrew checks in the release process

---

internal/cli/wire_gen.go
internal/controllers/core/cmdimage/reconciler.go
internal/controllers/core/cmdimage/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/cmdimage3:
2890f6417d3f08b9b7cc567be27cc0789d42e368 (2021-12-20 19:25:25 -0500)
controllers: add CmdImage scaffolding

controllers: add CmdImage scaffolding

---

internal/engine/uiresource/subscriber.go

Hello @milas,
Please review the following commits I made in branch nicks/uiresource:
f9bf23f696e161fa7f076e2abf9a416784ad802a (2021-12-21 11:35:17 -0500)
uiresource: aggregate errs instead of bailing early

uiresource: aggregate errs instead of bailing early

---

internal/cli/wire_gen.go
internal/controllers/core/tiltfile/buildsource.go
internal/controllers/core/tiltfile/reconciler.go
internal/controllers/core/tiltfile/reconciler_test.go
internal/controllers/core/tiltfile/wire.go
internal/controllers/indexer/requeuer.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/buildsource:
da971939c63c342e1b88d4a1ee14a502ad4794ab (2022-01-03 13:51:27 -0500)
controllers: factor out a generic requeue mechanism

controllers: factor out a generic requeue mechanism

---

internal/controllers/manager.go

bbb7cf77f68ca548004f602a54c8d5f7f23fa672 (2022-01-07 10:36:27 -0500)
controllers: filter out transient reconciler errors

controllers: filter out transient reconciler errors

---

internal/controllers/core/cluster/reconciler.go
internal/controllers/core/cluster/reconciler_test.go
internal/controllers/fake/fixture.go

Report a metric about Cluster connections. The primary goal here
is to allow us to determine how often users are running into
Cluster connection issues. Currently, there's no granularity beyond
successful or in an error state.

api: track Cluster connection events as a metric

---

internal/cli/wire_gen.go
internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go
internal/engine/upper_test.go

to allow us to track how many users have opted into experimental features

tiltfile: report enabled features

---

internal/engine/session/controller.go
internal/engine/session/controller_test.go
internal/engine/session/conv.go

Please review the following commits I made in branch nicks/status2:
d85eb969cb8510c4081dc1fc6bc3766cf97294fa (2022-01-20 18:40:29 -0500)
session: use RuntimeStatus and PodReadinessMode to derive CI state
This leans more on RuntimeStatus as the "source of truth"
and the logic in the tiltfile about inferring whether something
is a job or a server.
fixes https://github.com/tilt-dev/tilt/issues/5394

session: use RuntimeStatus and PodReadinessMode to derive CI state

---

integration/event_test.go
internal/store/actions.go

Hello @nicksieger, @milas,
Please review the following commits I made in branch nicks/event:
3a9664c3b86ac768dd16f0d87c308f0723501f2a (2022-01-25 16:07:24 -0500)
store: tweak event display

store: tweak event display

---

internal/build/docker_builder.go

Please review the following commits I made in branch nicks/ignore:
5b4dd90ea3bde9b5b91af93915be703ffe4081b6 (2022-01-27 17:54:10 -0500)
build: Trick buildkit into not reading .dockerignore
Fixes https://github.com/tilt-dev/tilt/issues/5415

build: Trick buildkit into not reading .dockerignore

---

internal/hud/server/gorilla/origin.go
internal/hud/server/server.go
internal/hud/server/websocket.go
web/src/AppController.ts

Hello @lizzthabet, @nicksieger,
Please review the following commits I made in branch nicks/issue5403:
daadc4613459241dbbeaa77ab7a46b142519cb5d (2022-01-28 19:10:40 -0500)
web: add a CSRF token to the websocket. Fixes https://github.com/tilt-dev/tilt/issues/5403

web: add a CSRF token to the websocket. Fixes https://github.com/tilt-dev/tilt/issues/5403

---

internal/controllers/core/cluster/reconciler.go
internal/controllers/core/tiltfile/buildsource.go
internal/controllers/core/tiltfile/log.go
internal/engine/buildcontroller.go
internal/engine/k8srollout/podmonitor.go
internal/store/logger.go

just to make it simpler to log to a given manifest + span

store: add WithManifestLogHandler

---

internal/controllers/core/extension/reconciler.go

Please review the following commits I made in branch nicks/reconcile:
dd3dc7a3ca532adf0f48546f3019fc8322ab3106 (2022-02-02 10:04:36 -0500)
extension: reorganize update() to be more level-triggered
This will make it easier to re-use the extension reconciler from within
the tiltfile loader.

extension: reorganize update() to be more level-triggered

---

web/src/OverviewTable.test.tsx
web/src/OverviewTable.tsx
web/src/OverviewTableColumns.tsx
web/src/OverviewTableStatus.tsx

Please review the following commits I made in branch nicks/rerender:
8ded04be0121e90f1b6d1e59a664c9e64d64570a (2022-02-09 18:26:31 -0500)
web: convert OverviewTable.test to react-testing-library

web: convert OverviewTable.test to react-testing-library

---

internal/controllers/core/kubernetesdiscovery/keys.go

Hello @milas,
Please review the following commits I made in branch nicks/cluster4:
0f9faba0ad91222b2751c62f043bacd326be0e3d (2022-02-14 10:42:03 -0500)
controllers: fix cluster NPE

controllers: fix cluster NPE

---

web/src/SidebarResources.tsx
web/src/analytics.ts

Hello @nicks,
f81356c6ff30902e74de31e931fe2b6800072ab9 (2022-02-15 18:03:21 -0500)
Revert "web: proposal - add a small show more button in each section with more than 20 items (#5483)"
This reverts commit 4b00780f388ba66ac0af681af6860dbfa5cce80a.

Revert "web: proposal - add a small show more button in each section with more than 20 items (#5483)"

---

internal/hud/server/websocket.go
internal/hud/server/websocket_test.go

Hello @landism, @lizzthabet,
Please review the following commits I made in branch nicks/batch2:
d829bf429cb48810e7dc9508eb45517f55cf2076 (2022-02-17 09:56:52 -0500)
server: batch websocket messages
this should improve performance a lot

server: batch websocket messages

---

internal/engine/analytics/analytics_reporter.go
internal/engine/analytics/analytics_reporter_test.go

A number of UI conversations have revolved around how many resources our users are looking at. The introduction of disabled resources means that when we report the resource count to analytics, any number of those resources might be disabled, and we don't know how many the user is actually looking at.
Explicitly report how many resources are enabled.
(also, while I was here, I noticed we were reporting counts for k8s and DC resources, but not local, and figured I might as well)

analytics: report counts of enabled, local resources

---

internal/controllers/core/kubernetesapply/reconciler.go

This was inside of the entity loop, so it was possible to get both
"no images injected" along with a list of injections for a single
resource if not all entities had an image injected, which was very
confusing. (Thanks @landism for pointing this out since evidently
I've forgotten how to read code 😬)
Thankfully, this is DEBUG logging so not particularly visible, but
the fix is easy enough to move the logging outside the loop. (Note
that `injectResults` is _exclusively_ used for logging, so this is
fine.)

api: fix confusing DEBUG logging for image injection

---

internal/hud/webview/convert.go
internal/hud/webview/convert_test.go

When a resource is disabled, its `UIResource.Status` shows things like RuntimeStatus: Error, UpdateStatus: Pending, ReadyCondition.Reason: Error, because that's what's in EngineState.
Override those fields when a resource is disabled.
I considered doing this upstream in EngineState, rather than leaving the inaccurate state in EngineState, just to try to make even more of our state consistent, but that gets complicated because the subscriber that disables DC resources uses EngineState as the source of truth to tell whether a resource is running (and thus might need to be disabled).

api: set uiresource conditions / update,runtime status when disabled

---

web/src/ApiButton.stories.tsx
web/src/BulkApiButton.tsx
web/src/HudErrorContext.tsx
web/src/OverviewTableBulkActions.stories.tsx
web/src/OverviewTableBulkActions.tsx

Please review the following commits I made in branch nicks/ch13212:
e12689e0a441870dd71577c229cb61212c8fde60 (2022-02-22 16:52:26 -0500)
web: update the split button UI to more gracefully handle border mismatch

web: update the split button UI to more gracefully handle border mismatch

---

web/src/OverviewLogPane.tsx

Please review the following commits I made in branch nicks/shuffle:
fe4c96119035f475758668bdec96c8164db275f9 (2022-02-23 17:08:27 -0500)
web: adjust log buffering behavior to avoid screen jiggling

web: adjust log buffering behavior to avoid screen jiggling

---

web/src/ResourceGroupsContext.test.tsx
web/src/ResourceGroupsContext.tsx
web/src/SidebarResources.tsx

Please review the following commits I made in branch nicks/ch13283:
defc9f3f7f638a64b3926cb7edb98ed822a0c39c (2022-02-23 12:55:16 -0500)
web: fix sidebar keyboard navigation for labels

web: fix sidebar keyboard navigation for labels

---

web/src/OverviewTable.test.tsx
web/src/OverviewTable.tsx
web/storybook.tiltfile

Please review the following commits I made in branch nicks/ch13347:
e02266eec5bdf61bcdff6f9f0634aafbbe8de669 (2022-02-28 14:04:25 -0500)
web: adjust background color on selected rows

web: adjust background color on selected rows

---

web/storybook.tiltfile

Please review the following commits I made in branch nicks/storybook2:
6b60da62ada725ff55da38d2ec1a4164ce2a85a6 (2022-03-01 13:28:00 -0500)
storybook: tweak the storybook tiltfile so that it works on preview.tilt.build

storybook: tweak the storybook tiltfile so that it works on preview.tilt.build

---

web/src/OverviewResourceSidebar.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/usememo:
c34d6d53347b9102168f699939a5bd921d41f0c0 (2022-03-02 10:29:11 -0500)
web: fix an incorrect use of useMemo

web: fix an incorrect use of useMemo

---

internal/cli/wire_gen.go
internal/controllers/core/dockercomposeservice/reconciler.go
internal/controllers/core/dockercomposeservice/reconciler_test.go
internal/controllers/wire.go
internal/engine/buildcontrol/wire_gen.go
internal/engine/upper_test.go
internal/engine/wire_gen.go
pkg/apis/core/v1alpha1/register.go

Hello @nicks,
Please review the following commits I made in branch nicks/dc3:
517e791c151ed7d5963253794eee9e07a6619237 (2022-03-02 11:17:11 -0500)
dockercomposeservice: reconciler scaffolding

dockercomposeservice: reconciler scaffolding

---

internal/store/kubernetesdiscoverys/reducers.go
internal/store/kubernetesdiscoverys/reducers_test.go

Please review the following commits I made in branch nicks/npe:
b7e046f7d0e008eea306457aaab869c39f7bab7f (2022-03-01 22:01:36 -0500)
store: fix a segfault when reorganizing resources

store: fix a segfault when reorganizing resources

---

web/src/SidebarItemView.tsx

Please review the following commits I made in branch nicks/ch13353:
920c9a54406d503c5657b54cefc865aa5260cea3 (2022-03-02 10:27:19 -0500)
web: scroll when a sidebar item is selected

web: scroll when a sidebar item is selected

---

.circleci/Dockerfile.integration
.circleci/config.yml
Makefile

Hello @nicks,
2dfffb7ae490587a64911ad809521ba1e02157b9 (2022-03-07 14:06:40 -0500)
circleci: bump test containers

circleci: bump test containers

---

web/src/BuildButton.tsx
web/src/OverviewTable.test.tsx
web/src/OverviewTable.tsx
web/src/OverviewTableColumns.tsx
web/src/OverviewTableStarResourceButton.tsx
web/src/OverviewTableStatus.tsx
web/src/ResourceStatus.ts

Hello @lizzthabet, @surbhisgupta,
Please review the following commits I made in branch nicks/ch13282:
ac1b356cdd2c331ef7e2377a9837d4cfa9908f31 (2022-03-04 19:11:38 -0500)
web: table styling pass
9ddbbb3df99694e8fb4066939c4d6e08116de62b (2022-03-04 16:15:54 -0500)
web: update the gray scale to match what's in figma

web: table styling pass

---

web/src/OverviewTable.tsx
web/src/OverviewTableColumns.tsx
web/src/OverviewTableStatus.tsx
web/src/Tooltip.tsx

Please review the following commits I made in branch nicks/tooltip2:
4df5549b5b0be72ca8024f0d1b26e414f8fca8e7 (2022-03-10 15:01:41 -0500)
web: fix the Mode tooltip, and make sure the tooltip icons don't shrink

web: fix the Mode tooltip, and make sure the tooltip icons don't shrink

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/ci2:
28fafcfaba3f5581e01ce39d2ffa240e0e824358 (2022-03-11 14:47:31 -0500)
circleci: update extensions image

circleci: update extensions image

---

.goreleaser.yml

Hello @milas,
Please review the following commits I made in branch nicks/cross:
0ecf00c4a6e894b89d9e0edecf6461522e5e4978 (2022-03-11 17:31:35 -0500)
goreleaser: set up c++ crosscompiler for tree-sitter

goreleaser: set up c++ crosscompiler for tree-sitter

---

internal/controllers/core/dockercomposeservice/reconciler.go
internal/engine/upper.go
internal/store/dockercomposeservices/actions.go
internal/store/dockercomposeservices/reducers.go
internal/store/engine_state.go

Hello @nicks,
Please review the following commits I made in branch nicks/dc8:
e4cb9bd0138043655a01087d8f589668589fc1fd (2022-03-14 14:38:24 -0400)
store: add actions and reducers for syncing dockercompose api objects

store: add actions and reducers for syncing dockercompose api objects

---

internal/controllers/core/dockercomposeservice/reconciler.go
internal/controllers/core/dockercomposeservice/reconciler_test.go

Please review the following commits I made in branch nicks/dc10:
db9f462c5524c5e77b756a086af945feab0822e5 (2022-03-16 12:10:30 -0400)
dockercomposeservice: auto-apply when images change

dockercomposeservice: auto-apply when images change

---

internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/reconciler_test.go
internal/store/build_result.go

Please review the following commits I made in branch nicks/dc13:
d6ed12ee69422dfb8d68619bd5da6a9cd7d1a06c (2022-03-18 12:27:50 -0400)
liveupdate: remove some state tracking that i'm pretty sure is unnecessary

liveupdate: remove some state tracking that i'm pretty sure is unnecessary

---

internal/controllers/core/liveupdate/monitor.go
internal/controllers/core/liveupdate/reconciler.go
internal/controllers/core/liveupdate/reconciler_test.go
internal/controllers/core/liveupdate/resource.go
internal/dockercompose/state.go

Please review the following commits I made in branch nicks/dc15:
53c281cb3e364caf9dd4cb749ac2c6086d86c650 (2022-03-21 11:23:32 -0400)
liveupdate: update the reconciler to support dockercompose selectors

liveupdate: update the reconciler to support dockercompose selectors

---

web/src/GlobalNav.tsx
web/src/HelpDialog.stories.tsx
web/src/HelpDialog.test.tsx
web/src/HelpDialog.tsx
web/src/OverviewTable.tsx
web/src/OverviewTableKeyboardShortcuts.tsx
web/src/ResourceSelectionContext.tsx
web/storybook.tiltfile

Please review the following commits I made in branch nicks/ch13285:
96dc53c5a9cca037845b9b6dfe5d42dc82637a77 (2022-03-08 20:11:40 -0500)
web: keyboard shortcuts for navigating the overview table

web: keyboard shortcuts for navigating the overview table

---

web/src/OverviewSidebarOptions.test.tsx
web/src/OverviewSidebarOptions.tsx
web/src/OverviewTableDisplayOptions.tsx
web/src/SidebarItemView.tsx
web/src/SidebarResources.tsx
web/src/resourceListOptionsButtons.tsx

Please review the following commits I made in branch nicks/ch13409:
66c135266e63e90d5cce5c1c9c3110bee09429fd (2022-03-29 13:23:35 -0400)
web: add the expand/collapse buttons to the sidebar

web: add the expand/collapse buttons to the sidebar

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/dockerversion:
6a147acb8af913b3f0b0d1ef657c8d6fa10e8d6f (2022-04-06 16:29:04 -0400)
circleci: bump remote docker version

circleci: bump remote docker version

---

internal/controllers/core/dockercomposeservice/reconciler_test.go
internal/controllers/fake/fixture.go
internal/store/dockercomposeservices/reducers.go

Please review the following commits I made in branch nicks/dclogs2:
4e2cd07b13d7f3c0581e390424a118aa3aae46a2 (2022-04-06 18:48:29 -0400)
dockercompose: fix a dumb bug that broke state propagation :(

dockercompose: fix a dumb bug that broke state propagation :(

---

internal/controllers/core/liveupdate/reconciler.go

Hello @nicks,
Please review the following commits I made in branch nicks/liveupdate11:
fd165c487b58861ae94de8d55c3937177018ea0f (2022-04-07 12:59:36 -0400)
liveupdate: remove some dead code

liveupdate: remove some dead code

---

internal/engine/buildcontrol/build_control.go
internal/engine/buildcontroller.go
pkg/model/image_target.go
pkg/model/manifest.go

Hello @milas, @lizzthabet,
Please review the following commits I made in branch nicks/cluster10:
a720cef92414a91d4cce4a1c8733fedbbee1dee3 (2022-04-07 13:48:20 -0400)
model: populate cluster names on images

model: populate cluster names on images

---

internal/controllers/core/cluster/reconciler.go

This was previously in the Tiltfile reconciler as part of the
call to `DecideRegistry`, which is no longer used (and imminently
being removed).
Because it's logged on connection initialization, it will only
occur 1x per cluster client initialization. (That does mean that
if you change the spec and/or delete+recreate, it'll get logged
again once it re-initializes the client, but that's arguably a
good thing IMO!) The important part is that it doesn't log on
every reconcile, which could get spammy very fast.

cluster: log default registry information

---

internal/tiltfile/tiltfile_state.go

This message is confusing and has gone through several iterations.
Fixes #5693.

tiltfile: improve warning for images but no resources

---

internal/controllers/core/podlogstream/podlogstreamcontroller_test.go

Reconciliation is async, so use `require.Eventually`. Other tests
doing similar things here were already using this pattern.
Fixes #5441.

podlogstream: fix flaky test

---

integration/ignores/.dockerignore
integration/ignores/.tiltignore
integration/ignores/Dockerfile
integration/ignores/Tiltfile
integration/ignores/compile.sh
integration/ignores/deployment.yaml
integration/ignores/ignored_by_dockerignore.txt
integration/ignores/ignored_by_tiltfile.txt
integration/ignores/ignored_by_tiltignore.txt
integration/ignores/main.sh
integration/ignores/restart.sh
integration/ignores/source.txt
integration/ignores/start.sh
integration/ignores_test.go

Hello @nicksieger,
Please review the following commits I made in branch nicks/ignores:
9a5876d3449c06176486ae8484f7a2cab0796e3d (2022-04-22 15:54:49 -0400)
test: add integration tests for ignore behavior
inspired by discussion on https://github.com/tilt-dev/tilt/issues/5651,
and realized we didn't have good integration tests for this behavior.

test: add integration tests for ignore behavior

---

web/src/OverviewActionBar.test.tsx
web/src/OverviewActionBar.tsx
web/src/ResourceNav.test.tsx
web/src/ResourceNav.tsx

Please review the following commits I made in branch nicks/issue5567:
d12c91ea2455b7a930256cc423881f60185335d2 (2022-04-19 12:22:55 -0400)
web: preserve filters across resource views
fixes https://github.com/tilt-dev/tilt/issues/5567

web: preserve filters across resource views

---

internal/tiltfile/api/__init__.py
internal/tiltfile/files.go
internal/tiltfile/tiltfile_test.go
internal/tiltfile/value/string.go

Hello @landism, @nicksieger,
Please review the following commits I made in branch nicks/stdin:
7cc721fb6f1a443a5bf899dea442bc5ae8e023f2 (2022-04-22 17:22:11 -0400)
tiltfile: handle stdin blobs

tiltfile: handle stdin blobs

---

internal/cli/demo.go

This got unintentionally flipped during some `--hud` / `--legacy`
flag cleanup.
I removed the (hidden) flags from `tilt demo` entirely as they were
not used, even by tests.

demo: use prompt terminal interface (not TUI)

---

web/jest.config.ts
web/package.json
web/src/setupTests.ts
web/yarn.lock

This PR should wait on #5733 being merged first. Closes [ch13478](https://app.shortcut.com/windmill/story/13478).

web: remove Enzyme dependencies and set up Jest without it

---

internal/build/custom_builder.go
internal/build/custom_builder_test.go

Currently, we pass `EXPECTED_REF`, which is the full image reference
including registry, path, and tag.
Some build scripts want to consume these independently, so in addition
to passing the full reference, this adds the individual components as
well.
There's a slight behavior change here in that previously, the registry
was passed as `REGISTRY_HOST` only in the case that
`outputs_image_ref_to` mode was being used. Now, it's _always_ passed
(if there is a local registry!) regardless of custom build mode along
with `EXPECTED_REGISTRY`, which is new and duplicative but consistent
with the other names. This should be harmless, however.
Closes #5433.

custom_build: add EXPECTED_{IMAGE,TAG,REGISTRY} env vars

---

internal/docker/client_test.go
internal/docker/env.go

Please review the following commits I made in branch nicks/rancher-desktop:
54602f1fe5be7eba28966b82cec1e462e04e83bd (2022-05-01 12:58:59 -0400)
docker: whitelist default host strings
fixes https://github.com/tilt-dev/tilt/issues/5751

docker: whitelist default host strings

---

go.mod
go.sum
vendor/go.starlark.net/internal/compile/compile.go
vendor/go.starlark.net/internal/compile/serial.go
vendor/go.starlark.net/resolve/resolve.go
vendor/go.starlark.net/starlark/eval.go
vendor/go.starlark.net/starlark/hashtable.go
vendor/go.starlark.net/starlark/int.go
vendor/go.starlark.net/starlark/int_generic.go
vendor/go.starlark.net/starlark/int_posix64.go
vendor/go.starlark.net/starlark/interp.go
vendor/go.starlark.net/starlark/library.go
vendor/go.starlark.net/starlark/unpack.go
vendor/go.starlark.net/starlark/value.go
vendor/go.starlark.net/starlarkstruct/struct.go
vendor/go.starlark.net/syntax/parse.go
vendor/go.starlark.net/syntax/quote.go
vendor/go.starlark.net/syntax/scan.go
vendor/go.starlark.net/syntax/syntax.go
vendor/modules.txt

Hello @nicks,
89e0d365969e80cca33857550b607949cb27028f (2022-05-02 15:25:49 -0400)
vendor: upgrade starlark

vendor: upgrade starlark

---

internal/cli/wire_gen.go
internal/controllers/core/dockercomposelogstream/reconciler.go
internal/controllers/core/dockercomposelogstream/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/dclogs:
cb5cfefc47e75e5e2c283c3b2e26869477463476 (2022-05-03 17:24:41 -0400)
dockercomposelogstream: reconciler scaffolding

dockercomposelogstream: reconciler scaffolding

---

internal/cloud/cloud_status_manager.go
internal/cloud/cloud_status_manager_test.go
internal/engine/upper.go
internal/hud/webview/convert.go
internal/store/actions.go
internal/store/engine_state.go
pkg/apis/core/v1alpha1/generated.proto
pkg/apis/core/v1alpha1/uisession_types.go
pkg/openapi/zz_generated.openapi.go
pkg/webview/view.swagger.json
web/src/view.d.ts

Please review the following commits I made in branch nicks/suggestedversion:
18c084af80e944afd0d79a580df0cdc54acbd6e0 (2022-05-03 18:03:15 -0400)
cloud: discard suggested version from the server

cloud: discard suggested version from the server

---

internal/cloud/cloud_status_manager.go
internal/cloud/cloud_status_manager_test.go
internal/engine/upper.go
internal/hud/webview/convert.go
internal/store/actions.go
internal/store/engine_state.go
pkg/apis/core/v1alpha1/generated.proto
pkg/apis/core/v1alpha1/uisession_types.go
pkg/openapi/zz_generated.openapi.go
pkg/webview/view.swagger.json
web/src/view.d.ts

Hello @nicks,
9fdce321fec3892648ae5d01c345618fb2f867dd (2022-05-05 11:07:47 -0400)
Revert "cloud: discard suggested version from the server (#5763)"
This reverts commit 190a93087f437870db06d9231630e9baa58f44b0.

Revert "cloud: discard suggested version from the server (#5763)"

---

internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

tiltfile: actually ignore invalid resource deps

---

CONTRIBUTING.md

* Remove some outdated instructions/sections
* Update `--web-mode` info to cover embedded
* Re-organize some sections to reduce duplication
* Minor consistency tweaks because I just can't help myself
[skip ci]

docs: update CONTRIBUTING.md with latest info

---

.circleci/Dockerfile.integration
.circleci/config.yml
integration/event_test.go
integration/k8s_fixture_test.go
integration/service-account.yaml

Hello @nicks,
Please review the following commits I made in branch nicks/kinds:
17aa68ed810d54fb98057d1c63a79e54b0b40a45 (2022-05-10 19:06:00 -0400)
circleci: upgrade kind

circleci: upgrade kind

---

integration/disable/Tiltfile
internal/controllers/core/tiltfile/api.go
internal/controllers/core/tiltfile/api_test.go
internal/feature/flags.go
web/src/OverviewResourceSidebar.stories.tsx
web/src/OverviewSidebarOptions.test.tsx
web/src/OverviewSidebarOptions.tsx
web/src/OverviewTable.stories.tsx
web/src/OverviewTable.test.tsx
web/src/OverviewTable.tsx
web/src/OverviewTableBulkActions.stories.tsx
web/src/OverviewTableBulkActions.test.tsx
web/src/OverviewTableBulkActions.tsx
web/src/OverviewTableColumns.tsx
web/src/OverviewTableDisplayOptions.test.tsx
web/src/OverviewTableDisplayOptions.tsx
web/src/OverviewTablePane.stories.tsx
web/src/SidebarItemView.test.tsx
web/src/SidebarItemView.tsx
web/src/SidebarResources.test.tsx
web/src/SidebarResources.tsx
web/src/SnapshotBar.stories.tsx
web/src/feature.tsx

This has been enabled by default for a few releases now, so time
for it to go!

feature: mark the `disable_resources` flag as obsolete

---

internal/cli/disable.go
internal/cli/enable.go
internal/cli/enable_test.go
internal/testutils/uiresourcebuilder/uiresourcebuilder.go

Allows to enable/disable groups of resources by their label(s).
Fixes #5789.

cli: enable/disable take a --labels option

---

internal/engine/buildcontrol/image_build_and_deployer.go
internal/engine/upper_test.go
internal/hud/view_test.go
internal/store/k8sconv/resource.go
internal/store/k8sconv/resource_test.go
internal/store/kubernetesdiscoverys/reducers.go
internal/store/kubernetesdiscoverys/reducers_test.go

Fixes #5837
I described a few other potential solutions in a comment on the issue. This is probably my least favorite of them, but it's nice and cheap. I'm happy to entertain alternatives.

engine: don't reparse yaml on every KA/KD upsert

---

.goreleaser.yml

See tilt-dev/ctlptl#227 for background.

goreleaser: build linux/arm64 images

---

.circleci/config.yml
build.toast.yml
scripts/release.Dockerfile

ci: upgrade tilt-releaser to Docker 20.10.14

---

.circleci/config.yml
build.toast.yml
scripts/release.Dockerfile

- release: updated docker install
- ci: run release-dry-run on master

Install Docker CE + Release Dry-Run

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/extensions-ci:
c0dffc86dd233d283cf76de60fb31213a33cd51a (2022-06-15 13:53:32 -0400)
ci: update extensions image

ci: update extensions image

---

internal/controllers/core/podlogstream/podlogstreamcontroller.go
internal/controllers/core/podlogstream/podlogstreamcontroller_test.go

Hello @milas,
Please review the following commits I made in branch nicks/issue-5851:
221dad8fb97a26ee65064afc00c24c8e1bb13d1b (2022-06-16 13:47:37 -0400)
podlogstream: requeue if the pod hasn't been synced yet
fixes https://github.com/tilt-dev/tilt/issues/5851

podlogstream: requeue if the pod hasn't been synced yet

---

scripts/record-release.sh

f5b540ba2227610a6caf479cd5751fa86a93ee3e (2022-06-24 15:57:39 -0400)
scripts: use github to record releases

scripts: use github to record releases

---

CODE_OF_CONDUCT.md
SECURITY.md

Hello @nicks,
Please review the following commits I made in branch nicks/windmill:
a48d934b0d1a6b8aafcecd6eff08147949e21f2e (2022-06-24 18:08:39 -0400)
update readmes to remove references to Windmill as a separate company

update readmes to remove references to Windmill as a separate company

---

internal/cloud/cloud_status_manager.go
internal/cloud/cloud_status_manager_test.go
internal/cloud/io_test.go
internal/engine/uisession/subscriber_test.go
internal/engine/upper.go
internal/hud/server/server.go
internal/hud/webview/convert.go
internal/store/actions.go
internal/store/engine_state.go
pkg/apis/core/v1alpha1/generated.proto
pkg/apis/core/v1alpha1/uisession_types.go
pkg/openapi/zz_generated.openapi.go
pkg/webview/view.swagger.json
web/src/GlobalNav.tsx
web/src/HeaderBar.tsx
web/src/OverviewResourceBar.tsx
web/src/ShareSnapshotModal.scss
web/src/view.d.ts

Please review the following commits I made in branch nicks/cloud5:
8f8127fd5994fce88a11af73cb0260c521a1b116 (2022-06-28 17:39:04 -0400)
cloud: remove more tilt cloud signin code

cloud: remove more tilt cloud signin code

---

internal/controllers/core/filewatch/controller.go
internal/controllers/core/filewatch/controller_test.go

Hello @milas,
Please review the following commits I made in branch nicks/issue5887:
4e52d618ea259b717a4276f55d49867cfe7e3cf6 (2022-07-08 14:30:56 -0400)
filewatch: fix a bug in error handling
fixes https://github.com/tilt-dev/tilt/issues/5887

filewatch: fix a bug in error handling

---

scripts/record-release.sh

Hello @nicks,
fd1d3d242e2702e407557d395b38985bc8a18307 (2022-07-14 19:40:15 -0400)
scripts: fix bug in release script

scripts: fix bug in release script

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/macos:
a446d2dd5b74526f3df79fc45ae8e068a3de2b74 (2022-08-04 12:14:15 -0400)
circleci: upgrade xcode

circleci: upgrade xcode

---

internal/testutils/tar.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

delete minor unreachable code caused by t.Fatal

---

internal/cli/flags.go
internal/cli/snapshot.go
internal/snapshots/server.go

Please review the following commits I made in branch nicks/snapshot:
491ff8cfb77f6fa63e8148af60a4178beef8d0f1 (2022-08-11 18:21:49 -0400)
snapshot: adjust how the snapshot server binds to an address
fixes https://github.com/tilt-dev/tilt/issues/5917

snapshot: adjust how the snapshot server binds to an address

---

internal/tiltfile/api/__init__.py

Adds docs for https://github.com/tilt-dev/tilt/pull/5935

Update docs for k8s_namespace

---

.circleci/config.yml
build.toast.yml
scripts/release.Dockerfile

Signed-off-by: Nick Sieger <nick@nicksieger.com>

release: use Go 1.19 to build releases

---

internal/cli/down.go
internal/cli/down_test.go

fixes https://github.com/tilt-dev/tilt/issues/5941

cli: ignore disabled resources on 'tilt down'

---

internal/controllers/core/tiltfile/reconciler_test.go
internal/engine/upper_test.go

windows: fix some tests

---

.circleci/config.yml

circleci: update windows golang

---

.circleci/config.yml

https://discuss.circleci.com/t/default-docker-version-for-remote-docker-jobs-changing-on-september-6/45157
Signed-off-by: Nick Sieger <nick@nicksieger.com>

ci: remove remote docker version

---

.goreleaser.yml

Signed-off-by: Nick Sieger <nick@nicksieger.com>

release: exclude alpine archives from brews

---

integration/ttl_job/Tiltfile
integration/ttl_job/job.yaml
integration/ttl_job_test.go
internal/controllers/core/kubernetesdiscovery/reconciler.go
internal/controllers/core/kubernetesdiscovery/reconciler_test.go
internal/engine/upper_test.go
internal/store/k8sconv/resource.go
pkg/webview/view.pb.go

Fixes https://github.com/tilt-dev/tilt/issues/5949

kubernetesdiscovery: continue to track pods that are completed but deleted

---

internal/store/kubernetesdiscoverys/reducers.go
internal/store/kubernetesdiscoverys/reducers_test.go

Fixes https://github.com/tilt-dev/tilt/issues/5979

store: clean up the readiness check

---

internal/engine/session/controller.go
internal/engine/session/controller_test.go
internal/engine/upper.go
internal/store/sessions/actions.go

store: move the session actions into their own package

---

internal/cli/wire_gen.go
internal/controllers/core/session/reconciler.go
internal/controllers/core/session/wire.go
internal/controllers/wire.go
internal/engine/upper_test.go
pkg/webview/view.pb.go

controllers: add a dummy session reconciler

---

internal/controllers/core/session/reconciler.go
internal/engine/upper.go
internal/store/sessions/actions.go
internal/store/summary.go

firing lots of spurious events was leading to some problems

session: fix a performance regression

---

internal/controllers/core/session/conv.go
internal/controllers/core/session/reconciler_test.go
internal/controllers/core/session/status.go

This only comes up in the case where nothing else schedules a reconcile. (Lots of things schedule reconciles at random times).
Fixes https://github.com/tilt-dev/tilt/issues/6016

session: fix a logic error in scheduling

---

.circleci/config.yml

circleci: update gcp installer

---

.circleci/config.yml

only publish assets on the main branch

---

web/src/UpdateDialog.tsx

fixes https://github.com/tilt-dev/tilt/issues/6030

web: remove the tilt update promo

---

internal/cli/explain.go
internal/cli/explain_test.go

Aims to resolve https://github.com/tilt-dev/tilt/issues/6055

cli: check for args in explain command

---

web/src/OverviewActionBar.tsx
web/src/OverviewResourcePane.stories.tsx
web/src/OverviewResourcePane.test.tsx
web/src/OverviewResourceSidebar.stories.tsx
web/src/OverviewResourceSidebar.tsx
web/src/OverviewSidebarOptions.tsx
web/src/OverviewSidebarToggle.tsx
web/src/ResourceNameFilter.tsx
web/src/SidebarContext.tsx
web/src/style-helpers.ts

- adjusts the icon used to expand/collapse the sidebar
- makes it inline instead of taking up its own line

web: clean up sidebar ux

---

internal/controllers/core/dockercomposelogstream/project.go
internal/controllers/core/dockercomposelogstream/reconciler.go
internal/docker/fake_client.go

detects when logs are multiplexed and de-multiplexes them
fixes https://github.com/tilt-dev/tilt/issues/6085

dockercompose: fix bug in log decoding

---

internal/dockerfile/ast.go
internal/dockerfile/ast_test.go

fixes https://github.com/tilt-dev/tilt/issues/6083

dockerfile: format heredocs correctly

---

.circleci/Dockerfile.integration
.circleci/config.yml
Makefile

circleci: update integration tests to use kind v0.19 and docker-compose v2.18.1

---

pkg/assets/middleware.go
pkg/assets/prod.go

fixes https://github.com/tilt-dev/tilt/issues/6123

assets: add manifest.json to the static asset list

---

internal/tiltfile/api/__init__.py

Replaces https://github.com/tilt-dev/tilt.build/pull/1136

Fix link in custom_build api docs

---

internal/build/tar_test.go
internal/dockerignore/ignore.go
internal/dockerignore/ignore_test.go

fixes https://github.com/tilt-dev/tilt/issues/6129

dockerignore: tweak the directory-skipping optimization

---

.circleci/config.yml
build.toast.yml
scripts/record-release.sh
scripts/release-ci.sh
scripts/release-update-homebrew-core.sh
scripts/release-update-tilt-docs-repo.sh
scripts/release-update-tilt-repo.sh
scripts/release.Dockerfile

add libz dev, which homebrew needs to do formula bumps
centralize git settings

release: tweaks to the release pipeline

---

internal/engine/upper_test.go

this test fails a lot and i don't think it's worth keeping

test: remove a flakey test

---

internal/tiltfile/api/__init__.py
internal/tiltfile/files.go

https://github.com/tilt-dev/tilt/issues/6181

chore: add skip_crds parameter to helm functions

---

integration/env_test.go
internal/docker/client.go
internal/docker/env.go

some bits of the load sequence changes in Docker 24
Fixes https://github.com/tilt-dev/tilt/issues/6189

docker: adjust how CLI is loaded

---

internal/controllers/core/podlogstream/logwriter.go
internal/controllers/core/podlogstream/podlogstreamcontroller.go
internal/controllers/core/podlogstream/podlogstreamcontroller_test.go

fixes https://github.com/tilt-dev/tilt/issues/2487

podlogstream: handle kubelet fsnotify failures

---

internal/docker/env.go
internal/docker/env_test.go
pkg/webview/view.pb.go

fixes https://github.com/tilt-dev/tilt/issues/6197

docker: update colima socket inference

---

internal/tiltfile/api/__init__.py
internal/tiltfile/custom_build_test.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go

sets the current working directory for the custom_build command
fixes https://github.com/tilt-dev/tilt/issues/6145

tiltfile: add custom_build(dir)

---

.circleci/Dockerfile.integration
.circleci/config.yml
internal/cli/up.go
pkg/model/web.go

prepare for deprecation of cloud assets

cli: report an error if embedded assets aren't available

---

internal/docker/env.go
internal/docker/env_test.go

fixes https://github.com/tilt-dev/tilt/issues/6218

docker: support orbstack k8s docker socket

---

internal/k8s/owner_fetcher.go
internal/k8s/owner_fetcher_test.go

We introduced a circular owner reference (so one CRD gets cleaned up when another is deleted and vice versa) and found that Tilt got stuck in pending for all resources. I peeked at pprof and this looked suspicious:
```
25 @ 0x104a19594 0x1049e2d1c 0x1049e2884 0x106252da8 0x106252da9 0x106253908 0x106252d30 0x106253908 0x1062534c0 0x106d6c818 0x104a4f494
#	0x106252da7	github.com/tilt-dev/tilt/internal/k8s.(*objectTreePromise).wait+0x2e7						/root/project/internal/k8s/owner_fetcher.go:275
#	0x106252da8	github.com/tilt-dev/tilt/internal/k8s.OwnerFetcher.OwnerTreeOfRef+0x2e8						/root/project/internal/k8s/owner_fetcher.go:157
#	0x106253907	github.com/tilt-dev/tilt/internal/k8s.OwnerFetcher.ownerTreeOfHelper+0x217					/root/project/internal/k8s/owner_fetcher.go:222
#	0x106252d2f …
```

k8s: Support circular owner references

---

internal/controllers/core/cluster/reconciler_test.go
internal/controllers/core/cmd/controller_test.go
internal/controllers/core/dockercomposelogstream/reconciler_test.go
internal/controllers/core/filewatch/controller_test.go
internal/controllers/core/kubernetesdiscovery/reconciler_test.go
internal/controllers/core/podlogstream/podlogstreamcontroller_test.go
internal/controllers/core/portforward/reconciler_test.go
internal/controllers/fake/fixture.go
internal/controllers/indexer/list_test.go
pkg/webview/view.pb.go

i think this will fix a bunch of weird race conditions and test flakiness

test: use a mutex to prevent simultaneous reconcilation

---

internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/value/string.go

fixes https://github.com/tilt-dev/tilt/issues/6250

tiltfile: compose projects should default to COMPOSE_PROFILES env var

---

go.mod
go.sum
vendor/github.com/compose-spec/compose-go/cli/options.go
vendor/github.com/compose-spec/compose-go/dotenv/parser.go
vendor/github.com/compose-spec/compose-go/loader/full-example.yml
vendor/github.com/compose-spec/compose-go/loader/include.go
vendor/github.com/compose-spec/compose-go/loader/interpolate.go
vendor/github.com/compose-spec/compose-go/loader/loader.go
vendor/github.com/compose-spec/compose-go/loader/mapstructure.go
vendor/github.com/compose-spec/compose-go/loader/merge.go
vendor/github.com/compose-spec/compose-go/loader/paths.go
vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
vendor/github.com/compose-spec/compose-go/template/template.go
vendor/github.com/compose-spec/compose-go/types/bytes.go
vendor/github.com/compose-spec/compose-go/types/command.go
vendor/github.com/compose-spec/compose-go/types/develop.go
vendor/github.com/compose-spec/compose-go/types/device.go
vendor/github.com/compose-spec/compose-go/types/duration.go
vendor/github.com/compose-spec/compose-go/types/healthcheck.go
vendor/github.com/compose-spec/compose-go/types/labels.go
vendor/github.com/compose-spec/compose-go/types/options.go
vendor/github.com/compose-spec/compose-go/types/stringOrList.go
vendor/github.com/compose-spec/compose-go/types/types.go
vendor/modules.txt

fixes https://github.com/tilt-dev/tilt/issues/6249

vendor: upgrade compose-spec

---

.goreleaser.yml

if we want to add notes, we'll add them manually

goreleaser: remove the TBD placeholder

---

.circleci/config.yml

circleci: update the extensions ci image

---

.goreleaser.yml

fixes https://github.com/tilt-dev/tilt/issues/6318

goreleaser: adds web assets to release

---

.circleci/config.yml
.goreleaser.yml
build.toast.yml
scripts/release.Dockerfile

ci: update goreleaser

---

.goreleaser.yml

goreleaser: update asset packaging directory

---

.goreleaser.yml

verified with a goreleaser dry run

goreleaser: tweak web archive glob

---

internal/cli/cli.go
internal/cli/up.go
internal/controllers/klog.go
internal/controllers/klog_test.go
internal/engine/upper_test.go
pkg/webview/view.pb.go

also, wire up log-silencing code
in engine tests, because i was getting
annoyed by all the spurious logs

engine: fix a flaky tiltfile test

---

go.mod
go.sum
vendor/github.com/tilt-dev/clusterid/product.go
vendor/modules.txt

vendor: update clusterid

---

go.mod
go.sum
vendor/go.starlark.net/internal/compile/compile.go
vendor/go.starlark.net/internal/compile/serial.go
vendor/go.starlark.net/resolve/binding.go
vendor/go.starlark.net/resolve/resolve.go
vendor/go.starlark.net/starlark/debug.go
vendor/go.starlark.net/starlark/eval.go
vendor/go.starlark.net/starlark/hashtable.go
vendor/go.starlark.net/starlark/int.go
vendor/go.starlark.net/starlark/int_generic.go
vendor/go.starlark.net/starlark/int_posix64.go
vendor/go.starlark.net/starlark/interp.go
vendor/go.starlark.net/starlark/library.go
vendor/go.starlark.net/starlark/profile.go
vendor/go.starlark.net/starlark/unpack.go
vendor/go.starlark.net/starlark/value.go
vendor/go.starlark.net/syntax/options.go
vendor/go.starlark.net/syntax/parse.go
vendor/go.starlark.net/syntax/scan.go
vendor/go.starlark.net/syntax/syntax.go
vendor/modules.txt

pulls in fixes to https://github.com/google/starlark-go/issues/544

starlark: update to main

---

internal/tiltfile/tiltextension/plugin_test.go

clean up tests to work with git_subpath

tiltextension: test improvements

---

web/src/OverviewLogPane.tsx
web/src/logs.ts

fixes https://github.com/tilt-dev/tilt/issues/6415

web: classify cmdimage logs as build logs

---

.circleci/Dockerfile
.circleci/Dockerfile.integration
.circleci/config.yml
.golangci.yml
build.toast.yml
go.mod
internal/controllers/core/cmd/execer_unix_test.go
internal/controllers/core/kubernetesdiscovery/portforwards.go
internal/engine/buildcontrol/docker_compose_build_and_deployer.go
internal/engine/dockerprune/docker_pruner.go
internal/hud/webview/convert.go
internal/k8s/client_test.go
internal/k8s/watch_test.go
internal/store/engine_state.go
internal/store/subscriber.go
internal/tiltfile/tiltfile_state.go
pkg/apis/core/v1alpha1/uibutton_types.go
pkg/logger/env_test.go
scripts/goreleaser.sh
scripts/protobuf-helper.dockerfile
scripts/release.Dockerfile
scripts/update-codegen.sh

vendor: go 1.23, goreleaser v2

---

internal/controllers/core/cluster/reconciler.go

playing around with this a bit,
i'm not sure it's really actionable.

cluster: remove xdg runtime warning message

---

.circleci/config.yml
.goreleaser.yml

goreleaser: adjust timeout

---

internal/ospath/ospath.go
internal/watch/notify_test.go
internal/watch/watcher_darwin.go
internal/watch/watcher_naive.go

fixes https://github.com/tilt-dev/tilt/issues/6485

watch: tweak dir change events

---

internal/engine/buildcontrol/build_control.go
internal/engine/buildcontroller.go
internal/hud/view.go
internal/store/engine_state.go
internal/store/engine_state_test.go

test: fix another flaky test

---

.circleci/Dockerfile
.circleci/config.yml
.golangci.yml
Makefile

golangci-lint: update to v2

---

internal/cli/down.go
internal/cli/down_test.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/controllers/core/cluster/reconciler.go
internal/controllers/core/cluster/reconciler_test.go
internal/controllers/wire.go
internal/engine/upper_test.go
internal/k8s/kubeconfig/writer.go

fixes https://github.com/tilt-dev/tilt/issues/6554

cli: inject kubeconfig into cmds on tilt down

---

internal/tiltfile/api/__init__.py

from https://github.com/tilt-dev/tilt.build/pull/1180

api: adjust helm docs

---

internal/tiltfile/api/__init__.py

Just a small typo I noticed when reading the docs...

Fix typo in documentation

---

internal/k8s/extract.go
internal/k8s/label.go
internal/k8s/label_test.go
internal/k8s/testyaml/testyaml.go
internal/tiltfile/tiltfile_test.go

fixes
https://github.com/tilt-dev/tilt/issues/6611

k8s: fix filter_yaml on crds
