internal/cli/alpha.go, internal/cli/updog.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/subscribers.go
Please review the following commits I made in branch nicks/updog:
36177fc677615813f9cfe854f3c971312cc70f21 (2021-03-16 18:59:18 -0400)
cli: add 'tilt alpha updog', a command to experiment with the new api
a3585fc8262057c2c55104fe87f7296f9fdda2fd (2021-03-16 18:01:57 -0400)
fix
=> cli: add 'tilt alpha updog', a command to experiment with the new api

Makefile, internal/analytics/tilt_analytics_test.go
The integration CI job is failing with `Too long with no output (exceeded 10m0s): context deadline exceeded`
(circle ci page for this error is [here](https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-))
Run `gotestsum` with `--format dots`, which prints a dot every time it runs a test, and also prints stdout from failed tests at the end.
=> integration: use --format dots

internal/engine/upper_test.go
Hello @nicks,
a642b6bec8934c0252732c727be12baf2732ad80 (2021-03-17 18:24:45 -0400)
test: add a standard timeout for engine tests
=> test: add a standard timeout for engine tests

internal/engine/fswatch/action.go
Hello @milas,
e9a97ceefd3c48d4d2e1a37e7b1f9388f33251ff (2021-03-18 09:30:23 -0400)
engine: add a workaround for live-update race condition
This isn't great, but i think will let us move forward with
a better architecture without too much grief.
=> engine: add a workaround for live-update race condition

integration/crash_test.go, integration/fixture_test.go, integration/tilt.go, integration/tilt_args_test.go
Randomized port assignment wasn't playing nice with this. I
simplified the port assignment so that it's part of the main Tilt
driver fixture so that all calls will use it consistently. In the
event that a test does pass `--port` as an arg, it won't include
`TILT_PORT` on the env for that call to avoid precedence issues.
Now, when `tilt dump engine` is called, it'll have the right port
via `TILT_PORT` in env, so that the engine state can be dumped.
This also (minimally) simplifies a couple tests that needed to capture
the port and explicitly pass it back for subsequent calls, either to
intentionally simulate a port conflict or to interact with the running
engine.
=> tests: fix engine dump on test failure

internal/hud/server/apiserver_test.go, pkg/apis/core/doc.go, pkg/apis/core/v1alpha1/cmd_types.go, pkg/apis/core/v1alpha1/doc.go, pkg/apis/core/v1alpha1/filewatch_types.go, pkg/apis/core/v1alpha1/register.go, pkg/clientset/tiltapi/clientset.go, pkg/clientset/tiltapi/fake/clientset_generated.go, pkg/clientset/tiltapi/fake/register.go, pkg/clientset/tiltapi/scheme/register.go, pkg/clientset/tiltapi/typed/core/v1alpha1/cmd.go, pkg/clientset/tiltapi/typed/core/v1alpha1/core_client.go, pkg/clientset/tiltapi/typed/core/v1alpha1/fake/fake_cmd.go, pkg/clientset/tiltapi/typed/core/v1alpha1/fake/fake_core_client.go, pkg/clientset/tiltapi/typed/core/v1alpha1/fake/fake_filewatch.go, pkg/clientset/tiltapi/typed/core/v1alpha1/filewatch.go, pkg/informers/externalversions/core/v1alpha1/cmd.go, pkg/informers/externalversions/core/v1alpha1/filewatch.go, pkg/informers/externalversions/factory.go, pkg/informers/externalversions/generic.go, scripts/api-new-type-boilerplate.go.txt
Hello @milas,
Please review the following commits I made in branch nicks/core:
ea17be0fccfe83fe4df7784cc0d3d10b42747a1b (2021-03-17 16:08:45 -0400)
apis: simplify core.tilt.dev to tilt.dev
=> apis: simplify core.tilt.dev to tilt.dev

integration/local_resource_test.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/controller_test.go, internal/controllers/core/cmd/execer.go, internal/controllers/core/cmd/execer_test.go, internal/engine/local/reducers.go, internal/engine/local/servercontroller.go, internal/hud/server/controller.go
Hello @milas,
Please review the following commits I made in branch nicks/cmdprint:
b24b9076678a25745150c8cb61088096ff1cbe84 (2021-03-17 15:21:36 -0400)
local: fix assorted cmd bugs
- expose /debug/pprof (this broke during server refactor). Useful for debugging stuck goroutines
- ensure Cmd doesn't assume we're running a server
- ensure ServerCmd doesn't start Cmd while a build command is waiting
=> local: fix assorted cmd bugs

internal/cli/updog-examples/hello-world.yaml, internal/cli/updog.go, internal/cli/visitor/decode.go, internal/cli/visitor/strings.go, internal/cli/visitor/visitor.go
Please review the following commits I made in branch nicks/ch11531:
8ebac2d998e128c63f5d596e682676639fd89771 (2021-03-17 17:32:21 -0400)
cli: updog accepts configs as input
Most of the input-decoding code here is loosely adapted from ctlptl and
not super great. We should probably clean it up at some point and move
it into a common package.
kubectl's input parsing code is much more complicated because it needs to
discover types from the server before parsing anything
=> cli: updog accepts configs as input

internal/controllers/core/filewatch/controller.go, internal/controllers/core/filewatch/controller_test.go, internal/controllers/fake/fixture.go, internal/engine/fswatch/manifest_subscriber.go
These cover the reconciler basics (i.e. do we actually start watching
for files?) as well as some of the more subtle/error-prone parts
such as implicit ephemeral ignores.
On the latter front, it'd be good to do some refactoring later on and
push some of that down a level so that the code at the controller level
is a bit "dumber" and just passes a spec to something else rather than
needing to do a bunch of conversion itself. It's definitely not critical
though, and the tests here should find any regressions on that front.
Thankfully "how do specs get created from manifests" has very good
coverage in `manifest_subscriber_test.go` (i.e. what used to be the
watch manager tests). Basically, as we rip this stuff apart, we need to
make sure we're testing the right things at the right levels and …
=> filewatch: add more reconciler tests

integration/oneup_test.go
Currently, the integration tests (try to) invoke an engine dump
on failure to give state for debugging purposes.
We had a regression recently (#4318), however, where the engine dump
command was completely non-functional due to a serialization
issue. This adds an explicit call to dump the engine in one of
the tests which will catch any total breakage like this. It's
not a comprehensive test of the actual output of the engine
dump (though the CLI command ensures it's valid JSON), but
that's okay because the API of it is not stable and we're
moving away from it towards a stable interface for this type
of introspection via apiserver.
=> tests: add explicit dump engine call to an integration test

pkg/assets/dev.go
Webpack listens on IPv4, Go will happily bind to the same port
on IPv6 when we do an upfront check for the port being open.
In theory, we could just let Webpack error out and let us know
that the port is in use, but because it thinks it's running in
interactive mode, it helpfully pops up a message and offers to
let you pick a different port, which we'll never see. Running
it without any stdin attached _would_ cause it to error and
show the issue on macOS at least, but we started attaching a
dummy stdin in #3388 for other Webpack/CRA issues in the first
place (likely OS-specific), so this is a reasonable compromise.
NOTE: This will break @landism's undocumented workflow to
share a single devserver across multiple `tilt`s, but it's his
own fault for filing the bug in the first place 😉 …
=> assets: report error if webpack dev port in use

web/src/ClearLogs.tsx, web/src/LogActions.test.tsx, web/src/LogActions.tsx, web/src/LogPaneLine.scss, web/src/OverviewActionBar.tsx, web/src/OverviewLogPane.tsx
Add buttons next to "Clear logs" to adjust the font size for logs.
At a high-level, a CSS custom property (variable) is used to set
a % font size for log lines (the absolute font size is set on the
container, and the default property value is 100%).
This provides an easy and performant way for JS to adjust the log
font size, particularly since the actual log CSS is pure CSS from
an SCSS stylesheet, not using `styled-components` in React.
The scale value is read from/written to local storage under a global
(NOT Tiltfile-namespaced) key so that it's persistent and applies to
all Tilt sessions. As a bonus, that means it live synchronizes between
tabs which is kinda nifty.
Closes #4210.
=> web: add zoom in/out for logs

scripts/api-new-type.sh, scripts/update-codegen-helper.sh
1) BSD sed (by default on macOS) doesn't support `\L` so just use
`awk` which should work on anything remotely POSIX-y
2) Codegen script has `nounset` so need to check if variables are
defined in a very particular way to make Bash happy
(I have been using the `update-codegen-helper.sh` script directly after installing recent Bash via Homebrew because the Dockerized version takes 10+ mins - I found an issue at some point about its slowness which is apparently due to running `go list` an excessive number of times.)
=> scripts: codegen helper portability tweaks

internal/engine/k8swatch/actions.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/runtimelog/podlogmanager_test.go, internal/store/summary.go
Please review the following commits I made in branch nicks/pod:
2063683d7308b4bd4d3fa2d14ddbee6b83197e95 (2021-03-23 16:38:02 -0400)
store: track changed pods OnChange, and only re-run pod streamer on pod change
a5863f724d2cdbbf74728e5d2c718d4d243d0aae (2021-03-23 16:02:21 -0400)
store: simplify the summary api a bit
=> store: track changed pods OnChange, and only re-run pod streamer on pod change

internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/service_watch.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/namespace:
6ed82b7cbea44d6b648804a7ed7b2196d049cdc8 (2021-03-24 18:16:01 -0400)
k8s: remove ability to watch all namespaces
=> k8s: remove ability to watch all namespaces

internal/engine/dcwatch/event_watcher.go, internal/engine/exit/controller.go, internal/engine/exit/controller_test.go, internal/engine/k8swatch/watcher.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/upper_test.go, internal/store/mode.go
Looking towards revamping exit controller for API server world and
don't want to carry this along since it's no longer used.
There was one test removed that was specifically testing this so
was removed, and a couple others that were relying on it for Upper
to run to completion without a successful deploy that were tweaked
slightly (in one case: test was actually meant to be around `Up`
behavior, so it actually does that; in the other, a fake pod event
is emmitted and we ensure that Upper in CI mode returns cleanly.)
=> engine: remove apply mode (--watch=false remnants)

internal/controllers/core/filewatch/controller.go, internal/engine/fswatch/manifest_subscriber.go, internal/ignore/path_matcher.go
Please review the following commits I made in branch nicks/ignore2:
b28dab088739c35ce39331f148b0fd34f3a273bb (2021-03-26 15:16:24 -0400)
filewatch: refactor the ignore api a bit
0eac967e3fdd7e969ce6f5e8bf6dd674d848839d (2021-03-26 12:11:49 -0400)
filewatch: fix a missing ignore. Fixes https://github.com/tilt-dev/tilt/issues/4370
=> filewatch: refactor the ignore api a bit

internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/pod.go, internal/store/k8sconv/doc.go, internal/store/k8sconv/pod.go, internal/store/k8sconv/pod_test.go
Please review the following commits I made in branch nicks/k8sconv:
49aee7b24277064760dd95a35aa8c4cd046233dc (2021-03-30 16:12:00 -0400)
k8sconv: a new package for code the converts Kuberentes apis to internal/storage apis
=> k8sconv: a new package for code the converts Kuberentes apis to internal/storage apis

internal/engine/runtimelog/podlogmanager_test.go, internal/engine/runtimelog/podlogstreamcontroller.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/podfrominformer2:
f26fdfee368c8b4bc5d1aeae161fb18bb0f8b380 (2021-03-31 11:26:45 -0400)
engine: update podlogstreamcontroller to read pods from the cache
This is part of a general trend of having all our controllers read
from the cache directly instead of through EngineState.
=> engine: update podlogstreamcontroller to read pods from the cache

.circleci/config.yml, integration/event/Dockerfile, integration/event_test.go, internal/store/runtime_state.go, internal/store/runtime_state_k8s_test.go
If a pod is unschedulable for some reason (e.g. resource limits),
mark its status as an error instead of letting it sit in pending
indefinitely.
If the scheduling issue is resolved, the resource (i.e. the pod
from Tilt's perspective) should then transition to OK as usual.
See also #437 which originally introduced a check for this;
while the code was deleted in #4365, it was **dead code** at that
point, so this regressed at some indeterminate point in the past
when we stopped relying on watching individual containers.
(I'm assuming TBH - I don't actually know _how_ that container
watch code was used originally! 😬)
Closes #4385.
=> engine: consider Unschedulable pods as being in error state

web/src/GlobalNav.tsx, web/src/HeaderBar.stories.tsx, web/src/HeaderBar.test.tsx, web/src/HeaderBar.tsx, web/src/OverviewResourceBar.tsx, web/src/ResourceStatusSummary.tsx
As part of merging tabs + pins, we're pulling resource status + nav menu up to the top bar, where the tabs currently are.
This PR adds a new HeaderBar component that matches this design, but only in the storybook. It won't be included in the actual UI until the new starred resources component is ready.
Screenshots:
NB: there are some differences in the resource status summary between this and the design in figma:
* no vertical dividing line between resources and tests
* no "pending"
* status counts are only colored if they meet their highlight criteria (for err/warn: # => 1, for healthy: # = 100%)
I figure sorting out the resource status summary is a separate change.
I did take out the explicit status labels (the existing tilt UI says, e.g., "10/10 healthy", and the new heaer bar doesn't …
=> web: add headerbar to storybook

internal/engine/fswatch/action.go, internal/engine/upper_test.go, internal/store/engine_state.go
This fixes the somewhat legitimate flakiness experienced by one of
the tests (`TestCrashRebuildTwoContainersTwoImages`).
Previously, we added logic to avoid missed live updates, but the
safer logic means that it's possible to get a duplicate change:
in the case of the test that was failing intermittently, it had two
image targets that watched overlapping sets of files. If `foo` is
changed, once `img1` target sees the event, it adds a record to its
pending file set for `time.Now()`, and a build is triggered.
Then, `img2` target sees the *same* event, and adds a record to its
pending file set for `time.Now()`, which will _intentionally_ not
be cleared after the build finishes because it appears to have been
a change that came from _after_ the build was started. As a result,
it'll end up …
=> filewatch: avoid accepting stale/duplicate events

internal/engine/runtimelog/podlogmanager_test.go, internal/k8s/fake_client.go
Hello @milas,
Please review the following commits I made in branch nicks/truncate:
d2a475bc3004ab9a130492f53004fa26a83c2372 (2021-04-06 15:20:55 -0400)
test: consistently truncate time when streaming logs
=> test: consistently truncate time when streaming logs

internal/cli/updog_get_test.go, internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/hud/server/apiserver.go, internal/hud/server/apiserver_test.go, internal/hud/server/controller.go
Hello @milas,
Please review the following commits I made in branch nicks/memconn:
0bc947e0cea346dd57f4add56b442302687495ae (2021-04-07 00:00:22 -0400)
server: listen on the memory connection only
this will temporarily break 'tilt alpha get'
while we transition to the new system
=> server: listen on the memory connection only

internal/engine/session/conv.go, pkg/apis/core/v1alpha1/session_types.go, pkg/openapi/zz_generated.openapi.go
Missed an desired rename here (`Reason` -> `WaitReason`) and a
few of these had mismatched/missing JSON field names from
continuous changes.
Also renamed a misnamed var in the conversion.
=> session: clean up data model fields

.circleci/config.yml, scripts/check-codegen.sh, scripts/update-codegen-helper.sh
This script tries to be smart and only run if the commit changed something under `pkg/apis` or `pkg/openapi` so it won't slow down CI in most cases.
If there was a modified file, it runs the codegen script and ensures there's no modified files in the repo afterwards.
=> test: add a check to ensure codegen is in sync as part of CI

web/src/HeaderBar.tsx, web/src/OverviewItemView.tsx, web/src/OverviewPane.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/SidebarItemView.stories.tsx, web/src/SidebarItemView.tsx, web/src/SidebarPinButton.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx, web/src/StarredResourceBar.tsx
* pins have been replaced by stars
* pins/stars and tabs were serving pretty similar purposes, so we've replaced both the "pinned items" section in the sidebar and the horizontal tab bar across the top with a single starred items bar across the top
* "all resources" is now in the header bar next to the tilt logo instead of showing up as a pseudo resource in the sidebar
This PR is mostly just changing the UI to make use of recently merged components. If you want more context on those, here are their PRs:
* ResourceStatusSummary - https://github.com/tilt-dev/tilt/pull/4411
* StarredResourceBar - https://github.com/tilt-dev/tilt/pull/4398
* HeaderBar - https://github.com/tilt-dev/tilt/pull/4393
* Actually change all the "pin" names in the code to "star"
* Delete the tabs code
=> web: use starred resource bar instead of tabs and pinned section

web/src/OverviewItemView.tsx, web/src/OverviewPane.test.tsx, web/src/OverviewPane.tsx
(previously there was a "pinned items" section at top)
=> web: use starred resource bar on overview pane

web/src/SidebarItemView.tsx, web/src/StarredResourceBar.stories.tsx, web/src/StarredResourceBar.tsx, web/src/style-helpers.ts
If a resource is selected, building, and starred, it shows up in the starred resource bar as white on white:
1. Copy the rest of the sidebaritemview css that adds the barberpole animation to building resources
2. move the .isSelected selector lower down so that the gray foreground takes precedence so that things are actually readable
(but animated)
=> web: fix css of selected+building+starred resource

internal/cli/alpha.go, internal/cli/delete.go, internal/cli/delete_test.go
Please review the following commits I made in branch nicks/ch11864:
8ab9e3120b1da4d99e68bd31a6feb17b1aac9759 (2021-04-14 12:20:22 -0400)
cli: add tilt alpha delete
=> cli: add tilt alpha delete

internal/tiltfile/sys/sys.go, internal/tiltfile/sys/sys_test.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/ch11874:
3fcb25f3d0b61e866c9338f6d9138287bcfc6ece (2021-04-14 17:02:23 -0400)
tiltfile: add sys.executable
We want to write tilt extensions that use tilt get, tilt apply,
etc to mutate things on the fly, so we need a way for extensions
to reliably find the tilt binary.
=> tiltfile: add sys.executable

internal/engine/session/controller_test.go, internal/engine/session/conv.go
The revised logic for session (which currently is really just used
for `tilt ci` to monitor when it's time to exit) does not share
all the logic with the internal engine due to needing more
granularity.
There was a slight behavior difference here which made it
unintentionally stricter for K8s resources - as long as a Pod is
in the `Running` phase, in the engine model, it's `RuntimeStatusOK`
if all containers are ready and `RuntimeStatusPending` if not.
Some fall-through logic in session meant that it'd end up in a
weird state with both `Active` and `Terminated` with the container
error on `Terminated` which took precedence.
This makes the logic closer to the `K8sRuntimeState::RuntimeStatus()`
and returns early once it determines proper state, eliminating a lot
of the subtlety in the …
=> session: k8s resource status consistency

internal/cli/create.go, internal/cli/create_filewatch.go, internal/cli/create_filewatch_test.go
Hello @milas,
Please review the following commits I made in branch nicks/filewatch:
c19e97125bab67bf458672ed32e8002752e7dca4 (2021-04-14 18:51:40 -0400)
cli: add tilt alpha create filewatch
ed7bbc6a74e6d380594dc598a360f6219fca4875 (2021-04-14 17:32:58 -0400)
cli: add tilt alpha create
=> cli: add tilt alpha create filewatch

internal/controllers/core/podlogstream/podlogstreamcontroller.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/pod.go, internal/engine/portforward/controller_test.go, internal/engine/session/controller_test.go, internal/hud/webview/convert_test.go, internal/store/runtime_state.go
Purely mechanical - removed the type alias in `store` package.
(This was way fewer changes than I thought it was going to be, which is why I'd planned to do it as its own PR 🤷)
=> engine: remove type alias for Container

internal/engine/build_and_deployer_live_update_test.go, internal/engine/buildcontrol/live_update_build_and_deployer.go
Please review the following commits I made in branch nicks/display:
2607e702dd6ee907e9afe608cc9c02d73e7d8ae1 (2021-04-20 10:34:50 -0400)
engine: truncate list of files in live_update display
=> engine: truncate list of files in live_update display

internal/controllers/core/podlogstream/podlogstreamcontroller_test.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/k8srollout/podmonitor.go, internal/engine/k8srollout/podmonitor_test.go, internal/engine/pod.go, internal/engine/portforward/controller.go, internal/engine/portforward/controller_test.go, internal/engine/session/controller_test.go, internal/engine/upper_test.go, internal/hud/webview/convert_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/store/runtime_state.go, internal/testutils/manifestutils/manifest.go
Purely mechanical change to get rid of the transitional type alias.
See #4448 for the introduction of the type alias and migration of
logic to use the API type rather than the old `store.Pod` type.
Note that there are still some helper methods in `store` that _really_
shouldn't be there, but with the current package dependency tree,
there isn't any easy/obvious place to move them.
As part of broader Pod discovery API server refactoring, they'll find
a better home and get moved around; most of these should probably be
unexported functions that live alongside the logic that depends on
them.
=> store: remove Pod alias and use canonical API type

internal/engine/portforward/actions.go, internal/engine/portforward/reducers.go, internal/engine/portforward/types.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/summary.go, internal/store/types.go
trying to keep PRs smallish -- will use these actions in a future PR to
store API PortForward objects on state whenever we create/delete them
via the API
=> portforward: port forward actions for writing API portforward's back to engine state [ch11906]

pkg/model/logstore/logstore.go
When searching for a matching manifest, if we never found it, we
could go negative on the index because the loop was using the wrong
variable.
In a normal `tilt up`, this would never be hit, since we would not
be looking for logs for a non-existent manifest.
When running `tilt logs`, it's possible to pass a resource name,
so an easy way to hit this would be with a typo. But also due to
the way logs are streamed combined with truncation, if you tried
to follow `bar` but only got logs for `foo`, the client would not
know about `foo` at all so would trigger this case even though it
is actually a legitimate manifest.
Now it'll fail to find it and fall-through to the `-1` case as it
should.
Fixes #4453.
=> cli: fix panic following logs for non-existent resources

internal/store/manifest_target.go, internal/store/manifest_target_test.go
Please review the following commits I made in branch nicks/dupecmds:
bc75d0ae2197c81cc48bc9306b12df90156c180a (2021-04-21 17:37:42 -0400)
store: fix a race condition where sometimes we would start a server twice
=> store: fix a race condition where sometimes we would start a server twice

internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/ref.go, internal/k8s/ref_test.go, internal/k8s/uid.go, internal/k8s/uid_test.go, internal/store/build_result.go, internal/store/json_test.go, internal/store/runtime_state.go, internal/testutils/podbuilder/podbuilder.go
This is in preparation for `PodDiscovery` API work.
The motivation here is that currently, the engine extracts some
details about the objects it's managing from the specs, i.e. what
it "expects" to deploy. These are gathered across all manifests to
determine which namespaces to watch in the cluster.
Indepedently, the deployer stores the UIDs, but that loses the
mapping back to namespace. Currently, it's not an issue because of
the aforementioned logic determining which namespaces to watch.
With the move to apiserver, the semantics will be slightly different;
each manifest will define the ancestor UID + namespaces it cares
about. The reconciler will handle ensuring only 1x watch per namespace
is created for efficiency, but the key is that the spec needs to
include the UID + namespace …
=> engine: track deployed object refs

internal/engine/buildcontroller_test.go, internal/engine/k8swatch/actions.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/pod.go, internal/engine/pod_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/k8sconv/pod.go, internal/store/runtime_state.go
This is another incremental change; it _mostly_ shifts the conversion
logic out of the action handler. The other biggest change is that it
now completely replaces the tracked Pod objects instead of getting a
reference and mutating it - this shifts some of the logic about
whether to track up a level. This gets the logic closer to its
eventual state as part of a reconciler based on the patterns we've
been following.
The actual action is still a change for a single Pod rather than a
`PodDiscoveryStatus` update, but the changes are large enough for
this chunk that it made since to use this as an increment.
~~(⚠️ This needs the changes from #4458, so I'll rebase once that's merged; diff might be chaotic in the interim)~~
=>  engine: use v1alpha.Pod for pod change events

web/src/alerts.test.ts, web/src/alerts.ts
Please review the following commits I made in branch nicks/alert:
e1df6a0630eaece7eb70284720d7340014042049 (2021-04-27 18:15:48 -0400)
web: remove alert fields no longer in use
=> web: remove alert fields no longer in use

pkg/model/logstore/logstore.go, pkg/model/logstore/logstore_test.go, web/src/LogStore.test.ts, web/src/LogStore.ts
Please review the following commits I made in branch nicks/logstore:
cfb1e8b4ceab8491cc8fae42c9060d47766e5cd4 (2021-04-28 14:40:37 -0400)
logstore: raise the log limit, and truncate by both recency and length
fixes https://github.com/tilt-dev/tilt/issues/4476
=> logstore: raise the log limit, and truncate by both recency and length

.goreleaser.yml
Not exhaustive by any means but took a quick look at some common
prefixes that aren't useful for the changelog and added them.
```
git log --pretty=format:%s | cut -d':' -f1 | sort | uniq -c | sort -r
```
FWIW the releaser bot itself doesn't use a prefix for version bumps, now that `ci:` is in the list, might be a good candidate?
=> ci: add some more exclude patterns for changelog

internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/k8s/target.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go, pkg/model/k8s_target.go, pkg/model/manifest_test.go
Extra pod labels come in as one or more maps of label keys and values
(`[]labels.Set`). Once converted into a list of `labels.Selector`,
it can be used for matching, but introspecting it is more difficult,
as it requires conversion, which produces a list of
`labels.Requirement`. The biggest problem that introduces is that
`labels.Requirement` is more expressive, so backwards conversion
means a bunch of error-handling for (what should be) impossible
cases.
This just passes the `labels.Set`s as they're parsed from the
`Tiltfile` through and stores them that way on the target in state.
Once they're actually used, they get converted to the actual
`labels.Selector`s for matching.
This will simplify the new intermediary step where they'll get
converted to API label selector objects, so that …
=> k8s: defer extra pod labels conversion to labels.Selector

internal/engine/portforward/subscriber_test.go, internal/k8s/fake_client.go
splitting out some of the changes in #4483 to reduce headaches
this change makes the FakePortForwardClient aware of its whole call history rather than just the last call it made, which lets us test that we're correctly handling e.g. a single pod with multiple port forwards
=> k8s/portforward: FakePortForwardClient knows its whole call history

internal/controllers/core/cmd/execer.go, internal/controllers/core/cmd/execer_unix_test.go, pkg/apis/core/v1alpha1/cmd_types.go, pkg/apis/core/v1alpha1/generated.proto, pkg/openapi/zz_generated.openapi.go
Please review the following commits I made in branch nicks/ch11952:
bee2771ebd947779b1986fc02bf1d811eba48ceb (2021-04-29 20:49:50 -0400)
cmd: Cmd Terminated should rely on Process Wait() semantics instead of Go Cmd Wait() semantics
The Go semantics are not what most people expect, and even Go team is considering changing them.
=> cmd: Cmd Terminated should rely on Process Wait() semantics instead of Go Cmd Wait() semantics

internal/engine/portforward/actions.go, internal/engine/portforward/subscriber.go, internal/k8s/client_test.go, internal/store/k8sconv/pod.go
Okay I think this is a better version of https://github.com/tilt-dev/tilt/pull/4483
As per [@milas's proposed new migration plan](https://tilt-dev.slack.com/archives/C01KM01RY64/p1619729063100900), this is step 1: 
> introduce API model, replace all similar objects with it and use for diffing/etc but don't store it in EngineState or apiserver
In the next PR, I will
1. store PortForward state on the EngineState, and
2. move responsibility for running/stopping PF's into a new `PortForwardReconciler` subscriber (which won't actually touch the API server yet will just read PF's off the EngineState)
=> portforward: reimplement current port forward behavior with api objects [ch11953]

internal/engine/k8srollout/podmonitor.go, internal/engine/pod.go, internal/engine/portforward/subscriber.go, internal/engine/runtimelog/podlogmanager.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/k8sconv/pod.go
99.9% of the time, a Pod will only be associated with one manifest,
both because that's the general usage pattern aside from some Helm
charts that cause the same Pod to get referenced across mulitple
manifests, and because the `k8swatch.ManifestSubscriber` that is
responsible for creating `KubernetesDiscovery` objects from the
resources in the `Tiltfile` only allows one manifest to "claim" a
given UID so that even if it's referenced in another, it will be
invisible to it.
However, there is a remaining scenario, which is trickier, and that
is extra pod label selectors. The manifest subscriber can't
practically play the same games with uniqueness here (at least not
in any sane, predictable fashion). The `PodWatcher` now behaves
more like a reconciler (and will be one soon), so tries to …
=> engine: add multi-manifest support for Pods

internal/engine/portforward/subscriber.go
See #4498 - the signature changed here but didn't get rebased
before #4499 was merged, so wrong signature was being used.
=> engine: fix Pod span ID for PortForward objects

internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/hud/fake_hud.go, internal/testutils/podbuilder/podbuilder.go, pkg/webview/view.pb.go
The upper/buildcontroller tests (which share a fixture) were
simulating pod events by manually dispatching events, thus bypassing
the `PodWatcher` entirely.
That in and of itself isn't hugely problematic (although since these
are more integration than unit tests, it was skipping a lot of logic
that's useful to exercise).
The problem arises from the fact that events are dispatched per-pod
(`PodChangeAction`) currently, but as part of the changes for api
server, the `KubernetesDiscovery` status includes _all_ pods. Since
thigns are dispatched async, this presents new synchronization to
manage in the test.
Instead of trying to work around it further, this changes the tests
to rely on emitting Pod events from the fake K8s client and letting
`PodWatcher` see them and dispatch events.
This does …
=> test: emit Pod events instead of manually dispatching actions

internal/cli/down_test.go, internal/containerupdate/exec_updater_test.go, internal/controllers/core/podlogstream/podlogstreamcontroller_test.go, internal/engine/analytics/analytics_reporter_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontroller_test.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/portforward/subscriber_test.go, internal/engine/upper_test.go, internal/k8s/fake_client.go, internal/k8s/owner_fetcher_test.go, internal/testutils/podbuilder/podbuilder.go, internal/tiltfile/tiltfile_test.go
* `PodBuilder` now allows customizing the PodUID
* To avoid confusion, `PodID` is now `PodName` on the builder
* `PodBuilder` considers Deployment UID when generating ReplicaSet
UID
* This ensures that `ReplicaSet`s for non-default Deployments
aren't erroneously associated (in terms of OwnerRef) with the
default Deployment
* `FakeK8sClient` internally tracks entities by UID to allow old
versions to be fetched to aid in simulating out-of-order/stale
data scenarios
* This should PROBABLY be more appropriately handled by targeted
tests with more specific mocks (e.g. a fake `OwnerFetcher`)
but this is the path of least resistance for now
All these changes are in support of test adjustments in `test_upper` which currently does some sneaky things since it bypasses a lot of logic that won't be …
=> test: k8s fakes (client + pod builder) improvements

internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/upper_test.go, internal/k8s/fake_client.go
Please review the following commits I made in branch nicks/pod:
83d123bcb13698830226a0f727aead9150d0bce8 (2021-05-05 20:02:58 -0400)
test: fix a race condition
In a real kubernetes client, the first time you watch pods, you get the listing
of all the pods in Kubernetes.
Update our fake client to behave the same way.
=> test: fix a race condition

internal/cloud/snapshot_uploader.go, internal/hud/server/logs_reader.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/hud/server/websocket.go
Please review the following commits I made in branch nicks/omit:
7442f697326d6a520a47f119b9ad1273f1b7093b (2021-05-06 19:51:04 -0400)
hud: remove EmitDefault from all json serializers
I think this is a holdover from the pre-typescript days
when we weren't able to remove props safely.
=> hud: remove EmitDefault from all json serializers

internal/cloud/io_test.go, internal/hud/server/websocket.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, web/src/AppController.ts, web/src/GlobalNav.tsx, web/src/HUD.tsx, web/src/HeaderBar.stories.tsx, web/src/HeaderBar.tsx, web/src/OverviewResourceBar.stories.tsx, web/src/OverviewResourceBar.tsx, web/src/UpdateDialog.test.tsx, web/src/UpdateDialog.tsx, web/src/testdata.tsx
Please review the following commits I made in branch nicks/uisession7:
4d9b9844265cc51ec2d22b92a08d5812bee12684 (2021-05-06 16:41:50 -0400)
web: update the ui to read uiSession instead of view
0a7e237529d504b74e4ada9b3d74f0d73fdb9f62 (2021-05-06 16:41:22 -0400)
apis: add UISession (a straight port of the old view.proto)
=> web: update the ui to read uiSession instead of view

internal/engine/k8swatch/reducers.go, internal/engine/portforward/subscriber.go
Hello @maiamcc, @milas,
Please review the following commits I made in branch nicks/ch11991:
cbf578ac611d895c9426101a426aa22a671cedcd (2021-05-13 15:56:25 -0400)
k8swatch: remove portforward warning
This warning is incorrect. From https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports :
> List of ports to expose from the container. Exposing a port here gives the
> system additional information about the network connections a container uses,
> but is primarily informational.
I could imagine a better warning here in the future like "Hey, you're trying to
connect to port 1234, but the container says it's listening on 1235, was that
intentional?". But I don't think the current warning addresses that well.
* …
=> k8swatch: remove portforward warning

internal/cli/create_filewatch.go, internal/cli/create_filewatch_test.go
Hello @milas,
Please review the following commits I made in branch nicks/filewatch2:
57b06406e2cdee0324d56f4c0af86c1a8d627ed2 (2021-05-12 19:55:09 -0400)
cli: fix a bug in 'create filewatch'
=> cli: fix a bug in 'create filewatch'

internal/engine/k8swatch/manifest_subscriber_test.go, internal/testutils/context.go
Currently, the `PodWatcher` tests cover both:
* Manifest -> KubernetesDiscovery spec creation
* KubernetesDiscovery spec -> Pod discovery + status update
The latter will be covered by the reconciler tests - it's not
desirable to have the reconciler tests needing to create manifests
and transit via the `ManifestSubscriber`, so these tests specifically
focus on the spec creation behavior so that the reconciler tests can
focus on actual discovery.
=> test: add k8swatch ManifestSubscriber tests

internal/cloud/io_test.go, internal/engine/uisession/reducers.go, internal/engine/uisession/subscriber.go, internal/engine/uisession/subscriber_test.go, internal/engine/upper.go, internal/hud/server/websocket.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go
Please review the following commits I made in branch nicks/uisession10:
317e380463c7e065904a927c9132c9a6b531fb22 (2021-05-07 18:14:00 -0400)
uisession: separate subscriber the writes UISession from code that reads it
=> uisession: separate subscriber the writes UISession from code that reads it

internal/cloud/io_test.go, internal/engine/uiresource/reducers.go, internal/engine/uiresource/subscriber.go, internal/engine/uiresource/subscriber_test.go, internal/engine/upper.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go
Please review the following commits I made in branch nicks/uisession11:
522e3e21c3f897ad66c99e2bf82d15db6cfd31bf (2021-05-10 12:06:52 -0400)
uiresource: separate subscriber that writes UIResource from code that reads it
ab8aa236b4c1607d6425d528dd7097d0849bbff3 (2021-05-10 09:55:37 -0400)
uisession: separate subscriber the writes UISession from code that reads it
=> uiresource: separate subscriber that writes UIResource from code that reads it

internal/engine/uiresource/subscriber_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/flake3:
564bc3d09133d2ef19ee57fb5f5dc419a8376c04 (2021-05-17 18:40:53 -0400)
engine: fix a flaky test that depends on ui resource order
=> engine: fix a flaky test that depends on ui resource order

integration/fixture_test.go, integration/tilt.go
Now that more and more state is in the apiserver, it's really
helpful to see its state when an integration test fails, particularly
for debugging issues where the engine state and apiserver are out
of sync.
=> test: dump apiserver state on integration test failure

pkg/logger/env.go, pkg/logger/env_test.go
Hello @milas,
Please review the following commits I made in branch nicks/ch12001:
8cfaeb2bd37ccdff9197c8b9323069cb4a1397d2 (2021-05-18 12:51:28 -0400)
logger: set PYTHONUNBUFFERED by default
fixes https://github.com/tilt-dev/tilt/issues/4558
=> logger: set PYTHONUNBUFFERED by default

internal/engine/buildcontrol/build_control.go, internal/engine/configs/configs_controller.go, internal/engine/configs/configs_controller_test.go, internal/engine/fswatch/action.go, internal/engine/session/conv.go, internal/engine/upper.go, internal/store/engine_state.go
Hello @milas,
Please review the following commits I made in branch nicks/miss:
7b2ea03e1eb6cd9cd72c1d3d5bbb80706341347f (2021-05-18 17:45:30 -0400)
engine: fix a race condition in Tiltfile reload
PendingConfigFileChanges had its own change tracking,
which didn't get the fixes we applied in
https://github.com/tilt-dev/tilt/pull/4397
This removes that state completely and unifies
Tiltfile change tracking with other stuff
=> engine: fix a race condition in Tiltfile reload

internal/engine/k8swatch/manifest_subscriber.go
While debugging, I cleaned this up a bit to make it easier to follow:
* Fatally error if the create fails - this _should_ never happen, but it was being silently ignored before and would have meant that no K8s resources would be discovered for a resource silently if hit, so erroring out is the best course of action for now
* Removed redundant delete case (this made sense at one point but was an impossible to hit branch at this point)
* Used a value instead of a pointer when processing specs (was never actually `nil` + makes the diff logic easier to follow)
=> k8swatch: simplify manifest subscriber logic

web/src/AccountMenu.test.tsx, web/src/FatalErrorModal.test.tsx, web/src/HUD.test.tsx, web/src/ShareSnapshotModal.stories.tsx, web/src/ShareSnapshotModal.test.tsx, web/src/ShareSnapshotModal.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap, web/src/index.tsx
This PR fixes issue #4424, where a user reports that they have trouble interacting with the UI using VoiceOver after the `Make a snapshot` button is clicked. I was able to reproduce the issue with VO and saw that `aria-hidden=true` was set on the `body` whenever the snapshot modal was visible. :sob:
The docs for `ReactModal` specify that the (`setAppElement`)[http://reactcommunity.org/react-modal/accessibility/] should be called on the app root so that the component can hide the main app content while the modal is displaying. Updating that method call with the app root id, instead of the document `body` fixed the issue. 
~I'm not sure how we want to fix the tests since the app root isn't available in the testing environment. (Probably just the limits of my react testing knowledge!) …
=> web: fix issue with UI becoming inaccessible to assistive tech when snapshot modal is opened

pkg/apis/core/v1alpha1/generated.proto, pkg/apis/core/v1alpha1/uiresource_types.go, pkg/apis/core/v1alpha1/uisession_types.go, pkg/openapi/zz_generated.openapi.go
Hello @nicks,
Please review the following commits I made in branch nicks/omitempty:
93f90f1554e6fcb230295855fcd87c3dea045f35 (2021-05-20 15:44:18 -0400)
apis: add omitempty/optional annotations
trying to follow the kube convention of defaulting to optional
for everything except real base-level structural fields (like spec and status)
=> apis: add omitempty/optional annotations

internal/engine/upper_test.go, internal/store/manifest_target.go
If a `local_resource` had no `update_cmd` (i.e. just a `serve_cmd`)
but was set to `auto_init=False`, it would end up starting anyway
because the server controller saw that the dependency status was
`not_applicable` (technically true).
To fix this, the dependency status is set to `none` for local
resources with `auto_init=False` that have not yet had a build
(either from being manually triggered or having `TRIGGER_MODE_AUTO`
and a file change). Once a build has happened, it will resume
returning `not_applicable` to indicate that there is no longer a
reason to block on a dependency.
Fixes #4548.
=> local: do not run serve_cmd with auto_init=False on start

.circleci/Dockerfile.integration, .circleci/config.yml
Please review the following commits I made in branch nicks/kind11:
984c1a1372e633ef41016bb42461f67c8daa3620 (2021-05-20 12:42:22 -0400)
test: upgrade integration tests to use kind 0.11
=> test: upgrade integration tests to use kind 0.11

internal/engine/k8srollout/podmonitor.go, internal/engine/k8srollout/podmonitor_test.go
Fixes #4566
1. When you run `tilt up` and the existing pod suffices, the tilt log still makes it look like it's rolling out a new pod, which is confusing:
```
Tracking new pod rollout (matt-fortune-6b8dc4dc74-24llm):
┊ Scheduled       - <1s
┊ Initialized     - <1s
┊ Ready           - 2s
```
2. On subsequent builds where the existing pod suffices, tilt will just omit that section entirely and not log anything in its place, which feels kind of weird (e.g, "why hasn't it rolled the pod out yet?"), and also leaves the user in the position of seeing runtime logs from the pod without seeing any of the startup logs they might expect, with no explanation
```
2b7fb36704d4: Layer already exists 
c1df871adf38: Layer already exists 
503e53e365f3: Layer already exists 
STEP 3/3 — Deploying
Injecting …
```
=> rollout: make clear when tilt is attaching to an existing pod rather than rolling out a new one

internal/cloud/snapshot_uploader.go, internal/hud/server/logs_reader.go, internal/hud/server/server.go, internal/hud/server/websocket.go, internal/hud/server/websocket_reader_test.go, internal/hud/server/websocket_test.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/store/summary.go, pkg/webview/view.proto, web/src/AppController.test.ts, web/src/AppController.ts, web/src/HUD.test.tsx, web/src/HUD.tsx
Please review the following commits I made in branch nicks/incremental:
0dbdfd17046b9cbb00e62a6f70f3e3eeb43069d7 (2021-05-25 16:12:36 -0400)
webview: only send updated objects
This has two big benefits:
1) We want to make it easier to read directly from the APIServer,
which uses List/Watch model for API access
2) Web UI performance should be much better and easier to optimize
going forward, since we know exactly what changed and
don't need to do a lot of JSON parsing/re-rendering
for objects that didn't change
=> webview: only send updated objects

internal/cli/wire_gen.go, internal/controllers/core/uiresource/reconciler.go, internal/controllers/core/uisession/reconciler.go, internal/engine/upper_test.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/hud/server/websocket.go, internal/hud/server/websocket_test.go, internal/hud/server/websocketlist.go, internal/hud/server/wire.go
Please review the following commits I made in branch nicks/uisession15:
294b972f8479aa8a7829ccd760e3d3afa7e9d8cb (2021-05-26 20:37:27 -0400)
controllers: use reconcilers to send webview updates
=> controllers: use reconcilers to send webview updates

internal/cli/ci.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/cloud/io.go, internal/cloud/io_test.go, internal/cloud/snapshot_uploader.go, internal/engine/upper_test.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/hud/server/websocket.go, internal/hud/server/websocket_test.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/hud/webview/view.go
Please review the following commits I made in branch nicks/uisession16:
9e2a9ae87e3c6fd660a08c6dd78b99d10c032f83 (2021-05-26 20:40:09 -0400)
webview: always read from the apiserver
294b972f8479aa8a7829ccd760e3d3afa7e9d8cb (2021-05-26 20:37:27 -0400)
controllers: use reconcilers to send webview updates
=> webview: always read from the apiserver

internal/docker/client.go
Docker 18.09+ added support for SSH remote Docker connections.
The code to handle this isn't actually in the Moby client portions
that we use, but in the Docker CLI (which we already have a
dependency on).
This adapts some of the code from the Docker CLI that attempts
to create a `ConnectionHelper` if the host value is set. Currently,
the logic only creates a helper for `ssh://` hosts and returns nil
otherwise, in which case the former logic is used (i.e. pass the
host as-is to Moby). If a connection helper is created, it's used
to create a custom HTTP client/transport that will use SSH under
the hood.
Fixes #4603.
=> docker: support DOCKER_HOST=ssh://... remotes

internal/hud/server/websocket.go, internal/hud/server/websocket_test.go
Fixes #4604.
A race condition can cause the HUD to wipe out its state and go back to "Loading..."
My understanding of how this happens is:
1. Store writes a LogEvent to the LogStore.
2. Store notifies WebsocketSubscriber with a ChangeSummary w/ Log: true for the LogEvent from (1)
3. Store writes a second LogEvent to the LogStore
4. WebsocketSubscriber processes the ChangeSummary from (2), asks LogStore for the LogList, gets the messages from both (1) and (3), and updates its checkpoint to indicate it's fully caught up.
5. Store notifies WebsocketSubscriber with a ChangeSummary w/ Log: true for the LogEvent from (2)
6. WebsocketSubscriber processes the ChangeSummary from (5), asks LogStore for the LogList since ws's checkpoint. Since there are no new log messages, LogStore [returns -1, …
=> websocket: ignore empty loglists

internal/cli/klog.go, internal/cli/klog_test.go
These error messages are benign and represent an uncommon yet
valid scenario where a group-version has no resource types.
This seems to be most common with the `prometheus-adapter` if
there are no external/custom metrics registered, at which point
the `external.metrics.k8s.io/v1beta1` (or `custom.`) group(s)
are empty.
The error/log does not impact Tilt operation but is confusing,
particularly during a `tilt down` where it's interleaved with
the actual Tilt output and makes it seem as though the operation
has failed.
Fixes #4610.
=> klog: suppress empty group-version errors

internal/build/docker_builder.go, internal/build/test_utils.go, internal/cli/wire_gen.go, internal/containerupdate/docker_container_updater.go, internal/docker/client_test.go, internal/docker/clients.go, internal/docker/env.go, internal/docker/fake_client.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/live_update_build_and_deployer.go, internal/engine/buildcontrol/live_update_build_and_deployer_test.go, internal/engine/buildcontrol/update_mode.go, internal/engine/buildcontrol/wire.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/env.go, internal/k8s/minikube.go, internal/k8s/minikube_fake.go, internal/k8s/minikube_test.go
Please review the following commits I made in branch nicks/ch12079:
cb46eee7205d6078b33247a62901e2d8b47e731f (2021-05-27 17:28:54 -0400)
docker: change how we model "image builds show up in the cluster immediately"
We used to treat this as a property of the cluster type + the container runtime.
But this made it impossible to support clusters that sometimes use your docker
runtime, and sometimes do not.
For examples, see:
- https://github.com/tilt-dev/tilt/issues/4587
- https://github.com/tilt-dev/tilt/issues/3654
- https://github.com/tilt-dev/tilt/issues/1729
- https://github.com/tilt-dev/tilt/issues/4544
This changes the data model so that "image builds show up in the cluster"
is a property of the Docker client, not of the cluster.
This should be much more flexible and …
=> docker: change how we model "image builds show up in the cluster immediately"

internal/tiltfile/docker.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch12145:
2556b036f404e8e7a6f577bc4349669c9d71b4c7 (2021-06-09 11:42:00 -0400)
tiltfile: fix a bug where we were reading the wrong .dockerignore
Fixes https://github.com/tilt-dev/tilt/issues/4605
I feel like all the ignore-interpreting code could use a rewrite/refactor
in general...but it might not be worth it depending on how
we start to integrate the tiltfile better with the apiserver
=> tiltfile: fix a bug where we were reading the wrong .dockerignore

pkg/apis/core/v1alpha1/.gitattributes
I finally got tired of scrolling through 30 pages of pb.go in `git diff master`.
=> api: hide generated code from diffs

internal/containerupdate/docker_container_updater.go, internal/containerupdate/exec_updater.go, internal/containerupdate/tar.go, internal/docker/client.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go
Please review the following commits I made in branch nicks/ch8967:
c8c15dcbd00827dcda42b3a6089a087c88e5a7c2 (2021-06-08 17:15:23 -0400)
containerupdate: use the exec API instead of the cp API for copying files
Fixes https://github.com/tilt-dev/tilt/issues/3708
=> containerupdate: use the exec API instead of the cp API for copying files

internal/cli/down_test.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/k8s/locator.go, internal/k8s/object_selector.go, internal/k8s/target.go, internal/store/json_test.go, internal/testutils/manifestbuilder/manifestbuilder.go, pkg/model/k8s_target.go, pkg/model/manifest.go, pkg/model/manifest_test.go
Please review the following commits I made in branch nicks/k8s2:
ee58f44909bb080a5f8e9bb197687f406486d855 (2021-06-09 18:32:02 -0400)
apis: use ImageLocators field in KubernetesApplySpec
ee0804a46236ce20d3718378145ade8c0a197626 (2021-06-09 18:31:50 -0400)
apis: use ImageMaps field in KubernetesApplySpec
96cf109538f3a15b009bee17e19f6bcf5f9c7255 (2021-06-09 18:31:35 -0400)
apis: use YAML field to KubernetesApplySpec
dbc136af27c5d04e3bff013737aac6f3d6225c80 (2021-06-09 18:29:27 -0400)
apis: flesh out KubernetesApplySpec
=> engine: use KubernetesApplySpec to apply to the cluster

web/src/HUD.test.tsx, web/src/OverviewActionBar.stories.tsx, web/src/OverviewActionBar.test.tsx, web/src/OverviewActionBar.tsx, web/src/OverviewResourceDetails.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourcePane.tsx, web/src/testdata.tsx
1. When a UIButton API object exists, it gets rendered in the OverviewActionBar.
2. When the user clicks on the button, it just console.logs that it was clicked. The work to make the click actually do something will be in a future PR. I figure it's fine to merge with partial functionality since users won't see it unless they are really getting into the weeds anyway.
Here are some screenshots of how two buttons ("text1" and "text2") render when other OverviewActionBar components are/are not present:
=> web: add UIButtons to UI

web/src/OverviewActionBar.tsx, web/src/OverviewResourcePane.tsx
Use the apiserver proxy to send a `/status` update for a UIButton
when clicked, updating its `LastClickedAt` field value with the
current time.
(See #4640 for the main PR that adds `UIButton` support to the web
interface.)
=> web: update LastClickedAt on UIButton click

pkg/apis/core/v1alpha1/cmd_types.go, pkg/apis/core/v1alpha1/generated.proto, pkg/openapi/zz_generated.openapi.go
For simplicity, it's fine to let this default to `time.Zero`,
which will mean there's no filter to ignore old events (see
`internal/controllers/core/cmd/startmanager.go` for where it's
used).
=> api: make StartAfter optional on Cmd StartOn spec

internal/engine/session/controller_test.go, internal/engine/session/conv.go
If a `local_resource` has `auto_init=False` and a `serve_cmd`,
the target in `Session` (used for `tilt ci`) would erroneously
be assigned a waiting state (with an unknown reason since it
wasn't _really_ waiting).
Now the waiting fallback is only used if the resource has
`auto_init=True` (default) OR has ever had a build triggered
for any reason (e.g. `TRIGGER_MODE_AUTO` + file change or via
UI). The latter avoids a potential race condition between the
build being invoked and the serve_cmd actually getting launched.
Fixes #4637.
=> engine: don't block tilt ci for local_resource with auto_init=False

integration/crash_test.go, integration/crd_test.go, integration/fixture_test.go, integration/oneup_test.go, integration/tilt.go, integration/tilt_args_test.go, integration/tilt_ci/Tiltfile, integration/tilt_ci/Tiltfile.generated, integration/tilt_ci/k8s.yaml, integration/tilt_ci_test.go
We've had several regressions here recently, particularly due to
nuances in `local_resource` between `auto_init` / `trigger_mode`
and presence/absence of an update `cmd` / `serve_cmd`.
This test has some static K8s resources (2x Deployment + 2x Job,
one of each `auto_init=True` and one of each `auto_init=False`) as
well as code to dynamically generate permutations of local resources
per the above.
Additionally, the Tilt driver now uses a context when creating
commands and the fixture gives a 3 minute timeout context. This is
particularly useful for this new test to ensure if there's a
regression it doesn't hang indefinitely until the test runner
timeout, but it also generally useful for the other integration
tests in the event they have an issue.
=> test: add integration test for `tilt ci`

internal/engine/buildcontrol/local_target_build_and_deployer.go, internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/live_update.go, internal/tiltfile/local_resource.go, internal/tiltfile/telemetry/telemetry.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/value.go
Adds a working directory option as specified in #4549.
Documentation change in [tilt.build/#872](https://github.com/tilt-dev/tilt.build/pull/872).
Given the following directory structure: 
```
.
├── Tiltfile
├── site.yaml
├── some_dir
│   └── test-greeting.txt
└── test-greeting.txt
```
And the contents of `Tiltfile`:
```
k8s_yaml('site.yaml')
k8s_resource('site')
local_resource('greeting', cmd='cat test-greeting.txt', dir='some_dir')
```
The "greeting" `local_resource` prints the contents of `some_dir/test-greeting.txt`.
Specifying `dir=None` defaults the working directory to the Tiltfile's directory, meaning the "greeting" resource will print the contents of the Tiltfile-level `test-greeting.txt` instead. This is equivalent to omitting the `dir` operation altogether.
The following will …
=> tiltfile: add working directory option to local and local_resource

web/package.json, web/src/OverviewActionBar.stories.tsx, web/src/OverviewActionBar.test.tsx, web/src/OverviewActionBar.tsx, web/src/OverviewLogPane.stories.tsx, web/src/OverviewLogPane.test.tsx, web/src/OverviewLogPane.tsx, web/src/SrOnly.tsx, web/src/assets/svg/filter.svg, web/src/logfilters.test.ts, web/src/logfilters.ts, web/src/regex-escape.d.ts, web/yarn.lock
*  Add support for filtering log spans based on a string input that behaves like the existing source and term filters
*  Add a term input field in the filter bar with a debounce delay; (this does behave a tiny bit quirky which i outlined in a code note. I think this is probably okay for mvp, but happy to chat more in-depth if needed.)
Styles and tests are still a wip, but otherwise code is ready for review. 
Term input field:
Filtering logs by term and level filters:
Closes ticket #12046
=> (web) Add term input field to filters bar to filter resource logs by string

internal/hud/server/apiserver_test.go, pkg/apis/core/v1alpha1/portforward_types.go
* PodName cannot be empty
* At least one Forward must be defined
* LocalPort must be [0, 65535] (0 == randomized)
* ContainerPort must be (0, 65535]
* LocalPorts cannot repeat (though likely not common, ContainerPort
can be forwarded multiple times, so duplicates are fine there)
=> api: validation for PortForward objects

internal/controllers/core/portforward/reconciler.go, internal/controllers/core/portforward/reconciler_test.go, internal/controllers/core/portforward/types.go, internal/controllers/fake/fixture.go, internal/k8s/client_test.go, internal/k8s/fake_client.go, internal/k8s/portforward.go, internal/k8s/portforward/portforward.go
There are 3 cases where status gets updated for a forward:
* Forward started successfully (StartedAt set as well as local
port, which is useful if a randomized one was requested)
* Forwarder instance can't be created (bad config)
* Forwarder returns an error after start
To simplify error handling and keep the status update logic
as centralized as possible, the actual initialization changed
slightly to happen in a single method.
There is some very basic logic to avoid spamming the API
server with updates on errors: it will only attempt to do
an update once a second if continuously failing. (Even then,
it will attempt to avoid a no-op update if the error hasn't
actually changed.)
(This is based off Maia's original stub PR: #4621)
=> k8s: update PortForwardStatus after initializing forwards

web/src/OverviewActionBar.tsx
CH12192 Fix a bug where the filter term is not removed during backspace by adding support to explicitly opt out of debouncing
When we update the filter term state, the existing code behaves differently based on whether we're adding/updating a filter term or removing it. The former always has a debouncing delay, while the latter does not have a debouncing delay. The reason behind this is so that we can immediately update the filter state without a delay when a user clears the term field via button. This causes a bug where if a user is backspacing a term they've entered, if they clear it completely, that state update fires immediately, while the previous state update fires after the debouncing delay. 💡
=> (web) Fix a bug where the filter term is not removed during backspace [ch12192]

internal/store/helpers_test.go, internal/store/sleep.go, internal/store/store.go, internal/store/subscriber.go, internal/store/subscriber_test.go, internal/store/summary.go
Please review the following commits I made in branch nicks/onchange:
69909e11093c984d6cedf1212148fdc789aedccd (2021-06-21 12:15:25 -0400)
store: add backoff logic to subscribers
=> store: add backoff logic to subscribers

internal/engine/uiresource/subscriber.go, internal/engine/uisession/subscriber.go
`tilt up` sometimes generates output like this:
```
listing uiresource: the cache is not started, can not read objects
fetching uisession: the cache is not started, can not read objects
```
* uiresource [already has a check](https://github.com/tilt-dev/tilt/blob/13c9bb803c8cfe08b51beaaa32788c565f3b69bd/internal/engine/uiresource/subscriber.go#L53-L57) to hide these errors, but it matches the string "cache not started" instead of "cache is not started"
* check the error's type instead of the string returned by `Error()`
* add the same check to uisession
I haven't learned enough about this to understand whether this has wider implications, like:
* are there other subscribers this affects and should we add these checks there as well? (I haven't seen these errors from any other types, and …
=> engine: hide "cache is not started" errors from uiresource/uisession

Makefile
Use some `gotestsum` flags to automatically retry a failed test.
If there's >10 failures that require retry, the tests will still
fail.
This only applies to the `shorttestsum` make task and more
specifically when run under CircleCI, which ONLY applies to
Windows.
=> ci: add retry for Windows tests

web/src/OverviewActionBar.tsx, web/src/assets/svg/alert.svg, web/src/logfilters.test.ts, web/src/logfilters.ts
This PR:
*  Fix a bug where navigating to an individual resource from sidebar view would clear the filter term in the url, but not the filter input field
*  Add support for using regular expressions to filter log spans
*  Display an error state with helpful text if parsing regexp errors, using Material UI's `FormHelperText` component
Fyi, the final style implementation does look different than the Figma files. While pairing with Han, we decided that displaying the error message styled as tooltip would be the easiest approach, and Surbhi approved.
Basic functionality:
Final styles:
Closes ch12047
=> web: add support for filtering logs by regular expression

web/src/OverviewActionBar.tsx
This PR fixes an issue with the `fieldset` border width + color and error color styles not applying correctly.
Active border is now 1px (instead of 2px) and matches the buttons:
Active border is now 1px (instead of 2px) and reds are the correct red:
=> web: tweak styles for filter term input field to align better with design

internal/controllers/core/podlogstream/podlogstreamcontroller_test.go, internal/k8s/fake_client.go
Eliminate the store part of the tests (besides using it to extract
logs).
This makes these tests purely about actual reconciler behavior and
not about implicit object creation from manifests; this will
temporarily reduce the test coverage, but will be reinstated by
tests for the `kubernetesdiscovery.Reconciler` to ensure that it
creates `PodLogStream` objects (instead of `runtimelog.PodLogManager`
which will go away). This is just split out because the scope of
changes required for these tests was sufficient on its own.
=> test: refactor PodLogStream reconciler tests

integration/crd_test.go
The Custom Resource Definition (CRD) test has a check to ensure that images only get pulled when necessary.
In k8s on Docker for Mac, Tilt uses an extra optimization to share the Docker image cache, which allows it to use `imagePullPolicy: Never` by default. Currently, the CRD test fails in this setup because it only accepts `imagePullPolicy: IfNotPresent`. 
This change allows the Custom Resource Definition test to take the Mac setting into account by replacing the single string to match with a regular expression that accepts both `IfNotPresent` and `Never` image pull policies.
=> integration: change string match to regexp to allow for either IfNotPresent or Never imagePullPolicy

integration/namespaceflag/Dockerfile, integration/namespaceflag/Tiltfile, integration/namespaceflag/index.html, integration/namespaceflag/namespaceflag.yaml, integration/namespaceflag_test.go, internal/cli/flags.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/buildcontrol/wire.go, internal/engine/buildcontrol/wire_gen.go, internal/k8s/client.go
A very basic default namespace flag, inspired by the change suggested in #1113. 
```
tilt up --namespace=my-namespace
```
Documentation change in [tilt.build #876](https://github.com/tilt-dev/tilt.build/pull/876).
=> cli: add namespace flag

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/controllers/fake/fixture.go, internal/engine/buildcontrol/image_build_and_deployer.go
Hello @milas,
Please review the following commits I made in branch nicks/ka:
f14dd9da7b50a58628fc2c1ba818316a7aaad883 (2021-06-25 13:28:50 -0400)
kubernetesapply: reconcile objects
=> kubernetesapply: reconcile objects

internal/cli/doctor.go
Motivated by #4678
```
Docker
- Host: [default]
- Server Version: 20.10.2
- API Version: 1.41
- Builder: 2
```
=> doctor: log docker server version

internal/controllers/builder.go, internal/controllers/manager.go
We've had a race condition here all along, but apparently the
latest changes exacerabated it (maybe just due to sheer number
of reconcilers we have now).
This moves the actual start of the controller manager to after
the controllers are initialized (which itself happens in two
phases).
It'd be nice to fully redo this initialization sequence in the
future, but we'd need to de-couple it from using the store to
initialize everything.
Fixes #4698.
=> api: defer controller manager init

internal/engine/configs/api.go, internal/hud/server/apiserver.go
Hello @milas,
Please review the following commits I made in branch nicks/entity-too-large:
27a5b010d06f87c384c9769bc36b677b9a5c4a29 (2021-06-28 19:54:20 -0400)
hud: improve 'entity too large' errors and raise limit
=> hud: improve 'entity too large' errors and raise limit

internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/entity.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/locator_test.go, internal/k8s/owner_fetcher.go, internal/k8s/owner_fetcher_test.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/entity:
60b63fcbc1a670905f4653adff5846eb3a4f4248 (2021-06-28 19:00:43 -0400)
k8s: remove our homegrown meta Accessor in favor of apimachinery's
=> k8s: remove our homegrown meta Accessor in favor of apimachinery's

internal/controllers/core/cmd/execer_unix_test.go
This test failed for me in CI.
I'm not sure a test change is the right path forward, but it's not immediately clear to me how to fix the underlying code in a way that's copacetic with #4456, so I figured I'd throw up a PR to discuss the issue.
(FWIW, I added logging to the `io.Writer` passed as stdout and confirmed its `Write` was being called with `BACKGROUND $!` after `c.Process.Wait()` had returned)
=> cmd: fix flaky grandkid test

internal/dockercompose/client.go
From the Docker Compose[1] docs:
```
--force-recreate    Recreate containers even if their configuration
and image haven't changed.
```
We are currently always passing this flag when Tilt is handling the
build (vs `docker-compose build`). However, Docker Compose already
checks if the image it's using is outdated; if it is, it will stop
the existing container and create a new one with the updated image
(and/or config). If the image and config are the same, it will not
replace them.
It looks like the flag has been in place since the original
implementation of Docker Compose code in Tilt, so wasn't a reaction
to any other sort of regression.
In general, it doesn't matter because Tilt only calls
`docker-compose up` after it has done a build. However, when
re-launching Tilt where an already …
=> docker-compose: do not force recreate on up

web/src/UpdateDialog.tsx
Hello @hyu, @ellenkorbes,
Please review the following commits I made in branch nicks/update2:
03b6cad38b64e1676046d5062662c8cdf316fef1 (2021-06-29 17:50:38 -0400)
web: add a subscribe link in the update dialog
My thinking is that if you're clicking around for updates,
you probably care about tilt news more than most people.
=> web: add a subscribe link in the update dialog

internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/execer.go, internal/controllers/core/cmd/execer_test.go
Please review the following commits I made in branch nicks/cmd2:
15142a7bd29f5191230674b83ba903b548d8e256 (2021-06-30 18:10:54 -0400)
cmd: remove redundant fields
- the spanID field was never used
- statusCh and doneCh had the same close() semantics, so we can make one depend on the other
=> cmd: remove redundant fields

go.mod, go.sum, vendor/github.com/tilt-dev/fsnotify/README.md, vendor/github.com/tilt-dev/fsnotify/windows.go, vendor/modules.txt
Ignore file attribute changes on Windows.
See https://github.com/tilt-dev/fsnotify/pull/8 for details.
Fixes #4706.
=> watch: upgrade fsnotify to fix spurious file changed on Windows

internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/core/kubernetesdiscovery/reconciler_test.go, internal/engine/k8swatch/manifest_subscriber.go, pkg/apis/core/v1alpha1/generated.proto, pkg/apis/core/v1alpha1/kubernetesdiscovery_types.go, pkg/openapi/zz_generated.openapi.go
Hello @milas,
Please review the following commits I made in branch nicks/pls2:
25351dd0f0122e8a2fa87a37352f22b77ce0a745 (2021-07-02 15:47:36 -0400)
kubernetesdiscovery: propagate PodLogStreamTemplate
=> kubernetesdiscovery: propagate PodLogStreamTemplate

web/src/GlobalNav.tsx, web/src/OverviewResourcePane.tsx, web/src/index.scss
There was an issue where if you go to the Log view and then back to Table Overview, you could no longer scroll down the page! This is now fixed in this PR.
We had some legacy code that was preventing scrolling, which was supposed to be deleted along with our old UI.
Also, I found that an overly long label in the header was causing the layout to be too wide and create scrollbars!
=> web: Fix scrolling bug with Table Overview

internal/tiltfile/starlarkstruct/struct.go, internal/tiltfile/starlarkstruct/struct_test.go
from (starlark-go)[https://github.com/google/starlark-go/blob/master/starlarkstruct/module.go#L9-L13]:
```
// A Module is a named collection of values,
// typically a suite of functions imported by a load statement.
//
// It differs from Struct primarily in that its string representation
// does not enumerate its fields.
```
This can be handy for Tiltfile extensions where you want multiple symbols, to allow, e.g., `load('ext://myextension', 'myextension')` and then `myextension.foo(myextension.bar)`
=> tiltfile: add `module`

internal/feature/flags.go, web/src/HUD.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/SidebarItem.tsx, web/src/SidebarResources.tsx, web/src/feature.test.ts, web/src/feature.ts, web/src/labels.ts, web/src/view.d.ts, web/storybook.tiltfile
This PR adds basic resource grouping by label using mocked data in Storybook and the `labels` feature flag (which can be toggled in Storybook) for [ch12250](https://app.clubhouse.io/windmill/story/12250/display-label-headings-and-resource-groups-behind-feature-flag). I haven't added any label-specific styles yet, since I want to use the MaterialUI [accordion](https://material-ui.com/components/accordion/#accordion) component and thought that would make this PR too large. (I'll tackle the styles and accordion functionality next for [ch12252](https://app.clubhouse.io/windmill/story/12252/add-expand-collapse-functionality-for-label-groups)).
With feature flag off, everything should remain the same:
With feature flag on, resources appear under each label they have, with unlabeled resources at …
=> web: Add basic display of labeled resources in Storybook behind feature flag

README.md
Hello @hyu, @peterchapman, @milas,
Please review the following commits I made in branch nicks/officehours:
40e840f25675bdbaa679cb3bf94303d6cd75b0d1 (2021-07-07 17:55:19 -0400)
readme: remove user research link, add zoom office hours
=> readme: remove user research link, add zoom office hours

internal/k8s/target.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/portforwardreconciler:
2d371e2ac0995b5f1d302acb2066eaeeeb01a670 (2021-07-09 19:24:38 -0400)
k8s: don't emit a PortForwardTemplate on 0 port-forwards
=> k8s: don't emit a PortForwardTemplate on 0 port-forwards

web/src/OverviewResourceSidebar.stories.tsx, web/src/SidebarItem.tsx, web/src/labels.ts, web/src/view.d.ts
These are some slight Typescript gymnastics to cast the generic `object` to `{ [key: string]: string }` for label data. 🙃 I'm not sure this is phenomenally better than using `any` types for labels, but it does let us keep stricter type information.
=> web: type the label data better to handle the generic generated type

internal/controllers/apicmp/delta.go, internal/controllers/core/cmd/cmp.go, internal/controllers/core/cmd/cmp_test.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/controller_test.go
Please review the following commits I made in branch nicks/ext202:
1b6311a3036b223f3286a20812e00ff7445f7ef7 (2021-07-12 13:47:07 -0400)
cmd: support self-modifying cmds
fixes https://github.com/tilt-dev/tilt-extensions/issues/202
334b676b0d49f627234a335270e146e21df91bfe (2021-07-09 19:38:30 -0400)
controller: improve apiserver logging
=> cmd: support self-modifying cmds

internal/engine/k8swatch/actions.go, internal/engine/k8swatch/manifest_subscriber.go, internal/engine/k8swatch/manifest_subscriber_test.go, internal/engine/k8swatch/reducers.go, internal/engine/upper.go, internal/store/engine_state.go, internal/store/summary.go
Hello @nicks,
Please review the following commits I made in branch nicks/kdstatus:
b317dede117b793813cd7b1a3ee1b41c38b3f350 (2021-07-13 19:50:09 -0400)
engine: remove some dead code
The store.KubernetesDiscovery map was only being used in tests,
and the actions were only being used for Status updates.
=> engine: remove some dead code

internal/controllers/core/kubernetesdiscovery/portforwards.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/indexer/list.go, internal/controllers/indexer/list_test.go
Please review the following commits I made in branch nicks/indexers:
22f5dfe8a025486050bade7f414ebdaf5c3b42a5 (2021-07-13 18:18:38 -0400)
controllers: index manually instead of with cache indexers
Fixes https://github.com/tilt-dev/tilt/issues/4719
=> controllers: index manually instead of with cache indexers

internal/cli/wire_gen.go, internal/controllers/core/kubernetesapply/disco.go, internal/controllers/core/kubernetesapply/disco_test.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/wire.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/upper_test.go, internal/engine/wire.go, internal/engine/wire_gen.go, pkg/webview/view.pb.go
Please review the following commits I made in branch nicks/apply2:
fa68d0fb31ff3c29d4401ca58bdd8e8bef6fbf76 (2021-07-14 15:12:59 -0400)
kubernetesapply: port the old KubernetesDiscovery code to the KubernetesApply reconciler
This is mostly copied and pasted from https://github.com/tilt-dev/tilt/blob/a760f2ebcb8d8346139d3143d8b82baf6183329f/internal/engine/k8swatch/manifest_subscriber.go
That code will be deleted in a subsequent PR
=> kubernetesapply: port the old KubernetesDiscovery code to the KubernetesApply reconciler

internal/tiltfile/docker_compose.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/bool.go
Please review the following commits I made in branch nicks/dc:
dd8b1b13744e5000f01760e28ca4b5d34f51bc87 (2021-07-15 15:59:39 -0400)
tiltfile: dc_resource and k8s_resource should both be additive
Before this change,
- If you had 2 k8s_resource calls for the same resource, it would be an error.
- If you had 2 dc_resource calls for the same resource, some properties
would merge and some would overwrite.
This behavior was confusing.
This changes both functions to "aggregate" options.
Fixes https://github.com/tilt-dev/tilt/issues/4736
Fixes https://github.com/tilt-dev/tilt/issues/3738
I think that has much better semantics in a world with extensions that want to
"add" things to a resource, and is a good stopgap as we add more things
to the API server.
Code review …
=> tiltfile: dc_resource and k8s_resource should both be additive

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/extractors.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/live_update_state_tree.go, internal/engine/buildcontrol/target_queue.go, internal/engine/buildcontrol/testdata_test.go, internal/engine/buildcontroller.go, internal/engine/configs/api.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/k8s/target.go, internal/k8s/target_test.go, internal/store/build_result.go, internal/testutils/manifestbuilder/assemble.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_state.go, pkg/model/image_target.go, pkg/model/k8s_target.go, pkg/model/target_test.go, pkg/webview/view.pb.go
Please review the following commits I made in branch nicks/ch12386:
7b1dbae447968c04f5009b6905b8078e1f3fb0e9 (2021-07-16 14:42:19 -0400)
engine: introduce a system for live-updating images we didn't deploy
This is the first step towards a general-purpose live-update API
that's independent of a general-purpose image build API, and suggests
how they might interoperate.
Fixes https://github.com/tilt-dev/tilt/issues/4577
I played around with a couple different ways to test this effectively,
but ultimately, the most valuable test was the file_sync_only
integration test we already have. Almost all of our live-update
specs are ultimately designed to catch bugs in how we do the live-update,
rather than asserting things about the live-update spec itself.
Code review reminders, by …
=> engine: introduce a system for live-updating images we didn't deploy

web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewSidebarOptions.test.tsx, web/src/ResourceStatusSummary.tsx, web/src/SidebarItemView.tsx, web/src/SidebarResources.tsx, web/src/StarredResourceBar.tsx, web/src/assets/svg/caret.svg, web/src/status.test.tsx, web/src/status.tsx, web/src/testdata.tsx
(feat) Add accordion functionality for resources grouped by labels in sidebar with styles and status summary
This PR uses Material UI's accordion component to display collapse-able and expand-able groups of resources in the sidebar. It also adds styles to align with the design and a small refactoring of resource summary display to cover different use cases. You can take a look at the `Resources with Labels` storybook entry to test. The resources sidebar should not look any different in the Tilt UI (outside of Storybook), cuz even though the feature flag is enabled in `storybook.tiltfile`, no resources have labels defined in the Tiltfile.
~There are a couple todos (noted in code) that I'd like to take care of before merging this in, but wanted to get this up for code review first.~ ✅ done! …
=> web: add accordion functionality for resources grouped by labels

internal/controllers/core/kubernetesdiscovery/portforwards.go, internal/controllers/core/kubernetesdiscovery/portforwards_test.go
Please review the following commits I made in branch nicks/loop:
f0ba496139e9a3d826a769a259b1ea0b3554e91e (2021-07-16 20:07:13 -0400)
controllers: fix an idempotency bug in the portforward manager
=> controllers: fix an idempotency bug in the portforward manager

internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Various Tilt extensions have been using `local()` to shell back
out to Tilt to use the API (e.g. `tilt apply -f ...`). This does
not play nice with custom ports if Tilt was invoked using the
`--port` argument.
Now, the current Tilt instance's port is passed as the `TILT_PORT`
argument so that the invoked command will automatically connect to
the same instance of Tilt.
Fixes #4737.
=> tiltfile: pass TILT_HOST + TILT_PORT to local() commands

internal/k8s/client.go, internal/k8s/helm.go, internal/k8s/helm_test.go
Please review the following commits I made in branch nicks/k8s:
d4a3d674e6091b14569551f478a7b9838f0e4d47 (2021-07-19 11:16:54 -0400)
k8s: fix a race condition where two goroutines were modifying the rest.Config
This caused weird k8s failures in CI
https://app.circleci.com/pipelines/github/tilt-dev/tilt/8267/workflows/299e4ca4-ef7a-4f49-be85-47b81cee3903/jobs/69248/tests#failed-test-0
=> k8s: fix a race condition where two goroutines were modifying the rest.Config

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go
The Docker Compose V2 beta (enabled by default in the latest Docker for Mac) resolves absolute paths for build Dockerfiles in the output of `docker-compose config`.
Old behavior:
```
❯ cat docker-compose.yml
version: '3'
services:
foo:
build:
context: ../foo
dockerfile: Dockerfile
❯ docker-compose disable-v2
❯ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
❯ docker-compose config
services:
foo:
build:
context: /Users/mattm/dev/foo
dockerfile: Dockerfile
version: '3'
```
New behavior:
```
❯ docker-compose enable-v2
❯ docker-compose version
Docker Compose version v2.0.0-beta.6
❯ docker-compose config
services:
foo:
build:
context: /Users/mattm/dev/foo
dockerfile: …
```
=> docker-compose: Support absolute path to Dockerfile in docker-compose build

web/package.json, web/src/OverviewResourcePane.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewResourceSidebar.tsx, web/src/Resizer.scss, web/src/SidebarItemView.stories.tsx, web/src/constants.scss, web/src/style-helpers.ts, web/yarn.lock
Please review the following commits I made in branch nicks/ch12138:
5b89976f30b9300b76611eaa2956a28d1d511c4f (2021-07-19 13:50:04 -0400)
web: Add a resize drag component to the sidebar
Fixes https://github.com/tilt-dev/tilt/issues/4614
=> web: Add a resize drag component to the sidebar

internal/engine/uiresource/subscriber.go, internal/engine/uisession/subscriber.go
Tilt regularly (~40% of the time on my machine) logs messages like this on startup:
```
creating uisession: uisessions.tilt.dev "Tiltfile" already exists
creating uiresource (Tiltfile): uiresources.tilt.dev "(Tiltfile)" already exists
```
These errors aren't really actionable or problematic but make it look like something went wrong.
Don't log the error - just return it and let the retry happen.
=> engine: don't log spurious uiresource/uisession errors

internal/cli/wire.go, internal/cli/wire_gen.go, internal/controllers/core/cmd/execer.go, internal/controllers/core/cmd/execer_test.go, internal/engine/buildcontrol/local_target_build_and_deployer_test.go, internal/engine/upper_test.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/localexec/localexec.go, internal/localexec/localexec_test.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Hello @milas,
Please review the following commits I made in branch nicks/env:
e24fe359841eb5f889bc1b53d96e63a882116e03 (2021-07-20 18:34:14 -0400)
localexec: two improvements for running controllers with local_resource:
- disable analytics
- set TILT_PORT and TILT_HOST to ensure we're talking to the right tilt instance
=> localexec: two improvements for running controllers with local_resource:

internal/store/subscriber.go
repro: `go test ./internal/engine -run TestConfigChange_ManifestWithPendingChangesBuildsIfTriggerModeChangedToAuto -count 100`
Sometimes on failures, I've gotten 100s of these in my output:
```
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context canceled
Problem processing change. Backing off 15s. Error: context …
```
=> store: stop retrying subscriber notifications on shutdown

internal/store/subscriber.go, internal/store/subscriber_test.go
I was hitting one of these errors so I threw this in to track it down.
We could also do this via a `SubscriberName` method on the `Subscriber` interface to avoid the reflection perf hit. I'm guessing in error cases the reflection perf hit is insignificant, relatively.
=> store: log subscriber name on notify error

internal/engine/configs/api.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
As part of apiserver transition, there is special handling for
certain objects that originate from the Tiltfile that can't be
represented via `OwnerReference` (since the Tiltfile does not
yet live in the API).
Because multiple places create/manage these objects and the
label assignment logic was inconsistent, there was a race where
the `uiresource` objects could get created without the label,
so the subscriber would not find them when looking for objects
to manage and instead try to (re)create them and fail with an
already exists error:
```
Failed to update API server: create uiresources/local: uiresources.tilt.dev "foo" already exists
```
Assignment is now done on ALL manifests via their new label
support during Tiltfile load. This label (along with any other
custom labels) are …
=> tiltfile: add Tiltfile owner label to all manifests

web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/ResourceStatusSummary.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx, web/src/types.ts
This PR removes the test / non-test resource grouping and filtering, since that delineating will be replaced with labels.
If we want to keep the test / non-test filters code, but turn it off instead of deleting it, I can do that instead.
Closes [ch12251](https://app.clubhouse.io/windmill/story/12251/hide-non-test-test-resource-code-throughout-ui-with-labels-feature-flag)
=> web: remove test and non-test default resource grouping

internal/controllers/core/podlogstream/podlogstreamcontroller.go
It was possible to get rare (but benign) error messages in the logs
about streaming:
```
Error streaming hello-xbhtp logs: Get "https://0.0.0.0:51700/api/v1/namespaces/default/pods/hello-xbhtp/log?container=hello&follow=true&sinceTime=2021-07-22T18%3A22%3A48Z": context canceled
```
There are two exit paths from the function - one already filtered
out context errors, while the other did not. In both cases, these
are not worthy of being logged, as they're part of normal execution
flow and will be handled (i.e. streaming will resume if it was
interrupted).
Fixes #3196.
=> podlogstream: do not log context errors

web/src/ResourceStatusSummary.test.tsx, web/src/ResourceStatusSummary.tsx
Clicking on a label group heading should only expand or collapse a group and not add/change log filters, (especially since we don't have log filtering by label group available). This PR removes those log filter links in label groups.
=> web: remove log filter links on resource status summary for label groups

Makefile, internal/dockercompose/client.go, internal/dockercompose/client_test.go
Currently, the `compose-go` library (used by the v2 Compose CLI)
has a regression in variable resolution: it applies it to the raw
YAML string _before_ parsing, so does not take field types into
consideration.
In Compose v1, variable substitution would appropriately quote
values based on the field type to avoid automatic YAML coercion
(e.g. `Y` -> `"Y"` for a string field to avoid it being interpreted
as a bool and causing a validation error).
As a temporary workaround, if the "native" (compose-go) parsing
fails, we shell out to `docker-compose config` (as we did previously)
to allow it to resolve the variables/merge configurations, and then
pass the prepared YAML to compose-go. This does rely on the user
having v1 docker-compose since v2 is broken, but the same was true
before even …
=> docker-compose: fix variable resolution type issues

internal/tiltfile/docker_compose.go, internal/tiltfile/docker_compose_test.go, internal/tiltfile/tiltfile_docker_compose_test.go
Some of the `compose-go` types are not marshalable with `yaml.v3`:
they will trigger infinite recursion and a stack overflow panic.
Internally, `compose-cli` uses `yaml.v2` when marshaling (e.g. for
output via `docker-compose config`).
This is now explicitly used, and a test has been added to prevent
regression. Due to other issues/requirements, `compose-go` is also
in the midst of upgrading to `yaml.v3`, so in the future we should
be able to upgrade it and switch to `yaml.v3` for marshaling its
types.
Fixes #4797.
=> docker-compose: fix stack overflow panic

web/src/SidebarResources.tsx, web/src/Tooltip.tsx, web/src/assets/svg/info.svg
This PR adds an info icon with a tooltip that gives the user information about grouping resources with a link to the docs. The icon will display regardless of whether labels are  The implementation is a little different than the design in Figma. After seeing how the icon overlapped with a resource item when scrolling, Surbhi recommended displaying the icon is against a solid, fixed background instead.
Info icon:
Info icon with tooltip:
Info icon with tooltip, when resource list is long:
This PR is blocked by [#895](https://github.com/tilt-dev/tilt.build/pull/895) and closes [ch12254](https://app.clubhouse.io/windmill/story/12254/add-documentation-and-help-callout).
=> web: add resource grouping (tool)tip with link to docs in the sidebar

internal/engine/k8srollout/podmonitor.go, internal/engine/k8srollout/podmonitor_test.go, internal/engine/k8srollout/testdata/TestJobCompletedAfterReady_master, internal/engine/k8srollout/testdata/TestJobCompleted_master
Fixes #3513
When a job's pod finishes, we get a PodCondition that says it's no longer in the ready state. This means we go back and update the pod rollout's "Ready" line in the log to "pending", which is very confusing. This is what the log shows for a completed job:
```
Tracking new pod rollout (echo-hi-rr7xd):
┊ Scheduled       - <1s
┊ Initialized     - <1s
┊ Ready           - (…) Pending
```
Treat PodCondition w/ Type="Ready" and Reason="PodCompleted" as meaning we're done with the pod, and munge "completed" into the "ready" field. I don't love this solution except for its cheapness, and am not sure doing something fancier is worth it right now.
=> pod rollout: don't show completed jobs as pending

internal/feature/flags.go
Enable resource grouping by default for the release tomorrow 🎉 
Closes [ch12255](https://app.clubhouse.io/windmill/story/12255/turn-feature-flag-on)
=> internal: enable resource grouping and labels feature flag

web/src/AnalyticsNudge.tsx, web/src/ErrorModal.tsx, web/src/OverviewActionBar.tsx, web/src/OverviewTable.tsx, web/src/ShortcutsDialog.tsx, web/src/SidebarResources.tsx, web/src/Tooltip.tsx, web/src/UpdateDialog.tsx, web/src/constants.ts
This pr adds two informational tooltips for trigger mode and for regexp log filtering, plus helpers for generating Tilt docs links.
=> web: add helpful tooltips for trigger mode toggle and regexp log filter

internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/api_test.go, internal/controllers/core/tiltfile/filewatch.go, internal/controllers/core/tiltfile/filewatch_test.go, internal/controllers/core/tiltfile/testdata_test.go, internal/engine/configs/configs_controller.go, internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/tiltfile3:
e02644d4fe5e9909e6f049d7fd53b112ea1d6a61 (2021-07-30 09:43:12 -0400)
controllers: move some APIs into the tiltfile reconciler package
=> controllers: move some APIs into the tiltfile reconciler package

internal/controllers/core/tiltfile/actions.go, internal/engine/configs/configs_controller.go, internal/engine/configs/configs_controller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/tiltfile/fake.go, internal/tiltfile/tiltfile.go
Hello @nicks,
Please review the following commits I made in branch nicks/tiltfile4:
6a7e67e1675937090939d92b3d0d9b1e79e88b13 (2021-07-30 17:11:14 -0400)
test: rearrange how fake tiltfile loaders are injected
also, reorganize actions into the controllers package
=> test: rearrange how fake tiltfile loaders are injected

internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/podorder2:
d27f0e7d0f685b030bc4585be2d9e81b692e93a8 (2021-07-30 17:41:12 -0400)
test: remove a bad test
This test is testing for two pods with the same name but different UIDs
coming in in reverse order (where the dead pod appears last).
But we use k8s infra that now indexes everything by name and prevents
this kind of ordering issue from happening.
=> test: remove a bad test

internal/controllers/apicmp/delta.go, internal/controllers/apicmp/delta_test.go
Please review the following commits I made in branch nicks/apicmp:
fb2932ade1507c4dbbc0653f5dbcfb0a7470239c (2021-07-30 16:04:46 -0400)
apicmp: panic if comparing two different types
=> apicmp: panic if comparing two different types

internal/k8s/portforward/error.go, internal/k8s/portforward/error_test.go, internal/k8s/portforward/portforward.go
Please review the following commits I made in branch nicks/ch12459:
4cdd6a54f84b5893a8a897c1d286844bcdc4f8f9 (2021-07-30 19:11:18 -0400)
portforward: handle broken spdy connections
Fixes https://github.com/tilt-dev/tilt/issues/4801
=> portforward: handle broken spdy connections

internal/tiltfile/print/print.go, internal/tiltfile/print/print_test.go, internal/tiltfile/starkit/environment.go, internal/tiltfile/starkit/error.go, internal/tiltfile/starkit/fixture.go
Currently we have `fatal()` for terminating Tiltfile execution
with an error.
However, there are some circumstances where it's desirable to
stop Tiltfile execution but NOT trigger an error. For example,
when debugging a problem, it's useful to disable everything
subsequent in the Tiltfile.
This adds `exit()` which will stop execution in a "successful"
manner.
An optional message can be provided which will be printed before
exiting.
Closes #4501.
=> tiltfile: add exit() built-in to stop execution

internal/cli/get_test.go, internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/hud/server/apiserver.go, internal/hud/server/apiserver_test.go
Please review the following commits I made in branch nicks/storage:
b84de2c2e97505b835ae58637675067faa989674 (2021-08-03 13:06:53 -0400)
server: store global extensions and repos on disk
=> server: store global extensions and repos on disk

web/src/OverviewTable.tsx
This link in the Trigger mode tooltip (shown in picture) is now opening in a new tab.
=> uibutton: opens link to trigger mode docs in a new tab

internal/controllers/core/cmd/execer.go, internal/controllers/core/cmd/execer_test.go, internal/localexec/localexec.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
`Env.ExecCmd` panics if given an empty `Cmd`. This reproduces with `local('')` or `local([])`.
Have it return an `error` instead.
We could instead check for empty at the starlark builtin level, but it seems good to also avoid panics if someone, e.g. creates a `Cmd` object with an empty argv.
=> cmd: error instead of panic when empty

go.mod, go.sum, vendor/github.com/tilt-dev/go-get/vcs.go, vendor/modules.txt
Update to `tilt-dev/go-get@v0.2.1` which includes a small fix for
CWD when executing commands.
In general, this would result in a spurious git submodule update in
the user's Tilt project repo (i.e. wherever the `Tiltfile` lives)
but things would still work since the `tilt-extensions` repo does
not rely on submodules.
However, if the directory with the `Tiltfile` happened to not be a
git repo, the extension load would fail with a cryptic error about
it not being in a git repo:
```
fatal: not a git repository (or any of the parent directories): .git
```
This is because it was trying to do the submodule update
in the wrong place.
=> extensions: fix extension loading in non-git Tilt projects

internal/tiltfile/v1alpha1/plugin_test.go, internal/tiltfile/v1alpha1/types.go
Please review the following commits I made in branch nicks/ref:
cb91c56b89b09d155908ce33e5e742dbc79ade25 (2021-08-13 14:40:14 -0400)
tiltfile: add ref field to v1alpha1.extension_repo
=> tiltfile: add ref field to v1alpha1.extension_repo

internal/hud/server/logs_reader.go, internal/hud/server/logs_reader_test.go
Please review the following commits I made in branch nicks/debug:
89b3aaaa585008d820ac120cae8dd536f2a4d906 (2021-08-13 18:39:53 -0400)
hud: fix a nil pointer exception in tilt logs
=> hud: fix a nil pointer exception in tilt logs

web/src/HUD.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewTable.stories.tsx, web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/ResourceGroupsContext.test.tsx, web/src/ResourceGroupsContext.tsx, web/src/SidebarResources.tsx, web/src/labels.test.ts
This PR adds state that tracks which label groups are expanded / collapsed and persists across views within the dashboard and across user sessions. If there isn't any saved state for a label group, then it'll default to expanded. As a user toggles a group closed and open, the `ResourceGroupsContext` will track that label's expanded state in local storage, under the "resource-groups" key.
Resource groups aren't live in table view yet, so the best way to test locally is in Storybook. You can toggle [OverviewResourcePane > Ten Resources With Labels](http://localhost:9009/?path=/story/new-ui-overviewresourcepane--ten-resources-with-labels) and [Overview > OverviewTable > Ten Resources With Labels](http://localhost:9009/?path=/story/new-ui-overview-overviewtable--ten-resource-with-labels) and …
=> web: add persistent state to resource grouping

web/.storybook/preview.js, web/src/OverviewTable.stories.tsx
(not necessarily looking for reviews from everyone but figured it'd be worth a bit of wider awareness since this might lead to surprises)
This fixes two issues that can lead to annoying/hard-to-debug differences between the webui and stories:
1. <Icon>${iconName}</Icon> will just show the value of the string `iconName` rather than the material icon named `${IconName}` (I don't know why icons work without this in the Tilt UI - I figure it just ends up happening via one of the many libraries we load, and haven't had much reason to actually take time to figure it out)
2. MUI styles take precedence over styled components' styles (this just makes the storybooks consistent with the [hud](https://github.com/tilt-dev/tilt/blob/d403ec100466fcb239f07854e18e179c4302d888/web/src/HUD.tsx#L246-L247))
=> storybook: add a global decorator

web/src/OverviewButton.tsx, web/src/instrumentedComponents.tsx, web/src/style-helpers.ts
In a separate branch, I'm trying to use MUI's [ButtonGroup](https://material-ui.com/components/button-group/), which needs MUI `Button`s rather than `button`s.
This might be a bit controversial since `InstrumentedButton` is kind of controversial in the first place for mixing analytics and rendering, but I don't think this really commits us further to it?
(fwiw (and at the risk of sparking that controversy in this PR) - I went down the path of getting rid of `InstrumentedButton` and replacing it with an `instrumentedOnClick` that takes a click handler and wraps it with a call that reports the click to analytics, but didn't like result - it seemed too much up to every single component to remember to call `instrumentedOnClick`, while with `InstrumentedButton`, the compiler ensures we specify …
=> web: have InstrumentedButton use MUI Button instead of a plain ol' button

web/src/HeaderBar.tsx, web/src/OverviewResourceBar.tsx, web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/ResourceGroups.tsx, web/src/ResourceStatusSummary.tsx, web/src/SidebarResources.tsx
This PR adds resource status summaries to groups in table view and refactors the core status summary code to take a template type so it can be used for resources in different data forms.
The best way to test this code is to look at Storybook in [Overview > OverviewTable > Ten Resources With Labels](http://localhost:9009/?path=/story/new-ui-overview-overviewtable--ten-resource-with-labels), since groups are available in the main table view just yet!
Collapsed and expanded groups:
Collapsed groups:
Closes [ch12501](https://app.clubhouse.io/windmill/story/12501/display-resource-status-summary-for-each-label-group).
=> web: add resource status summaries to groups in table view

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/k8swatch/reducers.go, internal/engine/upper_test.go, internal/store/build_result.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/jobs:
ef490cca875b509964c65f54d655f3b890c8546b (2021-08-19 20:12:49 -0400)
engine: don't look in completed pods for running containers
I was playing around with live-update Jobs.
I saw weird behavior where:
- builds would get stuck pending forever on already completed jobs
- tilt would think that a pod had crash when a job completed normally
Note that this changes the behavior of crash rebuild.
Before, if a pod crashed, Tilt would immediately begin a new build.
Now, if a pod crashes, Tilt waits for the controller to replace
it before starting the crash rebuild.
I think this behavior is probably more correct, given
that Tilt can't know if the controller is going to replace the Pod.
Code review reminders, by …
=> engine: don't look in completed pods for running containers

internal/controllers/core/kubernetesapply/disco.go, internal/controllers/core/kubernetesapply/disco_test.go, internal/k8s/target.go, internal/k8s/target_test.go, internal/tiltfile/k8s.go, internal/tiltfile/k8s/types.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/apis/core/v1alpha1/generated.proto, pkg/apis/core/v1alpha1/kubernetesapply_types.go, pkg/apis/core/v1alpha1/kubernetesdiscovery_types.go, pkg/openapi/zz_generated.openapi.go
Please review the following commits I made in branch nicks/ch12592:
775362907588eedee90fe5363dfe5434925d7d5a (2021-08-23 18:46:54 -0400)
kubernetesapply: add support for discovery_strategy='selectors-only'
You can specify this in the tiltfile as
k8s_resource(..., discovery_strategy='selectors-only')
and tilt will create kdisco objects with namespace-only watches (no UIDs).
Fixes https://github.com/tilt-dev/tilt/issues/4867
b88eb3c55ca0c14a13474270f489987551aafb05 (2021-08-23 17:38:08 -0400)
apis: data model for k8s discovery options
* Code is suitably instrumented with logging and …
=> kubernetesapply: add support for discovery_mode='selectors-only'

internal/build/tar.go
When performing a live update, we create a tar with a batch of
changed files for efficiency. When adding a file to the tar, if
the source file on disk no longer exists, we can safely skip it:
it has since been deleted, so a delete event should be in the
next batch of file events and will be processed by live update.
However, the header was _always_ being written to the tar file,
which includes the file size, but then we'd simply not write the
file, producing an invalid tar. Specifically, it'd hit EOF too
early since it was expected to read `n` bytes as specified by the
header, but then there was nothing.
This wasn't always caught because often only a single file is in
the live update changeset, so it's the only tar entry. The Go
stdlib catches this on `Flush()` which is called either when …
=> docker: avoid unexpected EOF tar errors

internal/controllers/core/extension/reconciler_test.go, internal/controllers/core/extension/tiltfiles.go, pkg/apis/identifiers.go
Hello @landism, @lizzthabet,
Please review the following commits I made in branch nicks/labels:
5a9a3b7eaa94dfee4cbf8c98c5311c33e3861bf9 (2021-08-24 19:32:25 -0400)
extension: group each extension by its own label
=> extension: group each extension by its own label

web/src/HUD.test.tsx, web/src/HUD.tsx
UIButtons are in seemingly random order when you refresh the web UI.
#4886 fixed object sorting in hud view updates, except that codepath only runs on view updates, not on complete views.
Also apply the sorting on complete views.
(this wasn't a problem previously because on complete views, the backend sends UIResources in sorted order anyway, and UIButtons had redundant sorting elsewhere, which #4886 removed)
=> hud: sort objects on complete view

web/src/ApiButton.tsx
#4894 always added a left margin to button labels, even when there was no icon
Only add the margin when the label follows an icon
=> web: only add margin to apibutton label when there's an icon

internal/tiltfile/build_index.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/updatesettings/update_settings.go, pkg/model/update_settings.go
Please review the following commits I made in branch nicks/ch12647:
6803f9615d09d6aba53b73a5531f56edf86b08a9 (2021-08-31 12:29:22 -0400)
tiltfile: add a mechanism to suppress unused image warnings
Examples:
update_settings(suppress_unused_image_warnings=['image-name'])
update_settings(suppress_unused_image_warnings='*') # suppress all
Fixes https://github.com/tilt-dev/tilt/issues/4891
=> tiltfile: add a mechanism to suppress unused image warnings

internal/container/default_registry.go, internal/container/default_registry_test.go
Hello @milas,
Please review the following commits I made in branch nicks/ch12648:
144a76fe1aa8c5c11626e0afe8c4023009e10748 (2021-08-31 12:50:41 -0400)
container: don't rebase image names that don't need it
Fixes https://github.com/tilt-dev/tilt/issues/4911
=> container: don't rebase image names that don't need it

web/src/OverviewTable.tsx, web/src/OverviewTableStatus.tsx, web/src/ResourceGroups.tsx, web/src/StarredResourceBar.tsx
This PR makes two style changes I chatted about with @SurbhiSGupta: 
* increase font size so text is easier to read
* add a little bit of padding in between columns / table cells so text from different columns doesn't run into other columns
before:
after:
=> web: increase font size and add padding between table cells in table view

internal/k8s/env.go, internal/k8s/env_test.go
[Rancher Desktop](https://rancherdesktop.io/) is a new local K8s distribution.
See also tilt-dev/tilt.build#931 for a blog post explaining how to use it with Tilt.
=> k8s: allow rancher-desktop context by default

internal/controllers/apis/configmap/triggerqueue.go, internal/engine/configs/trigger_queue_subscriber.go, internal/engine/configs/trigger_queue_subscriber_test.go
Hello @milas,
Please review the following commits I made in branch nicks/triggerqueue:
9f0907ffe54df9478a29535a177669ca5d0c21a2 (2021-09-02 17:25:37 -0400)
configs: also store trigger queue reasons in the apiserver
=> configs: also store trigger queue reasons in the apiserver

web/src/LocalStorage.tsx, web/src/OverviewActionBar.tsx, web/src/OverviewTable.tsx, web/src/ResourceGroups.tsx, web/src/Tooltip.test.tsx, web/src/Tooltip.tsx
Info tooltips are really helpful for introducing users to new features! However, they can be kind of distracting and annoying if you're already familiar with their information.
Add a button to the info tooltip to allow the user to hide the info button.
When clicked, a bool will be written to localStorage and the user will no longer see that little (i) or the tooltip (unless they do something like switch browsers or clear local storage).
Notes:
1. There is currently no way to undo this other than digging into your browser's localStorage.
2. Until now, all of the info Tilt stores in localStorage has had its key namespaced by the path to the currently running Tiltfile. That seems like it'd be much more annoying than useful for this feature, so dismissals do not use the Tiltfile in their …
=> web: make info buttons hideable by user

internal/cli/wire_gen.go, internal/controllers/apis/configmap/triggerqueue.go, internal/controllers/apis/restarton/restarton.go, internal/controllers/core/extension/tiltfiles.go, internal/controllers/core/tiltfile/buildsource.go, internal/controllers/core/tiltfile/reconciler.go, internal/controllers/core/tiltfile/reconciler_test.go, internal/controllers/manager.go, internal/engine/buildcontroller.go, internal/engine/configs/configs_controller.go, internal/engine/configs/configs_controller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/actions.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/store/engine_state.go, internal/store/tiltfiles/args.go
Please review the following commits I made in branch nicks/configs2:
0fbfb9701b233c56d9db5a343618fa8eab30676f (2021-09-02 20:22:46 -0400)
controllers: move all rebuild triggers to the tiltfile controller
=> controllers: move all rebuild triggers to the tiltfile controller

web/src/OverviewTable.tsx
If you open table view when any resources do not have a last deploy time, you get these in your js console:
```
[react-timeago] Invalid Date provided 
at TimeAgo (http://localhost:10350/static/js/vendors~main.chunk.js:100008:5)
at TableUpdateColumn (http://localhost:10350/main.4a1820d1880d4331f4d2.hot-update.js:217:19)
at td
at O (http://localhost:10350/static/js/vendors~main.chunk.js:108247:6)
at tr
at O (http://localhost:10350/static/js/vendors~main.chunk.js:108247:6)
at tbody
at table
at O (http://localhost:10350/static/js/vendors~main.chunk.js:108247:6)
at Table (http://localhost:10350/main.4a1820d1880d4331f4d2.hot-update.js:754:17)
at TableWithoutGroups (http://localhost:10350/main.4a1820d1880d4331f4d2.hot-update.js:978:80)
at section
at O …
```
=> web: fix timeago console errors on table view

internal/cli/create.go, internal/cli/create_cmd.go, internal/cli/create_filewatch.go, internal/cli/create_repo.go, internal/cli/create_repo_test.go, pkg/apis/core/v1alpha1/extensionrepo_types.go
Hello @milas,
Please review the following commits I made in branch nicks/generator:
e3220afe93feb6a3dd3c69f3e2eb0eb2bf2a4bd5 (2021-09-03 13:45:49 -0400)
cli: add a convenience function over extension repos
=> cli: add a convenience function over extension repos

internal/build/options.go, internal/docker/client.go, internal/docker/options.go, internal/dockercompose/client_test.go, internal/testutils/env.go, internal/tiltfile/docker.go, internal/tiltfile/docker_test.go, internal/tiltfile/tiltfile_state.go, pkg/model/image_target.go
Docker CLI has a `--platform` argument and `DOCKER_DEFAULT_PLATFORM`
environment variable for default.
This is useful when dealing with multi-architecture images in
different scenarios, e.g. using an M1-based macOS machine.
This adds a `platform` argument to `docker_build` which will get
passed through to Docker/BuildKit. Similar to the Docker CLI, if
not specified, `DOCKER_DEFAULT_PLATFORM` will be used as a default
if set.
Fixes #4932.
=> docker: platform argument to customize image arch

internal/cli/apply_test.go, internal/cli/create.go, internal/cli/create_cmd_test.go, internal/cli/create_ext.go, internal/cli/create_ext_test.go, internal/cli/create_filewatch_test.go, pkg/apis/core/v1alpha1/extension_types.go
Hello @milas,
Please review the following commits I made in branch nicks/generator2:
dea70380f1a2f0329df620736e77d16e6d7397f3 (2021-09-03 14:58:01 -0400)
cli: add a convenience function for installing extensions
e3220afe93feb6a3dd3c69f3e2eb0eb2bf2a4bd5 (2021-09-03 13:45:49 -0400)
cli: add a convenience function over extension repos
=> cli: add a convenience function for installing extensions

web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx
Basically just applying [this](https://github.com/tilt-dev/tilt/blob/844f193f6539966ea6c0c70aa619d04aea2b288f/web/src/OverviewTable.tsx#L490-L495) to the columns that weren't already returning primitives from accessor, following the pattern that seems to be working for uibuttons.
=> web: table view: allow sorting by status, fix sorting by endpoints

web/src/OverviewButton.tsx
Fix the focus/hover border weirdness spotted in [this PR comment](https://github.com/tilt-dev/tilt/pull/4898#pullrequestreview-742973668)
MUI is kind of annoying for this:
In a button group, each line between buttons is on the same 1px from each neighbor button. MUI does this by adding `margin-left: 1px;` to each button in the group other than the first.
Button 2's left border gets rendered on top of button 1's right border.
My understanding of the way this works in normal MUI is:
1. give the buttons a transparent background, so button 2's background doesn't wipe out button 1's right border
2. make the normal border color transparent, so that when button 2's left border is rendered on top of button 1's right border, you still see most of button 1's right border.
I'd previously tried to …
=> web: fix borders on table view api buttons

web/src/OverviewTable.tsx
Clicking on a header column multiple times to cycle through sort orders annoyingly results in the titles being selected
Make the headers unselectable. Maybe this will be slightly annoying to someone who wants to copy a header title, but the highlighting feels pretty broken as-is.
NB: FWIW, the text inside a header's info tooltip is still selectable after this change
=> web: don't highlight header titles on multiple clicks

web/src/ApiButton.tsx, web/src/CustomNav.tsx, web/src/GlobalNav.tsx
Fixes navbar issues from this [PR's comment](https://github.com/tilt-dev/tilt/pull/4898#pullrequestreview-742973668):
1. title display on hover overlaps and can lead the user to click the wrong button
2. (very subtle) drop shadow on buttons that shouldn't be there
3. ripple displays on click and shouldn't be there
4. icon and button seems to darken/flicker on click, though this could be related to the disabled/loading state
5. the click area is a little strange for the button groups. the click area is large for the command button itself, but small for the dropdown button. i think we could solve this by making the size of the command button / button group smaller and centering the button title display, but i didn't play around with this solution!
=> web: fix navbar button styling

internal/controllers/core/extension/reconciler_test.go, internal/controllers/core/extension/tiltfiles.go, internal/controllers/core/tiltfile/reconciler.go, internal/hud/webview/convert.go
Hello @milas,
Please review the following commits I made in branch nicks/tiltfile2:
e362ad9879a72e7c9825c3a90e23d16f9453a50e (2021-09-07 14:55:34 -0400)
extension: set up filewatch triggers correctly
=> extension: set up filewatch triggers correctly

internal/controllers/core/extension/reconciler.go, internal/controllers/core/extension/reconciler_test.go
Hello @milas,
Please review the following commits I made in branch nicks/args:
211609a6b33bfeb0195d334f45c0d07f22897aab (2021-09-08 10:37:07 -0400)
extension: propagate extension arg changes correctly
=> extension: propagate extension arg changes correctly

web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/StarredResourceBar.tsx
This PR adds a global sort state for Table View, so that when there are multiple resource group tables, they can all be sorted by the same column. Clicking on one sortable header will sort all the tables at once. It also adds a highlight to the sorted column, so it's clearer to the user that the tables are sorted.
The interface that `react-table` exposes for manually managing table state is not super intuitive. 🙃 (I haven't seen any examples of handling sort state outside of the component itself.) This approach consists of:
* using the `useControlledState` hook, which can override any `react-table`-tracked state
* manually implementing the default sort behavior of `react-table` so we can track the global sort state ourselves
* passing a click handler to columns through the …
=> web: improve table sorting

internal/dockercompose/client.go, internal/dockercompose/fake_client.go, internal/engine/dcwatch/event_watcher.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/runtimelog/docker_compose_log_manager_test.go, internal/engine/upper_test.go
The core issue this aims to solve is that for a stopped container,
`docker-compose logs` exits, and Tilt would continuously attempt
to re-launch it, resulting in high CPU usage due to repeatedly
invoking the command.
However, there were actually several intermingled issues that this
exposed/worsened. These mostly tie back to the behavior of
`docker-compose logs`: there is no built-in support for time
filtering (unlike `docker logs --since ...`), and since it exits
when a container stops, once invoked again, all the old logs will
be returned again. This means if a container crashes/restarts,
we'd re-emit all the old logs each time. Similarly, if there is
a "job" container that naturally runs to completion, whenever
re-triggered from the UI to run it, all the logs from prior
invocations …
=> docker-compose: log tailing robustness fixes

internal/cli/docker_prune.go, internal/cli/down.go, internal/cli/tiltfile_result.go, internal/controllers/apis/tiltfile/main.go, internal/controllers/core/tiltfile/reconciler.go, internal/engine/configs/configs_controller.go, internal/engine/upper_test.go, internal/tiltfile/fake.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/fetcher2:
5f94b0f148e6acc5a15917665b3a97363e7e5974 (2021-09-09 12:27:43 -0400)
tiltfile: Pass the Tiltfile model into TiltfileLoader
=> tiltfile: Pass the Tiltfile model into TiltfileLoader

internal/engine/upper_test.go
This is not the result of any behavior changes from the recent
Docker Compose changes. This test is a negative test case to
ensure we filter out the "Attaching to foo" message Docker Compose
emits at the beginning of every log session. Previously, it was
only checking that it hadn't seen that exact message. In attempt
to tighten it up, it now asserts that it hasn't seen that message
AND that it HAS seen a message that _should_ be output.
Turns out that there was a race in the test, so it was looking at
the logs while they were still empty sometimes. It would pass
before but fails now due to being stricter.
The solution is a copy-paste from another DC test that relies
on logs.
=> engine: fix flaky Docker Compose test

.circleci/config.yml
Temporarily allow downgrading to Go 1.16 until we upgrade all
OSes to 1.17 for test/release.
NodeJS v16.9.0 has a regression causing a crash:
```
Check failed: !holder_map.has_named_interceptor().
```
Temporarily pin to v16.8.
=> ci: fix Windows + Javascript jobs

.circleci/Dockerfile.integration, .circleci/config.yml, go.mod, internal/dockercompose/client.go, internal/dockercompose/client_test.go, internal/dockercompose/fake_client.go, internal/tiltfile/docker_compose_test.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, vendor/modules.txt
There's two parts here:
1. Look for the `docker-compose-v1` binary in the path and prefer
that (fall back to `docker-compose` if it does not exist) until
Compose v2 is stable and does not have issues with Tilt
2. Add `DockerComposeClient::Version()` method and use it during
Tiltfile load to either error if a minimum version is not met
or warn if v2 is being used; the latter check can be adjusted
to only warn for v2 under a minimum version once it's stable
and known issues with Tilt have been addressed
=> docker-compose: version detection logic

web/src/ApiButton.tsx, web/src/GlobalNav.tsx, web/src/OverviewButton.tsx
Fixes #4954 
1. In the overview action bar, when a uibutton is disabled, its submit button is effectively invisible. Also, its options button gets no disabled styling.
2. In the nav bar, there's no visual indication that a button is disabled.
3. The UI was not showing the appropriate cursor on disabled buttons.
1. Fix the disabled styling for overview buttons and apply the same to the options button.
1. I accomplished the latter by just disabling the options button, which is hacky, but was almost free and seems unlikely to have much user impact. If a user notices this we can spend the time to apply the styling without disabling the button, or if anyone thinks that's worth the time now, I'll do it.
2. Add some opacity to the disabled styling for nav bar buttons.
3. Apply the [mui …
=> web: fix rendering of disabled api buttons

internal/store/store.go, internal/store/store_test.go
A couple action handlers in the upper reducer [append directly to the logstore](https://github.com/tilt-dev/tilt/blob/688f5dfb982ce68de84977dc26e3d12b7f486355/internal/engine/upper.go#L352), but don't implement `Summarizer`, so they do not set `Summary.Log` when they are handled.
The WebSocketSubscriber only passes log updates to the frontend when [`summary.Log` is true](https://github.com/tilt-dev/tilt/blob/13c9bb803c8cfe08b51beaaa32788c565f3b69bd/internal/hud/server/websocket.go#L122). When one of these messages is logged: 1) at the time, it shows up in the TUI but not the web ui 2) the next time something is logged (properly), it shows up in the web ui. This can be quite some time later.
AFAIK this problem hasn't been affecting prod, because these logs happen to precede other logging …
=> store: infer ChangeSummary.Log

web/src/HUD.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewTable.stories.tsx, web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/OverviewTablePane.stories.tsx, web/src/ResourceListOptionsContext.tsx, web/src/ResourceNameFilter.test.tsx, web/src/SidebarResources.test.tsx
This PR adds the resource name filter to Table View. I have a couple detail-oriented design questions for Surbhi, though those questions aren't blockers for review.
Example of resource filtering with labels:
Closes [ch12500](https://app.shortcut.com/windmill/story/12500/add-resource-name-filter-to-table-view)
=> web: add resource name filter to Table View

internal/controllers/apis/tiltfile/main.go, internal/engine/configs/configs_controller_test.go, internal/tiltfile/config/config.go, internal/tiltfile/config/config_test.go, internal/tiltfile/config/resources.go, internal/tiltfile/k8scontext/k8scontext.go, internal/tiltfile/k8scontext/k8scontext_test.go, internal/tiltfile/starkit/environment.go, internal/tiltfile/starkit/fixture.go, internal/tiltfile/starkit/model.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, pkg/webview/view.pb.go
Please review the following commits I made in branch nicks/allowed:
af810d6f5d1412cc361a7f5731662e08f573ca10 (2021-09-20 19:54:41 -0400)
tiltfile: kubecontext protection shouldn't apply when loading extensions
Fixes https://github.com/tilt-dev/tilt-extensions/issues/253
=> tiltfile: kubecontext protection shouldn't apply when loading extensions

internal/controllers/apiset/apiset.go, internal/controllers/core/tiltfile/api.go, internal/tiltfile/v1alpha1/plugin.go, internal/tiltfile/v1alpha1/plugin_test.go, internal/tiltfile/v1alpha1/types.go, pkg/apis/core/v1alpha1/filewatch_types.go
Hello @milas,
Please review the following commits I made in branch nicks/filewatchcodegen:
22cc7165582aa74fa81b01cdf32a745632594941 (2021-09-20 16:33:30 -0400)
tiltfile: add built-in for filewatch
=> tiltfile: add built-in for filewatch

internal/controllers/apis/configmap/disable.go, internal/controllers/apis/configmap/disable_test.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/controller_test.go, internal/controllers/core/cmd/types.go
When a `Cmd`'s disable `ConfigMap` is set, the `Cmd` will disable/enable and set its `Status.DisableStatus` as appropriate.
=> cmd: reconciler uses DisableSource/Status

internal/cli/openapi.go, internal/hud/server/apiserver.go
Hello @milas,
Please review the following commits I made in branch nicks/ch12774:
b2159dc4a539e0b69e3b96d508b2c6c09dc09651 (2021-09-23 20:08:38 -0400)
cli: use XDG_HOME for headless cert generation
=> cli: use XDG_HOME for headless cert generation

internal/docker/client.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go
This is in preparation for directly creating+running containers
with Docker, where it's necessary to do a pull first to ensure
the image exists before creating the container (this is automatic
behavior from the CLI but not when using the API).
(This was split out of #4988.)
=> docker: add image pull method

internal/cli/demo/k3d.go
To simplify trying out Tilt when following the new tutorial, we
want an "all-in-one" `tilt demo` command that will launch a
temporary K8s cluster, clone the sample project, and `tilt up`
against it.
To avoid extra dependencies within Tilt, this is an experimental
k3d client that executes k3d commands by running k3d itself via
Docker with the Docker socket mounted. This eliminates the need
for the user to have k3d downloaded (or Tilt to play "package
manager" and grab the appropriate binary from GitHub releases.)
There's a few quirks/limitations with this approach, namely that
k3d can't interact with the host system to e.g. update kubeconfig.
However, that's actually desirable in this instance as we want to
keep things isolated.
Longer-term, particularly if we want Tilt to truly manage …
=> demo: add k3d-via-Docker client to provision clusters

internal/controllers/core/filewatch/controller.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/engine/upper.go, internal/store/engine_state.go, internal/store/filewatches/actions.go, internal/store/filewatches/reducers.go, internal/store/kubernetesapplys/actions.go, internal/store/kubernetesapplys/reducers.go, internal/store/kubernetesdiscoverys/actions.go, internal/store/kubernetesdiscoverys/reducers.go
Please review the following commits I made in branch nicks/liveupdate7:
b14c6bd5c60f73e0c40f5416159581b1a3b4e943 (2021-09-29 13:19:02 -0400)
engine: temporarily replicate FileWatch, KubernetesApply, and KubernetesDiscovery back to the EngineState
This will help enable the tried-and-true pattern of
"let's make everything use API models before moving them to the reconciler"
=> engine: temporarily replicate FileWatch, KubernetesApply, and KubernetesDiscovery back to the EngineState

pkg/apis/core/v1alpha1/uibutton_types.go, web/src/ApiButton.test.tsx, web/src/ApiButton.tsx
In #4992, I relied only on unit tests, which missed a couple bugs:
1. UIInput validation fails since it's unaware of the 'hidden' input type
2. If a button has only hidden fields, it shows the arrow button to toggle the options form, which is then empty. instead, we should not show the arrow.
=> web: fix a couple UIButton hidden input bugs

internal/cli/wire_gen.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/reducers.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/store/build_result.go, internal/store/json_test.go, internal/store/k8sconv/resource.go, internal/store/runtime_state.go, pkg/webview/view.pb.go
Please review the following commits I made in branch nicks/lu10:
6ef1e4c198ea19816930c3cf1be5731a82a6a6e8 (2021-09-30 16:39:01 -0400)
store: create helper objects for summarizing Discovery+Apply
Right now, we decide which pods to LiveUpdate based on a complex
set of information from Discovery+Apply. We want to move all the relevant
info into its own object, separate from the old K8sRuntimeState
=> store: create helper objects for summarizing Discovery+Apply

internal/engine/upper_test.go, internal/k8s/pod_template.go, internal/store/store.go, internal/testutils/podbuilder/podbuilder.go
Please review the following commits I made in branch nicks/lu12:
247f0fd7ac42aab89120eb51af1ddcf9e04ba17c (2021-10-01 12:30:36 -0400)
test: improve how we infer pod template hashes
d80e6ee232c4c1e4919a547fce266deee8798412 (2021-09-30 16:42:25 -0400)
store: create helper objects for summarizing Discovery+Apply
Right now, we decide which pods to LiveUpdate based on a complex
set of information from Discovery+Apply. We want to move all the relevant
info into its own object, separate from the old K8sRuntimeState
=> test: improve how we infer pod template hashes

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/k8swatch/reducers.go, internal/engine/upper.go, internal/store/build_result.go, internal/store/engine_state.go, internal/store/k8sconv/resource.go, internal/store/kubernetesapplys/reducers.go, internal/store/kubernetesdiscoverys/reducers.go, internal/store/liveupdates/reducers.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/lu11:
c3f5735ac54a10d43e528b0aaedc4fd57137817f (2021-10-01 13:01:00 -0400)
engine: infer liveupdate pods from KubernetesApply+KubernetesDiscovery
247f0fd7ac42aab89120eb51af1ddcf9e04ba17c (2021-10-01 12:30:36 -0400)
test: improve how we infer pod template hashes
d80e6ee232c4c1e4919a547fce266deee8798412 (2021-09-30 16:42:25 -0400)
store: create helper objects for summarizing Discovery+Apply
Right now, we decide which pods to LiveUpdate based on a complex
set of information from Discovery+Apply. We want to move all the relevant
info into its own object, separate from the old K8sRuntimeState
* Code is easy to understand and …
=> engine: infer liveupdate pods from KubernetesApply+KubernetesDiscovery

internal/cli/wire_gen.go, internal/dockercompose/state.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/store/build_result.go, internal/store/engine_state.go, internal/store/engine_state_test.go, pkg/webview/view.pb.go
Hello @landism, @lizzthabet,
Please review the following commits I made in branch nicks/ch12807:
a144c3df5d065ef7aa56382c472d2e596e75351e (2021-10-01 17:35:57 -0400)
engine: create links for dynamically allocated Docker Compose ports
Fixes https://github.com/tilt-dev/tilt/issues/4998
=> engine: create links for dynamically allocated Docker Compose ports

internal/containerupdate/container_updater.go, internal/containerupdate/docker_container_updater.go, internal/containerupdate/docker_container_updater_test.go, internal/containerupdate/exec_updater.go, internal/containerupdate/fake_container_updater.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/extractors.go, internal/engine/buildcontrol/live_update_build_and_deployer.go, internal/engine/buildcontrol/live_update_build_and_deployer_test.go, internal/engine/buildcontrol/live_update_state_tree.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/store/build_result.go, internal/store/dcconv/resource.go, internal/store/engine_state.go, internal/store/liveupdates/containers.go, internal/store/liveupdates/fake.go, internal/store/liveupdates/reducers.go
Please review the following commits I made in branch nicks/lu13:
aabc42555e5756b7075071330df46fa4123341a0 (2021-10-04 20:05:26 -0400)
engine: Pass KubernetesResource and KubernetesSelector to BuildState
This is mostly a giant yak shave. Getting both data and testdata
into the format that the LiveUpdate API expects.
=> engine: Pass KubernetesResource and KubernetesSelector to BuildState

scripts/install.sh
Hello @milas,
Please review the following commits I made in branch nicks/installer:
5e6177cdb4dc9ba8513cd015ff2f76efe043b9c0 (2021-10-29 17:41:29 -0400)
scripts: update installer now that ALPHA has been removed
=> scripts: update installer now that ALPHA has been removed

.circleci/config.yml
Looks like Homebrew made some change, so make a new cache version.
=> ci: bump Brew cache version

.circleci/config.yml
We were only using Homebrew for installing Go, so using CircleCI orb seems easier than trying to debug whatever is wonky with the caching.
=> ci: use circleci orb for Go on macOS

internal/cli/wire_gen.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/wire.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/upper_test.go, internal/engine/wire.go, internal/engine/wire_gen.go
Reconciler isn't actually using this still: just pulling it out
into its own commit/PR because the wire changes were fairly
pervasive/noisy on their own.
=> api: inject localexec.Excer into KubernetesApply reconciler

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/controllers/core/tiltfile/api.go
Instead of ignoring any `KubernetesApply` resource owned by
the Tiltfile, only ignore those that have a "managed by" annotation.
This will mean that _implicitly_ created `KubernetesApply` objs
(i.e. those that come from manifests) will continue to not be
reconciled, instead relying on `ForceApply` from the engine.
However, objects explicitly created via `v1alpha1.kubernetes_apply()`
_will_ be reconciled and exclusively managed via API.
=> api: only ignore buildcontrol managed KubernetesApply objs

internal/localexec/execer_test.go
This failed a couple times in CI - I can't reproduce the failure
on my macOS laptop, but I'm guessing it's a timing issue due to
the CI runners being slower.
Changes are two-fold:
* Aggressively cancel context (i.e. trigger SIGKILL to process
group) as soon as PID is seen - this makes it possible to run
this test hundreds of times much quicker, which was useful to
try and reproduce the issue
* Allow grace period for child PID to get terminated - hopefully
this prevents flakiness on CI runners
It's _possible_ the CI flakiness is actually due to the child PID
getting recycled, but that seems very unlikely given the timings
here combined with standard OS behavior for Linux. If these changes
don't eliminate the flakiness, we might just need to reduce the
strictness of this test and not …
=> localexec: improve flaky test

internal/controllers/apis/restarton/restarton.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/tiltfile/reconciler.go
I did not actually add a watch when adding `RestartOn` to the
`KubernetesApply` spec, so it wouldn't actually work.
I realized that the Tiltfile reconciler was also only watching
`FileWatch` and not `UIButton` so thought a helper was probably
warranted to ensure these all stay in sync.
=> api: add helper for registering RestartOn watches

integration/custom_deploy/Tiltfile, integration/custom_deploy/deploy.yaml, integration/custom_deploy_test.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/localexec/execer.go, internal/store/logger.go
Allow deeper integration with custom deploy tools (e.g. Helm) by
invoking a command to perform the apply instead of having Tilt
call the K8s API directly.
The invoked command MUST return YAML for applied entities on
stdout and return an exit code of 0.
=> api: custom apply command support for KubernetesApply

internal/controllers/core/liveupdate/reconciler.go, internal/controllers/core/liveupdate/reconciler_test.go
Please review the following commits I made in branch nicks/liveupdate4:
55db64896b4842bdd4a20b92203c211f5ea7d951 (2021-11-02 13:11:29 -0400)
liveupdate: set waiting status correctly when init containers are starting
=> liveupdate: set waiting status correctly when init containers are starting

internal/controllers/apis/restarton/restarton.go, internal/controllers/apis/restarton/restarton_test.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/controller_test.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/tiltfile/reconciler.go, internal/controllers/fake/fixture.go, internal/controllers/indexer/indexer.go
Replace `ExtractKeysForIndexer` + `RegisterWatches` with a unified
`restarton.SetupController` function, which uses these (now unexported)
functions internally.
This is expected to be called as part of a reconciler's `CreateBuilder()`
method and will add watches for all restart on types as well as set up
the indexer. A func must be passed to pull the `RestartOnSpec` and/or
`StartOnSpec` objects off the reconciler object type.
The `ControllerFixture` now invokes `CreateBuilder` to ensure this logic
gets called during tests, which sometimes rely on the indexer being
properly set up. Note that no automatic reconciliation for dependent
objects will happen in a test scenario still.
The `Cmd` reconciler tests were refactored to use `ControllerFixture`
(they pre-dated its existence), so that …
=> api: simplify/unify RestartOn initialization

web/src/OverviewTableTriggerButton.tsx, web/src/SidebarTriggerButton.test.tsx, web/src/SidebarTriggerButton.tsx
Please review the following commits I made in branch nicks/triggers:
c15081fd12874a1d7cca68308b1939625b57426c (2021-11-01 14:34:34 -0400)
web: enable trigger button when pod rolling out
We want to be able to cancel the rollout and rebuild.
=> web: enable trigger button when pod rolling out

internal/controllers/core/liveupdate/reconciler.go, internal/controllers/core/liveupdate/reconciler_test.go
Please review the following commits I made in branch nicks/liveupdate7:
2953b14cd8a658e1874b3c2ae37a017de359740f (2021-11-02 18:31:53 -0400)
liveupdate: once a container reaches CrashLoopBackOff, stop trying to live-update it
=> liveupdate: once a container reaches CrashLoopBackOff, stop trying to live-update it

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontrol/live_update_build_and_deployer_test.go, internal/engine/buildcontrol/testdata_test.go, internal/engine/buildcontroller_test.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/liveupdate5:
c9a405eb168f156887283ef4864c8c1bd0ad98e5 (2021-11-02 16:15:00 -0400)
engine: update the tests to use the live update reconciler by default
=> engine: update the tests to use the live update reconciler by default

Makefile
Hello @nicks,
54f61e413f07cb53a089392bd299bc1c50aa67dc (2021-11-03 10:39:11 -0400)
makefile: increase linter timeout
=> makefile: increase linter timeout

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/extractors.go, internal/store/liveupdates/reducers.go, internal/store/liveupdates/reducers_test.go
Please review the following commits I made in branch nicks/crashrebuild:
993109b814b593944d4866af4d733fd268ca5e56 (2021-11-03 12:54:34 -0400)
engine: skip container crash check when using the live update reconciler
=> engine: skip container crash check when using the live update reconciler

integration/restart_process_different_user_test.go, integration/same_img_multi_container_test.go, internal/engine/upper_test.go, internal/feature/flags.go
Please review the following commits I made in branch nicks/liveupdate6:
96f88eed2e407420d86b15d3409f9e66a3194c06 (2021-11-02 17:03:22 -0400)
feature: enable live_update_v2 by default on kubernetes
1855a5c7b55844cf91f162a6c7cbf12893f31486 (2021-11-02 16:22:58 -0400)
engine: update the tests to use the live update reconciler by default
=> feature: enable live_update_v2 by default on kubernetes

internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/metrics.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/engine/session/controller_test.go, internal/engine/session/conv.go, internal/k8s/target.go, pkg/model/k8s_target.go
We won't always have this anymore since the "to-be-applied" might
be invoking an external deploy command rather than a YAML blob.
There is some impact to this change (unlike the wholly redundant
removal of port forwards here recently):
1. The `Session` object (used for Tilt CI) will _change_ a target
type from "server" to "job" since it no longer knows up front
until it gets deployed. This is a bit odd; longer-term, maybe
it makes sense to provide explicit user control here and in
the `k8s_yaml()` case to infer it up front to set a value.
2. K8s event + service watches won't be started for a given
namespace until _after_ the first deploy. In practice, this
should not mean missed events, as the watch will return the
existing ones when started.
=> engine: remove "to-be-deployed" ObjectRefs from K8sTarget

internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/k8s/names.go, internal/k8s/target.go, internal/k8s/target_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/store/k8sconv/resource.go, internal/store/k8sconv/resource_test.go, internal/store/runtime_state.go, pkg/model/k8s_target.go
This is now a computed property on `K8sRuntimeState` that uses
the deployed references.
These are included in `UIResource`, but not shown in the web
UI. The TUI does use them, so there's a slight behavior change
here that they won't show up until after applied. (Note that
they are also only used in the case when you've set pod readiness
mode to `ignore`.)
=> engine: remove DisplayNames from K8sTarget

integration/live_update_only/Tiltfile, integration/live_update_only/nginx.yaml, integration/live_update_only/special.txt, integration/live_update_only/web/index.html, integration/live_update_only_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/store/buildcontrols/actions.go, internal/store/buildcontrols/reducers.go, internal/store/engine_state.go, pkg/model/manifest.go
Hello @milas,
Please review the following commits I made in branch nicks/lu-only-fix:
2f74377a9200e1d6e21d3344b76cde58c0973e8c (2021-11-04 19:57:35 -0400)
buildcontrol: now that LiveUpdate fires BuildStarted events, we can't synchronize based on number of BuildStarted events
12fa319d6c0e61b9ca317aa40aa0743e993a5dcb (2021-11-04 17:39:47 -0400)
api: fix Live Update selector inference for LU-only targets
There is no corresponding `ImageMap` for Live Update-only targets,
so it can be skipped.
=> buildcontrol: now that LiveUpdate fires BuildStarted events, we can't synchronize based on number of BuildStarted events

internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/testdata_test.go, internal/engine/buildcontroller_test.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/k8s/target.go, internal/testutils/manifestbuilder/assemble.go, pkg/model/k8s_target.go, pkg/model/target_test.go
This will be used for `custom_deploy`, where the target has a
command instead of YAML.
(In the `k8s_yaml()` case, the file dependencies actually belong
to the Tiltfile because there's additional K8s entity <> resource
mapping logic that requires the "global" Tiltfile state, so it's
not sufficient to only trigger the target.)
=> engine: allow file dependencies for K8sTarget

internal/container/container.go, internal/containerupdate/docker_container_updater.go, internal/controllers/core/liveupdate/reconciler.go, internal/engine/buildcontrol/live_update_build_and_deployer.go, internal/store/liveupdates/containers.go, internal/store/liveupdates/string.go
Please review the following commits I made in branch nicks/lu1:
58c9fa3d8357ea0e65322be71d23b0304a303895 (2021-11-05 11:56:47 -0400)
liveupdate: print pod name and container name instead of container id
container id just isn't that meaningful to people
=> liveupdate: print pod name and container name instead of container id

internal/controllers/core/cmd/controller.go, internal/controllers/core/filewatch/controller.go, internal/controllers/core/filewatch/controller_test.go, internal/controllers/core/filewatch/fsevent/fake_watcher.go, internal/controllers/fake/client.go
It's possible for the monitor to get cancelled while in the midst
of reporting an event, which will cause the API operations to fail.
We don't want to treat these as fatal errors: since the monitor
was cancelled, the failed update was stale anyway and we should
just silently ignore it.
=> api: fix race during FileWatch cancellation

integration/Tiltfile, integration/live_update_only/Tiltfile, internal/feature/flags.go
Hello @milas,
Please review the following commits I made in branch nicks/lu2:
722764e506f3ba7ba4412b36d7294316eb9f2fa7 (2021-11-05 12:38:46 -0400)
features: flip live_update_v2 back off by default
=> features: flip live_update_v2 back off by default

integration/live_update_only_test.go, internal/controllers/core/liveupdate/monitor.go, internal/controllers/core/liveupdate/reconciler.go, internal/controllers/core/liveupdate/reconciler_test.go
Hello @milas,
Please review the following commits I made in branch nicks/lu4:
5e117358113871b9996a9b590ff3f27b3bc667dc (2021-11-05 18:31:04 -0400)
liveupdate: clear stop_path failures on new build/apply
=> liveupdate: clear stop_path failures on new build/apply

integration/Tiltfile, internal/feature/flags.go
Hello @milas,
Please review the following commits I made in branch nicks/v2:
984162e5f15a0710fca60649e66eade14a2ad577 (2021-11-09 10:14:28 -0500)
features: flip live_update_v2 back on by default
=> features: flip live_update_v2 back on by default

integration/k8s_custom_deploy/Tiltfile, integration/k8s_custom_deploy_test.go
Underlying issue was fixed by #5145, so this can + should rely on
Live Update v2 (reconciler/API managed).
=> test: re-enable Live Update v2 for `k8s_custom_deploy` test

web/src/ResourceStatus.ts, web/src/SidebarItem.tsx, web/src/SidebarItemView.test.tsx, web/src/SidebarItemView.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx, web/storybook.tiltfile
This PR displays disabled resources in the Resource Detail View based on the `disable_resources` feature flag.
* Consider a resource disabled when its `disableStatus.disableCount` > 0
* If flag is off, don't display disabled resources or groups with only disabled resources
* If flag is on, display disabled resources in their own list at the bottom of the enabled resource list
* Add tests for `SidebarResources` and `SidebarItemView`
I ran out of time to add Storybook examples, but happy to do that! For now, you can test locally by disabling resources through the Tilt API and enabling the feature flag.
Disabled resources with groups with one disabled resource selected and another disabled resource on hover:
Here's that same list when the feature flag is off (and disabled resources + groups …
=> web: display disabled resources in detail view based on feature flag

internal/controllers/core/filewatch/controller.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go
Add logic to watch the `configmap` specified in a `KubernetesApply`'s `DisableSpec` and update its `DisableStatus`, plus delete any of its managed objects when it's disabled.
Note: there's a `ForceApply` that runs during a `Reconcile` when a `KubernetesApply` isn't disabled. It will overwrite any `DisableStatus` that's been updated earlier in the reconciling, so I added a couple lines to make sure that status gets written properly. If there's a better way to handle this, lmk!
Closes [CH12731](https://app.shortcut.com/windmill/story/12731/rest-of-api-controllers-other-than-cmd-s-deal-with-disablesource-status)
=> controllers: add `DisableSpec` and `DisableStatus` behavior to `KubernetesApply`

internal/controllers/core/filewatch/controller.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go
We're not using this code at all yet, so let's revert until we've figured out what's causing the test failures.
Reverts tilt-dev/tilt#5077
=> Revert "controllers: add `DisableSpec` and `DisableStatus` behavior to `KubernetesApply`"

.circleci/Dockerfile, .circleci/config.yml, Makefile
Please review the following commits I made in branch nicks/helm2:
3bf761ced58406209ab4e35da951292ac6258da7 (2021-11-15 17:45:55 -0500)
test: remove helm2 CI job
Helm2 was end-of-life'd 1 year ago:
https://helm.sh/blog/helm-v2-deprecation-timeline/
That doesn't mean we're removing support for Helm2.
Just that it's not worth maintaining a separate CI job.
=> test: remove helm2 CI job

configs/storybook/templates/ingress.yaml
Hello @nicks,
Please review the following commits I made in branch nicks/ingress2:
fed4c8a8eff6c86f86260bab115652d49dcd953f (2021-11-16 14:37:01 -0500)
storybook: gce loadbalancers really want the pathType to be ImplementationSpecific
https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#creating_an_ingress
=> storybook: gce loadbalancers really want the pathType to be ImplementationSpecific

internal/build/buildkit_printer.go, internal/build/container_test.go, internal/build/docker_builder.go, internal/build/docker_builder_test.go, internal/controllers/core/dockerimage/status.go, internal/controllers/core/tiltfile/api.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_builder.go, internal/testutils/manifestbuilder/manifestbuilder.go
Please review the following commits I made in branch nicks/dockerimage4:
d918439a8b47cf74a7307b7d8389308c997dd1cc (2021-11-16 17:51:36 -0500)
dockerimage: write image build performance to the apiserver
=> dockerimage: write image build performance to the apiserver

internal/controllers/core/filewatch/controller.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go
This PR reverts the (original) reverted PR, since @milas posted a fix for the flaky tests seen in `upper_test.go`. (See #5172 for more details.)
Reverts tilt-dev/tilt#5161
=> (revert the revert) controllers: implement `DisableStatus` for `KubernetesApply`

internal/cli/dump.go
The CLI docs require a new line in their front matter to render properly.
=> cli: update template for cli docs

internal/engine/k8swatch/reducers.go, internal/engine/upper_test.go, internal/store/buildcontrols/reducers.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/pods:
d8ec0b9e63cff9ea01e8cf8a0a9ed1bfa36cf9c1 (2021-11-18 17:37:44 -0500)
store: remove baselinerestarts from the data model
We don't use this anymore for warnings, and it's not modelled in the API.
=> store: remove baselinerestarts from the data model

internal/cli/cli.go, internal/cli/explain.go, internal/cli/explain_test.go, vendor/k8s.io/kubectl/pkg/cmd/explain/explain.go, vendor/k8s.io/kubectl/pkg/explain/OWNERS, vendor/k8s.io/kubectl/pkg/explain/explain.go, vendor/k8s.io/kubectl/pkg/explain/field_lookup.go, vendor/k8s.io/kubectl/pkg/explain/fields_printer.go, vendor/k8s.io/kubectl/pkg/explain/fields_printer_builder.go, vendor/k8s.io/kubectl/pkg/explain/formatter.go, vendor/k8s.io/kubectl/pkg/explain/model_printer.go, vendor/k8s.io/kubectl/pkg/explain/recursive_fields_printer.go, vendor/k8s.io/kubectl/pkg/explain/test-recursive-swagger.json, vendor/k8s.io/kubectl/pkg/explain/test-swagger.json, vendor/k8s.io/kubectl/pkg/explain/typename.go, vendor/modules.txt
Please review the following commits I made in branch nicks/explain:
ca12dd7eade5e27adc48396ce3b0df3b532676bb (2021-11-19 11:19:27 -0500)
cli: add 'tilt explain', a counterpart to 'kubectl explain'
=> cli: add 'tilt explain', a counterpart to 'kubectl explain'

internal/controllers/core/uibutton/hash.go, internal/controllers/core/uibutton/reconciler.go, internal/controllers/core/uibutton/reconciler_test.go, web/src/ApiButton.tsx
Please review the following commits I made in branch nicks/metrics7:
d9c5afc9580f7cc0819d0dc5d23841dc7eb66cd5 (2021-11-18 19:52:56 -0500)
uibutton: add a hash to identify unique buttons
=> uibutton: add a hash to identify unique buttons

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go
* Result of apply now consistently logged for both YAML + Cmd deploys
* This slightly changes things for YAML, which used to show the
objects it was _going_ to apply
* Image injection message only shown when relevant and moved to debug
* More detailed, including the entity and the transformation that
was applied
* Consistent/improved indentation across YAML + Cmd deploys
Fixes #5192.
=> kubernetesapply: improve user-facing logging

internal/container/selector.go, internal/engine/buildcontrol/image_build_and_deployer.go, pkg/model/image_target.go
Hello @milas,
Please review the following commits I made in branch nicks/dockerimagetweak:
6aea91397fc267138b791721920ac37769b5442e (2021-11-22 16:52:59 -0500)
buildcontrol: minor tweaks to docker image reporting
1) include the push phase
2) strip docker.io/library prefix correctly
=> buildcontrol: minor tweaks to docker image reporting

internal/controllers/manager.go
This is mostly annoying in tests when trying to reproduce an issue
and running with something like `-count 100`. With the async nature
of the reconcilers, it's pretty inevitable that some things will
still be in-flight when the tests are done (and so cancel the context
to clean up resources), and a bunch of irrelevant errors that are
really just wrapped "context canceled" get logged out.
=> api: do not log controller-runtime messages after context cancel

.goreleaser.yml
Please review the following commits I made in branch nicks/autocomplete:
e16852e6cd253210284fd15be36315340a4991ab (2021-11-23 13:44:15 -0500)
goreleaser: add autocompletion to our homebrew formula
Adapted from: https://github.com/Homebrew/homebrew-core/pull/88977
Thanks to autocompletion support added in https://github.com/tilt-dev/tilt/pull/5029
=> goreleaser: add autocompletion to our homebrew formula

web/src/ApiButton.stories.tsx, web/src/SidebarResources.tsx
Two tiny fixes I noticed when testing code locally:
Add missing dependency for ApiButton stories and correct data format for memo use in Sidebar
=> web: misc. fixes for `ApiButton` stories and memoizing sidebar items

web/src/ResourceGroupsContext.test.tsx, web/src/ResourceGroupsContext.tsx
Please review the following commits I made in branch nicks/onload:
9622b3f8f7c97327e976b37b216b5ca8ae4ac66e (2021-11-23 16:28:57 -0500)
web: add a load event for expand/collapse
intended to mirror the similar load event for star/unstar
=> web: add a load event for expand/collapse

web/src/ResourceGroupsContext.test.tsx, web/src/ResourceGroupsContext.tsx
Hello @nicks,
665aa44b1d4cb05045ce60f68c0ec52b9dec2b79 (2021-11-24 15:06:19 -0500)
Revert "web: add a load event for expand/collapse (#5219)"
This reverts commit ac711d0ea03bdd4d9a80f2386db20f41012e3994.
=> Revert "web: add a load event for expand/collapse (#5219)"

internal/store/uiresources/reducers.go, internal/store/uiresources/reducers_test.go
I don't love the actual text being logged, but also couldn't come up with a good alternative.
1. `Resource "foo" is disabled` - why did it become enabled? How do I reenable it?
2. `User disabled resource "foo"` - we don't actually know it was changed by user action, vs some operator writing to the API
Went with the former since if the user clicked, hopefully they'll remember, though maybe it'll still be disabled two days later and they'll have forgotten and not be sure how to reenable. Probably not worth worrying about unless someone is confused by it.
=> store: log when a resource becomes enabled or disabled

web/src/HeaderBar.stories.tsx, web/src/OverviewActionBar.stories.tsx, web/src/OverviewActionBar.test.tsx, web/src/OverviewResourceBar.stories.tsx, web/src/OverviewResourcePane.test.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewTable.stories.tsx, web/src/OverviewTable.test.tsx, web/src/SidebarItemView.stories.tsx, web/src/SidebarItemView.test.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarTriggerButton.test.tsx, web/src/SidebarTriggerModeToggle.test.tsx, web/src/analytics_test_helpers.ts, web/src/status.test.tsx, web/src/testdata.tsx
I find myself doing a bunch of manual manipulation of generated resources in tests or copy-pasta'ing another test data function and changing things slightly for what I need. Rather than have multiple `<some-description>Resource()` with slight variability, this PR refactors the `oneResourceNoAlerts()` into a parametrized function that returns a configured resource. 
So something like this:
```js
// multiple generators with similar code
oneResourceNoAlerts() {...}
oneResourceNoAlertsWithLabels() {...}
// or manually manipulating the test resource
const myResource = oneResourceNoAlerts()
myResource.name = "bleep"
myResource.metadata.labels = ["bloop", "beep"]
```
becomes this with this PR:
```js
oneResource({ name: "bleep", labels: 2 })
```
I expect that tests will still need to manipulate …
=> web: refactor single test resource generation into a single, configurable function call

internal/cloud/io_test.go, internal/engine/uiresource/subscriber.go, internal/engine/uiresource/subscriber_test.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go
Hello @milas,
Please review the following commits I made in branch nicks/readycond:
06ab713339c5693cad5e15d088cfb62ebf6e36e2 (2021-11-30 12:56:03 -0500)
engine: add a ready condition to all uiresources
=> engine: add a ready condition to all uiresources

internal/cli/wait.go, internal/cli/wait_test.go
Hello @milas,
Please review the following commits I made in branch nicks/wait:
3393803952243553ffcd4544c0350ea38bf2978b (2021-11-30 16:04:29 -0500)
cli: add 'tilt wait' to wait on resources to become ready
=> cli: add 'tilt wait' to wait on resources to become ready

web/src/ApiButton.tsx, web/src/CustomNav.tsx, web/src/SidebarItem.tsx, web/src/testdata.tsx, web/src/types.ts
To prep for the disable resources launch:
* Add `toggleValue` property to toggle button analytics to indicate what the value for toggle is when the user clicks on it
* Add toggle button analytics tags to the confirm/cancel buttons
* Reorganize and add more types and constants for `ApiButton`
The `toggleValue` property will help us know if a user is clicking `disable` or `enable` on a resource. I could see this value being potentially confusing because it doesn't represent the value that will result from the user interaction. But because a user could confirm or cancel their toggle, I think it's fine to record the value "pre" toggle. 
Here's what a disable resource button click looks like:
```json
{
"action": "click",
"buttonType": "DisableToggle",
"component": "Resource",
"specHash": …
```
=> web: add additional analytics to toggle `ApiButton` interactions

Makefile, Tiltfile
Adds a local resource to run tests in recently changed go packages. Uses a new makefile target to run `go test` with the most recent set of changes reported by Tilt.
- Makefile: add 'testchanges' which checks Tilt for changed pkgs
- Tiltfile: remove unused code
- Tiltfile: add go_test_changed resource
=> Add go_test_changes resource to Tiltfile

internal/hud/server/apiserver.go, internal/k8s/portforward.go
After trying multiple ways of looking up and caching the provided value for `--host`/`providedWebHost`, this turned out to be the simplest option to just look up the host before creating the portforward, so it will handle both the defaulted web host and specified hosts. It has the added benefit of creating portforwards on IPV6 addresses if any are resolved for the given host.
- Fixes #5043.
- Also fixes port-forwarding when passing an IPv6 literal like `tilt up --host='[::1]'`
- Only sets up port-forwards on addresses that can be listened, and returns an error if none of the resolved addresses can.
- Clarify error message between port collision and other errors
```
$ tilt up --port 10350
Tilt started on http://localhost:10350/
v0.23.1-dev, built 2021-12-02
Error: Tilt cannot start because …
```
=> fix: lookup hosts before passing to NewOnAddresses

internal/tiltfile/k8s_custom_deploy.go, internal/tiltfile/k8s_custom_deploy_test.go, internal/tiltfile/live_update_test.go, pkg/model/image_target.go, pkg/model/manifest.go
In some instances, when using a custom deploy tool, you have no
underlying knowledge of the image name it'll produce, but there
is a predictable container name it'll use for the deployment, so
a `container_selector` argument allows providing the name of a
container in lieu of the image, which will be used to determine
which containers are targeted for Live Update operations.
=> k8s_custom_deploy: add container name selector support

go.mod, go.sum, internal/cli/args.go, internal/cli/args_test.go, vendor/github.com/kballard/go-shellquote/LICENSE, vendor/github.com/kballard/go-shellquote/README, vendor/github.com/kballard/go-shellquote/doc.go, vendor/github.com/kballard/go-shellquote/quote.go, vendor/github.com/kballard/go-shellquote/unquote.go, vendor/modules.txt
Previously:
* `tilt args` w/ no args would just generate an error telling the user to use `--clear` if they wanted to clear the args
* `tilt args` operated via a gorilla-routed api
Now:
* `tilt args` w/ no args opens the current args in $EDITOR and applies the result to the Tiltfile (using a chunk of the code that powers `kubectl edit`)
* `tilt args` operates via the Tilt API server
Notes:
* I haven't implemented the "on error, re-open the file and iterate" behavior that `kubectl edit` has - that seemed like more of a nice-to-have and better as a separate PR.
* Suggestions on wording (the initial comment/instructions placed in the editor, error messages, help) welcome!
=> cli: `tilt args` allows editing args in $EDITOR

internal/dockercompose/client.go, internal/dockercompose/client_test.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go
Fixes #4890.
Based on [this comment](https://github.com/tilt-dev/tilt/issues/4993#issuecomment-981637127) on #4993 as well as commentary at the end of docker/compose#8554, version 2.2 or greater appears to be stable.
=> dockercompose: greenlight dc version 2.2 or later

internal/cli/cli.go
Please review the following commits I made in branch nicks/wait2:
c8e2d9cda11278e0bb43df9a98d6e09d0b644819 (2021-12-06 13:24:12 -0500)
cli: finish wiring up the wait cmd :oops:
=> cli: finish wiring up the wait cmd :oops:

internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/allowparallel:
af2afc1678b44f376cc0fa4108987edf6b3ab26a (2021-12-06 18:07:44 -0500)
tiltfile: by default, local servers can start in parallel
=> tiltfile: by default, local servers can start in parallel

web/src/instrumentedComponents.test.tsx, web/src/instrumentedComponents.tsx
[Originally noted here](https://github.com/tilt-dev/tilt/pull/5212#pullrequestreview-813993395). The analytics events for typing into an `ApiButton`'s text input field are delayed, but they fire multiple times. There's not an event for every keystroke, but it's way more than what I'd expect with a five second debounce delay.
This PR removes `useMemo`'s dependencies to make sure debounce analytics calls fires only once. (The dependencies aren't really needed, since the debounce function has access to the current values for `analyticsName` and `analyticsTags`.)
=> web: fix multiple analytics calls on instrumented text field input

web/src/OverviewTable.tsx, web/src/OverviewTableTriggerButton.tsx, web/src/SidebarItemView.stories.tsx, web/src/SidebarItemView.tsx, web/src/SidebarResources.tsx, web/src/SidebarTriggerButton.test.tsx, web/src/SidebarTriggerButton.tsx, web/src/SidebarTriggerModeToggle.test.tsx, web/src/trigger.tsx
Please review the following commits I made in branch nicks/ch13060:
e85f34f14be06994b6a9b557e7d25df00575d1d1 (2021-12-08 09:24:09 -0500)
web: better unify all the trigger buttons
fixes https://github.com/tilt-dev/tilt/issues/5252
=> web: better unify all the trigger buttons

internal/cli/wire_gen.go, internal/controllers/core/cluster/reconciler.go, internal/k8s/client.go
This is a mechanical removal of an outdated / unused arg I noticed while working in this file earlier.
=> k8s: remove unused ctx constructor arg

internal/cli/wire_gen.go, internal/container/selector.go, internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/api_test.go, internal/controllers/core/tiltfile/reconciler.go, internal/controllers/core/tiltfile/reconciler_test.go, internal/controllers/fake/fake.go, internal/engine/upper_test.go, internal/testutils/manifestbuilder/assemble.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/cluster2:
5e4625c0cb9263a802b37bb08541fd522e8e00b6 (2021-12-10 14:02:44 -0500)
tiltfile: infer the registry during reconciliation rather than during tiltfile loading
We want to support a world where
- k8s connections can be reloaded
- there are multiple k8s connections
- we can change image parameters based on arch
and the reconciler (rather than the tiltfile loader) is in a better position to
do all of that.
=> tiltfile: infer the registry during reconciliation rather than during tiltfile loading

internal/dockercompose/client.go, internal/dockercompose/fake_client.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, pkg/model/dockercompose.go
Fixes #4999.
Supports any combination of compose file paths and blobs, with the following path resolution:
1. The compose project directory will be set to the parent directory of the first file, if any.
2. Otherwise, the compose project directory will be set to the parent directory of the executing Tiltfile.
Caveats that still exist:
- Multiple `docker_compose` files, blobs, and declarations with any combination of files and blobs are merged into a single compose project with the directory inferred as above.
=> dockercompose: get `docker_compose(Blob)` wired up

internal/tiltfile/tiltextension/github_fetcher.go
extension git fetch errors were writing directly to [os.Stderr](https://github.com/tilt-dev/tilt/blob/2d0ddc5cb13e7779fde1b8bdb6b56b423b499aa4/vendor/github.com/tilt-dev/go-get/get.go#L56), leaving the log looking pretty useless:
```
Loading Tiltfile at: /Users/matt/tmp/tilt_tests/Tiltfile
Traceback (most recent call last):
/Users/matt/tmp/tilt_tests/Tiltfile:2:8: in <toplevel>
<builtin>: in include
Error: Fetching tilt-extensions: exit status 1
```
This fix takes the same approach we use in [the reconciler](https://github.com/tilt-dev/tilt/blob/a959e0ac25da2c55a7fa78b77042c77e237f6548/internal/controllers/core/extensionrepo/reconciler.go#L158).
The unit testing approaches I could think of for this seemed ugly enough to not be worth it, but I could be convinced.
=> extensions: write fetch errors to log

internal/build/docker_builder.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/k8s/client.go, internal/k8s/watch.go
Please review the following commits I made in branch nicks/platform:
3fd9959370431a01e1502741d4fa82e769e945d1 (2021-12-14 15:04:19 -0500)
engine: infer image architecture off the cluster
Fixes https://github.com/tilt-dev/tilt/issues/4274
=> engine: infer image architecture off the cluster

internal/build/tar.go, internal/build/tar_test.go, internal/controllers/core/liveupdate/reconciler.go
Please review the following commits I made in branch nicks/shortread:
54cb443ec1b190fc43f48ea8bfd00a2248a3c188 (2021-12-14 16:27:51 -0500)
build: fix a race condition in constructing tarballs
i was able to reproduce this with a tilt environment
with a local resource that rapidly writes to a file
and a live-update rule that syncs it.
=> build: fix a race condition in constructing tarballs

internal/controllers/apis/imagemap/imagemap.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go
Hello @milas,
Please review the following commits I made in branch nicks/kapp-imagemap:
b59556a1259ca7f6f29515ef5453de44b2a52af4 (2021-12-16 15:47:45 -0500)
kubernetesapply: add images to custom commands
=> kubernetesapply: add images to custom commands

internal/build/buildkit_printer_test.go, internal/build/tar.go, internal/cloud/io.go, internal/containerupdate/fake_container_updater.go, internal/controllers/core/liveupdate/reconciler.go, internal/engine/upper_test.go, internal/watch/notify_test.go
I've been running the test suite (`./internal/engine` in particular)
with `-count X` a lot recently to catch timing-related test failures.
After running enough times, the tests start failing due to too many
open files, so I did an audit and found a few places where files or
readers weren't always being closed.
=> build: ensure file handles properly closed

Makefile
Hello @nicks,
49105c50ceccfbcc88861b6c7a264c862bcff182 (2021-12-17 13:17:05 -0500)
test: increase the timeout on integration tests
=> test: increase the timeout on integration tests

internal/engine/session/conv.go, internal/hud/webview/convert.go, internal/store/engine_state.go, internal/store/manifest_target.go, internal/store/manifest_target_test.go, internal/store/runtime_state.go, pkg/apis/core/v1alpha1/runtimestatus_types.go, web/src/status.tsx, web/src/types.ts
Please review the following commits I made in branch nicks/ch13122:
d2dd450538d39edd6502db43a141e6730b6fe1c8 (2021-12-17 12:24:22 -0500)
store: add a new RuntimeStatusNone for the case where a build hasn't been triggered yet
We try to borrow the general pattern from UpdateStatus()
=> store: add a new RuntimeStatusNone for the case where a build hasn't been triggered yet

.github/dependabot.yml
Hello @nicks,
Please review the following commits I made in branch nicks/dependabot:
cd8a42aa7ae18e47beeec86c3d4270d83e5ec4e5 (2021-12-17 14:13:35 -0500)
test: only surface production dependencies, not dev dependencies
I have no idea why this isn't the default, here are some threads on the issues:
https://github.com/dependabot/dependabot-core/issues/4146
https://github.com/dependabot/dependabot-core/issues/2521
https://github.com/facebook/create-react-app/issues/11174
=> test: only surface production dependencies, not dev dependencies

go.mod, go.sum, internal/controllers/core/cmd/controller.go, internal/controllers/core/filewatch/controller.go, internal/controllers/core/filewatch/watcher.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/fake/client.go, vendor/github.com/kballard/go-shellquote/README, vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/fs.go, vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/jsonfile_rest.go, vendor/github.com/tilt-dev/tilt-apiserver/pkg/storage/filepath/version.go, vendor/modules.txt
Most of the heavy-lifting is from the `tilt-apiserver` update here,
which fixes three important issues:
* Fix race condition at storage-level that would result in two
conflicting updates both being accepted
* Fix optimistic concurrency check for subresources (i.e. status)
* Fix `PATCH` semantics so it can't fail due to resource versioning
On the actual Tilt side, the only change currently is to start using
`PATCH` for status updates in the `KuberenetesApply` reconciler,
which has multiple concurrent writers between the standard
reconcilation process and the `ForceApply` calls from the
`BuildAndDeployer`. The latter doesn't support elegant retry, so
any optimistic concurrency failures result in a failed build. By
using `PATCH`, we prevent these failures, which prevents a host of
race …
=> api: concurrent update fixes

.gitattributes, internal/cli/wire.go, internal/cli/wire_gen.go, internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/core/kubernetesdiscovery/reconciler_test.go, internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/owner_fetcher.go, internal/k8s/owner_fetcher_test.go
Historically, we've injected (via wire) a single Kubernetes client,
so we also injected a single `OwnerFetcher` (which uses the K8s
client).
Now that we're moving to multiple Kubernetes cluster connections
being supported, that means there can be multiple `OwnerFetcher`
instances, BUT we only want 1x `OwnerFetcher` per cluster connection.
(There is a lot of internal caching and clever logic to avoid duplicate
lookups!)
To avoid adding extra book-keeping/logic for consumers to look these
up in addition to the actual Kubernetes client, this moves the
`OwnerFetcher` to be managed by the client, which will ensure there's
a 1:1:1 mapping between cluster connection, Kubernetes cilent, and
`OwnerFetcher`.
=> k8s: make OwnerFetcher part of the K8sClient

internal/cli/wire_gen.go, internal/controllers/core/cluster/cache_fake.go, internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/engine/upper_test.go
Do not use an injected client but do a lookup from the
`cluster.ClientCache`.
Most of the changes here are to carry the cluster info
along with the namespace/UID so that it's safe to use
across multiple clusters without collisions.
=> engine: use K8s clients from Cluster cache

internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/controllers/core/tiltfile/filewatch_test.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/testdata_test.go, internal/engine/testdata_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/apis/core/v1alpha1/cmdimage_types.go, pkg/model/custom_build_test.go, pkg/model/image_target.go
Hello @milas,
Please review the following commits I made in branch nicks/cmdimage2:
486ffd37a97d257ad83fc79dc74affa87c94e582 (2021-12-20 19:20:30 -0500)
build: use new CmdImageSpec
=> build: use new CmdImageSpec

web/src/ApiButton.tsx, web/src/OverviewButton.tsx
Currently, the component that's responsible for rendering the confirmation and cancel buttons for an `ApiToggleButton` returns a different `ButtonGroup` wrapper (and HTML buttons) when it enters the "confirmation" state.
Here's part of my [original note](https://github.com/tilt-dev/tilt/pull/5218#discussion_r756319246):
> the disadvantage of returning a different dom node for the confirmation state is that in privileges mouse users. if i'm interacting with the disable button using a keyboard, then that button disappears and i'm no longer focused on it. to confirm or dismiss, i have to navigate back in the tab order. if i'm using an assistive device, there's no immediate (non-visual) indication that i need to confirm the action i just tried to perform.
This PR refactors how the main …
=> web: improve accessibility and keyboard nav on `ApiButton`s that require confirmation

web/src/ApiButton.test.tsx, web/src/ApiButton.testhelpers.tsx, web/src/ApiButton.tsx
This PR fixes a bug in which the `confirming` state of an `ApiToggleButton` persisted across rendering different disable resources buttons. If you clicked "disable resource" on one resource (without confirming or cancelling), then navigated to another resource, that confirmation state would not reset.
The easiest solution I found is to track the button name in the component's formal state and then calculate the actual `confirming` state in the render based on whether or not the current button name matches the tracked state button name.
At first, this was a little bit goofy for me to conceptualize with React. Because, if the props change (i.e., the button name changes), then we want to reset the confirmation state of the component. However, we can't make any `setState` calls within the …
=> web: reset the confirmation state of `ApiToggleButton`s when navigating between resources

internal/feature/flags.go, web/src/feature.ts
Add a feature flag to develop bulk disabling of resources without interfering with beta testing
(We can remove the `bulk_disable_resources` flag and switch any frontend code to the general `disable_resources` flag when this is ready to be user-facing.)
Closes [ch12972](https://app.shortcut.com/windmill/story/12972/optional-add-bulk-disable-resources-feature-flag).
=> features: add flag for bulk disabling resources in Table View

internal/controllers/core/cmdimage/status.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go
Hello @milas,
Please review the following commits I made in branch nicks/cmdimageapi2:
6f85122f225866a7663d1fc077058f37377760a2 (2021-12-21 15:27:37 -0500)
buildcontrol: publish CmdImageStatus
=> buildcontrol: publish CmdImageStatus

internal/build/container_test.go, internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/build/docker_builder.go, internal/build/inject.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/docker_compose_build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_builder.go
Please review the following commits I made in branch nicks/imagemap7:
bd576bab9a0a18275c37f5e001a332f58e560759 (2021-12-23 16:16:24 -0500)
build: refactor so that the builders read image dependencies from the API
There should be no functional changes in this PR.
This is preparation for custom_build to handle image dependencies
the same way DockerImage handles image dependencies.
=> build: refactor so that the builders read image dependencies from the API

internal/build/custom_builder.go, internal/build/custom_builder_test.go, internal/controllers/apis/imagemap/imagemap.go, internal/testutils/tempdir/temp_dir_fixture.go, internal/tiltfile/custom_build_test.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/imagemap8:
25c40350a13f53383996c00fc25b1216631faa95 (2022-01-03 11:45:49 -0500)
tiltfile: add custom_build(image_deps)
Fixes https://github.com/tilt-dev/tilt/issues/2856
51b9477de4b39be44f9ec0e31b43ea17d5a1c22f (2022-01-03 10:24:44 -0500)
build: refactor so that the builders read image dependencies from the API
There should be no functional changes in this PR.
This is preparation for custom_build to handle image dependencies
the same way DockerImage handles image dependencies.
* Code is suitably instrumented with logging and …
=> tiltfile: add custom_build(image_deps)

internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go, internal/timecmp/assert.go
See #5340 for API change. The data here was already tracked
internally, so this just applies it to the `Cluster` status object.
There's some tweaks to the test assertion helper for API time types
so that it can handle `nil` types, as used in the `Cluster` status
`ConnectedAt` field.
=> api: report ConnectedAt on Cluster status

internal/timecmp/assert.go, internal/timecmp/cmp.go, internal/timecmp/cmp_test.go
We've been using more pointer types for time fields in the API
recently, which makes doing comparisons with them a nuisance.
The time comparison helpers now normalize any `nil` time value
to the zero time internally. This should still result in sane
behavior across the comparison operations.
=> api: support nil for time comparisons

internal/controllers/core/podlogstream/podlogstreamcontroller_test.go, internal/controllers/core/podlogstream/podsource.go, internal/k8s/fake_client.go, internal/k8s/watch.go
Please review the following commits I made in branch nicks/issue5330:
bfdb3b09c932001bfeab0f3b2ca95bfa15a5968d (2022-01-04 16:12:31 -0500)
controllers: fix a spurious pod log streaming error. Fixes https://github.com/tilt-dev/tilt/issues/5330
=> controllers: fix a spurious pod log streaming error

internal/controllers/apis/configmap/disable.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/controller_test.go
Please review the following commits I made in branch nicks/cmd:
4411d4315bd14ed1ffa7e1ac9801be30ae4330e6 (2022-01-03 16:02:28 -0500)
controllers: make the Cmd controller level-triggered rather than edge triggered
Before this PR, the controller would listen for process
changes and update the apiserver on each change.
After this PR, the controller does all bookkeeping about the state of the
process in local memory, then updates the apiserver only during reconciliation.
This should be way more robust and eliminate a lot of race conditions.
* Code is suitably instrumented with logging …
=> controllers: make the Cmd controller level-triggered rather than edge triggered

internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/store/clusters/actions.go, internal/store/summary.go
For event + service watchers, which still live in engine as store
subscribers, use the `ClientManager` from #5341 to reset state on
`Cluster` changes and re-create any watches using the new client.
(I split this out from #5341 to make each PR smaller but am posting it
in parallel to make it clear how the `ClientManager` will get used.)
=> k8swatch: reset state on Cluster change

internal/controllers/apis/cluster/client.go, internal/controllers/apis/cluster/client_fake.go, internal/controllers/apis/cluster/client_test.go, internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/service_watch.go, internal/engine/k8swatch/watcher.go, internal/engine/upper_test.go, pkg/apis/identifiers.go
There's numerous competing concerns with managing K8s clients/their
operations, and a big one is that for efficiency, we only ever want
to set up a namespace-level watch for a specific cluster once and
then triage the incoming data.
In particular, this worked well with the engine subscribers, as
they'd always evaluate global state.
However, for reconcilers, this is trickier, as we operate on
individual objects. Behind the scenes, the reconciler tracks the
consumers for a given watch, so that it can de-duplicate and perform
refcounting to know when it's safe to cancel.
This complicates client refreshes, as if the underlying K8s client
for the `Cluster` object gets changed, we need to reset state for
each referencing object individually when its reconcile happens.
The changes here actually …
=> api: make ClientManager resource aware

internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Fixes #5326
Old:
```
Loading Tiltfile at: /Users/matt/go/src/github.com/tilt-dev/tilt/integration/crd/Tiltfile
Matching (json_path="{.spec.image}"): image is not found
```
New:
```
Loading Tiltfile at: /Users/matt/go/src/github.com/tilt-dev/tilt/integration/crd/Tiltfile
Finding image in UselessMachine/bobo2: Matching (json_path="{.spec.image}"): image is not found
```
=> tiltfile: include name of crd when image_json_path doesn't match

internal/controllers/core/kubernetesdiscovery/container_restart.go, internal/controllers/core/kubernetesdiscovery/portforwards_test.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/core/kubernetesdiscovery/reconciler_test.go, internal/store/logger.go
Hello @milas,
Please review the following commits I made in branch nicks/kd:
9ee45731be35c98ded9d5ab05336a3061e0c5c5a (2022-01-06 17:28:07 -0500)
kubernetesdiscovery: make controller level-triggered rather than edge-triggered
also removes all tilt-crashing ErrorActions
=> kubernetesdiscovery: make controller level-triggered rather than edge-triggered

scripts/release-update-homebrew-core.sh, scripts/release.Dockerfile
Hello @nicksieger,
Please review the following commits I made in branch nicks/release2:
7b1772341719a7516bb3b88583630f694484f495 (2022-01-07 18:27:49 -0500)
scripts: add no-browse to release scripts
=> scripts: add no-browse to release scripts

internal/controllers/core/tiltfile/metrics.go, internal/controllers/core/tiltfile/reconciler.go, internal/controllers/core/tiltfile/reconciler_test.go, internal/docker/fake_client.go
After loading a Tiltfile, report the status of the Docker connection
if the Tiltfile iif it has Docker resources.
Currently, the Docker client is constructed very early in Tilt start
via DI (wire), and if an error is encountered, an exploding client is
used that will error out on any operation. It's not possible to
re-initialize the client at runtime (you need to restart Tilt), so the
status can never change. As a result, a `sync.Once` guards the metric
reporting so that it doesn't happen on every Tiltfile load.
Supersedes #5363.
=> api: report Docker connect events on Tiltfile load

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/controllers/fake/fixture.go, internal/controllers/fake/store.go
Hello @milas,
Please review the following commits I made in branch nicks/applyprint:
9202477695998e55a157ddcfd9b43c4f6605a6ab (2022-01-12 16:01:38 -0500)
kubernetesapply: print applied objects on failure
also build LogAction handling into the fixture
=> kubernetesapply: print applied objects on failure

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go
Hello @milas,
Please review the following commits I made in branch nicks/kappdelete:
208af94148bbe6e90d2d7011c17522eced83c7da (2022-01-12 18:50:52 -0500)
buildcontrol: force refresh should apply the DeleteCmd in k8s_custom_deploy
9202477695998e55a157ddcfd9b43c4f6605a6ab (2022-01-12 16:01:38 -0500)
kubernetesapply: print applied objects on failure
also build LogAction handling into the fixture
=> buildcontrol: force refresh should apply the DeleteCmd in k8s_custom_deploy

web/src/HUD.tsx, web/src/OverviewTable.stories.tsx, web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/OverviewTablePane.stories.tsx, web/src/ResourceSelectionContext.test.tsx, web/src/ResourceSelectionContext.tsx, web/src/analytics.ts, web/src/instrumentedComponents.tsx, web/src/testdata.tsx, web/storybook.tiltfile
* Add a `ResourceSelection` context that tracks what resources are selected by a list of their names
* Add a checkbox column that displays when the bulk feature flag is enabled and only for resources that are disable-able
* Add support for bulk disable resources feature in Storybook stories
(This PR doesn't cover resource group selection or enable/disable menu display yet.)
The easiest way to test is through Storybook (through looking at any of the `OverviewTable` stories and toggling the flag) or spinning up any `Tiltfile` with the `bulk_disable_resources` flag enabled.
Closes [ch12973](https://app.shortcut.com/windmill/story/12973/add-checkbox-selection-to-each-row-in-table-view).
=> web: add checkbox column on Table View behind feature flag

Tiltfile.starter
I might have gone a bit overboard here so making this a PR to Lian's branch instead of pushing straight to #5366  😅 
* Improved formatting on "hello world" so it's more noticeable
* Provide path to generated Tiltfile in logs
* Move `local_resource` example below Docker/K8s
* Ensure file is (99%) 72-col friendly
* Make examples IDE friendly to uncomment
* `Cmd-/` to uncomment a block in both JetBrains IDEs/VSCode will produce valid Starlark now
* Fix issue with extension load (can't be in function)
* Add some more reference links
* Add `auto_init` + `trigger_mode` to `k8s_resource` example
* Tweak language/explanations
=> cli: starter Tiltfile formatting + language adjustments

internal/controllers/core/tiltfile/reducers.go, internal/tiltfile/docker_compose.go, internal/tiltfile/k8s.go, internal/tiltfile/k8s_custom_deploy_test.go, internal/tiltfile/local_resource.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Hello @nicksieger, @landism,
Please review the following commits I made in branch nicks/dupe-resource:
1098d9395efb9c97985043a43c4c038552aaf8d4 (2022-01-18 20:14:09 -0500)
tiltfile: duplicate resources should consistently be an error
=> tiltfile: duplicate resources should consistently be an error

integration/docker_prune/Tiltfile, integration/docker_prune/pod.yaml, integration/docker_prune_test.go, internal/cli/docker_prune.go, internal/cli/wire_gen.go, internal/controllers/core/tiltfile/reconciler.go, internal/engine/dockerprune/docker_pruner.go
Re-use the logic from the reconciler directly to determine the
registry (based on the cluster + `default_registry` in Tiltfile)
in the CLI code.
This addresses a crash resulting from the image properties not being
present, as they're inferred + populated during Tiltfile
reconciliation, which does not occur here.
In the future, we'll likely want this (and other similar commands
such as `tilt alpha tiltfile-result`) to launch a headless apiserver
and wait for a condition, i.e. Tiltfile loaded, before reading the
objects from the apiserver to do work.
Fixes #5370.
=> cli: fix `tilt docker-prune` command panic

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go
Hello @milas,
Please review the following commits I made in branch nicks/issue5382:
4aed451754a4c80c7f1f799bff4cec7edc4c5fb9 (2022-01-19 12:31:34 -0500)
buildcontrol: adjust how we determine image rebuilds
Fixes https://github.com/tilt-dev/tilt/issues/5382
=> buildcontrol: adjust how we determine image rebuilds

internal/feature/flags.go, internal/tiltfile/tiltfile_test.go
Under the hood, `disable_snapshots()` is just a convenience wrapper
for `disable_feature("snapshots")`. As a result, when the FF was
moved to `Obsolete`, it started producing a warning and the FF value
couldn't be set.
We can't suppress the error/warning, as when the obsolete error is
returned, no value is stored, so the FF is flipped back to `Active`.
Arguably, this is a "misuse" of feature flags, but it's not worth the
headache to refactor it away to do something different right now, yet
there are a non-negligible number of repos using `disable_snapshots()`,
so leaving it as-is doesn't seem viable either.
There's an existing test, `TestDisableSnapshots`, which should have
caught this, but the `tiltfile` fixture was using a hardcoded set of
feature flags different than at runtime; these …
=> tiltfile: fix disable_snapshots()

scripts/local-analytics.sh, scripts/release-metrics.sh
Had these in my local repo and thought they might be useful to save:
- `./scripts/local-analytics.sh` to run a local analytics server
- `./scripts/release-metrics.sh` to generate csv of download counts from Github
=> scripts: add a couple script utilities

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go
Hello @milas,
Please review the following commits I made in branch nicks/issue5400:
7428c380a34b341c846bb67c2d220529a919b50e (2022-01-21 18:59:19 -0500)
Revert "buildcontrol: adjust how we determine image rebuilds (#5393)"
This reverts commit 86116938738c516194e3dbf6dbb0e1b1745a2041.
fixes https://github.com/tilt-dev/tilt/issues/5400
=> Revert "buildcontrol: adjust how we determine image rebuilds (#5393)"

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go
Hello @milas,
Please review the following commits I made in branch nicks/buildcontrol:
056b8a4637cc5d5154d233afbf931893a41d56c2 (2022-01-24 16:19:06 -0500)
buildcontrol: correctly handle live update image graphs
fixes https://github.com/tilt-dev/tilt/issues/5382
c1ec0acf7efea120d85dbefe197f1ecef587012f (2022-01-24 10:45:43 -0500)
Revert "Revert "buildcontrol: adjust how we determine image rebuilds (#5393)" (#5401)"
This reverts commit 089f6e0a95392f1143656c8d4c59c3ba1996d806.
=> buildcontrol: correctly handle live update image graphs

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller.go, internal/engine/dcwatch/disable_watcher.go, internal/store/engine_state.go, internal/store/manifest_target.go, internal/store/tiltfiles/reducers.go, internal/store/uiresources/reducers.go
A few places in the engine (the ones changed in this PR) need to know if a Manifest is enabled and were doing this by checking UIResource.DisableStatus.
As part of the tilt args / enable/disable work, I'm changing things so that all manifests are considered disabled when created and then become enabled when the api objects shake out. For the engine bits in this PR, that'd mean tests need to ensure enabled resources have both a UIResource and a ConfigMap.
It also felt kind of weird that, e.g., BuildController was coupled to UIResource.
This almost certainly isn't how we want to do this long term, but it seems like a better interim solution than what's already there and will make some upcoming changes less invasive.
=> engine: store manifest enabled state in ManifestState

internal/engine/upper_test.go
This test creates two manifests and then asserts their builds happen in the order they were defined, but with parallel builds, they occasionally happen in the other order.
=> engine: fix flaky test: TestMultipleChangesOnlyDeployOneManifest

web/src/ApiButton.test.tsx, web/src/ApiButton.testhelpers.tsx, web/src/ApiButton.tsx, web/src/BulkApiButton.test.tsx, web/src/BulkApiButton.tsx, web/src/CustomNav.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewTable.tsx, web/src/OverviewTableBulkActions.test.tsx, web/src/OverviewTableBulkActions.tsx, web/src/OverviewTableColumns.tsx, web/src/style-helpers.ts, web/src/testdata.tsx
This PR adds a new `BulkApiButton` component and an `OverviewBulkActions` component, so users can enable and disable multiple resources at a time from Table View.
Because the data model and styling are pretty different for bulk buttons, I opted to fork the `ApiButton` code and customize  it based on what functionality is needed for bulk actions now. In the future, I could see the `BulkApiButton` supporting other `UIButton` properties, like inputs and custom icons, or even supporting non-`UIButton` tasks, like starring resources or triggering updates.
The **`BulkApiButton`** renders a configurable html button that, when clicked, updates a list of `UIButton`s in the Tilt API. The bulk button can be configured to require confirmation, as well as only update `UIButton`s that can be toggled to …
=> web: add bulk action buttons for disabling resources in Table View

internal/tiltfile/tiltextension/github_fetcher.go, internal/tiltfile/tiltfile_state.go
Since the tiltfile state's scratchDir is deleted when Tilt exits, this should eliminate most tilt-extension directory leakage issus in #5291.
=> tiltfile: fetch extensions inside tiltfile state scratch dir

web/src/HeaderBar.tsx, web/src/OverviewResourceBar.tsx, web/src/OverviewTable.tsx, web/src/ResourceStatusSummary.test.tsx, web/src/ResourceStatusSummary.tsx, web/src/SidebarResources.tsx
This PR adds a count of disabled resources to the resource status summary component. The total resource count doesn't include the disabled resources, and the status summary will display if the (enabled) resource count or the disabled count is > 0.
I also added more semantic html (like replacing `div`s with `li`s) and aria markup, so it's more accessible to assistive tech. (There are more improvements we can make in the future to make sure the visual information is also accessible over text and audio, but I didn't want the scope of this PR to creep.)
[Closes ch12978](https://app.shortcut.com/windmill/story/12978/display-disabled-resource-count-in-status-summary).
=> web: add disabled resource status count to summary 

internal/cli/demo.go
This should always use the _local_ Docker client rather than the
cluster client because we're creating our own ephemeral cluster
and doing that e.g. inside of minikube's Docker is unlikely to
be what anyone wants beyond resulting in the UI getting perpetually
stuck at "Waiting for cluster" because it's launched an inaccessible
ephemeral cluster with comical levels of nested virtualization/
containerization.
=> demo: fix perpetual "Waiting for cluster" in some setups

.golangci.yml, internal/build/buildkit_printer.go, internal/cli/docker.go, internal/controllers/core/cmd/probe_test.go, internal/controllers/core/kubernetesdiscovery/portforwards.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/core/liveupdate/reconciler_test.go, internal/controllers/core/podlogstream/podlogstreamcontroller.go, internal/engine/upper_test.go, internal/git/remote.go, internal/hud/webview/convert_test.go, internal/k8s/entity_test.go, internal/tiltfile/files.go, internal/tiltfile/helm.go, internal/tiltfile/os/environ.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/value.go
This PR includes the following:
* Fixed misspelling in comment
* Organized the linters used
* Added the following linters
- gosimple
- staticcheck
- unconvert
- unused
- varcheck
* Code updates to compile (mostly unnecessary casting)
* Ignoring errcheck for tests
The staticcheck had an entry in `exclude-rules` however was never enabled as a linter.  
I would recommended turning up errcheck but results in much work to-do.  Worth ignoring on tests but not in base code IMO.    There is a lot to-do around cyclomatic complexity.  The numbers are high with the greatest concern around untested code.  Some of this seems pulled from other projects or inspired by other projects.  It is worth adding there is a high number of unused params as well.
Happy to trim this PR down... or add more if …
=> Add Additional Linters

internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
Enable kustomize executable path to be kustomized. Fixes #5412.
=> Kustomize: specify custom executable path

internal/tiltfile/config/config.go, internal/tiltfile/config/config_test.go, internal/tiltfile/config/resources.go
Add a way to specify that all resources should be disabled, giving a "resource catalog" experience.
`config.set_enabled_resources([])` currently acts as `tilt up` with `argv == []`, i.e., it enables all resources. We probably don't want to change this since it'll break basic use cases like the first [tiltfile config example](https://docs.tilt.dev/tiltfile_config.html#run-only-some-services-reimplement-default-tilt-behavior).
`config.set_enabled_resources(None)` was previously an error, but will now indicate that all resources should be disabled.
=> tiltfile: add config.set_disabled_resources

internal/feature/flags.go, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewTable.stories.tsx, web/src/OverviewTable.test.tsx, web/src/OverviewTableBulkActions.test.tsx, web/src/OverviewTableBulkActions.tsx, web/src/OverviewTableColumns.tsx, web/src/OverviewTablePane.stories.tsx, web/storybook.tiltfile
This PR turns on the `DisableResources` flag by default and deprecates `BulkDisableResources` flag since it is no longer needed. All the frontend code that uses the bulk feature flag now uses the disable resources flag.
Disable resources will launch for everyone on the next release. 🎉
=> features: turn on Disable Resources feature flag by default

internal/cli/args.go, internal/cli/args_test.go
If `tilt args` specifies the existing args value, then nothing happens. The Tiltfile is not re-executed, and the set of enabled resources is not changed. This might make a user think their command didn't work.
Explicitly tell the user the command didn't do anything.
=> cli: tilt args output indicates when there is no change

integration/fixture_test.go, integration/tilt_ci_test.go, internal/build/pipeline_state.go, internal/build/pipeline_state_test.go, internal/controllers/core/tiltfile/api.go, internal/engine/build_and_deployer.go, internal/engine/k8srollout/podmonitor_test.go, internal/engine/telemetry/controller_test.go, internal/hud/server/apiserver.go, internal/hud/server/server.go, internal/k8s/jsonpath/jsonpath.go, internal/k8s/jsonpath/parser.go, internal/k8s/testyaml/testyaml.go, internal/rty/interactive_tester.go, internal/tiltfile/tiltfile_test.go, pkg/logger/prefixed_logger.go
There is a preference to use `replaceAll` over `replace` with a `-1`.  `replaceAll` is more readable and expressive and is simply a wrapper around the latter func.  It is easier when reading to reason about.
gocritic also wants `//comment` to be `// comment` which does look better.  Additionally this change makes the comments consistent with all other comments in the code base.
Signed-off-by: Ken Sipe <kensipe@gmail.com>
=> Linting fix:  gocritic for replaceall and commentFormatting

web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/OverviewTableColumns.tsx, web/src/ResourceSelectionContext.tsx
This PR adds a checkbox to the resource selection column header for each table displayed in Table View. The header checkbox will select or deselect all resources in its table. It will display as unchecked, indeterminate (partially checked), or checked, depending on the resources in its table.
Here's a sample of what those states look like:
I'd like to refactor the `ResourceSelectionContext` tests and possibly the `OverviewTable` tests to use React Testing Library in a separate PR, so that this one can be reviewed and potentially make into the next release in time.
[Closes ch12975](https://app.shortcut.com/windmill/story/12975/add-checkbox-for-resource-groups).
=> web: add resource selection checkbox for table groups

internal/cli/api_utils.go, internal/cli/args.go, internal/cli/cli.go, internal/cli/disable.go, internal/cli/disable_test.go, internal/cli/enable.go, internal/cli/enable_test.go, internal/controllers/apis/configmap/disable.go, internal/controllers/apis/uiresource/disable.go, internal/hud/webview/convert.go
Some CLI ergonomics that should feel a lot nicer than `tilt args` for use cases that don't involve Tiltfile arg parsing.
```
tilt enable frontend backend
tilt enable --only frontend backend
tilt enable --all
tilt disable frontend backend
tilt disable --all
```
=> cli: add tilt enable/disable

internal/engine/buildcontrol/extractors.go
Historically, the engine builds a lightweight DAG for the targets
in a manifest. A sanity check is done up-front to ensure there's
a single root node (the "deploy" target, i.e. `K8sTarget` or
`DockerComposeTarget` for the cases relevant to this bug). That
node can then have children, which will be `ImageTarget`s, and
for completeness sake, those can recursively have further child
`ImageTarget`s for base images.
Live Update-only targets are currently modeled in the engine as
`ImageTarget`s with a special `IsLiveUpdateOnly` flag which causes
the engine to skip the (non-existant) build. Because there is no
build, there is no `ImageMap`.
As part of API migration, the deploy targets mentioned above are
now driven by their API specs as the source of truth, and both
`KubernetesApplySpec` and …
=> engine: fix build graph structure error on LU-only targets

internal/controllers/core/tiltfile/reconciler.go
This suggested change addresses the possible lack of feedback discussed in #5446
=> tiltfile: warn if default registry has been set but will be ignored

pkg/logger/env.go, pkg/logger/env_test.go
This is an unreported bug, found by using the `gocritic` linter.
The issue was the order of arguments to `strings.HasPrefix`.  The bug wasn't captured in tests as the unit tests were written in a way that didn't detect the issue.  A number of tests were added to provide coverage to verify expectations.
Signed-off-by: Ken Sipe <kensipe@gmail.com>
=> bug: Fix env bug based on order of hasPrefix and provide test coverage

internal/engine/dcwatch/disable_watcher.go, internal/engine/dcwatch/disable_watcher_test.go
When a DC resource is running and configured to be disabled, the DC disable watcher will spawn a goroutine to `docker-compose rm` it. This command can take 5-10 seconds. In the meantime, every call to the watcher's `OnChange` will spawn a new goroutine.
Track which resources currently have an `rm` in progress, and only start cleanup goroutines when there are resources that both need an `rm` and do not already have one.
=> disable: DC: don't spawn goroutines for work that's already in progress

internal/controllers/apiset/apiset.go, internal/controllers/apiset/apiset_test.go, internal/controllers/core/tiltfile/api.go
`ObjectSet.AddSetForType` will blow away any existing objects of the given type, but it's also much easier to read/write than looping over objects.
In [the Tiltfile reconciler](https://github.com/tilt-dev/tilt/blob/06758a2cff2dc808a54a9d24acd0896beb46cef2/internal/controllers/core/tiltfile/api.go#L227-L253), which has all of the uses of this method, we have a mix of calls to `ObjectSet.AddSetForType` and looping over a map and calling Add on objects individually, depending on whether the type had already been added. I added an easy-to-miss bug adding UIButtons here - my buttons blew away any buttons that were added by the Tiltfile. (similarly, if we add ToggleButton to [typesWithTiltfileBuiltins](https://github.com/tilt-dev/tilt/blob/06758a2cff2dc808a54a9d24acd0896beb46cef2/internal/contro …
=> apiset: make ObjectSet.AddSetForType merge instead of replace

internal/cli/generate_tiltfile.go
The primary issue here is that Windows is particular about how
`os.Stdin` + `os.Stdout` are used, so by passing a wrapper that
contains both (stdin for reads, stdout for writes), it's happy
and things still work on macOS/Linux. Hurray!
=> cli: fix Tiltfile generation prompt on Windows

internal/engine/upper_test.go
(and presumably other tests that use this method)
I was getting pretty consistent failures with
`go test ./internal/engine -run TestPodUnexpectedContainerStartsImageBuildOutOfOrderEvents -count 100  -failfast`:
`Operation cannot be fulfilled on [kubernetesapplys.tilt.dev](http://kubernetesapplys.tilt.dev/) "foobar": the object has been modified; please apply your changes to the latest version and try again`
We might want to change the test client to automatically retry on this type of error, as we'd get with an actual controller, but this is simple enough for now.
=> engine: fix flaky TestPodUnexpectedContainerStartsImageBuildOutOfOrderEvents

internal/dockercompose/client.go, internal/dockercompose/fake_client.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, pkg/model/dockercompose.go
=> dockercompose: accept `env_file` argument

internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
=> tiltfile: don't check enabled resources when loading failed

internal/controllers/core/extensionrepo/reconciler_test.go, internal/controllers/core/filewatch/fsevent/factories.go, internal/controllers/core/filewatch/watcher.go, internal/controllers/core/podlogstream/podlogstreamcontroller.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/k8s/entity.go, internal/k8s/statefulset.go, internal/rty/scroll_test.go, internal/rty/text.go, internal/tiltfile/tiltfile_test.go, pkg/logger/prefixed_logger.go
In the process of adding linting fixes currently working on gocritic.  This fixes:
- typeSwitchVar: which cleans up switch statement code with variable assignment 
- assignOp: which cleans up modifications to a var to not stutter
- unlamba: which removes an anonymous function which does nothing but enclose a function of the same signature
- removal of params that start with a capitalization
=> Linting fix: gocritic assignOp, unlambda, typeSwitchVar

internal/controllers/core/filewatch/controller_test.go, internal/controllers/core/portforward/reconciler_test.go, internal/controllers/fake/store.go, internal/dockerignore/ignore_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/local_target_build_and_deployer.go, internal/engine/buildcontrol/local_target_build_and_deployer_test.go, internal/git/gitignore_test.go, internal/rty/interactive_tester.go, internal/store/build_result.go, pkg/apis/core/v1alpha1/togglebutton_types.go
In the process of adding linting fixes currently working on gocritic.  This fixes:
- singleCaseSwitch: should rewrite switch statement to if statement
- ifElseChain: rewrite if-else to switch statement    
- elseif: can replace 'else {if cond {}}' with 'else if cond {}'
Several of these fixes make the code easier to read and reason about.
=> Linting fix: gocritic singleCaseSwitch, ifElseChain, elseif

web/src/OverviewSidebarOptions.test.tsx, web/src/OverviewSidebarOptions.tsx, web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/OverviewTableDisplayOptions.tsx, web/src/ResourceListOptionsContext.tsx, web/src/ResourceNameFilter.tsx, web/src/SidebarResources.test.tsx, web/src/SidebarResources.tsx
This PR adds a "Show disabled resources" option to Detail View and Table View, so people can opt into viewing disabled resources. Like the alerts and resource name filter, it persists in session storage. The option will only display if the `"disable_resources"` feature is enabled.
I also refactored how Detail View and Table View loop over resources to apply options and feature flags to minimize how many iterations the component is doing.
_Side note:_ I've found writing tests with react-testing-library is much easier than enzyme! But refactoring entire test suites takes time. This PR has a combo of new tests written with react-testing-library and new enzyme tests that were easy to copy-paste from existing tests. If this is confusing or undesirable, I'm happy to address, but for speed, I …
=> web: add a show/hide toggle for disabled resources

internal/controllers/core/tiltfile/reconciler_test.go
#5471 had changes relevant to #5473, but #5473 didn't run CI with those changes merged, so master broke when it was merged.
Merging this without waiting for approval since it's trivial and master is broken.
=> api: fix tiltfile reconciler_test compilation

web/src/OverviewTableBulkActions.test.tsx, web/src/OverviewTableBulkActions.tsx, web/src/ResourceSelectionContext.test.tsx, web/src/ResourceSelectionContext.tsx
This PR refactors the `ResourceSelectionContext`, so that adding, removing, and determining whether or not a resource is selected is more performant. (Funnily enough, this was my first implementation, but I refactored to use arrays instead of sets because I thought it might be a premature optimization. 🤦🏻‍♂️ Now, I know it's not!)
This refactor won't make Table View rendering that much faster for Tilt sessions that display a lot of resources, but I can see a noticeable difference in how responsive the UI is when selecting and deselecting resources.
As a bonus, this PR also moves the `ResourcesSelectionContext` tests over to react testing library.
=> web: refactor how resource selection state is stored and calculated

web/src/OverviewLogPane.tsx
This PR simply disables the `use_classes` option when converting ANSI logs to HTML.
While previously only the ANSI classes in https://github.com/tilt-dev/tilt/blob/master/web/src/AnsiLine.scss had any form of colorization support, disabling the `use_classes` option allows any ANSI log to be colorized properly.
=> web: let anser colorize ansi logs

internal/engine/buildcontroller.go
When BuildController starts a build, it synchronously adds the cancel func to its internal state.
When BuildController checks if a build needs canceling, it checks that internal state (which, again, was updated synchronously) against the store's ManifestState (which is updated asynchronously), leaving a brief window where the controller is aware a build is cancelable from its internal state, but has not yet picked up the new ManifestState, and LastClickedAt and ms.CurrentBuild.StartTime are both zero.
(the absence of this check was theoretically fine before because `c.cleanupBuildContext` is a no-op for a build that's not running, but this is probably better to have either way)
=> engine: fix flaky TestCancelBuild

Tiltfile, integration/tilt.go, internal/cli/args.go, internal/cli/demo.go, internal/cli/up.go, internal/cli/up_test.go
Improving UX and reducing confusion around `hud` and `legacy` in favor of `legacy` as noted in  Issue #5455 
Internally, it is still referenced as hud or legacy hud, but it exposed to users as `legacy`.  
The change is much easier to reason about on startup of `up` or `demo`.
`hud` is marked as deprecated which requires a sleep pause in order to display.  1 sec seemed too fast to notice and guessed 3 was reasonable but looking for feedback.
Additionally I guess that 3 major release versions was a reasonable deprecation window, looking for guidance there.
This PR does not handle consolidation of key navigation from prompts yet.
Signed-off-by: Ken Sipe <kensipe@gmail.com>
=> Deprecate --hud in favor of --legacy

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller.go, pkg/model/build_reason.go
Please review the following commits I made in branch nicks/buildcontrol2:
dd2648abe515c9445f6289287ea5deacbb8ef662 (2022-02-14 13:13:43 -0500)
buildcontrol: liveupdate holds should handle triggers
fixes https://github.com/tilt-dev/tilt/issues/5492
=> buildcontrol: liveupdate holds should handle triggers

internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
You run your Tiltfile and get an error like "resource X specified a dependency on unknown resource Y". You know you created a resource named "Y". How do you validate that? At the moment, you have to remove your resource_deps and see what resources come out of Tilt. You're also might suspect a bug in Tilt (and you very well might be right! but there's frustratingly little to go on).
When we generate this error, also include the list of resources Tilt knows about, so that the user can see what resources Tilt is expecting to see there and narrow down the problem.
=> tiltfile: unknown resource_dep is a warning instead of error

web/src/SidebarResources.tsx, web/src/SrOnly.tsx, web/src/analytics.ts
Please review the following commits I made in branch nicks/revert2:
b2d6f0e4a9d863b91e64a0f5b1ff7cdfa9ee60d3 (2022-02-15 18:24:09 -0500)
web: add a small show more button in each section with more than 20 items (try 2)
I had to remove the SrOnly screenreader text because it was causing major layout problems
=> web: add a small show more button in each section with more than 20 items (try 2)

Makefile, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/buildcontrol/wire.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, toast.yml
Follow-up on #5453 that uses the same `-local` arg a few other
places where we have `goimports` tasks.
It also adds `integration/` to the `make goimports` task, which
was missing previously.
Lastly, this runs the latest (v0.1.9) goimports against the repo,
as there were some lingering unformatted files around.
See: https://pkg.go.dev/golang.org/x/tools@v0.1.9/cmd/goimports
=> lint: use consistent goimports local everywhere

internal/controllers/core/portforward/reconciler.go, internal/controllers/core/portforward/reconciler_test.go, internal/controllers/fake/fixture.go
Please review the following commits I made in branch nicks/portforward:
2ef95c5c3ea8fccbdd087a3fb87ad4b27235a774 (2022-02-15 17:23:51 -0500)
controllers: make the portforward reconciler level-triggered rather than edge-triggered
i was chasing down a flaky test and it was easier just to fix the reconciler
=> controllers: make the portforward reconciler level-triggered rather than edge-triggered

internal/controllers/apis/trigger/trigger.go, internal/controllers/apis/trigger/trigger_test.go, internal/controllers/core/cmd/controller.go, internal/controllers/core/cmd/controller_test.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/tiltfile/reconciler.go, internal/engine/buildcontroller.go, internal/engine/k8swatch/event_watch_manager.go, internal/timecmp/cmp.go, internal/timecmp/cmp_test.go
The `trigger` package now returns `metav1.MicroTime` instead of
stdlib `time.Time` for trigger (start/restart/stop) timestamps.
There's a ripple effect for some internal state types on reconcilers
which went through the same conversion.
Comparisons are also all now made via the `timecmp` package using
the API types.
Primarily, this fixes flakiness for tests on Windows; it's fairly
unlikely that the cases here would cause unexpected behavior at
runtime because real world events (e.g. clicking a button) are not
performed instantaneously.
Previously, I'd pretty consistently see failures with just a few (~10) test runs for `TestCancelButton` (in `internal/engine`) on a Windows 11 machine.
After these changes, 500 runs passes:
```
PS C:\Users\User\tilt> go test ./internal/engine -run …
```
=> api: ensure API times used for trigger comparisons

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/upper_test.go, internal/hud/webview/convert.go, internal/store/hold.go
Please review the following commits I made in branch nicks/holds:
38001b7a226093627430dca85294759cb26320ec (2022-02-16 19:57:15 -0500)
buildcontrol: avoid spurious changes to the 'waiting' state on disabled resources
Before this change, the "waiting" state of disabled resources would be
continuously in flux. This is expensive and doesn't even make sense from a data
model perspective - a disabled resource isn't waiting or being held.
=> buildcontrol: avoid spurious changes to the 'waiting' state on disabled resources

internal/cli/doctor.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/reconciler.go, internal/docker/client.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go, internal/docker/wire.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/upper_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, pkg/apis/core/v1alpha1/cluster_types.go
This is an experimental/spike on supporting K8s and DC orchestration simultaneously for #5482. I took a naive approach and am probably overlooking some issues, but I thought I'd put it up for review in any case.
With these changes, I was able to get simultaneous deploys working for the tilt-example-docker-compose project and a Kind cluster. I suspect using Minikube/Microk8s with a separate cluster Docker daemon might still cause issues.
https://github.com/tilt-dev/tilt-example-docker-compose/blob/nicksieger/dc-and-k8s/Tiltfile
=> docker: allow simultaneous k8s and compose orchestration

internal/controllers/core/extensionrepo/reconciler.go, internal/controllers/core/extensionrepo/reconciler_test.go
Please review the following commits I made in branch nicks/ref2:
1d09bba3318f59fabe6a4f3e56a4edd373608299 (2022-02-18 13:49:08 -0500)
extensionrepo: handle ref changes correctly
Fixes https://github.com/tilt-dev/tilt/issues/5508
=> extensionrepo: handle ref changes correctly

.goreleaser.yml
Hello @lianmakesthings,
Please review the following commits I made in branch nicks/contributors:
bfc63385bc94552c1d5acb98d1a8af6777d649f1 (2022-02-22 11:01:44 -0500)
release: add github author names to the release changelog
=> release: add github author names to the release changelog

internal/cli/klog.go, internal/cli/klog_test.go, internal/dockercompose/fake_client.go, internal/engine/dcwatch/disable_watcher.go, internal/engine/dcwatch/disable_watcher_test.go, internal/filteredwriter/filtered_writer.go, internal/filteredwriter/filtered_writer_test.go
For some reason, when we filter `docker-compose rm` through a Tilt logger, we get:
```
Stopping servantes_fortune_1 ... 
Stopping servantes_fortune_1 ... done
servantes_fortune_1 exited with code 137
Removing servantes_fortune_1 ... 
Removing servantes_fortune_1 ... done
Going to remove servantes_fortune_1
```
The last line says "Going to...", which leads one to expect it's going to do something else, but nothing ever comes.
When running docker-compose directly, it shows up in a more sensible place:
```
Stopping servantes_vigoda_1 ... done
Going to remove servantes_vigoda_1
Removing servantes_vigoda_1 ... done
```
(you also might note there's only one line each for "stopping" and "removing" - they do tty tricks to go back and update the existing line, which is probably also why it looks …
=> dc: hide 'going to remove...' message when disabling dc services

web/src/ResourceSelectionContext.test.tsx, web/src/ResourceSelectionContext.tsx
Hello @landism, @lizzthabet,
Please review the following commits I made in branch nicks/selection:
c104669cc33cd379ee8fa8d9696e6c3ab2a3ea99 (2022-02-22 13:59:02 -0500)
web: memoize resource selection provider
=> web: memoize resource selection provider

internal/controllers/core/kubernetesdiscovery/portforwards.go, internal/engine/upper_test.go, internal/store/kubernetesdiscoverys/reducers.go
When a KuberenetesApply is disabled, we delete its KubernetesDiscovery. When we delete a KubernetesDiscovery, the resource's K8sRuntimeState.FilteredPods remains the same forever. The only known impact of this at the moment is that UIResource.Status will list pods that no longer exist. AFAIK the frontend handles that fine.
If a KubernetesApply's KubernetesDiscovery doesn't exist, clear the resource's K8sRuntimeState.FilteredPods.
=> engine: clear known pods when KD is deleted

internal/controllers/core/extensionrepo/reconciler.go, internal/controllers/core/extensionrepo/reconciler_test.go, internal/tiltfile/tiltextension/plugin.go, internal/tiltfile/v1alpha1/plugin.go, internal/tiltfile/v1alpha1/plugin_test.go
Please review the following commits I made in branch nicks/extensions:
308a574504cb4023f98fd347f06a2f493e4d3127 (2022-02-24 11:28:17 -0500)
tiltextension: if a regression where we stopped pulling the default repo
also some minor usability fixes
=> tiltextension: fix a regression where we stopped pulling the default repo

integration/tilt_ci_test.go, internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/store/buildcontrols/log.go, web/src/LogLine.scss, web/src/OverviewLogPane.tsx
Please review the following commits I made in branch nicks/ch13284:
fc1623a022e386281baf124e1d99283ba92ba0ab (2022-02-24 19:38:56 -0500)
web: make build event logs sticky
=> web: make build event logs sticky

internal/hud/fake_hud.go, internal/hud/hud.go, internal/hud/view.go, internal/hud/view_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go
Please review the following commits I made in branch nicks/issue5543:
c19167de564b3c33f647a3d075527dbee04fe3ff (2022-02-28 14:32:30 -0500)
store: move HUD view rendering into the HUD package
Also: skip disabled resources when rendering the legacy HUD
Fixes https://github.com/tilt-dev/tilt/issues/5543
=> store: move HUD view rendering into the HUD package

internal/cli/args.go
There are the changes I originally attempted to make [here](https://github.com/tilt-dev/tilt.build/pull/1056/files#diff-9196fb42514c5c98aa44fc9372700ed5b542218e7d229881830618ad63e99176) before realizing the source code lived here! 
The formatting for headings is a little off on the [`tilt args` docs](https://docs.tilt.dev/cli/tilt_args.html), so this PR attempts to fix the heading hierarchy and moves the code examples into a separate `Examples` section with comments.
=> args: clarify long description and add examples

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/entity.go, internal/k8s/entity_test.go
49e34b218ada023d6c47f5fe8c114be4e12f3627 (2022-03-01 22:26:46 -0500)
k8s: send Pods and Jobs down the same update codepath as other resources
We used to handle Pods and Jobs differently, because
they were immutable. Now, the main codepath should handle
immutability correctly.
=> k8s: send Pods and Jobs down the same update codepath as other resources

internal/build/error.go, internal/k8s/exec.go
When running a command in a Pod, `client-go` attempts to handle
the failure case of a non-zero exit code by inspecting a
`metav1.Status` object.
For other failure cases, it returns `fmt.Errorf(status.Message)`,
and `Message` might be blank, resulting in cryptic error messages
from Tilt.
There's not a lot we can do without upstream `client-go` changes
on the Tilt side, so some extra context is added around where the
exec failed, and for the stream error case, a generic fallback
error message is used if we get an empty error from `client-go`.
See `remotecommand/v4.go` for the problematic `client-go` code:
https://github.com/kubernetes/client-go/blob/8e46da3fd12b54a2d1726fc9a9438ff8fc38494c/tools/remotecommand/v4.go#L91-L118
=> k8s: improve error messages during Pod exec failures

go.mod, go.sum, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, vendor/modules.txt
- tiltfile: preserve dc_resource state
- chore: updated go mod vendor changes
=> Preserve dc_resource state between docker_compose calls

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_state.go
Follow-up to #5561 that extracts options separate from DC services, so that dc_resource state is more easily preserved across docker_compose calls. Also ensures that image ref is preserved, which the previous PR didn't cover.
=> tiltfile: extract dcResourceOptions

internal/controllers/core/cmd/controller_test.go, internal/controllers/core/liveupdate/reconciler.go, internal/controllers/core/tiltfile/reducers.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/engine/runtimelog/docker_compose_log_manager.go, internal/engine/session/conv.go, internal/engine/uiresource/subscriber_test.go, internal/engine/upper_test.go, internal/hud/view.go, internal/hud/view_test.go, internal/hud/webview/convert.go, internal/store/buildcontrols/actions.go, internal/store/buildcontrols/reducers.go, internal/store/engine_state.go, internal/store/manifest_target_test.go, internal/store/tiltfiles/reducers.go, pkg/model/target.go
Please review the following commits I made in branch nicks/builds:
3ac775bc56a2fed62878271224eee7effc22693d (2022-03-07 12:50:47 -0500)
store: separately track builds from different sources
This should become more important once we handle independent
image builds that can run in parallel.
=> store: separately track builds from different sources

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go
Please review the following commits I made in branch nicks/destroy:
7ee196dd61bdd0b78ddaebff1d87d976e5fed19d (2022-03-09 15:04:52 -0500)
kubernetesapply: when disabling a custom deploy, use the delete cmd, not implicit object cleanup
=> kubernetesapply: when disabling a custom deploy, use the delete cmd, not implicit object cleanup

web/src/StarredResourceBar.tsx
Side note: starred disabled resources will display regardless of the "show disabled resources" option.
[Closes ch12979](https://app.shortcut.com/windmill/story/12979/nice-to-have-style-disabled-resources-in-starred-bar).
=> web: style disabled resources in the starred bar

web/src/OverviewTableColumns.tsx, web/src/ResourceStatus.ts
I added back the `disabledResourceStyleMixin`, since we're using those styles in multiple places. This will fix the compilation error in the main branch.
=> web: re-add shared disabled resources style mixin to fix compilation error

web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/OverviewTableColumns.tsx, web/src/OverviewTablePane.tsx, web/src/OverviewTableStatus.tsx
This PR moves the resource name filter, bulk actions, starred bar, and display options into the `OverviewTablePane` component and wraps them in a `sticky` container. They'll be visible as a user scrolls through a long list of resources.
I also included a couple minor adjustments so:
* disabled resource status links are clickable
* tables have a minimum width, since the fixed table layout can make content spill outside of the table container on medium and small screens
[Closes ch12976](https://app.shortcut.com/windmill/story/12976/nice-to-have-make-header-and-options-bar-sticky-to-top-on-table-view)
=> web: make navigation and table options sticky on Table View, plus minor style fixes

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, pkg/model/cmd.go
Hello @milas,
Please review the following commits I made in branch nicks/cmd2:
5066673abc8e1ee456fbe771953a5ffb12bc77c9 (2022-03-11 11:33:51 -0500)
kubernetesapply: improvements to custom cmd
print the command before applying
trim spaces
add a note about multi-line batch scripts on windows
=> kubernetesapply: improvements to custom cmd

.circleci/config.yml
Mirroring https://github.com/tilt-dev/tilt-extensions/blob/26f6619ab1f99313897a1f068ff862d00bdeb460/.circleci/config.yml#L40-L42
=> ci: use Pulumi context for integration tests

.circleci/Dockerfile, .circleci/config.yml, .goreleaser.yml, scripts/release.Dockerfile
This pulls in changes from tilt-dev/golang-cross#2 and makes the
necessary changes on the Tilt side:
* Use the updated `golang-cross` base image
* Minor cleanup to `tilt-releaser` image to reduce layer sizes
* Split `.goreleaser.yml` into more "builds" by OS/arch and pass
the proper `CC` / `CXX` flags now that we need cgo for every
target
* Re-build generic Tilt CI Linux image to pick up Go 1.17.8 to
match the releaser
* Minor cleanup to reduce layer sizes + fix build issue due to
image having cached IP for apt source
* Update image references for CircleCI jobs
* Update Go versions for macOS/Windows CircleCI jobs
* Linux Go version determined by generic Tilt CI image above
* Add new `release-verify` job that runs a `goreleaser build` +
`yarn build` but doesn't publish anything
* Does not …
=> ci: fix cross-compilation toolchain + bump to Go 1.17.8

integration/disable_test.go
Hello @nicksieger, @landism,
Please review the following commits I made in branch nicks/flake2:
f589a550f11f7b515c163cf4835d35b0307f6b95 (2022-03-15 12:58:24 -0400)
integration: wait for resource to become ready before disabling
=> integration: wait for resource to become ready before disabling

internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go
This will be used to poll for cluster health and update the Tilt
`Cluster` status object in the (Tilt) apiserver accordingly.
=> k8s: add cluster/apiserver health check method

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/watch_test.go
Pointer receivers strike again! The `errors.As` check would fail
because `*apierrors.StatusError` is what implements `error`, so
need a pointer-to-a-pointer.
Added some tests that I should have included in the first place
now that I figured out how to fake the raw REST client responses
(surprisingly easy!)
=> k8s: fix cluster health & add tests

internal/controllers/core/dockercomposeservice/disable_watcher_test.go
Hello @nicks,
c21469ab04c1ffe1c7208c473d9b279b622db19d (2022-03-22 17:22:07 -0400)
dockercomposeservice: fix some test race conditions
Most of these are caused by https://github.com/jonboulle/clockwork/issues/35
=> dockercomposeservice: fix some test race conditions

internal/cli/wire_gen.go, internal/controllers/core/cluster/client.go, internal/controllers/core/cluster/client_fake.go, internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go, internal/controllers/core/cluster/wire.go, internal/engine/upper_test.go
The motivation here is in preparation for cluster status polling
to make it possible to write more robust unit tests. Currently,
the reconciler behaved very differently when provided with fake
clients for test. (In fact, there was actually a bug as a result
of this! The `ConnectedAt` timestamp handling was different for
tests.)
Now, there's factories for both K8s/Docker clients that get
injected, and tests can override these. Helper methods are
offered to return a static client for all created connections
or an error.
This latter part is critical to simulating errors with fake clients
in a controlled fashion to verify the (forthcoming) retry behavior.
=> cluster: refactor client initialization

internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go
Thankfully, this wasn't an issue in practice because we never
delete the default `Cluster` object that gets created by the
Tiltfile reconciler.
=> cluster: handle deletes properly

internal/controllers/core/liveupdate/reconciler_test.go, internal/controllers/fake/fixture.go
Hello @nicks,
Please review the following commits I made in branch nicks/restartpolicy:
c71e0bc0633efb27e4000f3a84ddc0dea8e6cadd (2022-03-24 16:00:32 -0400)
test: add tests for live update execs and restarts
=> test: add tests for live update execs and restarts

internal/engine/upper_test.go, internal/feature/flags.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/liveupdateflag:
628032535b3c57a29b67442e2f43335801bc0bb6 (2022-03-24 15:28:47 -0400)
feature: mark the live_update_v2 flag as obsolete
=> feature: mark the live_update_v2 flag as obsolete

internal/controllers/core/cluster/cache.go, internal/controllers/core/cluster/reconciler.go
This PR populates the local registry info in the cluster API object. (Once #5631 is merged in, I'll point this PR to the main branch.)
=> cluster: populate local registry information

internal/controllers/core/liveupdate/reconciler.go, internal/controllers/core/liveupdate/reconciler_test.go
Please review the following commits I made in branch nicks/execerror:
4b7eb165ccc34afdc836193fed14321602e700e1 (2022-03-28 16:00:17 -0400)
liveupdate: display exec errors correctly
fixes https://github.com/tilt-dev/tilt/issues/5635
=> liveupdate: display exec errors correctly

web/src/GlobalNav.tsx
This PR refactors how the `GlobalNav` manages the display state for menu item dialogs, and it'll simplify the code I'll write to add a cluster connection menu item.
* It now uses a single `openDialog` state, instead of tracking separate (mutually exclusive) state for each dialog. 
* It also removes references to analytics `close` events, since there wasn't a code path that would log those events. (I think it's sufficient for our analytics to continue to log `click` events on the menu buttons, and separate `close` events don't add additional information, but chime in if I'm wrong!)
=> web: simplify how the global nav manages dialog display state

internal/engine/build_and_deployer_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/store/build_result.go, internal/store/liveupdates/fake.go
Please review the following commits I made in branch nicks/liveupdate2:
6457079b35132eb660cb4137170ac9466ae7306d (2022-03-29 11:47:47 -0400)
buildcontrol: remove live update state from build state
=> buildcontrol: remove live update state from build state

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontroller.go, internal/store/build_result.go
Please review the following commits I made in branch nicks/liveupdate3:
2716aeb84ad81354220c369123b248f6d031b04a (2022-03-30 13:21:16 -0400)
buildcontrol: put the Cluster in BuildState
b70a390062a8471baa8009268acd36b795213655 (2022-03-29 11:53:55 -0400)
buildcontrol: remove live update state from build state
=> buildcontrol: put the Cluster in BuildState

internal/controllers/apis/configmap/disable.go, internal/controllers/apis/configmap/disable_test.go, internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/api_test.go, internal/controllers/core/tiltfile/filewatch.go
Hello @landism, @nicksieger,
Please review the following commits I made in branch nicks/every2:
f289f7a052e3829b2e67ec2258cccf7b4095848a (2022-03-31 17:41:50 -0400)
tiltfile: properly model filewatches shared across multiple images
fixes https://github.com/tilt-dev/tilt/issues/5621
=> tiltfile: properly model filewatches shared across multiple images

internal/engine/buildcontrol/extractors.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/upper_test.go, pkg/model/image_target.go, pkg/model/manifest.go
Please review the following commits I made in branch nicks/cluster7:
2326cd8b18a8b50f879517724567f7fc711e4b53 (2022-04-04 13:09:56 -0400)
buildcontrol: use ClusterNeeds to determine whether to push
most importantly, this is the last step to removing the
dependency of image build/push on K8sTarget
=> buildcontrol: use ClusterNeeds to determine whether to push

go.mod, go.sum, internal/docker/env.go, vendor/github.com/tilt-dev/clusterid/product.go, vendor/modules.txt
Colima is a macOS/Linux local cluster tool built on top of Lima.
It creates lightweight VMs with Docker and (optionally) Kubernetes
with Docker being used as the Kubernetes container runtime and the
socket exposed for building images directly to its context.
Fixes #5625.
=> docker: support Colima for building direct to cluster

internal/build/image_builder.go, internal/build/kind.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/controllers/core/cmdimage/reconciler.go, internal/controllers/core/dockerimage/imagemap.go, internal/controllers/core/dockerimage/reconciler.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/wire.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/upper_test.go, internal/engine/wire.go, internal/engine/wire_gen.go
Please review the following commits I made in branch nicks/cluster9:
4b294b71e83ae0b8a3d1a8d782946b4a72a0f734 (2022-04-05 14:08:18 -0400)
buildcontrol: move image build logic into the reconcilers
=> buildcontrol: move image build logic into the reconcilers

internal/controllers/core/liveupdate/reconciler.go, internal/controllers/core/liveupdate/reconciler_test.go, internal/controllers/core/liveupdate/resource.go
Please review the following commits I made in branch nicks/liveupdatedc:
0931493713b7a385edd66787730db793a3a3ecc6 (2022-04-06 15:14:25 -0400)
liveupdate: fix handling of docker-compose restarts
Fixes https://github.com/tilt-dev/tilt/issues/5663
=> liveupdate: fix handling of docker-compose restarts

web/src/ApiButton.tsx, web/src/OverviewTablePane.tsx, web/src/SocketBar.tsx, web/src/constants.scss, web/src/style-helpers.ts
Fixing a bug I introduced when I implemented the sticky Table View bar 🤦🏻‍♂️
This PR fixes the conflicting overlap in `z-index` values that caused the socket bar message to be hidden on Table View. I also centralized any `z-index` values greater than `2`, so we can avoid conflicts like this in the future.
=> web: fix socket bar z-index so it displays on Table View

internal/cli/down.go, internal/cli/down_test.go
When running tilt down, the order of deletion isn't dependent on the
resource_deps specified. These changes introduce a dependency graph to
the down command to determine the correct deletion order.
Fixes #4431
=> Build dependency graph for k8s deletion in tilt down

internal/build/image_builder.go, internal/cli/docker_prune.go, internal/cli/wire_gen.go, internal/container/default_registry.go, internal/container/default_registry_test.go, internal/container/reference.go, internal/controllers/apis/cluster/registry.go, internal/controllers/core/cluster/reconciler.go, internal/controllers/core/dockerimage/imagemap.go, internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/api_test.go, internal/controllers/core/tiltfile/reconciler.go, internal/controllers/core/tiltfile/reconciler_test.go, internal/engine/analytics/analytics_reporter.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontrol/docker_compose_build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer_test.go, internal/engine/buildcontrol/target_queue_test.go, internal/engine/buildcontrol/testdata_test.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/k8s_custom_deploy_test.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_test.go, pkg/model/image_target.go, pkg/model/manifest.go, pkg/model/manifest_test.go
This is another place where we need to use the `Cluster` object
to determine the registry to resolve image references on the fly.
The brunt of the fallout here is actually throughout tests; many
of these now rely on the `.ImageMapSpec.Selector` directly, but
some that are testing specific registry-rewriting functionality
have been adapted to work.
Marking this as a draft because it depends upon #5677.
=> engine: remove Refs from ImageTarget

web/src/HUD.tsx, web/src/HeaderBar.stories.tsx, web/src/HeaderBar.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourcePane.test.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewTablePane.stories.tsx, web/src/OverviewTablePane.tsx, web/src/ResourceStatusSummary.tsx, web/src/SocketBar.tsx, web/src/constants.ts
This PR updates the document title and page favicon when there's a socket connection issue, so it's clearer to users looking at a browser tab title that Tilt has disconnected.
Closes #5650
=> web: update the document title and favicon when Tilt UI disconnects

internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go
Until the `cluster_refresh` feature is done, initialization errors
for the cluster are unrecoverable, as not all parts of Tilt know
how to re-initialize the client/themsleves properly on change.
The error message is now wrapped with some additional context and
a notice that Tilt needs to be restarted after fixing the issue.
=> cluster: improve unrecoverable error message

web/src/GlobalNav.tsx, web/src/HeaderBar.stories.tsx, web/src/HeaderBar.tsx
This PR passes the cluster information from the `view` to the `GlobalNav` component, so that cluster status will be visible to users. (Previously the cluster info was only added to storybook components, so we had flexibility to do more API work before showing that information explicitly to users.)
I'll keep this PR in draft state till we're ready to launch. 
Closes [ch13397](https://app.shortcut.com/windmill/story/13397/as-user-i-see-cluster-status-with-dropdown-menu-that-shows-only-k8s-info-no-buttons).
=> web: display cluster connection status in global nav

internal/controllers/apis/cluster/client_fake.go, internal/controllers/apis/cluster/client_test.go, internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/controllers/core/kubernetesdiscovery/reconciler_test.go, internal/controllers/fake/fixture.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/service_watch_test.go
I extracted this from the KubernetesDiscovery Reconciler since it'll
be needed across a bunch of them.
=> api: add cluster helpers to ControllerFixture

integration/k8s_custom_deploy/Tiltfile, integration/k8s_custom_deploy_test.go, internal/engine/buildcontroller_test.go, internal/tiltfile/k8s_custom_deploy.go, internal/tiltfile/tiltfile_state.go, pkg/model/k8s_target.go
The `k8s_custom_deploy` is unusual: it's possible to use with
no Tilt-managed image build while still getting Live Update
functionality. This is useful for scenarios where you have an
all-in-one build&deploy tool (e.g. Knative) you want to use
with Tilt.
However, this meant that the value of the `deps` arg was being
passed both to the deploy target (K8s/`apply_cmd`) as well as
the image target (Live Update), which introduced a race between
them. If the Live Update reconciler saw a (supported) file change
first, it would clear it from the pending file list on the deploy
target once done, and so the deploy target would be skipped, as
it no longer had any pending changs. On the other hand, if the
deploy target saw it first, it'd start running because deploy
target changes can't be Live …
=> k8s_custom_deploy: fix Live Update rebuild

.circleci/Dockerfile.integration, .circleci/config.yml
We were pinned to v2.2.2 previously because v2.3.x had a regression
that made it unsuitable for use with Tilt, but v2.4.x is now out
(and shipping with latest Docker Desktop releases).
A couple of other bits were behind so I bumped them as well. (Note
that the Docker CLI is still behind because the latest static
binaries are mysteriously missing from the download site, but that's
not really a big deal.)
=> ci: use Compose v2.4.1 for integration tests

internal/controllers/core/cmdimage/reconciler.go, internal/controllers/core/cmdimage/status.go, internal/controllers/core/dockerimage/imagemap.go, internal/controllers/core/dockerimage/reconciler.go, internal/controllers/core/dockerimage/status.go, internal/controllers/wire.go, internal/engine/buildcontrol/image_build_and_deployer_test.go
Please review the following commits I made in branch nicks/imager:
878270caabcd9c2990e768bcf7220d4c442b3c99 (2022-04-15 11:33:28 -0400)
controllers: move status updates into the reconcile loop
=> controllers: move status updates into the reconcile loop

internal/cli/wire_gen.go, internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go, internal/engine/upper_test.go, internal/feature/flags.go, internal/hud/server/websocket.go, internal/hud/server/websocket_test.go, web/src/HUD.tsx
We were only sending this on the full view, so it wouldn't get
re-sent at runtime without a refresh.
=> server: send Cluster as part of partial update

web/src/ApiButton.test.tsx, web/src/ApiButton.tsx
I'm sorry this diff is massively large. 😅 All the tests should be the same, both in title and what they're testing! Some are shorter because RTL has more concise interfaces for stuff like user events, and some are longer because I used more robust assertions, `expect().toBeInDocument()` and `expect().toHaveValue()`, and it can be wordier to query by label text.
=> web: refactor ApiButton tests to use react-testing-library instead of enzyme

internal/controllers/core/kubernetesdiscovery/reconciler.go, internal/engine/k8swatch/event_watch_manager.go
Please review the following commits I made in branch nicks/events:
195cbd53d69b353685a7fc9913dcf44299edfda5 (2022-04-18 18:51:00 -0400)
engine: remove an error message from the event watcher
=> engine: remove an error message from the event watcher

web/src/HUD.test.tsx, web/src/SocketBar.tsx
Please review the following commits I made in branch nicks/reacttesting:
a729e8594ffe49a65515beb5ffa2e323e97c2624 (2022-04-19 14:31:46 -0400)
web: switch HUD tests to use react test-utils instead of enzyme
=> web: switch HUD tests to use react test-utils instead of enzyme

internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/flake4:
63757750aa8c1e56a5be0d000b6bba9184ac4e74 (2022-04-22 14:28:52 -0400)
test: if we don't see any call for 200ms, it's OK to assume no build is happening
takes engine tests from ~70s to 40s
=> test: if we don't see any call for 200ms, it's OK to assume no build is happening

internal/tiltfile/api/__init__.py, internal/tiltfile/files.go
This add a parameter to `helm` command (kube-version) to support `--kube-version` `helm template` flag.
=> feat(helm): fix #5726, add kube-version flag support to helm command

internal/build/test_utils.go, internal/cli/demo.go, internal/cli/doctor.go, internal/cli/wire_gen.go, internal/controllers/core/cluster/reconciler.go, internal/docker/client.go, internal/docker/client_integration_test.go, internal/docker/client_test.go, internal/docker/clients.go, internal/docker/env.go, internal/docker/switch.go, internal/docker/wire.go
Hello @milas, @lizzthabet,
Please review the following commits I made in branch nicks/dockerclient2:
6b1917e34eb65c0935a3753770abd4acd2753635 (2022-04-22 12:38:47 -0400)
docker: use the CLI library for creating our docker client.
Fixes https://github.com/tilt-dev/tilt/issues/4769
Fixes https://github.com/tilt-dev/tilt/issues/4878
=> docker: use the CLI library for creating our docker client.

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go
In some cases, the GC logic for `KubernetesApply` objects with custom
apply + delete commands would fallback to the YAML based GC, which
looks at dangling objects.
We want to explicitly avoid that: the `delete_cmd` should _always_ be
used (and must handle dangling objects). This is critical for the
`k8s_attach`[1] use case (provided by an extension), where we do NOT want
Tilt to potentially delete the externally managed resource. (The
extension uses a no-op `delete_cmd`[2].)
Fixes #5722.
[1]: https://github.com/tilt-dev/tilt-extensions/tree/master/k8s_attach
[2]: https://github.com/tilt-dev/tilt-extensions/blob/106042efccd0149854f40619493257e305b5c755/k8s_attach/Tiltfile#L32
=> kubernetesapply: only use `delete_cmd` for GC with `k8s_custom_deploy`

internal/controllers/core/kubernetesdiscovery/portforwards.go, internal/controllers/core/kubernetesdiscovery/reconciler_test.go, internal/controllers/fake/fixture.go
Tilt supports a bunch of variations when defining a port forward in
a Tiltfile.
It's possible to specify a single value (a local port), and in this
case, Tilt will look for a matching exposed port to use. If none
is found, it'll use the first exposed port.
This behavior is confusing and doesn't match existing functionality
in e.g. `kubectl`.
Allowing a single port that will be used identically for local and
container is reasonable short-hand, but picking an implicit port
to map to adds extra complexity for questionable value.
In this latter case, a warning is now emitted along with the mapping
and instructions for the user to update their `Tiltfile` to make it
explicit before it breaks in a future release of Tilt.
To fully deprecate this, we can change the logic to always default
the …
=> portforward: deprecate implicit container port behavior

internal/ignore/ephemeral.go
When creating files in Go, the stdlib will create (and then rapidly
delete) files ending with `-go-tmp-umask` to determine the umask
to use for permission purposes.
This can cause trouble with Live Update because the files tend to
vanish underneath it, for example.
Fixes #5117.
=> ignore: add Go umask files to ephemeral set

internal/cli/up.go, internal/cli/up_test.go
The `--hud` flag has been deprecated for a bit and thrown a warning
on start (with a forced multi-second wait).
Users who wish to continue using the TUI may do so for now by running
`tilt up --legacy`.
=> cli: remove deprecated --hud flag in favor of --legacy

internal/tiltfile/docker.go, internal/tiltfile/encoding/json.go, internal/tiltfile/encoding/json_test.go, internal/tiltfile/files.go, internal/tiltfile/io/io.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value/path.go
Hello @landism, @nicksieger,
Please review the following commits I made in branch nicks/none:
8fd07614d1c84b4911c708f9311a61f53bf69dc2 (2022-05-02 16:02:16 -0400)
tiltfile: improve path argument parsing. Allow docker_build(dockerfile=None).
Fixes https://github.com/tilt-dev/tilt/issues/5753
=> tiltfile: improve path argument parsing. Allow docker_build(dockerfile=None).

internal/tiltfile/docker.go, internal/tiltfile/docker_test.go, internal/tiltfile/tiltfile_state.go
Do not _watch_ the Dockerfile from the image target, as this is
handled by the Tiltfile, which provides the full contents to the
target in-memory (i.e. the on-disk Dockerfile isn't actually used
when we execute the build).
This prevents race conditions from them both watching it, and
ensures that the flow always goes:
(Dockerfile change) -> Tiltfile execute -> image build
Fixes #5586.
=> docker: fix spurious double builds on Dockerfile change

internal/hud/webview/convert.go, internal/hud/webview/convert_test.go
This is a bit of a hacky fix to prevent bizarre behavior if you
end up with an extension that has the same name as another resource.
Fixes #4883.
=> extension: prevent name collisions with resources

internal/k8s/serialize.go, internal/tiltfile/tiltfile_test.go
If possible, contextualize the error with the object kind and
name.
This is useful when the object is syntactically valid YAML/JSON
but fails parsing due to e.g. mismatched types on a field.
See #5640.
=> tiltfile: improve k8s_yaml error messages

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go
This simple fix appears to give the desired behavior described in #5605. It also causes the Tiltfile to be reevaluated, and may causes an image build (which should be fast because everything is cached), but it does reload the service with the env file changes injected.
I put up a branch https://github.com/tilt-dev/tilt-example-docker-compose/tree/nicksieger/env-files with two env files, `compose.env` as well as `app.env`. Changing either file causes the app to be reloaded.
Fixes #5605.
=> dockercompose: watch service env files

web/src/OverviewTable.test.tsx, web/src/OverviewTable.tsx, web/src/OverviewTableColumns.tsx, web/src/OverviewTableTriggerModeToggle.test.tsx, web/src/testdata.tsx
fixes #5754
This was broken by #5582 - the addition of `id` to the "mode" column definition caused the trigger mode to be written to RowValues as "mode" rather than "triggerMode", and this somehow didn't cause a compilation failure. The react-table docs around id vs accessor are not very clarifying, and I'm not sure it's worth getting to the bottom of that at the moment.
I'm happy to hear if there's a more idiomatic way to write the test.
=> web: fix table view trigger mode button

internal/hud/server/server.go, web/src/HUD.tsx
Please review the following commits I made in branch nicks/apierrors:
5bbbb0cc016b7788981c8e0501504ee84099a743 (2022-05-03 17:56:04 -0400)
web: more gracefully handle server errors when posting snapshots
=> web: more gracefully handle server errors when posting snapshots

internal/watch/watcher_naive.go, internal/watch/watcher_naive_test.go
Please review the following commits I made in branch nicks/inotify:
daaaf614cd55dd0bea75fecfc48164b3e114e975 (2022-05-04 19:58:46 -0400)
watch: optimization to help avoid inotify nodes for large file trees
fixes https://github.com/tilt-dev/tilt/issues/5764
=> watch: optimization to help avoid inotify nodes for large file trees

internal/controllers/core/kubernetesapply/disco.go, internal/controllers/core/kubernetesapply/reconciler.go
Hello @milas,
Please review the following commits I made in branch nicks/disco:
66d2265b9e086a356205b08fec412f95703ce702 (2022-05-05 16:19:32 -0400)
kubernetesapply: prevent some spurious error messages
=> kubernetesapply: prevent some spurious error messages

internal/controllers/core/dockercomposeservice/logs.go, internal/controllers/core/dockercomposeservice/reconciler.go, internal/controllers/core/dockercomposeservice/reconciler_test.go
Hello @milas,
Please review the following commits I made in branch nicks/dclogs:
d3992e3f912468db69504e17c3fd4419b805b552 (2022-05-05 17:16:43 -0400)
dockercomposeservice: create logs object
=> dockercomposeservice: create logs object

internal/k8s/client.go
Set a timeout on the request, which will both be passed onto the
server as well as used to create a child context with a deadline.
A fixed value of 10sec is used here for now.
Additionally, max retries is set to 1 vs the default of up to 10.
See #5729.
=> cluster: reduce timeout/retries on cluster health check

internal/tiltfile/api/__init__.py, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go
Fixes #5770
We already had and used project name in the ProjectSpec, it just wasn't settable from the Tiltfile
=> tiltfile: add docker_compose project_name param

internal/controllers/core/kubernetesapply/disco.go, internal/controllers/core/kubernetesapply/disco_test.go
Fixes #5773
Neither my brain nor the unit tests have come up with a reason it'd be problematic to use the yaml from the status instead of the spec, but I'm not super familiar with this part of the code.
=> kubernetesapply: support extra_pod_selectors with custom_k8s_deploy

internal/controllers/core/cluster/cache.go, internal/controllers/core/cluster/monitor.go, internal/controllers/core/cluster/reconciler.go
I'm not 100% sure this is the root cause of the cluster health
monitoring getting stuck, but it's definitely not totally correct
in its current state.
The `ConnectionManager` is a fancy wrapper over a `sync.Map` and
expects the `connection` objects to be immutable — we replace them
entirely on change. Within the context of the reconciliation loop,
this is good. However, the health status monitor also needs to store
the result of the health checks and was doing so on the same object,
which resulted in a race condition.
Now, the cluster health state is stored independently and used within
reconciliation. The main `Reconcile()` loop still replaces objects
in their entirety in the `ConnectionManager`, but as its the only writer
now, there's no potential for stale data/races.
See #5729.
=> cluster: refactor health monitoring to avoid getting stuck

internal/controllers/core/cmd/execer_test.go
I've seen this fail in CI a decent number of times in recent months. I haven't taken the time to 100% confirm this hypothesis, but it seems [assertCmdSucceeds](https://github.com/tilt-dev/tilt/blob/7e0994075b6cea84b1df12cb408f844906474696/internal/controllers/core/cmd/execer_test.go#L43-L44) (which waits for the process to report an exit) can return before all output has been written to the stdout Writer.
I'm guessing this is due to the complications discussed in [this execer comment](https://github.com/tilt-dev/tilt/blob/52f56d1aab323169e33a97f1bd94c4bbd0764a9d/internal/controllers/core/cmd/execer.go#L188-L195)
This is arguably actually a bug in execer, but I'm not sure it's a problem in practice, am not aware of any manifestations of it outside of tests, and suspect it's non-trivial to …
=> execer: fix flaky TestWorkdir

internal/cli/wire.go, internal/cli/wire_gen.go, internal/controllers/core/cluster/client.go, internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go, internal/controllers/core/kubernetesapply/disco.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/env.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go
Hello @milas, @lizzthabet,
Please review the following commits I made in branch nicks/minify2:
01f0473accbe5a95cc3514db257935a7ba20b16f (2022-05-06 15:20:37 -0400)
cluster: write a frozen kubeconfig when we connect
=> cluster: write a frozen kubeconfig when we connect

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/upper_test.go
Hello @milas,
Please review the following commits I made in branch nicks/minify5:
2e180a76f290e5e3c04392b75a9e281bc78c4040 (2022-05-09 12:42:22 -0400)
kubernetesapply: inject a frozen kubeconfig into k8s_custom_deploy
Fixes https://github.com/tilt-dev/tilt/issues/5703
=> kubernetesapply: inject a frozen kubeconfig into k8s_custom_deploy

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/engine/buildcontrol/image_build_and_deployer.go, internal/engine/buildcontrol/image_build_and_deployer_test.go
Hello @milas,
Please review the following commits I made in branch nicks/minify6:
65c17cd8abce54b36f99ac36f998322da13ee4a2 (2022-05-09 14:34:00 -0400)
kubernetesapply: inject frozen kubeconfig into the delete cmd as well
=> kubernetesapply: inject frozen kubeconfig into the delete cmd as well

.circleci/config.yml, CONTRIBUTING.md, Makefile, build.toast.yml, scripts/release.Dockerfile
Our builds have gotten more complicated recently with the new
requirement of CGO on _all_ platforms (due to Tree-sitter for
the LSP) as well as the embedded assets mode.
As a result, I added an alternate CI flow to build (but not
publish) binaries to ensure things were working as expected.
However, this requires having sufficient CircleCI access, has
a confusing UX, and complicates the `.circleci/config.yml` file
pretty significantly.
This commit eliminates that in favor of a `Makefile` task that
can be executed locally and uses Toast to do a containerized build
that will include embedde JS assets and produce cross-compiled
binaries for all supported OS/arch combinations using the same
underlying builder image as CI.
(Users who wish to build Tilt from source can also take advantage
of …
=> script: add local release build `Makefile` task

web/src/ResourceStatusSummary.test.tsx, web/src/ResourceStatusSummary.tsx
This PR fixes the misleading `... disconnected | Tilt` document title that displays for snapshots when there's no socket connection. Instead, snapshots will have `Snapshot:` prepended to the usual (connected) resource status title. 
This PR also moves the document metadata calculations into a separate helper function, so it's easier to test.
You can test this PR by creating and viewing snapshots using the CLI or web UI with `offline_snapshot_creation` flag enabled.
[Closes ch13500](https://app.shortcut.com/windmill/story/13500/fix-snapshots-json-disconnected-html-title)
=> web: update document HTML title based on snapshot status

web/src/ShareSnapshotModal.tsx, web/src/SnapshotBar.tsx
The formatted version for the filename was also being used for
display in the header. Switched it to use `lll` format, which
is friendlier/more readable.
=> web: fix snapshot bar date format

internal/tiltfile/api/__init__.py
[Closes #1106](https://github.com/tilt-dev/tilt.build/issues/1106)
=> docs: fix wording on `docker_build`'s DC description

web/src/OverviewActionBar.tsx
I was able to reproduce #5818 by adding a bunch of `links` to a resource and viewing that resource in a small window. Wrapping the links container fixes the issue. 
Closes #5818
=> web: wrap endpoint links container to prevent log pane from hiding sidebar

internal/docker/client_test.go, internal/docker/env.go
=> docker: recognize docker desktop for linux socket location

.circleci/Dockerfile, .circleci/config.yml
* Docker Compose v2.6.0
* Helm v3.9.0
* kustomize v4.5.5
* golangci-lint v1.46.2
The only major bump here is for kustomize, but `kubectl` now ships
v4.x built-in, so this should be safe and keep things more in
alignment with what many users are likely using implicitly.
=> ci: update dependencies

web/package.json, web/src/AnalyticsNudge.scss, web/src/FatalErrorModal.scss, web/src/HUD.scss, web/src/ShareSnapshotModal.scss, web/yarn.lock
The `node-sass` package has been deprecated and superseded by the
`sass` package.
The `node-sass` package used a C library via `node-gyp`, which itself
requires Python to wrangle the compilation. The version of `node-sass`
we were using was old and thus relied on an old version of `node-gyp`,
which only supported <= Python 3.8.
This caused problems with Homebrew builds with embedded assets, as
Python 3.9 is used there, so `node-gyp` would error out.
While it's theoretically possible to upgrade `node-sass` to a newer
version to transitively get a newer `node-gyp` that will not bail on
Python 3.9, that did NOT work out of the box, and the recommended
solution for the problem was...switch to `sass`, which does not have
any native code requirements and is actively supported.
As part of this, …
=> web: replace node-sass with sass

.circleci/config.yml
- Missed this config in #5842.
- Also bump remote docker version to 20.10.14.
=> ci: add arm support to release remote docker

internal/k8s/env.go
Hello @nicksieger,
Please review the following commits I made in branch nicks/issue5831:
1b6ff4c60d7bf58e6b707085984ce1171b13436d (2022-06-07 16:35:39 -0400)
k8s: use a different config validation codepath.
Fixes https://github.com/tilt-dev/tilt/issues/5831
=> k8s: use a different config validation codepath.

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go, internal/hud/view_test.go, internal/store/kubernetesdiscoverys/reducers.go, internal/store/runtime_state.go
If a Job ran to completion in the past, so the apply was a no-op,
and the Pod is now gone, consider the Job as being in an "OK"
state. See #5858 for API changes.
Fixes #5822.
=> engine: consider apply conditions for runtime status

.circleci/Dockerfile.integration, .circleci/config.yml, .goreleaser.yml, Makefile, build.toast.yml, scripts/build-tilt-releaser.sh, scripts/goreleaser.sh, scripts/release.Dockerfile, scripts/tilt.Dockerfile
Hello @nicksieger,
Please review the following commits I made in branch nicks/images:
85190daa499b9a65ae7606d9b0e9999a2808ffff (2022-06-10 14:57:15 -0400)
circleci: move images to docker org
=> circleci: move images to docker org

Makefile, go.sum, internal/build/custom_builder.go, internal/build/custom_builder_test.go
- chore: go mod tidy and use gotestsum for local `make test-go`
- build: outputsImageRefTo cluster ref uses HostFromContainerRuntime
=> Replace registry when using outputs_image_ref_to with different cluster host

internal/store/kubernetesapplys/reducers_test.go, internal/store/kubernetesdiscoverys/reducers.go
Please review the following commits I made in branch nicks/issue-5866:
c66e333e1696a1bac5ba439ebd729ca38b330cb0 (2022-06-15 12:02:10 -0400)
store: fix a segfault when events come in out of order
=> store: fix a segfault when events come in out of order

internal/controllers/core/kubernetesdiscovery/portforwards.go, internal/controllers/core/kubernetesdiscovery/reconciler_test.go
Update error message for port_forwards to say `port_forwards` to reduce possible copy paste confusion
=> Update error message for port_forwards

internal/cli/up.go
<https://tilt.dev/user_config.html> is 404 and digging in <https://github.com/tilt-dev/tilt.build/> didn't reveal when it disappeared, so… no idea how long this has been broken, but now it is and should be fixed. :-/
=> cli: fix link to tiltfile_config doc

internal/controllers/core/filewatch/controller.go, internal/controllers/core/filewatch/controller_test.go, internal/controllers/core/filewatch/fsevent/fake_watcher.go, internal/controllers/core/filewatch/watcher.go
Hello @milas,
Please review the following commits I made in branch nicks/watcher:
1cdad91ea324e30fa213c228e5593fd4977b04c1 (2022-07-08 16:50:10 -0400)
filewatch: if the Start() fails, clean up immediately
=> filewatch: if the Start() fails, clean up immediately

internal/ignore/ephemeral.go, internal/ignore/path_matcher_test.go
Currently the emacs ignore patterns include `**/.#*` (lock files), but
doesn't include `**/#*#` (autosave files;
https://www.emacswiki.org/emacs/AutoSave, not to be confused with
`**/*~` backup files, which are ignored.)
Add autosave files.
=> Update emacs ignore patterns

internal/docker/client_test.go, internal/docker/env.go
Rancher Desktop has an option to run in a mode that does not require `sudo` access on Linux and Mac.  In these cases, Rancher Desktop creates the docker socket at `~/.rd/docker.sock`.  This PR updates the docker socket connection logic to account for this case.
Related issues:
#5367 
#5751
=> Detect non-admin socket for Rancher Desktop on Mac

internal/tiltfile/api/__init__.py, internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
also print kustomize invocation like we do with helm
fixes https://github.com/tilt-dev/tilt/issues/5956
fixes https://github.com/tilt-dev/tilt/issues/5007
=> tiltfile: add kustomize(flags) for passing extra flags

internal/controllers/core/dockercomposeservice/reconciler.go, internal/controllers/core/dockercomposeservice/reconciler_test.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/engine/buildcontrol/docker_compose_build_and_deployer.go, internal/engine/buildcontrol/docker_compose_build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer_test.go
This is similar to how it works for the kubernetes controllers; this is just porting the same logic to the compose controllers.
fixes https://github.com/tilt-dev/tilt/issues/5913
=> buildcontrol: restart should do a full delete of the resource

internal/k8s/portforward.go
A possible fix for #5981. Ignores IP addresses that contain a zone index when trying to determine which IP address to use for port forwarding.
=> Ignores IPv6 addresses containing a zone index #5981

internal/cli/client/config.go, internal/filelock/filelock.go, internal/filelock/filelock_unix.go, internal/filelock/filelock_windows.go, internal/filelock/with_lock.go, internal/hud/server/controller.go
Fixes #4814.
Signed-off-by: Nick Sieger <nick@nicksieger.com>
=> config: copy go's file lock and use it instead of client-go's

internal/controllers/core/cluster/reconciler.go, internal/controllers/core/togglebutton/reconciler.go
controller-runtime Get() sets the pointer to an object in the cache.
Status().Update(obj) modifies the object :\
this was leading to really weird race conditions
that were nagging at me.
=> controllers: objects need to be cloned before update

internal/cli/ci.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/controllers/core/session/reconciler_test.go, internal/controllers/core/session/status.go, internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/api_test.go, internal/controllers/core/tiltfile/reconciler.go, internal/controllers/core/tiltfile/reconciler_test.go, internal/engine/upper_test.go, internal/store/sessions/object.go, internal/tiltfile/api/__init__.py, internal/tiltfile/cisettings/ci_settings.go, internal/tiltfile/cisettings/ci_settings_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/wire.go, pkg/model/ci.go, pkg/webview/view.pb.go
Fixes https://github.com/tilt-dev/tilt/issues/3783
=> session: implement ci timeouts, defaulting to 30m

internal/engine/upper_test.go, internal/tiltfile/docker_compose.go, internal/tiltfile/docker_compose_test.go, internal/tiltfile/tiltfile_docker_compose_test.go
`depends_on` or other dependencies in the compose file implicitly add a resource dependency, so you won't have to declare duplicate information with `dc_resource(..., resource_deps=...)`.
=> docker_compose: infer resource deps from compose project

internal/build/container_test.go, internal/cli/demo/k3d.go, internal/docker/client.go, internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go
fixes https://github.com/tilt-dev/tilt/issues/6000
note that after this PR, tilt will only prune images with the new label. we could add backcompat code to prune the old images, but i'm not sure it's worth the ongoing performance hit.
=> docker: add properly namespaced labels

go.mod, go.sum, vendor/github.com/tilt-dev/go-get/vcs.go, vendor/modules.txt
adds support for gitlab modules
Pulls in https://github.com/tilt-dev/go-get/pull/13 Fixes https://github.com/tilt-dev/tilt/issues/5909
=> vendor: update tilt-dev/go-get

internal/engine/upper_test.go
hoping this will help with some recent test flakes where assertions were running after the test exited
eg https://app.circleci.com/pipelines/github/tilt-dev/tilt/12529/workflows/7f94f22d-c92a-4f69-b8f7-543b56558bac/jobs/93616
=> test: add a channel drain during test teardown

web/src/HUD.tsx, web/src/OverviewActionBar.tsx, web/src/OverviewResourcePane.stories.tsx, web/src/OverviewResourcePane.test.tsx, web/src/OverviewResourcePane.tsx, web/src/OverviewResourceSidebar.stories.tsx, web/src/OverviewResourceSidebar.tsx, web/src/OverviewSidebarOptions.test.tsx, web/src/SidebarContext.tsx, web/src/analytics.ts, web/src/style-helpers.ts
Relates to https://github.com/tilt-dev/tilt/issues/5771#issuecomment-1465038918
This introduces the Proof of Concept collapsible Sidebar mentioned in the linked comment.
=> web: sidebar collapse/expand toggle

internal/controllers/core/dockercomposelogstream/project.go, internal/controllers/core/dockercomposelogstream/project_test.go, internal/controllers/core/dockercomposelogstream/reconciler.go, pkg/webview/view.pb.go
the k8s api infra really wants all fields to be public
=> dockercomposelogstream: fix a panic in DeepEqual

internal/tiltfile/docker.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go
this check is vestigial from the days when we didn't always normalize the path correctly. now that we use the Go parser, i feel more confident in this.
fixes https://github.com/tilt-dev/tilt/issues/6097
=> tiltfile: handle docker compose build urls correctly

web/src/OverviewActionBar.tsx, web/src/OverviewTableColumns.tsx, web/src/links.test.tsx, web/src/links.ts
fixes https://github.com/tilt-dev/tilt/issues/6080
=> web: display 0.0.0.0 as the current window hostname

integration/ignores/.dockerignore, integration/ignores/topdir/subdir/src.txt, integration/ignores_test.go, internal/build/docker_builder.go
the sync protocol should always send over the directory file info when it sends over files in its subtree, even if the directory path itself is marked as ignored
fixes https://github.com/tilt-dev/tilt/issues/6102
=> build: adjust file sync server

internal/container/ignore.go, internal/tiltfile/tiltfile_state.go
Currently Istio container logs are ignored, this adds the same functionality for Linkerd
=> Adds additional exclusions for linkerd logs in addition to Istio

internal/cli/down.go, internal/controllers/core/kubernetesapply/reconciler.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go
before this change, force refresh would delete, then wait for 30s for the delete to finalize. if the delete timeout failed, the force refresh would ignore it and continue applying resources as if nothing had happened.
after this change, force refresh does an asynchronous deletion. When it applies, it checks if the resource is still in the delete phase, and waits for the delete to finish before continuing the apply.
I think this is likely to be a lot more robust and better for parallelization (since now, deletes can happen in parallel with image builds).
Fixes https://github.com/tilt-dev/tilt/issues/6048
=> k8s: adjust how tilt handles two-step deletes

internal/controllers/core/cmdimage/reconciler.go
this ensures that a ForceApply doesn't modify the internal data structures during reconcilation
Mirrors the similar code in the dockerimage reconciler: https://github.com/tilt-dev/tilt/blob/31595cfb3ca178c1f7f36b24f0f935068c838398/internal/controllers/core/dockerimage/reconciler.go#L60
fixes https://github.com/tilt-dev/tilt/issues/6120
=> cmdimage: reconcile() should hold the lock

internal/engine/dockerprune/docker_pruner.go, internal/engine/dockerprune/docker_pruner_test.go, internal/store/engine_state.go
So that docker pruner will run when the manifest only includes custom builds.
More details in #6131
Related to #4023
=> Include CustomBuild in HasBuild condition

.circleci/config.yml, build.toast.yml, scripts/build-tilt-releaser.sh, scripts/release.Dockerfile
Before this change, we did all our own cross-compilation.
After this change, we pull the cross-compiling logic from a shared image. Loosely based on the Compose approach.
Does not yet switch to go 1.20 by default.
=> circleci: use a go 1.20 release image

scripts/release.Dockerfile
Upgrade GoReleaser to v1.18.2.
- https://github.com/tilt-dev/tilt/issues/6151
To resolve the following warning and build prebuilt binaries for darwin/arm64.
```
• DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```
I confirmed the warning was resolved using GoReleaser v1.18.2.
- https://github.com/tilt-dev/tilt/issues/6151#issuecomment-1611322177
=> chore: upgrade GoReleaser to v1.18.2

.circleci/config.yml, build.toast.yml, scripts/release-ci.sh
To resolve the warning of GoReleaser v1.18.2.
```
• DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
```
https://goreleaser.com/deprecations#-rm-dist
⚠️ This pull request needs to update the Docker image `docker/tilt-ci` because goreleaser v1.6.3 doesn't support this option.
https://github.com/tilt-dev/tilt/pull/6152 upgraded GoReleaser v1.18.2 in Dockerfile, so we need to release a new Docker image and update image tags.
https://github.com/tilt-dev/tilt/blob/afb1422a3bd17388b6dd0f68d156dba16f352bfb/build.toast.yml#L2
https://github.com/tilt-dev/tilt/blob/afb1422a3bd17388b6dd0f68d156dba16f352bfb/.circleci/config.yml#L141
=> chore: replace GoReleaser's deprecated option `--rm-dist` to `--clean`

internal/engine/upper_test.go
asserts should never be in goroutines, because we
expect errors during TearDown
=> test: remove assert from a goroutine

internal/watch/notify_test.go, internal/watch/watcher_darwin.go
before this change, we would ignore on linux and windows, but emit events on linux
fixes https://github.com/tilt-dev/tilt/issues/6160
=> watch: ignore the watched dir on all platforms

web/src/OverviewTableStatus.tsx, web/src/SidebarIcon.test.tsx, web/src/SidebarIcon.tsx, web/src/SidebarItemView.tsx
the tooltip often shows the names of resources that the build is waiting on, so it's useful to make the hover target a bit bigger.
=> web: show the build tooltip over the build bar, not just the status icon

internal/k8s/client.go, internal/k8s/client_test.go
fixes https://github.com/tilt-dev/tilt/issues/6166
=> k8s: infer endpoints for NodePort service on Docker Desktop

web/src/OverviewLogPane.stories.tsx, web/src/OverviewLogPane.test.tsx, web/src/third-party/anser/index.js
this still isn't perfect, but at least avoids over-escaping html
a better fix would probably to move to a better ansi-to-html library.
fixes https://github.com/tilt-dev/tilt/issues/6170
=> web: improve handling for links with escape codes in the middle

internal/build/docker_builder.go, internal/docker/client.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go
we really should convert this code to vendor buildx directly like Compose does, but for now this makes the implementations closer together.
=> docker: use errgroup for build session error handling

internal/controllers/core/cmd/execer.go
Implementation of proposal 2 from https://github.com/tilt-dev/tilt/issues/6192
Changing a log message from `Error` to `Debug` to prevent it from being printed twice.
I tested this with the following resource:
* `local` - does not appear to run this code path, the error output from a failure has not changed
* `local_resource` - was printing the error twice, and now only prints it once
* `custom_build` -  was printing the error twice, and now only prints it once
* `k8s_custom_deploy` - still prints the full command and stdout, not sure if it changed
The call graph looks something like this:
```mermaid
flowchart TD
cmd.Controller.Reconcile --> cmd.Controller.runInternal
cmd.Controller.ForceRun --> cmd.Controller.runInternal
cmd.Controller.runInternal --> 
processExecer.Start --> …
```
=> Hide duplicate exit code log message

internal/cloud/cloud_status_manager.go
this should make it slightly easier to replace this endpoint with cloudfront
=> cloud: use GET instead of POST for fetching latest tilt version

internal/controllers/fake/upsert.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontrol/docker_compose_build_and_deployer_test.go, internal/engine/buildcontrol/image_build_and_deployer_test.go
newer versions of the fake client libraries are more strict about this.
=> test: clean up update spec vs status

internal/controllers/core/session/reconciler_test.go, internal/controllers/core/session/status.go
Related to #6231
We've been trying out a new setup where we pre-create environments ahead of time using `tilt up`. Then we pass the environment to `tilt ci` for CI runs. That's been working well, but we've noticed a few Timeout failures where every service in the snapshot has a `RuntimeStatus: ok`. 
It seems like there may be something stuck that isn't visible from the `UIResources` stored in the snapshot.
This PR attempts to expose more detail about why `tilt ci` reached the timeout. I'll do some testing of this internally using this patch to see if we can isolate the problem a bit further.
This message could be too verbose in some cases. Maybe instead of printing all 3 categories it only includes the first category that includes resources? Any retrying resources, then not ready …
=> More verbose timeout reason

internal/dockercompose/client.go, internal/tiltfile/api/__init__.py, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, pkg/apis/core/v1alpha1/dockercomposeservice_types.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go, pkg/openapi/zz_generated.openapi.go
Adds support for compose profiles to both provide a solution for https://github.com/tilt-dev/tilt/issues/6250 and to improve the integration with docker compose.
The PR which changed the previous functionality from compose-go between `v1.6.0` and `v1.18.4` is most likely https://github.com/compose-spec/compose-go/pull/359.
=> dockercompose: support compose profiles

scripts/release-ci.sh
this got accidentally removed
in https://github.com/tilt-dev/tilt/pull/6241
when i removed the publish step
=> scripts: add build-js to release process

internal/cli/cli.go
this has been noticed in a few places, including
https://github.com/tilt-dev/tilt/issues/6265
all users of controller-runtime now need to set a default logger
=> cli: send controller-runtime logs to /dev/null

integration/analytics_test.go, integration/dc_fixture_test.go, internal/cli/args_test.go, internal/cli/edit_test.go, internal/cli/get_test.go, internal/docker/client_test.go, internal/tiltfile/os/os_test.go, internal/tiltfile/tiltfile_test.go, internal/watch/notify_test.go
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
=> test: use `t.Setenv` to set env vars in tests

integration/job_fail/Tiltfile, integration/job_fail/app.dockerfile, integration/job_fail/app.yaml, integration/job_fail/db-init.dockerfile, integration/job_fail/db-init.yaml, integration/job_fail/db.dockerfile, integration/job_fail/db.yaml, integration/job_fail_test.go, integration/job_reattach/Tiltfile, integration/job_reattach/app.dockerfile, integration/job_reattach/app.yaml, integration/job_reattach/db-init.dockerfile, integration/job_reattach/db-init.yaml, integration/job_reattach/db.dockerfile, integration/job_reattach/db.yaml, integration/job_reattach_test.go, internal/controllers/core/session/conv.go, internal/controllers/core/session/reconciler_test.go, internal/controllers/core/session/status.go
fixes https://github.com/tilt-dev/tilt/issues/6272
History of this change:
- we used to have a very naive definition of "Ready"
- callers of the runtime status API had hacks to look at Job pods to determine completeness (https://github.com/tilt-dev/tilt/pull/4367)
- later, we changed it to have a more sophisticated definition, so that Jobs only count as 'ready' when they're complete. (https://github.com/tilt-dev/tilt/pull/5013)
- we forgot to remove the old caller hacks :grimace:
in any case, i added a bunch of tests, since we need more job integration tests anyway.
=> session: ensure 'tilt ci' exits properly when reattaching to jobs

internal/tiltfile/files.go
We have a few [local](https://docs.tilt.dev/api.html#api.local) commands that run from the `Tiltfile` before starting resources.  We use these commands to output kubernetes yaml that is passed to [k8s_yaml](https://docs.tilt.dev/api.html#api.k8s_yaml). These commands have rather verbose stdout (thousands of lines of yaml), so it's important for us to run these with `quiet = True`. When one of these commands fail, the stderr is also relatively verbose, it will contain multiple lines to help the user understand why it failed and where the problem occurred. 
We've noticed that it can be difficult to read these multi-line error messages because they are printed using `%q`. This escapes backslashes and replaces newlines with `\n`. For example:
```
stderr: "\nFailed to do some thing:\n at …
```
=> Improve output of multi-line stderr from local command

internal/cli/klog.go, internal/cli/klog_test.go, internal/cli/up.go
i don't think these logs have ever caught a real problem, and are often confusing / inscrutable. they're really meant for people writing k8s controllers, and i don't think they make sense to show to tilt users.
=> cli: give up and suppress klog output by default

internal/cli/alpha.go, internal/cli/shell.go, internal/controllers/core/kubernetesdiscovery/portforwards.go
designed to interoperate with the new `kubectl shell`, but fallback to kubectl exec if the container supports it.
Future work:
- use with Docker Compose
- add a terminal to the tilt UI
=> cli: add 'tilt alpha shell' for creating a shell into a container

internal/dockercompose/client.go
This solves the issue I reported in #6322 by adding `--profile ___` to the `docker compose up` command
=> dockercompose: fix profiles failing to start (#6322)

internal/store/engine_state.go, internal/store/engine_state_test.go, internal/tiltfile/api/__init__.py, internal/tiltfile/docker_compose.go, pkg/model/docker_compose_target.go
There was a suggestion in #6270 to suppress the "http://localhost:${port}" links that get added automatically when using docker_compose. I liked the idea, so I took a swing at implementing this.
=> dockercompose: Add ability to suppress automatic links in UI (#6270)

.circleci/config.yml, scripts/release.Dockerfile
=> scripts: install buildx in the release image

.circleci/config.yml
=> circleci: update tilt-extensions to go 1.21

integration/onedc/docker-compose.yaml, integration/onedc_test.go
compose v2 vs v1 changed the name of the
image being built...though it's not totally
clear to me why this makes the test
flakey rather than failing outright.
=> integration: fix flaky docker compose test

internal/tiltfile/docker_compose.go, internal/tiltfile/docker_compose_test.go
i don't think this affects anything in practice!
But it mostly helps ensure tests are deterministic.
=> tiltfile: make docker compose dependency order deterministic

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go
This solves the issue I reported in #6325 by modifying the loop in the `renameDCService` function to also patch `s.dc[projectName].services[n].ServiceConfig.DependsOn[name]` and `s.dc[projectName].services[n].Options.resourceDeps[name]`
I also made some temporary local variables because there was a lot of repeated `s.dc[projectName]` and `s.dc[projectName].services` and it was hurting readability, especially after I added the changes to the loop
=> dockercompose: fix dc_resource new_name parameter causing depends_on problems (#6325)

.circleci/Dockerfile, .circleci/Dockerfile.integration, .circleci/config.yml
compose 2.24 had some network flakyness
problems; our ci is also having network
flakyness problems; i'm hoping this will
fix them.
=> circleci: upgrade compose to 2.25

internal/build/docker_builder.go, internal/cli/docker.go, internal/cli/doctor.go, internal/controllers/core/cluster/reconciler.go, internal/controllers/core/tiltfile/reconciler.go, internal/docker/client.go, internal/docker/exploding.go, internal/docker/fake_client.go, internal/docker/switch.go
this ensures that if the Docker daemon
is dead or not responding, it doesn't
block tiltfile execution.
now that we have reconcilers that are
checking the cluster status, i think this
is safer than it used to be.
fixes https://github.com/tilt-dev/tilt/issues/5841
=> docker: remove ping from boot sequence

.circleci/Dockerfile, .circleci/Dockerfile.integration, .circleci/config.yml, Dockerfile.toast, build.toast.yml, go.mod, scripts/protobuf-helper.dockerfile, scripts/release.Dockerfile, scripts/update-codegen.sh
=> circleci: update to go 1.22

internal/docker/env.go, internal/docker/env_test.go
link the docker context and kubernetes
context to the same docker image store
when using colima/linux socket conventions
=> docker: colima/linux support

internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go
fixes https://github.com/tilt-dev/tilt/issues/6369
i think there's an underlying starlark bug here,
since it's supposed to be marking this as optional
implicitly, and the enforcement of optionality
seems to be buggy.
=> tiltfile: explicitly mark echo_off as optional

internal/tiltfile/api/__init__.py
- tags doesn't exist
- the order of args was wrong
=> docs: fix some bugs in local_resource docs

internal/docker/env.go, internal/docker/env_test.go
fixes https://github.com/tilt-dev/tilt/issues/6394
=> docker: update docker-desktop socket check

internal/tiltfile/helm.go, internal/tiltfile/helm_test.go
`helm version` doesn't necessarily return a string with `v` in the prefix, as it depends how it's packaged and bundled. For instance when running helm with [pkgx.sh](https://pkgx.sh/) (for [pinning tool dependencies](https://docs.pkgx.sh/using-dev/dev)):
```
$ pkgx helm version --client --short
3.15.2
```
(due to https://github.com/pkgxdev/pantry/blob/main/projects/helm.sh/package.yml#L22)
Without this change, tilt fails to parse the version with error:
```
Error in helm: could not parse Helm version from string: "3.15.2\n"
```
This fixes that.
=> tiltfile/helm: handle parsing version strings without `v` prefix

.circleci/config.yml
add a note about circleci decommissioning
the intel runners
=> circleci: remove macos runners

internal/dockerfile/ast.go, internal/dockerfile/ast_test.go
buildkit changed the AST format for the Env command
fixes https://github.com/tilt-dev/tilt/issues/6421
=> dockerfile: bug fix for env parsing

web/src/index.scss
I use Tilt daily.
This is an unsolicited suggestion for the web UI styling. Because the Tilt UI is a dark theme, https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme hints to browsers to apply similar adjustments to the interface. In this case, the change is most notable with the scrollbars.
By default, scrollbars rendered by Chrome for overflowing content are light-themed.
By applying the declaration on the `html` root element, the browser applies a dark theme to the scrollbars on the `body` and the components list.
=> web: use dark color scheme to match UI

internal/store/k8sconv/resource.go, internal/store/k8sconv/resource_test.go
ensures that if one JobSet
has two jobs, we track all the pods.
fixes https://github.com/tilt-dev/tilt/issues/6383
=> kubernetesdiscovery: fix jobset tracking

internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go
before this change, if you were deploying
to both a DockerCompose engine and a Kube
cluster, we sometimes wouldn't correctly
synchronize the cluster connections.
this led to problems where we would try
to deploy before the connection had been
established properly.
fixes https://github.com/tilt-dev/tilt/issues/6453
=> engine: fix a bug in cluster connection checks

internal/controllers/core/cluster/reconciler.go, internal/controllers/core/cluster/reconciler_test.go, internal/xdg/fake.go
- treat failure to write kubeconfigs as a cluster
connection failure
- if runtime dir is not available, write
kubeconfigs in a state dir instead
(spec says that if the runtime dir doesn't exist,
it's up to the implementer to find a better dir,
but isn't opinionated about what dir we use)
=> cluster: bug fixes to kubeconfig gen

internal/controllers/core/kubernetesapply/reconciler.go, internal/controllers/core/kubernetesapply/reconciler_test.go
in theory, we shouldn't even start going down this
codepath if the cluster connection hasn't been established,
so let's make it a hard error and see what happens.
=> kubernetesapply: error if kubeconfig has not been resolved

integration/crd_test.go
crd api routes are deleted async
=> integration: fix a race condition

internal/k8s/client.go, internal/k8s/client_test.go
Update the regular expression used to match the Kubernetes `metadata.annotations: Too long` API error returned when a resource annotation exceeds a maximum size.
The error message changed in Kubernetes `v1.32`: https://github.com/kubernetes/kubernetes/pull/128553
The change of error string caused Tilt's logic to fall back to create or replace the resource to fail:
https://github.com/tilt-dev/tilt/blob/875606fb003e208c3c3fc4e013317c6254258198/internal/k8s/client.go#L574-L583
Updating the regular expression ensures that resources with annotations exceeding the maximum size can still be applied in Kubernetes >= `v1.32`.
Take a large CRD, such as the one in [this Gist](https://gist.github.com/andrew-farries/14f3332ae4bb7d50bc37c71804421ddc) and save it as `install.yaml`.
Create the following …
=> Update `metadata:annotations: Too long` error string detection

internal/controllers/core/podlogstream/podsource.go, internal/controllers/indexer/requeuer.go
prevents race conditions that cause a panic
for more info, see
https://github.com/kubernetes-sigs/controller-runtime/issues/3057
=> controllers: ensure all sources implement fmt.Stringer

scripts/install.ps1
While trying to automate installing tilt, I came across this issue. (I don't have scoop installed)
```powershell
$script:ErrorActionPreference = 'Stop'
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.ps1'))
```
throws the error
```
Line |
14 |  if (Get-Command "scoop" 2>$null) {
|      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The term 'scoop' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
This change prevents the scoop check from throwing an error while also allowing me to stop the installation if it throws a real error.
=> Fix powershell install crashing when $script:ErrorActionPreference='Stop' and Scoop not installed

internal/controllers/core/filewatch/controller.go, internal/controllers/core/filewatch/controller_test.go
Fixes #5902 
I was having the same issue described in #5902 where when using filesystem triggers to add or remove resources, it would sometimes race and leave the Tiltfile in the pending status without the most recent state.
I believe I successfully tracked this down to the filewatch controller when reconciled can replace the watcher object with a new configuration, but doesn't preserve previous file events when doing so. This can then race with the Reconcile on the tiltfile to miss that there is a pending filesystem change and instead see an empty list of filesystem changes (https://github.com/tilt-dev/tilt/blob/59f9aa24c86dc5302772c61905275fd90675596f/internal/controllers/core/tiltfile/reconciler.go#L235-L240). The Tiltfile reconciler then does not trigger a subsequent build.
=> fix (Tiltfile) stuck in pending state

internal/docker/client.go, internal/docker/client_test.go, internal/docker/env.go
i think this feature was removed from microk8s
years ago and we no longer need to support it.
fixes https://github.com/tilt-dev/tilt/issues/6494
=> docker: remove support for building to microk8s docker socket

internal/k8s/exec.go
In version 1.31, Kubernetes switched from SPDY to WebSockets for streaming ([blog post](https://kubernetes.io/blog/2024/08/20/websockets-transition/)).
For clusters where SPDY is unavailable (e.g., the Kubernetes API server is accessed through an edge proxy that doesn't support SPDY), the `exec` operation must use WebSockets.
A possible solution for this would be to use a WebSocket Stream Executor by default and fall back to a SPDY Stream Executor when WebSocket based streaming is unavailable. (this also aligns with what [`kubectl exec`](https://github.com/kubernetes/kubectl/blob/316ed014ab225ba07735ebc18e05dca602bcaf5c/pkg/cmd/exec/exec.go#L138) currently does)
I also replaced `Executor.Stream` with `Executor.StreamWithContext` because the former is deprecated.
(A similar solution could …
=> k8s: add websocket support to exec

internal/controllers/core/tiltfile/reducers.go, internal/engine/buildcontrol/build_control.go, internal/engine/buildcontrol/build_control_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/hud/view.go, internal/hud/view_test.go, internal/hud/webview/convert_test.go, internal/store/buildcontrols/reducers.go, internal/store/engine_state.go, internal/store/engine_state_test.go
before this PR, we kept a map of recent file changes,
and deleted from the map when the changes were consumed.
this creates race conditions if the events are processed
in a different order than the changes, e.g.,
if a "consumed" event at 12:02 is processed before
the file change event at 12:01.
after this PR, we record both the file change time
and the consumed time, then compare them to determine
if the file change is still pending.
=> store: update how we model file changes

internal/k8s/portforward.go, internal/k8s/portforward/doc.go, internal/k8s/portforward/fallback_dialer.go, internal/k8s/portforward/fallback_dialer_test.go, internal/k8s/portforward/portforward.go, internal/k8s/portforward/portforward_test.go, internal/k8s/portforward/tunneling_connection.go, internal/k8s/portforward/tunneling_connection_test.go, internal/k8s/portforward/tunneling_dialer.go, internal/k8s/portforward_test.go, internal/testutils/context.go
tilt has a fork of the client-go portforward
package that's better integrated with tilt's
logging and error handling.
this PR rebases the package on top of
the current version of client-go (v0.32)
adds support for websocket-based portforwards
fixes issue #6445
=> k8s: rebase portforward fork

internal/cli/docker_prune.go, internal/controllers/core/tiltfile/api.go, internal/controllers/core/tiltfile/reconciler_test.go, internal/engine/upper_test.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/tiltfile_test.go, pkg/model/manifest.go
if a base image is used in ANY manifest,
it needs to be pushed in all manifests.
Otherwise the caching system will get confused.
fixes issue #6486
=> tiltfile: fix a bug where sometimes a base image wasn't pushed

Makefile, internal/cli/ci.go, internal/cli/flags.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/buildcontrol/wire_gen.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/hud/log_filter.go, internal/hud/log_filter_test.go, pkg/webview/view.pb.go, toast.yml
- create custom wire types
- allow multiple resource filters
- remove legacy wire gen
=> cli: tweak how new log flags are injected

internal/cli/ci.go, internal/cli/flags.go, internal/cli/logs.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/hud/log_filter.go, internal/hud/server/logs_reader.go, internal/hud/server/logs_reader_test.go, internal/hud/terminal_stream.go
- ensure they both let you filter by level/source
- ensure they both print the prefix when necessary
=> cli: reconcile `tilt up` and `tilt logs`

internal/controllers/core/liveupdate/reconciler.go
this is a fun deep dive into the history of Tilt
and Kubernetes file-syncing
When Tilt was first written, there weren't well-established
conventions for how to sync a file to a cluster. There
were disagreements about whether this was a "user-space"
operation or a "privileged" operation, and what permissions
a file should get when it's written.
Over the years, all that's settled down: the k8s community
has invested a lot in having a robust, streaming exec
endpoint, and using that for all file copying.
(a similar convergence has happened on the container runtime
side -- everything has consolidated on the docker exec
endpoint, rather than separate file-copying endpoints)
with that in mind, let's simplify things even more
and use kubectl exec endpoint, even when we have direct
access to the …
=> liveupdate: always update k8s clusters with kubectl exec

internal/kustomize/dependencies.go, internal/kustomize/dependencies_test.go
When calling `kustomize(<directory>)` in a Tiltfile, the directory is watched as well as any paths the Kustomization includes. This doesn't currently include components, so Kustomizations that include [components](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md) don't trigger a reload of the Tiltfile and the Kustomization when files in those components change.
This PR adds the `components:` field of a Kustomization to the list of paths `dependenciesForKustomization` will inspect.
=> When calculating Kustomize dependencies, include components

internal/cli/down.go, internal/dockercompose/client.go, internal/dockercompose/fake_client.go
Add '--delete-volumes' option to `tilt down` that removes volumes for docker compose projects only.
`docker compose down` does not remove internal volumes without a '-v|--volumes' option. This change adds that option if `tilt down` is called with an additional '--delete-volumes' option.
Tested and working as expected.
=> Docker delete volumes
