cmd/tilt/main.go
internal/cli/up.go

whoooops, fix broken import

---

.circleci/config.yml
Makefile

0e0276da04e264b6a82c5c2b71285f652563b64a (2018-08-08 13:05:12 -0400)
circleci: add config

circleci: add config

---

.circleci/config.yml
internal/build/docker_test.go

Hello @nicks,
b801aed773a40fca6a1c34851344a92cdb6065ff (2018-08-10 15:06:04 -0400)
build: run tests on circleci
63783402e3bb7839cacdc91b39b64b85a5b8b310 (2018-08-10 14:54:21 -0400)
docker: negotiate api version up to 1.30

build: run tests on circleci

---

internal/build/docker.go
internal/build/docker_test.go

Please review the following commits I made in branch maiamcc/multimount:
a162f7491a4e3e6f9f45ab06e20e82927b594bc6 (2018-08-10 16:31:19 -0400)
tests hooray
28ef17c30d62930f09742f1e9a75b707ed6cc33c (2018-08-10 16:18:45 -0400)
close tar writer properly
a347c36e883a39367a6df6e4481ad7a137d69574 (2018-08-10 16:17:45 -0400)
build: support multiple mounts (todo: tests)

build: support multiple mounts

---

internal/build/docker_test.go

Please review the following commits I made in branch maiamcc/fixtest:
75db6011daf83dc423fe305a976f76c7b1fb5115 (2018-08-10 17:16:45 -0400)
build: fix tests, and better output for assert

build: fix tests, and better output for assert

---

internal/build/docker.go
internal/build/docker_test.go
internal/tiltd/tiltd_server/tiltd.go

Please review the following commits I made in branch maiamcc/tests-refactor:
2353f14efc33c7e609e0c014340d34a83bba1048 (2018-08-13 16:10:39 -0400)
build/test: refactor tests, skeleton for entrypoint

build/test: refactor tests, skeleton for entrypoint

---

internal/build/docker.go
internal/build/docker_test.go

Please review the following commits I made in branch maiamcc/entrypoint:
595e65ab0d7927684a35e45a532527bc1ad2da20 (2018-08-13 17:05:08 -0400)
build: add entrypoint to docker image

build: add entrypoint to docker image

---

Makefile
internal/build/docker.go
internal/build/docker_test.go
internal/image/history.go
internal/image/history_test.go
internal/tiltd/tiltd_server/tiltd.go

Please review the following commits I made in branch nicks/history:
38cc49c037efa4f771ff1693a270dcab2bb45eba (2018-08-14 14:31:04 -0400)
image: add a small image tracker

image: add a small image tracker

---

internal/build/docker.go
internal/build/docker_test.go
internal/tiltd/tiltd_server/tiltd.go

With this PR our YAML has the correct image and the container can pull the image from GKE.

build: get digest from push output

---

internal/build/docker_test.go

Hello @nicks,
0f6d7419bcbbec93cd13b8c0655bdb1f3aa22fbd (2018-08-15 11:43:23 -0400)
tests: fix a minor race condition

tests: fix a minor race condition

---

internal/build/incremental.go

as discussed with @dbentley and @landism

build: incremental build interface

---

internal/build/docker.go
internal/build/docker_test.go

Please review the following commits I made in branch nicks/assert:
455544fde43fc576d090038d0f4c8bd832541a86 (2018-08-15 17:35:58 -0400)
build: Add a more robust assert function

build: Add a more robust assert function

---

internal/image/fs.go
internal/image/history.go
internal/image/history_test.go

Please review the following commits I made in branch nicks/add:
d9a2ac5719ab1a0a7398a518752ab00c0acd3fb4 (2018-08-15 18:13:56 -0400)
image: remove savetofs in favor of incremental add

image: remove savetofs in favor of incremental add

---

internal/build/docker_test.go
internal/model/service.go

Duplicates #72 but too many merge conflicts, so started fresh.

model: helper func to make shell cmd's (duplicate PR)

---

internal/build/container.go
internal/build/docker.go
internal/build/docker_test.go

Please review the following commits I made in branch nicks/asserts2:
b3e9c6f6776e70fe312dea72d36b320fe192f65c (2018-08-15 18:20:10 -0400)
build: response to comments and spec references

build: response to comments and spec references

---

internal/build/docker_test.go

Please review the following commits I made in branch nicks/not:
de4ef6cc6ece40619307d0a88b1750f5f032ffee (2018-08-16 11:28:11 -0400)
build: add an assert that files are missing from a container

build: add an assert that files are missing from a container

---

.circleci/config.yml
internal/build/docker_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/macos:
1d04efc6dfd13f22d8c32a57b4df344a12ef5439 (2018-08-16 15:04:01 -0400)
circleci: add macos

circleci: add macos

---

internal/build/docker_test.go

Please review the following commits I made in branch maiamcc/prettify-tests:
741c9285d5b4c84a3b380d0733993b3703c50a1f (2018-08-16 15:18:29 -0400)
build/test: test prettification
bfdf19c6361cdb3fd3454e84a6540ada154c7eb9 (2018-08-16 15:05:06 -0400)
build: inc. build doesn't take its own entrypoint, preserves entrypoint of existing img
fb7b5b1037d2b626ea0771c92c3f8293d8afce31 (2018-08-16 14:56:09 -0400)
wip

build/test: test prettification

---

internal/engine/build_and_deployer.go
internal/engine/upper.go
internal/proto/server_adaptor.go
internal/service/manager.go
internal/service/manager_test.go

I haven't tested this end-to-end yet but wanted to get your eyes on it

engine: build and deploy from existing

---

internal/build/docker_test.go
internal/ospath/ospath.go
internal/ospath/ospath_test.go
internal/test_utils/temp_dir_fixture.go
internal/testutils/temp_dir_fixture.go

Hello @nicks, @dbentley,
Please review the following commits I made in branch maiamcc/ospath-child:
7226680a2c994269bc392e520daa04816f6b380d (2018-08-16 18:40:06 -0400)
add test
847c13a1348efa7f3005a961011c60bb4b0b7160 (2018-08-16 18:21:55 -0400)
test util for TempDirFixture, redo docker_test with it
10c359255fa762c153e755a5b2223b731ccd37b6 (2018-08-16 18:21:37 -0400)
add ospath.child

ospath: port ospath.child func from windmill

---

internal/build/docker.go
internal/build/docker_test.go
internal/build/file_ops.go
internal/build/file_ops_test.go
internal/build/tar.go
internal/logger/logger.go
internal/model/service.go
internal/testutils/context.go

Hello @nicks, @landism, @jazzdan,
Please review the following commits I made in branch maiamcc/file-ops:
e0f5ef325698549abb141d0907424d9761fd9fdf (2018-08-17 11:59:52 -0400)
build: given list of changed files, figure out where on the container they go
eb827b810859cb5a6b27e5a529f23d9f994716de (2018-08-17 11:16:42 -0400)
wip

build: given list of changed files, figure out where on the container they go

---

Makefile
internal/build/docker_benchmark_test.go
internal/build/docker_test.go
internal/testutils/temp_dir_fixture.go

Please review the following commits I made in branch nicks/benchmark:
9b359d0a689d78b0ba8e5eab935af4e9d893b7c8 (2018-08-17 17:07:05 -0400)
build: add a benchmark

build: add a benchmark

---

internal/build/docker.go
internal/build/docker_test.go
internal/build/path_mapping.go
internal/build/path_mapping_test.go
internal/build/tar.go
internal/engine/build_and_deployer.go
internal/testutils/temp_dir_fixture.go

Please review the following commits I made in branch maiamcc/add-only-some-files:
4e937f6b4cb0be88b73ea678414d5407b72ea597 (2018-08-17 16:36:58 -0400)
privatize methods, better func names, e2e hookup
f89a57387c1733775e6f5cebed2bb3d7062f357e (2018-08-17 16:20:49 -0400)
selective file add/rm works

build: selective file add

---

internal/build/docker_benchmark_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/build:
13323f85e2d060252a96e5be085ecf75897c8fad (2018-08-20 11:09:14 -0400)
fix the build

fix the build

---

internal/build/docker.go
internal/build/docker_test.go
internal/build/dockerfile.go
internal/build/tar.go
internal/engine/build_and_deployer.go

as suggested by @nicks in https://github.com/windmilleng/tilt/pull/95

build: introduce Dockerfile abstraction

---

internal/build/container.go
internal/build/docker.go
internal/build/pool.go

Please review the following commits I made in branch nicks/comments:
13d0073af11c213e36eaa7efcf963f98d037e33c (2018-08-20 12:58:25 -0400)
response to comments

response to comments

---

internal/build/docker_benchmark_test.go

Please review the following commits I made in branch nicks/iterative:
59f7a42c06c5b4e3e375b4926a165e28a3b93614 (2018-08-20 15:56:16 -0400)
Add a benchmark for BuildDockerFromExisting

Add a benchmark for BuildDockerFromExisting

---

internal/image/fs.go

Please review the following commits I made in branch nicks/close:
01f179e5169df7c8755a5e7b6c1235dff4cf9dd6 (2018-08-20 16:26:46 -0400)
close some files

close some files

---

internal/model/service.go
internal/model/service_test.go

Please review the following commits I made in branch nicks/model:
5bcef8fe6c2e02e987bde0c62c5ab19aa13a1486 (2018-08-20 16:54:19 -0400)
model: fix some minor escaping issues i ran into

model: fix some minor escaping issues i ran into

---

internal/build/docker.go
internal/build/tar.go
internal/engine/build_and_deployer.go
internal/engine/upper.go
internal/image/fs.go
internal/image/history.go
internal/image/history_test.go
internal/proto/server_adaptor.go

note: for some reason cross grpc tracing isn't working. Looking in to that now but I may be at a loss.

tracing: more tracing

---

internal/engine/build_and_deployer.go
internal/k8s/image.go
internal/k8s/image_test.go
internal/k8s/testdata_test.go

Please review the following commits I made in branch nicks/pull:
f8df3bc84321f44401d6cfa6a3eeb3912b0938f4 (2018-08-21 13:38:51 -0400)
k8s: add an api for modifying the container image pull policy

k8s: add an api for modifying the container image pull policy

---

internal/build/docker.go
internal/build/docker_test.go
internal/cli/daemon.go
internal/engine/build_and_deployer.go
internal/engine/upper.go
internal/k8s/env.go
internal/k8s/env_test.go
internal/k8s/image.go
internal/k8s/image_test.go
internal/proto/server_adaptor.go

Hello @jazzdan, @maiamcc, @yuindustries,
Please review the following commits I made in branch nicks/kube:
35fe94ac73de9915d0768ac13443455500f363a7 (2018-08-21 14:30:38 -0400)
engine: don't push to a central registry when using docker-for-mac

engine: don't push to a central registry when using docker-for-mac

---

scripts/timing.py

Please review the following commits I made in branch nicks/timing:
a47f8e6609955e9f205f8010ff6e23ab8786c0ff (2018-08-21 15:44:08 -0400)
timing: raise an exception if tilt fails for some reason

timing: raise an exception if tilt fails for some reason

---

internal/build/docker.go
internal/build/path_mapping.go
internal/build/tar.go

Please review the following commits I made in branch nicks/onefile:
45fed0cb0e76a550bdf08089f9c7686747993ea7 (2018-08-21 16:53:25 -0400)
build: do the whole build in a single ImageBuild call. this should be simpler and perform better

build: do the whole build in a single ImageBuild call. this should be simpler and perform better

---

internal/engine/upper.go
internal/proto/server_adaptor.go
scripts/timing.py

note that process.terminate() will leave an orphan daemon running until we put better signal handling somewhere

timing: benchmark builds from --watch

---

internal/cli/up.go

Please review the following commits I made in branch nicks/errors2:
e4c7e0e49238f737644337a4ce7eed6fb70aa493 (2018-08-22 12:44:29 -0400)
fix an error that was getting dropped on the floor

fix an error that was getting dropped on the floor

---

cmd/tiltdemo/main.go
internal/demo/demo.go

demo: Set up tiltdemo

---

internal/watch/notify_test.go

Please review the following commits I made in branch nicks/watch2:
17e2d9a6d922c3caefb0d5cd970b7de30f2f6ef4 (2018-08-22 15:33:22 -0400)
watch: stop skipping tests

watch: stop skipping tests

---

internal/watch/notify_test.go
internal/watch/watcher_linux.go

Please review the following commits I made in branch nicks/watch3:
23edc4db01f860554ccb87c68bd62ebd74945b60 (2018-08-22 15:49:33 -0400)
watch: fix a segfault on linux

watch: fix a segfault on linux

---

internal/model/service.go
internal/model/service_test.go

Hello @yuindustries, @maiamcc,
Please review the following commits I made in branch nicks/errors:
fa628c42df80e96798e304013e6f0ae2b7202b08 (2018-08-22 12:27:16 -0400)
model: slight improvements to run/entrypoint printing

model: slight improvements to run/entrypoint printing

---

internal/build/docker.go
internal/build/docker_test.go

Please review the following commits I made in branch nicks/tag:
0c9eae20dc621c9bd413410998299ba96d16148c (2018-08-22 16:49:26 -0400)
build: create a tag based on the digest, instead of using a constant tag

build: create a tag based on the digest, instead of using a constant tag

---

internal/build/docker.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/k8s/client.go

Please review the following commits I made in branch nicks/k8s:
7983c2ca67d2e591b7347f3f818fd376cbea4802 (2018-08-23 13:07:05 -0400)
wire: inject a k8s client, in preparation for tests for BuildAndDeployer

wire: inject a k8s client, in preparation for tests for BuildAndDeployer

---

scripts/timing.py

not currently super necessary but we'll probs want this when outputting to csv etc.

timing: get current k8s env

---

internal/watch/watcher_darwin.go

ed2bc70ef0e1eb02b69a0aebd66e5f3f00689d13 (2018-08-23 15:05:09 -0400)
watch: fix more data races on darwin

watch: fix more data races on darwin

---

internal/build/client.go
internal/build/docker.go
internal/build/docker_test.go
internal/build/fake_client.go
internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/testdata_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/model/service.go

Please review the following commits I made in branch nicks/engine:
363aade180ffc9585d70b2b2dde1df85ba07e479 (2018-08-23 16:12:24 -0400)
engine: tests for BuildAndDeployer

engine: tests for BuildAndDeployer

---

internal/watch/watcher_darwin.go

Please review the following commits I made in branch nicks/watch4:
1dfed294fb0055b69712d4972b482f7f6c00d5df (2018-08-24 11:56:47 -0400)
watch: try a slightly different ignore strategy

watch: try a slightly different ignore strategy

---

internal/build/docker.go

build: make spans for relevant steps in Docker output

---

internal/output/outputter.go

tilt: fix pipeline done colors

---

internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/k8s/client.go
internal/k8s/entity.go
internal/k8s/entity_test.go
internal/k8s/serialize.go
internal/k8s/testdata_test.go
internal/k8s/update.go

Please review the following commits I made in branch nicks/job:
2898265f0b4621df89d6a54d3c6249ffe377b482 (2018-08-24 15:23:56 -0400)
k8s: add logic for deleting jobs

k8s: add logic for deleting jobs

---

Dockerfile.base
Tiltfile
internal/build/docker_test.go
internal/k8s/client.go
tilt-test.yaml

38e9e8b4632fe1a79090a2335ef7ebf7132186d2 (2018-08-24 16:17:38 -0400)
tilt: I'm in ur tiltfile, tilting your tilt tests

tilt: I'm in ur tiltfile, tilting your tilt tests

---

scripts/timing.py

Please review the following commits I made in branch nicks/minikube2:
56ce9ebe0ca1990b6d2b01d51fd4ba18ab132919 (2018-08-27 11:39:01 -0400)
add minikube to timing script

add minikube to timing script

---

internal/build/docker.go
internal/build/path_mapping.go
internal/engine/upper.go
scripts/timing.py

also fix bug when fs event contains too many files

timing: add span to missingLocalPaths

---

Gopkg.lock
internal/build/dockerfile.go
internal/build/dockerfile_test.go
internal/build/local_docker.go
vendor/github.com/moby/buildkit/LICENSE
vendor/github.com/moby/buildkit/frontend/dockerfile/command/command.go
vendor/github.com/moby/buildkit/frontend/dockerfile/parser/line_parsers.go
vendor/github.com/moby/buildkit/frontend/dockerfile/parser/parser.go
vendor/github.com/moby/buildkit/frontend/dockerfile/parser/split_command.go

Please review the following commits I made in branch nicks/dockerfile:
9aa2f87e596688407ca1b3b8e0e3a12fa3d03256 (2018-08-27 17:57:14 -0400)
build: improve base dockerfile validation

build: improve base dockerfile validation

---

internal/k8s/entity.go
internal/k8s/entity_test.go

Please review the following commits I made in branch nicks/forward2:
fac11ca66e7d42508e347c3baa3b25841d9365df (2018-08-28 14:23:18 -0400)
k8s: add some code to extract loadbalancers

k8s: add some code to extract loadbalancers

---

internal/engine/build_and_deployer.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/forward:
255e7b31183b0ea9df70eef3990b13bc9bc21074 (2018-08-28 14:03:33 -0400)
engine: refactor build_and_deployer. attach k8s services to the build token

engine: refactor build_and_deployer. attach k8s services to the build token

---

internal/build/client.go
internal/build/fake_client.go
internal/build/remote_docker.go
internal/build/remote_docker_test.go

Please review the following commits I made in branch maiamcc/remote-builder-steps:
bf6a4f8a504d7e39d50ebdc98a46c8f604f24711 (2018-08-28 16:45:37 -0400)
remote build: exec steps on a running container

remote build: exec steps on a running container

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/wire.go
internal/engine/wire_gen.go

Hello @nicks,
4de9d33817d109447187ec6d755e77c6f5883b0e (2018-08-29 11:51:37 -0400)
wire: regenerate the wire injectors

wire: regenerate the wire injectors

---

.circleci/Dockerfile
.circleci/config.yml
Makefile

Hello @nicks,
b106176a03051e6a031ab31aafdaf31d82c12f02 (2018-08-29 11:58:02 -0400)
Makefile: generate docker container for circleci

Makefile: generate docker container for circleci

---

internal/build/client.go
internal/build/container_updater.go
internal/build/container_updater_test.go
internal/build/fake_client.go
internal/build/image_builder_test.go

Please review the following commits I made in branch maiamcc/restart-container:
c721372ec03b526f3ed00f77b17c38a393b2387d (2018-08-29 12:16:19 -0400)
containerUpdate: restart container

containerUpdate: restart container

---

internal/build/container_updater.go
internal/build/container_updater_test.go

Hello @jazzdan, @nicks
Please review the following commits I made in branch maiamcc/pass-cid:
ac9e9e120e00dda4381c7ee98528563c79f00b91 (2018-08-29 12:29:01 -0400)
containerUpdater: pass containerID instead of attaching pod name to updater
c721372ec03b526f3ed00f77b17c38a393b2387d (2018-08-29 12:16:19 -0400)
containerUpdate: restart container

containerUpdater: pass containerID instead of attaching pod name to updater

---

internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/container_build_and_deployer.go
internal/engine/local_build_and_deployer.go
internal/engine/result.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/token:
218a7675b3b1bb395f36673b3426537f995bb45c (2018-08-29 15:53:49 -0400)
engine: fix bugs in how we pass around build state

engine: fix bugs in how we pass around build state

---

internal/build/image_builder.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/local_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go

Please review the following commits I made in branch maiamcc/more-renames:
14a4dd085486d743f70261c86059cf12eb55edbf (2018-08-29 16:38:33 -0400)
build: rename local -> image

build: rename local -> image

---

internal/build/options.go

a future commit will make a cli flag that will turn buildkit on

build: toggle buildkit on env variable [ch98]

---

Gopkg.lock
internal/build/image_builder.go
vendor/github.com/dustin/go-humanize/.travis.yml
vendor/github.com/dustin/go-humanize/LICENSE
vendor/github.com/dustin/go-humanize/README.markdown
vendor/github.com/dustin/go-humanize/big.go
vendor/github.com/dustin/go-humanize/bigbytes.go
vendor/github.com/dustin/go-humanize/bytes.go
vendor/github.com/dustin/go-humanize/comma.go
vendor/github.com/dustin/go-humanize/commaf.go
vendor/github.com/dustin/go-humanize/ftoa.go
vendor/github.com/dustin/go-humanize/humanize.go
vendor/github.com/dustin/go-humanize/number.go
vendor/github.com/dustin/go-humanize/ordinals.go
vendor/github.com/dustin/go-humanize/si.go
vendor/github.com/dustin/go-humanize/times.go

Looks like this:
```
Starting Tilt…
──┤ Pipeline Starting … ├────────────────────────────────────────
STEP 1/2 — Building from scratch: [blorg.io/blorgdev/blorg-frontend]
→ tarring context
╎ Tar size: 12 MB
→ building image
╎ Step 1/4 : FROM iron/go:dev
╎  ---> bc624028dcfb
╎ Step 2/4 : ADD . /
╎  ---> Using cache
╎  ---> 9e060aa96e39
╎ Step 3/4 : RUN go install github.com/windmilleng/blorg-frontend/...
╎  ---> Using cache
╎  ---> 53ccda54c75e
╎ Step 4/4 : ENTRYPOINT /go/bin/blorg-frontend --backendAddr lb-blorg-be:8080
╎  ---> Using cache
╎  ---> 69d2255e8555
╎ Successfully built 69d2255e8555
[+] Building 0.0s (0/0)
(Done 2.409s)
```

build: print tar size [ch97]

---

internal/build/image_builder.go

Please review the following commits I made in branch nicks/output:
5d068fe1542aa9e2168d0cc52191648af3dbf810 (2018-08-30 14:16:59 -0400)
build: fix broken output when buildkit is off

build: fix broken output when buildkit is off

---

internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/builderror:
56e5368b122584ad009c053740c1e4bb0e1f80a0 (2018-08-30 13:38:04 -0400)
engine: handle error cases properly if the first build failed

engine: handle error cases properly if the first build failed

---

internal/cli/cli.go
internal/cli/daemon.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/browser.go
internal/engine/upper.go
internal/engine/upper_test.go
scripts/timing.py

Please review the following commits I made in branch nicks/browser:
dfdf49cb6b9efecfd4c10ebe29fb64788ca1ddc0 (2018-08-31 11:32:58 -0400)
cli: add a --browser flag that we can turn off in the timing script

cli: add a --browser flag that we can turn off in the timing script

---

internal/engine/upper.go

Hello @nicks,
Please review the following commits I made in branch nicks/browser2:
e691d8b50791697678f30e4f4da2e632ac00dbf0 (2018-08-31 11:59:33 -0400)
engine: fix an uninitialized prop :ahhh:

engine: fix an uninitialized prop :ahhh:

---

internal/build/client.go
internal/build/container.go
internal/build/container_updater.go
internal/build/fake_client.go
internal/build/image_builder_test.go
internal/k8s/client.go

Part of what will replace #229

build: move containerID in to k8s package [ch84]

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/pull:
118bc046b4f3916f0664765e684fd410cf441a26 (2018-08-31 16:27:21 -0400)
circleci: pre-pull the registry

circleci: pre-pull the registry

---

internal/logger/logger.go
internal/output/outputter.go
internal/output/outputter_test.go

Please review the following commits I made in branch nicks/error:
6099819bb544fdb0354bd4039ab5ae01cd815b96 (2018-08-30 17:24:36 -0400)
output: handle multi-line prints, and non-color output

output: handle multi-line prints, and non-color output

---

internal/k8s/client.go
scripts/timing.py

Please review the following commits I made in branch nicks/minikube:
75c6728e4d244e2d48ebcb53f980c8b678a5c27e (2018-09-04 17:39:34 -0400)
minikube: set k8s polling interval to 1s

minikube: set k8s polling interval to 1s

---

internal/build/client.go
internal/build/container_updater.go
internal/build/container_updater_test.go
internal/build/fake_client.go

Please review the following commits I made in branch maiamcc/instrument-container-update:
5a491da725f3abce577762bd692b6fe061994e6f (2018-09-04 18:15:59 -0400)
container updater: better instrumentation

container updater: better instrumentation

---

internal/engine/image_build_and_deployer.go
internal/k8s/image.go
internal/k8s/image_test.go
internal/k8s/testdata_test.go

(if this is the way we want to go)

k8s: remove command from containers [ch120]

---

internal/engine/container_build_and_deployer.go
scripts/timing.py

pending refactor of the blorgly frontend tests (left them till later cuz it'll take me a bit longer).
among other things, this should make it easier to run a single test against multiple services.

timing: refactor to use servantes, Service object; to be smarter about container builds; trigger go builds"

---

internal/build/client.go
internal/build/container_updater.go
internal/k8s/pod.go

Please review the following commits I made in branch maiamcc/more-instrumenting:
306bb95fcce27bca3bdce2c9ef350022ff7f3e3e (2018-09-05 17:39:22 -0400)
build: more instrumenting

build: more instrumenting

---

internal/build/buildkit_printer.go

Please review the following commits I made in branch nicks/test:
1a3b9343405cd71c8a67d608b53902feac647389 (2018-09-05 18:25:45 -0400)
build: track the order of keys so that iteration order is consistent

build: track the order of keys so that iteration order is consistent

---

internal/engine/container_build_and_deployer.go

Please review the following commits I made in branch maiamcc/turn-on-container-build:
9b3dda4e73fc53f3aab8e2ef6ef0730a473e143a (2018-09-06 11:41:35 -0400)
build: turn on container build by default

build: turn on container build by default

---

internal/cli/up.go
internal/engine/container_build_and_deployer.go

Please review the following commits I made in branch maiamcc/tag-build-by-service:
22e9fcdb6face310615310f27f26e035892d3d69 (2018-09-06 11:54:25 -0400)
tracing: tag build spans with service name

tracing: tag build spans with service name

---

internal/build/container_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/test2:
f14cee9ad6d7595ec06bd3b344391a944883ebbc (2018-09-07 12:52:07 -0400)
build: fix a brittle test

build: fix a brittle test

---

internal/dockerignore/ignore.go
internal/engine/up_watch.go
internal/git/gitignore.go
internal/ignore/composite.go

Also moved the composite repo service out in to the ignore package.

engine: use dockerfile ignore

---

internal/build/client.go
internal/build/container_test.go
internal/build/dockerfile.go
internal/build/fake_client.go
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/build/image_reaper.go
internal/build/label.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/wire.go
internal/engine/wire_gen.go

Please review the following commits I made in branch nicks/reaper2:
2d46aaadb28d82aea4d7991e3b5d7fc628b44e38 (2018-09-07 12:44:53 -0400)
build: add a framework for deleting images

build: add a framework for deleting images

---

internal/build/container_updater_test.go
internal/engine/container_build_and_deployer.go
internal/engine/image_build_and_deployer.go
internal/engine/testdata_test.go
internal/ignore/tester.go
internal/model/service.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicksantos/ch140/add-data-structures-to-model-service-to-support:
241cbeae8c84275d8b3cf3147bdb0a9d82365e4a (2018-09-10 14:50:48 -0400)
model: define a model for conditional steps

model: define a model for conditional steps

---

internal/build/container_test.go
internal/build/image_builder_test.go
internal/build/image_reaper.go

Please review the following commits I made in branch nicks/reaper4:
c43746fc7768fb39adc4d519aa57e0b417aab513 (2018-09-07 16:41:10 -0400)
build: delete images when the test is done

build: delete images when the test is done

---

internal/dockerignore/ignore.go
internal/dockerignore/ignore_test.go
internal/engine/up_watch.go
internal/git/gitignore.go
internal/model/matcher.go

Please review the following commits I made in branch nicks/ch141/match:
fe7d63377fc01837e6ce56d369751935c2b2112e (2018-09-10 18:37:27 -0400)
model: Add AsMatchPatterns(), so i can include these in docker ADD statements

model: Add AsMatchPatterns(), so i can include these in docker ADD statements

---

internal/engine/image_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/model/service.go
internal/tiltfile/skylarkTypes.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ref:
d09fc89477280722dbd3c84b1912f7a9b568c201 (2018-09-10 12:38:07 -0400)
tiltfile: detect invalid dockerfile tags sooner

tiltfile: detect invalid dockerfile tags sooner

---

internal/build/client_benchmark_test.go
internal/build/container_test.go
internal/build/docker_benchmark_test.go
internal/build/image_builder.go
internal/engine/image_build_and_deployer.go

Please review the following commits I made in branch nicks/ch141/cond:
77fe3f97344a06355203ca43e679b3528b9e8169 (2018-09-11 11:39:13 -0400)
build: rejigger the imagebuilder interface so that we can add the conditional steps code
there should be no functional changes in this pr

build: rejigger the imagebuilder interface so that we can add the conditional steps code

---

.gitignore
Dockerfile.synclet
cmd/synclet/main.go
deploy_synclet.py
synclet/Dockerfile
synclet/deploy_synclet.py
synclet/deploy_utils.py
synclet/populate_config_template.py
synclet/synclet-conf.template.yaml

fyi the symlinking scheme is so that you can call ./deploy_synclet from the project root and the dockerfile can pull in the right stuff but you don't have synclet code cluttering the project root too. there's probably a better way but this works :)

synclet: script to deploy synclet, dummy app

---

internal/build/image_builder_test.go
internal/build/tar.go
internal/build/tar_test.go

Please review the following commits I made in branch nicks/containers:
46e7718847ec01560ace895c36b40041acf52525 (2018-09-11 15:56:32 -0400)
build: fix some bugs in tarballs and tarball tests

build: fix some bugs in tarballs and tarball tests

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go

Please review the following commits I made in branch maiamcc/synclet-builder-skeleton:
e943e3d2aa1bc53204cf09c2526a6f9a52f20e97 (2018-09-11 14:35:53 -0400)
engine/synclet: skeleton for syncletBuildAndDeployer

engine/synclet: skeleton for syncletBuildAndDeployer

---

internal/build/dockerfile.go

Please review the following commits I made in branch nicks/rmpaths:
ed5da8a4a4245a5a3f9cff5554218a71be9118e4 (2018-09-11 18:26:05 -0400)
build: simplify rmpaths a bit; i was getting confused by this

build: simplify rmpaths a bit; i was getting confused by this

---

internal/build/container_test.go
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/build/path_mapping.go

Please review the following commits I made in branch nicks/ch141/df:
a779c6e8effb37f4bc1119d2d58a1753ca9ca256 (2018-09-11 19:10:29 -0400)
build: construct dockerfile for run triggers

build: construct dockerfile for run triggers

---

internal/build/path_mapping.go

Just removes the `foundMount` variable.

build: simplify fileToPathMapping

---

internal/build/container_test.go
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/build/path_mapping.go

Hello @nicks,
Please review the following commits I made in branch nicks/ch141/unrevert:
9c074e6e03c0706729212aca41d66e4a208266a7 (2018-09-12 13:03:39 -0400)
Revert "Revert "build: construct dockerfile for run triggers (#301)" (#302)"
This reverts commit 590e322ed1f7759f2072db917eda47f857e8b157.

Revert "Revert "build: construct dockerfile for run triggers (#301)" (#302)"

---

internal/build/container_updater.go
internal/build/image_builder.go
internal/build/path_mapping.go
internal/build/tar.go
internal/build/tar_test.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/synclet/client_adapter.go
internal/synclet/fake_client.go
internal/synclet/synclet.go

Please review the following commits I made in branch maiamcc/hook-up-synclet-bad:
b64880affa353c65d5c3c6c596ac4d51b82e1512 (2018-09-12 12:43:14 -0400)
synclet: hook up SyncletBuildAndDeploy
[ch219]

synclet: hook up SyncletBuildAndDeploy

---

internal/build/image_builder.go
internal/build/image_builder_test.go

Please review the following commits I made in branch nicks/bugs:
ebfdff00790a6a7751e5297d14ce989456689776 (2018-09-12 14:33:05 -0400)
build: fix a bug where we were duplicating steps

build: fix a bug where we were duplicating steps

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go

6c3d3099a802508a0094ffe5d5be9c63dc6bc4da (2018-09-12 15:54:55 -0400)
wire: clean up injections a bit

wire: clean up injections a bit

---

internal/engine/build_and_deployer.go
internal/engine/synclet_build_and_deployer.go

Please review the following commits I made in branch maiamcc/get-container-id:
60a21740b115410496c03b6597452a5872fcfbaa (2018-09-12 16:18:14 -0400)
synclet: tilt-side hookup for GetContainerId

synclet: tilt-side hookup for GetContainerId

---

internal/engine/upper.go
internal/summary/summary.go

Merrily dumping more info here in the Summary section!

output: Summary section has K8s Info

---

internal/synclet/synclet.go

[ch186] uhh can't actually test this b/c i don't have port forwarding o_0 but i thiiiink it works?

synclet: build steps

---

internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go

Please review the following commits I made in branch nicks/envs:
1c4c7b80eb4b50be80eb6ee11d579d226ef5c02e (2018-09-13 11:43:21 -0400)
engine: change wiring a bit, to make it easier to support different cluster configs

engine: change wiring a bit, to make it easier to support different cluster configs

---

Gopkg.lock
README.md
internal/cli/analytics.go
internal/cli/cli.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/cli.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/opt.go

Please review the following commits I made in branch nicks/ch224/analytics:
06a00ac05f5b473851f53423985ad4b5a255b6e7 (2018-09-12 16:37:53 -0400)
cli: add analytics

cli: add analytics

---

internal/cli/cli.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/up_watch.go
internal/engine/up_watch_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/model/manifest.go
internal/service/creator.go
internal/service/manager.go
internal/service/manager_test.go
internal/summary/summary.go
internal/tiltfile/tiltfile.go

Please review the following commits I made in branch nicks/ch55/service:
01a747d1f81d58bd74982187906f3882d27832bd (2018-09-13 14:56:44 -0400)
partial rename from Service -> Manifest for groups of k8s objects

partial rename from Service -> Manifest for groups of k8s objects

---

internal/engine/build_and_deployer.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/result.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch maiamcc/post-process-builds:
b6ec4b13fd69bbcfa019c233697028fad0fca2fa (2018-09-13 12:56:10 -0400)
buildAndDeploy/upper: replace ContainerIdForBuild with PostProcessBuilds/better interface [ch239]

buildAndDeploy/upper: replace ContainerIdForBuild with PostProcessBuilds/better interface [ch239]

---

README.md
internal/build/container_test.go
internal/build/dockerfile.go
internal/build/dockerfile_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Still waiting to be able to test this on master before I call it "done done".

tiltfile: make entrypoint an optional parameter

---

internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/up_watch.go
internal/engine/up_watch_test.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch55/service:
3f8a3fe4e62df73d261fc4d3034b1a44dbd4a97f (2018-09-13 15:41:02 -0400)
engine: partial rename service -> manifest

engine: partial rename service -> manifest

---

internal/watch/notify_test.go
internal/watch/watcher_linux.go

Please review the following commits I made in branch nicks/mysteriouserror:
3fbf03e2341c3c85ff861fb0508073af75a57f28 (2018-09-14 16:57:12 -0400)
watch: fix a spurious error

watch: fix a spurious error

---

internal/engine/build_and_deployer_test.go
internal/engine/local_container_build_and_deployer.go
internal/engine/result.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper_test.go

Hello @nicks, @maiamcc,
Please review the following commits I made in branch nicks/ch264/revert:
d10fc383d906f13ad2a5a8bb07ae510b5247c118 (2018-09-17 13:39:50 -0400)
Revert "buildAndDeploy: store deployInfo on BuildAndDeployer (rather than on build state) (#338)"
This reverts commit d81521396c5915bf4c60cf5da5dd37800062ffd6.

Revert "buildAndDeploy: store deployInfo on BuildAndDeployer (rather than on build state) (#338)"

---

internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/result.go
internal/engine/synclet_build_and_deployer.go

Please review the following commits I made in branch nicks/ch264/image:
51b33fe398e1d423f139f1db16c24c97aef11f24 (2018-09-17 18:00:18 -0400)
engine: when falling back to image build, make sure we pass enough state to do the build properly

engine: when falling back to image build, make sure we pass enough state to do the build properly

---

internal/engine/build_and_deployer_test.go
internal/engine/local_container_build_and_deployer.go
internal/engine/result.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch264/unrevert:
6c3bfbec7d52f871f1b5e8421f63f26039396633 (2018-09-17 18:02:21 -0400)
Revert "Revert "buildAndDeploy: store deployInfo on BuildAndDeployer (rather than on build state) (#338)" (#347)"
This reverts commit d57228c0845f58f1828afb481dea24d01ad8acfc.

Revert "Revert "buildAndDeploy: store deployInfo on BuildAndDeployer (rather than on build state) (#338)" (#347)"

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/synclet_build_and_deployer.go
internal/engine/synclet_client_manager.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/k8s/pod.go
internal/k8s/pod_test.go

with this change, incremental builds work in GKE

tilt: wire up SyncletBaD to call the Synclet

---

internal/build/container_resolver.go
internal/build/container_resolver_test.go
internal/build/container_updater.go
internal/build/container_updater_test.go
internal/cli/wire_gen.go
internal/engine/local_container_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/synclet/server_adapter.go
internal/synclet/synclet.go
internal/synclet/wire.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/resolver:
dbf6d7b8dbe71615303f3a1b952a6521ebfaf45c (2018-09-18 15:48:33 -0400)
build: factor out ContainerResolver, bc this is about to get more complex

build: factor out ContainerResolver, bc this is about to get more complex

---

internal/engine/build_and_deployer_test.go
internal/engine/upper.go
internal/k8s/client.go
internal/k8s/entity.go
internal/k8s/entity_test.go
internal/summary/summary.go

Hello @maiamcc, @yuindustries,
Please review the following commits I made in branch nicks/ch263/summary:
1ef60b72298bc519904653d6fb9e225f1c5c2f48 (2018-09-18 13:35:40 -0400)
k8s: make it easier to resolve the real load balancer url with the k8s client

k8s: make it easier to resolve the real load balancer url with the k8s client

---

internal/build/container_resolver.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go

Please review the following commits I made in branch nicks/error:
1c4725c9c57dd3cf1fd1c87b3a36457c7ab5d990 (2018-09-19 11:59:13 -0400)
engine: improve some error output

engine: improve some error output

---

internal/build/container_test.go
internal/build/image_builder.go

Please review the following commits I made in branch nicks/ch48/push:
8d28a77dff333738bba3c1e40590c4b2d14ebf8f (2018-09-12 11:51:35 -0400)
build: improve push failure a bit

build: improve push failure a bit

---

internal/k8s/image.go
internal/k8s/image_test.go
internal/k8s/testdata_test.go

Please review the following commits I made in branch nicks/ch306/error:
64d420a636472bd205fe2e8640d6b7886aeeecde (2018-09-19 16:01:48 -0400)
image: support docker short names when parsing k8s yaml

image: support docker short names when parsing k8s yaml

---

internal/cli/wire_gen.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/portforward.go

Please review the following commits I made in branch nicks/ch322/urls:
381817b2248fd5cfb22fdad6a344ba6b69a15760 (2018-09-20 15:32:02 -0400)
k8s: load the URL for GKE loadbalancers

k8s: load the URL for GKE loadbalancers

---

internal/build/tar.go
internal/build/tar_test.go

Story details: https://app.clubhouse.io/windmill/story/222

build: edits to Tiltfile shouldn't cause docker cache miss

---

internal/k8s/entity.go
internal/k8s/entity_test.go
internal/summary/summary.go

Please review the following commits I made in branch nicks/ch298/namespaces:
1ac632ffd405f6d408da38e952ee8d0fcdbc587b (2018-09-20 13:58:42 -0400)
k8s: capture namespaces and show them in summary

k8s: capture namespaces and show them in summary

---

README.md
Tiltfile
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Story details: https://app.clubhouse.io/windmill/story/327

tiltfile: rename `build_docker_image` to `start_fast_build`

---

internal/engine/upper_test.go

Please review the following commits I made in branch maiamcc/wmdocker-fix:
6b20fefcf0ad68c31e227c277115406eca102e0f (2018-09-21 15:27:01 -0400)
docker: lulz fix a bad import

docker: lulz fix a bad import

---

internal/engine/build_and_deployer_test.go
internal/engine/upper_test.go
internal/k8s/fake_client.go

Please review the following commits I made in branch maiamcc/move_fake_k8s_cli:
e858af9616a94246d71dc2ac6786e78cfc90678a (2018-09-21 16:11:09 -0400)
k8s: move fake kubernetes client into k8s package

k8s: move fake kubernetes client into k8s package

---

internal/build/container_resolver.go

will tackle blocking on this process in another diff

container resolver: inc timeout to poll for container [ch314]

---

Tiltfile

Hello @jazzdan, @landism
Please review the following commits I made in branch maiamcc/fix-tilt-tiltfile:
8df78b49fcdeb3009d81f5ee09a5e01af4220e24 (2018-09-24 12:33:26 -0400)
Tilefile: syntax changes

Tilefile: syntax changes

---

internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/fake_client.go
internal/k8s/pod.go
internal/k8s/pod_test.go

Please review the following commits I made in branch nicks/node:
bf2b39a8c9066b2d8cc73859c01c193cd0dcf01c (2018-09-24 12:50:19 -0400)
k8s: Change PodWithImage to return the full pod info

k8s: Change PodWithImage to return the full pod info

---

internal/k8s/extract.go
internal/k8s/extract_test.go
internal/k8s/image.go
internal/k8s/image_test.go

Please review the following commits I made in branch nicks/extract:
56bbbe175358bbf17b84088372aa34593d8c559c (2018-09-24 17:55:18 -0400)
k8s: add helper methods for extracting pods

k8s: add helper methods for extracting pods

---

internal/k8s/entity_test.go
internal/k8s/extract.go
internal/k8s/extract_test.go
internal/k8s/image_test.go
internal/k8s/serialize_test.go
internal/k8s/testyaml/testyaml.go
internal/synclet/sidecar/inject.go
internal/synclet/sidecar/sidecar.go
internal/synclet/sidecar/sidecar_test.go

Please review the following commits I made in branch nicks/sidecar:
5be67f5b820efbbad6c837701d49aba9b198eacd (2018-09-24 18:25:26 -0400)
k8s: add a function for injecting sidecars

k8s: add a function for injecting sidecars

---

Makefile
hide_tbd_warning
internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/sidecar_synclet_manager.go
internal/engine/synclet_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
synclet/Dockerfile

Please review the following commits I made in branch nicks/deploy:
7e58168ae48fee3adee5eed50b76c54d5724dfc9 (2018-09-25 11:56:16 -0400)
synclet: deploy as sidecar

synclet: deploy as sidecar

---

internal/git/gitignore.go
internal/git/gitignore_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch323/gitignore:
b5dae35ca5328b97b1d827cd95eff8a29cb4e6c5 (2018-09-25 13:54:27 -0400)
tiltfile: ignore .git by default and add tests for cases i'm worried about

tiltfile: ignore .git by default and add tests for cases i'm worried about

---

internal/build/image_builder.go
internal/engine/build_and_deployer.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch332/errors:
c9952782f8d835b6b13b8243e415da09c16522ef (2018-09-25 14:18:25 -0400)
engine: propagate cancellation thru the watch loop

engine: propagate cancellation thru the watch loop

---

internal/engine/build_and_deployer_test.go
internal/engine/sidecar_synclet_manager.go
internal/engine/synclet_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/synclet/fake_client.go

ok let's try this again
(wip, tests/implementation for d4m still outstanding)

container deploys block on PostProcessBuild [ch334] WIP

---

internal/engine/build_and_deployer_test.go
internal/engine/testdata_test.go

Please review the following commits I made in branch nicks/skip:
bff7bb485b3031b5bbf11521b313c15b1309f8bd (2018-09-26 15:17:33 -0400)
engine: fix some bogus tests

engine: fix some bogus tests

---

internal/build/container_test.go
internal/build/container_updater.go
internal/build/container_updater_test.go
internal/build/docker_benchmark_test.go
internal/build/docker_client_benchmark_test.go
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/build/tar.go
internal/build/tar_test.go
internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/model/matcher.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch384/ignore:
93743c574fe611a17080ea6148f1899d20338af5 (2018-09-26 16:22:14 -0400)
build: handle dockerignore correctly when tarballing files

build: handle dockerignore correctly when tarballing files

---

internal/synclet/client_adapter.go

Please review the following commits I made in branch maiamcc/synclet-comment:
ed1a8c43f36da2fea8c65f825f23ab6953e0daea (2018-09-26 16:01:16 -0400)
synclet: add comment about polling

synclet: add comment about polling

---

internal/build/container_test.go
internal/build/image_builder.go
internal/build/path_mapping.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/model/manifest.go
internal/tiltfile/skylarkTypes.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch390/static:
b9d567ac081971ce50eaa95228a07588fd7fd111 (2018-09-26 18:35:41 -0400)
engine: support static builds

engine: support static builds

---

internal/engine/up_watch.go
internal/engine/upper_test.go
internal/model/manifest.go

Please review the following commits I made in branch nicks/ch390/watch:
4c9968773b98a6ad7d093147c35cd0b2c613338b (2018-09-27 12:00:13 -0400)
engine: support static rebuilds

engine: support static rebuilds

---

internal/engine/build_and_deployer_test.go
internal/model/matcher.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

feb0b52d088037334826d41402a46093a59e3fc9 (2018-09-26 17:15:09 -0400)
tiltfile: get the absolute filename

tiltfile: get the absolute filename

---

internal/tiltfile/tiltfile_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/tiltfiletests:
e5c4d07415c07d94910884eb403b19a861580498 (2018-09-27 19:30:56 -0400)
tiltfile: remove test boilerplate

tiltfile: remove test boilerplate

---

Makefile
internal/synclet/sidecar/sidecar.go

Please review the following commits I made in branch maiamcc/install-dev:
02b364fb115bf78197df8f03abd68cd82f386d1f (2018-09-28 12:23:02 -0400)
make: install tilt with dev synclet

make: install tilt with dev synclet

---

Makefile
internal/synclet/sidecar/sidecar.go

46f954eabe5c8110c1049ff73ae3ee2239176c39 (2018-09-28 12:11:29 -0400)
synclet: Add a synclet release process

synclet: Add a synclet release process

---

README.md
internal/tiltfile/skylarkTypes.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch329/static:
e938c26df73fec5196b954995dfe5e8ee07feb41 (2018-09-27 19:45:48 -0400)
tiltfile: Add static_build for existing dockerfiles

tiltfile: Add static_build for existing dockerfiles

---

internal/k8s/container.go
internal/k8s/container_test.go

Please review the following commits I made in branch nicks/unschedulable:
ccdcd7d189a1af9b985f705912b4a809ef55175e (2018-09-28 14:44:05 -0400)
k8s: fail if the pod is unschedulable

k8s: fail if the pod is unschedulable

---

cmd/synclet/main.go
internal/engine/sidecar_synclet_manager.go
internal/options/grpc.go

hat tip to @jazzdan for the original code in Tesseract, which I just stole ^_^''
[ch425]

grpc: inc max msg size (and consolidate options)

---

internal/engine/sidecar_synclet_manager.go

52de9e0323092ca9597239df84d739243dd34000 (2018-09-28 16:03:56 -0400)
remove i'm a sidecar logs

remove i'm a sidecar logs

---

internal/docker/client.go
internal/engine/synclet_build_and_deployer.go
scripts/timing.py

Please review the following commits I made in branch maiamcc/tracing-for-gke:
01342c9113273d5dca199ad22ac81f2654087b73 (2018-09-28 17:14:10 -0400)
timing: some tweaks for benchmarking gke

timing: some tweaks for benchmarking gke

---

internal/engine/sidecar_synclet_manager.go

don't poll for new client -- `WaitForContainerReady` takes care of waiting for stuff to come up properly. [ch431]

synclet: don't poll for new client

---

scripts/timing.py

Please review the following commits I made in branch maiamcc/time-third-build:
661264303c7cfc1f74f3b570ff52e82318525859 (2018-10-01 17:25:26 -0400)
timing: measure SECOND incremental build to avoid any noise from post-processing

timing: measure SECOND incremental build to avoid any noise from post-processing

---

internal/cli/cli.go
internal/cli/hud.go
internal/cli/up.go

Please review the following commits I made in branch maiamcc/hud-cmd-placeholder:
c09f4f4393cb12065f5fb060cbbe520b1a445b2c (2018-10-02 16:44:15 -0400)
hud: placeholder command to start hud

hud: placeholder command to start hud [ch452]

---

Gopkg.lock
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/cli.go

Hello @nicks,
415e8c3e78264d00f93317c3e02371bc6021c959 (2018-10-03 14:13:54 -0400)
vendor: update wmclient

vendor: update wmclient

---

Makefile
integration/README.md
integration/doc.go
integration/fixture_test.go
integration/namespace.yaml
integration/oneup/Dockerfile
integration/oneup/Tiltfile
integration/oneup/main.go
integration/oneup/oneup.yaml
integration/oneup_test.go

Please review the following commits I made in branch nicks/ch455/simpleup:
3b4635165319b81fb6f1e11486985afb27879cec (2018-10-03 15:09:18 -0400)
integration: add a basic integration test fixture
Note that this doesn't run on circleci yet

integration: add a basic integration test fixture

---

Dockerfile.protogen
internal/synclet/proto/synclet.pb.go

Hello @nicks,
cc @maiamcc
Please review the following commits I made in branch nicks/protoc:
79bf9898f773e8cd8019f80d20a6d171278f3509 (2018-10-03 22:19:30 -0400)
proto: make protoc-gen-go more deterministic

proto: make protoc-gen-go more deterministic

---

Makefile
integration/README.md
integration/oneup/Tiltfile
integration/oneup/oneup.yaml
integration/purge-image.sh
integration/purge-test-images.sh

Please review the following commits I made in branch nicks/images:
def394e4e66e22f1b2ddc7dc4675ffbda304b864 (2018-10-04 18:31:50 -0400)
integration: push to windmill-test-containers and delete images between runs

integration: push to windmill-test-containers and delete images between runs

---

internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/result.go
internal/engine/synclet_build_and_deployer.go
internal/engine/synclet_manager.go
internal/engine/testdata_test.go
internal/k8s/entity.go
internal/k8s/entity_test.go
internal/k8s/fake_client.go
internal/summary/summary.go
internal/synclet/fake_client.go

Please review the following commits I made in branch nicks/namespace:
7ffa1021c26aa20661e1b3368c4fae7527138159 (2018-10-05 14:31:13 -0400)
engine: handle namespaces correctly

engine: handle namespaces correctly

---

integration/fixture_test.go
integration/onewatch/Dockerfile
integration/onewatch/Tiltfile
integration/onewatch/deployment.yaml
integration/onewatch/main.go
integration/onewatch_test.go

Please review the following commits I made in branch nicks/ch457/watch:
a7bb2bcd27c16d58763e0cc5e6301b0b34a6107d (2018-10-05 15:00:30 -0400)
integration: add a test for tilt watch and container updates
b8f920487df4a1e67a598aa6ee0b8f929efd7baf (2018-10-05 14:38:11 -0400)
engine: handle namespaces correctly

integration: add a test for tilt watch and container updates

---

internal/cli/up.go

For iterating on tilt changes, any one service is generally too few, and `servantes` is too many.
This allows, e.g., `tilt up doggos vigoda`, so that you can just run 2-3 services.

tilt: allow multiple services on command line

---

internal/engine/upper_test.go
internal/hud/fake_hud.go

a9a0acb69388276a3e28c822a61ea2569c0fe863 (2018-10-08 15:48:51 -0400)
engine: make sure tests consume all events

engine: make sure tests consume all events

---

README.md
internal/model/manifest.go
internal/model/manifest_test.go
internal/tiltfile/skylarkTypes.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch522/port:
9e8c4502719398c09da81424f3cd3421cc633599 (2018-10-09 14:12:44 -0400)
tiltfile: add a port_forward method to k8s_service

tiltfile: add a port_forward method to k8s_service

---

internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/up_watch.go
internal/engine/upper_test.go
internal/ignore/path_matcher.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch543/upper:
6387d9b7896060f582a25a98f27bd938d5eb3436 (2018-10-10 12:51:44 -0400)
engine: fix gitignore/dockerignore regression

engine: fix gitignore/dockerignore regression

---

internal/build/test_utils.go
internal/testutils/bufsync/bufsync.go

Hello @nicks,
Please review the following commits I made in branch nicks/threadsafebuf:
60c3ed55efca9dc8e43e0cbfbe07abd116e3924b (2018-10-10 18:17:36 -0400)
testutils: factor out a utility for thread-safe bufio

testutils: factor out a utility for thread-safe bufio

---

internal/engine/actions.go
internal/engine/up_watch_test.go
internal/engine/upper.go
internal/store/engine_state.go
internal/store/store.go

Please review the following commits I made in branch nicks/actions:
5105fa57c5ac36e9f83fd45827ba9da5c2d9fa64 (2018-10-10 20:29:38 -0400)
engine: Add BuildCompletedAction, InitAction

engine: Add BuildCompletedAction, InitAction

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/deploy.go
internal/engine/podlogmanager.go
internal/engine/podlogmanager_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/k8s/client.go
internal/k8s/container.go
internal/k8s/container_test.go
internal/k8s/fake_client.go
internal/k8s/pod.go
internal/output/outputter.go
internal/output/outputter_test.go

Please review the following commits I made in branch nicks/ch520/podlogs:
ba10bf1aea98bcc3555cdbc9b827a7634ff05b77 (2018-10-10 17:34:54 -0400)
engine: stream the logs from the deployed container

engine: stream the logs from the deployed container

---

internal/engine/upper_test.go

Please review the following commits I made in branch nicks/buildlog:
28fd1894507fcc2459ce0947e849f0c1ca6bc27c (2018-10-11 16:41:17 -0400)
engine: fix flaky test

engine: fix flaky test

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/actions.go
internal/engine/deploy.go
internal/engine/deploy_test.go
internal/engine/local_container_build_and_deployer_test.go
internal/engine/podlogmanager.go
internal/engine/podlogmanager_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/ch531/podlogs:
248515369f4ff4f6a5a6813d4ea6681032d0993b (2018-10-11 17:50:38 -0400)
engine: send pod logs to EngineState

engine: send pod logs to EngineState

---

internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/screen.go

hud: add subtle color

---

internal/store/engine_state.go

Hello @nicks,
Please review the following commits I made in branch nicks/test:
f83009ea823435b3e2bda431828548eb46970937 (2018-10-12 11:22:17 -0400)
store: fix a flakey test

store: fix a flakey test

---

internal/engine/deploy.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/k8s/container.go
internal/k8s/fake_client.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/ch522/portforward:
4b05fd9d87defc91975ef83586c52969d3969a6b (2018-10-11 20:20:16 -0400)
engine: store container state in engine state

engine: store container state in engine state

---

internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/fake_hud.go
internal/hud/hud.go
internal/store/store.go
internal/store/subscriber.go
internal/store/subscriber_test.go

Please review the following commits I made in branch nicks/sub:
43a83c75d84883cc0f346ea94ccf89f8edf6abb1 (2018-10-12 15:51:48 -0400)
store: add a subscriber api, and update the HUD async

store: add a subscriber api, and update the HUD async

---

internal/engine/upper_test.go

Hello @nicks,
dd5d9bdad76ed0907809411282aa1ec9e2eedd06 (2018-10-15 13:05:16 -0400)
engine: fix a flaky test

engine: fix a flaky test

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/portforwardcontroller.go
internal/engine/portforwardcontroller_test.go
internal/engine/synclet_manager.go
internal/engine/upper.go
internal/k8s/client.go
internal/k8s/fake_client.go
internal/k8s/portforward.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/ch522/reactive:
5eea7b255f622ab2f8e483035bc80eb021c46e8a (2018-10-15 12:25:55 -0400)
engine: add port-forwarding

engine: add port-forwarding

---

internal/engine/portforwardcontroller.go
internal/engine/portforwardcontroller_test.go
internal/engine/upper.go
internal/k8s/fake_client.go

Please review the following commits I made in branch nicks/containerport:
b4da922c4c070e514587b4c1c071d6650a78e670 (2018-10-15 17:23:38 -0400)
engine: auto-discover container ports if the user specified port 0

engine: auto-discover container ports if the user specified port 0

---

internal/cli/up.go
internal/engine/upper.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/autoopen:
6b9e52a964ecd2e052a82619142098007d80a1d5 (2018-10-15 17:02:36 -0400)
engine: remove auto-open browser in favor of HUD open-browser input

engine: remove auto-open browser in favor of HUD open-browser input

---

internal/hud/renderer.go

tilt: show last deployed edits

---

internal/engine/deploy.go

Please review the following commits I made in branch maiamcc/old-log-line:
cf65793648a98e83ed0b62cd49abfcc0cd1cef78 (2018-10-16 14:12:33 -0400)
misc: remove old log line

misc: remove old log line

---

internal/tiltfile/skylarkTypes.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch589/static:
55814e205c3553084071fe68a6afe6517727cdb4 (2018-10-16 14:40:05 -0400)
tiltfile: make .gitignore/.dockerignore work in static_build

tiltfile: make .gitignore/.dockerignore work in static_build

---

internal/cli/wire_gen.go

Hello @nicks,
30ce6ec6f654ee4d7845c13d930e62b732a33aeb (2018-10-16 14:55:07 -0400)
wire: regenerate

wire: regenerate

---

internal/engine/upper.go
internal/engine/upper_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch595/segfault:
d270fa22d3ae4ee0cc9c9b101eb7cb7f3eb7aff8 (2018-10-16 17:48:00 -0400)
engine: fix a segfault when the dockerfile is edited

engine: fix a segfault when the dockerfile is edited

---

internal/cli/hud.go

theoretically this could have been done by making a custom dialer that retries connections to dead sockets, but that seems way more complex

tilt: hud waits for up to start instead of erroring

---

internal/hud/fake_hud.go
internal/hud/hud.go
internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/view/view.go

Please review the following commits I made in branch nicks/ch583/narration2:
43553507babfe19ac5bf9d0678d6e41df86a1abf (2018-10-17 13:18:54 -0400)
hud: Add a pane for the demo narration message

hud: Add a pane for the demo narration message

---

internal/cli/hud.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/demo/script.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/client/client.go
internal/hud/fake_hud.go
internal/hud/hud.go
internal/model/manifest.go

Please review the following commits I made in branch nicks/ch583/narration3:
704505da56f744daf86f4e850a52bb63a5ac4aad (2018-10-17 16:11:54 -0400)
demo: make the demo connect to the hud directly

demo: make the demo connect to the hud directly

---

.circleci/Dockerfile.integration

Hello @nicks,
7481393c8d17a04a972939ec9ca76bcc7b2cab51 (2018-10-18 12:59:27 -0400)
integration: pin the kubeadm-dind-cluster scripts

integration: pin the kubeadm-dind-cluster scripts

---

internal/cli/demo.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/demo/script.go
internal/demo/step.go

Hello @nicks,
Please review the following commits I made in branch nicks/demodir:
15c9e51d0af40ccb820a60628ad75cde871d5019 (2018-10-18 14:44:49 -0400)
demo: add a branch flag to help development

demo: add a branch flag to help development

---

internal/rty/canvas.go
internal/rty/components.go
internal/rty/scroll.go

Hello @landism, @dbentley,
Please review the following commits I made in branch maiamcc/rty-scroll-to-end:
75077cb7dae93bc9e8d66486eb25b14807f0247c (2018-10-16 15:01:02 -0400)
rty: 'following' mode auto-scrolls to end of textScroll contents [ch575]

rty: 'following' mode auto-scrolls to end of textScroll contents [ch575]

---

internal/demo/script.go
internal/demo/step.go

Please review the following commits I made in branch nicks/demo3:
a6cf27d73fb299e9542eff8eea0756ac80f08a57 (2018-10-18 16:17:17 -0400)
demo: flesh out the demo script

demo: flesh out the demo script

---

internal/hud/hud.go

Please review the following commits I made in branch maiamcc/open-browser:
6c67bb1e63a03fa4958a655a4694d9424bcdc5fe (2018-10-18 16:09:32 -0400)
hud: keystroke in hud to open url in browser [ch523]

hud: keystroke in hud to open url in browser [ch523]

---

internal/hud/hud.go

Please review the following commits I made in branch nicks/reset:
8ec1200b7f898879e5c486c020b5ec5832072907 (2018-10-18 16:42:49 -0400)
hud: always reset when closing

hud: always reset when closing

---

internal/engine/build_and_deployer_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/build_result.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/buildstate:
3d295dc6486311ae8640e21d35d1a10636bb851a (2018-10-18 17:34:02 -0400)
store: simplify file tracking a bit

store: simplify file tracking a bit

---

internal/cli/wire_gen.go
internal/demo/script.go
internal/k8s/client.go
internal/k8s/fake_client.go

Please review the following commits I made in branch nicks/ch585/clean:
6928b2ca93e05f4d1ffd6126f9a1b499a7cc744e (2018-10-19 16:51:34 -0400)
demo: clean up when finished

demo: clean up when finished

---

internal/cli/cli.go
internal/cli/down.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/demo/script.go
internal/engine/parse.go
internal/tiltfile/tiltfile.go

Please review the following commits I made in branch nicks/ch585/cleancmd:
f2262a64de1f498329dae68e4eaa988ec5d01cd3 (2018-10-19 18:45:11 -0400)
cli: pull out a 'down' command

cli: pull out a 'down' command

---

README.md

Please review the following commits I made in branch nicks/video:
97830bc5fefc08edb537faebedc397cd80ce27e7 (2018-10-22 12:04:15 -0400)
add tagline and video

add tagline and video

---

internal/engine/upper_test.go

In support of additional changes to #586.
I also deleted `assertAllHUDUpdatesConsumed` on the advice of @nicks. It doesn't make sense in the future when there are lots of ambient changes state that can cause the HUD to update.

engine: refactor upper tests to use NewUpper

---

internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch maiamcc/changed-config-file-tests:
fa745a75e5a07b2a4e9d2c551a04392358e2c511 (2018-10-22 12:39:33 -0400)
upper: tests for config file changes

upper: tests for config file changes

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/atomic:
1d9262a93ab47277e9c1bed471bdc9d3a7e4b687 (2018-10-22 18:16:58 -0400)
circleci: peg the image digests

circleci: peg the image digests

---

.circleci/Dockerfile
.circleci/Dockerfile.integration
.circleci/config.yml
DEVELOPING.md
Dockerfile.base
Dockerfile.protogen
integration/oneup/Dockerfile
integration/onewatch/Dockerfile

Please review the following commits I made in branch nicks/go11:
d8c7042bd90c37b4532a30d64f880b4628bae674 (2018-10-23 12:37:30 -0400)
upgrade to go 1.11

upgrade to go 1.11

---

internal/build/pipeline_state.go
internal/build/testdata/TestPipelineErrored_master
internal/build/testdata/TestPipelineMultilinePrint_master
internal/build/testdata/TestPipeline_master
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/renderer.go
internal/hud/view/view.go
internal/store/engine_state.go

tilt: display logs inline in HUD

---

.gitignore
.goreleaser.yml
DEVELOPING.md
Makefile
cmd/tilt/main.go
internal/cli/build.go
internal/cli/cli.go
internal/cli/hud.go
internal/cli/up.go
internal/cli/version.go

Please review the following commits I made in branch nicks/ch656/release:
8882353741277ea220b6df32533dc8a64c92fe59 (2018-10-24 16:15:22 -0400)
cmd: make tilt binary compatible with goreleaser

cmd: make tilt binary compatible with goreleaser

---

internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/testyaml/testyaml.go

Please review the following commits I made in branch nicks/ch674/fix-statefulset-error:
54a2073204294f94b2542b69ba0fe74cfe211f55 (2018-10-24 17:32:44 -0400)
k8s: handle statefulset immutability errors

k8s: handle statefulset immutability errors

---

.circleci/Dockerfile.integration
.circleci/config.yml

Hello @nicks,
4d5eae42b59fb311954cdd90d2b514627013fcb4 (2018-10-25 19:31:17 -0400)
integration: upgrade the cluster

integration: upgrade the cluster

---

internal/rty/interactive_tester.go

It's been too long since I read Highlights Magazine - I'm out of practice at spotting the differences.
(the diff is really naive - just looking for mismatched cells - but better than nothing)

tilt: add 'd' to highlight diff in interactive tests

---

internal/engine/podlogmanager.go
internal/engine/podlogmanager_test.go
internal/k8s/client.go
internal/k8s/fake_client.go
internal/k8s/pod.go

8088a8a3553a37679d2ed855b9a30c0536a1696c (2018-10-25 19:22:27 -0400)
engine: make log watching more robust

engine: make log watching more robust

---

internal/cli/wire_gen.go
internal/engine/upper.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/dead:
dbece0acf2e07fc613c4e67047f22efc13d8bdad (2018-10-30 13:38:22 -0400)
upper: remove some dead code

upper: remove some dead code

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/imagecontroller.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ch713/gc:
0e5a4eff89740a5e1beb8f1992137785ca247e8c (2018-10-30 13:34:02 -0400)
engine: make image reaping a subscriber

engine: make image reaping a subscriber

---

internal/cli/wire_gen.go
internal/engine/deploy_test.go
internal/engine/local_container_build_and_deployer_test.go
internal/engine/podlogmanager_test.go
internal/engine/portforwardcontroller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/watchmanager_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/store/reducer.go
internal/store/store.go
internal/store/subscriber_test.go

Please review the following commits I made in branch nicks/ch713/store:
6912f36a75326baa0d94d1136d9b496f7bf5f7bb (2018-10-30 15:04:56 -0400)
store: move the main action loop into the store

store: move the main action loop into the store

---

internal/k8s/client.go
internal/k8s/fake_client.go

Please review the following commits I made in branch nicks/deadservice:
a115596700b9d1ff2d85f693106f7775036fe45e (2018-10-30 17:41:40 -0400)
k8s: delete some dead code

k8s: delete some dead code

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/actions.go
internal/engine/service_watch.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/wire_gen.go
internal/k8s/client.go
internal/k8s/ip.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/ch709/minikube:
778d9feb60854fb5b412ce773c9f334d4e69f5d9 (2018-10-30 18:17:08 -0400)
engine: detect minikube ip
a115596700b9d1ff2d85f693106f7775036fe45e (2018-10-30 17:41:40 -0400)
k8s: delete some dead code

engine: detect minikube ip

---

internal/engine/actions.go
internal/engine/global_yaml_buildcontroller.go
internal/engine/upper.go
internal/model/globalyaml.go
internal/store/engine_state.go
internal/store/engine_state_test.go

and are automatically displayed in the UI! Looks like this:

store: YAML manifests can be converted to views

---

integration/fixture_test.go

this isn't super interesting, but now I get this
```
error: invalid resource name "deployment/oneup": [may not contain '/']
port forward failed: exit status 1
```
and don't have to wonder as much what's generating the error
(I also tried to make the error case cause the test to fail, but it seemed like it sufficiently increased the complexity of the tests that it wasn't worth it, when printing gets us most of the value anyway)

tilt: log portforward errors in integration tests

---

README.md

Please review the following commits I made in branch nicks/demo:
26afef3f807d132056b9f1b01b7684b936609d74 (2018-11-01 12:12:59 -0400)
readme: upload new demo

readme: upload new demo

---

internal/engine/upper.go
internal/engine/upper_test.go

https://app.clubhouse.io/windmill/story/700/when-editing-tiltfile-hud-displays-pending-forever

tilt: fix false 'pending' after editing tiltfiles

---

internal/engine/upper_test.go

Please review the following commits I made in branch maiamcc/fix-build:
f48674ac3e022cd47f54cecab256566ac809e0e7 (2018-11-02 16:28:47 -0400)
engine: fix a broken test

engine: fix a broken test

---

internal/synclet/sidecar/sidecar.go

63b878ccb8a0c5f8d78aeb097698e23cfdec5e6c (2018-11-05 15:54:15 -0500)
synclet: do a synclet release

synclet: do a synclet release

---

.goreleaser.yml

6e03b1fff183139a9cc06d0d90ecb6a9633496e6 (2018-11-05 18:04:39 -0500)
goreleaser: add macos binaries

goreleaser: add macos binaries

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/readme:
0dce20002adaf652069dce4a212ef482f2733c14 (2018-11-07 18:58:18 -0500)
readme: add links to binaries

readme: add links to binaries

---

internal/build/container_test.go
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/build/image_reaper.go
internal/build/label.go
internal/build/tar.go
internal/build/tar_test.go
internal/build/test_utils.go
internal/cli/wire_gen.go
internal/dockerfile/dockerfile.go
internal/dockerfile/dockerfile_test.go
internal/dockerfile/label.go
internal/engine/image_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/dockerfile:
e16bcecc9e9389ec111fb51ea2dd41b1cc4c290e (2018-11-07 19:23:08 -0500)
build: move dockerfile logic out of the build package

build: move dockerfile logic out of the build package

---

internal/rty/interactive_tester.go

tilt: actually print instructions on golden test failure

---

internal/build/cache_builder.go
internal/build/cache_builder_test.go
internal/build/image_builder.go
internal/build/label.go
internal/build/tar.go
internal/build/test_utils.go

Please review the following commits I made in branch nicks/ch728/cachebuilder:
f5ec0d2dc4272f44b3712dc71466fc3044f20d04 (2018-11-08 15:45:50 -0500)
build: add a way to build a cache of directories

build: add a way to build a cache of directories

---

internal/engine/global_yaml_buildcontroller.go
internal/engine/global_yaml_buildcontroller_test.go
internal/model/globalyaml.go

Please review the following commits I made in branch maiamcc/global-yaml-controller-tests:
1561af19dfd54b5ccac30daf41b0dc8b4fe17069 (2018-11-08 17:43:57 -0500)
engine: some tests for globalYAMLBuildController.OnChange
11206d0cab4fb653d808994c082ee7bf3441c798 (2018-11-08 17:22:34 -0500)
wip

engine: some tests for globalYAMLBuildController.OnChange

---

integration/onewatch_test.go

7ef61378829ccee8c76984d048eab3bfec69e2f0 (2018-11-09 15:32:31 -0500)
integration: turn up timeouts a bit

integration: turn up timeouts a bit

---

internal/build/image_builder.go
internal/cli/wire_gen.go
internal/docker/fake_client.go
internal/dockerfile/dockerfile.go
internal/dockerfile/dockerfile_test.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/testdata_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/model/manifest.go
internal/model/manifest_test.go

Please review the following commits I made in branch nicks/ch728/ibd:
89cd371471bc7487be3ae1b780e423d77ef5f781 (2018-11-09 15:20:40 -0500)
engine: add engine logic for building cache paths

engine: add engine logic for building cache paths

---

internal/engine/upper_test.go

Please review the following commits I made in branch nicks/uppertests:
18baf00445e0609272aac0598384a502f5b26ac0 (2018-11-09 19:10:43 -0500)
engine: clean up upper tests a bit

engine: clean up upper tests a bit

---

Makefile

Hello @nicks,
Please review the following commits I made in branch nicks/makefile:
44b53bea1fe6da1c3e83c881f245d7c96ffec4b4 (2018-11-12 14:53:19 -0500)
small makefile bug fixes

small makefile bug fixes

---

internal/build/container_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/build:
9569f8fb09029749ab0ae68847b945be16f0b01b (2018-11-20 00:27:54 -0500)
build: fix a unit test on docker 18.09

build: fix a unit test on docker 18.09

---

internal/build/buildkit_printer.go
internal/build/buildkit_printer_test.go
internal/build/testdata/TestBuildkitPrinter/docker-18.09-output_master

Please review the following commits I made in branch nicks/ch856/printer:
335e5c25e6b12eb6a4bcac56d46937ef68950455 (2018-11-20 18:25:23 -0500)
build: handle new buildkit output

build: handle new buildkit output

---

.circleci/Dockerfile.integration
.circleci/config.yml

Hello @nicks,
c921d91e0a85e1db0d261f19010c383be76142ee (2018-11-26 15:47:52 -0500)
integration: update k8s setup script

integration: update k8s setup script

---

internal/engine/actions.go
internal/engine/buildcontroller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/build_reason.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/store/store.go

Please review the following commits I made in branch nicks/ch719/panic:
2574e17666112a24f7178595988f7eec4d8566bb (2018-11-21 18:35:38 -0500)
store: remove the build queue
Builds are kicked off only based on causation state.
Makes it easy to determine why a build is happening.

store: remove the build queue

---

internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/crashrebuild:
982bb3ec70110fb0847da3cdc437f8c242d78ee0 (2018-11-27 14:48:37 -0500)
engine: fix regression in crash rebuild and add better testing

engine: fix regression in crash rebuild and add better testing

---

internal/hud/format.go
internal/hud/format_test.go
internal/hud/renderer.go

Please review the following commits I made in branch nicks/ch894/time:
772306a40ac6b1940e7355f08bee0bfe783fe4ee (2018-11-28 14:29:28 -0500)
hud: smaller increments in time formatting

hud: smaller increments in time formatting

---

internal/engine/fake_notify_test.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/clone:
264e05b414d2d159fda5fa61143a32e270c92377 (2018-11-29 16:17:08 -0500)
engine: fix some minor race conditions and locking issues

engine: fix some minor race conditions and locking issues

---

internal/build/container_resolver.go
internal/build/container_test.go
internal/build/container_updater.go
internal/build/image_builder.go
internal/build/image_reaper.go
internal/build/path_mapping.go
internal/build/tar.go
internal/container/container.go
internal/docker/client.go
internal/dockerfile/dockerfile.go
internal/engine/imagecontroller.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/env.go
internal/k8s/fake_client.go
internal/k8s/image.go
internal/k8s/pod.go
internal/minikube/docker.go
internal/model/matcher.go
internal/synclet/synclet.go
internal/tiltfile/skylarkTypes.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go
internal/watch/watcher_linux.go

this has been bugging/scaring me, and i've had it on my todo list forever.

cleanup: wrap errors properly

---

internal/cli/wire_gen.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/wire_gen.go
internal/synclet/wire_gen.go

this is all done through BuildController now so doesn't need to be here

tilt: remove BaD instance from upper

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/dockercompose/event.go
internal/dockercompose/info.go
internal/engine/actions.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/docker_compose_watch.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/view/view.go
internal/store/engine_state.go

include a hacky map from dc event --> probable status.
no real UI thought given to this yet. Looks like this:

[docker-compose] listen for dc events, update hud with dc status [ch977]

---

internal/engine/upper_test.go

Please review the following commits I made in branch nicks/flaky:
95b6b03fdbd1efeeb399caa56985e73c6c506417 (2018-12-03 17:59:05 -0500)
engine: fix a racey segfault in testing

engine: fix a racey segfault in testing

---

internal/hud/resourceview.go
internal/rty/layouts.go

After changes to master, had to reimplement docker compose hud stuff.
Here's what I've got.

re-implement docker-compose hud support after changes

---

internal/demo/script.go
internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/build_result.go
internal/store/build_status.go
internal/store/engine_state.go
internal/store/engine_state_test.go

Please review the following commits I made in branch nicks/ch1047/history:
68235dd58f70551ff5ce7ffe4cd214b89a59ad86 (2018-12-05 17:35:26 -0500)
engine: store multiple build states

engine: store multiple build states

---

internal/cli/up.go
internal/demo/script.go
internal/engine/logger.go

Hello @nicks,
Please review the following commits I made in branch nicks/demologs:
ee73f9a4e4702a7422a9b5c39afcc18a592a0d05 (2018-12-10 14:59:45 -0500)
demo: move log setup to engine, use it in demo

demo: move log setup to engine, use it in demo

---

internal/k8s/ip.go

Hello @nicks,
Please review the following commits I made in branch nicks/ch1094/minikube:
9d69746d2cb8840bb809a6382f0a7f189705b717 (2018-12-11 11:54:29 -0500)
k8s: improve minikube ip error message

k8s: improve minikube ip error message

---

internal/tiltfile2/docker_compose.go
internal/tiltfile2/tiltfile.go
internal/tiltfile2/tiltfile_state.go
internal/tiltfile2/tiltfile_test.go

tiltfile: docker compose support to new tiltfile syntax [ch1108]

---

internal/engine/build_and_deployer_test.go
internal/engine/upper_test.go
internal/engine/watchmanager.go
internal/ignore/path_matcher.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/ospath/ospath.go
internal/tiltfile2/docker.go
internal/tiltfile2/files.go
internal/tiltfile2/tiltfile_state.go
internal/tiltfile2/tiltfile_test.go

cc @jazzdan
Please review the following commits I made in branch nicks/ch1046/dockerignore:
1bc3b488b409e1ba654d0c24f0188034064ee500 (2018-12-13 15:26:24 -0800)
model: separate out dockerignore from gitignore

model: separate out dockerignore from gitignore

---

internal/engine/upper.go
internal/hud/buildstatus.go
internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/resourceview.go
internal/hud/view/view.go
internal/model/build_status.go
internal/store/engine_state.go
internal/store/engine_state_test.go

Please review the following commits I made in branch nicks/ch1047/history:
3c0579f53dc40690701e93aee6f072ffbf323294 (2018-12-06 14:43:18 -0500)
store: multiple build statuses in the view state

store: multiple build statuses in the view state

---

internal/dockercompose/compose.go
internal/dockercompose/logs.go
internal/engine/docker_compose_event_watcher.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/tiltfile2/tiltfile_state.go
internal/tiltfile2/tiltfile_test.go

Please review the following commits I made in branch maiamcc/dc-config-files:
6b81ed5721027035ab82341623c710cc0f620ba1 (2018-12-18 16:52:44 -0500)
docker compose: rebuild service on Dockerfile/dc.yml change [ch1111]

docker compose: rebuild service on Dockerfile/dc.yml change [ch1111]

---

internal/cli/down.go
internal/dockercompose/compose.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/docker_compose_event_watcher.go
internal/engine/docker_compose_log_manager.go
internal/hud/view/view.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/store/engine_state.go
internal/tiltfile2/tiltfile_test.go

unnecessary rename, as discussed ^_^''

compose: dcYaml -> dcConfig

---

internal/testutils/tempdir/temp_dir_fixture.go
internal/watch/notify_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/tempdir:
9faaa59ffd27469e5bdfef6493441b0c892cef93 (2018-12-19 18:40:02 -0500)
testing: update internal/watch to use the tempdir fixture

testing: update internal/watch to use the tempdir fixture

---

docserver.yaml
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/docker/client.go
internal/docker/fake_client.go

Please review the following commits I made in branch nicks/ch1157/docker:
3776caaad68bb8b4dd19ddba621112a44e8691eb (2018-12-20 14:20:49 -0500)
build: handle older docker versions

build: handle older docker versions

---

internal/build/image_builder.go
internal/build/image_builder_test.go

Please review the following commits I made in branch nicks/push:
d833629f5c8e47c5c6815f2b5d55e8fa5f0704ee (2018-12-20 14:40:28 -0500)
build: remove some dead code

build: remove some dead code

---

internal/engine/upper_test.go

Please review the following commits I made in branch maiamcc/fix-tests:
b633953b3476a0353a169e031ddd3957247b455f (2018-12-20 14:57:54 -0500)
fix test from bad merge o_0

fix test from bad merge o_0

---

docs/api/api.py
docs/write_your_tiltfile.md

tl;dr:
- The parameter in a k8s_resource is `image` not `img`.
- we are not a wrestling entertainment company.

Fix a few typos / parameter names in docs

---

internal/engine/buildcontroller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/ignore/path_matcher.go
internal/store/engine_state.go
internal/tiltfile2/docker.go
internal/tiltfile2/files.go
internal/tiltfile2/tiltfile_state.go
internal/tiltfile2/tiltfile_test.go

Please review the following commits I made in branch nicks/ch1076/gitignore2:
55075100adf6422e0a2a34247f4ca8c12931ea1c (2018-12-20 16:44:18 -0500)
tiltfile: if the tiltfile is in the root of a git repo, pick up that repo.
and other bug fixes for how ignored files/temp files are handled

tiltfile: if the tiltfile is in the root of a git repo, pick up that repo.

---

internal/engine/upper_test.go

Hello @nicks,
4a38cc54e1d5fae468d8165f6326011f37076f37 (2018-12-21 08:28:12 -0500)
engine: fix some race conditions

engine: fix some race conditions

---

Gopkg.lock
internal/model/manifest.go
vendor/github.com/google/go-cmp/LICENSE
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/compare.go
vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
vendor/github.com/google/go-cmp/cmp/internal/function/func.go
vendor/github.com/google/go-cmp/cmp/internal/value/format.go
vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
vendor/github.com/google/go-cmp/cmp/options.go
vendor/github.com/google/go-cmp/cmp/path.go
vendor/github.com/google/go-cmp/cmp/reporter.go
vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go

Hello @nicks,
Please review the following commits I made in branch nicks/cmp:
42fd268ed2edca557d5c0027ccf36aa1fc71bb0c (2018-12-21 10:15:31 -0500)
vendor: go-cmp

vendor: go-cmp

---

internal/engine/upper.go
internal/hud/renderer.go

Please review the following commits I made in branch maiamcc/rm-comments:
115c7af04b281287d218ec974159bc677cf86397 (2018-12-21 14:02:45 -0500)
remove some irrelevant docker compose todos

remove some irrelevant docker compose todos

---

internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/wire_gen.go
internal/hud/server/server.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/ch1144/web:
cdd9c1d253f56523fe5f53dbb7ebbb7871ab66c4 (2018-12-20 19:03:52 -0500)
server: a simple http server that serves the HUD view

server: a simple http server that serves the HUD view

---

internal/k8s/serialize.go
internal/k8s/serialize_test.go
internal/k8s/testyaml/testyaml.go

Hello @nicks,
Please review the following commits I made in branch nicks/issue893:
92d7d088b59212bf0ca5f6f536f91ac8b5ce40e1 (2018-12-22 19:54:23 -0500)
k8s: more flexible yaml parsing to match kubectl. Fixes issue #893

k8s: more flexible yaml parsing to match kubectl. Fixes issue #893

---

internal/engine/image_build_and_deployer.go
internal/engine/imagecontroller.go
internal/engine/testdata_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/model/docker_info.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/tiltfile2/tiltfile_state.go
internal/tiltfile2/tiltfile_test.go

`DockerInfo.DockerRef` is kind of redundant ^_^''

model: rename dockerInfo.DockerRef -> dockerInfo.Ref

---

integration/oneup/main.go

integration: log oneup HTTP requests

---

Gopkg.toml

The option branch was merged in to master.

Remove the branch override for starlark.

---

internal/dockercompose/fake_client.go
internal/engine/build_and_deployer_test.go
internal/engine/testdata/fixture_docker-config.yml
internal/engine/testdata/haproxy.dockerfile
internal/engine/testdata/haproxy_docker-config.yml
internal/engine/testdata/server.dockerfile
internal/engine/upper_test.go

Please review the following commits I made in branch maiamcc/dc-upper-tests:
2efa255a2ff24f02d74d2a1752392e85e108f39a (2019-01-03 16:14:05 -0500)
docker compose upper tests
7790afcd09c7e94291295519fa8663f0ac9e66e4 (2019-01-03 15:32:10 -0500)
tighter dc setup for tests

upper: docker compose upper tests [ch1194]

---

web/package.json
web/src/App.test.js
web/src/ResourceList.js
web/src/setupTests.js
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/ch1199/tests:
347bf999beda2874e120cd4e44ced04cd04b516a (2019-01-03 16:12:52 -0500)
web: basic test scaffolding

web: basic test scaffolding

---

internal/cli/down.go
internal/demo/script.go
internal/engine/configs_controller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/files.go
internal/tiltfile/k8s.go
internal/tiltfile/text_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Hello tbd,
Please review the following commits I made in branch maiamcc/tiltfile2-rename:
1be33639599cf54731cc99ec8a6f551d9b62c678 (2019-01-03 17:17:56 -0500)
internal: rename tiltfile2 pkg -> tiltfile

internal: rename tiltfile2 pkg -> tiltfile

---

internal/docker/client.go

Please review the following commits I made in branch nicks/issue931:
375c57a49416245e7ce18dab94239c7d08598ef6 (2019-01-07 11:50:33 -0500)
docker: Add version negotation to docker init. Fixes https://github.com/windmilleng/tilt/issues/931

docker: Add version negotation to docker init. Fixes https://github.com/windmilleng/tilt/issues/931

---

internal/engine/upper_test.go
internal/engine/watchmanager.go

71d55eee93123617101e2ba15c16f4645f4f5438 (2019-01-04 18:23:09 -0500)
engine: fix some flaky tests

engine: fix some flaky tests

---

internal/hud/renderer_test.go

fixes a merge error introduced by #935

renderer_test: fix build

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/profiler.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/actions.go
internal/hud/hud.go
internal/hud/view/view.go
internal/store/engine_state.go

'p' now starts and stops a pprof profile

tilt: p is for profile

---

docserver.yaml
internal/k8s/label.go
internal/k8s/label_test.go
internal/k8s/testyaml/testyaml.go

Please review the following commits I made in branch nicks/ch846/beta:
26a00d7906a0b0752b46e888f5c308dd2c4278eb (2019-01-09 11:49:12 -0500)
k8s: bug fix for extensions/v1beta deployments

k8s: bug fix for extensions/v1beta deployments

---

.circleci/Dockerfile.integration
.circleci/config.yml
integration/fixture_test.go
integration/onedc/Dockerfile
integration/onedc/Tiltfile
integration/onedc/docker-compose.yaml
integration/onedc/main.go
integration/onedc_test.go

Please review the following commits I made in branch nicks/ch1128/integration:
bb849691a2070057522d7e3303e95c10013f1288 (2019-01-04 16:23:52 -0500)
docker-compose: integration tests

docker-compose: integration tests

---

internal/cli/down.go
internal/dockercompose/config.go
internal/engine/build_and_deployer_test.go
internal/engine/buildcontroller.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/docker_compose_log_manager.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/imagecontroller.go
internal/engine/local_container_build_and_deployer.go
internal/engine/parse.go
internal/engine/portforwardcontroller.go
internal/engine/portforwardcontroller_test.go
internal/engine/testdata_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/resourceview.go
internal/hud/view/view.go
internal/model/deploy_info.go
internal/model/docker_info.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/model/target.go
internal/store/build_result.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/targets:
74ae9cb7e9559e39ce87758da9cbd2761d46318a (2019-01-09 16:38:26 -0500)
model: change all the names to move towards abstract build graph

model: change all the names to move towards abstract build graph

---

internal/model/deploy_info.go
internal/model/docker_info.go
internal/model/globalyaml.go
internal/model/manifest.go
internal/model/target.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/targets2:
0fbed0900f9d0a41d7a5de68e86f9b3f4969c6ea (2019-01-09 18:07:40 -0500)
model: Add TargetStatus interface for ManifestState

model: Add TargetStatus interface for ManifestState

---

internal/demo/script.go
internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/docker_compose_log_manager.go
internal/engine/imagecontroller.go
internal/engine/podlogmanager.go
internal/engine/podlogmanager_test.go
internal/engine/portforwardcontroller.go
internal/engine/portforwardcontroller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/watchmanager.go
internal/model/deploy_info.go
internal/model/docker_info.go
internal/model/globalyaml.go
internal/model/manifest.go
internal/model/target.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/store/manifest_target.go
internal/store/store.go

Please review the following commits I made in branch nicks/nesting:
0fee9b66402849fe1586e6863606ab18e85f3e35 (2019-01-10 14:51:43 -0500)
model: separate out TargetSpec and TargetStatus

model: separate out TargetSpec and TargetStatus

---

Gopkg.lock
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/option.go
vendor/github.com/windmilleng/wmclient/pkg/os/temp/temp.go

Hello @nicks,
1abf03e62f4cdb3a706d7f66e6f050ae5c4c3a04 (2019-01-14 13:08:05 -0500)
vendorr: update wmclient

vendorr: update wmclient

---

internal/engine/watchmanager.go
internal/ignore/path_matcher.go

this is what i meant by [this comment](https://github.com/windmilleng/tilt/pull/996#discussion_r247267603)

reduce Manifest interface redundancy

---

internal/engine/image_build_and_deployer.go
internal/model/deploy_info.go
internal/model/docker_info.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/model/target.go

Please review the following commits I made in branch nicks/validation:
06f27bfc135fb4dbab24c031ae285f61c98c6d9b (2019-01-10 17:59:08 -0500)
model: all target specs implement validation

model: all target specs implement validation

---

internal/store/subscriber_test.go

Hello @nicks,
6288ea1af8a018b841203e8ce1cc5d8ecc7c1554 (2019-01-14 17:34:36 -0500)
test: tweak timeouts a bit bc we're seeing timeouts on circleci but not locally

test: tweak timeouts a bit bc we're seeing timeouts on circleci but not locally

---

internal/engine/actions.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/extractors.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/model/deploy_info.go
internal/store/build_result.go

Please review the following commits I made in branch nicks/targets4:
803099dbed6c7350c300732fab8d26db278c9f0c (2019-01-15 14:40:39 -0500)
engine: BuildAndDeployer takes sets of targets and returns sets of results

engine: BuildAndDeployer takes sets of targets and returns sets of results

---

internal/engine/build_and_deployer_test.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/store/engine_state_test.go
internal/tiltfile/tiltfile_state.go

Hello @nicks,
Please review the following commits I made in branch nicks/imagetarget:
50c053f0249429a7bcc78de9b8fd1afb4abeb655 (2019-01-15 21:13:24 -0500)
model: add setter/getter for image target

model: add setter for image target

---

internal/engine/build_and_deployer_test.go
internal/model/manifest.go
internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_state.go

Hello @nicks,
Please review the following commits I made in branch nicks/deps:
061155d40c80faf5d84aa0b449bac6a2ec9c44d4 (2019-01-16 09:57:43 -0500)
model: remove some dead code

model: remove some dead code

---

internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/testdata_test.go
internal/k8s/testyaml/testyaml.go

Please review the following commits I made in branch nicks/targets2:
4c094161017904064902077d4d2ced98c05a688f (2019-01-15 18:09:31 -0500)
engine: ImageBuildAndDeployer supports multiple images

engine: ImageBuildAndDeployer supports multiple images

---

internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/flaky:
b2c961a29c02b69fddb50e22732740fcaae31e79 (2019-01-16 11:02:38 -0500)
engine: fix a flaky test with more build synchronization

engine: fix a flaky test with more build synchronization

---

internal/dockercompose/client.go
internal/dockercompose/fake_client.go

Get the Docker Container ID for for a docker compose service.

dockercompose: ContainerID method

---

internal/build/container_updater.go
internal/build/container_updater_test.go
internal/build/error.go
internal/engine/build_and_deployer_test.go
internal/synclet/synclet.go

Please review the following commits I made in branch nicks/ch1380/exit:
2f0f520a3e1112014978161531b7614f46307585 (2019-01-17 12:21:08 -0500)
build: more user-friendly error fallback for container update
Fixes https://github.com/windmilleng/tilt/issues/1029

build: more user-friendly error fallback for container update

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch1375/portforwards:
5b170a8a1dc0b1fadaa095f362fc2333c3393e85 (2019-01-17 13:04:48 -0500)
tiltfile: support port-forward strings like in kubectl/dc

tiltfile: support port-forward strings like in kubectl/dc

---

internal/synclet/sidecar/sidecar.go

96f7e80559ed6205a90fb07afed8f71d590bf487 (2019-01-17 13:21:34 -0500)
synclet: release the synclet! :squid:

synclet: release the synclet! :squid:

---

internal/git/gitignore_test.go

gitignore: add failing test for subdir

---

internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_state.go

for the sake of my next pr being a reasonable size, breaking out this stuff

tiltfile: reorg and rename how we assemble k8s resources, stub out docker compose resource methods

---

internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_state.go

Please review the following commits I made in branch maiamcc/tiltfile-dockerbuild-dc:
71bc1e0d1ba925d9a0740c07ad9402118ebea8ae (2019-01-24 18:21:13 -0500)
tests are great
2cf846b6e51d7747b2bda97cdb10393de654415c (2019-01-24 18:01:26 -0500)
dc_resource method
8be5a89b8483942ebbf75db638f0fad1d61140ba (2019-01-24 18:00:56 -0500)
break out getting image targets

tiltfile support for docker compose resource + tilt image build [ch1372]

---

Gopkg.lock
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/opt.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/option.go

Hello @nicks,
Please review the following commits I made in branch nicks/wmclient:
f6db357d62d78950c39943999034accedb7cd3a3 (2019-01-28 17:27:35 -0500)
vendor: upgrade wmclient

vendor: upgrade wmclient

---

Gopkg.lock
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/option.go

Hello @nicks,
Please review the following commits I made in branch nicks/ch1296/logs:
3b7ebf8030b28a4098abb84d4ad04c79ec71125b (2019-01-29 14:38:49 -0500)
vendor: update wmclient with new logging defaults

vendor: update wmclient with new logging defaults

---

.goreleaser.yml

Please review the following commits I made in branch nicks/goreleaser:
5891799b6945bf61170db2600bd5ae08f1829228 (2019-01-30 09:53:11 -0500)
goreleaser: add homebrew releaser

goreleaser: add homebrew releaser

---

internal/hud/resourceview.go
internal/tiltfile/tiltfile.go

the copy here was bugging me, tho i'll happily take suggestions as to
wording (or tell me that it was fine as it was).

hud: copy change for unresourced k8s

---

internal/dockercompose/client.go

this will hopefully be useful for our chat with PicnicHealth tomorrow

dockercompose: verbose mode for docker compose up/down according to log level

---

internal/build/options.go
internal/docker/client.go
internal/docker/fake_client.go
internal/docker/options.go

Please review the following commits I made in branch nicks/ch1453/private:
99087a43b42d6827f9dcff973d7ddc74c3033130 (2019-01-31 18:39:33 -0500)
docker: correctly set auth configs on ImageBuild

docker: correctly set auth configs on ImageBuild

---

Gopkg.lock
vendor/github.com/windmilleng/fsevents/go.mod

In an increasingly annoying quest to get tilt to build with go.mod

vendor: update go.mod

---

Gopkg.lock
internal/cli/analytics.go
internal/cli/analytics_test.go
vendor/github.com/whilp/git-urls/.travis.yml
vendor/github.com/whilp/git-urls/Makefile
vendor/github.com/whilp/git-urls/README.md
vendor/github.com/whilp/git-urls/urls.go

This will help give us an idea of how many of our users share a repo.

analytics: include hash of git origin url

---

internal/engine/image_build_and_deployer.go

Please review the following commits I made in branch maiamcc/only-synclet-fastbuild:
715c7179dd064b532a55a71fdc3e84f6b79bee1f (2019-02-07 17:05:37 -0500)
wip

only inject synclet for fastbuilds

---

internal/cli/analytics.go
internal/cli/analytics_test.go

analytics: fix git remote reporting

---

internal/k8s/client.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go
internal/k8s/pod.go
internal/k8s/pod_test.go

Hello @nicks,
1c035b963c76edc0d79cea8b9b0522d0e79a11ba (2019-02-11 16:52:40 -0500)
remove a bunch of dead code

remove a bunch of dead code

---

internal/tiltfile/docker_compose.go

this will save us .4s per dc.yml when loading manifests.
in particular, a big gain for tests:
```
$ # on master
$ go test github.com/windmilleng/tilt/internal/engine -count=1 && go test github.com/windmilleng/tilt/internal/tiltfile -count=1
ok  	github.com/windmilleng/tilt/internal/engine	15.682s
ok  	github.com/windmilleng/tilt/internal/tiltfile	14.437s
$ # on this branch
$ go test github.com/windmilleng/tilt/internal/engine -count=1 && go test github.com/windmilleng/tilt/internal/tiltfile -count=1
ok  	github.com/windmilleng/tilt/internal/engine	10.958s
ok  	github.com/windmilleng/tilt/internal/tiltfile	8.815s
```
So that's a savings of c. 10s per test suite run.

tiltfile: parallelize docker-compose config calls for faster manifest load [ch1201]

---

.goreleaser.yml

goreleaser: remove homebrew dependencies

---

internal/tiltfile/tiltfile_state.go

tiltfile: clean up a line of k8sResourceForImage

---

internal/dockerfile/ast.go
internal/dockerfile/dockerfile.go

Please review the following commits I made in branch nicks/dockerfileprinter:
04bb7093c1cbe75776c5c233e68894b8e7b89c24 (2019-02-14 15:37:27 -0500)
dockerfile: refactor into AST type

dockerfile: refactor into AST type

---

internal/build/cache_builder.go
internal/build/cache_builder_test.go
internal/engine/image_and_cache_builder.go

Please review the following commits I made in branch nicks/ch1596/cache:
bb33b93e672a74c39d5ec04e77372bb88e867a76 (2019-02-14 14:51:54 -0500)
build: bake the base dockerfile into the cache key

build: bake the base dockerfile into the cache key

---

internal/synclet/sidecar/sidecar.go

Please review the following commits I made in branch nicks/syncletrelease:
16da7c4a0096067dcdaaa35aa57da92549942e73 (2019-02-15 12:17:53 -0500)
release the synclet :squid:

release the synclet :squid:

---

internal/engine/pod_watch_test.go
internal/k8s/target.go
internal/model/deploy_info.go
internal/model/docker_info.go
internal/model/manifest.go
internal/model/target.go
internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/deps:
bb51db5a602dfbb0673c9464872a495f5d243deb (2019-02-15 15:18:59 -0500)
model: Add DependencyIDs to TargetSpec, so it looks more like a real graph

model: Add DependencyIDs to TargetSpec, so it looks more like a real graph

---

internal/dockerfile/dockerfile.go
internal/dockerfile/dockerfile_test.go
internal/model/docker_info.go
internal/tiltfile/build_index.go
internal/tiltfile/docker.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/findimages:
378f2e0e588320038faf387724d7b21243588de5 (2019-02-15 16:44:51 -0500)
tiltfile: infer image dependencies

tiltfile: infer image dependencies

---

internal/dockerfile/ast.go
internal/dockerfile/inject.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/target_queue.go
internal/engine/testdata_test.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/injectimages:
aa3b0264f20e9be52c0c81b77355a4f2881c6f3d (2019-02-15 18:22:46 -0500)
engine: inject image dependencies

engine: inject image dependencies

---

Gopkg.lock
internal/dockerfile/ast.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/bflag.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_nosecrets.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_runmount.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_secrets.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/errors_unix.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/errors_windows.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/parse.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/support.go

Hello @nicks,
Please review the following commits I made in branch nicks/instructions:
f1f3373331a77a94040266802e648a54ed6a4553 (2019-02-18 13:14:56 -0500)
vendor: buildkit instruction parser

vendor: buildkit instruction parser

---

Gopkg.lock
internal/tiltfile/build_index.go
internal/tiltfile/tiltfile_test.go
vendor/github.com/schollz/closestmatch/.travis.yml
vendor/github.com/schollz/closestmatch/LICENSE
vendor/github.com/schollz/closestmatch/Makefile
vendor/github.com/schollz/closestmatch/README.md
vendor/github.com/schollz/closestmatch/closestmatch.go

Please review the following commits I made in branch nicks/ch1448/matches:
c37f627423022fa1a868069fab6d99e8c909cb86 (2019-02-18 19:08:13 -0500)
tiltfile: add fuzzy matching suggestions to docker_build

tiltfile: add fuzzy matching suggestions to docker_build

---

internal/tiltfile/files.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

This will make setting up the GCP Microservices demo a lot simpler and bring it in line with [how easy it is to do in Skaffold](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/skaffold.yaml#L50).

tiltfile: add listdir function

---

DEVELOPING.md
README.md
ROADMAP.md
internal/engine/configs_controller.go
internal/store/engine_state.go
internal/tiltfile/tiltfile.go

Hello @nicks,
Please review the following commits I made in branch nicks/tilt.dev:
ff9856b636af070a2dc971859b37408ef46ee2fb (2019-02-19 17:59:51 -0500)
readme: update site references to tilt.dev

readme: update site references to tilt.dev

---

internal/build/test_utils.go
internal/cli/synclet.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/container/runtime.go
internal/container/runtime_test.go
internal/demo/script.go
internal/docker/client.go
internal/engine/build_and_deployer.go
internal/engine/image_build_and_deployer.go
internal/engine/mode.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go
internal/k8s/runtime.go
internal/synclet/wire.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/ch1634/container:
fa939ae6ac8e78d0d4a632308d7e6bb50dc1d21d (2019-02-19 17:42:49 -0500)
k8s: detect the container runtime

k8s: detect the container runtime

---

internal/build/test_utils.go
internal/cli/cli.go
internal/cli/doctor.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/docker/client.go
internal/k8s/client.go
internal/synclet/wire.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/ch1255/doctor:
6458d531623c253df30f20c87903a66b91b46879 (2019-02-20 16:14:49 -0500)
cli: The Doctor is IN

cli: The Doctor is IN

---

internal/engine/configs_controller_test.go
internal/engine/store_testutil.go
internal/engine/watchmanager_test.go
internal/store/store.go

these are changes I forgot to push to #1202 before merging.

engine: missed changes from #1202

---

internal/hud/renderer.go

hud: pending color for 'PodInitializing'

---

internal/model/deploy_info.go
internal/model/manifest_test.go

i know we're not actively developing this right now but i had an old
TODO that was bugging me and it took 5 minutes so ¯\_(ツ)_/¯

model: docker compose target validation

---

internal/container/container.go
internal/docker/image.go
internal/dockerfile/ast.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/k8s/image.go
internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/parse:
b07103888ea9a70aee09ce0df864f95a04d770f2 (2019-02-25 17:09:22 -0500)
container: centralize ref-parsing

container: centralize ref-parsing

---

internal/engine/buildcontroller_test.go
internal/engine/fake_notify_test.go
internal/engine/testdata_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/engine/watchmanager.go
internal/engine/watchmanager_test.go
internal/k8s/testyaml/testyaml.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/ch1655/manifests:
e4f658331ada8b82076052fff5d379845b3a4591 (2019-02-22 13:22:30 -0500)
engine: handle common image deps
Fixes https://github.com/windmilleng/tilt/issues/1197

engine: handle common image deps

---

internal/cli/build.go

Please review the following commits I made in branch maiamcc/increment-version:
5ac8d1030b52f3f6732d539bd740fdce5387ead6 (2019-02-25 17:59:43 -0500)
cli: increment version to 0.7.6

cli: increment version to 0.7.6

---

internal/engine/docker_compose_log_manager.go

7d2a6a866d5941365b9c9990b87072982ed3bcc7 (2019-02-26 14:29:50 -0500)
docker-compose: fix a flaky test

docker-compose: fix a flaky test

---

internal/build/image_builder.go
internal/build/test_utils.go
internal/cli/wire_gen.go
internal/engine/wire_gen.go
internal/output/output.go

Please review the following commits I made in branch nicks/stdout:
5eee8912a6eaccd61c202bed7a9f44b959d31da4 (2019-02-26 15:17:03 -0500)
wire: re-wire os.Stdout DI a bit

wire: re-wire os.Stdout DI a bit

---

internal/tiltfile/files.go
internal/tiltfile/tiltfile_test.go

tiltfile: add recursive option to listdir

---

internal/dockerfile/dockerfile.go
internal/dockerfile/dockerfile_test.go

Please review the following commits I made in branch nicks/baseimage:
b8e69a2413249e27e4b8e6ef3e31272609a8a7e8 (2019-02-28 14:40:27 -0800)
dockerfile: allow COPY --from in base images

dockerfile: allow COPY --from in base images

---

Makefile
internal/hud/server/assets.go
scripts/upload-assets.sh
web/package.json
web/src/App.js
web/src/AppController.js
web/src/index.js
web/yarn.lock

Please review the following commits I made in branch nicks/router:
9b463e36eea4a5b6c65f025a650ab326099b202b (2019-02-27 14:43:23 -0500)
web: add a little react router for starting new experiments
d0555f5a0bda8e4a21596e29afaaa3965a5efde0 (2019-02-27 12:42:30 -0500)
hud: serve web assets directly from Tilt

web: add a little react router for starting new experiments

---

internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/wire.go
internal/engine/wire_gen.go

Please review the following commits I made in branch nicks/skippushes:
58b684f216d54d7e6a088b6338c8d0fb5c184b6d (2019-02-28 19:20:40 -0800)
engine: skip unnecessary pushes

engine: skip unnecessary pushes

---

internal/build/options.go

Fix buildargs string to *string conversion

---

web/src/App.css
web/src/App.js
web/src/LoadingScreen.css
web/src/LoadingScreen.js
web/src/LogApp.css
web/src/LogApp.js
web/src/index.js

Please review the following commits I made in branch nicks/ch1694/logs:
cc1205a65ba5eeff2657b59ab71d2305a8975f2a (2019-02-27 14:58:25 -0500)
web: Demonstrate what a new experiment looks like
9b463e36eea4a5b6c65f025a650ab326099b202b (2019-02-27 14:43:23 -0500)
web: add a little react router for starting new experiments
d0555f5a0bda8e4a21596e29afaaa3965a5efde0 (2019-02-27 12:42:30 -0500)
hud: serve web assets directly from Tilt

web: Demonstrate what a new experiment looks like

---

internal/engine/build_and_deployer_test.go
internal/engine/buildcontroller.go
internal/engine/extractors.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper.go
internal/k8s/container.go
internal/store/build_result.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/fastbuild2:
48bea7425c8beba8d8e495e441da7ab993618a21 (2019-03-03 19:54:59 -0800)
support fast build container updates with image deps

support fast build container updates with image deps

---

tools/devlog/log_to_file.go

was getting frustrated trying to debug someting in the hud,
threw this together. does it seem useful? if it's not worth
merging into master, I can just hang onto it on local.

development/logging: logger that writes to file (for hud debugging)

---

web/package.json
web/src/LogApp.js
web/yarn.lock

Please review the following commits I made in branch nicks/ansi:
49061b0c9d7e12df00b36ad51e798b44952d6f07 (2019-03-07 12:52:02 -0500)
web: support ansi color codes

web: support ansi color codes

---

internal/engine/docker_compose_build_and_deployer.go
internal/engine/docker_compose_build_and_deployer_test.go

Please review the following commits I made in branch nicks/dcbuilds:
1d15a57c5a782ee50ddd8487c3ea82f788316e76 (2019-03-03 19:52:19 -0800)
engine: support multi-stage image builds in docker-compose

engine: support multi-stage image builds in docker-compose

---

internal/hud/view/view.go
internal/hud/view/view_test.go
internal/model/log.go

Please review the following commits I made in branch nicks/forbidprivate:
2ae73ef2d9484b732e9ffe482cb8c75f64b478f1 (2019-03-07 16:02:53 -0500)
hud: fix unexported fields that were missing from the web data

hud: fix unexported fields that were missing from the web data

---

internal/engine/upper_test.go

[This test](https://github.com/windmilleng/tilt/blob/c551d6634e155b02db10543131b3789ea33985ca/internal/engine/upper_test.go#L1319) was blocking until the `fakeBaD` had been called and then trying to deal with `PodChangeAction` depending on the pod's `DeployID` being updated in the `ManifestState`.
Because `fakeBaD` was writing to `b.calls` before it dispatched the `DeployIDAction`, sometimes the test would dispatch the `PodChangeAction` before `fakeBaD` dispatched the `DeployIDAction`, so the `PodChangeAction` would be ignored because it didn't match the (`0`) `DeployID` in the `ManifestState`.

upper_test: fix flaky deployid test

---

internal/tiltfile/docker_compose.go
internal/tiltfile/tiltfile_docker_compose_test.go

Please review the following commits I made in branch nicks/dcimage:
14389e5176cf29621b47555e403f847b197074b3 (2019-03-08 17:04:23 -0500)
docker-compose: auto-match image names

docker-compose: auto-match image names

---

internal/engine/upper.go
internal/hud/view/view.go
internal/store/engine_state.go
web/package.json
web/src/LogApp.css
web/src/LogApp.js
web/src/index.js
web/yarn.lock

Please review the following commits I made in branch nicks/ch1570/single:
5f603bd699c85241ef040642ae5d7b33ccbc1128 (2019-03-08 16:15:03 -0500)
web: create a web view for a single log
dd035e2b6427735f60edc0e06a4c0838265f3a76 (2019-03-08 14:16:32 -0500)
hud: fix an escaping bug in serialization

web: create a web view for a single log

---

internal/docker/client.go
internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/store/build_result.go

Please review the following commits I made in branch nicks/ch1750/dcfast:
3528436161098b2c69e464b9db1c2c421e36ac24 (2019-03-11 10:05:31 -0400)
engine: pass along the state needed for fast_build with docker-compose

engine: pass along the state needed for fast_build with docker-compose

---

internal/build/custom_builder.go
internal/build/test_utils.go
internal/cli/doctor.go
internal/cli/down.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/demo/script.go
internal/docker/client.go
internal/docker/client_test.go
internal/dockercompose/client.go
internal/engine/upper_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/k8s/ip.go
internal/minikube/docker.go
internal/minikube/fake.go
internal/synclet/wire.go
internal/synclet/wire_gen.go
internal/tiltfile/files.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/dockerenv:
16b7b92c05219f963194cb8a86c2998541327e4d (2019-03-08 18:18:47 -0500)
docker: unify environment overrides across docker client / custom build / docker compose

docker: unify environment overrides across docker client / custom build / docker compose

---

internal/container/selector.go
internal/dockerfile/inject_test.go
internal/engine/image_build_and_deployer.go
internal/k8s/image.go
internal/k8s/image_test.go
internal/model/manifest.go
internal/synclet/sidecar/inject.go
internal/synclet/sidecar/sidecar_test.go
internal/tiltfile/build_index.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch1654/matchers:
d776dc3bfed3d95d5bbb86f16eded829c3b4ca0d (2019-03-12 17:06:04 -0400)
tiltfile: support multiple images with the same name but different tag
Fixes https://github.com/windmilleng/tilt/issues/1259

tiltfile: support multiple images with the same name but different tag

---

internal/cli/build.go
internal/cli/build_test.go

Please review the following commits I made in branch nicks/dev:
44aee890e88a28255b5b60459a9125896463b667 (2019-03-13 13:29:39 -0400)
cli: fix up the web version in dev :embarrassed:

cli: fix up the web version in dev :embarrassed:

---

internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/hud/hud.go
internal/model/web.go

Please review the following commits I made in branch nicks/ch1676/keys:
4149b76ed4bbb6ebe15b994ec61ed1d2efc06ffe (2019-03-11 13:29:45 -0400)
hud: add key shortcuts for the web view

hud: add key shortcuts for the web view

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

to allow the fully specified group/version/kind instead of just the ambiguous kind

tiltfile: add group and version to k8s_kind/k8s_image_json_path

---

internal/cli/wire_gen.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/extractors.go
internal/engine/local_container_build_and_deployer.go
internal/engine/wire_gen.go

Please review the following commits I made in branch nicks/dcimage4:
10fa555e9e7a75144305b6cc7abee82e56862927 (2019-03-12 21:08:59 -0400)
engine: fix up dc deploys when tilt is configured to talk to k8s

engine: fix up dc deploys when tilt is configured to talk to k8s

---

internal/tiltfile/tiltfile_test.go

These broke as a mix of #1323 and #1298

tiltfile: fix tests

---

internal/engine/upper.go
internal/store/engine_state.go
web/package.json
web/src/LogApp.css
web/src/LogApp.js
web/src/index.js
web/yarn.lock

Please review the following commits I made in branch nicks/ch1835/links:
d09ddf599c5f7a1aff1182ae7fedacba97b90e46 (2019-03-15 12:36:32 -0400)
web: Add a log select box

web: Add a log select box

---

web/src/LogApp.js

Hello @nicks,
Please review the following commits I made in branch nicks/scroll:
ca0ee18bc8f508ba91c315564a2a79bdb0753b19 (2019-03-15 18:16:51 -0400)
web: fix a minor auto-scroll bug

web: fix a minor auto-scroll bug

---

internal/docker/fake_client.go
internal/engine/build_and_deployer.go
internal/engine/build_and_deployer_test.go
internal/engine/docker_compose_build_and_deployer.go

Please review the following commits I made in branch maiamcc/weird-dcbad-err-msg:
adc40817017fc3adda8765ce8e94cdb554ab5d88 (2019-03-15 15:27:45 -0400)
engine: if all BaD calls fail, return last UNEXPECTED error [ch1854]
6b72d020648b56b15ada3b94d84dfaf38ae7854a (2019-03-15 15:23:23 -0400)
wip

engine: if all BaD calls fail, return last UNEXPECTED error [ch1854]

---

internal/hud/view/view.go
internal/store/engine_state.go
web/src/K8sApp.js
web/src/K8sApp.scss
web/src/LogApp.js
web/src/ResourceList.js
web/src/index.js

Please review the following commits I made in branch nicks/ch1759/yaml:
3bf1f91b1b57ce25fa3346453a3107137420506f (2019-03-18 11:35:57 -0400)
web: add a view of the yaml for each k8s resource

web: add a view of the yaml for each k8s resource

---

Makefile

Tests are sometimes timing out on my machine

makefile: Increase test timeout

---

internal/container/default_registry.go
internal/container/default_registry_test.go
internal/container/selector.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/docker_compose_build_and_deployer_test.go
internal/engine/image_and_cache_builder.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/imagecontroller.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/k8s/container_test.go
internal/k8s/image_test.go
internal/model/custom_build_test.go
internal/model/docker_info.go
internal/model/manifest_test.go
internal/store/build_result.go
internal/tiltfile/build_index.go
internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

docs [here](https://github.com/windmilleng/tilt.build/pull/82)

tiltfile: add default_registry

---

Makefile
integration/dc_fixture_test.go
integration/dcbuild/Dockerfile
integration/dcbuild/Tiltfile
integration/dcbuild/cmd/dcbuild/main.go
integration/dcbuild/docker-compose.yaml
integration/dcbuild_test.go
integration/dcfastbuild/Dockerfile
integration/dcfastbuild/Tiltfile
integration/dcfastbuild/cmd/dcfastbuild/main.go
integration/dcfastbuild/docker-compose.yaml
integration/dcfastbuild_test.go
integration/fixture_test.go
integration/k8s_fixture_test.go
integration/onedc/docker-compose.yaml
integration/onedc_test.go
integration/onewatch/Tiltfile

Please review the following commits I made in branch nicks/dcimage3:
64df29015aa4f94113929304838132334c141b35 (2019-03-19 18:52:41 -0400)
integration: add more docker-compose integration tests

integration: add more docker-compose integration tests

---

Makefile
integration/dc_fixture_test.go
integration/dcbuild_test.go
integration/dcfastbuild_test.go
integration/fixture_test.go
integration/imagetags/Tiltfile
integration/imagetags/app-stretch.yaml
integration/imagetags/app-stretch/Dockerfile
integration/imagetags/app.yaml
integration/imagetags/app/Dockerfile
integration/imagetags/common-stretch/Dockerfile
integration/imagetags/common-stretch/message.txt
integration/imagetags/common/Dockerfile
integration/imagetags/common/message.txt
integration/imagetags_test.go
integration/k8s_fixture_test.go
integration/onedc_test.go
integration/onewatch_test.go

Please review the following commits I made in branch nicks/ch1941/integration:
921d95eb08dfec4f87502a8abb9b1ba7a1700b03 (2019-03-20 16:35:48 -0400)
integration: add tests for multiple images with same tag

integration: add tests for multiple images with same tag

---

internal/watch/notify_test.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/ch1947/reload:
d2306dffadf3db80e384092ee8cc7fe4a589c46b (2019-03-22 16:00:50 -0400)
watch: tfw you have a test that asserts broken file-watch behavior :cry:

watch: tfw you have a test that asserts broken file-watch behavior :cry:

---

DEVELOPING.md

Please review the following commits I made in branch nicks/ch1946/profiling:
acbebcb234711217db4862457030b7e72335de97 (2019-03-22 16:52:33 -0400)
developing: add documentation on profiling/pprof

developing: add documentation on profiling/pprof

---

internal/tiltfile/docker.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch1887/profiling:
e82f1c4145e5a19123401970841d8786a32232a7 (2019-03-22 17:39:41 -0400)
tiltfile: fix some bad attr implementations

tiltfile: fix some bad attr implementations

---

web/src/HUD.js
web/src/HUD.scss
web/src/HUD.test.js
web/src/K8sViewPane.js
web/src/LogApp.js
web/src/LogViewPane.js
web/src/NoMatch.js
web/src/PreviewPane.js
web/src/ResourceViewPane.js
web/src/Sidebar.js
web/src/Sidebar.scss
web/src/Statusbar.js
web/src/Statusbar.scss
web/src/constants.scss
web/src/index.js

Please review the following commits I made in branch nicks/ch1956/router:
ef2f09642337e6347a9ac94ed3859a92f14207b4 (2019-03-22 15:20:51 -0400)
web: stub out components

web: stub out components

---

internal/hud/server/server.go
internal/hud/server/view.go
internal/hud/server/view_test.go
internal/hud/server/websocket.go
internal/hud/webview/view.go
internal/hud/webview/view_test.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/ch1955/fork:
d276d955b1e35636a614b570a6052927d4d4f0e8 (2019-03-21 17:33:42 -0400)
hud: fork view into two data structures: webview and view

hud: fork view into two data structures: webview and view

---

web/package.json
web/src/App.js
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/yarn:
0c345dc4e62631d870c13ac0bfbbc428e639186b (2019-03-26 13:48:58 -0400)
web: upgrade enzyme test library, which broke support for React.Fragment but fixed support for other things

web: upgrade enzyme test library, which broke support for React.Fragment but fixed support for other things

---

web/package.json
web/src/LogApp.tsx
web/src/react-app-env.d.ts
web/tsconfig.json
web/yarn.lock

Mostly just putting a bunch of `any` types in places unless a better typt was obvious. We can fill them in later, or not at all.
@nicks if you think this will be more trouble than it's worth, that's fine by me and I'll close this PR. As a JavaScript foreigner I like the types safety blanket but I can live without it.
Also create-react-app makes this so easy! 🎉

web: use TypeScript for log app

---

internal/build/boil_runs.go
internal/build/boil_runs_test.go
internal/build/container_test.go
internal/build/container_updater.go
internal/build/container_updater_test.go
internal/build/docker_benchmark_test.go
internal/build/image_builder.go
internal/build/image_builder_test.go
internal/docker/fake_client.go
internal/engine/image_and_cache_builder.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/ignore/path_matcher.go
internal/model/docker_info.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/model/squash.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch maiamcc/steps-runs:
b596d06289d49bc54aeca135bb8a6742f139dec4 (2019-03-26 16:39:23 -0400)
naming: s/fastbuild.step/fastbuild.run (soon we'll implement liveUpdate and 'step' will be distinct from 'run')

naming: s/fastbuild.step/fastbuild.run (soon we'll implement liveUpdate and 'step' will be distinct from 'run')

---

web/src/HUD.js
web/src/Sidebar.scss
web/src/Sidebar.tsx
web/src/text.scss

Please review the following commits I made in branch nicks/ch1960/sidebar:
a5b8615bba0ccd0a4301eba7921cb57827ee423a (2019-03-27 17:37:07 -0400)
web: implement sidebar mocks

web: implement sidebar mocks

---

web/package.json
web/tsconfig.json
web/yarn.lock

which includes typescript perf improvements

web: upgrade to create-react-app 2.1.8

---

internal/model/target.go
internal/model/target_test.go

Please review the following commits I made in branch nicks/top:
44209ed8245a4f19845fbd4448142dfcf97fa7ee (2019-03-28 13:08:27 -0400)
model: helper function for topologically sorting targets

model: helper function for topologically sorting targets

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/image_build_and_deployer.go

Please review the following commits I made in branch maiamcc/synclet-inject:
5c147e66573148b9c31eb995ebe36e7d377e6346 (2019-03-28 17:29:48 -0400)
engine: inject synclet if image target has a LiveUpdate [ch2040]

engine: inject synclet if image target has a LiveUpdate [ch2040]

---

web/src/LogPane.tsx

Story details: https://app.clubhouse.io/windmill/story/2049

web: actually set state in autoscroll timeout

---

internal/hud/hud.go

Story details: https://app.clubhouse.io/windmill/story/1964

hud: make TUI log key controls direct to web

---

internal/model/live_update.go
internal/model/live_update_test.go
internal/tiltfile/live_update.go
internal/tiltfile/live_update_test.go
internal/tiltfile/tiltfile_state.go

also, require that sync dests be absolute

live_update: remove work_dir

---

.circleci/config.yml

I missed the whole point in #1399!

ci: actually report the integration test results

---

Makefile
integration/dcbuild/Dockerfile
integration/dcfastbuild/Dockerfile
integration/live_update/Dockerfile
integration/onedc/Dockerfile
integration/oneup/Dockerfile
integration/oneup_custom/Dockerfile
integration/onewatch/Dockerfile
integration/onewatch_exec/Dockerfile

Hello @nicks,
0a8e626ed28ac463cfe55c1aaba1b2506011cac9 (2019-04-02 14:35:07 -0400)
integration: only use alpine images and bump timeout

integration: only use alpine images and bump timeout

---

internal/engine/upper_test.go
internal/hud/server/assets.go
internal/hud/server/controller.go
internal/hud/server/websocket.go
internal/store/store.go
internal/store/subscriber.go
internal/store/subscriber_test.go

Please review the following commits I made in branch nicks/ch2025/webpack:
132d5926a755d49301300b54ea51b050ddd96afe (2019-04-02 13:06:27 -0400)
hud: better control of webpack shutdown

hud: better control of webpack shutdown

---

internal/hud/hud.go
web/src/AppController.ts
web/src/LogPane.tsx

Please review the following commits I made in branch nicks/polish:
cea3d60e911cc3b01e028c6a802f0722237b0877 (2019-04-02 16:32:21 -0400)
web: minor bug fixes

web: minor bug fixes

---

DEVELOPING.md
internal/cli/build.go
internal/cli/build_test.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/hud/server/assets.go
internal/model/web.go

Please review the following commits I made in branch nicks/ch2066/mode:
1bb5a89c05b2eda00d28dd9ecf3a8c8542bc7d75 (2019-04-02 15:40:14 -0400)
web: default to web-mode=local when building from HEAD

web: default to web-mode=local when building from HEAD

---

internal/hud/hud.go

5a03b5397af894c07a48749e5d81d2552952cf23 (2019-04-03 13:11:48 -0400)
Revert "Revert "hud: make TUI log key controls direct to web (#1391)" (#1398)"
This reverts commit 6fd1fdd696d9c91d710a991b42621b6286227388.

Revert "Revert "hud: make TUI log key controls direct to web (#1391)" (#1398)"

---

web/src/Sidebar.tsx
web/src/Statusbar.test.tsx
web/src/Statusbar.tsx
web/src/__snapshots__/Statusbar.test.tsx.snap
web/src/status.test.tsx
web/src/status.tsx
web/src/testdata.test.tsx
web/src/time.tsx

Please review the following commits I made in branch nicks/status:
76332bfaa955751a39c383c4d15f742ba43bed3a (2019-04-03 13:58:48 -0400)
web: unify right sidebar status and statusbar status

web: unify right sidebar status and statusbar status

---

Makefile
internal/cli/up.go
internal/hud/server/assets.go
internal/model/web.go

Please review the following commits I made in branch nicks/prebuilt:
02fd66b7275b112703d2ffa5388ea4553ad91da4 (2019-04-04 11:31:29 -0400)
web: add a precompiled mode

web: add a precompiled mode

---

internal/dockercompose/state.go
internal/engine/upper_test.go
internal/hud/hud.go
internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/resourceview.go
internal/hud/server/view.go
internal/hud/tabview.go
internal/hud/view/view.go
internal/hud/webview/view.go
internal/model/log.go
internal/store/engine_state.go

31619f63bf73801671d7f5f1d4e53e30a197ae54 (2019-04-04 11:51:58 -0400)
hud: cut out some log copying

hud: cut out some log copying

---

internal/hud/hud.go
internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/tabview.go
internal/hud/view/view.go

Please review the following commits I made in branch nicks/experiment:
78693ee937848d137a84023a32af8de10014e305 (2019-04-04 12:16:47 -0400)
hud: remove tab experiment

hud: remove tab experiment

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/model/live_update.go
internal/model/live_update_test.go
internal/model/matcher.go
internal/tiltfile/docker.go
internal/tiltfile/live_update.go
internal/tiltfile/live_update_test.go

Hello tbd,
Please review the following commits I made in branch maiamcc/fall-back-on:
956afb14ca1911f5e272f9f34f80cbcbbf03df1c (2019-04-04 17:46:54 -0400)
model: update LiveUpdate internals to s/fullRebuildTriggers/FallBackOn, and include those as steps

model: update LiveUpdate internals to s/fullRebuildTriggers/FallBackOn, and include those as steps

---

internal/engine/upper.go
internal/engine/upper_test.go
internal/store/engine_state.go

a7af1f546a1ccc95f48495a6e6abae603a9f0bff (2019-04-05 10:40:58 -0400)
store: remove pre-restart log. now that we use CombinedLog, it's not necessary

store: remove pre-restart log. now that we use CombinedLog, it's not necessary

---

internal/store/subscriber_test.go

Hello @nicks,
940872e59768f70c797f9f4082358f0cb4f163cb (2019-04-05 18:38:20 -0400)
store: fix a flaky test

store: fix a flaky test

---

internal/hud/server/assets.go

Before:
```
> tilt up
Error: Installing Tilt webpack deps: exit status 1
```
After:
```
> tilt up
Error: Error installing Tilt webpack deps:
stdout:
yarn install v1.15.2
info If you think this is a bug, please open a bug report with the information provided in "/Users/dan/go/src/github.com/windmilleng/tilt/web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
stderr:
error An unexpected error occurred: "/Users/dan/go/src/github.com/windmilleng/tilt/web/package.json: Unexpected token } in JSON at position 857".
error: exit status 1
```

hud: better error message if `yarn install` fails

---

internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/resourceview.go
internal/hud/server/view.go
internal/hud/tabview.go
internal/hud/text.go
internal/hud/view/view.go
internal/hud/webview/view.go
internal/model/log.go
internal/model/log_test.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/abbrev2:
feca731fb5e346f88e0078792dc47d690651f119 (2019-04-05 18:58:02 -0400)
hud: truncate the logs pre-render

hud: truncate the logs pre-render

---

internal/ospath/ospath.go
internal/tiltfile/docker.go
internal/tiltfile/live_update_test.go

realized i missed a case for these two tickets!

tiltfile: check that sync src and fall_back_on files are children of customBuild deps [ch2057 ch2089]

---

internal/cli/wire_gen.go
internal/hud/server/server.go
internal/hud/server/server_test.go

Part 1/2.
Part 2 will add code to the frontend to call this endpoint at the appropriate times.
Right now it only supports incrementing keys.

hud: analytics endpoint

---

web/src/Sidebar.scss
web/src/Sidebar.test.tsx
web/src/Sidebar.tsx
web/src/Statusbar.scss
web/src/Statusbar.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/constants.scss
web/src/status.tsx

Please review the following commits I made in branch nicks/ch2210/web-warning:
e60bd99bc5715a81107f2d737547a28b89194f6d (2019-04-09 13:32:19 -0400)
web: add a warning icon

web: add a warning icon

---

web/src/Sidebar.test.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Please review the following commits I made in branch nicks/fix:
eb9556f788da853d6835339558d2b60431f53e85 (2019-04-10 12:00:28 -0400)
web: fix master

web: fix master

---

internal/engine/upper_test.go
internal/hud/fake_hud.go
internal/hud/server/view.go
internal/hud/server/view_test.go
internal/hud/view/view.go
internal/hud/webview/view.go
internal/store/engine_state.go
internal/store/engine_state_test.go
web/src/Sidebar.tsx

Please review the following commits I made in branch nicks/ch2203/tiltfile:
683ce40d634a624cc05776193ff47a490d19ce2b (2019-04-09 18:01:22 -0400)
hud: move tiltfile to the top

hud: move tiltfile to the top

---

web/src/Sidebar.test.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Hello @nicks,
Please review the following commits I made in branch nicks/endpoints:
c0959a3ba32ef14f66e4f8b4992e566611088dee (2019-04-10 16:40:37 -0400)
web: use the normal test data so that this test stops breaking

web: use the normal test data so that this test stops breaking

---

internal/hud/server/assets.go
internal/hud/server/controller.go
internal/network/port.go

Please review the following commits I made in branch nicks/porterror:
da887c165f7acc6638e38dddf26d408e71d38868 (2019-04-10 16:29:09 -0400)
server: improve port-binding error message

server: improve port-binding error message

---

web/src/LogPane.scss
web/src/LogPane.tsx
web/src/__snapshots__/LogPane.test.tsx.snap
web/src/constants.scss

Please review the following commits I made in branch nicks/ch2231/colors:
12c1ff577720086a74395b9bf96347c516a57e5a (2019-04-10 16:11:58 -0400)
web: update ansi colors to match brand colors

web: update ansi colors to match brand colors

---

internal/tiltfile/k8s.go

1. fix url
2. add a "just try this!" line

tiltfile: fix resource assembly deprecation message

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/subscribers.go
internal/engine/upper.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/subscribers:
98196b5329be425f5f9db2fcfce1167cd83ee693 (2019-04-12 11:44:14 -0400)
engine: pull subscribers into their own wire provider

engine: pull subscribers into their own wire provider

---

Makefile
cmd/sail/main.go
internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/subscribers.go
internal/model/sail.go
internal/sail/client/client.go
internal/sail/sail.go
internal/sail/server/server.go

Please review the following commits I made in branch nicks/sail:
6c947fa9453b936293265cede5b2c4dc2345eaae (2019-04-12 12:16:59 -0400)
sail: no-op sail server that just prints "connected"

sail: no-op sail server that just prints "connected"

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/podlogmanager_test.go
internal/sail/client/client.go
internal/sail/client/client_test.go
internal/sail/client/conn.go
internal/sail/client/wire.go
internal/sail/server/room.go
internal/sail/server/server.go

Please review the following commits I made in branch nicks/sailclient:
365859eff791544823b415096aff9bc72508b17d (2019-04-12 15:02:12 -0400)
sail: stream data from the client to the server

sail: stream data from the client to the server

---

internal/sail/server/room.go
internal/sail/server/room_test.go

Please review the following commits I made in branch nicks/room:
d91168b402ebf11eee5501a01b434628fc86157b (2019-04-15 12:12:39 -0400)
sail: add websocket fan-out

sail: add websocket fan-out

---

web/src/LogPane.tsx

Please review the following commits I made in branch nicks/ch2263/scroll:
a6ded38e32463d96a086ec2571b938337ac14cf9 (2019-04-15 12:53:54 -0400)
web: cancel auto-scroll on mousewheel up

web: cancel auto-scroll on mousewheel up

---

internal/sail/server/room.go
internal/sail/server/room_test.go

7bf7d5a1f4b66220bc80cbcbf51a365ec78201f9 (2019-04-16 17:19:57 -0400)
sail: fix some race conditions in the room test

sail: fix some race conditions in the room test

---

internal/hud/server/assets.go
internal/hud/server/controller.go
internal/network/port.go
internal/network/port_test.go
internal/sail/sail.go

Please review the following commits I made in branch nicks/localhost:
d9a111a4d442e5831e8b14ffb4a5281efdb9b13d (2019-04-16 14:03:35 -0400)
network: clean up port-binding logic a bit

network: clean up port-binding logic a bit

---

DEVELOPING.md

Hello @nicks,
Please review the following commits I made in branch nicks/goimports:
a067e5030324c658fef038df4111a1e8c24bf8f1 (2019-04-18 11:02:48 -0400)
add goimports to DEVELOPING.md

add goimports to DEVELOPING.md

---

web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/LogPane.scss
web/src/PreviewPane.scss
web/src/Sidebar.scss
web/src/Sidebar.test.tsx
web/src/Sidebar.tsx
web/src/Statusbar.scss
web/src/TabNav.scss
web/src/TabNav.test.tsx
web/src/TabNav.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/__snapshots__/TabNav.test.tsx.snap
web/src/constants.scss
web/src/types.ts

web: tab nav lives above main pane instead of in sidebar

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

some of the errors/warnings as they appear in the hud:

tiltfile: make v2 assembly the default

---

web/src/HUD.tsx
web/src/PathBuilder.test.tsx
web/src/PathBuilder.tsx
web/src/Sidebar.test.tsx
web/src/Sidebar.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

Please review the following commits I made in branch nicks/ch2307/links:
94996027a6719309f262c967fec81719678e7723 (2019-04-18 12:30:41 -0400)
web: Add a PathBuilder for constructing links

web: Add a PathBuilder for constructing links

---

web/src/AnsiLine.tsx
web/src/ErrorPane.scss
web/src/ErrorPane.test.tsx
web/src/ErrorPane.tsx
web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/LogPane.scss
web/src/LogPane.tsx
web/src/Sidebar.tsx
web/src/Statusbar.tsx
web/src/TabNav.test.tsx
web/src/TabNav.tsx
web/src/__snapshots__/ErrorPane.test.tsx.snap
web/src/__snapshots__/LogPane.test.tsx.snap
web/src/__snapshots__/TabNav.test.tsx.snap
web/src/types.ts

web: error pane

---

internal/model/sail.go
internal/sail/client/client.go
internal/sail/client/client_test.go
internal/sail/client/roomer.go
internal/sail/server/room.go
internal/sail/server/server.go
internal/sail/server/server_test.go

Hello @landism, @dmiller,
Please review the following commits I made in branch maiamcc/sail-room-id-model:
7aa1f886740963c93c2c07351c3e2138ec69cb2a (2019-04-24 16:04:50 -0400)
sail: make RoomID a common type

sail: make RoomID a common type

---

web/src/Statusbar.scss
web/src/Statusbar.tsx
web/src/__snapshots__/Statusbar.test.tsx.snap
web/src/mostRecentBuild.test.ts
web/src/mostRecentBuild.ts
web/src/types.ts

web: show last edited file in statusbar

---

web/src/LogPane.tsx

Please review the following commits I made in branch nicks/scroll:
3aa4d10e1ee504b341cf88e9b16a010d1e45a3ba (2019-04-25 12:57:49 -0400)
web: add a little debouncer to wheel autoscroll

web: add a little debouncer to wheel autoscroll

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/build_and_deployer_test.go
internal/engine/extractors.go
internal/engine/image_and_cache_builder.go
internal/engine/image_build_and_deployer.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/model/custom_build_test.go
internal/model/docker_info.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/nullability:
81068ccb63afe3dc1bfb9e881a3f1f1b9d6c91ad (2019-04-25 15:09:08 -0400)
engine: fix a bunch of bugs around live update where we needed both nil checks and Empty() checks

engine: fix a bunch of bugs around live update where we needed both nil checks and Empty() checks

---

internal/engine/extractors.go
internal/engine/local_container_build_and_deployer.go
internal/engine/synclet_build_and_deployer.go
internal/engine/upper_test.go
internal/model/extractors.go

Hello @nicks,
Please review the following commits I made in branch nicks/extract:
ad030a13b73e6401645f19b23786ffa3677f6a31 (2019-04-26 13:11:07 -0400)
model: move some functions for working with lists of targets to the model package

model: move some functions for working with lists of targets to the model package

---

internal/cli/build.go

Please review the following commits I made in branch maiamcc/dev-version-0.8.1:
a83bec7daee6d25a92b718ea9079ee044ccd0554 (2019-04-26 13:54:23 -0400)
bump dev version

bump dev version

---

internal/cli/wire_gen.go
internal/engine/subscribers.go
internal/hud/server/controller.go
internal/hud/server/server.go
internal/hud/server/server_test.go
internal/hud/server/websocket.go
internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/sail/client/client.go
internal/sail/client/client_test.go
internal/sail/client/conn.go
internal/sail/client/fake_client.go
internal/sail/client/roomer.go
internal/sail/client/wire.go
web/src/SailInfo.tsx
web/src/__snapshots__/TopBar.test.tsx.snap

sail/web: button to trigger sail room join [ch2282]

---

Gopkg.lock
internal/tiltfile/files.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
vendor/github.com/ghodss/yaml/.gitignore
vendor/github.com/ghodss/yaml/.travis.yml
vendor/github.com/ghodss/yaml/LICENSE
vendor/github.com/ghodss/yaml/README.md
vendor/github.com/ghodss/yaml/fields.go
vendor/github.com/ghodss/yaml/yaml.go

Similar to the `read_json` function. You can pass a `.yaml` file to `read_yaml` in the Tiltfile. The function will parse the yaml and return a dictionary.

Read yaml function

---

internal/hud/server/websocket.go
internal/hud/server/websocket_test.go
internal/store/store.go

Please review the following commits I made in branch nicks/ch2404/concurrent:
cc6e31eab5afb58a705faba19ff4832e3f12e4c4 (2019-04-30 19:50:57 -0400)
shud: handle websocket concurrency better

shud: handle websocket concurrency better

---

web/src/HUD.tsx
web/src/PreviewList.scss
web/src/PreviewList.test.tsx
web/src/PreviewList.tsx
web/src/Sidebar.tsx
web/src/__snapshots__/PreviewList.test.tsx.snap

It looks extremely basic, but Han and I are going to refine it later.

web: implement "all" preview view

---

web/src/ErrorPane.tsx
web/src/LogPane.scss
web/src/LogPane.tsx
web/src/PreviewList.scss
web/src/PreviewList.tsx
web/src/PreviewPane.tsx
web/src/__snapshots__/PreviewList.test.tsx.snap

web: polish layout for "ALL" Preview

---

web/src/ErrorPane.scss
web/src/LogPane.tsx
web/src/PathBuilder.tsx
web/src/Sidebar.tsx
web/src/Statusbar.tsx
web/src/TabNav.tsx
web/src/analytics.ts

Using === instead of ==, analytics incr somehow got deleted, etc

web: misc cleanup

---

internal/engine/upper_test.go
internal/engine/watchmanager_test.go
internal/git/gitignore.go
internal/git/gitignore_test.go
internal/ignore/path_matcher.go
internal/model/manifest.go
internal/model/manifest_test.go
internal/tiltfile/docker.go
internal/tiltfile/files.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/ch2416/ignore:
c1423518759365530648397a5395a2fcb40536dd (2019-05-02 13:14:54 -0400)
ignore: don't use gitignore now that we have tiltignore

ignore: don't use gitignore now that we have tiltignore

---

web/src/ErrorPane.test.tsx
web/src/HUD.test.tsx
web/src/__snapshots__/ErrorPane.test.tsx.snap

Hello @nicks,
Please review the following commits I made in branch nicks/jstest:
dd0b58b4d5c46e9a3f99487b59c3f4c0e2272639 (2019-05-02 18:54:35 -0400)
web: fix snapshot tests

web: fix snapshot tests

---

internal/cli/build.go

Hello @nicks,
844e89ab6929a271b58f0a9d63b5ec6ebe58f995 (2019-05-02 18:39:27 -0400)
bump version

bump version

---

internal/sliceutils/sliceutils.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/msg:
ec3fe8fc76aaa68db319bc0c776bf922cb5fa426 (2019-05-06 11:54:44 -0400)
tiltfile: improve error message when services on the cli aren't found

tiltfile: improve error message when services on the cli aren't found

---

internal/k8s/client.go
internal/k8s/client_test.go

Please review the following commits I made in branch maiamcc/immutable-field-err:
e695be25b6672aa5d888796608608e5850e5f922 (2019-05-07 15:25:38 -0400)
k8s: don't accidentally treat 'unable to create new content in terminating namespace' errors as 'immutable field' errors

k8s: don't accidentally treat 'unable to create new content in terminating namespace' errors as 'immutable field' errors

---

internal/sail/sail.go
internal/sail/server/server.go

Please review the following commits I made in branch nicks/saillogs:
37eb09ba2b72daad0a0cff5a162e57de071cbc53 (2019-05-07 18:27:21 -0400)
sail: add structured logging

sail: add structured logging

---

internal/engine/upper_test.go

test for [this issue](https://app.clubhouse.io/windmill/story/1967/tilt-up-watch-false-doesn-t-work-anymore) -- unit test version of #1591

engine: unit test for `tilt up --watch=false` with no explictly named

---

internal/assets/server.go

I kept finding this jarring and annoying on startup. This still ain't pretty, but it's maybe a little better?

web: nicer connection refused error with web-mode local

---

Makefile
deployments/sail-networking.yaml
deployments/sail.dockerfile
deployments/sail.yaml

Please review the following commits I made in branch nicks/ch2361/prod:
621582a14717b73d91d06bd3635bfc28fc3b2300 (2019-05-08 12:28:47 -0400)
sail: deployment rules

sail: deployment rules

---

internal/engine/analytics_reporter.go
internal/engine/analytics_reporter_test.go

We have stats that can stand in for these with varying effectiveness -- calls to `sync()` are a basically 1:1 stand-in for use of LiveUpdate, but the best stats we have for use of FastBuild are calls to `fast_build()`, which ignore use of nested FastBuilds. So, trying to make stats better.

engine/analytics: stats for anyfastbuild, liveupdate

---

internal/cli/up.go
internal/cli/up_test.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/model/sail.go
web/src/PathBuilder.test.tsx
web/src/PathBuilder.tsx
web/src/SailInfo.tsx
web/src/analytics.ts

Please review the following commits I made in branch nicks/ch2490/sail:
a5bc6ba04f47cf83d357e3b0959f39f287d0ac77 (2019-05-08 17:55:27 -0400)
cli: configure sail instance and fix bugs in the web ui around http vs https

cli: configure sail instance and fix bugs in the web ui around http vs https

---

web/src/PathBuilder.test.tsx
web/src/PathBuilder.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/wss:
f83afcd3c8b198b89be3db565527c9e8a6a0351d (2019-05-09 14:56:31 -0400)
web: fix a bug that broke the ui. host vs hostname :shakes fist:

web: fix a bug that broke the ui. host vs hostname :shakes fist:

---

internal/cli/down.go
internal/cli/wire_gen.go
internal/demo/script.go
internal/engine/configs_controller.go
internal/engine/upper_test.go
internal/hud/server/controller.go
internal/hud/server/server.go
internal/hud/server/server_test.go
internal/hud/server/websocket.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/autoopen:
c1e59cd758da437a3764cd694921446e3c178b31 (2019-05-10 13:26:41 -0400)
server: only open the browser window if there isn't one open already

server: only open the browser window if there isn't one open already

---

DEVELOPING.md

Please review the following commits I made in branch nicks/gopath:
450aa997587baee097964e221be06c271adf8c12 (2019-05-13 13:27:44 -0400)
developing: add a small note about checking out code with Go tooling

developing: add a small note about checking out code with Go tooling

---

internal/cli/up.go

Hello @nicks,
Please review the following commits I made in branch nicks/browser:
b281934b4af46321ddd7adcfa0e7345b09bc725c (2019-05-14 19:01:08 -0400)
remove an old flag

remove an old flag

---

internal/cli/analytics.go
internal/hud/webview/analytics_nudge.go

This will make it easier for me to develop this feature,
though if this seems too risky I can omit.

cli: don't ask for analytics opt on startup if newAnalyitcs flag is set

---

Gopkg.lock

I uh, _assume_ this isn't just weirdness with my local go setup?

vendor: run dep ensure

---

internal/k8s/watch.go

Please review the following commits I made in branch nicks/runtime:
e64451994248ac980ab5a6b598ecdb3dbe902a0b (2019-05-16 17:51:56 -0400)
k8s: fix regression in namespace-restricted service accounts

k8s: fix regression in namespace-restricted service accounts

---

internal/cli/build.go

15c4a7ab72ff7ece48dcf524a09989b5234fa8b7 (2019-05-16 15:59:07 -0400)
cli: update version

cli: update version

---

internal/sail/server/room.go
internal/sail/server/room_test.go

Please review the following commits I made in branch nicks/ch2583/errors:
82eaadb3c2f1ced4d6c6847514dfe6f9d6717174 (2019-05-15 17:27:57 -0400)
sail: handle disconnected clients

sail: handle disconnected clients

---

web/src/HUD.test.tsx
web/src/Sidebar.scss
web/src/Sidebar.tsx
web/src/Statusbar.scss
web/src/TabNav.scss
web/src/TabNav.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/__snapshots__/TabNav.test.tsx.snap
web/src/__snapshots__/TopBar.test.tsx.snap
web/src/constants.scss

web: show number of alerts next to each resource

---

web/src/Sidebar.scss
web/src/Sidebar.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap

web: show total number of alerts next to all item

---

web/src/AnalyticsNudge.scss
web/src/AnalyticsNudge.test.tsx
web/src/AnalyticsNudge.tsx
web/src/__snapshots__/AnalyticsNudge.test.tsx.snap
web/src/__snapshots__/TopBar.test.tsx.snap

final final copy tbd (db is working on it) but wanted to get this out for review

web: more specific info when showing nudge - whether user opted in/out, http response body if error; finalize copy [ch2553]

---

web/src/LogPane.scss
web/src/LogPane.tsx
web/src/Statusbar.scss
web/src/__snapshots__/LogPane.test.tsx.snap

Please review the following commits I made in branch nicks/wrap:
e5c9754cc8c1878d7935feb04af997761cbabec4 (2019-05-20 12:09:55 +0200)
web: clean up the UI a bit on narrow widths

web: clean up the UI a bit on narrow widths

---

web/src/AnalyticsNudge.scss
web/src/AnalyticsNudge.test.tsx
web/src/AnalyticsNudge.tsx
web/src/HUD.tsx
web/src/TopBar.scss
web/src/TopBar.test.tsx
web/src/TopBar.tsx
web/src/__snapshots__/AnalyticsNudge.test.tsx.snap
web/src/__snapshots__/TopBar.test.tsx.snap
web/src/constants.scss

Please review the following commits I made in branch maiamcc/style-nudge:
cabbe79d8e9316a16151d069765d909badfb7c6b (2019-05-17 17:40:31 -0400)
button tweaks, fix hide/show logic
ffb11d96902c96c9e0bcd4036f7dc68952a8fcf8 (2019-05-17 17:26:24 -0400)
clean up animations, other views
c3b5e1c795d3e326bca751ac6af1a75f5db62600 (2019-05-17 17:13:28 -0400)
buttons
b8d1e96d63ccb55a5aae3b10dfb8034acf8698a3 (2019-05-17 17:07:27 -0400)
use the right elems to wrap things
35d58cc715b11730725cc92b3eaed47a8f870787 (2019-05-17 16:59:15 -0400)
style the nudge itself
bc60f1b955440a2e5662561008e76fe6939df17d (2019-05-17 16:45:01 -0400)
put nudge at top of page
* Code is easy to understand and …

web: style analytics nudge [ch2554]

---

internal/engine/upper_test.go

before fix: `go test ./internal/engine -run TestSetAnalyticsOpt -count 20` failed 4/4 times
after fix: `go test ./internal/engine -run TestSetAnalyticsOpt -count 100` passed

upper tests: fix race condition

---

web/src/AnalyticsNudge.scss
web/src/constants.scss

Hello tbd,
Please review the following commits I made in branch maiamcc/more-obvi-analytics-nudge:
d88bb41e1730aea42f42caa3066b33627144983d (2019-05-20 17:53:48 -0400)
analytics-nudge: styling to make nudge more obvious

analytics-nudge: styling to make nudge more obvious

---

internal/cli/build.go

Please review the following commits I made in branch maiamcc/update-0.8.6:
0f0a4666fc3b495d3667b9533dde6a0bdb1c6741 (2019-05-20 18:24:43 -0400)
update dev version to 0.8.6

update dev version to 0.8.6

---

web/src/AnalyticsNudge.tsx

web: analytics nudge confirmation disappears after 15s (up from 4s)

---

internal/build/test_utils.go
internal/cli/cli.go
internal/cli/docker.go
internal/cli/doctor.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/docker/client.go
internal/docker/client_test.go
internal/synclet/wire.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/docker:
67204d7ce08e947d1f6338ccdccc5d99792b44f8 (2019-05-24 13:32:43 +0100)
cli: add 'tilt docker' and let the user manually enable/disable buildkit

cli: add 'tilt docker' and let the user manually enable/disable buildkit

---

internal/k8s/watch.go

Idk exactly how it worked out so, but everything in selectCases corresponds to an elem in `gvrs` (i.e. is a channel for events for a specific kind of k8s group+version+resource), except the very last case, which represents ctx close.
When we got a ctx close and also `!ok` (i don't understand why this would or wouldn't happen, but it happened at least sometimes) we tried to print an error message referencing `gvrs[chosen]`, i.e. the group+version+resource at the index of the select statement that made things weird. If the select statement that tripped it was `<- ctx.Done()` (i.e. the very last `SelectStatement`), it wouldn't correspond to something in the `gvrs` array, and we'd get a panic:
```
panic: runtime error: index out of range
goroutine 1297 [running]: …
```

k8s events: fix panic from trying to index into array when context canceled

---

internal/hud/server/controller.go
web/src/AppController.ts
web/src/PathBuilder.tsx

Please review the following commits I made in branch nicks/open:
836386669b5e6a670497c9db30a8cab276ef286f (2019-05-29 03:15:09 -0400)
web: adjust open() semantics a bit to avoid dupe windows

web: adjust open() semantics a bit to avoid dupe windows

---

internal/assets/server.go

Please review the following commits I made in branch nicks/loading:
1d8d108b390d11adf659891c81d2c24824dd1371 (2019-05-29 01:23:19 -0400)
web: style error page a bit better

web: style error page a bit better

---

internal/k8s/watch.go

We know that this works because the integration tests with restricted permissions pass locally (with no errors) on GKE/Minikube. Before this change, these tests would throw error: 
> Error: Error watching for uids. Are you connected to kubernetes?
> : error making watcher for resource 'apiregistration.k8s.io/v1, Resource=apiservices': unknown, Reason: Forbidden, Code: 403
(These tests will always pass on CI because CI doesn't actually respect auth lolsob.)

k8s: only watch resources we have permissions for

---

internal/cli/up.go
internal/demo/script.go
internal/logger/deferred.go
internal/logger/deferred_test.go
internal/store/logger.go

b5bf11e8d53caeb40d633b7b98ae0a8341912b7e (2019-05-31 16:51:45 -0700)
logger: better support for logging during dependency-injection

logger: better support for logging during dependency-injection

---

internal/tiltfile/docker.go
internal/tiltfile/tiltfile_test.go

Just the syntax changes, rest is coming in another diff.

tiltfile: add ignore parameter to docker_build

---

internal/container/default_registry.go
internal/container/default_registry_test.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go
internal/k8s/registry.go
internal/k8s/registry_test.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go

Please review the following commits I made in branch nicks/microk8s:
5db97903a4363f9a08a506917735ef283de98e0e (2019-06-05 16:17:44 -0400)
k8s: Add a helper for pulling out the microk8s registry

k8s: Add a helper for pulling out the microk8s registry

---

internal/engine/actions.go
internal/engine/buildcontroller.go
internal/engine/configs_controller.go
internal/engine/docker_compose_log_manager.go
internal/engine/podlogmanager.go
internal/engine/tiltfile_log_writer.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/server/server.go
internal/model/log.go
internal/model/log_test.go
internal/store/actions.go
internal/store/logger.go
internal/store/testing_store.go

9e7f60eb736946b50d3d8fde958fa31b082c9b29 (2019-06-06 18:46:29 -0400)
engine: bring some consistency to how we do logging

engine: bring some consistency to how we do logging

---

internal/engine/event_watch_manager.go
internal/engine/event_watch_manager_test.go
internal/engine/k8s_events_feature.go
internal/engine/pod_watch.go
internal/engine/service_watch.go
internal/engine/uid_map_manager.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/renderer.go
internal/hud/renderer_test.go
internal/hud/resourceview.go
internal/hud/view/view.go
internal/hud/webview/convert.go
internal/hud/webview/view.go
internal/hud/webview/view_test.go
internal/store/actions.go
internal/store/engine_state.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/k8s:
26d1ba7e6edb26b0c029ff2f50495a3f89398da1 (2019-06-07 11:53:07 -0400)
Consistently use K8s casing over K8S

Consistently use K8s casing over K8S

---

internal/engine/fake_notify_test.go
internal/engine/upper.go
internal/engine/watchmanager.go
internal/watch/notify_test.go
internal/watch/watcher_darwin.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/ch2402/watch:
111f1784d645fb31981fa6571b0ead08c6d48b98 (2019-06-07 17:48:43 -0400)
watch: fix spurious errors while watching

watch: fix spurious errors while watching

---

internal/cli/wire_gen.go
internal/engine/upper_test.go
internal/engine/wire_gen.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/registry.go
internal/k8s/registry_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/microk8s:
3cc32811874d61f15f2fb870b5b6fea73d8a6cbf (2019-06-07 20:15:33 -0400)
k8s: auto-detect microk8s registry. Fixes issue #1621

k8s: auto-detect microk8s registry. Fixes issue #1621

---

internal/engine/buildcontroller_test.go
internal/engine/upper.go
internal/hud/server/actions.go
internal/hud/server/server.go
internal/hud/server/server_test.go
internal/store/testing_store.go

Please review the following commits I made in branch maiamcc/trigger-update-endpt:
0cbfda50385c2c21f9a0fb0d1eb5e751d6b7e533 (2019-06-07 17:24:57 -0400)
hud server api endpoint to trigger build, if possible [ch2670]

hud server api endpoint to trigger build, if possible [ch2670]

---

internal/engine/buildcontroller_test.go

Please review the following commits I made in branch maiamcc/fix-master-test:
5e21438b17f3d19e8efba59ba33bf595f418af8c (2019-06-11 11:29:48 -0400)
engine: fix broken tests from weird merge

engine: fix broken tests from weird merge

---

internal/hud/webview/convert.go
internal/hud/webview/view.go
web/src/HUD.tsx
web/src/Sidebar.test.tsx
web/src/Sidebar.tsx
web/src/SidebarIcon.test.tsx
web/src/SidebarIcon.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/testdata.test.tsx

Also better support for manual mode pending resources

web: show * next to resources with pending manual mode changes

---

internal/k8s/watch.go
internal/k8s/watch_test.go

Tilt is often logging k8s events for issues that are no longer issues (e.g., healthcheck failed on startup).
As the reader may or may not be aware, k8s events are just another type of k8s object. We subscribe to notifications of the creation and update of k8s event objects. We log updates of k8s objects because when an event occurs multiple times, k8s will increment the `Count` field of an existing event rather than creating a new event (this is open to revisiting depending on whether people find that useful or spammy).
When debugging this, it turns out that the k8s informer will continue calling our `UpdateFunc` for event objects when there have been no changes to those event objects! (at least, I called cmp.Equal on old vs new and it said they were the same). And it does so for long …

watch: only emit event updates on count incr

---

internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go

engine: unresourced YAML always builds first

---

internal/cli/build.go

d6a752afe4dc309e1503c9ac50c1a0b19938d810 (2019-06-20 16:31:07 -0400)
cli: update dev version to 0.9.0

cli: update dev version to 0.9.0

---

.gitignore
integration/fixture_test.go

5c0343be0b1348d865a1531e96c9b70ee33fa023 (2019-06-21 13:22:39 -0400)
integration: enforce timeouts better

integration: enforce timeouts better

---

Makefile
internal/assets/prod_server_test.go
internal/cli/docker.go
internal/cli/doctor.go
internal/cli/up_test.go
internal/cli/wire_gen.go
internal/engine/buildcontroller_test.go
internal/engine/event_watch_manager_test.go
internal/engine/extractors.go
internal/engine/uid_map_manager_test.go
internal/engine/upper.go
internal/engine/wire_gen.go
internal/hud/server/websocket_test.go
internal/k8s/registry.go
internal/model/matcher.go
internal/model/matcher_test.go
internal/sail/client/roomer.go
internal/sail/server/room.go
internal/sail/server/room_test.go
internal/sail/server/server.go
internal/sail/server/server_test.go
internal/store/actions.go
internal/store/engine_state_test.go
internal/watch/notify_test.go

makefile: fix goimports -local

---

internal/build/custom_builder.go
internal/build/custom_builder_test.go
internal/build/test_utils.go
internal/cli/docker.go
internal/cli/doctor.go
internal/cli/synclet.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/docker/client.go
internal/docker/client_test.go
internal/docker/clients.go
internal/docker/env.go
internal/docker/fake_client.go
internal/docker/wire.go
internal/dockercompose/client.go
internal/engine/upper_test.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/synclet/wire.go
internal/synclet/wire_gen.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/dockerclients:
a3883595b188e34281755575852a386cfd42f702 (2019-06-21 17:48:51 -0400)
docker: split client providers into a local docker client and a cluster docker client

docker: split client providers into a local docker client and a cluster docker client

---

internal/docker/env.go

Hello @nicks,
Please review the following commits I made in branch nicks/merge:
002ef2098f099f0e3517888445e1f0bac3c7d194 (2019-06-24 12:22:57 -0400)
goimports fix

goimports fix

---

integration/fixture_test.go
integration/k8s_fixture_test.go
integration/onewatch/Dockerfile
integration/onewatch/Tiltfile
integration/onewatch/deployment.yaml
integration/onewatch/restart.sh
integration/onewatch/start.sh
integration/restart.sh
integration/start.sh

Please review the following commits I made in branch nicks/kind:
fa0f6f27c6ae84618998ce1484e669f96f50d52a (2019-06-25 17:30:17 -0400)
integration: make onewatch work on containerd

integration: make onewatch work on containerd

---

.circleci/Dockerfile.integration
.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/kind4:
44685112b9ee601f133dedd3128e971e29bfbd4c (2019-06-26 13:49:39 -0700)
kind 0.4.0 is out today!!

kind 0.4.0 is out today!!

---

Makefile
cmd/buildkitapi/main.go
internal/build/cache_builder.go
internal/build/tar.go

Please review the following commits I made in branch nicks/buildkittests:
5d7574bba5f4cc839773434b3e2fa3a114e0d40d (2019-06-26 13:29:09 -0700)
Add a testutil for reading from the buildkit api

Add a testutil for reading from the buildkit api

---

internal/build/buildkit_printer.go
internal/build/testdata/TestBuildkitPrinter/echo-hi-success-verbose.master.txt
internal/build/testdata/TestBuildkitPrinter/echo-hi-success.master.txt
internal/build/testdata/TestBuildkitPrinter/multistage-fail-copy.master.txt
internal/build/testdata/TestBuildkitPrinter/multistage-fail-run.master.txt
internal/build/testdata/TestBuildkitPrinter/multistage-success.master.txt

Please review the following commits I made in branch nicks/buildkit:
90403a3b1f18b7492bc78de1193490a052b4f8d4 (2019-06-26 13:37:42 -0700)
build: a quick dirty fix for bugs in buildkit output
Reported in https://github.com/windmilleng/tilt/issues/1777

build: a quick dirty fix for bugs in buildkit output

---

cmd/tilt/main.go
internal/watch/watcher_naive.go

To help @dotellie diagnose some watch issues in the #tilt channel

watch: record num watches in expvars

---

internal/engine/watchmanager.go

engine: detect inotify queue overflow and display helpful message

---

internal/engine/target_queue_test.go

(I'm about to change this class for a bug)

engine: add TargetQueue tests

---

internal/cli/down.go
internal/cli/down_test.go
internal/dockercompose/fake_client.go
internal/k8s/fake_client.go

Please review the following commits I made in branch nicks/ch2853:
ff12f2afc3121f203b042401f1f6dfc76067b071 (2019-07-05 13:40:06 -0400)
cli: make sure tilt down fails properly if the kubectl/docker-compose commands fail

cli: make sure tilt down fails properly if the kubectl/docker-compose commands fail

---

internal/engine/pod_watch.go
internal/engine/pod_watch_test.go
internal/engine/upper.go
internal/hud/renderer.go
internal/hud/view/view.go
internal/hud/webview/convert.go
internal/hud/webview/view.go
internal/store/engine_state.go
web/src/AlertPane.test.tsx
web/src/AlertPane.tsx
web/src/HUD.test.tsx
web/src/Statusbar.tsx
web/src/__snapshots__/AlertPane.test.tsx.snap
web/src/combinedStatusMessage.test.ts
web/src/combinedStatusMessage.ts
web/src/constants.ts
web/src/testdata.test.tsx

Please review the following commits I made in branch nicks/ch2807/crash:
fad5188b4173efb7f849c7432a5f75e1cd16bd6e (2019-07-05 17:41:55 -0400)
engine: handle pod run errors properly
fixes https://github.com/windmilleng/tilt/issues/1769

engine: handle pod run errors properly

---

internal/build/buildkit_printer.go
internal/build/buildkit_printer_test.go
internal/build/image_builder.go
internal/build/testdata/TestBuildkitPrinter/echo-hi-failure-verbose.master.txt
internal/build/testdata/TestBuildkitPrinter/echo-hi-failure.master.txt
internal/build/testdata/TestBuildkitPrinter/multistage-fail-copy.master.txt
internal/build/testdata/TestBuildkitPrinter/multistage-fail-run.master.txt
internal/build/testdata/TestBuildkitPrinter/rust-success.master.txt

Please review the following commits I made in branch nicks/rust:
5fb58ad0a6a602f05963d5e054b7c943be912fb4 (2019-07-09 13:41:59 -0400)
build: fix rustc output. Fixes https://github.com/windmilleng/tilt/issues/1824

build: fix rustc output. Fixes https://github.com/windmilleng/tilt/issues/1824

---

internal/engine/image_build_and_deployer.go
internal/k8s/client.go

Please review the following commits I made in branch nicks/apply:
b35bffe3508bb0c1032ec8f5aab5ca80b4055819 (2019-07-09 15:31:09 -0400)
engine: print out the resources we're deploying

engine: print out the resources we're deploying

---

internal/tiltfile/docker.go
internal/tiltfile/files.go
internal/tiltfile/tiltfile_test.go
internal/tiltfile/writer.go

Please review the following commits I made in branch nicks/running:
4799f142e3dbcf2fd64ab677a119e2f5a7cb839a (2019-07-09 15:02:18 -0400)
tiltfile: print output of local() to the logger

tiltfile: print output of local() to the logger

---

internal/dockerignore/ignore.go
internal/watch/notify.go
internal/watch/notify_test.go
internal/watch/watcher_darwin.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/exclusions:
6b63d9089e709bf7181cc2110e3f9a0316d107dd (2019-07-11 12:36:29 -0400)
watch: add tests for ignores and number of watches

watch: add tests for ignores and number of watches

---

internal/cli/build.go

Please review the following commits I made in branch maiamcc/v0.9.3:
0f53916013684c57b7e23649af2fe5915bd01b19 (2019-07-11 17:36:37 -0400)
bump version to 0.9.3

bump version to 0.9.3

---

internal/watch/notify_test.go
internal/watch/watcher_darwin.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/zerodeps:
9f588501593be67067cf92a7c22aa05384e94b00 (2019-07-15 18:46:39 -0400)
watch: skip setup if nothing is being watched

watch: skip setup if nothing is being watched

---

integration/start.sh

Please review the following commits I made in branch maiamcc/wrapper-scripts-up-to-date:
3fa122722209dcef3f6d3bbfe0f8e4be371dbcd1 (2019-07-15 17:11:54 -0400)
bring start script up to date with rerun-process-wrapper repo

bring start script up to date with rerun-process-wrapper repo

---

internal/watch/notify_test.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/exclusions:
54ed14fa4c5f2e8f46cc168460e422e518fc63ca (2019-07-16 14:46:07 -0400)
watch: add a simple check when there are no exclusions

watch: add a simple check when there are no exclusions

---

internal/dockerignore/ignore.go
internal/ignore/path_matcher.go
internal/model/matcher.go
internal/watch/notify.go
internal/watch/watcher_naive.go

Please review the following commits I made in branch nicks/exclusions2:
c80ef864b4d50debda91da61e4f3bb24184b6ec3 (2019-07-16 16:12:46 -0400)
watch: move more of the directory-skipping logic into the interface

watch: move more of the directory-skipping logic into the interface

---

internal/build/tar.go
internal/build/tar_benchmark_test.go

Please review the following commits I made in branch nicks/exclusions4:
b9a66cae8246d9dcbc144020e8c9fd85cb7835a5 (2019-07-16 16:53:15 -0400)
build: optimize tar a bit

build: optimize tar a bit

---

integration/analytics/Tiltfile
integration/fixture_test.go
integration/imagetags/Tiltfile
integration/k8s_fixture_test.go
integration/live_update_base_image/Tiltfile
integration/oneup/Tiltfile
integration/oneup_custom/Tiltfile
integration/onewatch/Tiltfile
integration/onewatch_exec/Tiltfile
integration/shortlived_pods/Tiltfile

Please review the following commits I made in branch nicks/namespace:
ed6368789ce4b32a09354f1ef29e643258391c79 (2019-07-17 15:46:32 -0400)
integration: create namespaces with Tilt, because namespace-creation seems like it breaks a lot

integration: create namespaces with Tilt, because namespace-creation seems like it breaks a lot

---

internal/analytics/tilt_analytics.go
internal/build/custom_builder_test.go
internal/build/tar_test.go
internal/build/test_utils.go
internal/cli/down_test.go
internal/containerupdate/docker_container_updater_test.go
internal/engine/analytics_reporter_test.go
internal/engine/build_and_deployer_test.go
internal/engine/configs_controller_test.go
internal/engine/docker_compose_build_and_deployer_test.go
internal/engine/event_watch_manager_test.go
internal/engine/image_build_and_deployer_test.go
internal/engine/local_container_build_and_deployer_test.go
internal/engine/pod_watch_test.go
internal/engine/service_watch_test.go
internal/engine/target_queue_test.go
internal/engine/tilt_analytics_test.go
internal/engine/upper_test.go
internal/engine/watchmanager_test.go
internal/hud/server/server_test.go
internal/hud/server/websocket_test.go
internal/k8s/client_test.go
internal/k8s/logging_kubectl_runner_test.go
internal/k8s/watch_test.go
internal/sail/client/client_test.go
internal/testutils/context.go
internal/tiltfile/docker_compose_test.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch maiamcc/analytics-on-test-ctx:
306a57c378822ab269703823dfb196d0b4f66208 (2019-07-18 12:26:38 -0400)
tests: make sure ctx we use for tests always has (the correct) analytics attached

tests: make sure ctx we use for tests always has (the correct) analytics attached

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/twitter:
45650db01739d67d3dbfd2c6e14ec241253b8d72 (2019-07-19 07:14:20 -0400)
readme: update twitter and blog links

readme: update twitter and blog links

---

internal/kustomize/dependencies.go

Please review the following commits I made in branch nicks/attribution:
a8f1fdd44ea40c043864e03328bf123d3773945c (2019-07-22 12:40:45 -0400)
kustomize: add attribution for skaffold Kustomize code

kustomize: add attribution for skaffold Kustomize code

---

DEVELOPING.md
scripts/install.sh

Please review the following commits I made in branch nicks/installer:
0326016e6b66939b39417adab441e4caeb590f60 (2019-07-22 18:01:10 -0400)
scripts: add a Tilt install script

scripts: add a Tilt install script

---

internal/kustomize/dependencies.go

Please review the following commits I made in branch nicks/license:
c63fab55efd5a1c09ea254ad647e378746b954b9 (2019-07-24 14:11:31 -0400)
kustomize: license info for Skaffold as requested in https://github.com/windmilleng/tilt/issues/1886

kustomize: license info for Skaffold as requested in https://github.com/windmilleng/tilt/issues/1886

---

DEVELOPING.md
internal/cli/build.go
scripts/install.sh

Please review the following commits I made in branch maiamcc/v0.9.5:
6316625b0879eb24c34d399ddeb665ae2ff0f5a1 (2019-07-25 14:51:39 -0400)
bump version to 0.9.5

bump version to 0.9.5

---

internal/cli/build.go
scripts/install.sh

Hello @mb, @landism,
Please review the following commits I made in branch maiamcc/bump-0.9.6:
a8b5e5437cf9c33a2f92189d4abd01b1c8d3a78b (2019-07-25 18:01:51 -0400)
bump to 0.9.6

bump to 0.9.6

---

internal/dockerignore/ignore.go
internal/ignore/ephemeral.go
internal/ignore/path_matcher.go
internal/ignore/path_matcher_test.go

Please review the following commits I made in branch nicks/tempfiles:
7c5bb21b1bb307fea86a7a92499964405e008092 (2019-07-26 17:44:04 -0400)
ignore: improve the ephemeral temp file patterns [ch2663]

ignore: improve the ephemeral temp file patterns [ch2663]

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/testpod:
2d37daac3e814c41c6275e67669ef2f4461ce116 (2019-07-29 20:39:36 -0400)
engine: make testPod take a Manifest, in preparation for generating PodStatuses for testing from the Manifest

engine: make testPod take a Manifest, in preparation for generating PodStatuses for testing from the Manifest

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go
internal/model/deploy_info.go
internal/testutils/podbuilder/podbuilder.go

Please review the following commits I made in branch nicks/podbuilder2:
3b87839785dab842df0382e685ade1acd4efa58e (2019-07-30 11:11:03 -0400)
engine: factor out a PodBuilder for creating fake pods

engine: factor out a PodBuilder for creating fake pods

---

internal/engine/buildcontroller_test.go
internal/engine/testdata_test.go
internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/fastbuild:
6e199b70a4d11fb10fa1b67b5c562dff32d9e302 (2019-07-30 13:49:24 -0400)
engine: change test default to LiveUpdate

engine: change test default to LiveUpdate

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go
internal/testutils/podbuilder/podbuilder.go

Please review the following commits I made in branch nicks/podbuilder3:
45b912ec08a36860286c13d25c781a5cdbf50b33 (2019-07-30 15:08:51 -0400)
podbuilder: response to comments

podbuilder: response to comments

---

internal/engine/buildcontroller_test.go
internal/engine/docker_compose_build_and_deployer_test.go
internal/engine/image_build_and_deployer_test.go
internal/engine/testdata_test.go
internal/engine/upper_test.go
internal/testutils/manifestbuilder/assemble.go
internal/testutils/manifestbuilder/manifestbuilder.go

Please review the following commits I made in branch nicks/manifestbuilder:
5163e5a91c8a5385a098e37d44616c4b8258d78e (2019-07-30 16:16:17 -0400)
manifestbuilder: add a test helper for building manifests

manifestbuilder: add a test helper for building manifests

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go
internal/testutils/podbuilder/podbuilder.go

Hello @nicks,
Please review the following commits I made in branch nicks/containerid:
8f07c8ae1bc5379cb3819659ca922f4eb406a1e0 (2019-07-30 17:20:03 -0400)
testing: remove container id param from testPod

testing: remove container id param from testPod

---

internal/testutils/podbuilder/podbuilder.go

Hello @nicks,
Please review the following commits I made in branch nicks/podbuilder5:
5731f72d6785c11c2ea4263ae34963127780383d (2019-07-30 18:00:52 -0400)
podbuilder: make sure index of image refs/cids matches number of containers

podbuilder: make sure index of image refs/cids matches number of containers

---

.circleci/config.yml
internal/assets/procutil_unix.go
internal/assets/procutil_windows.go
internal/assets/server.go

Please review the following commits I made in branch nicks/windows:
56b943dcd4a91af15e7ef7bda059f864cd19da97 (2019-08-01 14:26:48 -0400)
windows: make sure binaries compile

windows: make sure binaries compile

---

internal/engine/podlogmanager.go
internal/engine/portforwardcontroller.go
internal/engine/upper_test.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/blessed:
5fd2b168ab94c1c8f2eef4cd00f5c360d1db754a (2019-07-31 18:15:14 -0400)
store: make some Pod methods work with multiple containers

store: make some Pod methods work with multiple containers

---

internal/demo/script.go
internal/engine/pod.go
internal/engine/podlogmanager_test.go
internal/engine/portforwardcontroller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/ch3091/blessed:
73b4094384f416acb1c19fa012fe643dc71d9ee4 (2019-08-01 12:51:30 -0400)
store: remove Blessed containers
5fd2b168ab94c1c8f2eef4cd00f5c360d1db754a (2019-07-31 18:15:14 -0400)
store: make some Pod methods work with multiple containers

store: remove Blessed containers

---

internal/cli/cli.go
internal/cli/klog.go
internal/cli/klog_test.go
internal/cli/up.go

klog: hide 'resourceVersion too old' warnings

---

internal/cli/doctor.go
internal/cli/wire.go
internal/cli/wire_gen.go

Please review the following commits I made in branch nicks/doctor:
26f09f203a0c1fe5f9d184811b06faa78c0e24be (2019-07-24 15:31:00 -0400)
doctor: print both cluster and local

doctor: print both cluster and local

---

internal/engine/image_build_and_deployer.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/entity.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go

Please review the following commits I made in branch nicks/ch3085/apply:
b86bd680c97644dbde54daea75684fa49a5eefd7 (2019-08-02 15:48:42 -0400)
k8s: return the results of apply

k8s: return the results of apply

---

Gopkg.lock
internal/tiltfile/k8s.go
internal/tiltfile/live_update.go
internal/tiltfile/live_update_test.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
vendor/go.starlark.net/internal/compile/compile.go
vendor/go.starlark.net/internal/compile/serial.go
vendor/go.starlark.net/internal/spell/spell.go
vendor/go.starlark.net/resolve/binding.go
vendor/go.starlark.net/resolve/resolve.go
vendor/go.starlark.net/starlark/debug.go
vendor/go.starlark.net/starlark/eval.go
vendor/go.starlark.net/starlark/hashtable.go
vendor/go.starlark.net/starlark/int.go
vendor/go.starlark.net/starlark/interp.go
vendor/go.starlark.net/starlark/library.go
vendor/go.starlark.net/starlark/profile.go
vendor/go.starlark.net/starlark/unpack.go
vendor/go.starlark.net/starlark/value.go
vendor/go.starlark.net/syntax/grammar.txt
vendor/go.starlark.net/syntax/parse.go
vendor/go.starlark.net/syntax/quote.go
vendor/go.starlark.net/syntax/scan.go
vendor/go.starlark.net/syntax/syntax.go
vendor/go.starlark.net/syntax/walk.go

Hello @nicks,
d1ee2299d5d33551abb9cd753d2e86a38df2db68 (2019-08-02 17:28:45 -0400)
vendor: update starlark
contains improvements to stack frames and error reporting

vendor: update starlark

---

internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/files.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/localpath:
a24cb1f0f65fcd6f313c3eb7e00cdf962f2c0363 (2019-08-02 18:43:26 -0400)
tiltfile: remove localPath
this abstraction just made things more complicated and we've been gradually moving away from it

tiltfile: remove localPath

---

web/src/feature.test.ts
web/src/feature.ts

web: handle null feature flags

---

internal/engine/image_build_and_deployer.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/entity.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go

Hello @nicks,
41fd54571e95f49eceabfdcadf92da4feee2a7e2 (2019-08-06 13:50:55 -0400)
Revert "k8s: return the results of apply (#1974)"
This reverts commit ec2f653436eb105913226d41a31612ccdf4c88fd.

Revert "k8s: return the results of apply (#1974)"

---

internal/containerupdate/synclet_updater_test.go
internal/synclet/server_adapter.go
internal/synclet/test_grpc_wrapper.go

f44c0264cc1e324369d8eaa90371429f001329b8 (2019-08-06 11:51:14 -0400)
synclet: add a grpc connection for testing

synclet: add a grpc connection for testing

---

web/src/AlertPane.scss
web/src/AlertPane.test.tsx
web/src/AlertPane.tsx
web/src/AppController.ts
web/src/HUD.tsx
web/src/__snapshots__/AlertPane.test.tsx.snap
web/src/alerts.ts

Instead of immediately opening a new window, which is often blocked by browser pop-up detection, let's show the URL first.

Alert Link shows URL to work around Pop-up detection

---

internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/files.go
internal/tiltfile/include.go
internal/tiltfile/include_test.go
internal/tiltfile/live_update.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go

Please review the following commits I made in branch nicks/load:
fb52ea09ab175cce141d3738b7318b6c71240513 (2019-08-06 17:41:26 -0400)
tiltfile: add load() and include()

tiltfile: add load() and include()

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/testdata_test.go

Please review the following commits I made in branch maiamcc/multiple-images-test-cov:
cb0bb586ead020a899a2993988acd504fcda9dd3 (2019-08-07 11:10:18 -0400)
better test coverage for live update multiple images same manifest

better test coverage for live update multiple images same manifest

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/macos:
c07068a7f303abbce47385b551878d74b9427d42 (2019-08-07 14:03:55 -0400)
circlecci: raise the max open file limit in the macos vm

circlecci: raise the max open file limit in the macos vm

---

internal/synclet/test_grpc_wrapper.go

Hello @nicks,
Please review the following commits I made in branch nicks/rmfile:
3741f6f7422b3023a663666617a5dca3cc90d72e (2019-08-07 14:27:12 -0400)
synclet: add additional socket cleanup

synclet: add additional socket cleanup

---

integration/k8s_fixture_test.go
integration/onewatch/Tiltfile
integration/onewatch_test.go
integration/same_img_multi_container/Tiltfile
integration/same_img_multi_container_test.go

d148c8d761a197d9b19e5b83534396177ad56862 (2019-08-07 13:07:40 -0400)
integration: add tests for crash rebuilds

integration: add tests for crash rebuilds

---

internal/engine/build_and_deployer_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/bad:
958c0e3936d29e2d42fe436451c793b28d050b4a (2019-08-07 15:17:00 -0400)
engine: cancel test context correctly

engine: cancel test context correctly

---

internal/engine/analytics_reporter_test.go
internal/engine/configs_controller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/server/controller.go
internal/hud/webview/convert.go
internal/store/engine_state.go

engine state: use ManifestState for Tiltfile

---

internal/watch/notify_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/fsync:
28bfde4cb4183298693b3e4360eb6b5761d27e1e (2019-08-08 19:09:34 -0400)
watch: add retry counts to fsync

watch: add retry counts to fsync

---

internal/engine/image_build_and_deployer.go
internal/k8s/client.go
internal/k8s/client_test.go
internal/k8s/entity.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go

Hello @nicks,
Please review the following commits I made in branch nicks/uuid:
7d17ac3de67b7086fea49abbf8a41ebd72da896e (2019-08-09 13:04:59 -0400)
Revert "Revert "k8s: return the results of apply (#1974)" (#1993)"
This reverts commit 4e16981ba5f53b84925ea9c59399eda554215cd7.

Revert "Revert "k8s: return the results of apply (#1974)" (#1993)"

---

Gopkg.lock
internal/cli/wire_gen.go
internal/k8s/env.go
internal/k8s/env_test.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/go.mod
vendor/github.com/mitchellh/go-homedir/homedir.go

Please review the following commits I made in branch nicks/k3d:
ce087491490ed5ce73a8d1d32b169551ee18b473 (2019-08-09 17:26:55 -0400)
k8s: add k3d env detection

k8s: add k3d env detection

---

internal/engine/event_watch_manager.go
internal/engine/event_watch_manager_test.go
internal/k8s/client.go
internal/k8s/entity.go
internal/k8s/entity_test.go
internal/k8s/label_test.go
internal/k8s/names.go
internal/k8s/names_test.go
internal/k8s/serialize.go
internal/k8s/serialize_test.go
internal/store/actions.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/kind:
9b5e50e183a13387663554bd8b0a26ff48d9f377 (2019-08-13 16:54:05 -0400)
k8s: simplify K8sEntity

k8s: simplify K8sEntity

---

internal/engine/extractors.go
internal/engine/image_build_and_deployer.go
internal/engine/upper_test.go

Please review the following commits I made in branch nicks/ibd:
908e71310e2aed97f97b2f46170e00a219d58835 (2019-08-14 15:41:49 -0400)
engine: reorganize ibd a bit

engine: reorganize ibd a bit

---

internal/containerupdate/synclet_manager.go
internal/dockercompose/state.go
internal/engine/buildcontroller.go
internal/engine/pod.go
internal/engine/podlogmanager.go
internal/engine/portforwardcontroller_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/store/build_result.go
internal/store/engine_state.go
internal/store/engine_state_test.go
internal/store/runtime_state.go
internal/testutils/manifestutils/manifest.go

Please review the following commits I made in branch nicks/state:
038e8d640d220ee9828075233aabe901e43b6540 (2019-08-14 18:21:50 -0400)
store: organize all k8s-specific info under RuntimeState

store: organize all k8s-specific info under RuntimeState

---

internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/webview/convert.go
internal/k8s/fake_client.go
internal/store/build_result.go
internal/store/runtime_state.go

Please review the following commits I made in branch nicks/ch3088/state:
4bbea819b5bb216e999fe4fd27d4344e37a15482 (2019-08-15 11:31:02 -0400)
engine: add deploy ids to the engine state

engine: add deploy ids to the engine state

---

internal/ignore/ephemeral.go

Please review the following commits I made in branch maiamcc/goland-ignores:
b771cb5cafc0bdd3a7cf6ebce8f959c4da89e0ea (2019-08-15 12:59:55 -0400)
ignore: auto-ignore jetbrains .idea file

ignore: auto-ignore jetbrains .idea file

---

internal/hud/webview/convert.go
internal/hud/webview/convert_test.go

Fixes #2073 
This was a bug introduced by #2016 [here](https://github.com/windmilleng/tilt/pull/2016/files#diff-9ba72e5012548279d39d668051f4d8bdR125).

webui: fix tiltfile log pane

---

web/src/HUD.test.tsx
web/src/HUD.tsx

Please review the following commits I made in branch nicks/preview:
a3547163e59bc061d78960d633220c6f3de7e815 (2019-08-19 15:57:25 -0400)
web: fix navigation to the preview list. Fixes https://github.com/windmilleng/tilt/issues/2069

web: fix navigation to the preview list. Fixes https://github.com/windmilleng/tilt/issues/2069

---

internal/engine/upper_test.go
internal/testutils/servicebuilder/servicebuilder.go

Hello @nicks,
Please review the following commits I made in branch nicks/servicebuilder:
11f3fa895ef9ac472c6ca950a56510790ac1add1 (2019-08-20 16:52:28 -0400)
testutils: add a helper for building services

testutils: add a helper for building services

---

internal/k8s/serialize.go
internal/k8s/serialize_test.go
internal/k8s/testyaml/testyaml.go

Please review the following commits I made in branch nicks/list:
264d6bbde494ba54bb746d7744d4e64aaaf5598e (2019-08-20 16:14:01 -0400)
k8s: unroll k8s resource lists returned sometimes from APIs

k8s: unroll k8s resource lists returned sometimes from APIs

---

.circleci/Dockerfile.integration
.circleci/config.yml
Makefile

Hello @nicks,
Please review the following commits I made in branch nicks/kind5:
f247dfdd8f41afa324bff2300b7529ab3ecdbd89 (2019-08-21 11:31:40 -0400)
uci: upgrade to kind 0.5

uci: upgrade to kind 0.5

---

internal/engine/buildcontroller_test.go
internal/engine/upper_test.go
internal/testutils/podbuilder/podbuilder.go

Hello @nicks,
Please review the following commits I made in branch nicks/testpod:
d5a65bd498c029934d2297d42f923c361047e2bb (2019-08-21 13:44:12 -0400)
engine: switch over more tests to use podbuilder

engine: switch over more tests to use podbuilder

---

internal/engine/actions.go
internal/engine/image_build_and_deployer.go
internal/engine/pod.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/engine_state.go
internal/testutils/servicebuilder/servicebuilder.go

Please review the following commits I made in branch nicks/ch3219/service:
92fa28cf580848760bb066b37d4b2580271c6608 (2019-08-20 18:55:38 -0400)
engine: use UIDs to associate services with manifests

engine: use UIDs to associate services with manifests

---

internal/engine/upper_test.go
internal/testutils/podbuilder/podbuilder.go

Hello @nicks,
Please review the following commits I made in branch nicks/testpod2:
4f55ea4bfa129833a35b8eb74d2256d165a73a81 (2019-08-22 01:36:31 -0400)
engine: remove old testPod method

engine: remove old testPod method

---

internal/engine/event_watch_manager_test.go
internal/engine/upper_test.go
internal/k8s/fake_client.go
internal/k8s/owner_fetcher_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/fakeclient:
beb22cafa2e92583a94ba3045c3686fa5ef9cf03 (2019-08-23 12:59:26 -0400)
k8s: simplify k8s Get() fakes

k8s: simplify k8s Get() fakes

---

internal/engine/pod_watch.go
internal/engine/service_watch.go
internal/engine/watcher.go

Hello @nicks,
Please review the following commits I made in branch nicks/common:
1ced84552a0058498aa0f2a4ed3808c652b6daf7 (2019-08-23 18:02:30 -0400)
engine: factor out a utility method

engine: factor out a utility method

---

internal/engine/upper_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/resultset:
91d068b5485e457a8fdf635925c2b6142bcc5df3 (2019-08-23 20:35:04 -0400)
tests: fix a bad BuildResult with both image build and live update fields set

tests: fix a bad BuildResult with both image build and live update fields set

---

.circleci/config.yml
Makefile
integration/k8s_fixture_test.go
internal/cli/doctor.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/image_build_and_deployer.go
internal/k8s/env.go
internal/k8s/env_test.go

Please review the following commits I made in branch nicks/issue1510:
f118de8817ce8234e1791bda7af3af952b22a34f (2019-09-03 11:20:24 -0400)
k8s: update kind detection. Fixes issue #1510

k8s: update kind detection. Fixes issue #1510

---

integration/imagetags/app-stretch/Dockerfile
integration/imagetags/app/Dockerfile
integration/imagetags/common-stretch/Dockerfile
integration/imagetags/common/Dockerfile

Hello @nicks,
Please review the following commits I made in branch nicks/imagetags:
b2c1b052baaef554137c271ce0e45444b99bb014 (2019-09-03 13:38:07 -0400)
integration: update slow test to use busybox
b74f20bf36af8fc08ad133b9782027dd22af863f (2019-09-03 13:17:53 -0400)
k8s: update kind detection. Fixes issue #1510

integration: update slow test to use busybox

---

DEVELOPING.md
Makefile
internal/synclet/sidecar/sidecar.go

16d2fbcc1d428d0876b90f611b23c66b9bb220a8 (2019-09-04 11:26:34 -0400)
release the synclet! :squid:

release the synclet! :squid:

---

integration/event/Dockerfile
integration/event/Tiltfile
integration/event/deployment.yaml
integration/event/index.html
integration/event_test.go

Please review the following commits I made in branch nicks/eventtest:
e81c38e3bd06ec7174f9a48fbad717be6dc83f59 (2019-09-04 12:06:17 -0400)
integration: add a test for events

integration: add a test for events

---

Gopkg.lock
internal/k8s/watch.go
internal/k8s/watch_test.go
vendor/k8s.io/client-go/dynamic/fake/simple.go

171db73bbb926ed4c0dd48c8189beae56e3e9f45 (2019-09-04 12:51:28 -0400)
k8s: watch by resource name, rather than duplicating watch code

k8s: watch by resource name, rather than duplicating watch code

---

internal/engine/image_build_and_deployer.go
internal/k8s/labels.go
internal/testutils/podbuilder/podbuilder.go
internal/testutils/servicebuilder/servicebuilder.go

Please review the following commits I made in branch nicks/label:
a5400b58e37827d04dc1f08d10f7f23598b8296f (2019-09-05 12:48:31 -0400)
k8s: add the standard app.kubernetes.io/managed-by label

k8s: add the standard app.kubernetes.io/managed-by label

---

internal/engine/pod_watch.go
internal/engine/pod_watch_test.go
internal/engine/service_watch.go
internal/engine/service_watch_test.go
internal/k8s/client.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go
internal/k8s/labels.go
internal/k8s/watch.go
internal/k8s/watch_test.go

Please review the following commits I made in branch nicks/ch3279/managed:
68ae7e4b4eb9fa735cde571c1e574e8fa4561458 (2019-09-05 19:49:58 -0400)
engine: Stop watching the Tilt run id label

engine: Stop watching the Tilt run id label

---

internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/hud/webview/view.go

This might be too simplistic an approach?

tilt: don't turn dots green until containers are ready

---

internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/pod_watch_test.go
internal/engine/upper_test.go
internal/testutils/podbuilder/podbuilder.go

Please review the following commits I made in branch nicks/ch3221/manifest:
f43b5a060983d1cdc28ea64ef426c5170dc63b97 (2019-09-06 14:36:10 -0400)
engine: remove manifest labels

engine: remove manifest labels

---

Gopkg.lock
internal/k8s/serialize_test.go
vendor/github.com/json-iterator/go/README.md
vendor/github.com/json-iterator/go/adapter.go
vendor/github.com/json-iterator/go/any.go
vendor/github.com/json-iterator/go/go.mod
vendor/github.com/json-iterator/go/go.sum
vendor/github.com/json-iterator/go/iter_float.go
vendor/github.com/json-iterator/go/iter_skip.go
vendor/github.com/json-iterator/go/iter_skip_strict.go
vendor/github.com/json-iterator/go/reflect_extension.go
vendor/github.com/json-iterator/go/reflect_map.go
vendor/github.com/json-iterator/go/reflect_marshaler.go
vendor/github.com/json-iterator/go/reflect_native.go
vendor/github.com/json-iterator/go/reflect_struct_decoder.go
vendor/github.com/json-iterator/go/stream_float.go

Please review the following commits I made in branch nicks/ch2408/serialize:
eedb64d677fdfdae8ebed6d05e3558c838794986 (2019-09-06 17:58:43 -0400)
vendor: update json-iterator and verify it fixes base64 serialization

vendor: update json-iterator and verify it fixes base64 serialization

---

pkg/model/local_target.go
pkg/model/manifest.go
pkg/model/target.go

Please review the following commits I made in branch maiamcc/local-target-model:
ac9499f4254454b3684cec14b1dca1d6df12aa42 (2019-09-16 17:20:29 -0400)
model: LocalTarget [ch3471]

model: LocalTarget [ch3471]

---

internal/build/test_utils.go
internal/cli/docker.go
internal/cli/doctor.go
internal/cli/wire_gen.go
internal/docker/client.go
internal/docker/clients.go
internal/docker/exploding.go
internal/docker/fake_client.go
internal/docker/switch.go
internal/engine/configs_controller.go
internal/engine/configs_controller_test.go
internal/synclet/wire_gen.go

Please review the following commits I made in branch nicks/issue2180:
d0fca8b009e41707845cd4acec2b0fd2f217f4c9 (2019-09-17 12:40:20 -0400)
docker: If the docker server fails to connect, don't report it until we're sure we need it. Fixes issue #2180

docker: If the docker server fails to connect, don't report it until we're sure we need it. Fixes issue #2180

---

internal/engine/pod.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/server/server.go
internal/hud/webview/convert.go
internal/store/actions.go
internal/store/engine_state.go
internal/store/runtime_state.go
web/src/AlertPane.scss
web/src/AlertPane.test.tsx
web/src/AlertPane.tsx
web/src/HUD.tsx
web/src/__snapshots__/AlertPane.test.tsx.snap
web/src/alerts.test.ts
web/src/alerts.ts

Please review the following commits I made in branch nicks/issue1850:
5510bd0b9b3f36710b2bd533a843c27ef5866831 (2019-09-17 15:21:43 -0400)
web: dismiss pod restart alerts. Fixes issue #1850

web: dismiss pod restart alerts. Fixes issue #1850

---

internal/k8s/entity.go
internal/tiltfile/files.go
internal/tiltfile/text_test.go
internal/tiltfile/tiltfile_test.go
internal/tiltfile/value.go

Please review the following commits I made in branch nicks/issue2209:
530ed109f5d00b317a6f4b827f2d692dda32f0e7 (2019-09-19 00:34:23 -0400)
helm: add arguments. Fixes issue #2209

helm: add arguments. Fixes issue #2209

---

internal/build/cache_builder.go
internal/build/container_test.go
internal/build/image_builder.go
internal/build/options.go
internal/docker/client.go
internal/docker/options.go
internal/engine/image_and_cache_builder.go
internal/engine/image_build_and_deployer_test.go
internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/image_target.go

Please review the following commits I made in branch nicks/issue2217/target:
e02b250bb7ee93816bbb2611921af39a093b3156 (2019-09-19 17:58:05 -0400)
docker: support docker build --target. Fixes issue #2217

docker: support docker build --target. Fixes issue #2217

---

internal/cli/build.go
scripts/install.sh

Hello @nicks,
c8b46c30719d6c850cf0911b40297ab6ce2ccec0 (2019-09-20 12:13:19 -0400)
tilt: update release script

tilt: update release script

---

internal/hud/webview/convert_test.go
internal/testutils/manifestbuilder/manifestbuilder.go
internal/tiltfile/tiltfile_state.go
pkg/model/local_target.go

need this in place for some tests i'm writing -- and tbh should be
this waqy anyway, more human-readable TargetID.

model: LocalTarget.Name

---

internal/cli/down.go
internal/demo/script.go
internal/engine/configs/configs_controller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/issue2062/error:
4c5bda41b9f6ce2a7b053da5b1986c8b723feb5c (2019-09-20 19:36:47 -0400)
tiltfile: enable feature on partial evaluation

tiltfile: enable feature on partial evaluation

---

internal/cloud/cloud_username_manager.go
internal/testutils/httptest/http_client.go

#2240 
second verse, same as the first

tilt cloud: don't log http.Response.String(), take two

---

internal/engine/upper_test.go
pkg/model/manifest.go
pkg/model/manifest_test.go

Please review the following commits I made in branch maiamcc/change-localresource-def:
d658020f93add23bd86da82345e05cf333edc1c0 (2019-09-23 18:32:52 -0400)
model: changes to LocalTarget should result in rebuild [ch3536]

model: changes to LocalTarget should result in rebuild [ch3536]

---

internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go

tiltfile: adjust allowed_k8s_contexts error message

---

internal/engine/configs/actions.go
internal/engine/configs/configs_controller.go
internal/engine/upper.go
internal/store/engine_state.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_test.go
pkg/model/secret.go

Please review the following commits I made in branch nicks/secrets:
a0f815816a3ffdcc8b8ab9b84bf1ea1b8617a7d0 (2019-09-23 17:51:09 -0400)
engine: load secrets into the engine state

engine: load secrets into the engine state

---

internal/tiltfile/docker.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

had 15 minutes to kill and wasn't swapped in on anything else

tiltfile: rm some fastbuild code

---

internal/hud/server/server_test.go
internal/hud/webview/convert.go
internal/hud/webview/convert_test.go
internal/hud/webview/testdata/snapshot.json
internal/hud/webview/view.go
internal/hud/webview/view_test.go
pkg/model/log.go
web/src/AlertPane.test.tsx
web/src/AppController.ts
web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/Statusbar.tsx
web/src/alerts.test.ts
web/src/alerts.ts
web/src/status.test.tsx
web/src/status.tsx
web/src/testdata.test.tsx
web/src/types.ts

Please review the following commits I made in branch nicks/protocol:
f17679f48d723d96a13b909db5cc2c36ba23909a (2019-09-25 15:43:05 -0400)
hud: make webview.View deserializable

hud: make webview.View deserializable

---

internal/engine/upper_test.go
pkg/model/secret.go

Please review the following commits I made in branch nicks/ch3568/redact:
30db8959103878018d92195e96865c893e1fc259 (2019-09-27 10:31:09 -0400)
don't scrub secrets <5 chars

don't scrub secrets <5 chars

---

Makefile
web/.storybook/addons.js
web/.storybook/config.js
web/.storybook/preview-head.html
web/package.json
web/src/ShareSnapshotModal.stories.tsx
web/yarn.lock

Please review the following commits I made in branch nicks/modal:
d3fe161830787932fd2ee1094dcd845d33c0724b (2019-09-27 12:01:24 -0400)
web: add a storybook for the snapshot modal

web: add a storybook for the snapshot modal

---

internal/build/test_utils.go

I tried running tests and got this single, very unhelpful panic:
```
--- FAIL: TestDockerBuildDockerfile (0.00s)
panic: interface conversion: docker.Client is docker.explodingClient, not *docker.Cli [recovered]
panic: interface conversion: docker.Client is docker.explodingClient, not *docker.Cli
goroutine 61 [running]:
testing.tRunner.func1(0xc0000f7c00)
/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x2194140, 0xc0005b21e0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/windmilleng/tilt/internal/build.newDockerBuildFixture(0x2675ee0, 0xc0000f7c00, 0x0)
/home/therc/go/src/github.com/windmilleng/tilt/internal/build/test_utils.go:59 +0x612
[...]
```
After this change, I get 16 errors:
```
--- FAIL: TestDockerBuildDockerfile (0.00s)
test_utils.go:65: Got permission denied …
```

Report NewDockerClient() errors in tests instead of swallowing them and panicking

---

internal/synclet/sidecar/sidecar.go

Please review the following commits I made in branch nicks/env2:
36f04931eed5d6549ec7c2876c51e813a7b43f3a (2019-10-01 14:35:12 -0400)
synclet: fix a global init bug introduced by https://github.com/windmilleng/tilt/pull/2277

synclet: fix a global init bug introduced by https://github.com/windmilleng/tilt/pull/2277

---

internal/cli/wire_gen.go
internal/containerupdate/synclet_manager.go
internal/engine/build_and_deployer_live_update_test.go
internal/engine/build_and_deployer_test.go
internal/engine/image_build_and_deployer.go
internal/engine/wire.go
internal/engine/wire_gen.go
internal/synclet/sidecar/inject.go
internal/synclet/sidecar/sidecar.go
internal/synclet/sidecar/sidecar_test.go
internal/synclet/sidecar/wire.go

Please review the following commits I made in branch nicks/syncletinit:
acfa782b747c0a5bf431bad3e3fc179399ef47fa (2019-10-02 07:57:17 -0700)
sidecar: integrate synclet image ref init with wire

sidecar: integrate synclet image ref init with wire

---

internal/tiltfile/files.go
internal/tiltfile/tiltfile_test.go

tiltfile: record helm.values args as config files (b/c they affect the helm chart, we should rerun whenever they change)

---

Makefile
internal/cli/build.go
internal/cli/build_test.go
pkg/assets/prod_server_test.go
pkg/assets/server.go
pkg/model/tilt_build.go
pkg/model/web.go

Now a version can be either `v1.2.3` or `abcdefedba`

assets: also be able to fetch assets by git SHA

---

web/src/HUD.tsx
web/src/LogPane.test.tsx
web/src/LogPane.tsx
web/src/ResourceInfo.tsx
web/src/__snapshots__/LogPane.test.tsx.snap

This makes it a bit easier for us to do the get selection logic (part of Link to Snapshots effort)

ResourceInfo should not be part of LogPane component

---

internal/tiltfile/include/include.go
internal/tiltfile/os/os.go
internal/tiltfile/os/os_test.go
internal/tiltfile/starkit/environment.go
internal/tiltfile/starkit/extension.go
internal/tiltfile/starkit/fixture.go
internal/tiltfile/starkit/module.go
internal/tiltfile/tiltfile_state.go

Please review the following commits I made in branch nicks/environ:
8f970302a8bbd8346d427eeb2dbb7fa3e466961f (2019-10-11 17:16:47 -0400)
tiltfile: implement os.environ. Fixes https://github.com/windmilleng/tilt/issues/1980

tiltfile: implement os.environ. Fixes https://github.com/windmilleng/tilt/issues/1980

---

internal/hud/webview/convert.go
internal/hud/webview/testdata/snapshot.json
internal/hud/webview/view.go
web/src/HUD.tsx
web/src/ShareSnapshotModal.stories.tsx
web/src/ShareSnapshotModal.test.tsx
web/src/ShareSnapshotModal.tsx
web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap

This is not the best place to put it or best way to render it, but it's there:

tilt: add link to team snapshots

---

.circleci/config.yml

b93cd4e59e637b3fde60ec6b04f46919f2df6be6 (2019-10-14 17:39:31 -0400)
circleci: configure tilt to notify slack on failure

circleci: configure tilt to notify slack on failure

---

internal/cli/wire.go
internal/cli/wire_gen.go
internal/cloud/snapshot_uploader.go
internal/cloud/wire.go
internal/hud/server/server.go
internal/hud/server/server_test.go

Please review the following commits I made in branch nicks/refactor:
888517e066c159a9c431342b78f0f9d0eb2761c1 (2019-10-14 17:27:38 -0400)
cloud: Factor out a separate SnapshotUploader

cloud: Factor out a separate SnapshotUploader

---

internal/cli/wire_gen.go
internal/cloud/update_uploader.go
internal/cloud/update_uploader_test.go
internal/cloud/wire.go
internal/engine/subscribers.go
internal/engine/upper_test.go
internal/feature/flags.go

Please review the following commits I made in branch nicks/update:
350c98c1b831bf8c8b6f2c1f92f73c17e9c6c021 (2019-10-14 21:27:20 -0400)
cloud: convert BuildRecords into update proto objects

cloud: convert BuildRecords into update proto objects

---

web/src/AppController.ts
web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/LogPane.test.tsx
web/src/LogPane.tsx
web/src/ShareSnapshotModal.scss
web/src/ShareSnapshotModal.stories.tsx
web/src/ShareSnapshotModal.test.tsx
web/src/ShareSnapshotModal.tsx
web/src/TopBar.scss
web/src/TopBar.tsx
web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
web/src/__snapshots__/TopBar.test.tsx.snap
web/src/types.ts

Show Highlight indication in Snapshot modal

---

internal/cloud/update_uploader.go
internal/cloud/update_uploader_test.go

Please review the following commits I made in branch nicks/ch3667/send:
c314c632d1d83cc2b7fe0c56ea0e53e1f5ac4d6e (2019-10-15 15:45:43 -0400)
cloud: send update records

cloud: send update records

---

internal/engine/build_and_deployer_live_update_test.go
internal/engine/build_and_deployer_test.go
internal/engine/docker_compose_build_and_deployer.go
internal/engine/docker_compose_build_and_deployer_test.go
internal/engine/image_and_cache_builder.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/engine/live_update_state_tree.go
internal/engine/local_target_build_and_deployer.go
internal/engine/local_target_build_and_deployer_test.go
internal/engine/target_queue.go
internal/engine/target_queue_test.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/store/build_result.go
internal/store/build_result_test.go
internal/store/engine_state.go

Please review the following commits I made in branch nicks/record:
77af5d3b9aa4cdf23bc773a6cf15853cb87fe9eb (2019-10-15 17:57:16 -0400)
store: refactor build result

store: refactor build result

---

web/src/AppController.test.ts
web/src/AppController.ts
web/src/HUD.tsx
web/src/LogPane.tsx

- make sure the highlight is passed into the Snapshot state
- clear the highlight when navigating between resources

See highlight in Snapshot

---

Makefile
web/package.json
web/src/ResourceInfo.tsx
web/src/ShareSnapshotModal.tsx
web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
web/yarn.lock

Hello @nicks,
Please review the following commits I made in branch nicks/web:
16ae2311cf4f378fc7455d7cc525d6b9749780d0 (2019-10-16 18:34:58 -0400)
web: add a Makefile rule for running npm link

web: add a Makefile rule for running npm link

---

web/src/LogPane.scss

web/css: fix logs vanishing under sidebar at small browser widths

---

internal/tiltfile/dockerprune/docker_prune.go
internal/tiltfile/dockerprune/docker_prune_test.go
internal/tiltfile/include/include_test.go
internal/tiltfile/k8scontext/k8scontext.go
internal/tiltfile/k8scontext/k8scontext_test.go
internal/tiltfile/os/os_test.go
internal/tiltfile/starkit/environment.go
internal/tiltfile/starkit/environment_test.go
internal/tiltfile/starkit/extension.go
internal/tiltfile/starkit/fixture.go
internal/tiltfile/starkit/model.go
internal/tiltfile/starkit/set_state.go
internal/tiltfile/tiltfile.go
internal/tiltfile/tiltfile_state.go

Please review the following commits I made in branch nicks/state:
e835b35649b297fe2964f9656499ee9b5495c083 (2019-10-16 14:51:50 -0400)
tiltfile: a better pattern for extensions with mutable state
this might be too crazy functional programming bananapants

tiltfile: a better pattern for extensions with mutable state

---

internal/k8s/registry.go

Please review the following commits I made in branch nicks/issue2369/registry:
298d0b92b6a7655ce6315f84c4b63c0b5eaceb16 (2019-10-17 19:36:59 -0400)
k8s: disable the microk8s registry if localhost resolves to ipv6

k8s: disable the microk8s registry if localhost resolves to ipv6

---

.goreleaser.yml

Please review the following commits I made in branch nicks/releaser:
f3742f9dad567ce0bb4faceccb66a90e8050f625 (2019-10-18 16:24:58 -0400)
goreleaser: build with pure-Go os.user

goreleaser: build with pure-Go os.user

---

web/src/ResourceInfo.scss

web: don't highlight endpoint link after clicking

---

internal/containerupdate/synclet_manager.go
internal/k8s/client.go
internal/k8s/exploding_client.go
internal/k8s/fake_client.go
internal/k8s/portforward.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/manifest.go

Please review the following commits I made in branch nicks/portforward:
57ca3e2bf88b64a190c4be7f2384a164eb122a74 (2019-10-21 19:32:17 -0400)
tiltfile: simplify port-forward data models

tiltfile: simplify port-forward data models

---

internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/files.go
internal/tiltfile/live_update.go
internal/tiltfile/local_resource.go
internal/tiltfile/tiltfile_state.go

Hello @nicks,
Please review the following commits I made in branch nicks/absworkingdir:
fa63de808f36aaf051d7d971de1f6a01662d069e (2019-10-22 12:13:54 -0400)
tiltfile: move some function calls

tiltfile: move some function calls

---

internal/cloud/snapshot_uploader.go
web/src/AppController.ts
web/src/HUD.tsx
web/src/types.ts

Please review the following commits I made in branch nicks/ch3765/reset:
4c5db4e4dfd39351211d16dba6be51a726fcb7ce (2019-10-22 20:28:26 -0400)
cloud: snapshotHighlight and path accidentally got capitalized

cloud: snapshotHighlight and path accidentally got capitalized

---

internal/tiltfile/files.go
internal/tiltfile/git/git.go
internal/tiltfile/git/git_test.go
internal/tiltfile/git/repo.go
internal/tiltfile/starkit/fixture.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/git:
eb53c9dd7f8257948ee812e5e22677267a693870 (2019-10-22 21:05:33 -0400)
tiltfile: move git.Repo into its own extension

tiltfile: move git.Repo into its own extension

---

Makefile
web/.dockerignore
web/Dockerfile
web/Tiltfile
web/tilt-web.yaml

Please review the following commits I made in branch nicks/staging:
f535b60ee6e640819dea18035e4377795671f600 (2019-10-23 14:28:32 -0400)
web: add a Tiltfile for tilt-web

web: add a Tiltfile for tilt-web

---

web/Tiltfile

Hello @nicks,
Please review the following commits I made in branch nicks/staging:
eba00292f2c48dd8aab0f8a2f5b62df59508e119 (2019-10-23 15:46:06 -0400)
tweak the tiltfile for tilt-web a bit

tweak the tiltfile for tilt-web a bit

---

internal/synclet/proto/synclet.pb.go
internal/tiltfile/docker.go
internal/tiltfile/docker_compose.go
internal/tiltfile/files.go
internal/tiltfile/git/repo.go
internal/tiltfile/k8s.go
internal/tiltfile/live_update.go
internal/tiltfile/local_resource.go
internal/tiltfile/value/value.go

Hello @nicks,
Please review the following commits I made in branch nicks/value:
efa81bc49864f0a1944f215517438c7121b4982b (2019-10-23 18:35:03 -0400)
tiltfile: refactor a function to not depend on GitRepo

tiltfile: refactor a function to not depend on GitRepo

---

web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/TopBar.scss
web/src/TopBar.stories.tsx
web/src/TopBar.test.tsx
web/src/TopBar.tsx
web/src/__snapshots__/TopBar.test.tsx.snap

Hello @hyu,
Please review the following commits I made in branch nicks/ch3761/updates:
71f94d9af584db782cb8a6f8afdfbb4b8faec922 (2019-10-24 21:09:50 -0400)
web: add buttons for team snapshots, updates

web: add buttons for team snapshots, updates

---

internal/k8s/entity.go
internal/tiltfile/files.go
internal/tiltfile/text_test.go
internal/tiltfile/tiltfile_test.go

tiltfile: if --namespace flag passed, helm builtin should also add yaml defining the namespace

---

internal/cloud/snapshot_uploader.go
internal/hud/server/server_test.go

Please review the following commits I made in branch nicks/snapshots:
ac2508f5f8dc48041e86730e0f325fb0c37cd4e8 (2019-10-25 14:55:13 -0400)
cloud: adjust snapshot json serialization

cloud: adjust snapshot json serialization

---

pkg/assets/prod_test.go

Please review the following commits I made in branch nicks/assets:
a47518efe36c07fb63999f4fd02848c473bb0325 (2019-10-25 13:47:43 -0400)
assets: add better tests

assets: add better tests

---

internal/build/cache_builder.go
internal/build/custom_builder.go
internal/container/container.go
internal/dockerfile/ast.go
internal/dockerfile/inject_test.go
internal/engine/docker_compose_build_and_deployer_test.go
internal/engine/extractors.go
internal/engine/image_and_cache_builder.go
internal/engine/image_build_and_deployer.go
internal/engine/image_build_and_deployer_test.go
internal/k8s/image.go
internal/tiltfile/build_index.go
internal/tiltfile/docker.go
internal/tiltfile/k8s.go
internal/tiltfile/live_update_test.go
internal/tiltfile/tiltfile_docker_compose_test.go
internal/tiltfile/tiltfile_test.go

Please review the following commits I made in branch nicks/normalize:
1e18d2ca95d6ab826ec63288641b9f19d2169f44 (2019-10-25 17:21:36 -0400)
container: familiarize some ref names

container: familiarize some ref names

---

Gopkg.lock
internal/tiltfile/include_test.go
internal/tiltfile/starkit/error.go
internal/tiltfile/tiltfile_state.go
vendor/go.starlark.net/internal/compile/compile.go
vendor/go.starlark.net/resolve/resolve.go
vendor/go.starlark.net/starlark/eval.go
vendor/go.starlark.net/starlark/interp.go

55372e8e804d2660f44aa9aa55f30e6c2e26478e (2019-10-29 10:40:49 -0400)
tiltfile: handle load() backtraces properly

tiltfile: handle load() backtraces properly

---

internal/analytics/tilt_analytics.go
internal/cli/analytics.go
internal/cli/doctor.go

Please review the following commits I made in branch nicks/ch3806/doctor:
d3935d6e6a4fbda0ecde09e838fce7480e602829 (2019-10-29 11:59:31 -0400)
cli: add machine and repo to tilt doctor
3d3141f5f388a332bf3e22aafc9a42f213079c91 (2019-10-29 11:42:46 -0400)
vendor: update wmclient

cli: add machine and repo to tilt doctor

---

pkg/assets/prod.go

Hello @nicks,
Please review the following commits I made in branch nicks/middleware2:
477069897d352525ebd5854828e91c0d98012f65 (2019-10-30 16:42:42 -0400)
assets: remove dead code

assets: remove dead code

---

internal/analytics/env.go
internal/analytics/fake.go
internal/analytics/tilt_analytics.go
internal/analytics/tilt_analytics_test.go
internal/cli/analytics.go
internal/cli/doctor.go
internal/cli/up.go
internal/engine/actions.go
internal/engine/analytics/analytics_reporter_test.go
internal/engine/analytics/analytics_updater.go
internal/engine/analytics/analytics_updater_test.go
internal/engine/configs/actions.go
internal/engine/configs/configs_controller.go
internal/engine/upper.go
internal/engine/upper_test.go
internal/hud/server/server.go
internal/hud/server/server_test.go
internal/hud/webview/analytics_nudge.go
internal/hud/webview/analytics_nudge_test.go
internal/store/actions.go
internal/store/engine_state.go
internal/testutils/context.go
internal/tiltfile/analytics/analytics.go
internal/tiltfile/analytics/analytics_test.go
internal/tiltfile/tiltfile.go

Please review the following commits I made in branch nicks/ch3805/analytics:
df5fb930d0e209e474ae94d39412e0c3167fa1e3 (2019-10-29 20:27:13 -0400)
tiltfile: add an analytics_settings for enabling/disabling analytics from the tiltfile

tiltfile: add an analytics_settings for enabling/disabling analytics from the tiltfile

---

integration/k8s_fixture_test.go
integration/live_update_two_images_one_manifest_test.go

Please review the following commits I made in branch nicks/skip:
f2d1edf8f86a53ec42b8b4a7bb6a6bc8dc1d996f (2019-10-30 16:00:01 -0400)
integration: fix the two-images-one-manifest test

integration: fix the two-images-one-manifest test

---

internal/cli/build.go
scripts/install.sh

Hello @nicks,
5c23293b5d44a9e27cbe3cdb6e2766771c1edda5 (2019-11-01 11:48:11 -0400)
scripts: update tilt installer to v0.10.16

scripts: update tilt installer to v0.10.16

---

integration/live_update_two_images_one_manifest_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/skip:
b396de2bedcf92758a021d7dec08a712f268bf4a (2019-11-01 12:26:03 -0400)
integration: disable the test again

integration: disable the test again

---

internal/tiltfile/docker.go
internal/tiltfile/files.go
internal/tiltfile/io/blob.go
internal/tiltfile/k8s.go
internal/tiltfile/tiltfile.go
internal/tiltfile/value/string.go
internal/tiltfile/value/value.go

Hello @nicks,
Please review the following commits I made in branch nicks/set:
617df57bf33c822466c80fe208524f312d50f39c (2019-11-01 16:29:19 -0400)
tiltfile: move some more converters into tiltfile/value

tiltfile: move some more converters into tiltfile/value

---

internal/tiltfile/tiltfile_state.go

tiltfile: make builtin setup easier to read

---

web/src/HUD.tsx

Hello @nicks,
Please review the following commits I made in branch nicks/mobiel:
17b3ad0beebd77375fd3533b4c0691003d14d0b8 (2019-11-01 17:37:36 -0400)
hud: split up the big render function

hud: split up the big render function

---

internal/tiltfile/files.go
internal/tiltfile/helm_test.go

Please review the following commits I made in branch nicks/helmset:
73007607ff8334c2ef3b6216ee30c24115e854ac (2019-11-01 18:14:25 -0400)
tiltfile: add helm --set to the helm() built-in

tiltfile: add helm --set to the helm() built-in

---

internal/cli/up.go
internal/cli/wire.go
internal/cli/wire_gen.go
internal/engine/upper_test.go
internal/hud/server/controller.go
internal/network/port.go
internal/network/port_test.go
pkg/model/web.go

I don't work with go very often and this my first pull request here, so please let me know if I missed something obvious (or not obvious)!
I copied the general approach from https://github.com/windmilleng/tilt/pull/1830. 
I had issues running some of the tests locally, but they _seem_ to be mostly passing now. Will watch to see what happens on circleci.
Closes https://github.com/windmilleng/tilt/issues/2321

Allow users to change the IP address that webserver binds to (#2321)

---

integration/Tiltfile
integration/onewatch_exec_test.go

Hello @nicks,
3dcb8a8bc67d04ef84bb9e049125bf6012aff31b (2019-11-04 17:57:38 -0500)
integration: add more logging to onewatchexec

integration: add more logging to onewatchexec

---

web/src/HUD.test.tsx
web/src/HUD.tsx
web/src/TopBar.tsx
web/src/__snapshots__/TopBar.test.tsx.snap

Hello @hyu,
Please review the following commits I made in branch nicks/handle:
cc65862425826845991f644a7b373a69db18c5b5 (2019-11-05 12:34:02 -0500)
web: fix handleOpenSnapshot

web: fix handleOpenSnapshot

---

web/src/AlertPane.test.tsx
web/src/HUD.test.tsx
web/src/Sidebar.scss
web/src/Sidebar.stories.tsx
web/src/Sidebar.test.tsx
web/src/Sidebar.tsx
web/src/Statusbar.test.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/combinedStatusMessage.test.ts
web/src/status.test.tsx
web/src/testdata.tsx

Please review the following commits I made in branch nicks/button:
f67b1eee39d6bab36ab68ec6baed5af39b5005e8 (2019-11-05 14:44:51 -0500)
web: restructure the SidebarItem and create a storybook for the Sidebar

web: restructure the SidebarItem and create a storybook for the Sidebar

---

web/src/AlertPane.scss
web/src/FacetsPane.scss
web/src/HUD.tsx
web/src/HUDGrid.stories.tsx
web/src/HUDGrid.tsx
web/src/LogPane.scss
web/src/LogPane.test.tsx
web/src/LogPane.tsx
web/src/ResourceInfo.scss
web/src/TopBar.scss
web/src/__snapshots__/LogPane.test.tsx.snap
web/src/constants.scss
web/src/constants.ts

Hello @hyu,
Please review the following commits I made in branch nicks/panels:
aaf34c0bfba132400cb8e20c849ac3686f55a1bb (2019-11-04 22:24:18 -0500)
web: introduce HUDGrid
Now, HUDGrid manages the layout and overlap between components, rather than
every component having to know about the other components in the grid.

web: introduce HUDGrid

---

web/src/Sidebar.scss
web/src/Sidebar.stories.tsx

Hello @hyu,
Please review the following commits I made in branch nicks/overflow:
ba603a59c713a666f0a7ee70fa0f61c0f08b249e (2019-11-05 16:20:28 -0500)
web: handle sidebar name overflow

web: handle sidebar name overflow

---

integration/onewatch_exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/skip:
3c70a28afe89b74c7c30871bc122508afad6eec2 (2019-11-05 21:55:52 -0500)
integration: disable a test for now

integration: disable a test for now

---

web/src/PathBuilder.test.tsx
web/src/PathBuilder.tsx
web/src/ResourceInfo.scss
web/src/Sidebar.scss
web/src/Sidebar.tsx
web/src/Statusbar.scss
web/src/Statusbar.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/__snapshots__/Statusbar.test.tsx.snap
web/src/constants.scss

Please review the following commits I made in branch nicks/mobile:
1ea37486a3c3b97ea8240688ef13d5dec9f83f3a (2019-11-05 20:29:54 -0500)
web: assorted mobile fixes

web: assorted mobile fixes

---

internal/store/json.go
internal/store/json_test.go
internal/store/private_fields.go

Hello @nicks,
Please review the following commits I made in branch nicks/dump3:
5dd78e5457607eed5f4da210b79590acec303054 (2019-11-05 19:04:46 -0500)
cli: engine dump should also include private fields

cli: engine dump should also include private fields

---

Makefile
web/src/view.d.ts

Please review the following commits I made in branch maiamcc/proto-ts:
732df35d2310010288463f91e8f6f3eae97bc4eb (2019-11-08 14:13:30 -0500)
web: update typescript definitions, streamline makefile for webview proto

web: update typescript definitions, streamline makefile for webview proto

---

internal/engine/buildcontrol/build_control.go
internal/engine/buildcontroller_test.go
internal/engine/upper_test.go
internal/hud/buildstatus.go
internal/hud/renderer_test.go
internal/hud/resourceview.go
internal/hud/server/server_test.go
internal/hud/webview/convert_test.go
internal/store/engine_state.go
internal/tiltfile/docker_compose.go
internal/tiltfile/local_resource.go
internal/tiltfile/tiltfile_state.go
internal/tiltfile/tiltfile_test.go
pkg/model/manifest_test.go
pkg/model/trigger_mode.go
web/src/Sidebar.stories.tsx
web/src/Sidebar.test.tsx
web/src/SidebarTriggerButton.scss
web/src/SidebarTriggerButton.test.tsx
web/src/SidebarTriggerButton.tsx
web/src/__snapshots__/Sidebar.test.tsx.snap
web/src/status.tsx
web/src/types.ts

This was supposed to be #2511, but that had a non-master base, and I failed to change the base back to master before merging, and it's not possible to reopen a merged PR, so reposting with a base of master.

tiltfile: add auto_init to local_resource

---

web/src/HUD.scss
web/src/HUD.tsx
web/src/Sidebar.tsx
web/src/SidebarIcon.tsx
web/src/Statusbar.tsx
web/src/TopBar.scss
web/src/TopBar.tsx

Please review the following commits I made in branch nicks/ch3682/snapshots:
8077a3022d1efaec55050baba00b728bcee7191b (2019-11-08 19:15:47 -0500)
web: snapshots polish
disable animations in snapshots
fix up the links in the upper-right

web: snapshots polish

---

internal/build/image_builder.go
internal/build/image_builder_test.go

addresses some of #2484
I think anything else I'd write here is covered by the comments and unit tests.
`EXEC` failure [in master](https://cloud.tilt.dev/snapshot/AbbM19wLpOMeczO4Hcs=) | [in branch](https://cloud.tilt.dev/snapshot/AaLL19wLdSw7frQKtZY=)
`ADD` failure [in master](https://cloud.tilt.dev/snapshot/AbTN19wLyl61UhZSW5k=) | [in branch](https://cloud.tilt.dev/snapshot/Af7N19wLCoYgy6WBsVg=)

build: humanize buildkit errors a bit

---

integration/live_update_after_crash_rebuild/Dockerfile
integration/live_update_after_crash_rebuild/compile.sh
integration/live_update_after_crash_rebuild/main.sh
integration/onewatch/Dockerfile
integration/onewatch/Tiltfile
integration/onewatch/compile.sh
integration/onewatch/main.sh

Please review the following commits I made in branch nicks/integration2:
d6d51602b3e1b629959d0d582b5209bb98fd8ad4 (2019-11-12 15:19:51 -0500)
integration: fix up sample projects to actually need restart.sh

integration: fix up sample projects to actually need restart.sh

---

web/src/AlertPane.tsx
web/src/PathBuilder.test.tsx
web/src/PathBuilder.tsx

web: allow alerts to be dismissed in all contexts _except_ snapshots

---

internal/engine/buildcontroller.go

On my laptop, which I'm assuming is not an outlier, the `──┤ Building: fortune ├──────────────────────────────────────────────` that we print on builds ends up wrapping and looking pretty ugly, which is unfortunate for something we print so often!
(to be clear: I have no idea what resolution my monitor is or what resolution our users' monitors are)
make that line shorter
(screenshots instead of snapshots since the problem is display-size-dependent)
before:
after:

engine: reduce length of build header line

---

web/src/HUD.tsx
web/src/TopBar.stories.tsx
web/src/TopBar.test.tsx
web/src/TopBar.tsx

Please review the following commits I made in branch nicks/snapshots2:
0284329dbcdb0742d82853c131186e61437e3772 (2019-11-15 11:56:04 -0500)
web: remove team buttons for now

web: remove team buttons for now

---

internal/engine/buildcontroller.go
internal/engine/buildcontroller_test.go

builder: fix panic on long resource name

---

web/src/Statusbar.scss

webui: fix upgrade notification text

---

internal/docker/clients.go
internal/engine/configs/configs_controller.go
internal/engine/configs/configs_controller_test.go
internal/engine/dockerprune/docker_pruner.go

Please review the following commits I made in branch nicks/issue2253:
179210c87a7e9370035605c43d632cacfcb29467 (2019-11-25 13:44:21 -0500)
docker: support booting tilt without docker. Fixes https://github.com/windmilleng/tilt/issues/2253

docker: support booting tilt without docker. Fixes https://github.com/windmilleng/tilt/issues/2253

---

internal/hud/server/websocket.go
internal/hud/server/websocket_test.go

Please review the following commits I made in branch nicks/issue2599/panic:
9b8f8ca2cea9cefe49e59c69188f969757eaadb2 (2019-11-25 19:06:48 -0500)
hud: fix a panic when the websocket breaks

hud: fix a panic when the websocket breaks

---

internal/engine/upper.go
internal/store/actions.go
internal/store/engine_state.go
internal/store/safe.go
internal/store/store.go
internal/store/subscriber.go

Please review the following commits I made in branch nicks/ch3963/panic:
c79d5605d07e67533bf2c436cf6e63626ac7e7e4 (2019-11-25 19:31:05 -0500)
store: handle panics more gracefully

store: handle panics more gracefully

---

internal/cli/build.go
scripts/install.sh

Hello @nicks,
07df680c363831cf2ff1a65c2168f143d27a86fc (2019-11-26 14:28:14 -0500)
update install script to v0.10.22

update install script to v0.10.22
