tilt-dev/tilt

internal/k8s/apply.go
Good idea @maiamcc!
Tested with this script again:
```go
package main
import (
"context"
"fmt"
"os"
"github.com/windmilleng/tilt/internal/k8s"
)
func main() {
yaml := `apiVersion: v1
kind: Service
metadata:
name: hello-kubernetes
spec:
type: LoadBalancer
ports:
- port: 80
targetPort: 8080
selector:
app: hello-kubernetes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: hello-kubernetes
spec:
replicas: 3
template:
metadata:
labels:
app: hello-kubernetes
spec:
containers:
- name: hello-kubernetes
image: paulbouwer/hello-kubernetes:1.4
ports:
- containerPort: 8080`
err := k8s.Apply(context.Background(), yaml)
if err != nil {
fmt.Println(err.Error())
os.Exit(1)
} else {
fmt.Println("It worked!")
}
}
```
=> k8s: simplify Apply to read from stdin instead of file

internal/build/builder.go
A builder takes a path on the FS, runs a cmd in them, and returns a new
path on the file system with those commands run, the output of those cmds,
and an error.
There could be different builder implementations: one for building locally,
one for remotely, one that just makes new directories, one that makes new
layers in overlayFS, etc.
=> build: first pass at builder interface

internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
had been putting this off because I didn't understand this part of the spec
usage, e.g.:
```
image = build_docker_image("%v", "docker tag")
image.add_mount('/mount_points/1', git_repo('/mount_points/1/foo'))
```
=> tilt: add tiltfile support for mount points

internal/build/docker.go, internal/build/docker_test.go
883e0265edcb6868ecf8763c3a1cbd62b9af7022 (2018-08-10 14:14:43 -0400)
docker: set the version explicitly instead of negotiating from the env
=> docker: set the version explicitly instead of negotiating from the env

internal/cli/cli.go, internal/cli/daemon.go, internal/tiltd/tiltd_server/tiltd.go
now instead of running `tiltd`, one runs `tilt daemon` (and `go install cmd/tilt` instead of `go install cmd/tilt && go install cmd/tiltd`)
this is mostly to reduce the chance that we're running inconsistent versions of `tilt` and `tiltd`
=> tilt: pull daemon into main tilt binary

internal/build/docker.go, internal/build/docker_test.go, internal/tiltfile/tiltfile.go
Please review the following commits I made in branch maiamcc/enforce-entrypoint:
4f1930fde10b254191d5c2cd83d5ecb405a02c63 (2018-08-14 17:03:49 -0400)
build: throw error if base Dockerfile contains an ENTRYPOINT
=> build: throw error if base Dockerfile contains an ENTRYPOINT

internal/tiltd/tiltd_server/tiltd.go
Hello @nicks,
Please review the following commits I made in branch nicks/digests:
3cb7386a387508bbebba38f7b3a2c1af40af0ce2 (2018-08-15 13:11:31 -0400)
tiltd: use the typed api instead of the string api
=> tiltd: use the typed api instead of the string api

internal/build/docker.go, internal/build/docker_test.go, internal/cli/daemon.go, internal/cli/up.go, internal/engine/build_and_deployer.go, internal/engine/upper.go, internal/model/service.go, internal/proto/server_adaptor.go, internal/tiltd/tiltd.go, internal/tiltd/tiltd_server/tiltd.go
Problems:
1. discussion with the Dans yesterday about the interface between the daemon and the builder for `--watch` got us to something approximating the new `BuildAndDeployer` interface
2. as I was implementing --watch, more logic and dependencies were going into tiltd.go, which already had too much code, and it felt weird that all the other packages had to reference `tiltd` to get `Mount`, `Cmd`, etc.
Solutions:
1. Move the various classes used to pass around service definitions into a new `model` package
2. Move the logic for combining all the work together into a new `engine` package
3. Create a new `BuildAndDeployer` interface at an attempt to draw a clean line in the code and reduce the chances of toe-stepping.
If I'd realized how big this diff would end up being, I'd have done …
=> tilt: move code out of tiltd, add --watch that just loops

internal/build/docker.go, internal/build/docker_test.go, internal/engine/build_and_deployer.go
Please review the following commits I made in branch maiamcc/inc-build-entrypoint:
bfdf19c6361cdb3fd3454e84a6540ada154c7eb9 (2018-08-16 15:05:06 -0400)
build: inc. build doesn't take its own entrypoint, preserves entrypoint of existing img
fb7b5b1037d2b626ea0771c92c3f8293d8afce31 (2018-08-16 14:56:09 -0400)
wip
=> build: inc. build doesn't take its own entrypoint, preserves entrypoint of existing img

internal/build/docker.go, internal/engine/build_and_deployer.go, internal/k8s/image.go
Please review the following commits I made in branch nicks/k8s:
394109d79d6f7338e6e8317afa23641af26a8758 (2018-08-20 12:35:45 -0400)
k8s: tighten the api to use ref.Canonical, which includes both name and digest
=> k8s: tighten the api to use ref.Canonical, which includes both name and digest

internal/cli/daemon.go, internal/engine/creator.go, internal/engine/upper.go, internal/model/service.go, internal/proto/server_adaptor.go, internal/service/creator.go
Please review the following commits I made in branch nicks/deps:
c7c19612d76038ea2cc642158ba58b6ad7fa103e (2018-08-21 15:21:36 -0400)
proto: rewire dependencies to avoid lots of logic in the server adaptor
=> proto: rewire dependencies to avoid lots of logic in the server adaptor

internal/engine/build_and_deployer.go, internal/image/history.go, internal/image/history_test.go
Prior to this patch when we loaded the existing history from disk
(in `NewImageHistory`) we would _re-persist_ all of the images that had
already been persisted.
To prevent this, I broke out `history.Add` in to two functions:
1. `history.Load` now adds an image to the in memory store
2. `history.AddAndPersist` loads an image and persists it to disk
We just call `history.Load` in `NewImageHistory` to prevent the exponential
hsitory problem.
=> image: history shouldn't grow exponentially

internal/engine/upper.go, internal/engine/upper_test.go, internal/watch/notify.go, internal/watch/notify_test.go, internal/watch/watcher_darwin.go, internal/watch/watcher_linux.go
e1ef01b3555ebad66b601bdb3ea1f124c360dfa8 (2018-08-22 15:24:28 -0400)
watch: simplify the fileEvent interface to only contain paths
=> watch: simplify the fileEvent interface to only contain paths

internal/cli/up.go, internal/tiltd/tiltd_server/tiltd.go
Hello @pmt, @landism,
Please review the following commits I made in branch nicks/errors2:
f42b533e363e069fc7831e9b9b858b5c89022f0f (2018-08-22 13:13:45 -0400)
cli: error handling when the daemon exists unexpectedly. also fixes the case where you're talking to an old daemon
=> cli: error handling when the daemon exists unexpectedly. also fixes the case where you're talking to an old daemon

internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
see: https://github.com/windmilleng/tilt/pull/146/files
q: should I update the blorg and blorgly tiltfiles with these new names?
=> tilt: git_repo becomes local_git_repo per README

internal/cli/up.go, internal/model/service.go, internal/proto/server_adaptor.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/skylark-returns-domain-services:
148f850e5e26e994e791d703ba998d6dc6075e9a (2018-08-22 16:43:23 -0400)
skylark: GetServiceConfig returns domain objects (model.Service, not proto.Service)
=> skylark: GetServiceConfig returns domain objects (model.Service, not proto.Service)

README.md
Hello @dbentley, @jazzdan,
Please review the following commits I made in branch maiamcc/repo-fixes:
01553d9a823e8717c09d028ec8118c47ea449f0d (2018-08-22 18:01:02 -0400)
readme: missing backtick, install instructions at top
=> readme: missing backtick, install instructions at top

internal/tracer/tracer.go
Tested by killing the jaeger container, and running `tilt up blorgly_frontend` and observing that there were no longer any errors printed.
=> tracer: doesn't log

internal/watch/notify_test.go, internal/watch/watcher_darwin.go
Please review the following commits I made in branch nicks/singlefile:
88e1b156c90a528b89f7d3e812e5dfda723c3af6 (2018-08-23 11:36:11 -0400)
watch: fix a flaky test by ignoring spurious events correctly
=> watch: fix a flaky test by ignoring spurious events correctly

scripts/timing.py
testing the performance characteristics of tarring over big resources -- will look separately at `go get`-ing or `go install`-ing big things if that also seems useful
=> timing: test files of varying bigness

internal/build/docker_test.go, internal/build/path_mapping.go, internal/build/path_mapping_test.go
This is due to the fact that file events come in as absolute paths.
=> build: relative local repo paths need to be absolute

internal/build/tar.go
Huge caveat here: I spent most of the morning trying to write a test for this and I was unable to. Here's how I tested it manually to verify that it is fixed.
1. `make install`
2. `cd ../blorg-tilt`
3.  `tilt up blorg_frontend --watch`
4. Wait for it to come up
5. `cd ../blorg-frontend`
6. Modify main.go
At this point in the old world if you looked at the container on the pod you would see `/go/src/github.com/windmilleng/blorg-frontend/main.go/main.go`. Note the incorrect path. In the new world: you'd see `/go/src/github.com/windmilleng/blorg-frontend/main.go` with the correct, updated contents.
=> build: fix bug where tar treated all top level files as directories

internal/minikube/docker.go, internal/minikube/docker_test.go
Please review the following commits I made in branch nicks/minikube2:
d582d9c1e874ccc95932635cb23beef69294399d (2018-08-23 17:58:52 -0400)
minikube: add a helper function for reading the docker client from minikube
=> minikube: add a helper function for reading the docker client from minikube

internal/git/gitignore.go, internal/git/gitignore_test.go
1. ignoring .git was failing because we were comparing against relative paths, so use absolute paths when setting up gitignore testers, add a unit test for that case
2. refactor gitignore tests so that they're less tedious
=> tilt: make gitignore tests prettier

internal/build/path_mapping.go, internal/build/path_mapping_test.go, internal/engine/upper.go, internal/ospath/ospath.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Hello @landism, @dmiller,
Please review the following commits I made in branch maiamcc/enforce-abs-repo:
82f8ab53ff1890c62dd166ee29efc0d270458d85 (2018-08-24 12:11:28 -0400)
mill: enforce repo is absolute path
e62010ab1889ca34c5b74a9275540fe2f331b93d (2018-08-24 11:51:23 -0400)
wip
=> mill: enforce repo is absolute path

internal/build/docker_test.go, internal/build/dockerfile.go, internal/testutils/temp_dir_fixture.go
addresses bug that @landism encountered: if user deletes a directory, we get the directory as the "changed path", which means dockerfile calls `RUN rf <dir>`, which obviously doesn't work if there's stuff in it hehhh.
=> build: support removing directories via dockerfile

internal/cli/up.go, internal/engine/upper.go
Please review the following commits I made in branch maiamcc/signal-trap:
db9589bffba0885276df09e5c098ce3fe610c5e0 (2018-08-27 11:02:39 -0400)
up: wait a bit before responding to SIGINT/SIGTERM to give tracing time to flush
=> up: wait a bit before responding to SIGINT/SIGTERM to give tracing time to flush

internal/cli/up.go, internal/output/outputter.go
it turns out there's a cleaner way to call the color library
also use the color library in up.go
=> tilt: clean up calls to color library

internal/build/container.go, internal/build/docker.go, internal/build/docker_benchmark_test.go, internal/build/docker_test.go, internal/build/dockerfile.go, internal/build/options.go, internal/build/options_buildkit.go, internal/engine/build_and_deployer.go, internal/engine/upper_test.go
I apologize for the size of this diff, I tried to break it out in to sensible commits below.
This diff replaces all instances of `digest.Digest` with `reference.NamedTagged`. This is necessary for BuildKit to work since it doesn't allow you to use digests in `FROM` statements in Dockerfiles anymore. Doing this touched a lot of files and involved changing not just building from existing docker files, but also from scratch, pushing, and more.
I pass the Buildkit flag in `ImageBuildOptions`.
Instead of returning a Digest from build, I tag the digest immediately and return the `reference.NamedTagged`.
Things that are broken:
1. History. I'm going to fix this in a later diff.
2. Streaming output.
=> build: use buildkit

internal/build/image_builder.go
note that ... I don't understand why this fixes the problem. =\
What I expected to happen after making this change is that I'd see the error printed instead of getting the segfault. Instead, afaict no error is printed.
=> build: if build output is nil then error

internal/build/image_builder.go, internal/output/outputter.go
Please review the following commits I made in branch nicks/printf:
576e4932c86e9e8bf9810cd2dd76352e51d9f421 (2018-08-29 12:07:05 -0400)
outputter: fix a broken call to Infof, change Print to Printf so that go vet checks it
=> outputter: fix a broken call to Infof, change Print to Printf so that go vet checks it

internal/build/container_test.go, internal/build/container_updater.go, internal/build/container_updater_test.go, internal/build/image_builder.go, internal/build/image_builder_test.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/container_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/wire.go, internal/engine/wire_gen.go, scripts/timing.py
should be a no-op -- containerBuildAndDeployer has an imageBuildAndDeployer on it, currently just calls that one. this PR is the set-up for actually hooking up container-based incremental builds
=> engine: re-wire to make a containerUpdater build-and-deployer (no-op)

internal/k8s/client.go
Hello @nicks,
Please review the following commits I made in branch nicks/browser3:
762cd3052419f8541770a9df456b2853b6cd3951 (2018-08-31 17:43:49 -0400)
minikube: add status messaging when minikube is stuck
=> minikube: add status messaging when minikube is stuck

internal/build/container_updater.go
Please review the following commits I made in branch nicks/container2:
0f80c5115020df3a807eb628b6ffba8a0fb9ca6c (2018-08-31 17:53:48 -0400)
build: don't wait on the container to fully start during restart
=> build: don't wait on the container to fully start during restart

internal/k8s/entity.go, internal/k8s/image.go, internal/k8s/image_test.go
Please review the following commits I made in branch nicks/deepcopy:
6aff581c8a686ab6acdf7320b2ce586c14fefc9a (2018-09-04 15:30:48 -0400)
k8s: do a deep copy of entity objects to avoid weird half-mutated objects
=> k8s: do a deep copy of entity objects to avoid weird half-mutated objects

internal/cli/up.go, internal/tracer/tracer.go, internal/tracer/tracer_test.go, scripts/timing.py
Please review the following commits I made in branch maiamcc/trace-tags:
9b2314823277974ee2a546885f9f6191c45819b2 (2018-09-05 15:33:41 -0400)
tilt calls from timing.py pass trace tags
38d8891ca9f48ae339a31cdb5e35d8e0ae6eee4d (2018-09-05 15:25:20 -0400)
tracer: implement span tags
=> tracing: add tags to spans (passable as command line args); add to timing.py

internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_test.go, internal/engine/container_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/result.go, internal/engine/upper.go, internal/engine/upper_test.go, scripts/timing.py
re: https://app.clubhouse.io/windmill/story/126/get-container-id-as-soon-as-initial-deploy-finishes
behavior works, interface-ing is sorta janky, feedback welcome. lmk if this is too ugly to land.
=> engine: get containerID earlier in pipeline

internal/cli/cli.go, internal/engine/image_build_and_deployer.go, internal/output/outputter.go, internal/output/outputter_test.go
Please review the following commits I made in branch maiamcc/ch136/good-err-output:
2fbd65bf3b7de7277a884b2650e8da23d504b8fa (2018-09-07 11:35:36 -0400)
output: indicate when pipeline errored
=> output: indicate when pipeline errored

Makefile
Hello @dbentley, @nicks,
Please review the following commits I made in branch maiamcc/lint-improper-pipeline-end:
70e7bbf6bc0b3fe51dc28588598a50d56ece599e (2018-09-07 13:01:05 -0400)
lint: verify no improper defers of PipelineEnd
=> lint: verify no improper defers of PipelineEnd

internal/build/fake_client.go, internal/build/image_reaper.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/reaper3:
a6a635487a69c109d4e31167685b4b335bcc79fa (2018-09-07 16:43:45 -0400)
engine: reap old images when starting a watch
=> engine: reap old images when starting a watch

internal/engine/upper.go, internal/engine/upper_test.go
If there's no image, we can't find the pod.
https://app.clubhouse.io/windmill/story/147/segfault-in-incremental-build
=> engine: only call GetContainerForBuild if we have an image

internal/engine/upper.go, internal/output/outputter.go, internal/output/summary.go, internal/summary/summary.go
Admittedly, this might be only minimally helpful to see the path in the summary. But this is part of a larger effort to add various data tidbits in here. Once we have this raw material in, it can then be refined and groomed.
=> output: summary includes path

internal/build/container_updater_test.go, internal/build/image_builder_test.go, internal/build/path_mapping_test.go, internal/build/tar_test.go, internal/dockerignore/ignore_test.go, internal/engine/build_and_deployer_test.go, internal/engine/up_watch_test.go, internal/engine/upper_test.go, internal/git/gitignore_test.go, internal/ospath/ospath_test.go, internal/testutils/output/context.go, internal/testutils/tempdir/temp_dir_fixture.go, internal/tiltfile/tiltfile_test.go
... to avoid circular dependencies in test
=> testutils: break apart tempdir and output ctx in to separate packages

cmd/synclet/main.go, internal/synclet/wire.go, internal/synclet/wire_gen.go
This is mildly ugly, but:
1. we're currently only using env to pass to DockerClient, which only uses it to override the method to read environment variables when in minikube
2. we don't expect people to be running this in minikube
=> tilt: synclet: hardcode unknown k8s env

internal/cli/up.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/syntax:
693afaa4e73906813a991c153d5afe04bce349bc (2018-09-12 14:26:52 -0400)
tiltfile: turn on nested functions so i can use them in servantes
=> tiltfile: turn on nested functions so i can use them in servantes

internal/synclet/synclet.go
this was causing failures when ephemeral files were deleted before tilt could pick them up (though maybe we should change the calling code to not pass those in the first place?)
=> tilt: synclet: use rm -rf instead of rm

internal/engine/upper.go
Please review the following commits I made in branch nicks/error:
28f63586ab378a16ecb796df21de3dadca102a64 (2018-09-13 14:35:44 -0400)
engine: demote gc errors to debug logs
=> engine: demote gc errors to debug logs

internal/engine/build_and_deployer_test.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/kubectl_runner.go, internal/k8s/pod.go, internal/k8s/pod_test.go
1. pull the actual exec out of KubectlClient so that we can fake it for tests
2. add GetNodeForPod and FindAppByNode so that given a service's PodID, we can find the PodID of the synclet running on the same node
=> tilt: add functions enabling us to find a synclet's pod

internal/k8s/client.go
idk if there's a reason to pass the runner via wire right now, but we can always implement that later if needed?
=> k8s: fix nil pointer exception -- make sure client has a kubectlRunner

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/kubectl_runner.go, internal/k8s/pod.go
Please review the following commits I made in branch maiamcc/more-generic-kubectlRunner:
930c223ccb35c2223f06dc330fc8e09abdf6f84d (2018-09-13 16:09:46 -0400)
k8s: more generic kubectlRunner so we can use it for more things, test better
=> k8s: more generic kubectlRunner so we can use it for more things, test better

internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/model/manifest.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch55/service:
5fdd655762d5d64f2ba456b3fa87dd4483abf7d2 (2018-09-13 16:32:08 -0400)
tiltfile: partial rename service -> manifest without changing syntax
=> tiltfile: partial rename service -> manifest without changing syntax

internal/engine/build_and_deployer_test.go, internal/engine/local_container_build_and_deployer.go, internal/engine/result.go, internal/engine/synclet_build_and_deployer.go, internal/engine/upper_test.go
in preparation for rewiring PostProcessBuilds to be concurrent [ch209]
=> buildAndDeploy: store deployInfo on BuildAndDeployer (rather than on build state)

internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
582a58507f988f50cf290cca38d1780f2d818cd7 (2018-09-14 17:24:04 -0400)
tiltfile: validate that the path exists
=> tiltfile: validate that the path exists

internal/build/container_test.go, internal/build/docker_benchmark_test.go, internal/build/image_builder_test.go, internal/build/tar.go, internal/build/tar_test.go, internal/testutils/tar.go
Please review the following commits I made in branch nicks/ch264/tar:
11fa162335818b68f85d686cf1f020f765d5c51c (2018-09-17 15:56:11 -0400)
build: move assertFileInTar into a helper package so i can use it elsewhere
=> build: move assertFileInTar into a helper package so i can use it elsewhere

internal/engine/build_and_deployer_test.go, internal/testutils/tar.go
Please review the following commits I made in branch nicks/tar:
7fa989c74181d4211e69d17f9830c45b7d025be7 (2018-09-18 11:58:25 -0400)
tests: add a cleaner function for asserting multiple files in a tarball
=> tests: add a cleaner function for asserting multiple files in a tarball

internal/engine/build_and_deployer_test.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/pod.go, internal/k8s/pod_test.go
This is motivated by needing to filter by username when getting the synclet (e.g., knowing whether to use maia's or dan's or my synclet), and while I was at it, I figured it wasn't pretty to hardcode the namespace into a k8s client function.
=> tilt: FindAppByNode: parameterize namespace + username

internal/dockerignore/ignore.go, internal/engine/up_watch.go, internal/git/gitignore.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
This does three things:
1) Read `.gitignore` and `.Dockerignore`, if present, upon invocation of `local_git_repo`. Store the path matcher on the `gitRepo` object
2) Associate the `gitRepo` to the `dockerImage` so that when we return the manifests we can assign a path matcher to the manifest
3) Use that path matcher in the up_watch code, rather than reading + parsing the ignore files there
Plus various cleanup.
=> tiltfile: read gitignore, associate with docker image, use on backend

internal/k8s/pod.go, internal/k8s/pod_test.go
I noticed when debugging today that `kubectl get pods -lowner=matt -lapp=synclet` was returning all the synclets, not just mine. It turns out that kubectl just keeps the last `-l` and silently drops any preceding ones, and the correct way to filter by multiple labels is to separate by commas. The code is working in practice as-is because we don't have any other pods with the 'owner' label.
=> fix kubectl -l args

Makefile
want to be able to check if everything builds, without gross output cruft
=> make: build command (so can ignore output cruft)

README.md, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Rather than passing around the image explicitly.
=> tiltfile: use an implicit build context for the docker image

internal/build/container_resolver_test.go, internal/docker/fake_client.go, internal/engine/local_container_build_and_deployer_test.go, internal/k8s/fake_client.go
tbh i don't know how useful it is to test this logic, lmk if you think these don't need to be in the codebase.
wanted SOME tests in place -- tho turns out that testing the new behavior (that we get deployInfo anew if we build a new image) is kind of silly and trivial.
if this looks like it's on the right track, can write tests for syncletBaD as well
=> engine: tests for local_container_bad.PostProcessBuild

internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile_test.go
https://app.clubhouse.io/windmill/story/341/improve-string-passed-to-add-instead-of-repopath-error-message
=> tiltfile: improve error message for add

internal/k8s/fake_client.go
we'll want this for #396
f30b2a80aaec1de21e9a42dc9996aadc9cb28c91 (2018-09-24 17:46:52 -0400)
k8s: can set PollForPod delay on fake client
=> k8s: can set PollForPod delay on fake client

internal/cli/cli.go
in my last PR i was waiting on something w/o checking for context.Cancelled and so i wanted to cover my ass
=> up: wait and os.Exit on sigint/sigterm in case we don't handle context cancel

internal/synclet/sidecar/sidecar.go
I was hitting cpu quota limits when trying to work on servantes. The default CPU allocation for containers is 100 mCPU, so we're paying 2x that per service (service + synclet). We should probably not consume CPU quota with the synclet.
The CPU request for the service itself is owned by the user, so not addressing that in tilt.
=> tilt: don't request cpu for synclet sidecar

internal/engine/sidecar_synclet_manager.go, internal/k8s/client.go, internal/synclet/client_adapter.go
i'm not positive that the client_adaptor is the right place to put this polling code... but sometimes we are able to connect to the synclet but it's not yet up and running in such a way that it can actually accept calls to `ContainerIdForPod`.
=> synclet: add polling/retries to synclet client creation, get container id [ch373]

internal/k8s/portforward.go
This should reduce the flood of tunnel errors.
1) I haven't yet seen an error for which we *don't* want to kill the portforward (i.e., a situation in which it might recover on its own)
2) we need to solve reconnects at a higher level anyway, so it shouldn't matter if we close the tunnel at this level
=> tilt: close portforwards on error

internal/synclet/synclet.go
So if we hit [this](https://app.clubhouse.io/windmill/story/380/error-removing-files-while-updating-container-on-temporary-idea-files) again, hopefully we can tell what's going on.
=> tilt: log more info in synclet when rm fails

internal/engine/up_watch.go, internal/git/gitignore.go, internal/model/manifest.go, internal/model/matcher.go, internal/tiltfile/tiltfile.go
Hello @nicks,
Please review the following commits I made in branch nicks/matcher:
43bc633d8388f5ba29ec8f5eb36886f4cdd834ca (2018-09-26 15:33:49 -0400)
model: organize empty matcher a bit
=> model: organize empty matcher a bit

internal/build/image_builder.go, internal/docker/fake_client.go
Please review the following commits I made in branch maiamcc/reusable-fake-docker-responses:
943bb4622cd458a0cc4fcaf8692bfd089b3ebf9f (2018-09-26 17:59:18 -0400)
docker: fix bug where fake client build/push were one-use-only
=> docker: fix bug where fake client build/push were one-use-only

internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_test.go, internal/engine/synclet_build_and_deployer.go
Please review the following commits I made in branch maiamcc/better-async:
77efe492438f114c144c86ec071ceb889fb4f9cb (2018-09-26 17:27:03 -0400)
engine: PostProcessDeploy should only pass control back to main thread after it has taken out locks
=> engine: PostProcessDeploy should only pass control [ch381]

Makefile
`man sed` on linux says
```
-E, -r, --regexp-extended
use extended regular expressions in the script
(for portability use POSIX -E).
```
this substitution works on my mac
=> tilt: use sed -E instead of -r

internal/engine/sidecar_synclet_manager.go, internal/engine/synclet_build_and_deployer.go, internal/k8s/client.go, internal/k8s/container.go, internal/k8s/container_test.go, internal/k8s/fake_client.go, internal/k8s/image.go, internal/k8s/portforward.go, internal/synclet/sidecar/sidecar.go
Please review the following commits I made in branch nicks/ch393/wait:
b5b16534fab7a2ea2ceb6081b2375c95594183d1 (2018-09-27 18:25:07 -0400)
synclet: wait for container up
in theory, this should failover more gracefully if the synclet or pod is
crashlooping or not coming up for some reason
=> synclet: wait for container up

internal/cli/up.go, internal/tracer/tracer.go
Ideally we'd be dropping the trace id into a URL that'd visualize the trace for you, but I haven't yet found any way to do that with honeycomb.
=> tilt: log traceid on startup

internal/engine/synclet_build_and_deployer.go, internal/k8s/container.go
Please review the following commits I made in branch maiamcc/prime-tunnel:
d223f891f3efc6a2b82b595dc30b89cbbd73c1b3 (2018-09-28 15:06:26 -0400)
synclet BaD: open tunnel/make synclet client asap so user doesn't have to wait
=> synclet BaD: open tunnel/make synclet client asap so user doesn't have to wait

internal/k8s/portforward.go
right now, if I kill a pod with a tunnel open, this gets printed to the console:
```
ERROR: logging before flag.Parse: E0928 15:53:51.779339   55827 portforward.go:331] an error occurred forwarding 55975 -> 23551: error forwarding port 23551 to pod ed9ff17ea164f04a0c5861b3455fe767d74147ec2f5b782c89945051c4d45b7e, uid : container not running (ed9ff17ea164f04a0c5861b3455fe767d74147ec2f5b782c89945051c4d45b7e)
ERROR: logging before flag.Parse: E0928 15:53:52.782373   55827 portforward.go:331] an error occurred forwarding 55975 -> 23551: error forwarding port 23551 to pod ed9ff17ea164f04a0c5861b3455fe767d74147ec2f5b782c89945051c4d45b7e, uid : container not running (ed9ff17ea164f04a0c5861b3455fe767d74147ec2f5b782c89945051c4d45b7e)
ERROR: logging before flag.Parse: E0928 15:53:54.089961   55827 …
```
=> tilt: move tunnel errors to debug level

internal/model/manifest.go, internal/model/matcher.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch353/files:
4f8d2e2288a81d1594d3b92e1882ec70dc74cda0 (2018-09-28 13:33:05 -0400)
tiltfile: track read files so that we can reload the manifest
=> tiltfile: track read files so that we can reload the manifest

internal/cli/wire_gen.go, internal/engine/synclet_build_and_deployer.go, internal/engine/synclet_manager.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/synclet/wire_gen.go
now that we're exclusively running the synclet as a sidecar, don't need 'sidecar' in the name to differentiate from daemonset.
not a big deal, but thought i'd clean it up
=> synclet: rename sidecar...client => ...client

.gitignore, Makefile
constant tags lead to us using any old image that happens to have that tag
=> tilt: use hashes in dev synclet tags

README.md
Two outstanding TODOs that I'd like feedback on:
1. Should we explain how `start_fast_build` is fast, and what image and container builds are?
2. We should probably explain the concept of the "active" build (if you call `start_fast_build` before calling `stop_build` there will be an error) but I'm not sure the best way to do that.
In the future we should probably use Sphinx, like we did in windmilleng/windmill.
=> readme: Make README more legible

internal/k8s/extract.go, internal/k8s/label.go, internal/k8s/label_test.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/labels:
b466fd3598197ad9b981d991393d1b8250c57807 (2018-10-02 18:16:26 -0400)
k8s: break out methods for applying labels
this is part of a larger change to do a better job selecting the right pods, but
labelling everything tilt deploys seems generally useful for auditing purposes
=> k8s: break out methods for applying labels

internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/local_container_build_and_deployer.go, internal/engine/local_container_build_and_deployer_test.go, internal/engine/pod.go, internal/engine/synclet_build_and_deployer.go, internal/k8s/client.go, internal/k8s/container_test.go, internal/k8s/fake_client.go, internal/k8s/label.go, internal/k8s/pod.go, internal/k8s/pod_test.go
Please review the following commits I made in branch nicks/ch436/labels:
45886270bb1a0b3c0f05861f3cc954e93d6fa68a (2018-10-02 20:01:23 -0400)
engine: inject and select labels to reduce the risk of collisions, and recognize that their might be more than one pod
57e0110c610c00d3b2305d52a63feb4204cef0ba (2018-10-02 19:50:59 -0400)
k8s: break out methods for applying labels
this is part of a larger change to do a better job selecting the right pods, but
labelling everything tilt deploys seems generally useful for auditing purposes
=> engine: inject and select labels to reduce the risk of collisions, and recognize that their might be more than one pod

internal/engine/local_container_build_and_deployer.go, internal/engine/synclet_build_and_deployer.go
Hello @nicks,
Please review the following commits I made in branch nicks/ch436/labels:
0c9b8207bfe3afc359ba39ec322896fa0311de35 (2018-10-03 11:30:01 -0400)
engine: add some logging when we find too many pods
=> engine: add some logging when we find too many pods

internal/engine/up_watch.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/model/manifest.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Same deal as last time: there are a couple outstanding TODOs and no tests but I wanted to validate the approach.
One question that's not in the code: It seems to me that we don't want to filter out any file events based off of information in the Tiltfile. Does that seem right? We certainly don't want to filter out file events for the dockerfile and tiltfile anymore and I couldn't think of any other situations.
=> engine: re-execute Tiltfile when config files for manifest change

integration/fixture_test.go, integration/oneup_test.go
71e5785a79d27d4225e3f4056b2e79ac7cffa615 (2018-10-04 15:14:33 -0400)
integration: fix a race condition: port-forwarding has to wait until all pods are up
=> integration: fix a race condition: port-forwarding has to wait until all pods are up

internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/mode.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/env.go
Please review the following commits I made in branch nicks/ch470/mode:
00da6ad6692b1e579ead5e448f5de31354b2b5ba (2018-10-03 12:15:06 -0400)
cli: add an update-mode flag to control update strategy
This flag is intended for people trying out Tilt for the first time
and want to better control what it's doing, and for testing.
=> cli: add an update-mode flag to control update strategy

Makefile, integration/fixture_test.go, internal/build/image_builder.go, internal/build/tag.go, internal/cli/up.go
Please review the following commits I made in branch nicks/images2:
b14563f439d8d23710aece02e5d32e146dde0ab8 (2018-10-05 10:46:34 -0400)
integration: add a flag to namespace container tags, so that integration tests don't step on each other
=> integration: add a flag to namespace container tags, so that integration tests don't step on each other

.circleci/Dockerfile.integration, .circleci/config.yml, Makefile, integration/README.md, integration/oneup_test.go
Please review the following commits I made in branch nicks/ch456/circle:
c9bc063eeeaa8e489f3d0d3bc3440d34c2c0b9aa (2018-10-05 12:15:44 -0400)
circleci: spin up a test k8s cluster and run tests against it
fe7d8a57630469afc39df862248521dc4da11258 (2018-10-05 12:05:47 -0400)
integration: add a flag to namespace container tags, so that integration tests don't step on each other
=> circleci: spin up a test k8s cluster and run tests against it

internal/engine/engine_state.go, internal/engine/up_watch.go, internal/engine/upper.go, internal/engine/upper_test.go
This makes it so that we update the engine state and HUD while the initial round of builds is executing.
It also slightly reduces duplicated code (we now only handle BaD in one place).
I don't have a good mental model about what the LB stuff is doing and am not sure I've made the right change. It's working on my machine, but I don't know if that's just because there are already LBs deployed or something.
=> tilt: move initial builds into event loop

internal/dockerignore/ignore.go, internal/dockerignore/ignore_test.go, internal/engine/build_and_deployer_test.go, internal/git/gitignore.go, internal/git/gitignore_test.go, internal/model/manifest.go, internal/model/matcher.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Instead just pass the contents of the ignore files along so they can be
parsed later. This is important so that we can end up with a manifest
that consists entirely of comparable fields.
=> tiltfile: don't parse ignore files at runtime

internal/build/image_builder.go, internal/build/image_builder_test.go, internal/model/manifest.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch517/entrypoint:
81b5e5957793e34731401670fea430c4157cbf6e (2018-10-08 18:01:59 -0400)
tiltfile: fix phantom entrypoints and apply labels later to help caching
=> tiltfile: fix phantom entrypoints and apply labels later to help caching

internal/tiltfile/skylarkTypes.go, internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Note that with this approach we only record a repo if it is used in a mount. This might be OK, but if you used a `repo.path` and interpolated in to like a `local` command and _never_ used it in a mount we wouldn't know that you used it
=> tiltfile: associate repos to mounts iff they are used

internal/build/container_resolver.go, internal/cli/wire_gen.go, internal/engine/build_and_deployer_test.go, internal/engine/deploy.go, internal/engine/local_container_build_and_deployer.go, internal/engine/local_container_build_and_deployer_test.go, internal/engine/synclet_build_and_deployer.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/fake_client.go
Please review the following commits I made in branch nicks/deploy:
11424495ee6af0382727f3d794e2afcb6f30f460 (2018-10-10 11:29:03 -0400)
engine: pull deploy discovery into a separate object, so i can use it for port-forwarding
=> engine: pull deploy discovery into a separate object, so i can use it for port-forwarding

internal/model/manifest.go, internal/model/manifest_test.go, internal/tiltfile/tiltfile.go
It's possible that other slices in the manifest will need to be treated the same, but I haven't observed any of the others being unstable yet. Cross that bridge when we get to it.
=> model: config file equality is not order dependent

internal/engine/actions.go, internal/engine/pod_watch.go, internal/engine/store.go, internal/engine/up_watch.go, internal/engine/up_watch_test.go, internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/actions:
6fe0c1d87cae5248332f883f0261050cda8f0bde (2018-10-10 15:47:01 -0400)
engine: organize watch loop to use reactive programming conventions
=> engine: organize watch loop to use reactive programming conventions

internal/engine/deploy.go, internal/engine/deploy_test.go, internal/engine/local_container_build_and_deployer.go, internal/engine/local_container_build_and_deployer_test.go, internal/engine/synclet_build_and_deployer.go, internal/k8s/fake_client.go
Please review the following commits I made in branch nicks/deployinfo:
f92aaaad732f38eb39cd15155d7e7472d68ed176 (2018-10-11 12:43:43 -0400)
engine: separate out the DeployInfo data from deployInfo readiness
=> engine: separate out the DeployInfo data from deployInfo readiness

internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/gitignore:
4333eff7551d0cf83fbc385b52ee84e3ca02f3cb (2018-10-11 15:21:39 -0400)
tiltfile: respect gitignore when adding subpaths. Fixes gitignore in servantes
=> tiltfile: respect gitignore when adding subpaths. Fixes gitignore in servantes

internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/actions.go, internal/hud/fake_hud.go, internal/hud/hud.go, internal/hud/renderer.go, internal/testutils/output/context.go
The 1-9 keys will now replay the last build log for that resource (in display order).
This is not the interface we intend to ship with the alpha, but is a cheap way to get us basic usability while we mature the UI code.
=> tilt: support build log replay

internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/store.go
Please review the following commits I made in branch nicks/rlock:
e14b135ef3126a9ff86028e235d116ea94b67cfc (2018-10-11 16:29:16 -0400)
engine: use rwlocks to control access to state
=> engine: use rwlocks to control access to state

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/service_watch.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/renderer.go, internal/hud/view/view.go, internal/k8s/client.go, internal/k8s/fake_client.go, internal/k8s/watch.go, internal/k8s/watch_test.go, internal/store/engine_state.go
1. subscribe to k8s service changes (most of the code in this diff is copying the pod-watching code for service watching.
2. when we get an LB, save its URL into EngineState
3. render those URLs in the HUD
=> tilt: put LB URLs in EngineState and HUD

internal/engine/pod_watch.go, internal/engine/service_watch.go, internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/loops:
b58edd3209aacc91fdc67e149332fecac08d3602 (2018-10-12 17:26:09 -0400)
engine: clean up loops on cancel, so that there are fewer goroutines to sort thru in tests
=> engine: clean up loops on cancel, so that there are fewer goroutines to sort thru in tests

internal/cli/hud.go
Problem:
For some reason, tcell's `Fini` is not working in the `hud` process, whether called from the `hud` process itself, or on the hud's tty from the `up` process. When the hud exits, we're left with a terminal that doesn't echo input, show the cursor, or reset to column 0 on `\n` (among probably others).
Solution:
Call `reset` from the hud before we exit. This ain't great because it clears the screen.
I also tried saving off the termios before and restoring it after. That mostly worked, and did not clear the screen, but still left me with an invisible cursor for reasons I did not manage to understand in 20 minutes.
=> tilt: reset terminal on hud exit

internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/timer:
bc6590fdeb11d5c514db72d2ce52c5b2a1757292 (2018-10-12 17:54:48 -0400)
engine: disable the refresh timer in testing
=> engine: disable the refresh timer in testing

internal/engine/up_watch.go, internal/engine/up_watch_test.go, internal/ignore/path_matcher.go
If config files are ignored then we won't learn about changes to them,
which breaks users expectations that, if they change yaml or the
Tiltfile that their manifests are changed.
=> engine: config files aren't ignored at the watch level

internal/cli/wire_gen.go, internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/fake_client.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/ch551:
3cd7bafb6209d96950f66ba2e2ff6d95adf697c7 (2018-10-16 11:05:48 -0400)
engine: auto-reconnect log streaming if the container crashes by making PodLogManager more reactive
=> engine: auto-reconnect log streaming if the container crashes by making PodLogManager more reactive

internal/hud/renderer.go
1. when a pod has a status with no defined color, we are printing black on black, which ain't great
2. we could probably give the "pending" status the color for pending!
=> tilt: fix pod unknown/pending status color

.gitignore, internal/engine/deploy.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/container.go
Please review the following commits I made in branch nicks/cid:
9dbd65f3303d9617f753b53579f523e043bc8f8d (2018-10-16 15:19:17 -0400)
engine: correctly handle the case when the container id hasn't materialized
=> engine: correctly handle the case when the container id hasn't materialized

internal/hud/hud.go
we've been printing this when quitting `tilt up` with a hud attached:
`^Cerror in hud: context canceled`
no more!
=> tilt: don't print hud context canceled errors

.circleci/config.yml, internal/watch/notify_test.go, internal/watch/watcher_darwin.go
TODO: I need to write a test for this new behavior, wanted to get this solution in front of y'all first.
Here's our new watch strategy on Darwin in a nutshell:
1. Create an fsevents stream for events "since" the last event ID that
we saw globally.
2. Add a path that we want to watch
3. Add that path to a map of paths that we're watching _directly_.
4. Restart the event stream to pick up the new path.
5. Ignore all events for all watches until we've seen a `HistoryDone`
event.
6. Ignore the first `ItemCreated` event for paths we're watching that
are also directories
7. Otherwise, forward along all events.
=> watch: use `sinceWhen` and `HistoryDone` to avoid spurious events

internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Please review the following commits I made in branch maiamcc/break-unbreak:
0e4e0c70a5e510dec426d99ca34a0194afed8c81 (2018-10-17 16:52:51 -0400)
engine: don't image build if config file changes but doesn't result in manifest change
=> engine: don't image build if config file changes but doesn't result in manifest change

internal/tiltfile/skylarkTypes.go, internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/rel:
9c7473d76e94154269be992404ef1fece87885e9 (2018-10-17 17:35:32 -0400)
tiltfile: read relative to tiltfile dir instead of working dir
We expect that the Tilt demo will have an arbitrary workdir
=> tiltfile: read relative to tiltfile dir instead of working dir

internal/demo/script.go, internal/demo/step.go
Please review the following commits I made in branch nicks/ch586/checkout:
554877407d5f6c60ec101d57508e86e5436da17e (2018-10-17 20:04:12 -0400)
demo: add a script
ee3ddef9e82ac192a07dd686d72bdd424fc1e3f8 (2018-10-17 20:04:00 -0400)
demo: make the demo connect to the hud directly
6ab36f26c6af4a2c657f8c5353f2f870055681e1 (2018-10-17 20:04:00 -0400)
tiltfile: read relative to tiltfile dir instead of working dir
We expect that the Tilt demo will have an arbitrary workdir
7b5b823c90383e74e1f7a5e371b6db95c4688468 (2018-10-17 20:00:32 -0400)
build: fmt.Printf interrupts TTY / HUD. everything needs to go thru logger
=> demo: add a script

internal/hud/client/client.go
Please review the following commits I made in branch maiamcc/no-reset-on-hud-quit:
7075194c2fe2a6ea841c69181a1e8aae20d220ac (2018-10-18 14:45:57 -0400)
hud: hud exit works, so no more need for hack where we reset the terminal
=> hud: hud exit works, so no more need for hack where we reset the terminal

internal/build/path_mapping.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/testutils/tempdir/temp_dir_fixture.go
Addresses [ch621](https://app.clubhouse.io/windmill/story/621/configfiles-not-copied-to-container).
If a config file changes but this doesn't result in a change to the manifest, we incremental build (since a bug fixed in #561) -- but incremental build runs individual changed files through `FilesToPathMapping` (unlike image build, which just makes a mapping per mount).
So when we change e.g. a Tiltfile and it DOESN'T change the manifest and results in an incremental build, we try to make a path mapping of Tiltfile and get an error b/c Tiltfile doesn't belong to any of our mounts.
The solution in this PR is to filter out non-mounted config files from the changed files set before continuing with the build process.
We should probably do this for the changed manifest case as well to be …
=> engine: pass config files as changed files iff they belong to a mount

internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Problem: when a pod gets into a crash loop, log replay pretty quickly starts showing 20 panics
Solution: don't show logs from pods preceding the last one or two
My first pass at the tests for this were pretty ugly, so I also added some new helper methods and converted some existing tests to use them, which ended up being a lot of the diff.
=> tilt: don't show pod logs from old crashes

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/reactive:
796185c3234d118064b9ae07667627215373f99c (2018-10-19 19:27:51 -0400)
engine: refactor into a reactive builder, so we can build in response to things like pod restarts, etc
=> engine: refactor into a reactive builder, so we can build in response to things like pod restarts, etc

internal/engine/buildcontroller.go
Hello @nicks,
Please review the following commits I made in branch nicks/gofmt:
d69c3cb08187c13a37cf4bbf37b7fb01b7ed7748 (2018-10-22 17:21:10 -0400)
gofmt 1.10 vs 1.11 is different
=> gofmt 1.10 vs 1.11 is different

internal/engine/actions.go, internal/engine/buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/reactive:
bb3a36120ed02c9b25feeacca72f966e60785a14 (2018-10-22 17:33:40 -0400)
engine: move more logic into BuildController, take tiltfile reloading out of the write lock
=> engine: move more logic into BuildController, take tiltfile reloading out of the write lock

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/pod_watch.go, internal/engine/service_watch.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/synclet/wire_gen.go
Please review the following commits I made in branch nicks/watcher:
b7e645fe9e6b89850e580cafa79b3886dd6faf6f (2018-10-23 16:59:29 -0400)
engine: change podwatcher and servicewatcher to use the subscriber interface
=> engine: change podwatcher and servicewatcher to use the subscriber interface

internal/hud/renderer.go
1. we were showing k8s LB below the log:
```
BUILD: Last build (done in 1s) ended <1m ago — OK
K8S: Pod [matt-fe-b5558bcc6-jk699] • <1m ago — Error [2 restart(s)]
LOG: panic: hellllooooo
goroutine 1 :
main.main()
/go/src/github.com/windmilleng/servantes/fe/main.go:39 +0x39
http://localhost:8080/
```
move it above:
```
BUILD: Last build (done in 1s) ended <1m ago — OK
K8S: Pod [matt-fe-b5558bcc6-jk699] • <1m ago — Error [2 restart(s)]
LOG: panic: hellllooooo
goroutine 1 :
main.main()
/go/src/github.com/windmilleng/servantes/fe/main.go:39 +0x39
http://localhost:8080/
```
2. we were missing a space on Last deployed edits
=> tilt: fix a couple minor hud layout issues

Makefile, internal/build/test_utils.go
The image tests are regularly making `make test` take 10x as long, and are generally not relevant to what I'm working on.
=> tilt: make it easy to skip image tests

README.md, integration/fixture_test.go, internal/cli/up.go
5da328023a9935bfac840d61b7bd1b396aea3768 (2018-10-24 18:20:21 -0400)
cli: tilt watch-mode should be the default
=> cli: tilt watch-mode should be the default

internal/engine/upper_test.go
Please review the following commits I made in branch maiamcc/configDirty-tests:
bda6c1609c2805709bbc2ed9980b1b8db74eef28 (2018-10-25 11:50:24 -0400)
engine: make configIsDirty tests better
=> engine: make configIsDirty tests better

internal/engine/watchmanager.go, internal/ignore/path_matcher.go, internal/model/globalyaml.go, internal/model/manifest.go, internal/store/engine_state.go
Unified in the appropriate places with the new `WatchableManifest`
interface, that both `model.Manifest` and `model.GlobalYAMLManifest`
implement.
=> model: new type of manifest that is only YAML

internal/hud/hud.go, internal/rty/components.go, internal/rty/scroll.go
1. Default to the bottom of the log when you open it
2. If you're at the bottom of the log, keep scrolling with new log output
3. Add support for home/end keys
=> tilt: enable log following for resource logs

internal/build/container_resolver.go, internal/build/container_updater.go, internal/build/image_builder_test.go, internal/build/test_utils.go, internal/container/container.go, internal/docker/client.go, internal/docker/fake_client.go, internal/engine/build_and_deployer_test.go, internal/engine/deploy.go, internal/engine/local_container_build_and_deployer_test.go, internal/engine/podlogmanager.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/container.go, internal/k8s/container_test.go, internal/k8s/fake_client.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/k8s/pod.go, internal/k8s/pod_test.go, internal/model/manifest_test.go, internal/store/build_result.go, internal/store/engine_state.go, internal/synclet/client_adapter.go, internal/synclet/fake_client.go, internal/synclet/server_adapter.go, internal/synclet/sidecar/sidecar.go, internal/synclet/synclet.go
feel free to tell me that this PR isnt worth merging, but it's been
bugging me for a bit that we're keeping all this code in the k8s package
when it's not k8s specific at all. (It can't go straight into the `docker`
package however cuz we get import cycles.)
=> container: move container-related stuff out of k8s cuz they don't really belong there

internal/cli/down.go, internal/cli/up.go, internal/demo/script.go, internal/engine/actions.go, internal/engine/buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/model/globalyaml.go, internal/store/engine_state.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/global-yaml-prelim-refactor:
7c44de9f85aafc86cdaa70010bcdd7a24e3986d6 (2018-10-26 17:14:32 -0400)
tiltfile: prelim refactor to support global yaml returned when we get manifests
=> tiltfile: prelim refactor to support global yaml returned when we get manifests [ch682]

internal/engine/image_build_and_deployer.go, internal/engine/parse.go, internal/engine/testdata_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/model/globalyaml.go, internal/model/manifest.go, internal/model/manifest_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Mostly renaming and hiding struct fields behind functions. Next PR will pass the global YAML manifest, which now implements, albeit questionably, `buildableImageManifest`.
=> engine: image build and deployer substeps take an interface

internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go
Please review the following commits I made in branch maiamcc/gyaml-tiltfile-thread:
d19aa1e5b36ed6d409659ca0c4dd0fff6a152cfb (2018-10-30 12:06:41 -0400)
tiltfile: store global yaml and deps on skylark thread instead of tiltfile obj
=> tiltfile: store global yaml and deps on skylark thread instead of tiltfile obj [ch707]

internal/cli/up.go, internal/demo/script.go, internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch maiamcc/gyaml-to-init:
5b6bdca2f4df4bea6620d02ed5d11f8eedc3c961 (2018-10-30 12:17:28 -0400)
engine: call init with global yaml [ch708]
=> engine: call init with global yaml [ch708]

internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/buildcontroller.go, internal/engine/global_yaml_buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/model/globalyaml.go, internal/synclet/wire_gen.go
Adds a new subscriber and some actions to detect when the global YAML manifest has changed correctly, and trigger a global YAML build (to be defined) in that case.
=> engine: global YAML can be updated

internal/k8s/entity.go, internal/k8s/testyaml/testyaml.go, internal/model/manifest.go, internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go, internal/yaml/utils.go, internal/yaml/utils_test.go
Please review the following commits I made in branch maiamcc/parse-global-yaml:
9574cf099829caded9a8feefedcd161a57f22a5b (2018-10-30 18:06:06 -0400)
tiltfile: on manifest creation, pull matching yaml l out of globalYAML and add to manifest [ch681]
=> tiltfile: on manifest creation, pull matching yaml l out of globalYAML and add to manifest [ch681]

internal/engine/upper_test.go, internal/hud/fake_hud.go
Please review the following commits I made in branch nicks/ch712/upper:
7dcb59c96553438d21333a99704562e1bb566bc6 (2018-10-31 15:10:24 -0400)
engine: upper tests should wait on state changes rather than counting out the number of HUD updates
=> engine: upper tests should wait on state changes rather than counting out the number of HUD updates

internal/cli/down.go, internal/cli/up.go, internal/demo/script.go, internal/engine/buildcontroller.go, internal/engine/upper_test.go, internal/k8s/entity.go, internal/k8s/extract.go, internal/k8s/extract_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_global_yaml_test.go, internal/tiltfile/tiltfile_test.go
Hello @nicks, @jazzda,
Please review the following commits I made in branch maiamcc/assoc-services:
7f7759c4e96f5173bde1116ce10daadefc97a708 (2018-10-31 17:50:08 -0400)
tiltfile: when extracting per manifest yaml from global yaml, also grab services that select for k8s entities matching the image
=> tiltfile: when extracting per manifest yaml from global yaml, also grab services that select for k8s entities matching the image [ch688]

README.md, Tiltfile, integration/oneup/Tiltfile, integration/onewatch/Tiltfile, internal/engine/upper_test.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_global_yaml_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/yaml-opt-arg:
671c8cda19dbf0dc3d8cb718a863e2b9771edf89 (2018-11-01 18:00:01 -0400)
tiltfile: k8s_service takes yaml as an OPTIONAL arg
=> tiltfile: k8s_service takes yaml as an OPTIONAL arg [ch715]

internal/cli/cli.go, internal/cli/down.go
Please review the following commits I made in branch maiamcc/tilt-down:
b12b00a67a0002ed403ab511d6e2aff417344e99 (2018-11-05 17:01:54 -0500)
cli: tilt down deletes k8s resources created via global yaml [ch698]
=> cli: tilt down deletes k8s resources created via global yaml [ch698]

internal/cli/down.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/buildcontroller.go, internal/engine/tiltfile_watcher.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/watchmanager.go, internal/engine/wire_gen.go, internal/store/engine_state.go, internal/synclet/wire_gen.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_global_yaml_test.go, internal/tiltfile/tiltfile_test.go
Note there are a couple tests that fail, I think I'm just going to rewrite them? For the record they are:
* `TestRebuildDockerfileFailed`
* `TestBreakManifest`
* `TestBreakAndUnbreakManifestWithNoChange`
* `TestBreakAndUnbreakManifestWithChange`
Wanted to get folk's eyes on this while I work on that solicit ideas for what could be wrong with those tests in the meantime. :)
=> engine: when tiltfile changes re execute all the manifests

README.md, internal/build/image_builder.go, internal/model/manifest.go, internal/model/manifest_test.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
In a subsequent PR I will use the new `StaticBuildArgs` field on `model.Manifest` to apply the build args in the image builder.
=> tiltfile: add build_args param to static_build

internal/build/image_builder.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/validate:
a3e381f7966969f13fa01fdd397e44859be6320f (2018-11-08 17:38:02 -0500)
tiltfile: move base dockerfile validation to Tiltfile
this should help produce better error messages, and also fixes an issue
where directory caches do have COPYs from other images
=> tiltfile: move base dockerfile validation to Tiltfile

internal/cli/up.go
Problem:
A couple of libraries we use (k8s, fswatch) log using golang's `log` package, which writes to the screen and screws up the hud.
Solution:
Tell golang's `log` package to write to the tilt logger.
=> tilt: redirect go logs to tilt logs

internal/model/manifest.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_global_yaml_test.go
Please review the following commits I made in branch maiamcc/gyaml-composite:
4e86a85d2d8606cb075d0f3365ef7d121d1c8692 (2018-11-09 15:54:17 -0500)
tiltfile: extract per yaml manifest from global yaml when loading composite services
=> tiltfile: extract per yaml manifest from global yaml when loading composite services [ch771]

README.md, internal/tiltfile/skylarkTypes.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch728/cache:
d4cd1f0bdbb2f6c6c0beb28d50f05d64c5319a7f (2018-11-09 16:50:05 -0500)
tiltfile: add syntax for cache paths
=> tiltfile: add syntax for cache paths

Gopkg.lock, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/deploy.go, internal/engine/deploy_test.go, internal/engine/local_container_build_and_deployer_test.go, internal/engine/podlogmanager_test.go, internal/engine/upper_test.go, internal/engine/watchmanager_test.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/store/engine_state.go, internal/store/store.go, internal/store/subscriber_test.go, vendor/gopkg.in/d4l3k/messagediff.v1/.coveralls.yml, vendor/gopkg.in/d4l3k/messagediff.v1/.gitignore, vendor/gopkg.in/d4l3k/messagediff.v1/.travis.yml, vendor/gopkg.in/d4l3k/messagediff.v1/CHANGELOG.md, vendor/gopkg.in/d4l3k/messagediff.v1/LICENSE, vendor/gopkg.in/d4l3k/messagediff.v1/README.md, vendor/gopkg.in/d4l3k/messagediff.v1/bypass.go, vendor/gopkg.in/d4l3k/messagediff.v1/bypasssafe.go, vendor/gopkg.in/d4l3k/messagediff.v1/messagediff.go
Add `--logactions` flag that causes every action and state change to be logged. Dan and I found this useful when debugging this afternoon.
e.g.:
```
action engine.BuildCompleteAction:
(engine.BuildCompleteAction) {
Result: (store.BuildResult) {
Image: (reference.taggedReference) gcr.io/windmill-public-containers/servantes/vigoda:tilt-e850a6711ff65719,
ContainerID: (container.ID) ,
Namespace: (k8s.Namespace) (len=7) default,
Entities: ([]k8s.K8sEntity) (len=2 cap=2) {
(k8s.K8sEntity) {
Obj: (*v1.Deployment)(0xc000354000)(&Deployment{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:matt-vigoda,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[st …
```
=> tilt: add action logging

internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/k8s/testyaml/testyaml.go, internal/tiltfile/tiltfile_global_yaml_test.go
Please review the following commits I made in branch nicks/doubleimages:
7b4baf218ab3b243c3fcce5b6b1cb7f3cad764e5 (2018-11-09 19:30:22 -0500)
testyaml: add tests for twin yamls (k8s resources with the same image)
=> testyaml: add tests for twin yamls (k8s resources with the same image)

cmd/tilt/main.go
Please review the following commits I made in branch nicks/glog:
6b1e0582d3ca46279f035a1bbdf3249af90abf98 (2018-11-16 17:29:12 -0500)
tilt: disable glog to avoid problems where TTY is garbage
=> tilt: disable glog to avoid problems where TTY is garbage

internal/testutils/tempdir/temp_dir_fixture.go, internal/testutils/tempdir/temp_dir_fixture_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/tempdir:
cf980912833393786e48ffa4d6c2c34383c5f25c (2018-11-20 11:04:45 -0500)
testutils: fix a bug in tempdir fixture that made it impossible to use in table-based tests
=> testutils: fix a bug in tempdir fixture that made it impossible to use in table-based tests

internal/k8s/label.go, internal/k8s/label_test.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/ch846/labels:
9969f3bbf9f80deabbd629fdd2ef4e27c62fe576 (2018-11-20 13:13:36 -0500)
k8s: fix betav1 and betav2 deployments before injecting labels
=> k8s: fix betav1 and betav2 deployments before injecting labels

internal/demo/script.go, internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go, internal/engine/portforwardcontroller.go, internal/engine/portforwardcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/image.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/synclet/sidecar/inject.go
Please review the following commits I made in branch nicks/ch774/multipods:
8f56d5d697690624d438bca95eb43deaedfd4a60 (2018-11-20 12:42:42 -0500)
engine: Support multiple pods for the same manifest
There are a variety of reasons why you might have multiple pods:
a Deployment with more than 2 replicas, or 2 Deployments using the same
image. It's not super important why they're there, just that we handle
them in a reasonable way.
=> engine: Support multiple pods for the same manifest

internal/engine/upper_test.go, internal/hud/view/view.go, internal/ospath/ospath.go, internal/ospath/ospath_test.go, internal/store/engine_state.go
@yuindustries this should let you differentiate files and directories in the view code and render them differently, with or without a trailing slash.
=> store: keep track of whether a watched path is a dir or a file

internal/engine/upper.go
This _kind of_ works. @maiamcc I think that this ends up encountering the nil pointer reference that we saw with @dbentley when we were experimenting adding/removing resources.
=> engine: don't bail out if tiltfile isn't present, wait for it to appear

internal/cli/wire_gen.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/fake_client.go
Output looks like this if it can't:
```
> tilt up foo
Error: Unable to connect to cluster via `kubectl cluster-info`: exit status 1
stdout: Kubernetes master is running at https://localhost:6443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
stderr: The connection to the server localhost:6443 was refused - did you specify the right host or port?
```
=> engine: check if we can connect to k8s during start

internal/engine/buildcontroller_test.go, internal/engine/upper_test.go
If you break Engine tests, they hang in annoying and hard-to-debug ways.
This should help.
=> engine test: get next buildAndDeployer call with a timeout so tests don't hang if broken

internal/engine/actions.go, internal/engine/buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/ch719/panic2:
b76d038716c9dcceef124a33493961dd7e9dd25f (2018-11-27 11:56:08 -0500)
engine: represent build logs as an action so that the ui responds to build log updates
=> engine: represent build logs as an action so that the ui responds to build log updates

internal/engine/upper.go
pretty sure the line i removed is redundant with the one before it,
since `ms` is a pointer to whatever lives in the map? but in the case
where there isn't an entry for the given manifest in `state.ManifestStates`,
we'll get a panic here.
=> engine: remove possible panic when handling config reload

internal/engine/actions.go, internal/engine/global_yaml_buildcontroller.go, internal/engine/global_yaml_buildcontroller_test.go, internal/engine/upper.go, internal/k8s/fake_client.go
this addresses [ch920](https://app.clubhouse.io/windmill/story/920/errors-in-global-yaml-are-handled-poorly)
also fixes bad `LastApplyDuration` on parse errors (due to not emitting a `GlobalYAMLApplyStartedAction`)
=> tilt: clean up global yaml error handling

internal/rty/interactive_tester.go
`os.Exit` and the repeated `screen.Fini` don't make me happy, but I don't see a cheap way to do it more properly, and I'm not sure this case justifies a fancy way.
=> tilt: add 'q' to interactive tester

internal/cli/down.go, internal/cli/wire_gen.go, internal/dockercompose/compose.go, internal/engine/actions.go, internal/engine/build_and_deployer.go, internal/engine/build_errors.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer.go, internal/engine/imagecontroller.go, internal/engine/local_container_build_and_deployer.go, internal/engine/synclet_build_and_deployer.go, internal/engine/upper.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/model/manifest.go, internal/synclet/wire_gen.go, internal/tiltfile/skylarkTypes.go, internal/tiltfile/thread_local.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
(note -- this code doesn't have tests, I'm going to merge it onto a separate branch)
Hello @dbentley, @jazzdan,
Please review the following commits I made in branch maiamcc/dc-tiltfile-and-build-deploy:
9a2dd89a222da3230393b65b737e8073d15eb688 (2018-11-29 17:16:46 -0500)
down works with dc services
abe89e7441db4c6b4bf61a82464a2e08db844d3f (2018-11-29 17:01:22 -0500)
tests green
c674f0f113213743bafcb76a4ee677dbf7efcc52 (2018-11-29 16:53:11 -0500)
fix a million merge conflicts
84904c5c004f9515c807ec8eb604cfb2b347b15a (2018-11-29 16:49:55 -0500)
remove dcmeta manifest -- dcBad can now up -d docker compose svcs
80ec1317569c9617e7c86c62642909c1671f8190 (2018-11-29 16:49:03 -0500)
checkpoint
* Code is easy …
=> docker-compose: support dc manifests from tiltfile, tilt up and down

internal/k8s/client.go
Please review the following commits I made in branch nicks/ch768/down:
752143ca166bd39a7f8e9c8410984c82800340ac (2018-11-28 14:10:21 -0500)
k8s: ignore delete errors when the resource isn't found
=> k8s: ignore delete errors when the resource isn't found

internal/engine/upper_test.go, internal/engine/watchmanager.go
Fixes https://app.clubhouse.io/windmill/story/849/if-you-add-a-new-config-file-or-mount-to-a-resource-it-doesn-t-get-watched
=> engine: diff dependencies in watchmanager in addition to manifests

internal/build/container_test.go, internal/build/path_mapping.go, internal/build/path_mapping_test.go, internal/build/tar.go
My one big question: is there a better way to indicate that the destination of a mount is a directory other than requiring that a `/` be appended?
Also I'm pretty sure this approach won't work in Windows.
=> build: support mounting files to directories

internal/cli/wire.go, internal/cli/wire_gen.go, internal/dockercompose/event.go, internal/dockercompose/info.go, internal/dockercompose/logs.go, internal/engine/actions.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_event_watcher.go, internal/engine/docker_compose_log_manager.go, internal/engine/podlogmanager.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/synclet/wire_gen.go
Known bug: doesn't support getting logs since a certain time. usually
not a problem since we rebuild with --force-recreate so have a clean
container every time. however, it's annoying if there are already dc
services running when the user calls `tilt up` -- then we periodically
get old error logs for the old versions of the services as their deps
all die, until the services themselves reboot. not great.
=> [docker-compose] prelim log support [ch978]

internal/cli/up.go
Please review the following commits I made in branch maiamcc/log-levels:
6042cb0b0be05d978e293e5334c8c04cb95d3aac (2018-12-07 17:34:51 -0500)
logger: funcLogger should observe log levels
=> logger: funcLogger should observe log levels

internal/engine/image_build_and_deployer.go, internal/engine/imagecontroller.go, internal/engine/upper.go, internal/k8s/testyaml/testyaml.go, internal/model/manifest.go, internal/store/engine_state.go, internal/tiltfile2/tiltfile.go, internal/tiltfile2/tiltfile_state.go, internal/tiltfile2/tiltfile_test.go
Please review the following commits I made in branch nicks/globalyaml2:
1ce65986bee153c241971fbe9c47009b386f7628 (2018-12-10 15:04:10 -0500)
tiltfile: correctly handle k8s resources that aren't associated with a manifest
=> tiltfile: correctly handle k8s resources that aren't associated with a manifest

internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/crash:
97336d23e7bc06a1e0d74924aa17b36f861a9d6b (2018-12-10 15:50:40 -0500)
engine: fix crash-rebuilds when the pod updates before the build finishes
=> engine: fix crash-rebuilds when the pod updates before the build finishes

internal/tiltfile2/tiltfile.go, internal/tiltfile2/tiltfile_state.go, internal/tiltfile2/tiltfile_test.go
Please review the following commits I made in branch nicks/ch1000/garbage:
f5d592ce7381d6d89344585245ec4c2b8bbd038f (2018-12-10 17:54:54 -0500)
tiltfile: fix error on typo'd resource names
=> tiltfile: fix error on typo'd resource names

internal/docker/client.go, internal/docker/client_test.go
Please review the following commits I made in branch nicks/ch1104/minikube:
e19ed6c02a570b45d3af177bb7cbc9f8c6a189ed (2018-12-12 11:09:58 -0500)
docker: some versions of docker reject requests for buildkit with error if it's not supported :sob:
=> docker: some versions of docker reject requests for buildkit with error if it's not supported :sob:

internal/tiltfile2/files.go, internal/tiltfile2/tiltfile_test.go
cc @jazzdan
Please review the following commits I made in branch nicks/dockerignore:
d894bfdb4ece7a10e74f94f4ee56a83820f001dd (2018-12-13 11:59:02 -0800)
tiltfile2: auto-infer git repos
this is the first part of a bigger change in how we
do dockerignore/gitignore to accomodate the new tiltfile changes
=> tiltfile2: auto-infer git repos

internal/model/manifest.go
idk if this is the right way to address this problem, but if you mount
/my/dir/nested and then mount /my/dir, the latter doesn't get properly watched.
This seemed like a cheap fix.
=> model/manifest: sort result of manifest.Dependencies()

.circleci/config.yml, internal/tiltfile2/docker_compose.go, internal/tiltfile2/tiltfile_test.go
@maiamcc any other assertions I should add for this basic test?
I also changed the docker compose yaml path to be absolute to match how we treat other files that we read and store in memory.
=> tiltfile2: basic test for loading a docker compose manifest

internal/tiltfile2/docker_compose.go, internal/tiltfile2/tiltfile.go, internal/tiltfile2/tiltfile_state.go, internal/tiltfile2/tiltfile_test.go
Also introduce the concept of a tiltfileRoot which could, in the future,
allow the Tiltfile and the directory we operate in to be disjoint paths.
=> tiltfile2: resolve docker-compose path relative to tiltfile root

internal/watch/notify_test.go, internal/watch/ospath.go
Please review the following commits I made in branch nicks/ch1153/nested:
6e1dac10a22c699124aac826689b7492df4ea3bc (2018-12-19 19:07:52 -0500)
watch: fix a bug when a file and its ancestor both have direct watches
=> watch: fix a bug when a file and its ancestor both have direct watches

internal/docker/client.go, internal/docker/client_test.go
Please review the following commits I made in branch nicks/dockernegotiation:
4256d7c498569d5adc24bfbc9f6b68d5e2931b23 (2018-12-20 15:06:08 -0500)
docker: reject older docker versions if we haven't tested them
=> docker: reject older docker versions if we haven't tested them

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/parse.go, internal/engine/portforwardcontroller.go, internal/engine/portforwardcontroller_test.go, internal/engine/testdata_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/model/deploy_info.go, internal/model/manifest.go, internal/model/manifest_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/tiltfile2/tiltfile_state.go, internal/tiltfile2/tiltfile_test.go
Please review the following commits I made in branch maiamcc/move-k8s-info:
c59c7a9cec4357bdb285159394838b4a36bcb87d (2018-12-20 16:23:22 -0500)
all k8s properties off manifest
7182e25ac562135b21a03efd6fff6057abf3f206 (2018-12-20 16:02:10 -0500)
yaml moved over
8e2e68dd0f94dbd3cbe3a3c8e7e597251c1c9b4f (2018-12-20 15:31:00 -0500)
prelim code reorg
=> model: move k8s-specific info to model.deployInfo [ch1136]

internal/ospath/ospath.go, internal/ospath/ospath_test.go
Please review the following commits I made in branch child-bug:
adaa2deafcf06c85b6e0719cc4e3a8581b91f0b2 (2018-12-20 19:21:06 -0500)
ospath: check ospath.Child for nonsensical args
=> ospath: check ospath.Child for nonsensical args

internal/model/deploy_info.go, internal/model/manifest.go, internal/model/manifest_test.go
Please review the following commits I made in branch nicks/comp2:
70b8d63b707e22a58193037f9fe8f5cc53a6de5c (2018-12-21 10:20:20 -0500)
model: use go-cmp for equality checking, which is slightly better for flexibility/correctness
most notably, it has an option for treating `nil` and the empty slice as equivalent
42fd268ed2edca557d5c0027ccf36aa1fc71bb0c (2018-12-21 10:15:31 -0500)
vendor: go-cmp
=> model: use go-cmp for equality checking, which is slightly better for flexibility/correctness

internal/watch/watcher_darwin.go, internal/watch/watcher_naive.go
Please review the following commits I made in branch nicks/inotify:
176e76e6f1da0fc97b1d663a7e2ce0312b3b9c2b (2018-12-21 17:51:15 -0500)
watch: remove inotify-specific bits of watcher_linux
the tests on windows don't pass yet, but at least it compiles
=> watch: remove inotify-specific bits of watcher_linux

internal/tiltfile2/tiltfile.go
=> tilt: remove redundant error message from starlark errors

internal/hud/server/origin.go, internal/hud/server/server.go, internal/hud/server/websocket.go, internal/store/store.go, internal/store/subscriber.go, internal/store/subscriber_test.go
Please review the following commits I made in branch nicks/websocket2:
3215dc5aea5936ec128be6ab17ca85eda4542c54 (2019-01-03 11:32:19 -0500)
server: Add a websocket endpoint that streams down the View object
=> server: Add a websocket endpoint that streams down the View object

web/src/App.js, web/src/AppController.js, web/src/ResourceList.js, web/src/index.js
Please review the following commits I made in branch nicks/ch1176/prototype:
1954a7f8224c4b350d47781f8c2ff37e8d995dd8 (2019-01-03 13:54:52 -0500)
web: live reload HUD updates
=> web: live reload HUD updates

internal/engine/actions.go, internal/engine/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go
Please review the following commits I made in branch nicks/ch1187/flash:
40e7f99238727ba8c89b0d89b524382212bb9c59 (2019-01-03 15:41:09 -0500)
engine: record more metadata on tiltfile execution
=> engine: record more metadata on tiltfile execution

internal/cli/up.go, internal/engine/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/engine_state_test.go
This allows us to specify a different Tiltfile to load with a command line flag.
=> engine: paramaterize Tiltfile

internal/build/tar.go, internal/build/tar_test.go, internal/testutils/tar.go
I couldn't think of a good way to test this since `chown` requires root. Open to any ideas!
=> build: clear UID and GID before adding to tar

.circleci/config.yml
Please review the following commits I made in branch nicks/brew:
23c3492ef29bd96f63837c5039f5f65abdf1ecef (2019-01-09 12:00:15 -0500)
circleci: update brew to go1.11 and explode brew cache
=> circleci: update brew to go1.11 and explode brew cache

internal/k8s/entity.go, internal/k8s/serialize.go, internal/k8s/serialize_test.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/ch1236/crd:
9dd876eb84ee94e52399a0b061c61d363035a269 (2019-01-08 17:27:42 -0500)
k8s: handle CRDs properly
=> k8s: handle CRDs properly

internal/rty/canvas.go, internal/rty/render.go
When tcell renders a cell with value `0`, it converts it to `\x20` (space) and saves that as its value, and remembers that it was already a space.
RTY is then going through and setting it back to `0` on every iteration, resulting in no difference in appearance, but a huge number of extra calls to change the screen, resulting in lots of extra CPU usage (#943) and breaking copy/paste.
tcell's `drawCell` was responsible for ~70% of Tilt's CPU usage. This brings it down to ~2%.
=> rty: don't set cells to 0

internal/dockercompose/event.go
Please review the following commits I made in branch maiamcc/dc-action-enum:
3a44420f5d96d862506408b56a6cfb138fe31ca8 (2019-01-09 14:01:04 -0500)
fix types while i'm here
2b5e07897242c019a6edc3c89ff4cbade3dfc706 (2019-01-09 13:53:55 -0500)
compose: change container actions to be enums, don't barf on unknown actions
=> better type support for Events from docker compose [ch1277]

internal/build/image_builder.go, internal/build/path_mapping.go
Hello tbd,
Please review the following commits I made in branch maiamcc/verbose-tar-info:
fdc795adc541049bc8b7ed9eb5bc43fe13504e56 (2019-01-10 12:15:00 -0500)
build: in verbose mode, print more info on what files we tar
=> build: in verbose mode, print more info on what files we tar

internal/engine/buildcontroller.go
Some processes that could be printing to the context.Context writer will
not nicely end their strings with a newline. Let's prepend our logs with
a newline so that they stand out and don't get lost.
=> engine: print newline before Tilt meta-logs

internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/synclet_build_and_deployer.go, internal/store/build_result.go
Hello @nicks,
Please review the following commits I made in branch nicks/entities:
e68c8977dd9aa39c278fb0ecd87d9cb074a302c5 (2019-01-10 18:58:35 -0500)
store: remove obsolete properties from BuildResult. this k8s info now comes from EngineState
=> store: remove obsolete properties from BuildResult. this k8s info now comes from EngineState

internal/build/cache_builder.go, internal/build/container_test.go, internal/build/container_updater.go, internal/build/container_updater_test.go, internal/build/docker_client_benchmark_test.go, internal/build/image_builder.go, internal/build/image_reaper.go, internal/build/test_utils.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/docker/client.go, internal/docker/fake_client.go, internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/upper_test.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/synclet/synclet.go, internal/synclet/wire.go, internal/synclet/wire_gen.go
renamed b/c lint errors in my IDE were bugging me, but there's no
super good reason for this PR, so if it's too much, np.
=> docker: s/DockerClient/Client b/c name redundant with package name

internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/local_container_build_and_deployer.go, internal/engine/synclet_build_and_deployer.go, internal/engine/upper_test.go, internal/engine/watchmanager.go, internal/model/deploy_info.go, internal/model/docker_info.go, internal/model/manifest.go, internal/model/manifest_test.go, internal/tiltfile/docker.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ibd:
1fa859f352eaaaef10dfdaeff5a2ce13e7e536c0 (2019-01-11 11:53:50 -0500)
engine: make image builders act on ImageTargets instead of on Manifests
=> engine: make image builders act on ImageTargets instead of on Manifests

internal/build/boil_steps.go, internal/build/boil_steps_test.go, internal/build/container_test.go, internal/build/container_updater.go, internal/build/container_updater_test.go, internal/build/image_builder.go, internal/build/path_mapping.go, internal/build/path_mapping_test.go, internal/build/tar.go, internal/build/tar_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/pathmapping:
667afc1dbcfa475bf8cdbc1c085ef6342ea9ad21 (2019-01-11 16:48:32 -0500)
build: make pathMapping public. it doesn't make sense to have public methods that take a non-public type
=> build: make pathMapping public. it doesn't make sense to have public methods that take a non-public type

internal/cli/down.go
Please review the following commits I made in branch maiamcc/down-file-flag:
2a700bf956bef4f238f4ab88c98765a266e8819a (2019-01-11 14:51:02 -0500)
cli: down takes --file flag
=> cli: down takes --file flag [ch1215]

internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch maiamcc/handle-unknown-evts:
060d6bb056955a45781e543972664a13a136c682 (2019-01-14 12:24:42 -0500)
dont set empty string as dockercompose status [ch1321]
=> dont set empty string as dockercompose status [ch1321]

internal/dockercompose/client.go, internal/dockercompose/fake_client.go, internal/engine/actions.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_log_manager.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/model/docker_info.go
Please review the following commits I made in branch nicks/targets3:
00025b7ed3c2a57448d8305d7974ab1ed7ba4062 (2019-01-14 17:24:08 -0500)
engine: remove manifest from buildAndDeployCall, in preparation for removing manifest from BuildAndDeployer
=> engine: remove manifest from buildAndDeployCall, in preparation for removing manifest from BuildAndDeployer

internal/engine/upper.go
We weren't clearing the old log when we did a new deploy, which led
to fun stuff like this:
=> engine: clear docker compose 'current log' when we deploy

internal/model/docker_info.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/targets5:
e46ec8452633e9d42f0afd9dce9a58c8e74d2bf9 (2019-01-15 13:06:24 -0500)
tiltfile: more graceful handling when the Dockerfile is empty. this was mostly causing weird behavior in tests
=> tiltfile: more graceful handling when the Dockerfile is empty. this was mostly causing weird behavior in tests

internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/watchmanager.go, internal/ignore/path_matcher.go, internal/model/target.go, internal/store/engine_state.go
41984a1b074181c63f9a552f7ed3d5d466b644c5 (2019-01-15 20:20:14 -0500)
engine: change WatchManager to watch targets instead of manifests
in preparation for multiple image builds per pod, where each image
may watch different things
=> engine: change WatchManager to watch targets instead of manifests

internal/demo/script.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/renderer_test.go, internal/hud/view/view.go, internal/model/build_status.go, internal/model/target.go, internal/store/build_result.go, internal/store/engine_state.go, internal/store/engine_state_test.go
Please review the following commits I made in branch nicks/pending:
fe4b3290ebb93ef151418793b77d16b3efe93804 (2019-01-16 10:40:17 -0500)
store: track pending files per-image instead of per-manifest
in preparation for multiple images per manifest
=> store: track pending files per-image instead of per-manifest

internal/watch/notify_test.go, internal/watch/watcher_naive.go
to find appropriate parent to watch and wait for the specified path to exist.
I added a constraint that says not to watch root but I'm not sure if that's necessary, or if it's Windows compatible. Thoughts?
=> watch: add watch function that traverses up directory structure recursively

internal/dockercompose/fake_client.go, internal/engine/build_and_deployer_test.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/flakey:
becc6dde8f702853d2de7f7f5c3dfed3e1a3aac8 (2019-01-16 13:21:41 -0500)
dockercompose: use a channel to more accurately simulate streaming output
=> dockercompose: use a channel to more accurately simulate streaming output

internal/k8s/testyaml/testyaml.go, internal/model/manifest.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch1202/sidecars:
204293830dfe051d59aa1fc5074fa36e3343064f (2019-01-16 16:02:25 -0500)
tiltfile: support multiple images per manifest
=> tiltfile: support multiple images per manifest

internal/hud/hud.go, internal/hud/renderer.go
Please review the following commits I made in branch nicks/ch1254/xterm:
85e85497ad4af5f37c2f717e8981a33aa6af41d9 (2019-01-17 15:46:04 -0500)
hud: improve error message on ErrTermNotFound
=> hud: improve error message on ErrTermNotFound

Tiltfile, internal/build/container_test.go, internal/build/container_updater.go, internal/build/container_updater_test.go, internal/engine/local_container_build_and_deployer.go, internal/model/docker_info.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/hotreload2:
33ead1a4cfda773db52c966e8065779e3b0d76ec (2019-01-24 11:01:27 -0500)
tiltfile: add experimental hotreload support
=> tiltfile: add experimental hotreload support

internal/cli/down.go, internal/demo/script.go, internal/engine/actions.go, internal/engine/configs_controller.go, internal/engine/tiltfile_log_writer.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/buildstatus.go, internal/hud/renderer.go, internal/hud/renderer_test.go, internal/hud/resourceview.go, internal/hud/view/view.go, internal/store/engine_state.go, internal/store/engine_state_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Regular (good) view:
There's a Tiltfile and an error:
There's no Tiltfile:
=> engine: record and display Tiltfile logs separately

internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch maiamcc/tiltfile-err-messaging:
4c791725e180bd4e9140a0dc7627aacd89d517b0 (2019-01-25 11:37:38 -0500)
tiltfile: better err messaging for k8s validation
=> tiltfile: better err messaging for k8s validation

internal/docker/image.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
=> tiltfile: store normalized image name on dc_resource for matching against imagesByName

internal/cli/wire_gen.go, internal/k8s/client.go, internal/k8s/env.go
running w/o k8s/kubectl is now a possible use-case that we shouldn't crash
for (e.g. someone is running tilt x DC and doesn't need k8s at all).
=> k8s: if can't get kubecontext (e.g. no kubectl), return EnvNone instead of throwing error [ch1443]

internal/tiltfile/build_index.go, internal/tiltfile/docker.go, internal/tiltfile/docker_compose.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch1447/match:
d16bbce5baf729648598e891d0c862cfdc2cd46a (2019-01-31 15:22:10 -0500)
tiltfile: reorganize how we match image targets to deploy targets
fixes https://github.com/windmilleng/tilt/issues/1059
=> tiltfile: reorganize how we match image targets to deploy targets

internal/dockercompose/fake_client.go, internal/tiltfile/docker_compose.go, internal/tiltfile/docker_compose_test.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/fix-assert-manifest:
676c1109e4e2d8322434c1dcb4f9bddd9a5fe895 (2019-02-01 15:51:06 -0500)
fix assertmanifest and test for docker compose service order
=> tiltfile: fix assertManifest and test for docker compose service order

Makefile
Hello @nicks,
Please review the following commits I made in branch nicks/parallelism:
6822c9a0aa4bce0cf19ef9cd083a1953d4e1c9c1 (2019-02-03 13:13:38 -0500)
Makefile: manually set Go parallelism
=> Makefile: manually set Go parallelism

internal/cli/wire.go, internal/cli/wire_gen.go, internal/k8s/client.go, internal/k8s/env.go, internal/k8s/exploding_client.go
Friend w/o kubectl was trying to run k8s and got error:
> Error: could not get config for context ({"" "" "" "" map[]}): invalid configuration: no configuration has been provided
This PR checks whether user has kubectl present at all before trying to get REST API/other k8s-relevant configs.
=> k8s: don't try to get k8s rest api etc if no k8s configured [ch1433]

internal/k8s/exploding_client.go
Hello tbd,
Please review the following commits I made in branch maiamcc/fix-master:
ca915b3b5595be87099a4ad9dff04b69698e9f81 (2019-02-05 11:41:24 -0500)
k8s: fix type err with exploding client
=> k8s: fix type err with exploding client

cmd/tilt/main.go
Please review the following commits I made in branch nicks/error:
5d8d1cba1e36732c7a6a0fcb7694ee56e3362eda (2019-02-05 18:29:43 -0500)
tilt: fix klog printing to stderr
=> tilt: fix klog printing to stderr

internal/tiltfile/docker.go, internal/tiltfile/tiltfile_test.go
This was generating errors like
```
Error: fast_build("add").add(): invalid type for src. Got string want gitRepo OR localPath
```
the `"add"` there is super weird
now we get:
```
Error: fast_build("docker.io/library/my_picnic_image").add(): invalid type for src. Got string, want gitRepo
OR localPath
```
=> fast_build: fix add error message

internal/build/tar.go, internal/build/tar_test.go, internal/testutils/tar.go, internal/testutils/tempdir/temp_dir_fixture.go
Please review the following commits I made in branch nicks/symlink:
ceff3c77f1e9fcdab49c9bcddab8adc7e96cd802 (2019-02-07 13:26:37 -0500)
tar: handle relative symlinks correctly
=> tar: handle relative symlinks correctly

Gopkg.lock, Gopkg.toml, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/synclet/wire.go, vendor/github.com/google/wire/.contributebot, vendor/github.com/google/wire/.travis.yml, vendor/github.com/google/wire/AUTHORS, vendor/github.com/google/wire/CODE_OF_CONDUCT.md, vendor/github.com/google/wire/CONTRIBUTING.md, vendor/github.com/google/wire/CONTRIBUTORS, vendor/github.com/google/wire/LICENSE, vendor/github.com/google/wire/README.md, vendor/github.com/google/wire/go.mod, vendor/github.com/google/wire/go.sum, vendor/github.com/google/wire/wire.go
notes:
1. wire has moved to a new repo (out of go-cloud), so this comes with a package name change.
2. This will silently break everyone's `make wire` until they switch to the new repo. The behavior with a `wire` from the old repo is that it just no-ops.
3. CI is already using the new repo (which means that its `wire check` was a no-op)
4. Maybe we wanna dockerize `make wire` so that we're not depending on what versions we have on our laptops? I'm leaning against that being a good use of time at the moment.
=> wire: upgrade version

internal/engine/upper_test.go, internal/store/engine_state.go
Please review the following commits I made in branch maiamcc/accurate-unexpected-container-tests:
2021261c0e219fe467d72e5432d1607e226d2b3c (2019-02-08 15:22:48 -0500)
engine: make unexpectedContainer/crashRebuild tests more accurate
=> engine: make unexpectedContainer/crashRebuild tests more accurate

Gopkg.lock, vendor/github.com/stretchr/testify/LICENSE, vendor/github.com/stretchr/testify/assert/assertions.go
This fixes a bug that causes a panic when showing the difference between variables with aliased types.
=> vendor: upgrade testify

Gopkg.lock, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/analytics_reporter.go, internal/engine/analytics_reporter_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
1. Report an "up.running" event every 4 hours while tilt is running (theoretically we have a compelling use case that involves just leaving Tilt running all the time, and we want to count these users appropriately).
2. Count builds, resources, resources w/ DC, resources w/ k8s, resources w/ fast build.
=> analytics: periodically report some tilt usage information

cmd/tilt/main.go, internal/cli/cli.go, internal/cli/klog.go, internal/cli/up.go
Please review the following commits I made in branch nicks/klog:
c3f3e4fd1d69975bee019b4e18c0fabd3038d6a0 (2019-02-11 11:36:58 -0500)
cli: add a hidden flag to turn on klog traces, which logs all k8s api calls
=> cli: add a hidden flag to turn on klog traces, which logs all k8s api calls

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/namespaces:
44e8b7306fa92e1a3534a6cc65bc7284901c7ae2 (2019-02-08 17:54:21 -0500)
k8s: more robust watches and error handling
fixes https://github.com/windmilleng/tilt/issues/1139
=> k8s: more robust watches and error handling

internal/engine/actions.go, internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/global_yaml_buildcontroller.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/local_container_build_and_deployer.go, internal/engine/pod_watch.go, internal/engine/pod_watch_test.go, internal/engine/service_watch.go, internal/engine/synclet_build_and_deployer.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/labels.go, internal/model/build_status.go, internal/model/deploy_info.go, internal/store/build_result.go, internal/store/engine_state.go, internal/store/testing_store.go
This lets us simplify the logic to match pods to image, and will let us more easily match pods that were deployed by tilt but don't have tilt-built images.
=> engine: inject deployID on k8s deploy, use that to find pods [ch1544]

internal/cli/wire.go, internal/cli/wire_gen.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/env.go, internal/k8s/kubectl_runner.go
Please review the following commits I made in branch nicks/kubecontext:
7d4b489451493b89e2a667adafd97ac40d4850ff (2019-02-11 16:27:14 -0500)
k8s: pull context from the k8s api instead of from the cli, and capture namespace in kubectlRunner
=> k8s: pull context from the k8s api instead of from the cli, and capture namespace in kubectlRunner

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/watchmanager.go, internal/hud/renderer.go, internal/model/deploy_info.go, internal/tiltfile/tiltfile_test.go
Hello @nicks, @dbentley,
Please review the following commits I made in branch maiamcc/explicit-resource-without-build:
9f0a81cb93dd44fe0abd9f1afdddc3f78c6acd36 (2019-02-12 18:28:27 -0500)
make sure logs get into log modal for resource even if redeploy is really fast
9336cf7f783305620846159132d417cf243fad44 (2019-02-12 17:44:58 -0500)
test container matching
43a94866c2121f7eab823d326ad896671a074d49 (2019-02-12 16:49:51 -0500)
port forwarding
d54847b886d33d67ae12b35ae357e1d43e87a653 (2019-02-12 14:57:04 -0500)
ImageBuildAndDeployer can handle calls with only deploy targets, no build targets (i.e. only k8s yaml, no image builds)
* Incomplete code …
=> engine: allow explicit k8s_resource with just yaml, no image, to appear in hud, get logs, etc. [ch1457]

internal/dockerfile/ast.go, internal/dockerfile/ast_test.go
Please review the following commits I made in branch nicks/dockerfileprinter2:
cb4f86ec57d6ef7f22cc1454fa7976e495e50044 (2019-02-14 17:25:44 -0500)
dockerfile: add a printer, to make it easy to make changes to the AST and then re-print it
8284661cce48abf8a97ae52076955f91c021546a (2019-02-14 17:25:44 -0500)
dockerfile: refactor into AST type
=> dockerfile: add a printer, to make it easy to make changes to the AST and then re-print it

internal/dockerfile/inject.go, internal/dockerfile/inject_test.go
Please review the following commits I made in branch nicks/inject:
3af357ede2e318c494cb29b22e0e9130f9b493dd (2019-02-14 18:21:03 -0500)
dockerfile: add a helper function for injecting an image digest into a dockerfile
=> dockerfile: add a helper function for injecting an image digest into a dockerfile

internal/dockerfile/ast.go, internal/dockerfile/ast_test.go
Please review the following commits I made in branch nicks/astprint:
a40052f2158ac4ccd4c094c9516b8f889bbd7c8e (2019-02-18 13:24:08 -0500)
dockerfile: fix a bug in the ast printer when the command has flags
=> dockerfile: fix a bug in the ast printer when the command has flags

internal/dockerfile/ast.go, internal/dockerfile/dockerfile.go, internal/dockerfile/dockerfile_test.go, internal/dockerfile/inject_test.go
Please review the following commits I made in branch nicks/copyfrom:
d7cd67abc3d66439988afb0c5da58c5a9457f080 (2019-02-18 15:23:45 -0500)
dockerfile: inject into COPY --from
324ce6fd5201b030c358ee6d576df48eb6456ac5 (2019-02-18 13:37:00 -0500)
vendor: buildkit instruction parser (#1174)
734db2dd537e25d7ce9ad37c72bb51b48d56acf3 (2019-02-18 13:28:32 -0500)
dockerfile: fix a bug in the ast printer when the command has flags
=> dockerfile: inject into COPY --from

internal/hud/renderer.go
Please review the following commits I made in branch maiamcc/more-k8s-statuses:
7d55bae04e3e4d148d24c67835902c2dab15ed04 (2019-02-19 15:15:51 -0500)
hud: colors for ErrImagePull and ImagePullBackOff
=> hud: colors for ErrImagePull and ImagePullBackOff

internal/tiltfile/files.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/return-yaml:
1e79b0d02d81ee7da65eeef36c4a18e81cc9dbf7 (2019-02-20 18:09:38 -0500)
tiltfile: make use of Yaml type instead of blob
=> tiltfile: make use of Yaml type instead of blob

internal/container/container.go, internal/dockerfile/inject_test.go, internal/k8s/pod.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/normalize:
f5fd5172aebf279d6675375172863bb925c2aae7 (2019-02-21 12:43:07 -0500)
container: normalize all image names
=> container: normalize all image names

internal/k8s/entity.go, internal/k8s/entity_benchmark_test.go, internal/k8s/label.go, internal/k8s/label_test.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/split-out-yaml:
55b701d6041bc2dda17c6e10349aecf5c6a3dc53 (2019-02-20 16:38:02 -0500)
tiltfile func to filter yaml by label
2c69e3cbe075ea0c76669842604ef4a2522d3702 (2019-02-20 16:28:03 -0500)
metadata label match funcs
a0f31ff53c0063a1c51f0ed9a23f4b6001c44616 (2019-02-20 14:51:58 -0500)
benchmark parse/unparse yaml
=> tiltfile func to filter yaml by label(s) [ch1626]

internal/dockerfile/ast.go, internal/dockerfile/inject_test.go
Please review the following commits I made in branch nicks/twice:
6628e1baa695f36afea0bb6bacdc9df184cb292b (2019-02-21 15:36:51 -0500)
dockerfile: fix a minor bug in how images were injected into the AST
quoting happens at AST-parsing time, not Instruction-parsing time
There's a separate bug here of "why are we trying to inject this image twice" that i also need to look into
=> dockerfile: fix a minor bug in how images were injected into the AST

internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch end-tiltfile-exec-log:
4f5cc2278fa13bf0fb09f821d867c9eb56725242 (2019-02-21 15:20:20 -0500)
tiltfile: logline for finished tiltfile exec
=> tiltfile: logline for finished tiltfile exec

internal/engine/analytics_reporter.go, internal/engine/analytics_reporter_test.go
Please review the following commits I made in branch maiamcc/unbuilt-resources-stats:
73b3be842c24558de140867f39b3afdcbf9e2add (2019-02-21 15:55:19 -0500)
analytics: count number of unbuilt resources (k8s resources w/o image targets)
=> analytics: count number of unbuilt resources [ch1651]

internal/tiltfile/files.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/no-yaml-constructor:
b670d072c7348ca3a5b36543e04d964d947fbd9b (2019-02-22 14:19:59 -0500)
tiltfile: roll back Yaml type, make blob constructor instead
=> tiltfile: roll back Yaml type, make blob constructor instead

internal/cli/down.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/demo/script.go, internal/engine/analytics_reporter_test.go, internal/engine/build_and_deployer_test.go, internal/engine/configs_controller.go, internal/engine/configs_controller_test.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/portforwardcontroller_test.go, internal/engine/store_testutil.go, internal/engine/synclet_manager_test.go, internal/engine/upper_test.go, internal/engine/watchmanager_test.go, internal/store/store.go, internal/store/subscriber_test.go, internal/testutils/fake_clock.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
also:
1. Make `FakeStore` a little more useful for testing subscribers (exposing dispatched actions)
2. Add a `FakeClock` class for the obvious
3. Add a `FakeTiltfileLoader` to avoid having to generate actual tilt configs in `Tiltfile.Load`'s callers (I'm not super excited about all the result `NewTiltfileLoader`s - open to suggestions)
=> engine: add ConfigsController test

internal/model/deploy_info.go, internal/model/docker_info.go, internal/model/target.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/doubledeps:
0627bd991f5a176e71e198ce7312dc717023240a (2019-02-21 17:40:52 -0500)
tiltfile: when building manifests, de-dupe dependencies
=> tiltfile: when building manifests, de-dupe dependencies

internal/k8s/entity.go, internal/k8s/entity_test.go, internal/k8s/testyaml/testyaml.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/filter-yaml-name-kind:
0867c1ef7fa83025f3eb41fb6aeb551de9d3532b (2019-02-22 17:41:58 -0500)
implement, tests
c08611729845979378bafaabd70a1bf6dae6f8d9 (2019-02-22 15:49:54 -0500)
stub out func
=> tiltfile: filter_yaml also supports name, namespace, kind [ch1626]

internal/tiltfile/files.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
before:
```
Error: error converting YAML to JSON: yaml: line 3:
could not find expected ':'
```
after:
```
Error: Error reading yaml from cmd: 'm4 -Dvarowner="matt"
-Dvarimgname="gcr.io/windmill-public-containers/servantes/doggos"
"deploy/doggos.yaml"': error converting YAML to JSON: yaml: line 3:
could not find expected ':'
```
=> tiltfile: include sources in k8s yaml parse errors

go.sum, internal/engine/pod_watch.go, internal/engine/service_watch.go
This may fix a problem Frank saw with Tilt hanging forever upon start when his Kube cluster wasn't ready
=> engine: add timeout for service watch

internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/add-takes-string:
708fb6b6f3395dadc5534a23d63e82179ca14f75 (2019-02-28 14:43:46 -0500)
tiltfile: fast_build.add may take a string (in addition to localpath, gitrepo)
=> tiltfile: fast_build.add may take a string (in addition to localpath, gitrepo) [ch1716]

internal/engine/global_yaml_buildcontroller.go, internal/engine/global_yaml_buildcontroller_test.go, internal/k8s/testyaml/testyaml.go
Problem:
If the yaml contains both namespaces and objects in those namespaces, trying to apply the objects in the namespaces before the namespaces themselves will result in failure (because the namespaces don't exist)
Solution:
sort namespaces to the front of global yaml
This doesn't fully solve the problem, since global yaml gets applied in parallel with resourced entities, and those resourced entities could be in a namespace specified in global yaml, but that's a problem to tackle separately.
=> globalyaml: apply namespaces first

internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/dont-need-git-repo:
257c6df2c605e0c03b65a736a5f3f04715b6fa78 (2019-02-28 18:13:16 -0500)
default case for tests is to pass a string to fb.add
198d6b2698b19b03cd56fb7021e3d5f1cc702b59 (2019-02-28 18:05:28 -0500)
more gitignore tests
=> tiltfile: fix tests to reflect preference for fb.add(src: str...) [ch1716]

internal/tiltfile/docker.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/correct-dockerignore-behavior:
1e63990a5e36cec9ae624c5b4bd384fe5a3acd89 (2019-02-28 16:47:48 -0500)
tiltfile: don't pull dockerignores for repo root
from Docker docs:
> Before the docker CLI sends the context to the docker daemon, it looks for a file named .dockerignore **in the root directory of the context**.
we should not check the repo root for .dockerignores, it's different from the behavior of docker
=> tiltfile: don't pull dockerignores for repo root

internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/store/build_result.go, internal/testutils/tempdir/temp_dir_fixture.go
Please review the following commits I made in branch nicks/fastbuild:
e1961ac645e8381c1359fc81e7e093f7918ea4ed (2019-02-28 19:34:19 -0800)
engine: skip images that have already been built and don't have updates
=> engine: skip images that have already been built and don't have updates

internal/engine/upper.go
I remember it was originally an intitional design choice to not have the
Tiltfile log to the global log pane, but it confuses me every damn time,
and [some users too](https://kubernetes.slack.com/archives/CESBL84MV/p1551395345022900).
I propose that until Tiltfile output gets unweildy, we display it in the global
log with everything else -- how do y'all feel about that?
=> engine: tiltfile logs also written to global logs

internal/k8s/entity.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/k8s/testyaml/testyaml.go, internal/tiltfile/docker.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Problems:
1. In order to use CRDs, users had to manually join images with k8s entities by passing them all together to `k8s_resource`, which felt kind of clunky.
2. `k8s_resource` only takes one image, which meant this didn't work with CRDs with multiple images.
Solution:
Add `k8s_extra_image_location` method, which says where to find the image definitions for a given k8s object type, so now CRDs can have multiple images and don't need a call to `k8s_resource`, but can just use the normal tiltfile joining logic.
=> tiltfile: add k8s_kind

internal/build/buildkit_printer.go, internal/build/image_builder.go, internal/build/label.go, internal/build/options.go, internal/cli/cli.go, internal/cli/up.go, internal/docker/client.go, internal/dockercompose/fake_client.go, internal/engine/build_errors.go, internal/engine/docker_compose_log_manager.go, internal/engine/image_and_cache_builder.go, internal/engine/podlogmanager.go, internal/engine/synclet_manager.go, internal/hud/hud.go, internal/hud/renderer.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/container.go, internal/k8s/env.go, internal/k8s/pod.go, internal/minikube/docker.go, internal/ospath/ospath.go, internal/store/engine_state.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go
Changing some things that golangci-lint complained about.
I think in general the only things that are really interesting are ineffectual assignment [here](https://github.com/windmilleng/tilt/compare/matt/fix_lint?expand=1#diff-187cac6214111b4c1831b65825c135f8R291) and `t.Fatal` from a go routine [here](https://github.com/windmilleng/tilt/compare/matt/fix_lint?expand=1#diff-d505e8f7d9a2cc3ff33cb6041e787e9dR84). I mostly just changing the others to make it cheaper to read the output of golangci-lint in the future.
=> tilt: fix misc lint errors

internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go
Please review the following commits I made in branch maiamcc/clean-up-pod-log-watch:
c2fc560669dd3211c118f87897947bc926099d90 (2019-03-05 17:52:39 -0500)
engine: rm dead code in podLogManager
=> engine: rm dead code in podLogManager

internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go, internal/engine/upper.go, internal/k8s/fake_client.go, internal/store/engine_state.go
This is the quickest way to support multi-container logs.
It doesn't actually improve our model in any useful way -- that's
for a separate PR.
=> engine: hack to allow us to watch all containers of a pod for logs [ch1737]

internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go
to avoid, e.g.:
```
2019/03/04 15:55:04 Running `"m4 -Dvarowner=\"matt\" \"deploy/fission.yaml\""`
2019/03/04 15:55:04 Successfully executed Tiltfile
resource "go-env": could not find k8s entities matching image(s)
"gcr.io/windmill-public-containers/servantes/go-env"; perhaps there's
a typo?
```
=> tiltfile: don't print 'Successfully executed' prematurely

internal/container/selector.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_and_cache_builder.go, internal/engine/imagecontroller.go, internal/engine/synclet_manager.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/k8s/container.go, internal/k8s/container_test.go, internal/k8s/entity.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/model/custom_build_test.go, internal/model/docker_info.go, internal/model/manifest_test.go, internal/store/build_result.go, internal/tiltfile/build_index.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/ch1654/selector:
56c33aa0ad99d8afdcdb432ee942df95c94fac8b (2019-03-07 11:57:18 -0500)
container: Add a concept of image selectors in place of image refs.
This is in service of https://github.com/windmilleng/tilt/issues/1259, but
currenlty changes no functionality
=> container: Add a concept of image selectors in place of image refs.

internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go
Please review the following commits I made in branch maiamcc/container-prefixes-ch1738:
f733c3ef544ec22f122d77397aa766bffabd150c (2019-03-07 11:37:21 -0500)
clean up tests with better assert funcs
410d4abd99f66ff06efebd399f8c0377124050e1 (2019-03-07 11:36:05 -0500)
engine: prefix logs with container name where appropriate
=> engine: prefix logs with container name where appropriate

internal/engine/docker_compose_event_watcher.go, internal/engine/upper_test.go
Please review the following commits I made in branch maiamcc/fix-dc-event-watch:
e902d4be932125238e28e5bce01559cdebb03510 (2019-03-06 17:12:22 -0500)
engine: keep trying to watch for Docker Compose events if we didn't actually start watching the first time
=> engine: keep trying to watch for Docker Compose events if we didn't actually start watching the first time

internal/engine/build_and_deployer_test.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/upper.go, internal/store/build_result.go, internal/store/build_result_test.go
Please review the following commits I made in branch nicks/asoneresult:
db5a72fc1d2149f9b6785662531194f311708814 (2019-03-08 11:17:50 -0500)
store: fix a bug in the results api when there are multiple images
=>  store: fix a bug in the results api when there are multiple images

internal/engine/build_and_deployer.go
This is very useful when debugging issues and helps a user understand
what Tilt is doing.
=> engine: always show unexpected fallback message

integration/dc_fixture_test.go, integration/fixture_test.go, integration/k8s_fixture_test.go, integration/onedc_test.go, integration/oneup_custom_test.go, integration/oneup_test.go, integration/onewatch_test.go
Please review the following commits I made in branch maiamcc/dc-integ-filewatch:
4231e11b1db277e4021fbe061063df65cbfcdcd9 (2019-03-07 14:15:15 -0500)
integration: add back filewatching to dc integration test
=> integration: add back filewatching to dc integration test

internal/dockerfile/ast.go, internal/dockerfile/inject.go, internal/dockerfile/inject_test.go, internal/engine/build_and_deployer_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/extractors.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/upper_test.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/model/deploy_info.go, internal/model/docker_info.go, internal/store/build_result.go
Please review the following commits I made in branch nicks/selectors:
90ddcd1778e4cde132d9f3c2182134da039f6275 (2019-03-08 12:42:15 -0500)
engine: Separate the image selector from the image being injected
This will help with a variety of things we want to do, including https://github.com/windmilleng/tilt/issues/1259 (multiple dockerfiles per image name) and subsituting a private repo at runtime.
=> engine: Separate the image selector from the image being injected

.circleci/config.yml
(built via `make ci-container` in master)
=> ci: bump ci image to go 1.12

.circleci/config.yml
at least I'm fixing new errors each time?
=> ci integration: bump image to go 1.12

.circleci/config.yml
Problem:
the macos CI build keeps failing with errors like this:
```
#!/bin/bash -eo pipefail
go get -u gotest.tools/gotestsum
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
ignoring go.mod;
see 'go help modules'
Cloning into '/Users/distiller/go/src/golang.org/x/sys'...
fatal: remote error: Internal Server Error
package golang.org/x/sys/unix: exit status 128
Exited with code 1
```
Solution:
download gotestsum instead of `go get`ting it
(also this step was taking 30-40 seconds, so we might as well not do that?)
=> ci: don't compile gotestsum

internal/k8s/entity.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/k8s/json_path.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Problem:
Using image names in env vars requires monkeying with `k8s_resource`, which doesn't work when there are multiple images for an entity. (I think, anyway? Apparently I didn't write any automated tests for env var support, so I'm not exactly sure what setup I used when manually testing this).
Solution:
Rename `k8s_kind` to `k8s_image_json_paths` and add `name` and `namespace` parameters.
This feature is still incomplete since these paths are not used at injection time. Image ID injection currently looks for image names in all fields (for CRDs) or in all env vars and container specs (for non-CRDs). It's currently sufficiently done to unblock env var usage, and we'll just keep it undocumented for now.
=> tiltfile: support image json paths by entity name

internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/warnings:
de3158a5c6dedda3100bc03c56db60454bf7b0eb (2019-03-12 14:00:26 -0400)
tiltfile: tests should error by default if there are warnings
we expect most test cases to have no warnings; the test writer
shouldn't have to remember to assert this
=> tiltfile: tests should error by default if there are warnings

internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/watchmanager_test.go, internal/store/engine_state.go
Now when you change a a config file that causes a manifest's definition to change, and thus be re-deployed, that file will show up as an edited file in both the Tiltfile _and_ the manifest that changed.
Here's an example: I changed `deploy/snack.yaml` in Servantes and both `snack` and `(Tiltfile)` are marked as edited, but `hypothesizer` is not.
=> engine: show all files that triggered a Tiltfile build

internal/build/buildkit_printer.go, internal/build/buildkit_printer_test.go, internal/build/testdata/TestBuildkitPrinter/docker-18.09-output_master, internal/build/testdata/TestBuildkitPrinter/echo-hi-success_master
This is two changes:
1. add the `isStep` check to streaming logs (i.e., support streaming logs for the new `[1/4]` buildkit vertex names, not just the old `sh -c` vertex names), so that log streaming works at all with modern buildkit
2. change the log streaming level from verbose to info, so that it shows by default (aside from any opinion changes we might have had after real-world usage, maybe also the verbose decision was made prior to the HUD and separated logs?)
I haven't seen download progress, which is unfortunate, but I've tested this with a shell script that was just a for loop with a sleep and echo, so I think it's worth checking in as-is, and worrying about download progress separately.
=> docker: show build progress

internal/dockercompose/client.go
Please review the following commits I made in branch nicks/newline:
de46c77129d27a472e73a4e5aa3918b91e76d04c (2019-03-12 22:33:13 -0400)
docker-compose: strip newline off docker-compose output
this was causing all sorts of weird behavior, depending on whether the api trimmed spaces implicitly
=> docker-compose: strip newline off docker-compose output

internal/tiltfile/tiltfile_test.go
Somehow we started cargo culting not putting these in 😅
=> tiltfile: add teardowns to tiltfile tests

internal/engine/buildcontroller.go, internal/engine/configs_controller.go, internal/engine/configs_controller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/ch1826/manifest:
b12b1646ad721a79ec3b126eea4df5545511995a (2019-03-12 16:10:45 -0400)
engine: don't kick off a build while tiltfile execution is pending
=> engine: don't kick off a build while tiltfile execution is pending

internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/static-build-helper:
bb2a3ca255fde5e0f8231ded904e736b45768b48 (2019-03-13 16:11:34 -0400)
tiltfile: make staticbuild helper (i.e. make image target assertions specific to the type of build)
=> tiltfile: make staticbuild helper (i.e. make image target assertions specific to the type of build)

internal/model/docker_info.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Hello @dmiller, @nicks,
Please review the following commits I made in branch maiamcc/fastbuild-on-dockerbuild:
e76ec665b73f12f48547bac73806bd8fb303c89f (2019-03-13 17:28:12 -0400)
implement it
a6e757555a7cf0ee1f325398b1855dc9ee784d1e (2019-03-13 17:27:44 -0400)
red test
2128fd242d6770f9ba9f3f284f0e3dbe180e907d (2019-03-13 17:15:39 -0400)
add nested fastbuild, test helpers
=> optionally nest fastBuild on staticBuild; can specify fastBuild properties in tiltfile on top of  a docker_build [ch1834]"

internal/k8s/entity.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
a couple of use cases:
1. When templating entity names, the tiltfile will have to duplicate the templating logic in order to pass the entity name to k8s_image_json path. e.g., in the simple Servantes case, the tiltfile would need `username() + "-vigoda"`. This allows the user to pass `name=".*-vigoda"`.
2. When specifying apiVersion, the user might care about the group but not the version. This allows the user to specify, e.g., `fission.io/.*`.
=> tiltfile: support regex in k8s_kind and k8s_image_json_path

internal/hud/hud.go
This isn't the cleanest solution, but it's very cheap and contained, and I haven't thought of a cleaner solution that doesn't involve big changes.
=> hud: don't scroll to the bottom after the tiltfile loads

internal/engine/build_and_deployer_test.go, internal/engine/testdata_test.go, internal/model/docker_info.go
Please review the following commits I made in branch maiamcc/nested-fb-live-update:
4c668b17fcebd2cb035190df4fcd0fbea5daa0d1 (2019-03-14 12:31:16 -0400)
imageTarget.FastBuildInfo consistent with MaybeFastBuild
67bf8e72b78a198514cabb7c588b9f2421e390de (2019-03-14 12:12:12 -0400)
extract nested fastbuild as a live update target
=> engine: use staticBuild.FastBuild for LiveUpdate where possible [ch1833]

internal/cli/down.go, internal/demo/script.go, internal/engine/configs_controller.go, internal/engine/upper_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go
I was about to add another return value to `Load` and it was getting a bit unwieldy
=> tiltfile: wrap load return values in struct

internal/engine/actions.go, internal/engine/configs_controller.go, internal/engine/upper.go, internal/engine/watchmanager.go, internal/engine/watchmanager_test.go, internal/sliceutils/sliceutils.go, internal/sliceutils/sliceutils_test.go, internal/store/engine_state.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
docs: https://github.com/windmilleng/tilt.build/pull/77
1. I'm not super thrilled about doing the loading itself in the Tiltfile loader, but that's where we're already loading configs, and that's what the Configs Controller deals with? Maybe the answer is just to wrap the tiltfile loader with a configs loader that does tiltfile + tiltignore?
2. One unfortunate behavior right now is that changing .tiltignore causes reexecution of the Tiltfile, but that doesn't seem like a blocker.
=> tilt: add .tiltignore support

integration/fixture_test.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/controller.go, internal/model/web.go, internal/store/actions.go
Please review the following commits I made in branch nicks/ch1836/server:
c2a42361957ce5cb183f732ff6dcd14737efe908 (2019-03-15 14:32:58 -0400)
hud: start up the hud server by default on port 10350
=> hud: start up the hud server by default on port 10350

internal/container/selector.go, internal/engine/buildcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/build_result.go
Please review the following commits I made in branch maiamcc/match-tagged-images:
c1bdbb632fa44ad53d2cbcea549d50ab34afff10 (2019-03-19 17:21:16 -0400)
test
e367b7e29b3b6c6ec8133a031c4aa1d18bbb33cd (2019-03-19 17:20:29 -0400)
engine: (for now) don't require image TAGS to match when checking container image for match with image target
=> engine: (for now) don't require image TAGS to match when checking container image for match with image target

internal/cli/doctor.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/env.go, internal/k8s/env_test.go
This is a more reliable way to detect cluster types that are likely to have different names, like KIND.
=> k8s: get KubeContext from config instead of context name

internal/engine/configs_controller_test.go, internal/engine/upper_test.go
chdir keeps breaking tests in annoying ways (one test fails to clean up its chdir, and then some other test, which passes when run by itself, fails when run as part of the suite, because it starts off with an invalid chdir)
1. remove the chdirs from upper_test, which were pretty much just unnecessary
2. removing it from ConfigsController is non-trivial since it calls `state.RelativeTiltfilePath`, which depends on WD, but at least catching errors on restoring the WD will make these issues easier to diagnose when we run into them
=> tests: clean up some uses of chdir

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/model/docker_info.go, internal/tiltfile/docker.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
@rohansingh needs this for his bazel + KIND setup. For the moment bazel is much better at doing the layer negotiation and pushing only what is necessary. `kind load` is less efficient. @rohansingh has a workaround where he tees the image to both docker and KIND, allowing custom_build to verify that the image was created correctly and allowing KIND to get the image in a fast way. What he needs is a way to disable the image push in this case. 
I decided to add this as a flag to `custom_build` because its a pretty special case, only is used from `custom_builds` right now and fits in with `custom_build`'s evolving, experimental API.
=> engine: add flag to disable push on custom build

.gitignore, integration/oneup/Tiltfile, integration/oneup/oneup.yaml, internal/container/default_registry.go, internal/container/default_registry_test.go, internal/container/selector.go, internal/engine/image_build_and_deployer_test.go, internal/k8s/image.go
Also changed the behavior to not spew docker.io/library into images.
=> integration/oneup: use default_registry

integration/oneup_custom/Tiltfile, internal/build/custom_builder.go, internal/model/docker_info.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/tag-env-var-to-ref:
d7dcfcaed7d19a12f9919b00338402b376683c09 (2019-03-22 13:25:19 -0400)
build: customBuild now relies on $EXPECTED_REF env var (rather than $TAG)
=> build: customBuild now relies on $EXPECTED_REF env var (rather than $TAG)

internal/tiltfile/files.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Makes more sense than `read_file` when you're implementing custom Tiltfile
functionality that wants to add dependencies, while avoiding the perf
hit of actually reading the file.
=> tiltfile: add watch_file function

internal/ospath/display.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/display:
66745d017433b559053edb60c36bfd065e2e8ea1 (2019-03-25 16:19:47 -0400)
ospath: move the function for file display names into the ospath package
=> ospath: move the function for file display names into the ospath package

internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
This way if a new file is added to to the directory that you listed it
will trigger Tiltfile execution.
=> tiltfile: watch entire directory passed to listdir

internal/k8s/env.go, internal/k8s/env_test.go
@landism on docker v18.09.2:
```
$ kc config get-clusters
NAME
gke_blorg-dev_us-central1-b_blorg
gke_some-project-162817_us-central1-b_windmill
gke_windmill-prod_us-central1-b_windmill
docker-for-desktop-cluster <-- !
```
me on docker v18.09.3:
```
$ kc config get-clusters
NAME
gke_blorg-dev_us-central1-b_blorg
gke_some-project-162817_us-central1-b_windmill
minikube
docker-desktop <-- different from string in code
```
=> k8s: correctly detect k8s env for docker edge

internal/dockerfile/dockerfile.go, internal/dockerfile/dockerfile_test.go, internal/engine/watchmanager_test.go, internal/model/deploy_info.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go
Please review the following commits I made in branch nicks/ch2008/watches:
1205f276e8649dffbe2fb62f92ddf8c916c42a17 (2019-03-26 20:19:48 -0400)
docker-compose: use the full build context for now instead of trying to be clever
fixes a bug where we were not handling multi-stage builds correctly
=> docker-compose: use the full build context for now instead of trying to be clever

integration/imagetags_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/target_queue.go, internal/engine/testdata_test.go
Please review the following commits I made in branch nicks/ch2033/deps:
ab92cf90cb49e30c567c9c20c9dc016b4eacf457 (2019-03-28 13:20:23 -0400)
engine: make target queue more like a real build graph. fixes some bugs in dirtyness checking w/ dependent images
=> engine: make target queue more like a real build graph. fixes some bugs in dirtyness checking w/ dependent images

web/src/HUD.tsx, web/src/LogPane.scss, web/src/LogPane.tsx, web/src/Statusbar.scss, web/src/__snapshots__/LogPane.test.tsx.snap, web/src/constants.scss
Please review the following commits I made in branch nicks/logpane:
aa563c19cbb88081ccadc6d2d7724abaf7260013 (2019-03-28 22:29:11 -0400)
web: tweak LogPane styles a bit to make room for blinking cursor
=> web: tweak LogPane styles a bit to make room for blinking cursor

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontroller_test.go, internal/engine/extractors.go, internal/engine/local_container_build_and_deployer.go, internal/engine/local_container_build_and_deployer_test.go, internal/engine/podlogmanager.go, internal/engine/synclet_build_and_deployer.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/model/live_update.go, internal/model/manifest.go
Please review the following commits I made in branch maiamcc/targets-for-live-upd:
8442ab8c58bde4092991fc0a55fcdf9849ad5ad3 (2019-03-28 16:45:22 -0400)
synclet BaD can handle LiveUpdate / tests green
ee7e5c0272d16ff931bd51c7f4780ea534603ab0 (2019-03-28 16:35:48 -0400)
red tests for synclet BaD
19182300872febdfa6daf21a9e7302a3b53f1c93 (2019-03-28 15:04:05 -0400)
are these tests better or worse?
8d2d5536ac6d61a724b7c81253f0764591df2d84 (2019-03-28 14:09:59 -0400)
behavior implemented for localContainerBuild / green tests
153e06faf47ee133aeca3440fb973a6398aaed87 (2019-03-28 13:16:24 -0400)
red test for localContainerBaD
e367c3b2ebb7f0f3514bab75a6af04ad57f3dcbd (2019-03-28 13:04:04 -0400)
extract liveupdate targets
Code review reminders, by giving a LGTM you attest …
=> engine: container BaD's can handle image targets with LiveUpdate [ch2039]

Makefile, hide_tbd_warning
This was fixed in go 1.11, so the workaround is no longer needed.
=> makefile: rm hide_tbd_warning

internal/k8s/image.go
Hello @nicks,
Please review the following commits I made in branch nicks/fmt:
b55efeb0dea4938cc4a000d2a497a5795996b695 (2019-04-02 12:06:40 -0400)
k8s: fix a bogus fmt.Print
=> k8s: fix a bogus fmt.Print

internal/build/boil_runs.go, internal/build/boil_runs_test.go, internal/build/container_test.go, internal/build/docker_benchmark_test.go, internal/build/image_builder.go, internal/build/image_builder_test.go, internal/build/path_mapping.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/local_container_build_and_deployer.go, internal/engine/testdata_test.go, internal/engine/upper_test.go, internal/ignore/path_matcher.go, internal/model/live_update.go, internal/model/live_update_test.go, internal/model/manifest.go, internal/model/manifest_test.go, internal/model/matcher.go, internal/synclet/fake_client.go, internal/testutils/tempdir/temp_dir_fixture.go, internal/tiltfile/docker.go, internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/run-triggers:
2a4675924f9d73972792dde5c89e37553295fa9b (2019-04-01 17:14:08 -0400)
better live update run.trigger tests
9e91704ff32f69807e254b035499b543e6168c3c (2019-04-01 17:06:47 -0400)
change how we store triggers
b94bd9e83978aea80516956313e3446bd874acee (2019-04-01 13:45:29 -0400)
pull up getChangedFiles
964da22a9ebe1acde6d963ec84651d51a22a1391 (2019-04-01 13:45:29 -0400)
red test for local container build
9a1ffb5839fad455878e8419d0cae914ef581e7b (2019-04-01 13:45:29 -0400)
generalize run.trigger matching
* Code is …
=> engine: change how we store/check run.triggers (so can better implement full_rebuild_trigger)"

web/src/HUD.test.tsx, web/src/HUD.tsx
Okay, let's dive in to some React and JavaScript truisms:
React components re-render under three conditions:
1. The component's state changed
2. The component's prop changed
3. The component's parent changed (See 1 and 2)
What was causing the flicking was a combination of 1, 2 and 3. While the
Sidebar component's props _weren't_ changing, its grandparents state was which
caused an accidental change to the Sidebar's parent's props, which caused
the sidebar to re-render.
Let's examine this flow in detail. First let's establish the component hierarchy:
[HUD] -> [Route] -> [Sidebar]
1. We get new information from the websocket, which changes HUD's state.
2. That change in state causes the HUD's render function to be re-run
3. This creates a new function, `SidebarRoute` which we pass to Route. …
=> web: fix sidebar flickering

web/src/LogPane.tsx
Autoscroll if the bottom of the element is not in view, not if the top
of the element is not in view.
=> web: adjust when autoscroll starts

internal/hud/server/view.go
Please review the following commits I made in branch nicks/ch2127/tick:
2d7ccff0067be78c77863153b6ec1155b78dce35 (2019-04-03 14:37:38 -0400)
webview: assume pending if pod state hasn't shown up yet
=> webview: assume pending if pod state hasn't shown up yet

web/tsconfig.json
This seems to make webpack a bit faster though it's annoying to precisely measure it since `yarn start` is interactive.
=> web: dont check libs with tsc

internal/tiltfile/files.go, internal/tiltfile/tiltfile_test.go
just noticed this while doing some other tests
(also fixed a bug where listdir was relative to wd instead of tiltfile)
=> tiltfile: rm chdir from tests

internal/tiltfile/k8s.go, internal/tiltfile/k8s_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
This is most of the implementation of the new resource assembly.
The chief missing thing is the ability to specify resource options (i.e., `k8s_resource`), which will is covered by ch2109.
=> tiltfile: add basic support for k8s resource assembly v2

internal/engine/configs_controller.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/errors:
424aefa00529ce8199d0af9bdef822997bc0e474 (2019-04-04 13:28:02 -0400)
engine: make sure tiltfile errors show up in the tiltfile pane
=> engine: make sure tiltfile errors show up in the tiltfile pane

integration/live_update/Tiltfile, internal/model/live_update.go, internal/tiltfile/docker.go, internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch maiamcc/live-update-syntax:
13940be1bc1bb1632fe9f5900e70919ce191cc6e (2019-04-04 14:09:50 -0400)
integration test
f8092c6197e4c734a8c3f9b95cf544ed09fe050e (2019-04-04 14:02:04 -0400)
custom build support
de1c7559431243ba8d4d971e436fb75c23b9a3fc (2019-04-04 13:58:09 -0400)
fall_back_on works
0a28d00d15fa997ec6801be35c3b46108d3f6138 (2019-04-04 12:54:30 -0400)
more red tests - ready for fall_back_on
24608d86b280b877f5745cb5bfe3bbba249e124e (2019-04-04 12:47:01 -0400)
tests so far mostly green
d5fcf8f51e2790be4f6f0b35d1b0de613b07efa5 (2019-04-04 12:22:30 -0400)
red tests …
=> tiltfile: rejigger live update declaration syntax"

web/src/AppController.ts, web/src/HUD.scss, web/src/HUD.test.tsx, web/src/HUD.tsx, web/src/LoadingScreen.scss, web/src/LoadingScreen.tsx, web/src/LogPane.scss, web/src/LogPane.test.tsx, web/src/LogPane.tsx, web/src/PreviewPane.scss, web/src/PreviewPane.test.tsx, web/src/PreviewPane.tsx, web/src/Sidebar.scss, web/src/Sidebar.test.tsx, web/src/Sidebar.tsx, web/src/Statusbar.scss, web/src/__snapshots__/LogPane.test.tsx.snap, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/constants.scss, web/src/index.scss
I tried tab-like buttons for "Logs" and "Preview" view options.
- In this PR, it's not obvious the view options are buttons. I'll address this in my next design pass.
- When we have more than two views, this design will have to change.
I mocked up a design with the view options to the left of the sidebar, but it was a bit too visually obtrusive.
=> web: create preview pane

internal/model/log.go
Please review the following commits I made in branch nicks/abbrev:
148ce6aebddd74307a04c645f9aaf47dbc032695 (2019-04-05 12:23:07 -0400)
model: represent Log as an array of lines
there should be no functional changes in this pr
=> model: represent Log as an array of lines

internal/build/tar.go
This results in a significant performance improvements for initial builds that ignore directories with lots of files in them, in the area of 2x-4x improvement on macOS.
=> build: skip iterating through directories that are ignored

internal/engine/upper.go, internal/engine/upper_test.go
Please review the following commits I made in branch nicks/nicks/ch2152/tiltfile:
fbf44d031c2fa73f785963144c922789e27a7063 (2019-04-05 17:26:06 -0400)
engine: fix up dupe tiltfile logs by making the tiltfile logs more consistent with other logs
=> engine: fix up dupe tiltfile logs by making the tiltfile logs more consistent with other logs

internal/cli/wire_gen.go, internal/hud/hud.go, internal/hud/renderer_test.go, internal/hud/server/view.go, internal/hud/view/view.go, internal/store/engine_state.go
It's unclear to me how best to record this data. Any advice?
=> engine: record how many times a user has opened a log in stats [ch2194]

internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go
I was confused when I added a warning and it didn't show up in the log or HUD. It turns out that we don't actually use the strings we put in `s.warnings`, but only check its length.
This was fine since we only had one warning, but now that we're adding more, we might as well put this in a func so we can be consistent about how we log them.
=> tiltfile: automatically print warnings after loading

internal/hud/renderer.go, internal/hud/server/view.go, internal/hud/server/view_test.go, internal/hud/view/view.go, internal/hud/webview/view.go, internal/store/engine_state.go, internal/store/engine_state_test.go, web/src/HUD.tsx
Please review the following commits I made in branch nicks/tiltfileerrormessage:
4ac7995f9ccdaf7c9c86f71d43f75358d11f34f9 (2019-04-09 15:05:45 -0400)
hud: remove TiltfileErrorMessage
This code is all obsolete. The empty tiltfile case is handled in configs_controller now.
=> hud: remove TiltfileErrorMessage

web/src/Sidebar.scss
Please review the following commits I made in branch nicks/sticky:
b4d67bc10875debf1a497efa14f9361a8c6b7f04 (2019-04-10 11:51:28 -0400)
web: don't set the line-height on the collapse button. it's unnecessary and makes an extra scrollbar appear
=> web: don't set the line-height on the collapse button. it's unnecessary and makes an extra scrollbar appear

internal/build/container_updater.go, internal/build/image_builder.go, internal/build/path_mapping.go, internal/engine/synclet_build_and_deployer.go
Hello @landism, @dbentley,
Please review the following commits I made in branch maiamcc/sync-transparency:
1e6abee87d1b335518f15597cc6e85b0da220271 (2019-04-09 15:45:33 -0400)
build: in verbose mode, print what files we're syncing/where syncing them to [ch2130]
=> build: in verbose mode, print what files we're syncing/where syncing them to [ch2130]

internal/build/boil_runs.go, internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_errors.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/extractors.go, internal/engine/image_build_and_deployer.go, internal/engine/local_container_build_and_deployer.go, internal/engine/synclet_build_and_deployer.go, internal/model/matcher.go
Hello @dbentley, @landism,
Please review the following commits I made in branch maiamcc/which-matched-fall-back:
c0c3d2d270dd3233d34487298068cabd49c982b5 (2019-04-08 12:47:48 -0400)
can specify log level for RedirectToNextBuilder error
070fc4a4289a0f3161a9d66e6872020b1dd9c55b (2019-04-08 12:36:33 -0400)
engine: better logging around which FallBackOn file matched
=> engine: specify which files matched FallBackOn, surface message to user [ch2129]

internal/tiltfile/k8s.go
the type name as we represent it to starlark should follow python naming conventions (i.e., classes start with caps)
=> tiltfile: make k8sobjectid starlark type UpperCase

internal/store/dirty.go, internal/store/dirty_test.go, internal/store/subscriber.go, internal/store/subscriber_test.go
Please review the following commits I made in branch nicks/dirty:
d2fa04d75b92ede93a8ebc40b927ad67afb96386 (2019-04-12 13:56:21 -0400)
store: try to avoid spurious onchange events
=> store: try to avoid spurious onchange events

internal/engine/buildcontroller.go, internal/engine/upper_test.go, internal/store/build_result.go
This addresses one of the issues in [ch2241](https://app.clubhouse.io/windmill/story/2241/infinite-k8s-redeploy-loop) and suffices to stop the looping (at least, in the one repro case I know of). There are a few other things in there that I might like to sort out, but they seem much less pressing.
=> engine: don't do container builds in the wrong container

internal/hud/server/assets.go, internal/sail/sail.go, internal/sail/server/room.go, internal/sail/server/server.go, web/src/HUD.tsx
Please review the following commits I made in branch nicks/ch2240/sail:
501c173096a11171c736e62e3d7f06562ccf7771 (2019-04-16 14:35:10 -0400)
sail: end-to-end sharing
=> sail: end-to-end sharing

internal/engine/build_and_deployer.go
as mentioned [here](https://github.com/windmilleng/tilt/pull/1454#discussion_r275933560) (#1451), the `write` method doesn't actually append a newline, so we need to do it ourselves.
otherwise, looks like this:
=> engine: add newline to a direct call to logger.write

internal/k8s/extract.go, internal/k8s/label.go, internal/k8s/label_test.go, internal/k8s/testyaml/testyaml.go
Please review the following commits I made in branch nicks/ch2291/pvc:
fb95da77a391754563a88e18097286e2543a72d0 (2019-04-17 18:08:24 -0400)
k8s: don't inject labels into persistent volume claims
=> k8s: don't inject labels into persistent volume claims

internal/ospath/ospath.go, internal/ospath/ospath_test.go
Please review the following commits I made in branch maiamcc/is-child-bug:
477bb8e293f740d84bd9a47a75afcee650bf60e3 (2019-04-18 16:05:11 -0400)
ospath: ensure that IsChild doesn't break on trailing slash
=> ospath: ensure that IsChild doesn't break on trailing slash

internal/kustomize/dependencies.go, internal/kustomize/dependencies_test.go, internal/tiltfile/tiltfile_test.go
Mostly taken from the [kustomize source code](https://github.com/kubernetes-sigs/kustomize/blob/ee68a9c450bc884b0d657fb7e3d62eb1ac59d14f/pkg/target/kusttarget.go#L97) itself.
Fixes #1503
=> kustomize: support alternative file names

web/src/Sidebar.scss, web/src/Sidebar.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Please review the following commits I made in branch nicks/sticky:
1c1730f10215fddeeaf829713a85dc59f419096c (2019-04-18 18:40:37 -0400)
remove position:sticky from the sidebar collapse button. this isn't really what sticky is for
=> remove position:sticky from the sidebar collapse button. this isn't really what sticky is for

internal/sail/sail.go
Please review the following commits I made in branch nicks/sailconfig:
35d3032d3bd041ab89838659d055db50a400fc7b (2019-04-18 18:21:24 -0400)
sail: more startup options and better cleanup
=> sail: more startup options and better cleanup

Tiltfile, internal/engine/build_and_deployer_test.go, internal/model/matcher.go, internal/model/matcher_test.go, internal/testutils/tempdir/temp_dir_fixture.go, internal/tiltfile/live_update_test.go
Please review the following commits I made in branch maiamcc/file-or-child-matcher:
51f641ee2de47ed80bb016f8d149e36eccd6b9c0 (2019-04-22 17:01:19 -0400)
add directory-based run triggers back to Tiltfile for sail
e0a1f09cfeaa7a00023b163f6bb9d0aa1efe621d (2019-04-22 16:54:31 -0400)
test
a1f1ec8c9836f9ca4b6f19b115677223dea3619a (2019-04-22 16:40:41 -0400)
model: new matcher that matches on either exact match of child of given paths
=> model: new matcher that matches on either exact match of child of given paths (for better tiltfile for Sail)

web/src/LogPane.scss, web/src/LogoButton.scss, web/src/Sidebar.scss, web/src/Statusbar.scss, web/src/TabNav.scss, web/src/constants.scss, web/src/index.scss
- Use Solarized grays (many people use this color scheme, and I think it still goes well with Tilt colors)
- Add some shadows to sidebar and tabnav to create look of depth
- Fewer colors to choose from makes life easier
=> web: fine-tune colors

internal/model/manifest.go, internal/tiltfile/docker_compose.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
This is the first PR for [manual update control](https://github.com/windmilleng/tilt.specs/blob/master/manual_update_control.md).
This PR lets you configure update modes, either globally, or per-resource.
All this currently does is set the internal `UpdateMode` field on the manifest, which is not currently used by anything, and will be used in a later PR.
=> tiltfile: add update_mode (but it doesn't do anything)

internal/model/manifest.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/busted:
c448e728bc2badd0d24054ad2ce36814e9f27d07 (2019-04-25 18:38:27 -0400)
titltfile: fix the impossible live update check when there are undeployed images
=> titltfile: fix the impossible live update check when there are undeployed images

internal/cli/up.go, internal/engine/actions.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/view.go, internal/hud/webview/view.go, internal/sail/client/client.go, internal/store/engine_state.go, web/src/HUD.tsx, web/src/SailInfo.scss, web/src/SailInfo.tsx, web/src/TabNav.scss, web/src/TabNav.test.tsx, web/src/TabNav.tsx, web/src/TopBar.scss, web/src/TopBar.test.tsx, web/src/TopBar.tsx, web/src/__snapshots__/TabNav.test.tsx.snap, web/src/__snapshots__/TopBar.test.tsx.snap, web/src/constants.scss
Hello @yuindustries, @nicks,
Please review the following commits I made in branch maiamcc/sail-info-component:
05454210c972ade589254606635e38c555f97545 (2019-04-26 13:36:28 -0400)
clean up go
b8e711c168237345b5d485d1b670e6dc20571ec6 (2019-04-26 13:35:36 -0400)
update tests
04bb99e5981e52bbd7b1edb89109a268db702d91 (2019-04-26 13:09:55 -0400)
sailinfo is its own component
b463de5c385e48f33be49d515c8c78dbd7e86b7f (2019-04-26 11:24:32 -0400)
share button in ui if sail enabled but no url
=> web: make sail-info its own component, show "connect to sail" button if sail enabled and no url

internal/assets/server.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/hud/server/controller.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/sail/sail.go, internal/sail/server/server.go
Please review the following commits I made in branch maiamcc/asset-server-pkg:
82f19200dde4f38e8bf6e6b5d4845b068aadbf8f (2019-04-26 16:12:07 -0400)
assets: move AssetServer to its own package because it's shared
=> assets: move AssetServer to its own package because it's shared

internal/model/target_graph.go, internal/model/target_graph_test.go, internal/model/target_test.go
Please review the following commits I made in branch nicks/liveupdategraph:
83c6780b60f53b11fc5d8957bef11985c6b857b8 (2019-04-26 15:20:40 -0400)
model: add a helper struct for traversing image graphs
=> model: add a helper struct for traversing image graphs

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go
Please review the following commits I made in branch nicks/stateset:
ff1b4fc29647b002e1ce05daad79e7a48359658e (2019-04-26 17:06:57 -0400)
engine: A BuildState's FileChanged field should only contain files that the image depends on. Fix up the tests to accurately reflect this
=> engine: A BuildState's FileChanged field should only contain files that the image depends on. Fix up the tests to accurately reflect this

Makefile
Hello @nicks,
Please review the following commits I made in branch nicks/parallel:
5ddb64b46145241adb9c5119ecbb92e4671a1aa5 (2019-04-29 13:06:16 -0400)
makefile: remove workaround for go linker issues
=> makefile: set parallelism to 4, because the linker is still getting sigkills on circleci

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/extractors.go, internal/engine/live_update_state_tree.go, internal/engine/local_container_build_and_deployer.go, internal/engine/synclet_build_and_deployer.go
Please review the following commits I made in branch nicks/liveupdategraph2:
ed079fd30eabb1ac8d4106d6f564eba0a9793577 (2019-04-28 23:33:29 -0400)
engine: in-place updates for files from the base image
Note that this commit doesn't fix the underlying bug yet, because
we still need to update the tiltfile to allow these kinds of live-updates
=> engine: in-place updates for files from the base image

internal/k8s/container.go, internal/k8s/container_test.go, internal/k8s/pod.go, internal/k8s/pod_test.go, internal/k8s/watch.go
Please review the following commits I made in branch nicks/badtag:
aea59f869406825b1bb9d444ba64883268c5c678 (2019-04-29 17:09:34 -0400)
k8s: add a work-around for bugs in container status image refs
https://github.com/kubernetes/kubernetes/issues/51017
=> k8s: add a work-around for bugs in container status image refs

integration/live_update_base_image/Tiltfile, integration/live_update_base_image/app.yaml, integration/live_update_base_image/app/Dockerfile, integration/live_update_base_image/common/Dockerfile, integration/live_update_base_image/common/message.txt, integration/live_update_base_image_test.go, internal/model/manifest.go, internal/tiltfile/docker.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/ch2351/liveupdate:
3093f8a14e4e2eb3074702a33a86962a64c6b386 (2019-04-29 15:36:42 -0400)
tiltfile: allow live_update syncs from dependent images
also add integration tests
=> tiltfile: allow live_update syncs from dependent images

internal/assets/server.go, internal/demo/script.go, internal/engine/analytics_reporter.go, internal/engine/configs_controller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/controller.go, internal/hud/server/websocket.go, internal/sail/client/client.go, internal/sail/client/fake_client.go, internal/sail/sail.go, internal/sail/server/server_test.go, internal/store/store.go, internal/store/store_test.go, internal/store/subscriber.go, internal/store/subscriber_test.go
Hello @nicks,
Please review the following commits I made in branch maiamcc/subscriber-setup:
2f2613ba1668f3acacf8a0c332dbf6c1fb54d52e (2019-04-30 14:33:55 -0400)
store: add optional SetUp method for subscribers
=> store: add optional SetUp method for subscribers

internal/hud/server/server.go, internal/sail/client/client.go, internal/sail/client/client_test.go, internal/sail/client/fake_client.go, internal/sail/client/roomer.go
Hello @nicks,
Please review the following commits I made in branch maiamcc/surface-url-right-away:
269580dedd50dc11882c3e01a864ee833ba42614 (2019-04-30 15:53:19 -0400)
fix tests
b7fae20f1de4ae27d1fb9b94a388b03891f6967a (2019-04-30 15:47:12 -0400)
http new room and room connect are one step (but use persistent ctx for websocket)
c3638e5cb58ec801a67783fe6d678aaebfca41e7 (2019-04-30 15:40:46 -0400)
use SetUp to get ctx on the sail client
=> sail: re-unify new room and room connect so that we can surface the sail url right away, w/o waiting for OnChange

internal/sail/server/room.go, internal/sail/server/room_test.go
Hello @nicks,
Please review the following commits I made in branch maiamcc/current-status-on-join:
97dcf25a6ead5594af3668b511b393fb96884e81 (2019-04-30 17:13:17 -0400)
sail server: send most recent data to new fan on join [ch2310]
=> sail server: send most recent data to new fan on join [ch2310]

internal/tiltfile/files.go
Please review the following commits I made in branch maiamcc/read-yaml-tweaks:
dd0fb7eab4566ebf1b737aa1b70274aa5d829351 (2019-05-01 11:22:31 -0400)
tiltfile: tweaks to read_yaml to match naming conventions
=> tiltfile: tweaks to read_yaml to match naming conventions

internal/assets/prod_server_test.go, internal/assets/server.go
Please review the following commits I made in branch maiamcc/specify-asset-version:
de425dd03db3c61cc3cac7df5a57ec0e0a3b203e (2019-05-02 13:59:54 -0400)
respect version query param
558a14aafb93c2cbe7ec3bef40a64c08206bff7e (2019-05-02 12:21:31 -0400)
preserve existing behavior constructing with default url
=> assets: prod asset server can accept version to serve as query param [ch2284]

deployments/sail.dockerfile, internal/assets/prod_server_test.go, internal/assets/server.go, internal/cli/build.go, internal/hud/server/server.go, internal/model/sail.go, internal/model/tilt_build.go, internal/sail/client/client.go, internal/sail/client/client_test.go, internal/sail/client/roomer.go, internal/sail/server/room.go, internal/sail/server/room_test.go, internal/sail/server/server.go
Please review the following commits I made in branch maiamcc/sail-serve-right-version:
5354bb72b31ff3be23609d1db1c50c2f007b71a3 (2019-05-02 18:36:42 -0400)
clean-up
b721f358e26d563261e8374a5a05a7c288198b47 (2019-05-02 18:28:40 -0400)
inject version into returned html
744c3f5f0a6ecb5c452040eea3415f895f12f3db (2019-05-02 18:28:35 -0400)
respect versions in prod server urls
0a1daa52a902c1198415e662b5800174253ec593 (2019-05-02 18:28:32 -0400)
wip
0bf54aa51c65cb443511f995bfcb475485e266a6 (2019-05-02 18:28:30 -0400)
send version with new_room request
* Code is suitably instrumented with …
=> sail: sail serves the correct assets for the requested room [ch2283]

internal/tiltfile/docker.go, internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
it turns out there was a very simple reason my dockerignore changes weren't taking effect!
=> tiltfile: record .dockerignore as configfiles

web/src/Sidebar.test.tsx, web/src/Sidebar.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/testdata.test.tsx
=> web: bucketize durations under a minute

internal/build/tar.go, internal/build/tar_test.go
This might be mildly controversial. This is effectively just reverting #1445, which gave us a big build speedup in some cases. Unfortunately, it introduced a problem:
If, e.g., vigoda's .dockerignore has `*` and `!main.go`, we'll `filepath.Walk` to `vigoda`, it will be ignored because it matches `*`, and we'll never descend into `vigoda` to discover `vigoda/main.go`.
This change makes the associated test go red -> green and also fixes the vigoda repro mentioned above.
We could be clever by parsing out the exclusions and descending more intelligently (or even only descending if there exists any `!` at all), but that's a more complex fix, and it seems best for today to apply this cheap fix to make things work, even if it comes with a perf hit.
=> build: don't skip ignored directories

internal/hud/webview/convert.go
to fix this situation:
Now tiltfile dependency edits are displayed relative to the tiltfile's directory, e.g.:
(FWIW, this wasn't a problem in the TUI because the renderer just shows `filepath.Base` for all edits, to save space. In the Web UI, we make paths relative to watched paths for normal resources, but didn't do anything for the Tiltfile resource, so we just showed abs paths)
=> web: display tiltfile edit paths relative to tiltfile

web/src/ErrorPane.tsx, web/src/HUD.test.tsx, web/src/HUD.tsx, web/src/TabNav.test.tsx, web/src/TabNav.tsx, web/src/TopBar.test.tsx, web/src/TopBar.tsx, web/src/__snapshots__/TabNav.test.tsx.snap, web/src/__snapshots__/TopBar.test.tsx.snap, web/src/index.tsx
Future work that will happen in a different PR:
* Styling this number to be a bit better
* When you click on the errors tab the number gets reset to zero.
=> web: show number of errors next to errors tab

Makefile, deployments/sail-staging-networking.yaml, deployments/sail-staging.dockerfile, deployments/sail-staging.yaml, internal/cli/up.go, internal/cli/up_test.go, internal/model/sail.go, internal/sail/client/roomer.go
Please review the following commits I made in branch nicks/ch2495/staging:
cb9a7c324cf655d1bd9ad4d9278c44bb3c850729 (2019-05-09 16:41:03 -0400)
sail: add a staging server for testing SSL
=> sail: add a staging server for testing SSL

internal/docker/client.go, internal/docker/client_test.go
Please review the following commits I made in branch nicks/tcp:
2aa5674cba80b8325a85e236a9683b49025cb607 (2019-05-13 11:16:54 -0400)
docker: normalize DOCKER_HOST addresses
=> docker: normalize DOCKER_HOST addresses

web/src/AnalyticsNudge.scss, web/src/AnalyticsNudge.tsx, web/src/HUD.tsx, web/src/Sidebar.test.tsx, web/src/Sidebar.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap
Styling TBD (look there's even [a ticket for it](https://app.clubhouse.io/windmill/story/2554/style-nudge-in-web)) but this PR displays the analytics nudge in the sidebar. If it's a long list of entries, we show the nudge 3rd in the list to avoid it getting lost in the shuffle. Awkward left-border to make it visible even when the pane is collapsed. Enjoy this hot mess of CSS! (don't worry, this is all gated behind an env variable.)
=> web: analytics nudge in sidebar (placeholder, styling TBD) [ch2531]

internal/assets/server.go, web/web.go
Please review the following commits I made in branch nicks/runtime:
a82182c5a6411c604de6d419a66cfdc20e941ff3 (2019-05-13 17:51:05 -0400)
web: use runtime instead of the build loader to load assets
=> web: use runtime instead of the build loader to load assets

integration/oneup_watch_exec_test.go, integration/onewatch_exec/Dockerfile, internal/engine/synclet_build_and_deployer.go
Prior to this change the exec test wasn't really testing exec. When
we tried to do an exec update it would fail due to incompatibilites
between GNU tar and busybox tar. This would cause the update to fall
back to an image build, which caused the test to pass.
Let's make sure that the pods dont change AND install GNU tar in the
container so that the test passes.
While this feels a little gross, it's at least testing more than it was.
Discovered while looking in to #1611
=> integration: fix exec test

internal/github/client.go, internal/model/tilt_build.go
prior to this:
the "current" build had no leading "v", e.g. "0.8.3"
the "latest" build fetched from github had a leading "v", e.g., "v0.8.3"
1. strip v from github versions, so that we're all the same
2. document that in the TiltBuild class
3. no unit test since implementing a fake github api doesn't seem like a good use of time right now. unless someone has a cheaper idea?
=> version check: strip leading 'v' from github versions to be consistent

DEVELOPING.md, internal/cli/up.go
Please review the following commits I made in branch nicks/sail:
f1d72354b2bfac687a26290fb1da9aee3adc067b (2019-05-14 19:32:03 -0400)
developing: add documentation on sail server, change flag name to --share
=> developing: add documentation on sail server, change flag name to --share

Gopkg.lock, Gopkg.toml, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/upper.go, internal/hud/server/analytics_opt.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/hud/webview/analytics_nudge.go, internal/store/actions.go, vendor/github.com/windmilleng/wmclient/pkg/analytics/cli.go, vendor/github.com/windmilleng/wmclient/pkg/analytics/opt.go
Please review the following commits I made in branch maiamcc/record-opt:
4782d0bc60e11074abe299205d24fc687920563c (2019-05-15 15:29:34 -0400)
tests
22eb8ac21f44adaf2719ae98d82d71f686fa8711 (2019-05-15 15:06:09 -0400)
put functionality in http handler
08d4fa94f388a4277038182e2125e0c58fd99bd9 (2019-05-15 14:58:36 -0400)
test opter
02dffc057f9c21c88e05ffd13ac6b33ebab29fb4 (2019-05-15 14:41:27 -0400)
skeleton opter and events
624a508e87ea47c8de2af0bbe250978e7233b2f7 (2019-05-15 14:27:19 -0400)
update wmclient
7cb4127815c0cb47f20b0634886349ae847eeae1 (2019-05-15 14:11:30 -0400)
vendor: run dep ensure
* Incomplete code is …
=> hud/server: record user choice from opt in/out button [ch2533]

web/package.json, web/src/AnalyticsNudge.test.tsx, web/src/AnalyticsNudge.tsx, web/src/__snapshots__/AnalyticsNudge.test.tsx.snap, web/src/__snapshots__/TopBar.test.tsx.snap, web/yarn.lock
Please review the following commits I made in branch maiamcc/acknowledge-opt:
d79f671082f9b2c739d80b725b368dcb63f9daec (2019-05-16 18:37:45 -0400)
add enzyme-to-json, test analyticsNudge
7d5497fecac9d32896fd75ef154d0ebcc21659a6 (2019-05-16 17:54:32 -0400)
web: store state on analyticsNudge, reflect endpoint result, disappear after 3s
=> web: when user opts in/out via nudge, acknowledge it, and vanish the notification [ch2590]

internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/watchnamespace:
628e37317d8d9899642f0e2ed585321d789aff5d (2019-05-16 18:38:35 -0400)
k8s: add a bunch of unit tests around watch and namespace restrictions
=> k8s: add a bunch of unit tests around watch and namespace restrictions

internal/cli/wire_gen.go, internal/engine/upper_test.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
This is useful to allow you to set a different registry when iterating against microk8s. e.g.,
if k8s_context() == 'microk8s': #microk8s uses a local registry
default_registry('localhost:32000')
=> tiltfile: k8s_context returns the name of the k8s context Tilt locked

internal/engine/version_checker.go, web/src/Statusbar.test.tsx, web/src/Statusbar.tsx, web/src/__snapshots__/Statusbar.test.tsx.snap
This is to make #1658 a little less bad.
The API limit issue will be addressed separately.
=> version check: move api limit errors to verbose, don't render upgrade badge on error

internal/engine/upper_test.go
Idk why this test hit this case on master at all, but when it did, we got this nonsensical error b/c of the weird args of `assert.FailNow`:
```
=== FAIL: internal/engine TestSetAnalyticsOpt (14.44s)
panic: interface conversion: interface {} is int, not string [recovered]
panic: interface conversion: interface {} is int, not string
goroutine 1671 [running]:
testing.tRunner.func1(0xc000156400)
/usr/local/go/src/testing/testing.go:830 +0x388
panic(0x24b5ca0, 0xc000746450)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/windmilleng/tilt/vendor/github.com/stretchr/testify/assert.messageFromMsgAndArgs(0xc000dafe88, 0x2, 0x2, 0x2, 0x3)
/go/src/github.com/windmilleng/tilt/vendor/github.com/stretchr/testify/assert/assertions.go:189 +0x177 …
```
=> upper test: don't use assert.FailNow b/c its type signature doesn't make sense

web/src/ErrorPane.test.tsx, web/src/ErrorPane.tsx, web/src/__snapshots__/ErrorPane.test.tsx.snap
The styling for errors in ErrorPane.scss applies to `<code>` elements.
For most of the types of error items we can show in ErrorPanes, we put them in `<p>` elements and *not* `<code>` elements!
It turns out that `<code>` elements are generated by the `AnsiLine` splitting we do for build errors.
This means we get all kinds of fun things, like if a pod crashes with two log lines, we display them both and ignore the newline, so they're concatenated horizontally.
Since build errors have been styled (i.e., we actually define styles for them in the scss) and the other types haven't, I'm assuming we should make everything else match build error styling.
Note this also means I'm dropping the "Last log line" copy, because:
1. we don't have it for build errors, and it's fine
2. it's a lie - we …
=> web: use build error formatting for other errors too

internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/webview/convert.go, internal/hud/webview/view.go, web/src/ErrorPane.test.tsx, web/src/ErrorPane.tsx, web/src/__snapshots__/ErrorPane.test.tsx.snap
1. We were only populating `CrashLog` in the crash rebuild case. We now also populate it when the restart count increases.
2. We were not using `CrashLog` at all in the web UI, so the web UI was just showing post-restart logs, and it's pretty frustrating for an alert to pull your attention to that tab just to show you logs that are not actually relevant.
on web:
in TUI:
=> ui: use crashlog for crashes

internal/tiltfile/docker.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/fast-build-deprecation-warn:
873ed75d9d799615774dace32223edb6041111b2 (2019-05-22 17:51:28 -0400)
tiltfile: deprecation warning for FastBuild
=> tiltfile: deprecation warning for FastBuild

internal/cli/analytics.go, internal/cli/demo.go, internal/cli/doctor.go, internal/cli/down.go, internal/cli/up.go, internal/cli/wire.go, internal/cli/wire_gen.go
Please review the following commits I made in branch maiamcc/analytics-on-context:
a4c4436dff2a0abf76c77a8da9f9eb5124b9f7d7 (2019-05-23 13:43:34 -0400)
[analytics] close loop on transporting analytics around on the context by removing global
=> [analytics] close loop on transporting analytics around on the context by removing global

internal/build/test_utils.go, internal/cli/wire_gen.go, internal/docker/client.go, internal/docker/client_test.go, internal/synclet/wire_gen.go
Please review the following commits I made in branch nicks/issue1681:
beb1954ab826bbe85f045146083ff7c288bbaa80 (2019-05-24 13:50:11 +0100)
docker: disable buildkit on minikube. Fixes https://github.com/windmilleng/tilt/issues/1681
2247f5f2aff9fcf7aa1cdc7b5de709a0861051d3 (2019-05-24 13:36:43 +0100)
cli: add 'tilt docker' and let the user manually enable/disable buildkit
=> docker: disable buildkit on minikube. Fixes https://github.com/windmilleng/tilt/issues/1681

internal/engine/upper.go
When one:
1. deploys a change to a tilt resource via live_update
2. triggers a crash in that resource
One observes:
1. "Detected a container change for docs-site. We could be running stale code. Rebuilding and deploying a new image." is logged in the "all resources" log
2. The same message is not logged in the resource-specific (e.g., `fortune`) log, so that log just shows builds happening without reason
Also log the "detected a container change" message to the resource-specific log.
(There's probably some logging api cleanup we should do here, like having a clear hierarchy of logs (all -> resource-specific -> resource+build-specific), and writing to a lower log also writes to its ancestors, or something)
=> upper: log 'detected a container change' message to ms.CombinedLog

internal/k8s/client.go, internal/k8s/encoder.go, internal/k8s/entity_benchmark_test.go, internal/k8s/fake_client.go, internal/k8s/image_test.go, internal/k8s/label_test.go, internal/k8s/serialize.go, internal/k8s/serialize_test.go, internal/k8s/target.go, internal/k8s/testyaml/testyaml.go, internal/synclet/sidecar/sidecar_test.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/poddisruption:
5b4b73e027e0d372fc4b24008671b53aa37ef647 (2019-05-28 10:44:19 -0400)
k8s: clean up serializers so that they ever print status objects
Fixes https://github.com/windmilleng/tilt/issues/1667
=> k8s: clean up serializers so that they ever print status objects

integration/fixture_test.go, integration/k8s_fixture_test.go, integration/shortlived_pods/Tiltfile, integration/shortlived_pods/shortlived_pods.yaml, integration/shortlived_pods_test.go, internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go
=> engine: get logs from pods if succeeded or failed (as well as if running) so we can get logs for short-lived pods (jobs, etc.) -- addresses #1669

internal/engine/actions.go, internal/engine/event_watch_manager.go, internal/engine/uid_map_manager_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/events.go, internal/k8s/fake_client.go, internal/model/log.go, internal/store/actions.go, internal/store/engine_state.go
Hello tbd,
Please review the following commits I made in branch maiamcc/event-in-mainfest-log:
66d790585c47b739ff76a218b2dfab83dcc206eb (2019-05-31 12:34:17 -0400)
store warn events on manifest state
37bcdbf7bb5eb595cc2c7a0fca51499f0ce24dc3 (2019-05-31 12:19:35 -0400)
test global log, only log warning events
d81501f1acbcfff3c2d1b2416448d5cda332153e (2019-05-31 12:07:40 -0400)
timestamp test
c6b0e531c678f8b602b0202f6d2019785a2ca8ba (2019-05-31 11:46:45 -0400)
tests wip
35be4adee1584ef92ad3de7f0eae04b1cc40fb0e (2019-05-30 16:52:25 -0400)
engine: log k8s events to appropriate manifest log as well as global log
* Incomplete code is marked with …
=> engine: log k8s events to appropriate manifest log as well as global log [ch2644]

internal/k8s/errors.go, internal/k8s/runtime.go, internal/k8s/runtime_test.go, internal/k8s/watch_test.go
Please review the following commits I made in branch nicks/node-error:
46e8f237c9de53436845bf49883191f62732924d (2019-06-03 11:06:13 -0400)
k8s: better error reporting when tilt doesn't have permission to read nodes
=> k8s: better error reporting when tilt doesn't have permission to read nodes

internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/store/actions.go, web/package.json, web/src/HUD.tsx, web/yarn.lock
This PR removes two things, under the assumption that we won't need them going forward:
1. Web shortcut to reset restart count for all resources
2. API endpoint that resets the restart count for a resource
=> engine/web: remove kubecon demo features

integration/access.yaml, internal/k8s/watch.go
Hello tbd,
Please review the following commits I made in branch maiamcc/watch-permissions-for-role:
a77b82679269585a8cb6463e71e7d5c2bbf389c9 (2019-06-06 11:29:41 -0400)
k8s: integration tests use roles instead of cluster roles, events watcher and uid watcher respect namespace [ch2686]
=> k8s: integration tests use roles instead of cluster roles, events watcher and uid watcher respect namespace [ch2686]

web/src/AlertPane.test.tsx, web/src/AlertPane.tsx, web/src/__snapshots__/AlertPane.test.tsx.snap, web/src/mostRecentBuild.test.ts, web/src/types.ts
Addresses parts of #1713
Alerts now show up in the UI like this:
=> web: warnings count as alerts

web/src/AlertPane.tsx, web/src/HUD.tsx, web/src/LogPane.scss, web/src/LogPane.test.tsx, web/src/LogPane.tsx, web/src/__snapshots__/LogPane.test.tsx.snap, web/src/combinedStatusMessage.test.ts, web/src/combinedStatusMessage.ts, web/src/constants.ts, web/src/testdata.test.tsx
Note the section above the logs and the message in the status bar.
=> web: show pod status more clearly

internal/cli/up.go, internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/engine/wire_gen.go, internal/hud/buildstatus.go, internal/hud/renderer.go, internal/hud/renderer_test.go, internal/hud/resourceview.go, internal/model/manifest.go, internal/model/trigger_mode.go, internal/tiltfile/docker_compose.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/disambiguate-update-mode:
7ac9f276c16620cfe54672d71e8f7c56633faf87 (2019-06-07 14:03:28 -0400)
fix in model
ac00de8ec2acb3c96c98073c565bd1d30649a0e7 (2019-06-07 13:39:20 -0400)
fix tiltfile tests
603bed5f3fbd00062e222a5b5f8782006c329ace (2019-06-07 12:13:45 -0400)
wip - changed in tiltfile code. TODO: tiltfile tests, model code
=> tiltfile/model: old UpdateModeAuto | Manual -> TriggerMode to match existing code, disambiguate with engine.UpdateMode [ch2701]

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/model/manifest.go
Please review the following commits I made in branch maiamcc/respect-trigger-mode:
4795e241e95a607f1d5a0b8d2d0ecb2c4c062723 (2019-06-07 15:45:56 -0400)
engine: build_controller respects manifest trigger mode [ch2355]
=> engine: build_controller respects manifest trigger mode [ch2355]

internal/engine/buildcontroller_test.go
Please review the following commits I made in branch maiamcc/honor-trigger-order:
82f0aaff7a74e29157fa7d589e1b3e9b985894fd (2019-06-10 12:13:36 -0400)
engine: tests that manual build queue respects order [ch2703]
=> engine: tests that manual build queue respects order [ch2700]

internal/engine/k8s_events_feature.go
Please review the following commits I made in branch maiamcc/events-feature-test:
f8b077f4e3a157dffd69555ce61f3e2830c7acda (2019-06-11 11:24:43 -0400)
engine: k8s_events feature flag casing should match the one we set in integration tests
=> engine: k8s_events feature flag casing should match the one we set in integration tests

internal/engine/upper_test.go, internal/engine/watchmanager.go
there are occasional test failures with `fatal error: concurrent map read and map write` due to tests accessing `WatchManager.targetWatches` while the manager is writing to it.
=> upper test: fix flaky tests

internal/engine/upper.go, internal/engine/upper_test.go, internal/model/manifest.go, internal/model/manifest_test.go
Please review the following commits I made in branch maiamcc/set-trigger-mode-from-tiltfile:
0dce522f86a002503d75a0b8aed6cbfa51eb06ed (2019-06-12 16:07:37 -0400)
actually test this code change
b315ef613b6db748286d0aa9c926058cb440b8ae (2019-06-12 16:01:24 -0400)
clean up some existing config change tests
f32a355fd79311fa5c7b3e30e4b3d71d99e27d3e (2019-06-11 16:27:43 -0400)
check triggerMode when checking manifest equality (so we attach the new manifest to the state if we only change triggerMode)
=> model: changes to a manifest's TriggerMode via config change actually make it into engine state [ch2703]

integration/k8s_fixture_test.go, internal/engine/event_watch_manager.go, internal/engine/event_watch_manager_test.go, internal/engine/k8s_events_feature.go, internal/engine/uid_map_manager.go, internal/engine/uid_map_manager_test.go, internal/engine/upper_test.go
A user reported #1744 affecting `Deployment`, so hiding the events feature behind a flag until we've fixed that.
=> Revert "engine/integration: remove k8s events feature flag (#1708)"

web/src/HUD.test.tsx, web/src/HUD.tsx, web/src/Sidebar.test.tsx, web/src/Sidebar.tsx, web/src/SidebarIcon.test.tsx, web/src/SidebarIcon.tsx, web/src/__snapshots__/Sidebar.test.tsx.snap, web/src/status.tsx, web/src/testdata.test.tsx, web/src/types.ts
This lays the groundwork for a series of changes that will disentangle the idea of "the status in kubernetes" from "where is this resource in Tilt's flow", in to two different statuses: `RuntimeStatus` (for k8s) and `ResourceStatus` (for Tilt).
In a future PR I will remove the `combinedStatus` function and call two different functions: `runtimeStatus` and `resourceStatus` as appropriate in the various places that `combinedStatus` is used.
All this PR does is:
1. Introduce `RuntimeStatus` and `ResoruceStatus`
2. Refactor tests to use the appropriate types
=> web: disambiguate k8s status from Tilt status

Gopkg.lock, Gopkg.toml, vendor/github.com/gdamore/tcell/.travis.yml, vendor/github.com/gdamore/tcell/README.adoc, vendor/github.com/gdamore/tcell/cell.go, vendor/github.com/gdamore/tcell/console_win.go, vendor/github.com/gdamore/tcell/go.mod, vendor/github.com/gdamore/tcell/go.sum, vendor/github.com/gdamore/tcell/screen.go, vendor/github.com/gdamore/tcell/terminfo/dynamic/dynamic.go, vendor/github.com/gdamore/tcell/terminfo/mkinfo.go, vendor/github.com/gdamore/tcell/terminfo/terminfo.go, vendor/github.com/gdamore/tcell/tscreen.go
This picks up a fix for #1728 from tcell.
Tested by:
export GOPATH=/tmp
export TERM=xterm-color
before the upgrade, this repro'd the error in #1728 
after the upgrade, tilt ran fine
=> vendor: bump tcell

internal/model/orchestrator.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/microk8s:
2e1b0a8fc8a4639c85be23881e09ed23b06da32b (2019-06-21 12:10:38 -0400)
tiltfile: track the current orchestator, so that we can run integration tests on microk8s
=> tiltfile: track the current orchestator, so that we can run integration tests on microk8s

internal/dockercompose/client.go, internal/tiltfile/files.go
Please review the following commits I made in branch nicks/live:
10827f3eef6b5f66c4855b0b80fac46abc9f20d6 (2019-06-21 11:23:45 -0400)
improve some error messages to remove redundant quoting
=> improve some error messages to remove redundant quoting

internal/cli/wire.go, internal/cli/wire_gen.go, internal/docker/client.go, internal/docker/fake_client.go, internal/docker/switch.go, internal/docker/wire.go, internal/engine/configs_controller.go, internal/engine/configs_controller_test.go, internal/engine/upper_test.go, internal/tiltfile/tiltfile.go
Please review the following commits I made in branch nicks/minikube:
f32c3ee39e5b166656e6bb56d3a73675d2fd4939 (2019-06-24 12:12:36 -0400)
docker: dynamically switch between the local docker daemon and the in-cluster daemon
fixes docker-compose integration tests on minikube
=> docker: dynamically switch between the local docker daemon and the in-cluster daemon

integration/access.yaml, integration/k8s_fixture_test.go, integration/service-account.yaml
Please review the following commits I made in branch nicks/minikubewatch:
3d49718c2e3d64fde6d686713f04a82c63a28ada (2019-06-21 19:29:12 -0400)
improve rbac integration tests
=> improve rbac integration tests

internal/build/container_updater.go, internal/build/image_builder.go, internal/build/tar.go, internal/engine/synclet_build_and_deployer.go
This will make it easier to refactor ArchiveBuilder to not use a
`bytes.Buffer` in the future, which should help address #1753.
=> build: change ArchiveBuilder to return io.Reader

internal/git/gitignore.go, internal/git/gitignore_test.go
Files beginning with `.git` were being excluded (for example `.gitlab-ci.yml`) when tarring files for image building.
(Failed build is un-related to PR)
=> fix bug in file filtering for .git directory

.circleci/Dockerfile.integration, .circleci/config.yml
Please review the following commits I made in branch nicks/kind3:
d4a708a37501b94f42003271beaa7d2d71040437 (2019-06-25 18:51:51 -0400)
integration: run tests on Kind
Should make the tests faster and more robust, because
we no longer need to push to a remote registry
eac18bf14334d01fcc760c8d32ffa7aeba1741d6 (2019-06-25 18:51:51 -0400)
integration: all tests pass on containerd/KIND
- we can delete live_update_test.go, because now it's just a duplicate of onewatch
- live_update_base_image needed the busybox tar workaround
=> integration: run tests on Kind

.circleci/Dockerfile.integration, .circleci/config.yml
Noticed some things when looking at a PR that was already merged, that probably won't really matter much, but figured I'd get them while they were on my mind.
1. curl should pretty much always have `-f`/`--fail`, otherwise 4XX/5XX will still result in exit code 0
2. when we have `--silent` (`-s`), we pretty much always want `--show-error` (`-S`) (otherwise, it won't even print when the command fails!
3. pipefail for pipes
baaaaaaaaash
=> ci: misc bash fixes

integration/live_update_base_image/app/Dockerfile, integration/onewatch_exec/Dockerfile, internal/engine/synclet_build_and_deployer.go
Please review the following commits I made in branch nicks/tarballs2:
dfa81af83362ddabb0465e48499ad24a9edca99b (2019-06-27 15:36:04 -0700)
engine: fix exec syncing on busybox
Fixes https://github.com/windmilleng/tilt/issues/1611
=> engine: fix exec syncing on busybox

internal/engine/upper_test.go
I think this is more distracting than useful now that upper test deadlocks are relatively rare.
=> upper tests: don't dump stacks on timeout

integration/onewatch/start.sh, integration/start.sh
1. we want `"$@"` instead of `$*` to ensure that we run the command with the same quotes as the original command
2. while I was testing that, it turned out that killing the script didn't kill the underlying process, which might not matter for k8s purposes, but is nice to do for local testing
=> start.sh: fix quoting, kill underlying process on exit

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/k8s/image.go, internal/k8s/image_test.go, internal/k8s/testyaml/testyaml.go, internal/model/docker_info.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
This fixes #1793 
#1603 made it configurable whether we match images in env vars for the purposes of workload assembly, but the backend still always injected in any env vars it found.
Store match_in_env_vars into the ImageTarget when parsing the Tiltfile, and only inject images into env vars when that value is set for a given target.
=> engine: only inject images into env vars when that image so configured

internal/cli/down.go, internal/dockercompose/client.go, internal/dockercompose/fake_client.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/docker_compose_event_watcher.go, internal/engine/docker_compose_log_manager.go, internal/engine/upper_test.go, internal/hud/renderer_test.go, internal/hud/view/view.go, internal/hud/webview/convert.go, internal/hud/webview/view.go, internal/model/deploy_info.go, internal/model/manifest_test.go, internal/store/engine_state.go, internal/tiltfile/docker_compose.go, internal/tiltfile/docker_compose_test.go, internal/tiltfile/files.go, internal/tiltfile/k8s.go, internal/tiltfile/text_test.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
As a response to  #1782 the docker_compose() function on the tiltfile should support multiple files.  
i.e: 
`docker_compose(["docker-compose1.yml", "docker-compose2.yml"]`
=> bug: Docker compose supporting multiple files

internal/engine/actions.go, internal/engine/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/feature/flags.go, internal/feature/flags_test.go, internal/store/engine_state.go, internal/tiltfile/tiltfile.go
This is so OnChange events will be called when feature flags change.
There might be a better way to do this. I'm all ears!
=> engine: store feature flags on engine state

internal/build/image_builder.go, internal/docker/fake_client.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/target_queue.go, internal/engine/target_queue_test.go, internal/engine/upper_test.go, internal/testutils/tar.go
This fixes #1768
When Tilt decides whether an image needs to build, it basically just checks whether it knows the id of a previous build that hasn't been invalidated. This only works on the assumption that it's a closed system. In reality, kubelet can come in and delete images to free up disk space, or the user could have manually deleted the image, or whatever. This leads to a build error when we try to use a ref that no longer exists.
When determining whether to build an image, check both whether we have an image id and whether that id points at an image that still exists.
=> engine: check if images still exist when deciding whether to build

internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
This fixes #1805
When Tilt creates workloads, it does so by looking for any k8s entities that either 1) have a ContainerSpec or 2) have an image specified by a k8s_kind image_json_path.
This leaves no mechanism by which a user can specify a CRD via k8s_kind that should be a workload, but has no image that should be built by Tilt. This is relevant for, e.g., Fission and Prometheus.
Allow `k8s_kind` to be called with 0 args, in which case we take it to mean "anything of this kind is a workload".
I made a Tiltfile that runs a fission CRD and didn't give it any information about images, and it successfully created a resource and watched the pods specified by extra_pod_selectors.
=> tiltfile: allow k8s_kind with no images

internal/cli/klog.go
informers annoyingly log spurious warnings, e.g.:
`github.com/windmilleng/tilt/internal/k8s/watch.go:105: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.`
I've seen these warnings pop up a number of times, and there's not really anything useful for a user to do in response to them.
If you google "resourceVersion for the provided watch is too old", you get a bunch of people asking what these mean and wondering why it's all over their logs, and all the answers I've seen have been "oh that doesn't matter, just ignore it".
When I've observed this warning in Tilt, I've seen no indication it's actually caused a problem, and I've still seen events.
This is a warning that happens at the watch level, but we're using the informer api on top of it, which handles …
=> klog: hide reflector.go warnings

internal/engine/synclet_build_and_deployer.go
Please review the following commits I made in branch maiamcc/better-err-msg-no-restart:
66b24c26f06910f8187b4b3c8d98ab9b78742e10 (2019-07-08 17:32:40 -0400)
engine: better err message if restart_container step not supported [ch2865]
=> engine: better err message if restart_container step not supported [ch2865]

internal/engine/image_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/testdata_test.go, internal/k8s/image.go, internal/k8s/testyaml/testyaml.go, internal/model/docker_info.go
For "user can override image entrypoint" (note that this is only the backend changes -- tiltfile changes to follow)
=> engine/k8s: ibad can inject OverrideCommand into k8s yaml [ch2886]

internal/dockerignore/ignore_test.go, internal/ignore/path_matcher.go, internal/model/matcher.go
Please review the following commits I made in branch nicks/matcher:
e37e5500ec9dfef64a17ed00718aa8a7cc294738 (2019-07-10 17:30:36 -0400)
model: remove a bunch of dead PathMatcher code
=> model: remove a bunch of dead PathMatcher code

internal/engine/fake_notify_test.go, internal/engine/upper.go, internal/engine/watchmanager.go, internal/watch/notify.go, internal/watch/notify_test.go, internal/watch/watcher_darwin.go, internal/watch/watcher_naive.go
Please review the following commits I made in branch nicks/watchapi:
5f5ac9d41d7258670ea7553b0f6d0bdf20609cc6 (2019-07-10 18:42:12 -0400)
watch: change the watcher interface to better match how we actually use it
=> watch: change the watcher interface to better match how we actually use it

internal/build/path_mapping.go, internal/build/tar.go, internal/dockerignore/ignore.go, internal/dockerignore/ignore_test.go, internal/engine/watchmanager.go, internal/git/gitignore.go, internal/git/gitignore_test.go, internal/ignore/path_matcher.go, internal/model/matcher.go, internal/model/matcher_test.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/matches:
62514ba62b8455b8fc37e66e5d88ccc1403428e2 (2019-07-11 11:44:51 -0400)
model: remove the isDir arg from PathMatcher
=> model: remove the isDir arg from PathMatcher

internal/tiltfile/docker.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Hello @landism, @nicks, @mariabelenvivanco,
Please review the following commits I made in branch maiamcc/tiltfile-override-entrypoint:
7f8a4527c3f97b522e35b7566f0c6d71babfab2d (2019-07-10 17:18:09 -0400)
rename a fastBuild-related field to free up better names
29bc4349a2f670a6635d702e36828307caa0d80e (2019-07-10 17:16:15 -0400)
tests
79181b35f8e53117620beaa4aa1f5239a69d1b44 (2019-07-10 17:16:01 -0400)
tiltfile: add 'entrypoint' opt arg to docker_build and custom_build, translate into image target
=> tiltfile: add 'entrypoint' opt arg to docker_build and custom_build, translate into image target [ch2886]

cmd/buildkitapi/main.go, internal/build/cache_builder.go, internal/build/container_updater.go, internal/build/image_builder.go, internal/build/tar.go, internal/build/tar_test.go, internal/engine/synclet_build_and_deployer.go
The basic strategy is to have the tar archiver be responsible only for _writing_ to a `io.Writer`. Whenever we call the tar archiver we need to either
1. pass in a byte buffer and [deal with it](https://gph.is/1lDpHWH)
2. wire up an `io.Pipe`, pass the writer end in to the archiver and pass the reader end to Docker
This makes the tar package API truly gross, IMO. But that's a problem for a separate PR.
Memory allocations during tar before:
```
(pprof) top
Showing nodes accounting for 1.11GB, 99.72% of 1.11GB total
Dropped 42 nodes (cum <= 0.01GB)
Showing top 10 nodes out of 20
flat  flat%   sum%        cum   cum%
1.11GB 99.72% 99.72%     1.11GB 99.72%  bytes.makeSlice
0     0% 99.72%     1.11GB 99.72%  archive/tar.(*Writer).Write
0     0% 99.72%     1.11GB 99.72% …
```
=> build: stream tar to docker

internal/git/gitignore.go, internal/git/gitignore_test.go, internal/ignore/path_matcher.go
Please review the following commits I made in branch nicks/gitignore:
654066c8d25b969cb473ca8481413715d887a9e6 (2019-07-11 18:35:25 -0400)
git: remove another pathmatcher implementation
=> git: remove another pathmatcher implementation

internal/hud/hud.go
there was no unit test for this, but I did run tilt and confirm that hitting enter on the yaml resource gets me the log in the web ui
=> hud: allow enter on yaml resource

internal/engine/buildcontroller_test.go, internal/engine/fake_notify_test.go, internal/engine/upper_test.go, internal/engine/watchmanager.go, internal/engine/watchmanager_test.go, internal/ospath/ospath.go, internal/watch/notify.go, internal/watch/notify_test.go, internal/watch/watcher_darwin.go, internal/watch/watcher_naive.go
Please review the following commits I made in branch nicks/fileevent:
5ed8139440f7b8b6cc1bd2eeee82ab20d61ae1f2 (2019-07-11 20:05:40 -0400)
watch: FileEvents must always be absolute
there were a lot of confused tests that were using relative paths, then trying to workaround this
=> watch: FileEvents must always be absolute

internal/engine/watchmanager.go, internal/ignore/path_matcher.go, internal/model/matcher.go
Please review the following commits I made in branch nicks/exclusions2:
76ca868fb10da22135a768eab465f6446b19584f (2019-07-11 20:12:00 -0400)
engine: WatchManager should pass ignore filters to watch.Notify instead of doing filtering itself
5ed8139440f7b8b6cc1bd2eeee82ab20d61ae1f2 (2019-07-11 20:05:40 -0400)
watch: FileEvents must always be absolute
there were a lot of confused tests that were using relative paths, then trying to workaround this
=> engine: WatchManager should pass ignore filters to watch.Notify instead of doing filtering itself

internal/k8s/names.go, internal/k8s/names_test.go, internal/k8s/target.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/duplicate:
33d4bb143e0e7db76dd8e3ce6143afe563ecd4b5 (2019-07-15 10:21:19 -0400)
tiltfile: handle duplicate resources without erroring
fixes https://github.com/windmilleng/tilt/issues/1853
helps with https://github.com/windmilleng/tilt/issues/1852, until we find a better way to address this
=> tiltfile: handle duplicate resources without erroring

internal/tiltfile/features.go, internal/tiltfile/tiltfile_test.go
I realized that this will be annoying now that we are deleting our first
feature flag. Once someone started tilt on a project that checks an old
feature flag it would crash. This changes unknown feature flags to be
warnings in the Tiltfile instead of errors.
=> tiltfile: unknown feature flag checks are warnings

internal/dockerignore/ignore.go, internal/dockerignore/ignore_test.go, internal/watch/notify_test.go
Please review the following commits I made in branch nicks/exclusions3:
59bcf2b409861707988db8407524b17ddfb6a491 (2019-07-16 16:24:29 -0400)
dockerignore: improve MatchesEntireDir
=> dockerignore: improve MatchesEntireDir

internal/model/live_update.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/test-multiple-live-update-on-manifest:
077b6ffa5378772edb74120eb0f6521d0c0122ff (2019-07-16 17:56:12 -0400)
tiltfile: test for multiple LiveUpdates on one manifest [ch2901]
=> tiltfile: test for multiple LiveUpdates on one manifest [ch2901]

web/src/testdata.test.tsx, web/src/types.ts
1. We have code using `ResourceInfo.PodStatusMessage`, but that wasn't a field on that type (I'm not really sure why this wasn't an error).
2. Reorder the fields to match how they're defined in go, to make it easier to keep them the same.
This PR led me to wonder about #1869, but that's a problem for later.
=> web: update ts ResourceInfo to match go ResourceInfo

internal/cli/down_test.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/configs_controller.go, internal/engine/configs_controller_test.go, internal/engine/event_watch_manager.go, internal/engine/event_watch_manager_test.go, internal/engine/upper_test.go, internal/feature/flags.go, internal/feature/flags_test.go, internal/tiltfile/features.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
We want to remove feature flags.
If Alice and Bob are on adjacent Tilt versions where the latter removes the flag, Bob will want to remove the flag, but then Alice will lose the feature.
Allow marking a flag "noop" (it's set to a fixed-value, but Bob doesn't see anything), then "obsolete" (Bob sees an error, removes it, and Alice isn't affected), and then removing it (where setting a value would be an error)
=> internal/feature: noop and obsolete flags let us deprecate flags

internal/engine/upper.go, internal/model/log.go, internal/model/log_test.go
The main log sometimes ends up with gobbledygook that does not appear in the resource log, e.g.:
```
alert-inges…┊   WORKDIR /usr/src/app
alert-inges…┊ 
Ealert-inges…┊   COPY package.json ./
alert-inges…┊   COPY yarn.lock ./
alert-inges…┊ 
Ealert-inges…┊ 
EXPOSE 30alert-inges…┊ 
Ealert-inges…┊ 
EXPOSE 30alert-inges…┊ 
EXPOSE 3000
alert-inges…┊   CMD ["yarn", "start"]
alert-inges…┊ 
```
The bug lies in [log.Append](https://github.com/windmilleng/tilt/blob/a6d13f0bb25655c6179629669ba991b26f6924e0/internal/model/log.go#L120). We're appending to `prefix` and sticking it in `logLines`, which means if we're given a `prefix` with enough cap, we could end up reusing the same backing array for multiple lines. From playing around with a unit test, this seems to only repro when 1) multiple lines are …
=> log: fix appending multiple lines at once w/ prefix

integration/analytics/Tiltfile, integration/imagetags/Tiltfile, integration/live_update_base_image/Tiltfile, integration/oneup/Tiltfile, integration/oneup_custom/Tiltfile, integration/onewatch/Tiltfile, integration/onewatch_exec/Tiltfile, integration/shortlived_pods/Tiltfile
whatever sh-compatibility mode mac's `/bin/sh` uses doesn't support `-n` on its `echo` 🤷‍♂ 
```
$ sh -c 'echo -n hello'
-n hello
```
=> integration: fix namespace creation on macos

internal/engine/event_watch_manager_test.go
There was a race condition here - basically sometimes we'd perform the last `clock.Advance` before the janitor's loop got back to its next `<-clock.After`, so then the janitor would just block forever and the test would fail. This is the result of using a fake clock and not a real problem.
[`FakeClock.BlockUntil`](https://github.com/windmilleng/tilt/blob/52bc7aaf97d59c6ba74e11f7bb0834567b1c9ce2/vendor/github.com/jonboulle/clockwork/clockwork.go#L25) seems like an easy solution to this. I'd seen this method but wasn't really sure why it existed. Maybe this is why!
=> engine: fix flaky EventWatchManagerTest

internal/engine/upper_test.go
Please review the following commits I made in branch nicks/prefix:
2e0743bb7c2c103634662788593b6b979e1646ea (2019-07-18 20:50:42 -0400)
engine: Add a test for multi-line BuildLogAction
=> engine: Add a test for multi-line BuildLogAction

internal/docker/client.go, internal/docker/client_test.go
Please review the following commits I made in branch nicks/issue1892:
2d153b85b5344a19cceae4efeadc34e43a026917 (2019-07-23 11:39:09 -0400)
docker: even if DOCKER_BUILDKIT=1, don't use buildkit on platforms that don't support it
=> docker: even if DOCKER_BUILDKIT=1, don't use buildkit on platforms that don't support it

internal/engine/upper_test.go
This test occasionally failed with:
```
Error:      	Not equal:
expected: "Crash"
actual  : "Down"
```
basically, [here](https://github.com/windmilleng/tilt/blob/8c9e1aacab535e1e7f790a8264948f443aff7ce8/internal/engine/upper_test.go#L2217), we send the container through a bunch of states and then assert that the first non-empty state that exists is "Crash". This passes if all the engine processes all state transitions before the test first notices the state is non-empty, but occasionally fails when the test manages to inspect the state in the middle of the state transitions.
=> engine: fix flaky DC upper test

internal/engine/testdata/fixture_docker-config.yml, internal/engine/upper_test.go, internal/tiltfile/docker_compose.go
(because reproing a flaky DC upper test is really annoying when it takes 2 seconds)
=> engine: use fake DC client in upper tests

internal/build/test_utils.go, internal/cli/wire_gen.go, internal/docker/client.go, internal/docker/client_test.go, internal/docker/clients.go, internal/docker/env.go, internal/docker/wire.go, internal/engine/wire_gen.go, internal/synclet/wire_gen.go
Please review the following commits I made in branch nicks/issue1892:
1895acfc8eb21783d71b6a41cb4dca35d2966c3f (2019-07-24 12:23:55 -0400)
docker: fix minikube detection when DOCKER_HOST is already set to the minikube docker host. Fixes https://github.com/windmilleng/tilt/issues/1892
=> docker: fix minikube detection when DOCKER_HOST is already set to the minikube docker host. Fixes https://github.com/windmilleng/tilt/issues/1892

Gopkg.lock, internal/engine/pod.go, internal/engine/podlogmanager.go, internal/engine/podlogmanager_test.go, internal/engine/portforwardcontroller.go, internal/engine/portforwardcontroller_test.go, internal/engine/upper_test.go, internal/k8s/container.go, internal/store/build_result.go, internal/store/engine_state.go, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go
Currently when we populate a `*store.Pod`, we bless a single container and collect info on that container ([see code](https://github.com/windmilleng/tilt/blob/f159b30e7f20a923c96981c393aab0d447c145e4/internal/engine/upper.go#L599)).
First step to enabling us to LiveUpdate multiple containers is to have info for all (relevant) containers on the store.Pod.
This PR only changes structs/data storage -- all logic continues to use info from a single blessed container, to minimize the size of this change.
=> engine: internal representation of pod (store.pod) contains info on multiple containers [ch3006]

internal/build/container_test.go, internal/build/docker_benchmark_test.go, internal/build/docker_client_benchmark_test.go, internal/build/image_builder.go, internal/build/image_builder_test.go, internal/engine/build_and_deployer_test.go, internal/engine/image_and_cache_builder.go
Please review the following commits I made in branch nicks/imagebuild:
af0bfd16e440a7250a53124ec89ae19c7d24b7d7 (2019-07-25 14:32:01 -0400)
build: remove iterative image builds
This was only used in fast build. This was too finicky and not very successful.
Removing this allows us to simplify the state passed between builds.
=> build: remove iterative image builds

internal/engine/build_and_deployer_test.go, internal/engine/live_update_state_tree.go, internal/store/build_result.go
Please review the following commits I made in branch nicks/files:
52d0e6a03e222bf15ed3fa09bc96f1ac61735a74 (2019-07-25 17:57:20 -0400)
store: remove FilesReplacedSet
This was only necessary in a world where we had two incremental build strategies
(incremental image builds and container updates). Now that we only have
container updates, we can remove the code needed to reconcile them when files diverged
=> store: remove FilesReplacedSet

internal/engine/docker_compose_build_and_deployer.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_state_tree.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/build_result.go, internal/store/build_result_test.go
Hello @dbentley, @nicks,
Please review the following commits I made in branch maiamcc/build-result-multi-container:
a86e80e3a1bb62a42644c8378e8836e6d11b7b17 (2019-07-26 15:26:13 -0400)
store/engine: BuildResult can have multiple container IDs
=> store/engine: BuildResult can have multiple container IDs

internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/slice:
fc3a7ca55bdb9dd7f535225dfc35a2d3f7efeb8a (2019-07-26 19:40:49 -0400)
engine: don't create container id arrays with empty elements
=> engine: don't create container id arrays with empty elements

internal/engine/live_update_build_and_deployer.go, internal/engine/pod.go, internal/engine/portforwardcontroller.go
Hello @nicks, @dbentley,
Please review the following commits I made in branch maiamcc/fix-no-container-ports-spam:
bbe6e5397090628f20900071fafe59a26a3266a3 (2019-07-26 17:17:38 -0400)
engine: fix regression from #1908 that caused spam about 'no container ports' when trying to port fwd (tho port forwarding still worked)
=> engine: fix regression from #1908 that caused spam about 'no container ports' when trying to port fwd (tho port forwarding still worked)

internal/k8s/image.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
fixes #1918 
old output:
```
Starting Tilt (v0.9.3-dev, built 2019-07-24)…
Installing Tilt NodeJS dependencies…
Beginning Tiltfile execution
invalid reference format: repository name must be lowercase
Starting Tilt webpack server…
```
new output:
```
Starting Tilt (v0.9.3-dev, built 2019-07-26)…
Beginning Tiltfile execution
Installing Tilt NodeJS dependencies…
finding images in test-pod: parsing IMAGE_URL: invalid reference format:
repository name must be lowercase
Starting Tilt webpack server…
```
=> tiltfile: include entity and image name when failing to parse image names in k8s objects

internal/build/image_builder.go, internal/cli/wire.go, internal/cli/wire_gen.go, internal/feature/flags.go, internal/hud/server/server.go, internal/hud/server/server_test.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/hud/webview/view.go, internal/store/engine_state.go, internal/tft/client/client.go, internal/tft/client/fake_client.go, web/src/AlertPane.test.tsx, web/src/AlertPane.tsx, web/src/AppController.ts, web/src/HUD.tsx, web/src/__snapshots__/AlertPane.test.tsx.snap, web/src/alerts.test.ts, web/src/alerts.ts, web/src/feature.test.ts, web/src/feature.ts
Hidden under a feature flag
(Add `enable_feature("team_alerts")` to your Tiltfile to see this WIP feature)
We were using `titleMsg` and `header` for the little bit of additional meta text we send along with errors. I standardized to the latter.
=> Errors have button to get Alert URL

internal/build/error.go, internal/container/container.go, internal/containerupdate/synclet_updater.go, internal/engine/build_and_deployer_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/live_update_build_and_deployer_test.go, internal/store/build_result.go
Please review the following commits I made in branch maiamcc/run-step-failed:
dc78fa0d7c3a96b5b599969364bc6c7bb1e129a6 (2019-07-30 12:43:00 -0400)
store more info in RunStepFailed err
05dfd220b9837740a05397adea794031f650daff (2019-07-30 12:30:46 -0400)
rename UserBuildError -> RunStepError, add some helper funcs
=> build: RunStepError rename, store more info

internal/engine/build_and_deployer_live_update_test.go, internal/engine/build_and_deployer_test.go, internal/engine/buildcontroller_test.go, internal/engine/docker_compose_build_and_deployer.go, internal/engine/docker_compose_build_and_deployer_test.go, internal/engine/image_build_and_deployer_test.go, internal/engine/live_update_state_tree.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/build_result.go, internal/store/build_result_test.go, internal/store/engine_state.go
Please review the following commits I made in branch nicks/liveupdated:
8317fa5bd419ed57e824b718e5e1cf9f4e63de49 (2019-07-29 16:35:02 -0400)
store: Split LiveUpdate container ids from DockerCompose container ids
These should have always been separate fields, since they trigger very different
behavior. Now that multiple containers can be updated with live_update, but
docker compose can only bring up one container per service, it seems like a good
excuse to fix this.
=> store: Split LiveUpdate container ids from DockerCompose container ids

internal/build/container_test.go, internal/build/docker_benchmark_test.go, internal/build/docker_client_benchmark_test.go, internal/build/image_builder.go, internal/build/image_builder_test.go, internal/engine/image_and_cache_builder.go
Hello @nicks,
Please review the following commits I made in branch nicks/fastbuild3:
0d40a5a31eb8aab9467dad239d32673789e5e879 (2019-07-30 14:46:24 -0400)
build: adjust api to clarify what's part of deprecated fast_build
=> build: adjust api to clarify what's part of deprecated fast_build

internal/containerupdate/docker_container_updater_test.go, internal/docker/fake_client.go, internal/engine/build_and_deployer_test.go
Please review the following commits I made in branch maiamcc/fake-docker-cli-errors:
4f745428be5656f492eb719bb607bc69ab521d61 (2019-07-30 16:16:42 -0400)
docker/test: better error spoofing for fake docker client
=> docker/test: better error spoofing for fake docker client

internal/engine/build_and_deployer_live_update_test.go, internal/engine/testdata_test.go, internal/testutils/manifestbuilder/assemble.go, internal/testutils/manifestbuilder/manifestbuilder.go
Please review the following commits I made in branch maiamcc/live-upd-engine-tests-manifestbuilder:
63f80fa2dc6e41e46ddc3544593525cae3201aeb (2019-07-30 18:37:59 -0400)
engine/test: rewrite live update build and deploy tests with manifestbuilder for easier refactoring
=> engine/test: rewrite live update build and deploy tests with manifestbuilder for easier refactoring

internal/container/container.go, internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/testutils/podbuilder/podbuilder.go
Please review the following commits I made in branch nicks/podbuilder6:
6b9f39db6434f83ad7c32b59d5d383cc03f1242e (2019-07-30 18:49:10 -0400)
podbuilder: by default, use the image ref name from the YAML rather than making one up
=> podbuilder: by default, use the image ref name from the YAML rather than making one up

internal/container/container.go, internal/engine/buildcontroller_test.go, internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/k8s/testyaml/testyaml.go, internal/store/build_result.go, internal/store/engine_state.go, internal/testutils/podbuilder/podbuilder.go
Please review the following commits I made in branch nicks/ch2905/crashes:
5b59a49d352acf630b5fe7c23f0e294c9c8be8e6 (2019-07-31 12:14:03 -0400)
engine: Handle pod crashes when there are multiple containers
6b9f39db6434f83ad7c32b59d5d383cc03f1242e (2019-07-30 18:49:10 -0400)
podbuilder: by default, use the image ref name from the YAML rather than making one up
=> engine: Handle pod crashes when there are multiple containers

internal/engine/buildcontroller_test.go, internal/engine/upper_test.go
Please review the following commits I made in branch maiamcc/test-rename:
67ccd3351e4997f7f18bae279fb1e8326862f49e (2019-07-31 17:03:11 -0400)
engine test: rename some helper methods on buildAndDeployCall
=> engine test: rename some helper methods on buildAndDeployCall

integration/fixture_test.go, integration/k8s_fixture_test.go, integration/shortlived_pods/shortlived_pods.yaml
I was trying to fix the TestShortLivedPods flakiness failure `does not contain "this job will fail"`, but failed. I did find a few other minor issues while trying to debug that, but AFAIK none of them have actually been problems for anyone.
1. Our integration tests delete the `tilt-integration` namespace on startup. `kubectl` doesn't wait for namespace deletion to complete before returning, so this gave us a race condition where we could try to create objects in that namespace, and it'd fail with an error like "namespace is still deleting". So, we now block until deletion completes.
2. If a background tilt command fails, log it instead of silently ignoring.
3. Delete jobs when we're deleting deployments and services.
4. `backoffLimit: 4` on our failure job meant that we'd end up with 4 …
=> integration: misc fixes

internal/engine/version_checker.go, internal/engine/version_checker_test.go
I got github API rate limited while trying to repro a flaky integration test.
We don't show the version notification in the UI for dev builds anyway, so we might as well not call the API in the first place.
=> tilt: disable version check on dev builds

internal/engine/build_and_deployer.go, internal/engine/build_and_deployer_test.go, internal/engine/build_errors.go, internal/engine/buildcontroller_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/upper_test.go
if a user's Run step(s) fails, we don't fall back to an image build (b/c
presumably the same thing will fail on the image build)
however, any sync's have run successfully, which means
that state on the running container has diverged, and we need
to monitor it for crashes/do a crash rebuild if that container
disappears. that means that we need to get that container's ID
onto the manifest state, regardless of the fact that the
BuildAndDeploy call as a whole has failed.
=> if we touched containers in LiveUpdate, return/record touched container IDs even if the BuildAndDeploy call fails [ch3105]

internal/engine/buildcontroller.go, internal/engine/changed_file_list.go, internal/engine/changed_file_list_test.go, internal/engine/configs_controller.go, internal/engine/upper.go
If you change a file that causes the Tiltfile to reexecute, it doesn't appear anywhere in the log, so it can be pretty frustrating to figure out why the Tiltfile rebuilt
Make ConfigsController log changed files the same way that BuildController does.
(Maybe at some point in the future we want to merge these controllers? I haven't given it much thought.)
=> tiltfile: log changed files before tiltfile rebuild

.goreleaser.yml
Please review the following commits I made in branch nicks/windows2:
e86e0a1dceaf51480b9f7c203bffec53997a727b (2019-08-02 11:57:16 -0400)
goreleaser: add windows but mark it as alpha
=> goreleaser: add windows but mark it as alpha

integration/fixture_test.go, integration/k8s_fixture_test.go, integration/onewatch_test.go, internal/build/error.go, internal/containerupdate/exec_updater.go, internal/containerupdate/exec_updater_test.go, internal/containerupdate/synclet_updater.go, internal/k8s/fake_client.go
Please review the following commits I made in branch nicks/liveupdate:
9e16268684663664fdf5c3302a2bd6a415520873 (2019-08-02 13:14:18 -0400)
containerupdater: fix kubectl exec updater to handle RunStepFailure
=> containerupdater: fix kubectl exec updater to handle RunStepFailure

internal/engine/build_and_deployer_test.go, internal/engine/buildcontroller_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/live_update_state_tree.go, internal/store/build_result.go
Please review the following commits I made in branch maiamcc/live-update-multi-image:
04f913506b05d7ea143d32d3185905de89269620 (2019-08-02 11:08:45 -0400)
fix error handling & test
4fc089e00b408a8b2a5d8cbf26dd89dfed152f74 (2019-08-01 15:14:44 -0400)
wip
e11ff97109e1de79d72640f220e583a23940c49f (2019-08-01 14:37:59 -0400)
some tests
fbc8ac330bcfc9a1cd8044d74de435defb9d70e0 (2019-08-01 12:51:43 -0400)
another crash rebuild test
1a88d75dfc413bccdeab1f6284ce97e16d4b1ce8 (2019-08-01 12:30:35 -0400)
initial implementation of multi-image live update for same pod
5d4db2b9a8d0b9d9447b745b09ad9015158023b0 (2019-08-01 12:30:02 -0400)
Red test
* Code is easy to understand and conforms to …
=> engine: can LiveUpdate multiple images for same manifest [ch3005]

internal/engine/build_and_deployer_live_update_test.go, internal/engine/testdata_test.go
Main purpose of this PR was to have the LiveUpdate test runner take
runningContainersPerTarget so that we could instantiate and check
running containers for multiple different image targets (setting
us up for testing multiple image targets per manifest)
While I was here I tightened up some setup code
=> engine/test: tighten up  live update tests

internal/tiltfile/docker.go, internal/tiltfile/docker_compose.go, internal/tiltfile/files.go, internal/tiltfile/k8s.go, internal/tiltfile/live_update.go, internal/tiltfile/live_update_test.go, internal/tiltfile/tiltfile_state.go
Please review the following commits I made in branch nicks/starlark:
4d77b774900c2a224fd637e81fdf96f1dd389780 (2019-08-05 18:34:15 -0400)
tiltfile: only calculate absolute paths on a starlark thread
in preparation for multiple tiltfiles, where the current Tiltfile will change over time
=> tiltfile: only calculate absolute paths on a starlark thread

synclet/Dockerfile, synclet/Dockerfile.base
(idk if there's a golang image with gcc out of the box, we should probs
swap that in if it exists)
=> synclet: update synclet dockerfile--correct image references, gcc

internal/engine/live_update_build_and_deployer.go, internal/synclet/client_adapter.go
#1985 introduced a bug:
- synclet server sends a message on run step failure (includes FailedRunStep field and nothing else)
- client receives that reply, processes the FailedRunStep, and _keeps going_, resulting in a nil pointer error when we try to read `LogMessage` info from the reply
=> fix nil pointer in synclet when we send a FailedRunStep

internal/engine/image_build_and_deployer.go, internal/k8s/statefulset.go, internal/k8s/statefulset_test.go
Please review the following commits I made in branch nicks/issue1962:
b61cb42a3f41f8fcbd8b992b2cf4f9ed8ae042a1 (2019-08-06 18:29:11 -0400)
k8s: override PodManagementPolicy to Parallel on deploy. Fixes issue 1962
=> k8s: override PodManagementPolicy to Parallel on deploy. Fixes issue 1962

internal/build/tar.go, internal/containerupdate/fake_container_updater.go, internal/engine/live_update_build_and_deployer.go, internal/engine/live_update_build_and_deployer_test.go, internal/testutils/tar.go
Fixes observed bug:
- introduce syntax error to same_img
- first container fails to update with go build error (expected)
- second container updates successfully (i.e. runs `go build` w/o error),
and we fall back to image build b/c of "inconsistent state: one update
succeeded, one failed"
The second `go build` succeeded b/c we weren't correctly syncing the change with the
syntax error to the second container -- early return from `buildAndDeploy` meant that
we didn't appropriately tee the tar reader.
=> engine: tee archive correctly even when run step fails

internal/build/path_mapping.go, internal/build/path_mapping_test.go, internal/engine/build_and_deployer_live_update_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/live_update_state_tree.go, internal/store/build_result.go
If `a.txt` is in the docker ctx for both `appimg` and `sidecarimg`, and the docker_build for `appimg` syncs `a.txt` and sidecar does not, we’ll get a “file matches no syncs” error when making path mappings for sidecar and fall back to an image build.
after this PR, we do NOT fall back to image build: instead, we can see that only the app has changed files, and do a LiveUpdate for the app but not the sidecar
=> engine: handle case where changed file matches sync for one image target but not another [ch3116]

internal/engine/pod.go, internal/engine/upper_test.go
fixes #1862 
If a manifest loses its pod and doesn't get a new pod to replace it, we never remove that pod from its podset, so every time `PodLogController`'s `OnChange` gets called, it tries to watch the old pod and immediately fails and logs an error, resulting in spam.
Our normal mechanism for removing dead pods from a manifest's podset only kicks in when the podset has one more than one pod (which is normally the case because normally a pod gets deleted when a new pod gets created).
Delete pods from podset as soon as we see they've been deleted.
=> pod watch: delete dead pods

.circleci/config.yml
c36d70861955faa4a18ad1a0e9f11834d2ae2fc4 (2019-08-07 16:40:26 -0400)
circleci: on macos, only run watch tests
=> circleci: on macos, only run watch tests

web/src/AppController.ts, web/src/HUD.scss, web/src/HUD.tsx, web/src/PathBuilder.test.tsx, web/src/PathBuilder.tsx
I couldn't really test this without some sort of working snapshot frontend server. I tested this by changing the URL that it loads from to `localhost:10350/api/view` manually.
=> web: can init from static HTTP response

internal/engine/live_update_build_and_deployer.go
Previously, LiveUpdating a manifest with two images, changing a file that synced to only one of the images, would get:
```
-> Updating container(s): abc123
-> Updating container(s):
```
(the second empty log line being from an empty LiveUpdInfo that we ran thru `buildAndDeploy`)
this PR fixes the typo in []liveUpdInfos initialization that caused us to run empties thru the deploy process
=> engine: don't run empty LiveUpdateInfos thru buildAndDeploy (eliminates log spam when LU-ing only one of multiple images)

internal/engine/build_and_deployer_live_update_test.go, internal/engine/live_update_build_and_deployer.go, internal/engine/live_update_state_tree.go, internal/model/target.go
this was causing a bug in the integration test I'm writing where I would
live update service 1, but the LU would return container IDs 1 and 2 as
changed containers (even tho we only touched container 1); when I killed
container 2 (running service 2), we did a crash rebuild, which we should NOT
have done b/c c2 hadn't been live updated, so we didn't lose any state when
it went down.
=> engine: don't return build results for images we didn't actually update

internal/tiltfile/docker.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch nicks/issue1982:
3556c4a73fd71d5057f4a9912d2e102d3cc9d359 (2019-08-08 12:41:42 -0400)
tiltfile: emit an error when 'only' contains a file glob. Fixes issue 1982
=> tiltfile: emit an error when 'only' contains a file glob. Fixes issue 1982

integration/Tiltfile, integration/analytics/Tiltfile, integration/imagetags/Tiltfile, integration/live_update_base_image/Tiltfile, integration/oneup/Tiltfile, integration/oneup_custom/Tiltfile, integration/onewatch/Tiltfile, integration/onewatch_exec/Tiltfile, integration/same_img_multi_container/Tiltfile, integration/shortlived_pods/Tiltfile
Please review the following commits I made in branch nicks/load2:
5724fb870b78216e84f9fffcdda6e8b99932f5c2 (2019-08-08 17:41:10 -0400)
Use include() to reduce duplication in integration tests
=> Use include() to reduce duplication in integration tests

internal/k8s/kubectl_runner.go, internal/k8s/logging_kubectl_runner.go, internal/k8s/logging_kubectl_runner_test.go
Please review the following commits I made in branch nicks/fork3:
638258f99dd4041f3ae39b17d2b34ed4643c9f8d (2019-08-09 12:48:55 -0400)
k8s: use 'tilt kubectl apply' instead of 'kubectl apply'
=> k8s: use 'tilt kubectl apply' instead of 'kubectl apply'

internal/feature/flags.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
Please review the following commits I made in branch maiamcc/rm-multic-feature-flag:
a8b6458c0ff5369034474eef868e21c1a922237f (2019-08-12 15:37:56 -0400)
tiltfile: enable multiple live updates per manifest by default
=> tiltfile: enable multiple live updates per manifest by default [ch3185]

internal/analytics/utils.go, internal/cli/analytics.go, internal/engine/analytics_reporter.go, internal/engine/analytics_reporter_test.go, internal/engine/pod_watch_test.go, internal/k8s/target.go, internal/tiltfile/k8s.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go, pkg/model/k8s_target.go
Would love feedback on how to report these stats for best slice-ability.
This PR records info on:
- number of containers running each ref
- number of resources with mutli-container live update
=> tiltfile/engine: metrics for multi-container usage

internal/feature/flags.go
I hope you're sitting down for this one.
I've verified that dropping a `console.log(features.isEnabled("snapshots"))` in HUD.tsx reflects whether I've enabled the feature in my Tiltfile.
=> tilt: add feature flag for snapshots

internal/tiltfile/docker.go
Feel free to reject the date, or even the fact of setting a hard deadline,
but I would love for us to actually get fast_build out of our codebase.
This PR puts a deprecation deadline in the fast_build deprecation warning.
Come 9/12, we'd remove tiltfile support for `fast_build`, and remove FastBuild internally at our leisure.
=> tiltfile: fast build deprecation date

.goreleaser.yml
Please review the following commits I made in branch nicks/arch:
b4449387e127667671522badbf8cc592abc70529 (2019-08-13 11:35:11 -0400)
goreleaser: don't bother with i386 architectures
=> goreleaser: don't bother with i386 architectures

internal/engine/buildcontroller.go, internal/engine/changed_file_list.go, internal/engine/changed_file_list_test.go, internal/engine/configs_controller.go, internal/engine/upper.go, internal/engine/upper_test.go
#1969 was reverted because it logged "1 changed file: [Tiltfile]" on startup.
This is pretty much the same, but with that log message wrapped by the same `if !firstBuild` check we use in BuildController, and a unit test for what actually gets logged.
=> tiltfile: log changed files, take two

internal/engine/event_watch_manager.go, internal/engine/event_watch_manager_test.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go
Please review the following commits I made in branch nicks/k8sget:
1d0b0d30a7d207cc04517bb37f2de7855e45aa02 (2019-08-13 13:45:52 -0400)
k8s: change client.Get to use an ObjectReference
=> k8s: change client.Get to use an ObjectReference

integration/fixture_test.go
Please review the following commits I made in branch maiamcc/integ-verbose:
98c06fded29d9e3df07430d01353a0aaf611ab63 (2019-08-13 15:01:51 -0400)
enable verbose mode for tilt up integ tests (previously only printed output if test failed)
=> enable verbose mode for tilt up integ tests (previously only printed output if test failed)

internal/engine/actions.go, internal/engine/event_watch_manager.go, internal/k8s/client.go, internal/k8s/entity.go
Hello @nicks,
Please review the following commits I made in branch nicks/uid:
c7a8854d30c11e9eb96f9caaf1b2ff241668f457 (2019-08-13 15:52:18 -0400)
k8s: remove custom uid type. We don't need two uid types
=> k8s: remove custom uid type. We don't need two uid types

internal/engine/upper_test.go
In upper tests, we get to see pretty much none of the tilt log when a test fails. The log is really helpful! For example, I had a syntax error in a Tiltfile, and the failure manifested as "timed out waiting for snack to build".
In `TearDown`, if the test failed, print the full tilt log.
We could do it on success as well, but that might be spammy with `go test`
=> upper tests: print log on failure

internal/engine/buildcontroller.go, internal/engine/upper.go, internal/engine/upper_test.go
When we change a config file and it causes a manifest to rebuild, the log would just say, e.g. "rebuilding snack", without any indication why it was happening
log, e.g., "1 changed: [snack/Dockerfile]"
=> engine: log changed config files in manifest builds

internal/engine/event_watch_manager.go, internal/engine/event_watch_manager_test.go, internal/engine/pod_watch.go, internal/engine/pod_watch_test.go, internal/engine/upper_test.go, internal/k8s/client.go, internal/k8s/entity.go, internal/k8s/entity_test.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/names_test.go
Please review the following commits I made in branch nicks/entity:
1959f82b8f6ad23e67df8388ae5c034aba8235e6 (2019-08-14 10:57:20 -0400)
k8s: Allow GetByReference to return structured objects as well as unstructured ones
=> k8s: Allow GetByReference to return structured objects as well as unstructured ones

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/pod_watch.go, internal/engine/pod_watch_test.go, internal/engine/service_watch.go, internal/engine/service_watch_test.go, internal/engine/upper_test.go, internal/k8s/owner_fetcher.go, internal/k8s/owner_fetcher_test.go
Please review the following commits I made in branch nicks/ch3086/owners:
ff9035dba2a725227e7753afa15863400b397b5c (2019-08-14 11:48:11 -0400)
k8s: add an owner visitor that can traverse owner trees
=> k8s: add an owner visitor that can traverse owner trees

internal/tiltfile/docker.go, internal/tiltfile/docker_compose.go, internal/tiltfile/fail.go, internal/tiltfile/features.go, internal/tiltfile/files.go, internal/tiltfile/include.go, internal/tiltfile/k8s.go, internal/tiltfile/live_update.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
We already report stats on which tiltfile builtins are used, but sometimes individual args (e.g., `match_in_env_vars`, or `extra_pod_selectors`) can represent a decent amount of complexity to maintain and we can be unsure of their usage.
When we report stats on which builtins get used, also report which args get used.
Unfortunately, this relies on being diligent about using `tiltfileState.unpackArgs` instead of `starlark.UnpackArgs`, but I don't see an easy way to avoid that.
e.g.:
`tiltfile.invoked.docker_build.args.context`, or `tiltfile.invoked.k8s_resource.args.extra_pod_selectors`
=> tiltfile: record stats on arg usage

internal/engine/analytics_reporter.go
I pressed "merge" on my last PR and realized the next second that
I wasn't paying attention to context cancellation while waiting to
report for the first time (which i set to do 2min after start to give
the user's state at least some time to get up and running). I think this
is better?
=> analytics_reporter: watch for context.Done when doing our initial report

internal/engine/portforwardcontroller_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/portforward:
95aeffd0d028cf749c82d6626483bb66194a1901 (2019-08-20 14:12:48 -0400)
portforwardcontroller: add tests for auto-discovery
=> portforwardcontroller: add tests for auto-discovery

internal/hud/server/server.go
With this change someone working on Tilt locally can navigate to
http://localhost:10350/snapshot/aaaaaa and Tilt will make a request to
localhost:10350/api/snapshot/aaaaaa which will serialize the current
Tilt engine state in to the snapshot format that the frontend understands
and return it.
Tilt will bootstrap off of this HTTP request thus simulating snapshots.
This addresses only part of ch3234
=> hud/server: create snapshot HTTP bootstrap simulacrum

Makefile
I think #2014 made it so we're now hitting the integration test timeout, causing us to occasionally fail in master. At some point we might want to speed this up, but for now let's not waste our time investigating fake failures.
=> integration: bump timeout

internal/hud/server/server.go
creating snapshots was failing for me and the reason did not appear anywhere in the tilt log or js console
=> snapshots: log http errors

internal/engine/actions.go, internal/engine/image_build_and_deployer.go, internal/engine/pod.go, internal/engine/service_watch.go, internal/engine/service_watch_test.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/store/engine_state.go, internal/store/runtime_state.go, internal/testutils/servicebuilder/servicebuilder.go
Please review the following commits I made in branch nicks/uidexp:
3b43542b3dd4cf42c36ff9205d6da7b3e154cf40 (2019-08-22 13:13:54 -0400)
engine: make the ServiceWatcher responsible for mapping services to manifests
=> engine: make the ServiceWatcher responsible for mapping services to manifests

internal/cloud/url.go, internal/hud/server/server.go, internal/hud/webview/convert.go, internal/hud/webview/convert_test.go, internal/hud/webview/view.go, internal/tft/url.go, web/src/AppController.ts, web/src/HUD.tsx, web/src/ShareSnapshotModal.scss, web/src/ShareSnapshotModal.test.tsx, web/src/ShareSnapshotModal.tsx, web/src/TopBar.test.tsx, web/src/TopBar.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
It's pretty ugly, but:
After clicking "Share Snapshot":
Will probably need to rope @nicks in for some styling help 😅
=>  web: move share snapshot in to modal, show register token URL 

internal/engine/actions.go, internal/engine/buildcontroller_test.go, internal/engine/pod.go, internal/engine/pod_watch.go, internal/engine/pod_watch_test.go, internal/engine/service_watch.go, internal/engine/upper_test.go, internal/k8s/owner_fetcher.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/testutils/podbuilder/podbuilder.go
Please review the following commits I made in branch nicks/podwatch2:
b2a016e67a48327c5b76e244d8a03c3ecd79d620 (2019-08-23 11:56:12 -0400)
engine: categorize pods by manifest in pod_watch instead of in the reducer
=> engine: categorize pods by manifest in pod_watch instead of in the reducer

internal/engine/event_watch_manager.go, internal/engine/pod_watch.go, internal/engine/pod_watch_test.go, internal/engine/service_watch_test.go, internal/k8s/client.go, internal/k8s/entity.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/owner_fetcher.go, internal/k8s/owner_fetcher_test.go, internal/testutils/podbuilder/podbuilder.go
Please review the following commits I made in branch nicks/podwatch:
30334e83b6572cba08adf6ff55f986c3fc236f31 (2019-08-23 14:52:47 -0400)
engine: triage pods by owner UID rather than by manifest label
=> engine: triage pods by owner UID rather than by manifest label

web/src/HUD.tsx
The "snapshot shared by" message is not showing on snapshots in prod.
This is because this was tested in dev, which does not pass through `cleanSnapshotForPOST`, which disables the snapshots feature, which stops the username from displaying
Don't rely on the snapshots feature being enabled to determine whether to show the "snapshot shared by message.
We don't currently have a high-fidelity way to test snapshot JS without doing a release.
Tested by, in `AppController.setStateFromSnapshot`:
1. Changing url to "http://localhost/api/snapshot/aaaa"
2. When we get `data` back from the api call, setting `data = cleanSnapshotForPOST(data)`
3. Verifying by setting other properties in cleanSnapshotForPOST to verify that I was seeing a snapshot that had flowed through that function.
=> snapshot: fix display of username

internal/build/image_builder.go
Please review the following commits I made in branch nicks/issue1967:
51557f125f78251239e6c2ad9526da887ab2b497 (2019-09-03 11:28:41 -0400)
build: improve error message when docker did not return a digest
=> build: improve error message when docker did not return a digest

web/src/ShareSnapshotModal.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
This PR tells Tilt Cloud a callback to notify Tilt when token registration has completed
(the other half of https://github.com/windmilleng/tft/pull/16)
=> tilt: pass tilt callback to register_token

web/src/ShareSnapshotModal.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
This reverts commit 69d1589b61400e7b5cb7e67b73d2e407ea3651e8.
This didn't work in prod because can't have a callback to http from https.
=> Revert "tilt: pass tilt callback to register_token (#2143)"

internal/cloud/cloud_username_manager.go, internal/cloud/cloud_username_manager_test.go, internal/testutils/httptest/http_client.go
It turns out `u.Query()` is a read-only copy, so this never worked.
=> tilt: fix /api/whoami long_get

internal/k8s/container_test.go, internal/k8s/fake_test.go, internal/k8s/pod_test.go, internal/k8s/watch_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/ch3277/list:
9c0fab812bc002366ced4d4d41ba85964995d5a8 (2019-09-05 13:28:52 -0400)
k8s: assert that the watchers emit all existing resources at startup
=> k8s: assert that the watchers emit all existing resources at startup

internal/k8s/fake_client.go, internal/k8s/owner_fetcher.go, internal/k8s/owner_fetcher_test.go
Please review the following commits I made in branch nicks/owner:
9b9ce21d1139d2f87c52f3c18ac5ac09541deef1 (2019-09-05 18:02:55 -0400)
k8s: handle parallel fetch() calls better. This happens a lot with events
=> k8s: handle parallel fetch() calls better. This happens a lot with events

internal/engine/pod_watch.go, internal/engine/service_watch.go
Hello @nicks,
Please review the following commits I made in branch nicks/podwatch:
6424d7cb884c1c6c1adeca4bbbe3ce9283e203c2 (2019-09-05 18:53:16 -0400)
engine: the watchers should discard old objects before doing an object tree lookup
=> engine: the watchers should discard old objects before doing an object tree lookup

web/src/LogPane.tsx
Please review the following commits I made in branch nicks/issue2155:
954ed701226f4962e922cf18e929bbe9e72158ed (2019-09-05 19:27:54 -0400)
web: don't autoscroll when we're scrolled horizontally. Fixes issue #2155
=> web: don't autoscroll when we're scrolled horizontally. Fixes issue #2155

integration/k8s_fixture_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/kubeconfig:
79c52ea4208f9b31440d4ae78dcc34f26276c241 (2019-09-06 10:31:23 -0400)
integration: filepath.Base() can return '.'
=> integration: filepath.Base() can return '.'

integration/fixture_test.go, internal/cli/up.go
Please review the following commits I made in branch nicks/imagetagprefix:
bc4029cef3526c8833233c0ae856ae4df20f98de (2019-09-06 10:36:32 -0400)
integration: remove the image tag prefix. this was used inconsistently and is obsolete now
=> integration: remove the image tag prefix. this was used inconsistently and is obsolete now

internal/engine/event_watch_manager.go, internal/engine/event_watch_manager_test.go
Please review the following commits I made in branch nicks/watchers:
cb39f794b4465457fae16344d634c1f5f9c20edc (2019-09-06 12:41:39 -0400)
engine: fix redundant watches :grimace:
=> engine: fix redundant watches :grimace:

integration/fixture_test.go, integration/idempotent/Dockerfile, integration/idempotent/Tiltfile, integration/idempotent/deployment.yaml, integration/idempotent/index.html, integration/idempotent_test.go, integration/k8s_fixture_test.go, internal/engine/image_build_and_deployer.go, internal/k8s/labels.go
Please review the following commits I made in branch nicks/ch3278/runid:
045ef32abc6b8cd312c594084056885518779366 (2019-09-06 12:21:30 -0400)
k8s: Remove run IDs. Add tests to verify that running 'tilt up' twice attaches to the existing pod
=> k8s: Remove run IDs. Add tests to verify that running 'tilt up' twice attaches to the existing pod

internal/tiltfile/blob.go, internal/tiltfile/files.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_test.go, internal/tiltfile/value.go
Please review the following commits I made in branch nicks/issue2108:
2573c229ba7cb33a06631d31e4e356fbe56c1ce2 (2019-09-06 13:20:26 -0400)
tiltfile: build_args should deserialize blobs to strings
=> tiltfile: build_args should deserialize blobs to strings

internal/engine/pod.go, internal/engine/upper.go, internal/engine/upper_test.go, internal/hud/webview/convert.go, internal/store/engine_state.go, internal/store/runtime_state.go
Please review the following commits I made in branch nicks/ch3417/baseline:
4dc0b7b9d1e0d8f5cc3f0be1a2e8abaff08e6c2f (2019-09-10 11:51:35 -0400)
engine: record baseline restarts when we first see a pod
=> engine: record baseline restarts when we first see a pod

web/src/ShareSnapshotModal.tsx, web/src/__snapshots__/ShareSnapshotModal.test.tsx.snap
This attempts to address comments made on #2160.
It now looks like this:
=> tilt: adjust snapshot modal copy

internal/build/image_builder.go, internal/docker/client.go, internal/docker/fake_client.go, internal/docker/switch.go, internal/engine/image_build_and_deployer.go
Please review the following commits I made in branch nicks/docker:
92f830e71f31fbf06e4b302e1844d913cca180db (2019-09-11 14:47:55 -0400)
docker: rejigger the docker API a bit so that engine tests don't connect to the docker server for auth info
=> docker: rejigger the docker API a bit so that engine tests don't connect to the docker server for auth info

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/client.go, internal/k8s/watch.go, internal/k8s/watch_test.go
Hello @nicks,
5b97a2ca4ae614fbbe0a70726e766e5e188f826d (2019-09-13 14:15:08 -0400)
wire: rejigger how k8s client apis are injected
=> wire: rejigger how k8s client apis are injected

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/wire.go, internal/engine/wire_gen.go, internal/k8s/client.go, internal/k8s/client_test.go, internal/k8s/fake_client.go, internal/k8s/portforward.go
Hello @nicks,
Please review the following commits I made in branch nicks/wire2:
f4fbb05835a71d90f56cb63d7ccb46b29514dd08 (2019-09-13 14:26:00 -0400)
k8s: rewire the portforwarder into a separate PortForwardClient
5b97a2ca4ae614fbbe0a70726e766e5e188f826d (2019-09-13 14:15:08 -0400)
wire: rejigger how k8s client apis are injected
=> k8s: rewire the portforwarder into a separate PortForwardClient

internal/tiltfile/k8s.go, internal/tiltfile/tiltfile.go, internal/tiltfile/tiltfile_state.go, internal/tiltfile/tiltfile_test.go
This addresses #2194 
This approach has some downsides:
1. Using the output of `local` to decide how to call `allowed_k8s_contexts` will no longer work, but we have no evidence of users doing that.
2. If a user has a Tiltfile with `docker_compose` and `local`, ideally they'd be able to use it independent of their k8s state. However, if they have k8s installed and their config pointed at a non-local cluster, they'll now get an error. This is unfortunate, but is at least workaroundable, and gets the default common case back to something more safe.
=> tiltfile: also enforce allowed k8s contexts on `local` calls

internal/containerupdate/synclet_manager.go, internal/engine/portforwardcontroller.go, internal/engine/portforwardcontroller_test.go, internal/k8s/client.go, internal/k8s/exploding_client.go, internal/k8s/fake_client.go, internal/k8s/portforward.go
Please review the following commits I made in branch nicks/issue2099:
1b708ecd8b67a8c953bf3f26a108d36b0e9f4668 (2019-09-13 15:48:00 -0400)
engine: improve error handling and retry logic in portforwarding. Fixes #2099
=> engine: improve error handling and retry logic in portforwarding. Fixes #2099

internal/k8s/env.go, internal/k8s/env_test.go
Please review the following commits I made in branch nicks/none:
c30bc7f2cd4c8e9a633b36f433ec0a17dba82e2d (2019-09-17 12:55:59 -0400)
k8s: correctly identify when we have no k8s configs
=> k8s: correctly identify when we have no k8s configs

web/package.json
I'm not sure if I can point to a tangible benefit of this.
=> web: move test deps to devDependencies

internal/tiltfile/docker_compose.go, internal/tiltfile/tiltfile_docker_compose_test.go, internal/tiltfile/tiltfile_state.go
in re #2208:
- make dc_resource.image optional (because we CAN auto-associate)
- add tests for auto-associate vs explicit associate
- comments for missing behavior -- i.e. ability to override dc's
expected image with the one specified by the user
- groundwork for warning user when their specified image
won't be recognized by DC (WE can say that the image is
associated with that service, but `docker-compose up` still
looks for the image specified in `Image`, OR for an image
of name <directory>_<service>. If we don't support that yet,
we should at least warn users
=> tiltfile: dc_resource cleanup

internal/engine/live_update_build_and_deployer.go
```
──┤ Rebuilding: snapshot-frontend ├────────────────────────────────────────────
→ Updating container(s): 37b25b7498
Will delete 1 file(s) from container(s): 37b25b7498
- '/app/snapshot_frontend/create_dev_secrets.sh' (matched local path: '/Users/matt/go/src/github.com/windmilleng/tft/snapshot_frontend/create_dev_secrets.sh')
RUNNING: go install /app/snapshot_frontend
→ Container 37b25b74984a7f81aec99904043a63d19febae0afbd86c43375c715644cfb2e1 updated!
```
now the last line will use the short ID, like the first two times the container ID is referenced
=> engine: use short container id for 'updated' message

internal/dockercompose/config.go, internal/dockercompose/read.go, internal/engine/upper_test.go, internal/tiltfile/docker_compose.go
Please review the following commits I made in branch nicks/dc:
11af908036cee0006e66db183d5fd0093f434837 (2019-09-18 13:01:50 -0400)
dockercompose: move config yaml parsing into the dockercompose package
=> dockercompose: move config yaml parsing into the dockercompose package

pkg/model/log.go, pkg/model/log_test.go
Mitigates at least one case of #1935 
When a log exceeds the max buffer size, we remove old lines until we're under the limit. This often happens when a service is rapidly logging a lot of messages.
This has the effect that every time the server logs a new message, we shift the full log buffer. The log view in the web UI scrolls very quickly and it is difficult to read and pretty much impossible to copy/paste.
When a log exceeds the max buffer size, instead of truncating to be just under the limit, we truncate to be at half of the limit. This means instead of constantly (with every log message) scrolling the whole buffer a little, we more rarely (with every 60k written) scroll the buffer a whole lot. even if users are logging an extreme 1k/second, this will still give them a minute …
=> logs: slow down truncation frequency

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go
Please review the following commits I made in branch nicks/issue2210/order:
92f95f64a721e13cd855de220b4c7b85fb565020 (2019-09-19 17:07:12 -0400)
engine: respect the native docker-compose order. Fixes part of issue #2210
=> engine: respect the native docker-compose order. Fixes part of issue #2210

internal/engine/buildcontroller_test.go, internal/engine/upper_test.go, internal/engine/watchmanager.go, internal/store/engine_state.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/tiltfile_state.go, pkg/model/local_target.go
Please review the following commits I made in branch maiamcc/watch-deps:
377135ce50f2c6ea71c9e617dd1e5e2fe78eac2c (2019-09-20 16:21:19 -0400)
test
87afe195124738cfd19d3189798e4c51ac8cde19 (2019-09-20 16:00:32 -0400)
i think this works
=> engine: watch LocalResource.deps; changes recorded on manifest, trigger build [ch3473]

internal/cli/wire.go, internal/cli/wire_gen.go, internal/engine/actions.go, internal/engine/k8swatch/actions.go, internal/engine/k8swatch/event_watch_manager.go, internal/engine/k8swatch/event_watch_manager_test.go, internal/engine/k8swatch/pod_watch.go, internal/engine/k8swatch/pod_watch_test.go, internal/engine/k8swatch/service_watch.go, internal/engine/k8swatch/service_watch_test.go, internal/engine/k8swatch/watcher.go, internal/engine/pod.go, internal/engine/subscribers.go, internal/engine/upper.go, internal/engine/upper_test.go
Hello @nicks,
Please review the following commits I made in branch nicks/watchpackages:
dd509e8300a301907242d1bd997301b54d4b819e (2019-09-20 18:21:35 -0400)
engine: Move all the kubernetes watchers into their own package
=> engine: Move all the kubernetes watchers into their own package

internal/engine/buildcontroller.go, internal/engine/buildcontroller_test.go, internal/hud/webview/convert_test.go, internal/testutils/manifestbuilder/manifestbuilder.go, internal/tiltfile/tiltfile_state.go, pkg/model/local_target.go
Please review the following commits I made in branch maiamcc/local-resources-first:
4e6c71daa88b4be6b2b1b3e6077c7077a2c717fb (2019-09-20 17:17:14 -0400)
engine: build LocalResources before cluster resources (k8s / DC) [ch3474]
514116f1af406cd7602af28a626b7864304562f5 (2019-09-20 17:15:13 -0400)
model: LocalTarget.Name
=> engine: build LocalResources before cluster resources (k8s / DC) [ch3474]

internal/cloud/cloud_username_manager.go
no one wants to see this:
```
error checking tilt cloud status: &{500 Internal Server Error 500 HTTP/1.1 1 1 map[Content-Length:[22] Content-Type:[text/plain; charset=utf-8] Date:[Sun, 22 Sep 2019 20:00:32 GMT] X-Content-Type-Options:[nosniff] X-Rate-Limit-Duration:[1] X-Rate-Limit-Limit:[10.00] X-Rate-Limit-Request-Forwarded-For:[] X-Rate-Limit-Request-Remote-Addr:[127.0.0.1:44982]] 0xc000dda700 22 [] false false map[] 0xc0014fff00 <nil>
```
=> tilt cloud: don't log http.Response.String()
